#ifndef ONCE_HAL_MSTAR_PLATFORM_MONTAGE_IO_H
#define ONCE_HAL_MSTAR_PLATFORM_MONTAGE_IO_H

///////////////////////////////////////////////////////////////////////////////////////////////////
/// @file   pkgconf_platform_io.h
/// @author MStar Semiconductor Inc.
/// @brief  video application header file
///////////////////////////////////////////////////////////////////////////////////////////////////
#include <pkgconf_system.h>

/* MStar Montage IP Base Addresses Definitions */
/* RIU space */
#define HAL_MSTAR_RIU_BASE               0x1f800000
#define HAL_MSTAR_RIU_CLKGEN             (HAL_MSTAR_RIU_BASE + 0x00000)
#define HAL_MSTAR_RIU_RSTGEN             (HAL_MSTAR_RIU_BASE + 0x01000)
#define HAL_MSTAR_RIU_EMI0              (HAL_MSTAR_RIU_BASE + 0x02000)
#define HAL_MSTAR_RIU_EMI1              (HAL_MSTAR_RIU_BASE + 0x03000)
#define HAL_MSTAR_RIU_MIU0               (HAL_MSTAR_RIU_BASE + 0x04000)
#define HAL_MSTAR_RIU_PATTERN_GEN        (HAL_MSTAR_RIU_BASE + 0x05000)
#define HAL_MSTAR_RIU_MISC               (HAL_MSTAR_RIU_BASE + 0x06000)
#define HAL_MISC_RIU_MIU1                (HAL_MSTAR_RIU_BASE + 0x07000)
#define HAL_MISC_RIU_MINF                (HAL_MSTAR_RIU_BASE + 0x08000)
#define HAL_MSTAR_RIU_MPLL               (HAL_MSTAR_RIU_BASE + 0x09000)
#define HAL_MSTAR_RIU_DISPLAY            (HAL_MSTAR_RIU_BASE + 0x0a000)

#define HAL_MSTAR_RIU_INTC               (HAL_MSTAR_RIU_BASE + 0x0c000)
#define HAL_MSTAR_RIU_TIMER              (HAL_MSTAR_RIU_BASE + 0x0d000)
#define HAL_MSTAR_RIU_ISP                (HAL_MSTAR_RIU_BASE + 0x0e000)

#define HAL_MSTAR_RIU_ICP                (HAL_MSTAR_RIU_BASE + 0x10000)

#define HAL_MSTAR_RIU_JPEG_ENC           (HAL_MSTAR_RIU_BASE + 0x12000)
#define HAL_MSTAR_RIU_JPEG_DEC           (HAL_MSTAR_RIU_BASE + 0x13000)
#define HAL_MSTAR_RIU_HIF                (HAL_MSTAR_RIU_BASE + 0x14000)
#define HAL_MSTAR_RIU_BBINT              (HAL_MSTAR_RIU_BASE + 0x15000)
#define HAL_MSTAR_RIU_I2S                (HAL_MSTAR_RIU_BASE + 0x16000)

#define HAL_MSTAR_RIU_CARD_READER        (HAL_MSTAR_RIU_BASE + 0x18000)

#define HAL_MSTAR_RIU_USB_11             (HAL_MSTAR_RIU_BASE + 0x1a000)
#define HAL_MSTAR_RIU_DMA                (HAL_MSTAR_RIU_BASE + 0x1b000)
#define HAL_MSTAR_RIU_UART               (HAL_MSTAR_RIU_BASE + 0x1c000)
#define HAL_MSTAR_RIU_SSP                (HAL_MSTAR_RIU_BASE + 0x1d000)
#define HAL_MSTAR_RIU_SPI_DMA            (HAL_MSTAR_RIU_BASE + 0x1e000)
#define HAL_MSTAR_RIU_SPI_MASTER         (HAL_MSTAR_RIU_BASE + 0x1f000)
#define HAL_MSTAR_RIU_PWM                (HAL_MSTAR_RIU_BASE + 0x20000)
#define HAL_MSTAR_RIU_IIC_MASTER         (HAL_MSTAR_RIU_BASE + 0x21000)
#define HAL_MSTAR_RIU_IO_PAD_MUX         (HAL_MSTAR_RIU_BASE + 0x22000)
#define HAL_MSTAR_RIU_LBC                (HAL_MSTAR_RIU_BASE + 0x23000)
#define HAL_MSTAR_RIU_RIGEL              (HAL_MSTAR_RIU_BASE + 0x24000)
#define HAL_MSTAR_RIU_UART1              (HAL_MSTAR_RIU_BASE + 0x25000)
#define HAL_MSTAR_RIU_WD                 (HAL_MSTAR_RIU_BASE + 0x29000)

#define HAL_MSTAR_RIU_PCM                (HAL_MSTAR_RIU_BASE + 0x2b000)
#define HAL_MSTAR_RIU_FUART_DMA          (HAL_MSTAR_RIU_BASE + 0x39000)
#define HAL_MSTAR_RIU_FUART              (HAL_MSTAR_RIU_BASE + 0x3A000)

#define REG_OFF_SHIFT       2


/* EMI space */
#define HAL_MSTAR_EMI0_CFG              (HAL_MSTAR_RIU_EMI0 + (0x00 << REG_OFF_SHIFT))
#define HAL_MSTAR_EMI0_DMC              (HAL_MSTAR_RIU_EMI0 + (0x100 << REG_OFF_SHIFT))
#define HAL_MSTAR_EMI0_SMC              (HAL_MSTAR_RIU_EMI0 + (0x200 << REG_OFF_SHIFT))



/* Montage Timer */
#define HAL_MSTAR_TIMER_ENABLE_OFFSET        (0x00 * 4)
#define HAL_MSTAR_TIMER0_STARTCNT_OFFSET     (0x01 * 4)
#define HAL_MSTAR_TIMER0_PRECISION_OFFSET    (0x02 * 4)
#define HAL_MSTAR_TIMER1_STARTCNT_OFFSET     (0x03 * 4)
#define HAL_MSTAR_TIMER1_PRECISION_OFFSET    (0x04 * 4)
#define HAL_MSTAR_TIMER0_COUNT_VAL_OFFSET    (0x05 * 4)
#define HAL_MSTAR_TIMER0_PREC_VAL_OFFSET     (0x06 * 4)
#define HAL_MSTAR_TIMER1_COUNT_VAL_OFFSET    (0x07 * 4)
#define HAL_MSTAR_TIMER1_PREC_VAL_OFFSET     (0x08 * 4)
#define HAL_MSTAR_TIMER_INT_MASK_OFFSET      (0x09 * 4)
#define HAL_MSTAR_TIMER_INT_FORCE_OFFSET     (0x0a * 4)
#define HAL_MSTAR_TIMER_INT_CLEAR_OFFSET     (0x0b * 4)
#define HAL_MSTAR_TIMER_INT_RAW_OFFSET       (0x0c * 4)
#define HAL_MSTAR_TIMER_INT_FINAL_OFFSET     (0x0d * 4)
#define HAL_MSTAR_TIMER_INT_SW_RSTN_OFFSET   (0x0e * 4)


#define HAL_MSTAR_TIMER_BASE              HAL_MSTAR_RIU_TIMER
#define HAL_MSTAR_TIMER_ENABLE            (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_ENABLE_OFFSET    )
#define HAL_MSTAR_TIMER0_STARTCNT         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER0_STARTCNT_OFFSET )
#define HAL_MSTAR_TIMER0_PRECISION        (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER0_PRECISION_OFFSET)
#define HAL_MSTAR_TIMER1_STARTCNT         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER1_STARTCNT_OFFSET )
#define HAL_MSTAR_TIMER1_PRECISION        (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER1_PRECISION_OFFSET)
#define HAL_MSTAR_TIMER0_COUNT_VAL        (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER0_COUNT_VAL_OFFSET)
#define HAL_MSTAR_TIMER0_PREC_VAL         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER0_PREC_VAL_OFFSET )
#define HAL_MSTAR_TIMER1_COUNT_VAL        (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER1_COUNT_VAL_OFFSET)
#define HAL_MSTAR_TIMER1_PREC_VAL         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER1_PREC_VAL_OFFSET )
#define HAL_MSTAR_TIMER_INT_MASK          (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_MASK_OFFSET  )
#define HAL_MSTAR_TIMER_INT_FORCE         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_FORCE_OFFSET )
#define HAL_MSTAR_TIMER_INT_CLEAR         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_CLEAR_OFFSET )
#define HAL_MSTAR_TIMER_INT_RAW           (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_RAW_OFFSET   )
#define HAL_MSTAR_TIMER_INT_FINAL         (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_FINAL_OFFSET )
#define HAL_MSTAR_TIMER_SW_RSTN           (HAL_MSTAR_TIMER_BASE + HAL_MSTAR_TIMER_INT_SW_RSTN_OFFSET )

//WatchDog
#define HAL_MSTAR_WD_BASE                 HAL_MSTAR_RIU_WD
#define HAL_MSTAR_WD_ENABLE               (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_ENABLE_OFFSET    )
#define HAL_MSTAR_WD_TIMER0_STARTCNT      (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER0_STARTCNT_OFFSET )
#define HAL_MSTAR_WD_TIMER0_PRECISION     (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER0_PRECISION_OFFSET)
#define HAL_MSTAR_WD_TIMER1_STARTCNT      (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER1_STARTCNT_OFFSET )
#define HAL_MSTAR_WD_TIMER1_PRECISION     (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER1_PRECISION_OFFSET)
#define HAL_MSTAR_WD_TIMER0_COUNT_VAL     (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER0_COUNT_VAL_OFFSET)
#define HAL_MSTAR_WD_TIMER0_PREC_VAL      (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER0_PREC_VAL_OFFSET )
#define HAL_MSTAR_WD_TIMER1_COUNT_VAL     (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER1_COUNT_VAL_OFFSET)
#define HAL_MSTAR_WD_TIMER1_PREC_VAL      (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER1_PREC_VAL_OFFSET )
#define HAL_MSTAR_WD_INT_MASK             (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_MASK_OFFSET  )
#define HAL_MSTAR_WD_INT_FORCE            (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_FORCE_OFFSET )
#define HAL_MSTAR_WD_INT_CLEAR            (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_CLEAR_OFFSET )
#define HAL_MSTAR_WD_INT_RAW              (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_RAW_OFFSET   )
#define HAL_MSTAR_WD_INT_FINAL            (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_FINAL_OFFSET )
#define HAL_MSTAR_WD_SW_RSTN              (HAL_MSTAR_WD_BASE + HAL_MSTAR_TIMER_INT_SW_RSTN_OFFSET )

// Alias names
#define HAL_MSTAR_WATCHDOG_BASE            HAL_MSTAR_WD_BASE

//Watch Dog Timer Control Register
#define HAL_MSTAR_WATCHDOG_WD_CODE        (HAL_MSTAR_RIU_MISC+(0x64<<2))
#define HAL_MSTAR_WATCHDOG_WD_CONTROL     (HAL_MSTAR_RIU_MISC+(0x65<<2))
//Misc Spare
#define HAL_MSTAR_MISC_SPARE0             (HAL_MSTAR_RIU_MISC+(0x70<<2))
#define HAL_MSTAR_MISC_SPARE1             (HAL_MSTAR_RIU_MISC+(0x71<<2))
#define HAL_MSTAR_MISC_SPARE2             (HAL_MSTAR_RIU_MISC+(0x72<<2))
#define HAL_MSTAR_MISC_SPARE3             (HAL_MSTAR_RIU_MISC+(0x73<<2))
#define HAL_MSTAR_MISC_SPARE2_0           (HAL_MSTAR_RIU_MISC+(0xA4<<2))
#define HAL_MSTAR_MISC_SPARE2_1           (HAL_MSTAR_RIU_MISC+(0xA5<<2))
#define HAL_MSTAR_MISC_SPARE2_2           (HAL_MSTAR_RIU_MISC+(0xA6<<2))
#define HAL_MSTAR_MISC_SPARE2_3           (HAL_MSTAR_RIU_MISC+(0xA7<<2))
#define SPARE2_3_CHIPVER_SHIFT  12


/* DMA Source Control */
#define HAL_MSTAR_DMASRC_CTRL01           (HAL_MSTAR_RIU_MISC+(0x03<<2))

#ifdef  HWR_HAL_MIPS_MSTAR_PLATFORM_MONTAGE3
#define HAL_MSTAR_DMASRC_CTRL02           (HAL_MSTAR_RIU_MISC+(0x9F<<2))
#define HAL_MSTAR_MISC_M3_CHIPID          (HAL_MSTAR_RIU_MISC+(0xBB<<2))
#define CHIP_ID_BIT             0x00F0
#endif


/* MStar INTC */
#define HAL_MSTAR_INTC_FIQ_MASK_OFFSET             (0x00 *4)
#define HAL_MSTAR_INTC_FIQ_FORCE_OFFSET            (0x01 *4)
#define HAL_MSTAR_INTC_FIQ_CLEAR_OFFSET            (0x02 *4)
#define HAL_MSTAR_INTC_FIQ_RAW_STATUS_OFFSET       (0x03 *4)
#define HAL_MSTAR_INTC_FIQ_FINAL_STATUS_OFFSET     (0x04 *4)
#define HAL_MSTAR_INTC_IRQ_MASK_OFFSET             (0x10 *4)
#define HAL_MSTAR_INTC_IRQ_MASK_LO_OFFSET          (0x10 *4)
#define HAL_MSTAR_INTC_IRQ_MASK_HI_OFFSET          (0x11 *4)
#define HAL_MSTAR_INTC_IRQ_FORCE_OFFSET            (0x12 *4)
#define HAL_MSTAR_INTC_IRQ_FORCE_LO_OFFSET         (0x12 *4)
#define HAL_MSTAR_INTC_IRQ_FORCE_HI_OFFSET         (0x13 *4)
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS_OFFSET       (0x14 *4)
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS_LO_OFFSET    (0x14 *4)
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS_HI_OFFSET    (0x15 *4)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS_OFFSET     (0x16 *4)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS_LO_OFFSET  (0x16 *4)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS_HI_OFFSET  (0x17 *4)

#ifdef  HWR_M3_BIG2
#define HAL_MSTAR_INTC_IRQ_MASK2_OFFSET            (0x19 *4)
#define HAL_MSTAR_INTC_IRQ_FORCE2_OFFSET           (0x1A *4)
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS2_OFFSET      (0x1B *4)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS2_OFFSET    (0x1C *4)
#endif  // HWR_M3_BIG2

#define HAL_MSTAR_INTC_BASE                 HAL_MSTAR_RIU_INTC

#define HAL_MSTAR_INTC_FIQ_MASK             (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_FIQ_MASK_OFFSET           )
#define HAL_MSTAR_INTC_FIQ_FORCE            (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_FIQ_FORCE_OFFSET          )
#define HAL_MSTAR_INTC_FIQ_CLEAR            (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_FIQ_CLEAR_OFFSET          )
#define HAL_MSTAR_INTC_FIQ_RAW_STATUS       (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_FIQ_RAW_STATUS_OFFSET     )
#define HAL_MSTAR_INTC_FIQ_FINAL_STATUS     (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_FIQ_FINAL_STATUS_OFFSET   )
#define HAL_MSTAR_INTC_IRQ_MASK             (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_MASK_OFFSET           )
#define HAL_MSTAR_INTC_IRQ_MASK_LO          (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_MASK_LO_OFFSET        )
#define HAL_MSTAR_INTC_IRQ_MASK_HI          (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_MASK_HI_OFFSET        )
#define HAL_MSTAR_INTC_IRQ_FORCE            (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FORCE_OFFSET          )
#define HAL_MSTAR_INTC_IRQ_FORCE_LO         (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FORCE_LO_OFFSET       )
#define HAL_MSTAR_INTC_IRQ_FORCE_HI         (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FORCE_HI_OFFSET       )
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS       (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_RAW_STATUS_OFFSET     )
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS_LO    (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_RAW_STATUS_LO_OFFSET  )
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS_HI    (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_RAW_STATUS_HI_OFFSET  )
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS     (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FINAL_STATUS_OFFSET   )
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS_LO  (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FINAL_STATUS_LO_OFFSET)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS_HI  (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FINAL_STATUS_HI_OFFSET)

#ifdef  HWR_M3_BIG2
#define HAL_MSTAR_INTC_IRQ_MASK2            (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_MASK2_OFFSET        )
#define HAL_MSTAR_INTC_IRQ_FORCE2           (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FORCE2_OFFSET       )
#define HAL_MSTAR_INTC_IRQ_RAW_STATUS2      (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_RAW_STATUS2_OFFSET)
#define HAL_MSTAR_INTC_IRQ_FINAL_STATUS2    (HAL_MSTAR_INTC_BASE + HAL_MSTAR_INTC_IRQ_FINAL_STATUS2_OFFSET)
#endif  // HWR_M3_BIG2

//MIU request mask control
#define REG_RQ0_MASK    0xBF806020
#define REG_RQ1_MASK    0xBF806024

#define RESET_MASK_CTL_HIF      0x0000000C
#define RESET_MASK_CTL_I2S      0x00000030
#define RESET_MASK_CTL_SPIDMA   0x00000040
#define RESET_MASK_CTL_USB      0x00000180
#define RESET_MASK_CTL_DISP     0x80000600
#define RESET_MASK_CTL_CARD     0x00001800
#define RESET_MASK_CTL_JPE      0x00002000
#define RESET_MASK_CTL_LBC      0x00084000
#define RESET_MASK_CTL_JPD      0x20018000
#define RESET_MASK_CTL_DMA      0x00060002
#define RESET_MASK_CTL_SCL      0x00300000
#define RESET_MASK_CTL_ICP      0x00400000
#define RESET_MASK_CTL_CPU      0x01800000
#define RESET_MASK_CTL_NAND     0x18000000


/* MStar MINF */
#define HAL_MSTAR_MINF_BASE                 HAL_MISC_RIU_MINF
#define HAL_MSTAR_MINF_WR_FLUSH             (HAL_MSTAR_MINF_BASE + (0x01<<2))
#define HAL_MSTAR_MINF_RD_CLEAR             (HAL_MSTAR_MINF_BASE + (0x02<<2))


#ifdef  HWR_HAL_MIPS_MSTAR_PLATFORM_MONTAGE3
/* IO PAD MUX */
#define HAL_MSTAR_PADMUX_BASE               HAL_MSTAR_RIU_IO_PAD_MUX
#define HAL_MSTAR_PADMUX_FUNC_CTRL          (HAL_MSTAR_PADMUX_BASE + (0x19<<2))

#define PADMUX_JTAG_UART_EN     0x0001
#define PADMUX_USBOTG_EN        0x0002
#define PADMUX_RIGEL_SIF_EN     0x0004
#define PADMUX_UART_MUX_EN      0x0040
#endif

//-----------------------------------------------------------------------------
// end of platform_io.h
#endif // ONCE_HAL_MSTAR_PLATFORM_MONTAGE_IO_H
