#ifndef ONCE_PKGCONF_KERNEL_H
#define ONCE_PKGCONF_KERNEL_H
/*
 * File <pkgconf/kernel.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

/***** proc output start *****/
#ifndef NUM_HAL_RTC_NUMERATOR
# define NUM_HAL_RTC_NUMERATOR     1000000000
# define NUM_HAL_RTC_DENOMINATOR   100
# define NUM_HAL_RTC_PERIOD        9999
#endif
/*****  proc output end  *****/
#define PKG_KERNEL_INTERRUPTS 1
#define IMP_KERNEL_INTERRUPTS_DSRS 1
#define IMP_KERNEL_INTERRUPTS_DSRS_LIST 1
#define PKG_KERNEL_EXCEPTIONS 1
#define SEM_KERNEL_EXCEPTIONS_GLOBAL 1
#define PKG_KERNEL_SCHED 1
#define INT_KERNEL_SCHEDULER_UNIQUE_PRIORITIES 0
#define INT_KERNEL_SCHEDULER_UNIQUE_PRIORITIES_0
#define SEM_KERNEL_SCHED_MLQUEUE 1
#define PRI_KERNEL_SCHED_IMPL_HXX
#define NUM_KERNEL_SCHED_PRIORITIES 32
#define NUM_KERNEL_SCHED_PRIORITIES_32
#define NUM_KERNEL_SCHED_BITMAP_SIZE NUM_KERNEL_SCHED_PRIORITIES
#define NUM_KERNEL_SCHED_BITMAP_SIZE_NUM_KERNEL_SCHED_PRIORITIES
#define SEM_KERNEL_SCHED_TIMESLICE 1
#define NUM_KERNEL_SCHED_TIMESLICE_TICKS 5
#define NUM_KERNEL_SCHED_TIMESLICE_TICKS_5
#define PKG_KERNEL_COUNTERS 1
#define VAR_KERNEL_COUNTERS_CLOCK 1
#define NUM_KERNEL_COUNTERS_CLOCK_ISR_PRIORITY 1
#define NUM_KERNEL_COUNTERS_CLOCK_ISR_PRIORITY_1
#define IMP_KERNEL_COUNTERS_SINGLE_LIST 1
#define NUM_KERNEL_COUNTERS_RTC_RESOLUTION {NUM_HAL_RTC_NUMERATOR, NUM_HAL_RTC_DENOMINATOR}
#define NUM_KERNEL_COUNTERS_RTC_PERIOD NUM_HAL_RTC_PERIOD
#define NUM_KERNEL_COUNTERS_RTC_PERIOD_NUM_HAL_RTC_PERIOD
#define PKG_KERNEL_THREADS 1
#define FUN_KERNEL_THREADS_TIMER 1
#define VAR_KERNEL_THREADS_NAME 1
#define VAR_KERNEL_THREADS_LIST 1
#define FUN_KERNEL_THREADS_STACK_LIMIT 1
#define VAR_KERNEL_THREADS_DATA 1
#define NUM_KERNEL_THREADS_DATA_MAX 6
#define NUM_KERNEL_THREADS_DATA_MAX_6
#define NUM_KERNEL_THREADS_DATA_ALL 15
#define NUM_KERNEL_THREADS_DATA_ALL_15
#define NUM_KERNEL_THREADS_DATA_KERNEL 0
#define NUM_KERNEL_THREADS_DATA_KERNEL_0
#define NUM_KERNEL_THREADS_DATA_ITRON 1
#define NUM_KERNEL_THREADS_DATA_ITRON_1
#define NUM_KERNEL_THREADS_DATA_ERRNO 2
#define NUM_KERNEL_THREADS_DATA_ERRNO_2
#define NUM_KERNEL_THREADS_DATA_POSIX 3
#define NUM_KERNEL_THREADS_DATA_POSIX_3
#define NUM_KERNEL_THREADS_IDLE_STACK_SIZE 1536
#define NUM_KERNEL_THREADS_IDLE_STACK_SIZE_1536
#define NUM_KERNEL_MAX_SUSPEND_COUNT_ASSERT 500
#define NUM_KERNEL_MAX_SUSPEND_COUNT_ASSERT_500
#define NUM_KERNEL_MAX_COUNTED_WAKE_COUNT_ASSERT 500
#define NUM_KERNEL_MAX_COUNTED_WAKE_COUNT_ASSERT_500
#define PKG_KERNEL_SYNCH 1
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL SIMPLE
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_SIMPLE
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_INHERIT 1
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_CEILING 1
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DEFAULT_PRIORITY 0
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DEFAULT_PRIORITY_0
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_NONE 1
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DEFAULT INHERIT
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DEFAULT_INHERIT
#define SEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_DYNAMIC 1
#define INT_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_COUNT 3
#define INT_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_COUNT_3
#define MFN_KERNEL_SYNCH_MBOXT_PUT_CAN_WAIT 1
#define NUM_KERNEL_SYNCH_MBOX_QUEUE_SIZE 10
#define NUM_KERNEL_SYNCH_MBOX_QUEUE_SIZE_10
#define MFN_KERNEL_SYNCH_MUTEX_TIMED_WAIT 1
#define MFN_KERNEL_SYNCH_CONDVAR_TIMED_WAIT 1
#define MFN_KERNEL_SYNCH_CONDVAR_WAIT_MUTEX 1
#define PKG_KERNEL_DEBUG 1
#define DBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT 1
#define PKG_KERNEL_API 1
#define FUN_KERNEL_API_C 1
#define PKG_KERNEL_OPTIONS 1

#endif
