#ifndef ONCE_PKGCONF_SYSTEM_H
#define ONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define NUM_VERSION_CURRENT 0x7fffff00
#define PKG_HAL_MIPS v2_0_60
#define PKG_HAL_MIPS_v2_0_60
#define NUM_HAL_MIPS_VERSION_MAJOR 2
#define NUM_HAL_MIPS_VERSION_MINOR 0
#define NUM_HAL_MIPS_VERSION_RELEASE 60
#define PKG_HAL_MIPS_MIPS32 v2_0_60
#define PKG_HAL_MIPS_MIPS32_v2_0_60
#define NUM_HAL_MIPS_MIPS32_VERSION_MAJOR 2
#define NUM_HAL_MIPS_MIPS32_VERSION_MINOR 0
#define NUM_HAL_MIPS_MIPS32_VERSION_RELEASE 60
#define BLD_HAL_VARIANT_H   <pkgconf/hal_mips_mips32.h>
#define BLD_SDE_TOOLCHAIN 1
#define PKG_HAL_MIPS_MSTAR v2_0_60
#define PKG_HAL_MIPS_MSTAR_v2_0_60
#define NUM_HAL_MIPS_MSTAR_VERSION_MAJOR 2
#define NUM_HAL_MIPS_MSTAR_VERSION_MINOR 0
#define NUM_HAL_MIPS_MSTAR_VERSION_RELEASE 60
#define HWR_HAL_MIPS_MSTAR_PLATFORM_MONTAGE3 1
#define HWR_M3_BIG2 1
#define HWR_BIG2_TYPE_C 1
#define HWR_BOOT_ROMENTRY 1
#define BLD_HAL_TARGET_H <pkgconf/hal_mips_mips32.h>
#define BLD_HAL_PLATFORM_H <pkgconf/hal_mips_mstar.h>

/* Make sure we get the CORE type definitions for HAL_PLATFORM_CPU */
//#include BLD_HAL_TARGET_H
#define HAL_PLATFORM_BOARD    "MStar"
#define HAL_PLATFORM_EXTRA    ""

#if defined(HWR_HAL_MIPS_MIPS32_CORE_4Kc)
#  define HAL_PLATFORM_CPU    "MIPS32 4Kc"
#elif defined(HWR_HAL_MIPS_MIPS32_CORE_4KEc)
#  define HAL_PLATFORM_CPU    "MIPS32 4KEc"
#elif defined(HWR_HAL_MIPS_MIPS32_CORE_M4K)
#  define HAL_PLATFORM_CPU    "MIPS32 M4K"
#elif defined(HWR_HAL_MIPS_MIPS32_CORE_4Kp)
#  define HAL_PLATFORM_CPU    "MIPS32 4Kp"
#elif defined(HWR_HAL_MIPS_MIPS32_CORE_4Km)
#  define HAL_PLATFORM_CPU    "MIPS32 4Km"
#elif defined(HWR_HAL_MIPS_MIPS64_CORE_5K)
#  define HAL_PLATFORM_CPU    "MIPS64 5K"
#elif defined(HWR_HAL_MIPS_MIPS64_CORE_20K)
#  define HAL_PLATFORM_CPU    "MIPS64 20K"
#else
//#  error Unknown Core
#endif

#define EFAT_HAL_STARTUP ROM
#define EFAT_HAL_STARTUP_ROM
#define EFAT_HAL_STARTUP_CODE_CACHED 1
#define EFAT_HAL_STARTUP_DATA_CACHED 1
#define HWR_HAL_MIPS_MSTAR_ROM_PHY_ADDR 0x1FC00000
#define HWR_HAL_MIPS_MSTAR_ROM_PHY_ADDR_0x1FC00000
#define HWR_HAL_MIPS_MSTAR_ROM_SIZE 0x00119000
#define HWR_HAL_MIPS_MSTAR_ROM_SIZE_0x00119000
#define HWR_HAL_MIPS_MSTAR_RAM_PHY_ADDR 0x0
#define HWR_HAL_MIPS_MSTAR_RAM_PHY_ADDR_0x0
#define HWR_HAL_MIPS_MSTAR_RAM_SIZE 0x00023800
#define HWR_HAL_MIPS_MSTAR_RAM_SIZE_0x00023800
#define HWR_HAL_MIPS_MSTAR_SDRAM_PHY_ADDR 0x04080000
#define HWR_HAL_MIPS_MSTAR_SDRAM_PHY_ADDR_0x04080000
#define HWR_HAL_MIPS_MSTAR_SDRAM_SIZE 0x000C1800
#define HWR_HAL_MIPS_MSTAR_SDRAM_SIZE_0x000C1800
#define HWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_mips_mstar_romBoot.ldi>
#define HWR_MEMORY_LAYOUT_H <pkgconf/mlt_mips_mstar_sdram.h>
#define HWR_HAL_MIPS_MSTAR_CFGVARS_START 0xA0000600
#define HWR_HAL_MIPS_MSTAR_CFGVARS_START_0xA0000600
#define HWR_HAL_MIPS_MSTAR_CFGVARS_SIZE 0x00000640
#define HWR_HAL_MIPS_MSTAR_CFGVARS_SIZE_0x00000640
#define HWR_HAL_MIPS_MSTAR_SHARED_BUF_OVERLAY 1
#define HWR_HAL_MIPS_MSTAR_SDRAM_ENABLE 1
#define HWR_HAL_MIPS_MSTAR_DRAM_BOOT 1
#define HWR_HAL_MIPS_MSTAR_AUDIO_MODULE_SIZE 0x0
#define HWR_HAL_MIPS_MSTAR_AUDIO_MODULE_SIZE_0x0
#define PKG_HAL v2_0_60
#define PKG_HAL_v2_0_60
#define NUM_HAL_VERSION_MAJOR 2
#define NUM_HAL_VERSION_MINOR 0
#define NUM_HAL_VERSION_RELEASE 60
#define PKG_IO v2_0_60
#define PKG_IO_v2_0_60
#define NUM_IO_VERSION_MAJOR 2
#define NUM_IO_VERSION_MINOR 0
#define NUM_IO_VERSION_RELEASE 60
#define PKG_INFRA v2_0_60
#define PKG_INFRA_v2_0_60
#define NUM_INFRA_VERSION_MAJOR 2
#define NUM_INFRA_VERSION_MINOR 0
#define NUM_INFRA_VERSION_RELEASE 60
#define PKG_KERNEL v2_0_60
#define PKG_KERNEL_v2_0_60
#define NUM_KERNEL_VERSION_MAJOR 2
#define NUM_KERNEL_VERSION_MINOR 0
#define NUM_KERNEL_VERSION_RELEASE 60
#define PKG_ERROR v2_0_60
#define PKG_ERROR_v2_0_60
#define NUM_ERROR_VERSION_MAJOR 2
#define NUM_ERROR_VERSION_MINOR 0
#define NUM_ERROR_VERSION_RELEASE 60
#define PKG_ISOINFRA v2_0_60
#define PKG_ISOINFRA_v2_0_60
#define NUM_ISOINFRA_VERSION_MAJOR 2
#define NUM_ISOINFRA_VERSION_MINOR 0
#define NUM_ISOINFRA_VERSION_RELEASE 60
#define PKG_FS_FAT v2_0_60
#define PKG_FS_FAT_v2_0_60
#define NUM_FS_FAT_VERSION_MAJOR 2
#define NUM_FS_FAT_VERSION_MINOR 0
#define NUM_FS_FAT_VERSION_RELEASE 60
#define EFAT_FS_FAT_USE_CLUSTER_CHAIN 1
#define EFAT_DYNAMIC_MEMORY_MODE_CC 1
#define NUM_FS_FAT_FCLUSTER_POOL_SIZE 256
#define NUM_FS_FAT_FCLUSTER_POOL_SIZE_256
//#define FS_FAT_MERGE_CONTINUOUS_CLUSTERS 1
#define CFG_FS_FAST_GET_CAPACITY 1
#define PKG_LIBC_STRING v2_0_60
#define PKG_LIBC_STRING_v2_0_60
#define NUM_LIBC_STRING_VERSION_MAJOR 2
#define NUM_LIBC_STRING_VERSION_MINOR 0
#define NUM_LIBC_STRING_VERSION_RELEASE 60
#define PKG_IO_FILEIO v2_0_60
#define PKG_IO_FILEIO_v2_0_60
#define NUM_IO_FILEIO_VERSION_MAJOR 2
#define NUM_IO_FILEIO_VERSION_MINOR 0
#define NUM_IO_FILEIO_VERSION_RELEASE 60
//#define PKG_IO_FILEIO_UNICODE_SUPPORT 1
#define PKG_IO_DISK v2_0_60
#define PKG_IO_DISK_v2_0_60
#define NUM_IO_DISK_VERSION_MAJOR 2
#define NUM_IO_DISK_VERSION_MINOR 0
#define NUM_IO_DISK_VERSION_RELEASE 60
#define PKG_LINUX_COMPAT v2_0_60
#define PKG_LINUX_COMPAT_v2_0_60
#define NUM_LINUX_COMPAT_VERSION_MAJOR 2
#define NUM_LINUX_COMPAT_VERSION_MINOR 0
#define NUM_LINUX_COMPAT_VERSION_RELEASE 60
#define PKG_LIBC_I18N v2_0_60
#define PKG_LIBC_I18N_v2_0_60
#define NUM_LIBC_I18N_VERSION_MAJOR 2
#define NUM_LIBC_I18N_VERSION_MINOR 0
#define NUM_LIBC_I18N_VERSION_RELEASE 60
#define MONTAGE_APPLICATIONS current
#define MONTAGE_APPLICATIONS_current
#define MONTAGE_DRIVERS current
#define MONTAGE_DRIVERS_current
#define MONTAGE_BASIC_DRIVERS current
#define MONTAGE_BASIC_DRIVERS_current
#define MONTAGE_APP_AUDIO_DRIVER current
#define MONTAGE_APP_AUDIO_DRIVER_current
#define MONTAGE_APP_ICP_DRIVER current
#define MONTAGE_APP_ICP_DRIVER_current
#define MONTAGE_APP_HIF_DRIVER current
#define MONTAGE_APP_HIF_DRIVER_current
#define MONTAGE_APP_GEMINI_DRIVER current
#define MONTAGE_APP_GEMINI_DRIVER_current
#define MONTAGE_APP_SPI_DRIVER current
#define MONTAGE_APP_SPI_DRIVER_current
#define MONTAGE_APP_CHIPTOP_DRIVER current
#define MONTAGE_APP_CHIPTOP_DRIVER_current
#define MONTAGE_APP_DISP_DRIVER current
#define MONTAGE_APP_DISP_DRIVER_current
#define MONTAGE_APP_LCM_DRIVER current
#define MONTAGE_APP_LCM_DRIVER_current
#define MONTAGE_APP_FS_DRIVER current
#define MONTAGE_APP_FS_DRIVER_current
#define MONTAGE_APP_MIIC_DRIVER current
#define MONTAGE_APP_MIIC_DRIVER_current
#define MONTAGE_EXTRA_DRIVERS current
#define MONTAGE_EXTRA_DRIVERS_current
#define MONTAGE_APP_JPEGENC_DRIVER current
#define MONTAGE_APP_JPEGENC_DRIVER_current
#define MONTAGE_APP_JPEG_DRIVER current
#define MONTAGE_APP_JPEG_DRIVER_current
#define MONTAGE_APP_SENSOR_DRIVER current
#define MONTAGE_APP_SENSOR_DRIVER_current
#define MONTAGE_APP_H263ENC_DRIVER current
#define MONTAGE_APP_H263ENC_DRIVER_current
#define MONTAGE_APP_MP4DEC_DRIVER current
#define MONTAGE_APP_MP4DEC_DRIVER_current
#define PKG_DEVS_USB current
#define PKG_DEVS_USB_current
#define NUM_DEVS_USB_VERSION_MAJOR NUM_VERSION_CURRENT
#define NUM_DEVS_USB_VERSION_MINOR -1
#define NUM_DEVS_USB_VERSION_RELEASE -1
#define MONTAGE_BASIC_APPLICATIONS current
#define MONTAGE_BASIC_APPLICATIONS_current
#define MONTAGE_APP_SHELL current
#define MONTAGE_APP_SHELL_current
#define CFG_FS_DIRECT_WRITE_COMMAND_SET 1
#define CFG_BACKTRACE_SD 1
#define CFG_BACKTRACE_BUFFER_SIZE 1536
#define CFG_BACKTRACE_BUFFER_SIZE_1536
#define CFG_REDUCE_MEM_USAGE 1
#define CFG_WHOLE_PACKAGE 1
#define MONTAGE_APP_DISPLAY_SDRAM_FUNCTION current
#define MONTAGE_APP_DISPLAY_SDRAM_FUNCTION_current
#define MONTAGE_IMAGE_APPLICATIONS current
#define MONTAGE_IMAGE_APPLICATIONS_current
#define MONTAGE_APP_IMAGE_PLAYER current
#define MONTAGE_APP_IMAGE_PLAYER_current
#define MONTAGE_APP_PNGDEC_SDRAM_FUNCTION current
#define MONTAGE_APP_PNGDEC_SDRAM_FUNCTION_current
#define MONTAGE_APP_BITMAPDEC_SDRAM_FUNCTION current
#define MONTAGE_APP_BITMAPDEC_SDRAM_FUNCTION_current
#define MONTAGE_VIDEO_APPLICATIONS current
#define MONTAGE_VIDEO_APPLICATIONS_current
#define MONTAGE_APP_MP4PLAYER current
#define MONTAGE_APP_MP4PLAYER_current
#define CFG_MONTAGE_HW_PLAYER_ARCH 1
#define MONTAGE_APP_MP4MXDMX current
#define MONTAGE_APP_MP4MXDMX_current
#define MONTAGE_APP_MP4DEC current
#define MONTAGE_APP_MP4DEC_current
#define MONTAGE_APP_MP4REC current
#define MONTAGE_APP_MP4REC_current
#define MONTAGE_APP_H263DEC current
#define MONTAGE_APP_H263DEC_current
#define MONTAGE_APP_H264DEC current
#define MONTAGE_APP_H264DEC_current
#define MONTAGE_AUDIO_APPLICATIONS current
#define MONTAGE_AUDIO_APPLICATIONS_current
#define MONTAGE_APP_MP3PLAYER current
#define MONTAGE_APP_MP3PLAYER_current
#define MONTAGE_APP_AMRDEC current
#define MONTAGE_APP_AMRDEC_current
#define _ENABLE_AMRDEC_DTX_ 1
#define _ENABLE_AMRDEC_ALLMODE_ 1
#define MONTAGE_APP_AMRCOM current
#define MONTAGE_APP_AMRCOM_current
#define MONTAGE_APP_PCMSTREAM current
#define MONTAGE_APP_PCMSTREAM_current
#define MONTAGE_APP_SRCCONVERT current
#define MONTAGE_APP_SRCCONVERT_current
#define MONTAGE_APP_MIDI current
#define MONTAGE_APP_MIDI_current
#define MONTAGE_APP_MAPPLAYER current
#define MONTAGE_APP_MAPPLAYER_current
#define MONTAGE_APP_WAVDEC current
#define MONTAGE_APP_WAVDEC_current
#define MONTAGE_APP_AMRENC current
#define MONTAGE_APP_AMRENC_current
#define MONTAGE_APP_SBCENC current
#define MONTAGE_APP_SBCENC_current
#define MONTAGE_APP_SURROUND current
#define MONTAGE_APP_SURROUND_current
#define MONTAGE_APP_ID3PARSER current
#define MONTAGE_APP_ID3PARSER_current
#define MONTAGE_APP_LYRICS_SDRAM_FUNCTION current
#define MONTAGE_APP_LYRICS_SDRAM_FUNCTION_current
#define MONTAGE_SDRAM_FUNCTION current
#define MONTAGE_SDRAM_FUNCTION_current
#define MONTAGE_APP_PEQ current
#define MONTAGE_APP_PEQ_current
#define MONTAGE_APP_DRC_LIMITER current
#define MONTAGE_APP_DRC_LIMITER_current
#define PKG_DEVS_DISK_STORAGE v2_0_60
#define PKG_DEVS_DISK_STORAGE_v2_0_60
#define NUM_DEVS_DISK_STORAGE_VERSION_MAJOR 2
#define NUM_DEVS_DISK_STORAGE_VERSION_MINOR 0
#define NUM_DEVS_DISK_STORAGE_VERSION_RELEASE 60
#define MONTAGE_OS_LAYER_FUN_TABLE current
#define MONTAGE_OS_LAYER_FUN_TABLE_current
#define MONTAGE_APP_BIG2_DISP_DRIVER current
#define MONTAGE_APP_BIG2_DISP_DRIVER_current
#define PKG_LIBM v2_0_60
#define PKG_LIBM_v2_0_60
#define NUM_LIBM_VERSION_MAJOR 2
#define NUM_LIBM_VERSION_MINOR 0
#define NUM_LIBM_VERSION_RELEASE 60
#define MONTAGE_APP_AAC2 current
#define MONTAGE_APP_AAC2_current
#define MONTAGE_APP_EMULATOR current
#define MONTAGE_APP_EMULATOR_current
#define MONTAGE_APP_FM_RX_PLAYER current
#define MONTAGE_APP_FM_RX_PLAYER_current
#define MONTAGE_APP_FM_RX_DRIVER current
#define MONTAGE_APP_FM_RX_DRIVER_current
#define MONTAGE_APP_RVCDEC current
#define MONTAGE_APP_RVCDEC_current
#define MONTAGE_APP_DEMUXER current
#define MONTAGE_APP_DEMUXER_current
#define MONTAGE_APP_M4VE_DRIVER current
#define MONTAGE_APP_M4VE_DRIVER_current
#define MONTAGE_APP_GAINFADE current
#define MONTAGE_APP_GAINFADE_current
#define MONTAGE_APP_M4VD_DRIVER current
#define MONTAGE_APP_M4VD_DRIVER_current
#define PKG_IO_FILEIO_FILE_ID_SUPPORT
/* ++ Port V107MMP ++ */

#define ENABLE_CHECK_DISK  1// <-- defined
#define FS_USING_SB
#define PARTIAL_SYNC  1//<-- defined
/* -- Port V107MMP -- */


#endif
