/**
 * @file rtsp_event.h
 *
 * @brief This file defines the app state control related message parsers
 *
 */
#ifndef __RTSP_EVENT_H__
#define __RTSP_EVENT_H__


#define MAKE_RTSP_IN_MSG \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_OPEN_REQ, RtspProcessDownloadOpenReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_CLOSE_REQ, RtspProcessDownloadCloseReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_INIT_REQ, RtspProcessDownloadInitReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_UNINIT_REQ, RtspProcessDownloadUninitReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PLAY_REQ, RtspProcessDownloadPlayReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_STOP_REQ, RtspProcessDownloadStopReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PAUSE_REQ, RtspProcessDownloadPauseReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_RESUME_REQ, RtspProcessDownloadResumeReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_SEEK_REQ, RtspProcessDownloadSeekReq), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_DATA_RSP, RtspProcessDownloadDataRsp), \

#define MAKE_RTSP_OUT_MSG \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_OPEN_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_CLOSE_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_INIT_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_UNINIT_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PLAY_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_STOP_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PAUSE_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_RESUME_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_SEEK_RSP, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_OPEN_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_CLOSE_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_INIT_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_UNINIT_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PLAY_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_STOP_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_PAUSE_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_RESUME_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_SEEK_NTF, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_DATA_IND, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_DOWNLOAD_EOS_IND, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_NET_DISCONNECTED_IND, NULL), \
    RTSP_MAKE_ITEM(MS_RTSP_EVT_NET_CONNECTION_FAIL_IND, NULL),\
    RTSP_MAKE_ITEM(MS_RTSP_EVT_NET_OPERATION_FAIL_IND, NULL)


#define RTSP_MAKE_ITEM(_Msg, _Parser) _Msg##_IDX
enum{
    MAKE_RTSP_IN_MSG
    MAKE_RTSP_OUT_MSG
};

#undef RTSP_MAKE_ITEM
#define RTSP_MAKE_ITEM(_Msg, _Parser) _Msg = VM_RTSP_BASE + _Msg##_IDX
enum{
    MAKE_RTSP_IN_MSG
    MAKE_RTSP_OUT_MSG
};

typedef u32 Rtsp_Evt_Type_e;
typedef void (*RTSP_MSG_PARSER_FUNC_PTR)(vm_msg_t *pMessage);


#endif /* __RTSP_EVENT_H__ */

