#ifndef __MAE_LG_OTF_TYPES_H__
#define __MAE_LG_OTF_TYPES_H__

#ifdef __FEATURE_VECTOR_FONT__

enum
{
	LE_OTF_SCRIPT_DEVA = 0,
	LE_OTF_SCRIPT_BENG = 1,
	LE_OTF_SCRIPT_GUJR = 2,
	LE_OTF_SCRIPT_ORYA = 3,
	LE_OTF_SCRIPT_TAML = 4,
	LE_OTF_SCRIPT_TELU = 5,
	LE_OTF_SCRIPT_KNDA = 6,
	LE_OTF_SCRIPT_MLYM = 7,
	LE_OTF_SCRIPT_SINH = 8,
	LE_OTF_MAX_SCRIPT_NUM
};
typedef u8 LE_OTF_ScriptTag_e;

enum
{
	LE_OTF_FEATURE_LOCL = 0,
	LE_OTF_FEATURE_INIT = 1,
	LE_OTF_FEATURE_NUKT = 2,
	LE_OTF_FEATURE_AKHN = 3,
	LE_OTF_FEATURE_RPHF = 4,
	LE_OTF_FEATURE_BLWF = 5,
	LE_OTF_FEATURE_HALF = 6,
	LE_OTF_FEATURE_PSTF = 7,
	LE_OTF_FEATURE_VATU = 8,
	LE_OTF_FEATURE_PRES = 9,
	LE_OTF_FEATURE_BLWS = 10,
	LE_OTF_FEATURE_ABVS = 11,
	LE_OTF_FEATURE_PSTS = 12,
	LE_OTF_FEATURE_HALN = 13,
	LE_OTF_FEATURE_BLWM = 14,
	LE_OTF_FEATURE_ABVM = 15,
	LE_OTF_FEATURE_DIST = 16,
	LE_OTF_FEATURE_RKRF = 17,
	LE_OTF_FEATURE_CJCT = 18,
	LE_OTF_FEATURE_CALT = 19,
	LE_OTF_FEATURE_KERN = 20,
	LE_OTF_FEATURE_PREF = 21,
	LE_OTF_MAX_FEATURE_NUM
};
typedef u8 LE_OTF_FeatureTag_e;

typedef struct
{
    LE_OTF_FeatureTag_e eTag;
    u32 u32Mask;
} LE_OTF_FeatureRecord_t;

#endif //__FEATURE_VECTOR_FONT__
#endif //__MAE_LG_OTF_TYPES_H__
