#ifndef __MMI_EBOOKAPP_ID_H__
#define __MMI_EBOOKAPP_ID_H__
/* ouyang's code start */
#define BOOKMARK_MAX_NAME_CHARACTER		(16)
#define BOOKMARK_INPUT_MAX_SIZE			(2*BOOKMARK_MAX_NAME_CHARACTER)

#define BOOKMARK_NAME_HIGH		(64)
#define BOOKMARK_NAME_WIDTH		(240)
    /* ouyang's code end */

#define E_BOOK_FILE_LIST_HEIGHT   		(MAIN_DEFVIEW_HEIGHT-MAIN_LCD_ONELINE_HEIGHT)
#define E_BOOK_PROPORTION_FILE_LIST     (E_BOOK_FILE_LIST_HEIGHT/MAIN_LCD_ONELINE_HEIGHT-1)
#define E_BOOK_PROPORTION_FILE_TEXT     1
typedef enum
{
    E_BOOK_WND_FILELIST = WND_ID_APP_BASE,
    E_BOOK_WND_TEXTBROWSE,
    E_BOOK_WND_BOOKMARKLIST,
    E_BOOK_WND_BOOKMARKEDIT,
    E_BOOK_WND_OPTION,
    E_BOOK_WND_OPTION_FILELIST,
    E_BOOK_WND_OPTION_FILELISTZERO,
    E_BOOK_WND_OPTION_TEXTBROWSE,
    E_BOOK_WND_OPTION_BOOKMARK,
    E_BOOK_WND_OPTION_BOOKMARKEDIT,
    E_BOOK_WND_OPTION_GOTOLINE,
    E_BOOK_WND_FILEINFO,
    E_BOOK_WND_TEXTBROWSESETTING,
    E_BOOK_WND_TEXTBROWSESETTING_SCROLL,
    E_BOOK_WND_TEXTBROWSESETTING_LANG,
} EbookId_e;

enum
{
    TEXTBROWSE_SCROLLBARWDG=APP_WDG_START,
    TEXTBROWSE_TEXTWIDGET,
    TEXTBROWSE_FLIPWIDGET,
    TEXTBROWSE_INDICATOR,
    TEXTBROWSE_DECBOOKWIDGET,
    TEXTBROWSE_DECBOOKTOPWIDGET,
    TEXTBROWSE_DECBOOKBUTTONWIDGET,
    TEXTBROWSE_MAGNIFYWIDGET,
    TEXTBROWSE_PAGEINDEXWIDGET,
}EbookTextBrowseWdgList_e;

enum
{
    TEXTBROWSEFULL_SCROLLBARWDG=APP_WDG_START,
    TEXTBROWSEFULL_TEXTWIDGET,
    TEXTBROWSEFULL_FLIPWIDGET,
    TEXTBROWSEFULL_BMPWIDGET,
    TEXTBROWSEFULL_INDICATOR,    
    TEXTBROWSEFULL_DECBOOKWIDGET,
    TEXTBROWSEFULL_DECBOOKTOPWIDGET,
    TEXTBROWSEFULL_DECBOOKBUTTONWIDGET,
    TEXTBROWSEFULL_MAGNIFYWIDGET,
    TEXTBROWSEFULL_PAGEINDEXWIDGET,
}EbookTextBrowseFullWdgList_e;

enum
{
    FILELIST_MENUWIDGET=APP_WDG_START,
    FILELIST_THMTEXTWIDGET,
}EbookFileListWdgList_e;

typedef enum
{
	MNU_E_BOOK_OPT_MENU = 0,
	MNU_E_BOOK_OPT_VIEW,
	MNU_E_BOOK_OPT_DELETE,
	MNU_E_BOOK_OPT_DELETE_ALL,
	MNU_E_BOOK_OPT_SCROLL_STYLE,
	MNU_E_BOOK_OPT_LANG_CODE,
	MNU_E_BOOK_OPT_FULL_SCRN,
	MNU_E_BOOK_OPT_GOTO_BOOKMARK,
	MNU_E_BOOK_OPT_SELECT,
	MNU_E_BOOK_OPT_OVERWRITE,
	MNU_E_BOOK_OPT_RENAME,
	MNU_E_BOOK_OPT_FILE_INFO,
	MNU_E_BOOK_OPT_GOTO_LINE,
	MNU_E_BOOK_SCROLL_STYLE,
	MNU_E_BOOK_SCROLLBY1LINE,
	MNU_E_BOOK_SCROLLBY3LINES,
	MNU_E_BOOK_SCROLLBY6LINES,
	MNU_E_BOOK_SCROLLBYAPAGE,
	MNU_E_BOOK_LANGUAGE_CODE,
	MNU_E_BOOK_GB2312,
	MNU_E_BOOK_BIG5,
	MNU_E_BOOK_UTF8,
	MNU_E_BOOK_UCS2,
	MNU_E_BOOK_WIN1250,
	MNU_E_BOOK_WIN874,
	MNU_E_BOOK_WIN1251,
	MNU_E_BOOK_WIN1252,
	MNU_E_BOOK_WIN1253,
	MNU_E_BOOK_WIN1254,
	MNU_E_BOOK_WIN1255,
	MNU_E_BOOK_WIN1256,
	MNU_E_BOOK_WIN1257,
	MNU_E_BOOK_WIN1258,
}EbookMenuId_e;

#endif //__MMI_EBOOKAPP_ID_H__

