ApBegin(RS,CLSID_UNITCONVERTER)

    WndBegin(UNICONVERTER_WND_CONVERTING)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_CONVERTER})

        WdgBegin(CLSID_PICK_WIDGET,WdgType)
            WdgPickCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},FALSE})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_PICK_WIDGET,WdgType)

        WdgBegin(CLSID_PICK_WIDGET,WdgType1)
            WdgPickCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},FALSE})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_PICK_WIDGET,WdgType1)

        WdgBegin(CLSID_TEXTWIDGET,WdgSolarText)
            WdgTextCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,WdgSolarText)

        WdgBegin(CLSID_INPUTWIDGET,WdgInput1)
            WdgInputCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},{TRUE,SKBOARD_ENABLE}})
            WdgCommonSetBGPositionRC(WDG_BG_POS_INNER)
            WdgInputSetShowBorderWhenLoseFocusRC(TRUE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
            WdgInputSetDecimalPointEnableRC(TRUE)
            WdgInputSetMaxlenAfterExponentRC(UNITCONVERTER_INPUT_FIELD_EXP_LENGTH)
            WdgInputSetMaxByteLengthRC(UNITCONVERTER_INPUT_FIELD_MAX_LENGTH)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetPaddingDataRC({8,5,2,2})
        WdgEnd(CLSID_INPUTWIDGET,WdgInput1)

        WdgBegin(CLSID_DATEWIDGET,WdgSolarInput)
            WdgDateCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},{0,1,1,1,0,0,0,0}})
            WdgCommonSetBGPositionRC(WDG_BG_POS_INNER)
            WdgInputSetShowBorderWhenLoseFocusRC(TRUE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
            WdgDateSetMinYearRC(UNITCONVERTER_MIN_YEAR)
            WdgDateSetMaxYearRC(UNITCONVERTER_MAX_YEAR)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_DATEWIDGET,WdgSolarInput)

        WdgBegin(CLSID_PICK_WIDGET,WdgType2)
            WdgPickCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},FALSE})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_PICK_WIDGET,WdgType2)

        WdgBegin(CLSID_TEXTWIDGET,WdgLunarText)
            WdgTextCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,WdgLunarText)

        WdgBegin(CLSID_INPUTWIDGET,WdgInput2)
            WdgInputCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},{TRUE,SKBOARD_ENABLE}})
            WdgCommonSetBGPositionRC(WDG_BG_POS_INNER)
            WdgInputSetShowBorderWhenLoseFocusRC(TRUE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
            WdgInputSetDecimalPointEnableRC(TRUE)
            WdgInputSetMaxlenAfterExponentRC(UNITCONVERTER_INPUT_FIELD_EXP_LENGTH)
            WdgInputSetMaxByteLengthRC(UNITCONVERTER_INPUT_FIELD_MAX_LENGTH)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetPaddingDataRC({8,5,2,2})
        WdgEnd(CLSID_INPUTWIDGET,WdgInput2)

        WdgBegin(CLSID_DATEWIDGET,WdgLunarInput)
            WdgDateCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},{0,1,1,1,0,0,0,0}})
            WdgCommonSetBGPositionRC(WDG_BG_POS_INNER)
            WdgInputSetShowBorderWhenLoseFocusRC(TRUE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgDateSetMinYearRC(UNITCONVERTER_MIN_YEAR)
            WdgDateSetMaxYearRC(UNITCONVERTER_MAX_YEAR)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_DATEWIDGET,WdgLunarInput)

        WdgBegin(CLSID_TEXTWIDGET,WdgRate)
            WdgTextCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,WdgRate)

        WdgBegin(CLSID_PICK_WIDGET,WdgLeapMonth)
            WdgPickCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,0},FALSE})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_PICK_WIDGET,WdgLeapMonth)
    WndEnd(UNICONVERTER_WND_CONVERTING)



    WndBegin(UNICONVERTER_WND_SELECTION)
        WdgBegin(CLSID_VTMMENU,vtmMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CONVERTER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,vtmMenu)
    WndEnd(UNICONVERTER_WND_SELECTION)

    WndBegin(UNICONVERTER_WND_EDITMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,vtmOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2, {{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_COMMON_TEXT_SAVE},TXT_OIL1_N_SAVE},{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_COMMON_TEXT_INPUT_MENU},TXT_OIL1_N_INPUT_MENU}})
        WdgEnd(CLSID_VTMOPTIONMENU,vtmOptionMenu)
    WndEnd(UNICONVERTER_WND_EDITMENU)

    WndBegin(UNICONVERTER_WND_EDITNAME)
        WndSetTitleRC({IMG_NULL_ID,TXT_NULL_ID})
        WndSetAllSoftkeyRC({SK_OPTION, SK_NONE, SK_CANCEL})

        WdgBegin(CLSID_INPUTWIDGET,Input)
            WdgInputCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetMaxByteLengthRC(UNITCONVERTER_EDIT_MAXCHAR)
            WdgInputSetMultilineRC(TRUE)
        WdgEnd(CLSID_INPUTWIDGET,Input)
    WndEnd(UNICONVERTER_WND_EDITNAME)

    WndBegin(UNICONVERTER_WND_SETRATE)
        WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_RATE_SETTING})

        WdgBegin(CLSID_TEXTWIDGET,BaseCurrency)
            WdgTextCreateForWndRC({{UNITCONVERTER_RATEVIEW_XPOS,UNITCONVERTER_RATEVIEW_BASE_YPOS},{UNITCONVERTER_VIEW_WIDTH,UNITCONVERTER_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
        WdgEnd(CLSID_TEXTWIDGET,BaseCurrency)

        WdgBegin(CLSID_INPUTWIDGET,RateInput)
            WdgInputCreateForWndRC({{UNITCONVERTER_RATEVIEW_XPOS,UNITCONVERTER_RATEVIEW_INPUT_YPOS},{UNITCONVERTER_RATEVIEW_EDIT_WIDTH,UNITCONVERTER_ITEM_HEIGHT},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
            WdgInputSetDecimalPointEnableRC(TRUE)
            WdgInputSetMaxlenAfterExponentRC(UNITCONVERTER_INPUT_FIELD_EXP_LENGTH)
            WdgInputSetMaxByteLengthRC(UNITCONVERTER_INPUT_RATE_FIELD_MAX_LENGTH)
            WdgInputSetMaxlenAfterDecimalPointRC(UNITCONVERTER_INPUT_FIELD_FRA_LENGTH)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_INPUTWIDGET,RateInput)

        WdgBegin(CLSID_TEXTWIDGET,TargetCurrency)
            WdgTextCreateForWndRC({{UNITCONVERTER_RATEVIEW_XPOS,UNITCONVERTER_RATEVIEW_TARGET_YPOS},{UNITCONVERTER_VIEW_WIDTH,UNITCONVERTER_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
        WdgEnd(CLSID_TEXTWIDGET,TargetCurrency)

        WdgBegin(CLSID_TEXTWIDGET,RateRange)
            WdgTextCreateForWndRC({{0,UNITCONVERTER_RATEVIEW_RANGE_YPOS},{UNITCONVERTER_VIEW_WIDTH,UNITCONVERTER_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PML_N_RATE_RANGE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
        WdgEnd(CLSID_TEXTWIDGET,RateRange)
    WndEnd(UNICONVERTER_WND_SETRATE)



ApEnd(RS,CLSID_UNITCONVERTER)

