ApBegin(ThmDefault,CLSID_SUDOKUAPP)
    WndBegin(SUDOKU_WND_MAIN)
	WndSetTitleVisiableRC(FALSE)
	WndSetSoftkeyVisibleRC(FALSE)
	WndSetBgPosRC(WDG_BG_POS_WHOLE)
 WdgMenuSetMenuBGImageRC(SUDOKU_MAIN_IMG_BG)
 
      WdgBegin(CLSID_BUTTONWIDGET,StartButtonWidget)
            WdgButtonCreateForWndRC({{SUDOKU_START_BTN_POS_X,SUDOKU_START_BTN_POS_Y},{SUDOKU_START_BTN_WIDTH,SUDOKU_START_BTN_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMG_START_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,StartButtonWidget)    

        /*WdgBegin(CLSID_BUTTONWIDGET,AdvenceButtonWidget)
            WdgButtonCreateForWndRC({{193,247},{167,23},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMG_ADVENCE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,AdvenceButtonWidget)*/
        
        WdgBegin(CLSID_BUTTONWIDGET,QuitButtonWidget)
            WdgButtonCreateForWndRC({{SUDOKU_QUIT_BTN_POS_X,SUDOKU_QUIT_BTN_POS_Y},{SUDOKU_QUIT_BTN_WIDTH,SUDOKU_QUIT_BTN_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMG_QUIT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,QuitButtonWidget)


    WdgBegin(CLSID_TEXTWIDGET,NOOWidget)
            WdgTextCreateForWndRC({{SUDOKU_NO_0_POS_X,SUDOKU_NO_0_POS_Y},{SUDOKU_NO_0_WIDTH,SUDOKU_NO_0_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC((FontCategory_t)SUDOKU_NO_0_FONT_CAT)
            WdgCommonSetAlignmentRC((WdgAlignment_e)SUDOKU_NO_0_ALIGN)
            WdgCommonSetTextColorRC((RGBColor_t)SUDOKU_NO_0_COLOR)
        WdgEnd(CLSID_TEXTWIDGET,NOOWidget)
        
    WndEnd(SUDOKU_WND_MAIN)	
    WndBegin(SUDOKU_WND_PLAY)
            WndSetTitleVisiableRC(FALSE)
	   WndSetSoftkeyVisibleRC(FALSE)
            WndSetBgPosRC(WDG_BG_POS_WHOLE)
	    WdgMenuSetMenuBGImageRC(SUDOKU_PLAY_IMG_BG)

       WdgBegin(CLSID_CUBE_TEXTWIDGET,CubeListWidget)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
            WdgMenuCreateForWndRC({{SUDOKU_CUBE_LIST_POS_X,SUDOKU_CUBE_LIST_POS_Y},{SUDOKU_CUBE_LIST_WIDTH,SUDOKU_CUBE_LIST_HEIGHT},WDG_MENU_TYPE_GRID})

	     WdgMenuSetItemWidthRC((u16)SUDOKU_CUBE_LIST_ITEM_WIDTH)
             WdgMenuSetItemHeightRC((u16)SUDOKU_CUBE_LIST_ITEM_HEIGHT)
             WdgMenuSetRowGapRC((u16)SUDOKU_CUBE_LIST_ITEM_ROW_GAP)
             WdgMenuSetColGapRC((u16)SUDOKU_CUBE_LIST_ITEM_COL_GAP)
             WdgMenuSetFixedNumRC((u8)SUDOKU_CUBE_LIST_ITEM_FIXED_NUM)
             WdgCommonSetTextColorRC((RGBColor_t)SUDOKU_CUBE_LIST_COLOR)
			 WdgCommonSetFontCategoryRC((FontCategory_t)SUDOKU_CUBE_LIST_FONT_CAT)
			 WdgCommonSetAlignmentRC((WdgAlignment_e)SUDOKU_CUBE_LIST_ALIGN)
      WdgEnd(CLSID_CUBE_TEXTWIDGET,CubeListWidget)	
      WdgBegin(CLSID_TEXTWIDGET,CubeTextWidget)
            WdgTextCreateForWndRC({{SUDOKU_CUBE_TEXT_POS_X,SUDOKU_CUBE_TEXT_POS_Y},{SUDOKU_CUBE_TEXT_WIDTH,SUDOKU_CUBE_TEXT_HEIGHT},0})
      WdgEnd(CLSID_TEXTWIDGET,CubeTextWidget)

		  WdgBegin(CLSID_FADEOUTWIDGET,PlayFadeOutWidget)
			  WdgFadeoutCreateForWndRC({{SUDOKU_FADEOUT_POS_X,SUDOKU_FADEOUT_POS_Y},{SUDOKU_FADEOUT_WIDTH,SUDOKU_FADEOUT_HEIGHT},FADEOUT_LEVEL_6})
		  WdgEnd(CLSID_FADEOUTWIDGET,PlayFadeOutWidget)

       WdgBegin(CLSID_IMAGEWIDGET,SucessWidget)
        	    WdgImageCreateForWndRC({{SUDOKU_SUCCESS_POS_X,SUDOKU_SUCCESS_POS_Y},{SUDOKU_SUCCESS_WIDTH,SUDOKU_SUCCESS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
	    WdgImageSetDataByIDRC(SUDOKU_IMAGE_SUCESS)
	WdgEnd(CLSID_IMAGEWIDGET,SucessWidget)

     WdgBegin(CLSID_IMAGEWIDGET,FailWidget)
        	    WdgImageCreateForWndRC({{SUDOKU_FAIL_POS_X,SUDOKU_FAIL_POS_Y},{SUDOKU_FAIL_WIDTH,SUDOKU_FAIL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
	    WdgImageSetDataByIDRC(SUDOKU_IMAGE_FAIL)
	WdgEnd(CLSID_IMAGEWIDGET,FailWidget)

    	WdgBegin(CLSID_TEXTWIDGET,TimerTxtWdg)
            WdgTextCreateForWndRC({{SUDOKU_TIMER_POS_X,SUDOKU_TIMER_POS_Y},{SUDOKU_TIMER_WIDTH,SUDOKU_TIMER_HEIGHT},TEXT_STYLE_COMMON})
				WdgCommonSetFontCategoryRC((FontCategory_t)SUDOKU_TIME_CAT)
				WdgCommonSetAlignmentRC((WdgAlignment_e)SUDOKU_TIME_ALIGN)
				WdgCommonSetTextColorRC((RGBColor_t)SUDOKU_TIME_COLOR)
		WdgEnd(CLSID_TEXTWIDGET,TimerTxtWdg)

        WdgBegin(CLSID_CUBE_TEXTWIDGET,OperandListWidget)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{SUDOKU_OPERAND_LIST_POS_X,SUDOKU_OPERAND_LIST_POS_Y},{SUDOKU_OPERAND_LIST_WIDTH,SUDOKU_OPERAND_LIST_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(9,
				{{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},0},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_1_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},1},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_2_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},2},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_3_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},3},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_4_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},4},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_5_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},5},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_6_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},6},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_7_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},7},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_8_PRESSED}},\
				{{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},8},{TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMAGE_9_PRESSED}}})
             WdgMenuSetItemWidthRC((u16)SUDOKU_OPERAND_LIST_ITEM_WIDTH)
             WdgMenuSetItemHeightRC((u16)SUDOKU_OPERAND_LIST_ITEM_HEIGHT)
             WdgMenuSetRowGapRC((u16)SUDOKU_OPERAND_LIST_ROW_GAP)
             WdgMenuSetColGapRC((u16)SUDOKU_OPERAND_LIST_COL_GAP)
             WdgMenuSetFixedNumRC((u8)SUDOKU_OPERAND_LIST_FIXED_NUM)  
        WdgEnd(CLSID_CUBE_TEXTWIDGET,OperandListWidget)
        
        WdgBegin(CLSID_BUTTONWIDGET,OperandButtonWidget)
            WdgButtonCreateForWndRC({{SUDOKU_OPERAND_BTN_POS_X,SUDOKU_OPERAND_BTN_POS_Y},{SUDOKU_OPERAND_BTN_WIDTH,SUDOKU_OPERAND_BTN_HEIGHT},0})
        WdgEnd(CLSID_BUTTONWIDGET,OperandButtonWidget)

        WdgBegin(CLSID_BUTTONWIDGET,PlayQuitButtonWidget)
            WdgButtonCreateForWndRC({{SUDOKU_PLAY_QUIT_BTN_POS_X,SUDOKU_PLAY_QUIT_BTN_POS_Y},{SUDOKU_PLAY_QUIT_BTN_WIDTH,SUDOKU_PLAY_QUIT_BTN_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,SUDOKU_IMG_PQUIT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PlayQuitButtonWidget)
        RSCustomize(RGBColor_t,tTxtClrOrig,SUDOKU_CUBE_LIST_COLOR_ORIG)
      WndEnd(SUDOKU_WND_PLAY)
      
ApEnd(ThmDefault,CLSID_SUDOKUAPP)

