#define RV_RELEASE

#define RV_TOOL_TYPE RV_TOOL_TYPE_AEON

#define RV_TOOL_VERSION RV_TOOL_GNU_3_2

#define RV_OS_TYPE RV_OS_TYPE_RTK

#define RV_OS_VERSION RV_OS_RVAD

#define RV_ARCH_ENDIAN RV_ARCH_LITTLE_ENDIAN

#define RV_ARCH_BITS RV_ARCH_BITS_32 