//==============================================================================
//
//  File        : StateMoviepbFunc_inc.h
//  Description : INCLUDE File for the StateCameraFunc function porting.
//  Author      : 
//  Revision    : 1.0
//
//==============================================================================

#ifndef _STATEMOVIEPBFUNC_INC_H_
#define _STATEMOVIEPBFUNC_INC_H_

/*===========================================================================
 * Include file 
 *===========================================================================*/

/*===========================================================================
 * Function prototype
 *===========================================================================*/
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_KEY_UP);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_KEY_DOWN);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_KEY_LEFT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_KEY_RIGHT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_PLAY_START);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_MODE);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_KEY_MENU);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_PREV_PRESS);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_NEXT_PRESS);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_VIDEO_PREVIEW);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_CAMERA_PREVIEW);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_FILE_DELETING);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_LOCK_FILE_M);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_DC_CABLE_IN);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_DC_CABLE_OUT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_USB_DETECT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_USB_REMOVED);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_SD_DETECT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_SD_REMOVED);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_HDMI_DETECT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_HDMI_REMOVED);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_TV_DETECT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_TV_REMOVED);
DECL_AHC_EV_HANDLER(STATE_PLAYBACK_MODE_EVENT_USB_B_DEVICE_DETECT);
DECL_AHC_EV_HANDLER(STATE_PLAYBACK_MODE_EVENT_USB_B_DEVICE_REMOVED);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_MOVPB_UPDATE_MESSAGE);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_SUB_MODE_ENTER);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_SUB_MODE_EXIT);
DECL_AHC_EV_HANDLER(STATE_MOVPB_MODE_EVENT_ENTER_NET_PLAYBACK);

AHC_BOOL 	StateMoviePlaybackModeInitLCD(void* pData);
AHC_BOOL 	StateMoviePlaybackModeInitHDMI(void* pData);
AHC_BOOL 	StateMoviePlaybackModeInitTV(void* pData);
AHC_BOOL 	StateMoviePlaybackModeShutDown(void* pData);
UINT32 		StateMoviePlaybackModeHandler(UINT32 ulMsgId, UINT32 ulEvent, UINT32 ulParam);

#endif //_STATEBROWSERFUNC_H_
