#ifndef __MMI_UNITCONVERTERAPP_ID_H__
#define __MMI_UNITCONVERTERAPP_ID_H__

typedef enum UniconverterWndId_e_
{
    UNICONVERTER_WND_CONVERTING = WND_ID_APP_BASE,
	UNICONVERTER_WND_SETRATE,
	UNICONVERTER_WND_SELECTION,
	UNICONVERTER_WND_EDITNAME,
	UNICONVERTER_WND_EDITMENU,
} UniconverterWndId_e;

typedef enum
{
    eUNITCONVERTER_CONTAINER = APP_WDG_START,
    eUNITCONVERTER_TYPE,
    eUNITCONVERTER_TYPE1,
    eUNITCONVERTER_SOLAR_TEXT,
    eUNITCONVERTER_INPUT1,
    eUNITCONVERTER_SOLAR_INPUT,
    eUNITCONVERTER_TYPE2,
    eUNITCONVERTER_LUNAR_TEXT,
    eUNITCONVERTER_INPUT2,
    eUNITCONVERTER_LUNAR_INPUT,
    eUNITCONVERTER_RATE,
    eUNITCONVERTER_LEAPMONTH,
}UniconverterWdgId_e;

typedef enum
{
    eUNITCONVERTER_EDIT_INPUT = APP_WDG_START,
    eUNITCONVERTER_EDIT_PROPCONATAINER,
}UniconverterEditWdgId_e; //VID_UNITCONVERTER_EDIT_VIEW_enum

typedef enum
{
    eUNITCONVERTER_RATE_BASE_CURRENCY = APP_WDG_START,
    eUNITCONVERTER_RATE_INPUT,
    eUNITCONVERTER_RATE_TARGET_CURRENCY,
    eUNITCONVERTER_RATE_RANGE,
}UniconverterRateWdgId_e; //VID_UNITCONVERTER_CURRENCY_RATE_VIEW_enum

#endif //__MMI_UNITCONVERTERAPP_ID_H__

