/**
* @file mmi_unitconverterapp.h
*
* State Machine Application - UNITCONVERTER
* Generated by XFSM v1.0, CodeVer=v0.24 
*
* Class Id: CLSID_UNITCONVERTER
* 
*
* @version $Id$
*/
#ifndef __MMI_UNITCONVERTERAPP_H__
#define __MMI_UNITCONVERTERAPP_H__

/*-------------------------------------------------------------------------*/

#include "mmi_mae_common_def.h"

/*-------------------------------------------------------------------------*/
/**
 * Functions
 */

MAE_Ret UNITCONVERTER_New(MAE_ClsId id, void **ppObj);

/*-------------------------------------------------------------------------*/


/*-------------------------------------------------------------------------*/
#endif /* __MMI_UNITCONVERTERAPP_H__ */
