//#include "tudouapp_resource.h"
#ifdef __APP_MMI_TUDOU__
ApBegin(RS,CLSID_TUDOUAPP)
    WndBegin(TUDOU_WND_START)
        WndSetStatusBarVisibleRC(VIEWSB_INVISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)
        WdgBegin(CLSID_IMAGEWIDGET,ImgWelc)
           WdgImageCreateForWndRC({{0,0},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,TUDOU_IMG_START}})
           WdgImageSetDataByIDRC(TUDOU_IMG_START)
		WdgEnd(CLSID_IMAGEWIDGET,ImgWelc)
		WdgBegin(CLSID_TEXTWIDGET,TextWdg)
        		WdgTextCreateForWndRC({{0,0},{0,0},TEXT_STYLE_COMMON})
        		WdgCommonSetAlignmentRC((ALIGN_H_CENTER | ALIGN_V_MIDDLE))
        		WdgCommonSetBorderDataRC({0,0,0,0,0})
        WdgEnd(CLSID_TEXTWIDGET,TextWdg)

    WndEnd(TUDOU_WND_START)

    WndBegin(TUDOU_WND_DUALSIM_SELECT)
        WdgBegin(CLSID_VTMSIMSELECTION,DualSim)
            VtmCreateSimSelectionRC({0,TXT_LIL_N_CDW_SIM_SELECTED})
        WdgEnd(CLSID_VTMSIMSELECTION,DualSim)
    WndEnd(TUDOU_WND_DUALSIM_SELECT)

    WndBegin(TUDOU_WND_HOTSPOT)
        WdgBegin(CLSID_GRID_MENUWIDGET,HotSpotGridWdg)
	        WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE_TEXT)
            WdgStaticMenuItemRC(5,
				{{{MENUMODEL_ITEM_VISABLE, {SK_NONE, SK_OK, SK_BACK}, MNU_TUDOU_HOTSPOT}, {TUDOU_IMG_HOTSPOT_MENU, TXT_LIL_N_TUDOUAPP_HOTSPOT}}, \
				{{MENUMODEL_ITEM_VISABLE, {SK_NONE, SK_OK, SK_BACK}, MNU_TUDOU_CHANNEL},  {TUDOU_IMG_CHANNEL_MENU, TXT_LIL_N_TUDOUAPP_CHANNEL}}, \
				{{MENUMODEL_ITEM_VISABLE, {SK_NONE, SK_OK, SK_BACK}, MNU_TUDOU_SEARCH},  {TUDOU_IMG_SEARCH_MENU, TXT_LIL_N_TUDOUAPP_SEARCH}}, \
				{{MENUMODEL_ITEM_VISABLE, {SK_NONE, SK_OK, SK_BACK}, MNU_TUDOU_DOWNLOAD},  {TUDOU_IMG_DOWNLOAD_MENU, TXT_LIL_N_TUDOUAPP_DOWNLOAD}}, \
				{{MENUMODEL_ITEM_VISABLE, {SK_NONE, SK_OK, SK_BACK}, MNU_TUDOU_SETTINGS},  {TUDOU_IMG_SETTINGS_MENU, TXT_LIL_N_TUDOUAPP_SETTINGS}}}) \
            WdgMenuSetItemWidthRC(TUDOUAPP_HOTSPOT_GRIDMENU_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(TUDOUAPP_HOTSPOT_GRIDMENU_ITEM_HEIGHT)
            WdgMenuSetColGapRC(1)
            WdgMenuSetFixedNumRC(TUDOUAPP_HOTSPOT_GRIDMENU_ITEM_NUM)
            WdgMenuSetToGridStyleRC({5, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		    WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		    WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
	    WdgEnd(CLSID_GRID_MENUWIDGET,HotSpotGridWdg)
    WndEnd(TUDOU_WND_HOTSPOT)
    WndBegin(TUDOU_WND_SETTINGS)
        WdgBegin(CLSID_DOUBLE_TEXT_WIDGET,NetWorkWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_DOUBLE_TEXT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_NETWORK_SETTINGS,TXT_NULL_ID})
        WdgEnd(CLSID_DOUBLE_TEXT_WIDGET,NetWorkWidget)
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordStorageTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(3, {0,{IMG_NULL_ID,TXT_OIL1_N_STORAGE}},{ {IMG_NULL_ID,TXT_LIL_N_CARD}, {IMG_NULL_ID,TXT_LIL_N_CARD2},{IMG_NULL_ID,TXT_LIL_N_PHONE} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordStorageTextPickWidget)
    WndEnd(TUDOU_WND_SETTINGS)
ApEnd(RS,CLSID_TUDOUAPP)
#endif

