#ifndef __MMI_VIDEOTELEPHONYAPP_ID_H__
#define __MMI_VIDEOTELEPHONYAPP_ID_H__

#define VIDEOTELEPHONYAPP_DIALER_MAX_INPUT_BYTE       (160) //Maximum allowable input bytes (80 characters)
#define VIDEOTELEPHONYAPP_IPCALL_MAX_NUM_LEN (5 * sizeof(MAE_WChar))

typedef enum VideoTelephonyWndId_e_
{
	VIDEOTELEPHONY_WND_DUALMENU = WND_ID_APP_BASE,
	VIDEOTELEPHONY_WND_OUTGOINGCALL,
	VIDEOTELEPHONY_WND_IPNUMBERLIST,
	VIDEOTELEPHONY_WND_IPNUMBEREDITOR,
	VIDEOTELEPHONY_WND_INCALLSCREEN,
	VIDEOTELEPHONY_WND_INCALLSCREENOPTIONMENU,
	VIDEOTELEPHONY_WND_INCALLSCREENMODE,
	VIDEOTELEPHONY_WND_INCALLSCREENSOURCE,
	VIDEOTELEPHONY_WND_INCALLEDITOR,
	VIDEOTELEPHONY_WND_INCALLEDITOROPTIONMENU,
	VIDEOTELEPHONY_WND_MULTIPARTYLIST,
	VIDEOTELEPHONY_WND_MULTIPARTYOPTIONMENU,
	VIDEOTELEPHONY_WND_DTMFNUMBERINPUT,
	VIDEOTELEPHONY_WND_CUS
} VideoTelephonyWndId_e;

typedef enum //VideoTelephonyAppOutgoingCallView_e
{
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_BEGIN=APP_WDG_START,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_CALLSCREEN_BG,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_MAINCONTAINER,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_IMGAREA_CONTAINER,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_OUTGOINGCALL_IMAGE,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_TEXTAREA_CONTAINER,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_CALLSTATE_TEXT,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_CALLINFO_TEXT,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_DUOSTATE_TEXT,
	VIDEOTELEPHONYAPP_OUTGOINGCALL_VIEW_END
} VideoTelephonyAppOutgoingCallView_e;

typedef enum
{
	VIDEOTELEPHONYAPP_DIALING_MAINCONTAINER=APP_WDG_START,
	VIDEOTELEPHONYAPP_DIALING_INPUT,
	VIDEOTELEPHONYAPP_DIALING_SHORTCUT,
#ifdef __TOUCH_SCREEN_MMI__
	VIDEOTELEPHONYAPP_DIALING_GRID1, // 0~9, *, #
	VIDEOTELEPHONYAPP_DIALING_BUTTON1,
	VIDEOTELEPHONYAPP_DIALING_GRID2, // Call, Clear, Add to Contact
	VIDEOTELEPHONYAPP_DIALING_BUTTON2,
#endif
} VideoTelephonyAppDialingView_e;

typedef enum //VIDEOTELEPHONYAPP_TALK_VIEW_e
{
	VIDEOTELEPHONYAPP_TALK_VIEW_BEGIN=APP_WDG_START,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLSCREEN_BG,
	VIDEOTELEPHONYAPP_TALK_VIEW_VIDEOCALL_BG,
	VIDEOTELEPHONYAPP_TALK_VIEW_VIDEOCALL_SMALLBG,
	VIDEOTELEPHONYAPP_TALK_VIEW_VIDEOCALL_OSD,
	VIDEOTELEPHONYAPP_TALK_VIEW_VIDEOCALL_LOCAL_OSD,	
	VIDEOTELEPHONYAPP_TALK_VIEW_MAINCONTAINER,
	VIDEOTELEPHONYAPP_TALK_VIEW_IMGAREA_CONTAINER,
	VIDEOTELEPHONYAPP_TALK_VIEW_MPTY_IMAGE1,
	VIDEOTELEPHONYAPP_TALK_VIEW_MPTY_IMAGE2,
	VIDEOTELEPHONYAPP_TALK_VIEW_MPTY_IMAGE3,
	VIDEOTELEPHONYAPP_TALK_VIEW_MPTY_IMAGE4,
	VIDEOTELEPHONYAPP_TALK_VIEW_MPTY_IMAGE5,
	VIDEOTELEPHONYAPP_TALK_VIEW_TIMEAREA_CONTAINER,
	VIDEOTELEPHONYAPP_TALK_VIEW_DUO_IMAGE,
	VIDEOTELEPHONYAPP_TALK_VIEW_RECORD_IMAGE,
	VIDEOTELEPHONYAPP_TALK_VIEW_RECORD_TIMER_WIDGET,
	VIDEOTELEPHONYAPP_TALK_VIEW_TIMER_WIDGET,
	VIDEOTELEPHONYAPP_TALK_VIEW_MUTE_IMAGE,
	VIDEOTELEPHONYAPP_TALK_VIEW_AUDIOSOURCE_OFF_IMAGE,
	VIDEOTELEPHONYAPP_TALK_VIEW_TEXTAREA_CONTAINER,
	VIDEOTELEPHONYAPP_TALK_VIEW_TEXTAREA_BG,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_IMAGE1,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_TEXT1,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_MPTY_LISTWIDGET,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_MPTY_IMAGES,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_IMAGE2,
	VIDEOTELEPHONYAPP_TALK_VIEW_CALLINFO_TEXT2,
	VIDEOTELEPHONYAPP_TALK_VIEW_END
} VideoTelephonyAppTalkView_e;

typedef enum //VideoTelephonyAppIpNumEditorView_e
{
	VIDEOTELEPHONYAPP_IP_NUM_VIEW_BEGIN=APP_WDG_START,
	VIDEOTELEPHONYAPP_IP_NUM_VIEW_INPUT,
	VIDEOTELEPHONYAPP_IP_NUM_VIEW_END
} VideoTelephonyAppIpNumEditorView_e;

typedef enum
{
	MNU_VIDEOTELEPHONY_DUAL_MENU = 0,
	MNU_VIDEOTELEPHONY_OPT_INCALL_OPTION,			// 1
	MNU_VIDEOTELEPHONY_OPT_SPEAKER,
	MNU_VIDEOTELEPHONY_OPT_HANDSET,
	MNU_VIDEOTELEPHONY_OPT_BT_HEADSET,
	MNU_VIDEOTELEPHONY_OPT_MUTE,					// 5
	MNU_VIDEOTELEPHONY_OPT_UNMUTE,
	MNU_VIDEOTELEPHONY_OPT_AUDIO_SOURCE_ON,
	MNU_VIDEOTELEPHONY_OPT_AUDIO_SOURCE_OFF,
	MNU_VIDEOTELEPHONY_OPT_HOLD,
	MNU_VIDEOTELEPHONY_OPT_RETRIEVE,				// 10
	MNU_VIDEOTELEPHONY_OPT_END_ACTIVE,
	MNU_VIDEOTELEPHONY_OPT_VOLUME,
	MNU_VIDEOTELEPHONY_OPT_DTMF,
	MNU_VIDEOTELEPHONY_OPT_DTMF_ON,
	MNU_VIDEOTELEPHONY_OPT_DTMF_OFF,				// 15
	MNU_VIDEOTELEPHONY_OPT_RECORD,
	MNU_VIDEOTELEPHONY_OPT_STOP_RECORD,
	MNU_VIDEOTELEPHONY_OPT_PHONEBOOK,
	MNU_VIDEOTELEPHONY_OPT_MESSAGE,
	MNU_VIDEOTELEPHONY_OPT_REPLACE_CALL_OPTION,	// 20
	MNU_VIDEOTELEPHONY_OPT_MULTIPARTY_OPTION,
	MNU_VIDEOTELEPHONY_OPT_SPLIT,
	MNU_VIDEOTELEPHONY_OPT_END_SELECTED_,
	MNU_VIDEOTELEPHONY_OPT_INCALLEDITOR_OPTION,
	MNU_VIDEOTELEPHONY_OPT_CALL,					//25
	MNU_VIDEOTELEPHONY_OPT_IPCALL,					
	MNU_VIDEOTELEPHONY_OPT_ADD,
	MNU_VIDEOTELEPHONY_OPT_SEND,
	MNU_VIDEOTELEPHONY_OPT_ZOOM,
	MNU_VIDEOTELEPHONY_OPT_ZOOM_MULTIPLY_ONE,		// 30
	MNU_VIDEOTELEPHONY_OPT_ZOOM_MULTIPLY_TWO,	
	MNU_VIDEOTELEPHONY_OPT_ZOOM_MULTIPLY_THREE,
	MNU_VIDEOTELEPHONY_OPT_ZOOM_MULTIPLY_FOUR,
	MNU_VIDEOTELEPHONY_OPT_LIGHT,
	MNU_VIDEOTELEPHONY_OPT_LIGHT_MINUS_TWO,		// 35
	MNU_VIDEOTELEPHONY_OPT_LIGHT_MINUS_ONE,		
	MNU_VIDEOTELEPHONY_OPT_LIGHT_DEFAULT,
	MNU_VIDEOTELEPHONY_OPT_LIGHT_PLUS_ONE,
	MNU_VIDEOTELEPHONY_OPT_LIGHT_PLUS_TWO,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS,				// 40
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SWITCH_CAMERA,	
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_CAMERA_ON,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_CAMERA_OFF,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_SMALL,	//45
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_LARGE,	
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_REMOTE_ONLY,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_ONLY,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SOURCE,
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SOURCE_FROM_CAMERA,		//50
	MNU_VIDEOTELEPHONY_OPT_SETTINGS_SOURCE_FROM_FILE,			
	//MNU_VIDEOTELEPHONY_OPT_SWAP,
	//MNU_VIDEOTELEPHONY_OPT_VIEW,
	//MNU_VIDEOTELEPHONY_OPT_END_HOLD,
	//MNU_VIDEOTELEPHONY_OPT_MULTIPARTY,
	//MNU_VIDEOTELEPHONY_OPT_TRANSFER,
} VideoTelephonyMenuId_e;
#endif //__MMI_VIDEOTELEPHONYAPP_ID_H__

