ApBegin(RS, CLSID_EMUAPP)
    WndBegin(EMU_WND_GAME)
        WdgBegin(CLSID_OSDWIDGET, Osd)
            WdgOsdCreateForWndRC({{EMUAPP_KEYPAD_PLAY_OSD_POS_X, EMUAPP_KEYPAD_PLAY_OSD_POS_Y}, {EMUAPP_KEYPAD_PLAY_OSD_WIDTH, EMUAPP_KEYPAD_PLAY_OSD_HEIGHT}, 0})
        WdgEnd(CLSID_OSDWIDGET, Osd)

#if defined(__EMU_VIRTUAL_KEYPAD_ENABLE__)
        WdgBegin(CLSID_ABSCONTAINER, KeypadCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadCtnr)

        // SELECT
        WdgBegin(CLSID_IMAGEWIDGET, SelectImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_SELECT_POS_X, EMUAPP_KEYPAD_PLAY_IMG_SELECT_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_FUNC_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_FUNC_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_SELECT}})
        WdgEnd(CLSID_IMAGEWIDGET, SelectImgWdg)

        // START
        WdgBegin(CLSID_IMAGEWIDGET, StartImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_START_POS_X, EMUAPP_KEYPAD_PLAY_IMG_START_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_FUNC_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_FUNC_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_START}})
        WdgEnd(CLSID_IMAGEWIDGET, StartImgWdg)

        // A/ B/ X/ Y CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, ABXYCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_ABXY_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_ABXY_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_ABXY_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_ABXY_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, ABXYCtnr)

        // A
        WdgBegin(CLSID_ABSCONTAINER, KeypadACtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_A_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_A_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadACtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadATxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadATxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadATxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadATxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadATxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadATxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadAImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadAImgWdg)

        // B
        WdgBegin(CLSID_ABSCONTAINER, KeypadBCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_B_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_B_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadBCtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadBTxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadBTxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadBTxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadBTxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadBTxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadBTxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadBImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadBImgWdg)

        // X
        WdgBegin(CLSID_ABSCONTAINER, KeypadXCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_X_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_X_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadXCtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadXTxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadXTxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadXTxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadXTxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadXTxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadXTxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadXImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadXImgWdg)

        // Y
        WdgBegin(CLSID_ABSCONTAINER, KeypadYCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_Y_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_Y_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadYCtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadYTxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadYTxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadYTxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadYTxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadYTxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadYTxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadYImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadYImgWdg)

        // L
        WdgBegin(CLSID_ABSCONTAINER, KeypadLCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_L_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadLCtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadLTxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadLTxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadLTxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadLTxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadLTxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadLTxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadLImgWdg)

        // R
        WdgBegin(CLSID_ABSCONTAINER, KeypadRCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_R_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_OP_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadRCtnr)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadRTxtLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadRTxtLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadRTxtMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadRTxtMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadRTxtRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadRTxtRImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_OP_POS_X, EMUAPP_KEYPAD_PLAY_IMG_OP_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_OP_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_OP_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadRImgWdg)

        // JOYSTICK CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, KeypadJoystickCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_PLAY_CTNR_JOYSTICK_POS_X, EMUAPP_KEYPAD_PLAY_CTNR_JOYSTICK_POS_Y}, {EMUAPP_KEYPAD_PLAY_CTNR_JOYSTICK_WIDTH, EMUAPP_KEYPAD_PLAY_CTNR_JOYSTICK_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadJoystickCtnr)

        // JOYSTICK BACKGROUND
        WdgBegin(CLSID_IMAGEWIDGET, KeypadJoystickBGImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_BG_POS_X, EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_BG_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_BG_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_BG_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_JOYSTICK_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadJoystickBGImgWdg)

        // JOYSTICK STICK
        WdgBegin(CLSID_IMAGEWIDGET, KeypadJoystickImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_STICK_POS_X, EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_STICK_POS_Y}, {EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_STICK_WIDTH, EMUAPP_KEYPAD_PLAY_IMG_JOYSTICK_STICK_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_JOYSTICK}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadJoystickImgWdg)
#endif // __EMU_VIRTUAL_KEYPAD_ENABLE__

    WndEnd(EMU_WND_GAME)

    WndBegin(EMU_WND_SETTINGS)
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_GAME_SETTINGS})

        WdgBegin(CLSID_MENUWIDGET, SettingsMenu)
            WdgMenuCreateForWndRC({{0, MAIN_TITLE_HEIGHT}, {MAIN_DEFVIEW_WIDTH, MAIN_DEFVIEW_HEIGHT - MAIN_TITLE_HEIGHT}, WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_MENUWIDGET, SettingsMenu)

/*            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)  set double item in menu ?? how to implement????  */
    WndEnd(EMU_WND_SETTINGS)

    WndBegin(EMU_WND_VOLUME)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_VOLUME})
    WndEnd(EMU_WND_VOLUME)

     WndBegin(EMU_WND_HELP)
        WdgBegin(CLSID_VTMPOPUPINFO, vtmPopUp)
            VtmCreatePopUpInfoRC({IMG_NULL_ID, TXT_LTL_N_EMU_GAMES})
        WdgEnd(CLSID_VTMPOPUPINFO, vtmPopUp)
    WndEnd(EMU_WND_HELP)

#if defined(__EMU_VIRTUAL_KEYPAD_ENABLE__)
    WndBegin(EMU_WND_SELECT_KEYPAD)
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_EMU_VIRTUAL_KEYPAD_SETTINGS})

        WdgBegin(CLSID_MENUWIDGET, SelectMenu)
            WdgMenuCreateForWndRC({{EMUAPP_SELECT_KEYPAD_MENU_POS_X, EMUAPP_SELECT_KEYPAD_MENU_POS_Y}, {EMUAPP_SELECT_KEYPAD_MENU_WIDTH, EMUAPP_SELECT_KEYPAD_MENU_HEIGHT}, WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_MENUWIDGET, SelectMenu)
    WndEnd(EMU_WND_SELECT_KEYPAD)

    WndBegin(EMU_WND_KEYPAD_SETTINGS)
        // CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsCtnr)

        // BACKGROUND
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsBGImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_BG_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_BG_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_BG_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_BG_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsBGImgWdg)

        // HINT text
        WdgBegin(CLSID_TEXTWIDGET, HintTxtWdg)
            WdgTextCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_TXT_HINT_POS_X, EMUAPP_KEYPAD_SETTINGS_TXT_HINT_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_TXT_HINT_WIDTH, EMUAPP_KEYPAD_SETTINGS_TXT_HINT_HEIGHT}, TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_KEYPAD_SETTINGS_HINT_TEXT)
            WdgTextSetLayoutFlagRC(EMUAPP_KEYPAD_SETTINGS_TXT_HINT_LAYOUT)
            WdgCommonSetTextColorRC(EMUAPP_KEYPAD_SETTINGS_TXT_HINT_COLOR)
            WdgCommonSetFontCategoryRC(EMUAPP_KEYPAD_SETTINGS_TXT_HINT_FONT_CATEGORY)
            WdgCommonSetAlignmentRC(EMUAPP_KEYPAD_SETTINGS_TXT_HINT_ALIGNMENT)
        WdgEnd(CLSID_TEXTWIDGET, HintTxtWdg)

        // DEFAULT
        WdgBegin(CLSID_BUTTONWIDGET, DefaultBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_DEFAULT_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_DEFAULT_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_LIL_N_DEFAULT, EMU_IMG_SETTING_BTN, EMU_IMG_SETTING_BTN_PRESSED})
            WdgButtonSetUnpressedTextColorRC(RGBCOLOR_WHITE)
        WdgEnd(CLSID_BUTTONWIDGET, DefaultBtnWdg)

        // OK
        WdgBegin(CLSID_BUTTONWIDGET, OKBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OK_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OK_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_LSK_N_OK, EMU_IMG_SETTING_BTN, EMU_IMG_SETTING_BTN_PRESSED})
            WdgButtonSetUnpressedTextColorRC(RGBCOLOR_WHITE)
        WdgEnd(CLSID_BUTTONWIDGET, OKBtnWdg)

        // CANCEL
        WdgBegin(CLSID_BUTTONWIDGET, CancelBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_CANCEL_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_CANCEL_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_SETTING_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_RSK_N_CANCEL, EMU_IMG_SETTING_BTN, EMU_IMG_SETTING_BTN_PRESSED})
            WdgButtonSetUnpressedTextColorRC(RGBCOLOR_WHITE)
        WdgEnd(CLSID_BUTTONWIDGET, CancelBtnWdg)

        // JOYSTICK CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsJoystickCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_JOYSTICK_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_JOYSTICK_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_JOYSTICK_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_JOYSTICK_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsJoystickCtnr)

        // JOYSTICK BACKGROUND
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsJoystickBGImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_BG_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_BG_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_BG_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_BG_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_JOYSTICK_BG}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsJoystickBGImgWdg)

        // JOYSTICK
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsJoystickImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_STICK_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_STICK_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_STICK_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_JOYSTICK_STICK_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_VIRTUAL_BTN_JOYSTICK}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsJoystickImgWdg)

        // A/B/X/Y CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsABXYCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_ABXY_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_ABXY_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_ABXY_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_ABXY_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsABXYCtnr)

        // A
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadACtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_A_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_A_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadACtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadABtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadABtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadALImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadALImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadAMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadAMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadARImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadARImgWdg)

        // B
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadBCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_B_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_B_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadBCtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadBBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadBBtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadBRImgWdg)

        // X
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadXCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_X_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_X_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadXCtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadXBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadXBtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadXRImgWdg)

        // Y
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadYCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_Y_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_Y_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadYCtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadYBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadYBtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadYRImgWdg)

        // L
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadLCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_L_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadLCtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadLBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadLBtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadLRImgWdg)

        // R
        WdgBegin(CLSID_ABSCONTAINER, KeypadSettingsKeypadRCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_R_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_OP_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadSettingsKeypadRCtnr)
        WdgBegin(CLSID_BUTTONWIDGET, KeypadSettingsKeypadRBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_OP_POS_X}, {EMUAPP_KEYPAD_SETTINGS_BTN_OP_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_OP_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_VIRTUAL_BTN_BG, EMU_IMG_VIRTUAL_BTN_BG_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadSettingsKeypadRBtnWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRLImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRLImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRMImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_M_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRMImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRRImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_OP_TXT_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadSettingsKeypadRRImgWdg)

        // PREVIOUS KEYPAD STYLE
        WdgBegin(CLSID_BUTTONWIDGET, KeypadStylePreBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_PREVIOUS_KEYPAD_STYLE_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_PREVIOUS_KEYPAD_STYLE_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_SELECT_KEYPAD_STYLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_SELECT_KEYPAD_STYLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_LEFT, EMU_IMG_LEFT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadStylePreBtnWdg)

        // NEXT KEYPAD STYLE
        WdgBegin(CLSID_BUTTONWIDGET, KeypadStyleNextBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_NEXT_KEYPAD_STYLE_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_NEXT_KEYPAD_STYLE_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_SELECT_KEYPAD_STYLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_SELECT_KEYPAD_STYLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_RIGHT, EMU_IMG_RIGHT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, KeypadStyleNextBtnWdg)

        // KEYPAD STYLE INDICATOR CONTAINER
        WdgBegin(CLSID_ABSCONTAINER, KeypadStyleIndicatorCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_KEYPAD_STYLE_INDICATOR_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_KEYPAD_STYLE_INDICATOR_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_KEYPAD_STYLE_INDICATOR_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_KEYPAD_STYLE_INDICATOR_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, KeypadStyleIndicatorCtnr)

        // KEYPAD STYLE INDICATOR 1
        WdgBegin(CLSID_IMAGEWIDGET, KeypadStyleIndicator1ImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR1_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR1_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_PAGE_INDICATOR_FALSE}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadStyleIndicator1ImgWdg)

        // KEYPAD STYLE INDICATOR 2
        WdgBegin(CLSID_IMAGEWIDGET, KeypadStyleIndicator2ImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR2_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR2_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_PAGE_INDICATOR_FALSE}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadStyleIndicator2ImgWdg)

        // KEYPAD STYLE INDICATOR 3
        WdgBegin(CLSID_IMAGEWIDGET, KeypadStyleIndicator3ImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR3_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR3_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_PAGE_INDICATOR_FALSE}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadStyleIndicator3ImgWdg)

        // KEYPAD STYLE INDICATOR 4
        WdgBegin(CLSID_IMAGEWIDGET, KeypadStyleIndicator4ImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR4_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR4_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_KEYPAD_STYLE_INDICATOR_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, EMU_IMG_PAGE_INDICATOR_FALSE}})
        WdgEnd(CLSID_IMAGEWIDGET, KeypadStyleIndicator4ImgWdg)

        // CONTROLLER
        WdgBegin(CLISD_ABSCONTAINER, ControllerCtnr)
            WdgAbsContainerCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_CTNR_CONTROLLER_POS_X, EMUAPP_KEYPAD_SETTINGS_CTNR_CONTROLLER_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_CTNR_CONTROLLER_WIDTH, EMUAPP_KEYPAD_SETTINGS_CTNR_CONTROLLER_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER, ControllerCtnr)

        // CONTROLLER OK
        WdgBegin(CLSID_BUTTONWIDGET, ControllerOKBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_OK_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_OK_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_SETTING_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_SETTING_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_LSK_N_OK, EMU_IMG_SETTING_BTN, EMU_IMG_SETTING_BTN_PRESSED})
            WdgButtonSetUnpressedTextColorRC(RGBCOLOR_WHITE)
        WdgEnd(CLSID_BUTTONWIDGET, ControllerOKBtnWdg)

        // CONTROLLER CANCEL
        WdgBegin(CLSID_BUTTONWIDGET, ControllerCancelBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CANCEL_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CANCEL_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_SETTING_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_SETTING_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_RSK_N_CANCEL, EMU_IMG_SETTING_BTN, EMU_IMG_SETTING_BTN_PRESSED})
            WdgButtonSetUnpressedTextColorRC(RGBCOLOR_WHITE)
        WdgEnd(CLSID_BUTTONWIDGET, ControllerCancelBtnWdg)

        WdgBegin(CLSID_IMAGEWIDGET, ControllerBGImgWdg)
            WdgImageCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_IMG_CONTROLLER_BG_POS_X, EMUAPP_KEYPAD_SETTINGS_IMG_CONTROLLER_BG_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_IMG_CONTROLLER_BG_WIDTH, EMUAPP_KEYPAD_SETTINGS_IMG_CONTROLLER_BG_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET, ControllerBGImgWdg)

        // EMU-8BIT A
        WdgBegin(CLSID_BUTTONWIDGET, EMU8BitABtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_EMU8BIT_A_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_EMU8BIT_A_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, EMU8BitABtnWdg)

        // EMU-8BIT B
        WdgBegin(CLSID_BUTTONWIDGET, EMU8BitBBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_EMU8BIT_B_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_EMU8BIT_B_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, EMU8BitBBtnWdg)

#if defined(__GAME_ENGINE_EMU_16BIT__)
        // SEMU-16BIT A
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitABtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_A_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_A_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitABtnWdg)

        // SEMU-16BIT B
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitBBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_B_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_B_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitBBtnWdg)

        // SEMU-16BIT X
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitXBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_X_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_X_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitXBtnWdg)

        // SEMU-16BIT Y
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitYBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_Y_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_Y_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitYBtnWdg)

        // SEMU-16BIT L
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitLBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_L_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_L_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitLBtnWdg)

        // SEMU-16BIT R
        WdgBegin(CLSID_BUTTONWIDGET, SEMU16BitRBtnWdg)
            WdgButtonCreateForWndRC({{EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_R_POS_X, EMUAPP_KEYPAD_SETTINGS_BTN_SEMU16BIT_R_POS_Y}, {EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_WIDTH, EMUAPP_KEYPAD_SETTINGS_BTN_CONTROLLER_CIRCLE_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, EMU_IMG_SELECT_FALSE, EMU_IMG_SELECT_TRUE})
        WdgEnd(CLSID_BUTTONWIDGET, SEMU16BitRBtnWdg)
#endif // __GAME_ENGINE_EMU_16BIT__

    WndEnd(EMU_WND_KEYPAD_SETTINGS)
#endif // __EMU_VIRTUAL_KEYPAD_ENABLE__

ApEnd(RS, CLSID_EMUAPP)

