/**
 * @file mmi_touchshortcutsrv_custom.h
 *
 * TouchShortcut Service Customization file
 *
 * @version $Id: mmi_touchshortcutsrv_custom.h 33814 2009-06-18 13:26:10Z brian.tsui $
 */
#ifndef __MMI_TOUCHSHORTCUTSRV_CUSTOM_H__
#define __MMI_TOUCHSHORTCUTSRV_CUSTOM_H__

#include "mmi_layout.h"

#if (TOUCHSHORTCUT_SHORTCUT_TOTAL == 4)
//defines the default launched function for each shortcut when support 4 shortcuts in layout
#define TOUCHSHORTCUT_SC1_FUNCID        SHORTCUTS_FUNC_NONE
#define TOUCHSHORTCUT_SC2_FUNCID        SHORTCUTS_FUNC_INBOX
#define TOUCHSHORTCUT_SC3_FUNCID        SHORTCUTS_FUNC_MUSICPLAYER
#define TOUCHSHORTCUT_SC4_FUNCID        SHORTCUTS_FUNC_PHONEBOOK
#define TOUCHSHORTCUT_SC5_FUNCID        SHORTCUTS_FUNC_NONE     // not support
#define TOUCHSHORTCUT_SC6_FUNCID        SHORTCUTS_FUNC_NONE     // not support
#elif  (TOUCHSHORTCUT_SHORTCUT_TOTAL == 5)
//defines the default launched function for each shortcut when support 4 shortcuts in layout
#ifdef __BIGBLUE_U8_PLUS__
#define TOUCHSHORTCUT_SC1_FUNCID        SHORTCUTS_FUNC_NONE
#define TOUCHSHORTCUT_SC2_FUNCID        SHORTCUTS_FUNC_PHONEBOOK
#define TOUCHSHORTCUT_SC3_FUNCID        SHORTCUTS_FUNC_INBOX
#define TOUCHSHORTCUT_SC4_FUNCID        SHORTCUTS_FUNC_CAMERA
#define TOUCHSHORTCUT_SC5_FUNCID        SHORTCUTS_FUNC_VIDEOPLAYER
#define TOUCHSHORTCUT_SC6_FUNCID        SHORTCUTS_FUNC_NONE     // not support
#elif defined(__LCM_QCIF_PLUS_MMI__)
#define TOUCHSHORTCUT_SC1_FUNCID        SHORTCUTS_FUNC_NONE
#define TOUCHSHORTCUT_SC2_FUNCID        SHORTCUTS_FUNC_INBOX
#define TOUCHSHORTCUT_SC3_FUNCID        SHORTCUTS_FUNC_PROFILES
#define TOUCHSHORTCUT_SC4_FUNCID        SHORTCUTS_FUNC_PHONEBOOK
#define TOUCHSHORTCUT_SC5_FUNCID        SHORTCUTS_FUNC_DIALING
#define TOUCHSHORTCUT_SC6_FUNCID        SHORTCUTS_FUNC_NONE     // not support
#else
#define TOUCHSHORTCUT_SC1_FUNCID        SHORTCUTS_FUNC_NONE
#define TOUCHSHORTCUT_SC2_FUNCID        SHORTCUTS_FUNC_INBOX
#define TOUCHSHORTCUT_SC3_FUNCID        SHORTCUTS_FUNC_PHONEBOOK
#define TOUCHSHORTCUT_SC4_FUNCID        SHORTCUTS_FUNC_DIALING
#define TOUCHSHORTCUT_SC5_FUNCID        SHORTCUTS_FUNC_MUSICPLAYER
#define TOUCHSHORTCUT_SC6_FUNCID        SHORTCUTS_FUNC_NONE     // not support
#endif
#endif

#endif /* __MMI_TOUCHSHORTCUTSRV_CUSTOM_H__ */
