/**
* @file mmi_dictapp.h
*
* State Machine Application - DICTAPP
* Generated by XFSM v1.0, CodeVer=v0.24  2009-02-02, 11:25:57
*
* Class Id: CLSID_DICTAPP
* 
*
* @version $Id$
*/
#ifndef __MMI_DICT_H__
#define __MMI_DICT_H__

/*-------------------------------------------------------------------------*/

#include "mmi_mae_common_def.h"

/**
 * Functions
 */
void DICT_Init(void);

MAE_Ret DICT_New(MAE_ClsId id, void **ppObj);

/*-------------------------------------------------------------------------*/
#endif /* __MMI_DICT_H__ */
