
#if PQ_GRULE_UFSC_DYNAMIC_CONTRAST_ENABLE
 unsigned char MST_GRule_1920_DYNAMIC_CONTRAST_DSPY[PQ_GRULE_DYNAMIC_CONTRAST_LVL_NUM_DSPY]=
{
    PQ_GRule_DYNAMIC_CONTRAST_Off_DSPY,
    PQ_GRule_DYNAMIC_CONTRAST_On_DSPY,
};
#endif

