#ifndef __MMI_MPLAYERAPP_ID_H__
#define __MMI_MPLAYERAPP_ID_H__

#ifdef __APP_MMI_SMALLROM__
#define __MPLAYERAPP_SMALLROM__
#endif	// __APP_MMI_SMALLROM__

#ifdef __SLIM_MMI__
#define __MPLAYERAPP_SLIM_MMI__
#endif	// __SLIM_MMI__

typedef enum MplayerWndId_e_
{
    MPLAYER_WND_PLAYLISTS = WND_ID_APP_BASE,    //MP_PLAYLISTS_VIEW
    MPLAYER_WND_COVER_FLOW,                     //MP_COVER_FLOW_VIEW
    MPLAYER_WND_PLAYLISTCONTENT,                //MP_PLAYLISTCONTENT_VIEW
    MPLAYER_WND_NOWPLAYING,                     //MP_NOWPLAYING_VIEW
    MPLAYER_WND_NEWPLAYLIST,                    //MP_EDITOR_VIEW
    MPLAYER_WND_EDITPLAYLIST,                   //MP_EDITOR_VIEW
    MPLAYER_WND_CHANGEORDER,                    //MP_CHANGEORDER_VIEW
    MPLAYER_WND_DETAILS,                        //MP_DETAILS_VIEW
    MPLAYER_WND_EQSETTING,                      //MP_EQSETTING_VIEW
    MPLAYER_WND_TSSETTING,                      //MP_TSSETTING_VIEW
    MPLAYER_WND_REVERBSETTING,                  //MP_REVERBSETTING_VIEW
    MPLAYER_WND_CHANGE_COVER_MENU,              //MP_CHANGE_COVER_MENU_VIEW
    MPLAYER_WND_SONG_INFO,                      //MP_SONG_INFO_VIEW
    MPLAYER_WND_PLAYLIST_OPTION_MENU,           //NEW
    MPLAYER_WND_PLAYLISTCONTENT_OPTION_MENU,    //NEW
    MPLAYER_WND_NOWPLAYING_OPTION_MENU,         //NEW
    MPLAYER_WND_NEWPLAYLIST_OPTION_MENU,        //NEW
    MPLAYER_WND_EDITPLAYLIST_OPTION_MENU,       //NEW
    MPLAYER_WND_SRSSETTING,                     //NEW - SRS mode selection window
    MPLAYER_WND_SRSTYPE,                        //NEW - SRS type seleciton window
    MPLAYER_WND_SRSTYPE_OPTION_MENU,            //NEW - SRS type option menu window
    MPLAYER_WND_SRSPARAM,                       //NEW - SRS param adjust window
    MPLAYER_WND_SRSPARAM_OPTION_MENU ,          //NEW - SRS param option menu window
} MplayerWndId_e;

enum //MP_NOWPLAYING_VIEW_enum
{
    eMP_NOWPLAYING_ABSCONTAINER = APP_WDG_START,
#ifndef __MPLAYERAPP_SMALLROM__
    eMP_NOWPLAYING_BG_IMAGEWIDGET,
    eMP_NOWPLAYING_COVER_IMAGEWIDGET,
#endif
    eMP_NOWPLAYING_LYRICS_TEXTWIDGET,
    eMP_NOWPLAYING_TITLE_IMAGEWIDGET,
    eMP_NOWPLAYING_ALBUM_IMAGEWIDGET,
    eMP_NOWPLAYING_ARTIST_IMAGEWIDGET,
    eMP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET,
    eMP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET,
    eMP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET,
    eMP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET,
    eMP_NOWPLAYING_TITLE_TEXTWIDGET,
    eMP_NOWPLAYING_ALBUM_TEXTWIDGET,
    eMP_NOWPLAYING_ARTIST_TEXTWIDGET,
    eMP_NOWPLAYING_TIME_TEXTWIDGET,
    eMP_NOWPLAYING_REPEAT_IMAGEWIDGET,
    eMP_NOWPLAYING_LISTINDEX_TEXTWIDGET,
    eMP_NOWPLAYING_REPEAT_BUTTONWIDGET,
    eMP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET,
    eMP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET,
    eMP_NOWPLAYING_LYRICS_SWITCHICONWIDGET,
    eMP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET,
    eMP_NOWPLAYING_PLAY_BUTTONWIDGET,
    eMP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET,
#if defined(__MMI_BATTERY_ICON_DISPLAY__)
    eMP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET,
    eMP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET,
#endif
#ifdef __MPLAYERAPP_SMALLROM__
    eMP_NOWPLAYING_TITLEBAR_BG_IMAGEWIDGET,
    eMP_NOWPLAYING_BG_IMAGEWIDGET,
#endif
    eMP_NOWPLAYING_TICK_PROGRESS_BAR_INDICATORWIDGET,
#if defined(__LANTERN_BY_AUDIO__) && !defined(__MPLAYERAPP_SMALLROM__)
    eMP_NOWPLAYING_SEPCTRUM_SWITCHICONWIDGET,
    eMP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET,
    eMP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET,
    eMP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_ABSCONTAINER,
    eMP_NOWPLAYING_SPECTRUM_DEGREE_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_BG_LISTWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET,
    eMP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET,
#endif
#ifdef __3D_UI_MPLAYER__
    eMP_NOWPLAYING_SPECTRUMWIDGET,
    eMP_NOWPLAYING_INFO_ABSCONTAINER,
    eMP_NOWPLAYING_GLFOTOLIST_FLIPWIDGET,
    eMP_NOWPLAYING_GLFOTOLIST_WIDGET,
    eMP_NOWPLAYING_GLFOTOLIST_IMAGEWIDGET,
    eMP_NOWPLAYING_CONTROL_BAR_WIDGET,
    eMP_NOWPLAYING_CONTROL_BAR_IMAGEWIDGET,
    eMP_NOWPLAYING_INDICATOR_WIDGET,
    eMP_NOWPLAYING_DURATION_TOTAL_TEXTWIDGET,
    eMP_NOWPLAYING_GLALBUMEFFECT_WIDGET,
    eMP_NOWPLAYING_LIST_FLIPWIDGET,
    eMP_NOWPLAYING_LIST_ABSCONTAINER,
    eMP_NOWPLAYING_LIST_MENUWIDGET,
    eMP_NOWPLAYING_LIST_IMAGEWIDGET,
    eMP_NOWPLAYING_LIST_MENU_BUTTONWIDGET,
    eMP_NOWPLAYING_LIST_BACK_BUTTONWIDGET,
    eMP_NOWPLAYING_LYRIC_ABSCONTAINER,
    eMP_NOWPLAYING_LYRIC_IMAGEWIDGET,
    eMP_NOWPLAYING_LYRIC_MENU_BUTTONWIDGET,
    eMP_NOWPLAYING_LYRIC_BACK_BUTTONWIDGET,
    eMP_NOWPLAYING_FLIP_EFFECT_WIDGET,
    eMP_NOWPLAYING_MAIN_ANIM_CONTAINER,
#endif
}; //MP_NOWPLAYING_VIEW_enum

enum //MP_COVER_FLOW_VIEW_enum
{
	eMP_COVER_FLOW_ABSCONTAINER = APP_WDG_START,
	eMP_COVER_FLOW_LEFT_2_COVER_IMAGEWIDGET,
	eMP_COVER_FLOW_RIGHT_2_COVER_IMAGEWIDGET,
	eMP_COVER_FLOW_LEFT_1_COVER_IMAGEWIDGET,
	eMP_COVER_FLOW_RIGHT_1_COVER_IMAGEWIDGET,
	eMP_COVER_FLOW_MIDDLE_COVER_IMAGEWIDGET,
	eMP_COVER_FLOW_PLAYLIST_NAME_TEXTWIDGET,

	eMP_COVER_FLOW_PLAYLIST_GLCOVERFLOWWIDGET,
}; //MP_COVER_FLOW_VIEW_enum

enum //MP_SRS_SETTING_VIEW_enum
{
    eMP_SRS_SETTING_MFLCONTAINER = APP_WDG_START,
    eMP_SRS_SETTING_STATUS_CMNPICKWIDGET,
    eMP_SRS_SETTING_TYPE_CMNPICKWIDGET,
}; //MP_SRS_SETTING_VIEW_enum

enum //MP_SRS_PARAM_VIEW_enum
{
    eMP_SRS_PARAM_MFLCONTAINER = APP_WDG_START,
    eMP_SRS_PARAM_SCROLLBARWIDGET,
    eMP_SRS_PARAM_3DSPACE_CMNPICKWIDGET,
    eMP_SRS_PARAM_3DCENTER_CMNPICKWIDGET,
    eMP_SRS_PARAM_TRUBASS_CMNPICKWIDGET,
    eMP_SRS_PARAM_FOCUS_CMNPICKWIDGET,
    eMP_SRS_PARAM_DEFINITION_CMNPICKWIDGET,
}; //MP_SRS_PARAM_VIEW_enum

typedef enum
{
    MNU_MPLAYER_DISPLAY_PLAYLIST_OPTION = 0,
    MNU_MPLAYER_DISPLAY_VIEW,
    MNU_MPLAYER_DISPLAY_NOW_PLAYING,
    MNU_MPLAYER_DISPLAY_NEW_PLAYLIST,
    MNU_MPLAYER_DISPLAY_RENAME,
    MNU_MPLAYER_DISPLAY_DELETE,
    MNU_MPLAYER_DISPLAY_REPEAT,
    MNU_MPLAYER_DISPLAY_SHUFFLE,
    MNU_MPLAYER_DISPLAY_EQUALIZER,
    MNU_MPLAYER_DISPLAY_TIME_STRETCH,
    MNU_MPLAYER_DISPLAY_REVERB,
    MNU_MPLAYER_DISPLAY_3D_SURROUND,
    MNU_MPLAYER_DISPLAY_VIRTUAL_BASS,
    MNU_MPLAYER_DISPLAY_SRS,
    MNU_MPLAYER_DISPLAY_BACKGROUND_PLAY,
    MNU_MPLAYER_DISPLAY_LYRIC,
    MNU_MPLAYER_DISPLAY_SPECTRUM,
    MNU_MPLAYER_DISPLAY_SET_COVER,
    MNU_MPLAYER_VIEW_PLAYLIST_OPTION,
    MNU_MPLAYER_VIEW_PLAY,
    MNU_MPLAYER_VIEW_NOW_PLAYING,
    MNU_MPLAYER_VIEW_UPDATE_PLAYLIST,
    MNU_MPLAYER_VIEW_ADD_MUSIC,
    MNU_MPLAYER_VIEW_ADD_VIDEO,
    MNU_MPLAYER_VIEW_SEND,
    MNU_MPLAYER_VIEW_DELETE,
    MNU_MPLAYER_VIEW_REPEAT,
    MNU_MPLAYER_VIEW_SHUFFLE,
    MNU_MPLAYER_VIEW_EQUALIZER,
    MNU_MPLAYER_VIEW_3D_SURROUND,
    MNU_MPLAYER_VIEW_VIRTUAL_BASS,
    MNU_MPLAYER_VIEW_SRS,
    MNU_MPLAYER_VIEW_BACKGROUND_PLAY,
    MNU_MPLAYER_VIEW_TIME_STRETCH,
    MNU_MPLAYER_VIEW_REVERB,
    MNU_MPLAYER_VIEW_LYRIC,
    MNU_MPLAYER_VIEW_SPECTRUM,
    MNU_MPLAYER_VIEW_CHANGE_ORDER,
    MNU_MPLAYER_VIEW_SONG_INFO,
    MNU_MPLAYER_VIEW_DETAILS,
    MNU_MPLAYER_VIDEO_PLAYING_OPTION,
    MNU_MPLAYER_VIDEO_SEND,
    MNU_MPLAYER_VIDEO_REPEAT,
    MNU_MPLAYER_VIDEO_SHUFFLE,
    MNU_MPLAYER_VIDEO_EQUALIZER,
    MNU_MPLAYER_VIDEO_DETAILS,
    MNU_MPLAYER_NOW_PLAYING_OPTION,
    MNU_MPLAYER_NOW_PLAY,
    MNU_MPLAYER_NOW_PAUSE,
    MNU_MPLAYER_NOW_STOP,
    MNU_MPLAYER_NOW_REPEAT,
    MNU_MPLAYER_NOW_SHUFFLE,
    MNU_MPLAYER_NOW_EQUALIZER,
    MNU_MPLAYER_NOW_TIME_STRETCH,
    MNU_MPLAYER_NOW_REVERB,
    MNU_MPLAYER_TIME_STRETCH_x05,
    MNU_MPLAYER_TIME_STRETCH_x075,
    MNU_MPLAYER_TIME_STRETCH_x1,
    MNU_MPLAYER_TIME_STRETCH_x15,
    MNU_MPLAYER_TIME_STRETCH_x2,
    MNU_MPLAYER_REVERB,
    MNU_MPLAYER_REVERB_NONE,
    MNU_MPLAYER_REVERB_CHURCH,
    MNU_MPLAYER_REVERB_BATHROOM,
    MNU_MPLAYER_REVERB_MEDIUMCONCERT,
    MNU_MPLAYER_REVERB_SMALLCLUB,
    MNU_MPLAYER_REVERB_CAVE,
    MNU_MPLAYER_NOW_3D_SURROUND,
    MNU_MPLAYER_NOW_VIRTUAL_BASS,
    MNU_MPLAYER_NOW_SRS,
    MNU_MPLAYER_NOW_BACKGROUND_PLAY,
    MNU_MPLAYER_NOW_LYRIC,
    MNU_MPLAYER_NOW_SPECTRUM,
    MNU_MPLAYER_NOW_DETAILS,
    MNU_MPLAYER_NOW_SONG_INFO,
    MNU_MPLAYER_REPEAT,
    MNU_MPLAYER_REPEAT_OFF,
    MNU_MPLAYER_REPEAT_ONE,
    MNU_MPLAYER_REPEAT_ALL,
    MNU_MPLAYER_EQUALIZER,
    MNU_MPLAYER_EQUALIZER_NORMAL,
    MNU_MPLAYER_EQUALIZER_BASS,
    MNU_MPLAYER_EQUALIZER_CLASSIC,
    MNU_MPLAYER_EQUALIZER_TREBLE,
    MNU_MPLAYER_EQUALIZER_LIVE,
    MNU_MPLAYER_EQUALIZER_ROCK,
    MNU_MPLAYER_BACKGROUND_PLAY,
    MNU_MPLAYER_BACKGROUND_OFF,
    MNU_MPLAYER_BACKGROUND_ON,
    MNU_MPLAYER_3D_SURROUND,
    MNU_MPLAYER_SURROUND_OFF,
    MNU_MPLAYER_SURROUND_ON,
    MNU_MPLAYER_VIRTUAL_BASS,
    MNU_MPLAYER_VIRTUAL_BASS_OFF,
    MNU_MPLAYER_VIRTUAL_BASS_ON,
    MNU_MPLAYER_SRS_OFF,
    MNU_MPLAYER_SRS_ON,
    MNU_MPLAYER_SRS_TYPE_NORMAL,
    MNU_MPLAYER_SRS_TYPE_CLASSIC,
    MNU_MPLAYER_SRS_TYPE_BASS,
    MNU_MPLAYER_SRS_TYPE_HIPHOP,
    MNU_MPLAYER_SRS_TYPE_PERFORM,
    MNU_MPLAYER_SRS_OPT_ACTIVATE,
    MNU_MPLAYER_SRS_OPT_PERSONALIZE,
    MNU_MPLAYER_SRS_OPT_CHANGE,
    MNU_MPLAYER_SRS_OPT_RESTORE,
    MNU_MPLAYER_COVER_SELECT,
    MNU_MPLAYER_COVER_USE_DEFAULT,
    MNU_MPLAYER_COVER_SELECT_PICTURE,
    MNU_MPLAYER_LYRIC_SETTING,
    MNU_MPLAYER_LYRIC_OFF,
    MNU_MPLAYER_LYRIC_ON,
    MNU_MPLAYER_SPECTRUM_OFF,
    MNU_MPLAYER_SPECTRUM_ON,
    MNU_MPLAYER_SEEK_CANCEL,
    MNU_COM_OPTION2_OFF,
    MNU_COM_OPTION2_ON,
}MplayerMenuId_e;

#endif //__MMI_MPLAYERAPP_ID_H__

