/**
 * @file	mae_rai_id_priv.h
 * @brief	This file defines internal RAI ID used in MAE.
 * @version	$Id: mae_rai_id_priv.h 1765 2009-09-11 13:34:03Z kenny.wu $
 */
#ifndef __MAE_RAI_ID_PRIV_H__
#define __MAE_RAI_ID_PRIV_H__

#include "mmi_common_custom.h"
#include "mmi_mae_rai_id.h"
#include "mdl_vm_rai_id.h"

#define MAE_RAI_SIZE_MAX ( 30 * 1024 ) //30k bytes

enum
{
	MAE_FS_RAI_DATAMGR_START =MAE_FS_RAI_START_ID,
	MMI_FS_RAI_ITEM_EVENT_TABLE_START = MAE_FS_RAI_DATAMGR_START,
	MMI_FS_RAI_ITEM_EVENT_TABLE_END = (MMI_FS_RAI_ITEM_EVENT_TABLE_START+MAE_DATAMGR_EVENT_TABLE_SIZE-1),
	MMI_FS_RAI_ITEM_EVENT_EXCEPTION_TABLE_START,
	MMI_FS_RAI_ITEM_EVENT_EXCEPTION_TABLE_END = (MMI_FS_RAI_ITEM_EVENT_EXCEPTION_TABLE_START+MAE_DATAMGR_EVENT_EXCEPTION_TABLE_SIZE-1),
	MMI_FS_RAI_ITEM_LOG_TABLE_START,
	MMI_FS_RAI_ITEM_LOG_TABLE_END = (MMI_FS_RAI_ITEM_LOG_TABLE_START+MAE_DATAMGR_LOG_TABLE_SIZE-1),
	MMI_FS_RAI_ITEM_TASK_TABLE_START,
	MMI_FS_RAI_ITEM_TASK_TABLE_END = (MMI_FS_RAI_ITEM_TASK_TABLE_START+MAE_DATAMGR_TASK_TABLE_SIZE-1),
	MMI_FS_RAI_ITEM_DRM_RO_TABLE_START,
	MMI_FS_RAI_ITEM_DRM_RO_TABLE_END = (MMI_FS_RAI_ITEM_DRM_RO_TABLE_START+MAE_DATAMGR_DRM_RO_TABLE_SIZE-1),
	MMI_FS_RAI_ITEM_EVENT_EXCEPTION_TABLE_UID,
	MMI_FS_RAI_ITEM_LOG_TABLE_UID,
	MMI_FS_RAI_ITEM_TASK_TABLE_UID,
    MAE_FS_RAI_DATAMGR_END,
};

#endif /*__MAE_RAI_ID_PRIV_H__ */
