/**
 * @file mae_gps_priv.h
 *
 * Service without using State Machine  - GPS
 * Generated by AP Designer v0.24, 2008-17-12 08:49
 *
 * @version $Id: mae_gps_priv.h 910 2009-05-18 13:45:14Z steve.lee $
 */
#ifndef __MAE_GPS_PRIV_H__
#define __MAE_GPS_PRIV_H__

#include "mmi_mae_common_def.h"
#include "mmi_mae_gps.h"

/**
 * Application structure
 */
typedef struct
{
    DECLARE_FUNCTBL(IGPS);	// function table pointer
    u32		nRefCnt;		// reference count
    /* Add custom fields below */
    boolean    bIsTerminated;
    MAEGpsAppId_e    eAppId;
    MAEGpsCmd_e      eCmdId;
    PfnGPSCallback    pfnCallBack;
    void    *pUserData;
} MAE_GPS_t;

#endif /* __MAE_GPS_PRIV_H__ */
