ApBegin(RS,CLSID_SENDVIAAPP)
    WndBegin(SENDVIA_WND_MENU)
        WdgBegin(CLSID_VTMMENU, vtmMenu)
#ifdef __MMI_KMX_TT__
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SEND_VIA,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,5,0,0})
            VtmCreateMenuDataRC(5, {
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_SMS}, {IMG_NULL_ID, TXT_LTL_N_SMS}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_MMS}, {IMG_NULL_ID, TXT_LTL_N_MMS}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_BLUETOOTH}, {IMG_NULL_ID, TXT_LTL_N_BLUETOOTH}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_EMAIL}, {IMG_NULL_ID, TXT_LTL_N_EMAIL}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_WEIBO}, {IMG_NULL_ID, TXT_LTL_N_SEND_TO_WEIBO}} })
#else
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SEND_VIA,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4, {
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_SMS}, {IMG_NULL_ID, TXT_LTL_N_SMS}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_MMS}, {IMG_NULL_ID, TXT_LTL_N_MMS}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_BLUETOOTH}, {IMG_NULL_ID, TXT_LTL_N_BLUETOOTH}},
            	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_SENDVIA_SEND_VIA_EMAIL}, {IMG_NULL_ID, TXT_LTL_N_EMAIL}} })
#endif
        WdgEnd(CLSID_VTMMENU, vtmMenu)
    WndEnd(SENDVIA_WND_MENU)
ApEnd(RS,CLSID_SENDVIAAPP)

