#ifndef __MMI_CDWAPAPP_ID_H__
#define __MMI_CDWAPAPP_ID_H__

typedef enum
{
    CDWAP_WND_MAINPAGE_EMPTY = WND_ID_APP_BASE,
    CDWAP_WND_MAINPAGELIST,
    CDWAP_WND_DUALSIM,      // the first window of WAP
    CDWAP_WND_OPTION_MENU,
    CDWAP_WND_SETTINGS,         // window stack
    CDWAP_WND_LAUNCH_AP,
    CDWAP_WND_FILE_MANAGE,
    CDWAP_WND_POPUP_MENU,
    CDWAP_WND_EDIT_BOOKMARK,    // window stack
    CDWAP_WND_INPUT_URL,            // window stack
    CDWAP_WND_INPUT_URL_OPTION_MENU,
    CDWAP_WND_MARK_MODE,
    CDWAP_WND_MOVE_FILES,
    CDWAP_WND_VIEW_PAGE_IMAGE,      // window stack
    CDWAP_WND_SAVE_BOOKMARK_OR_PAGE,    // window stack
    CDWAP_WND_EDIT_FOLDER,      // window stack
    CDWAP_WND_OPEN_URL,
    CDWAP_WND_EXPLORER,
    CDWAP_WND_SETTINGS_RADIO_MENU_FONT_SIZE,
    CDWAP_WND_EDIT_CONTENT,         // window stack
#ifdef __MMI_OMA_DRM_V1__
    CDWAP_WND_VIEW_OMA_DD,
#endif
    CDWAP_WND_MARK_OPTION_MENU,
    CDWAP_WND_EDIT_OPTION_MENU
} CdWapWndId_e;

#ifdef __MMI_OMA_DRM_V1__
typedef enum
{
    CDWAP_VIEW_OMA_DD_CONTAINER=APP_WDG_START,
    CDWAP_VIEW_OMA_DD_PORT_WDG,
    CDWAP_VIEW_OMA_DD_SCROLLBAR,
    CDWAP_VIEW_OMA_DD_NAME_WDG,
    CDWAP_VIEW_OMA_DD_TYPE_WDG,
    CDWAP_VIEW_OMA_DD_SIZE_WDG,
    CDWAP_VIEW_OMA_DD_VENDOR_WDG,
    CDWAP_VIEW_OMA_DD_URI_WDG,
    CDWAP_VIEW_OMA_DD_DESCRIPTION_WDG,
} CdWapViewOMADD_e;
#endif

typedef enum
{
    CDWAP_EDITBOOKMARK_MFLCONTAINER=APP_WDG_START,
    CDWAP_EDITBOOKMARK_NAME,
    CDWAP_EDITBOOKMARK_URL,
}CdWapEditBookMark_e;

typedef enum
{
    CDWAP_SETTINGS_MFL=APP_WDG_START,
    CDWAP_SETTINGS_DOUBLE_TEXT,
    CDWAP_SETTINGS_DOUBLE_FONT_SIZE_TEXT,
    CDWAP_SETTINGS_STORAGE_TYPE_DOUBLE_TEXT,
} CdWapSettings_e;

typedef enum
{
    CDWAP_EXPLORER_PAGE_TITLE = APP_WDG_START,
    CDWAP_EXPLORER_PAGE_SCROLLBAR,
    CDWAP_EXPLORER_PAGE_VIEWERCONTAINER,
    CDWAP_EXPLORER_PAGE_ANIMATE,
	CDWAP_EXPLOREE_PAGE_TOPTEXTWDG,
	CDWAP_EXPLOREE_PAGE_BOTTOMTEXTWDG,
	CDWAP_EXPLOREE_PAGE_MARQUEEWDG,
    CDWAP_EXPLOREE_PAGE_TEXTWDG,
    CDWAP_EXPLOREE_PAGE_BITMAP,
    CDWAP_EXPLOREE_PAGE_IMAGE,
    CDWAP_EXPLOREE_PAGE_BUTTON,
    CDWAP_EXPLOREE_PAGE_CHECKBOX,
    CDWAP_EXPLOREE_PAGE_RADIOBOX,
    CDWAP_EXPLOREE_PAGE_SINGLELIST,
    CDWAP_EXPLOREE_PAGE_MULTILIST,

    CDWAP_EXPLORER_PAGE_END
}CdWapExplorerPage_e;

typedef enum
{
    CDWAP_INPUTURL_TITLE=APP_WDG_START,
    CDWAP_INPUTURL_INPUT,
    CDWAP_INPUTURL_MENU,
} CdWapInputUrlView_e;

typedef enum
{
	MNU_CDWAPAPP_CDWAPAPP = 0,
	MNU_CDWAPAPP_CDWAP_OPTION,
	MNU_CDWAPAPP_OPEN,                       //open
	MNU_CDWAPAPP_HISTORY,                    //history
	MNU_CDWAPAPP_NEXT,
	MNU_CDWAPAPP_BACK,
	MNU_CDWAPAPP_GUIDANCE,                   //guidance
	MNU_CDWAPAPP_BOOKMARK,
	MNU_CDWAPAPP_GOTOURL,
	MNU_CDWAPAPP_HOMEPAGE,
	MNU_CDWAPAPP_RECORD,           /* long-term history for future re-use */
	MNU_CDWAPAPP_MANAGE_BOOKMARK,            //bookmark management
	MNU_CDWAPAPP_SET_HOME_PAGE,
	MNU_CDWAPAPP_CREATE_BOOKMARK,
	MNU_CDWAPAPP_EDIT_BOOKMARK,
	MNU_CDWAPAPP_DELETE_BOOKMARK,
	MNU_CDWAPAPP_MOVE_TO,
	MNU_CDWAPAPP_LOCAL_PAGE,                 //local page management
	MNU_CDWAPAPP_DELETE_LOCAL_PAGE,
	MNU_CDWAPAPP_MOVE_LOCAL_PAGE,
	MNU_CDWAPAPP_FOLDER,                     //folder management
	MNU_CDWAPAPP_NEW_FOLDER,
	MNU_CDWAPAPP_DELETE_FOLDER,
	MNU_CDWAPAPP_RENAME_FOLDER,
	MNU_CDWAPAPP_REFRESH,                    //refresh
	MNU_CDWAPAPP_TOOLS,                      //tools
	MNU_CDWAPAPP_SAVE_IMAGE,
	MNU_CDWAPAPP_SAVE_BOOKMARK,
	MNU_CDWAPAPP_SAVE_PAGE,
	MNU_CDWAPAPP_SET_HOMEPAGE,
	MNU_CDWAPAPP_SEND_URL,
	MNU_CDWAPAPP_MARK,                       //enter mark mode
	MNU_CDWAPAPP_CLEAN,                      //clean cache
	MNU_CDWAPAPP_SETTING,                    //setting
	MNU_CDWAPAPP_DOWNLOAD_DIRECTORY,         //download folder
	MNU_CDWAPAPP_EXIT,                       //exit CDWAP
	MNU_CDWAPAPP_EXIT_EXPLOR,                //exit explorer on viewing bookmark/localpage
	MNU_CDWAPAPP_MARK_OPTION,
	MNU_CDWAPAPP_MO_MARK,
	MNU_CDWAPAPP_MO_UNMARK,
	MNU_CDWAPAPP_MO_MARK_ALL,
	MNU_CDWAPAPP_MO_UNMARK_ALL,
	MNU_CDWAPAPP_MO_DELETE,
	MNU_CDWAPAPP_INPUT_URL_CLEAR,
	MNU_CDWAPAPP_INPUT_URL_CLEAR_ALL,
#ifdef __3G_RIL_MMI__
    MNU_CDWAPAPP_DIAL,
#endif //__3G_RIL_MMI__
}CdwapMenuId_e;

typedef enum
{
    CDWAPAPP_FONT_SIZE_SMALLEST = 0,
    CDWAPAPP_FONT_SIZE_SMALL,
    CDWAPAPP_FONT_SIZE_NORMAL,
    CDWAPAPP_FONT_SIZE_LARGE,
    CDWAPAPP_FONT_SIZE_LARGEST,

    CDWAPAPP_FONT_SIZE_NUM,
}CdWapFontSize_e;

#endif //__MMI_CDWAPAPP_ID_H__

