/**
 *
 * @file    ven_apptbl.h
 * @brief
 *
 * @author
 * @version $Id$
 *
 */
#ifndef __VEN_APPTBL_H_
#define __VEN_APPTBL_H_
#include "ven_appdef_pub.h"
/***************************************************************************
 Description:
 This file defines the following tables
 1. Task table for 3rd-party vendor
 2. Class ID table for 3rd-party vendor
 3. Name table for 3rd-party vendor
 4. Integration table for 3rd-party vendor
***************************************************************************/

#ifdef __DECLARE_VEN_TASK_TABLE__
/***************************************************************************
 Task configuration table
 1. Define stack size for each task
 2. Define priority for each task
***************************************************************************/

/*
 Number of bytes for stack size
 Ex. 1024 / 2048 / 4000 / 8000 / 16000
*/

#ifdef __TENCENT_MCARE__
#define VEN_TASK_STACK_1 16000
#elif defined(__SKYENGINE__)
#define VEN_TASK_STACK_1 8000
#else
#define VEN_TASK_STACK_1 1600
#endif //__TENCENT_MCARE__

#if defined(__SXMENGINE__) ||defined(__ZYUE_ENGINE__)
#define VEN_TASK_STACK_2 16000
#else //__SXMENGINE__
#define VEN_TASK_STACK_2 1600
#endif //__SXMENGINE__

#ifdef __SRE__
#define VEN_TASK_STACK_3 16000
#elif defined(__TTS__)
#define VEN_TASK_STACK_3 8000
#elif defined(__MMI_KMX_TT__)
#define VEN_TASK_STACK_3 6000
#else
#define VEN_TASK_STACK_3 1600
#endif //__SRE__

#ifdef __MMI_GTSBOX__
#define VEN_TASK_STACK_4 8000
#else
#define VEN_TASK_STACK_4 1600
#endif //__MMI_GTSBOX__

#define VEN_TASK_STACK_5 1600

#ifdef __ZMOL__
#define VEN_TASK_STACK_6 8000
#else
#define VEN_TASK_STACK_6 1600
#endif

/*
 Priority of each task
 Priority > MMI task
 (VEN_TASK_PRIO_1 > VEN_TASK_PRIO_2 > VEN_TASK_PRIO_3 > VEN_TASK_PRIO_4 > VEN_TASK_PRIO_5)

 Priority < MMI task
 (VEN_TASK_PRIO_6 > VEN_TASK_PRIO_7 > VEN_TASK_PRIO_8 > VEN_TASK_PRIO_9 > VEN_TASK_PRIO_10)
*/
#define VEN_TASK_1_PRIO VEN_TASK_PRIO_3
#define VEN_TASK_2_PRIO VEN_TASK_PRIO_4
#define VEN_TASK_3_PRIO VEN_TASK_PRIO_6
#define VEN_TASK_4_PRIO VEN_TASK_PRIO_9
#define VEN_TASK_5_PRIO VEN_TASK_PRIO_10
#define VEN_TASK_6_PRIO VEN_TASK_PRIO_2


#endif // __DECLARE_VEN_TASK_TABLE__

#ifdef DECLARE_VEN_APP_CLSID
/***************************************************************************
 Vendor class id configuration table
 1. Define class ID for each 3rd-party vendor
***************************************************************************/
/*
 Declare new vendor class id here. Please use a meaningful name
 Ex.

 DECLARE_VEN_APP_CLSID(CLSID_JAVAAPP)
 DECLARE_VEN_APP_CLSID(CLSID_MSNAPP)
 DECLARE_VEN_APP_CLSID(CLSID_QQAPP)
*/
DECLARE_VEN_APP_CLSID(CLSID_SDKV2APP)

/*===== Add new 3rd party class id below this line =====*/


#if defined (__TENCENT_MCARE__) && defined(__TENCENT_MCARE_QXIN__)
DECLARE_VEN_APP_CLSID(CLSID_TENCENT_MCARE_QXIN)
#else
DECLARE_VEN_APP_CLSID(CLSID_TENCENT_MCARE)
#endif


#ifdef __FAKE_VENDOR__
DECLARE_VEN_APP_CLSID(CLSID_FAKE_VENDOR_APP)
#endif
#ifdef __SKYENGINE__
DECLARE_VEN_APP_CLSID(CLSID_SKY_ENGINE_QQ_APP)
DECLARE_VEN_APP_CLSID(CLSID_SKY_ENGINE_GAME_APP)
#endif
#ifdef __ZMOL__
DECLARE_VEN_APP_CLSID(CLSID_ZMOL_APP)
#endif
#ifdef __SXMENGINE__
DECLARE_VEN_APP_CLSID(CLSID_SXM_VCHAT)
DECLARE_VEN_APP_CLSID(CLSID_SXM_BOOK)
DECLARE_VEN_APP_CLSID(CLSID_SXM_GAME)
#endif
#ifdef __TTS__
DECLARE_VEN_APP_CLSID(CLSID_TTS)
#endif
#ifdef __SRE__
DECLARE_VEN_APP_CLSID(CLSID_SRE)
#endif /// __SRE__
#ifdef __SDK_MMI_VENDOR_ENTRY__
DECLARE_VEN_APP_CLSID(CLSID_SOCKET_TEST1)
DECLARE_VEN_APP_CLSID(CLSID_SOCKET_TEST2)
#endif/* __SDK_MMI_VENDOR_ENTRY__ */

#ifdef __EMAIL_MMI__
DECLARE_VEN_APP_CLSID(CLSID_EMAIL)
#endif

#ifdef __MMI_KMX_TT__
DECLARE_VEN_APP_CLSID(CLSID_KMX_TT_APP)
#endif

#ifdef __NCCQQ_MMI__
DECLARE_VEN_APP_CLSID(CLSID_QQCLIENT)
#endif // #ifdef __NCCQQ_MMI__

DECLARE_VEN_APP_CLSID(CLSID_3RD_ZHANGYUE_EBOOK)

#ifdef __MMI_GTSBOX__
DECLARE_VEN_APP_CLSID(CLSID_GTSBOX_APP)
#endif

/*===== Add new 3rd party class id above this line =====*/
#endif


#ifdef __DECLARE_VEN_MMI_TABLE__
/***************************************************************************
 Vendor name configuration table
***************************************************************************/
/*
 Declaration rule:
 DECLARE_VEN_NAME(VEN_XXX, English name, Simplified Chinese, Traditional Chinese)

 Ex.
 DECLARE_VEN_NAME(VEN_JAVA, L"Java Applications", L"Java Applications", L"Java Applications")
*/
/*===== Do not modify anything below this line =====*/
/* Let VEN_ID start from 1 */
DECLARE_VEN_NAME(VEN_ID_NULL, L"", L"", L"")
#ifdef __SDK_MMI_TEST__
DECLARE_VEN_NAME(VEN_DEFAULT, L"SDK v2 Test", L"SDK v2 \x6D4B\x8BD5\x0000", L"SDK v2 \x6E2C\x8A66\x0000")
#else
DECLARE_VEN_NAME(VEN_DEFAULT, L"Default VendorApp", L"Default VendorApp", L"Default VendorApp")
#endif
DECLARE_VEN_NAME(VEN_WAP, L"", L"", L"")

DECLARE_VEN_NAME(VEN_JAVA, L"", L"", L"")
DECLARE_VEN_NAME(VEN_JVM, L"", L"", L"")

DECLARE_VEN_NAME(VEN_CDWAP, L"", L"", L"")
DECLARE_VEN_NAME(VEN_EMAIL, L"", L"", L"")
DECLARE_VEN_NAME(VEN_QQ, L"QQ", L"QQ", L"QQ")
DECLARE_VEN_NAME(VEN_TEMOBI_LBS, L"", L"", L"")
DECLARE_VEN_NAME(VEN_WLAN, L"", L"", L"")
DECLARE_VEN_NAME(VEN_AUTO_TEST, L"", L"", L"")
DECLARE_VEN_NAME(VEN_HTTP, L"", L"", L"")
DECLARE_VEN_NAME(VEN_RTSP, L"", L"", L"")

DECLARE_VEN_NAME(VEN_PLATFORM, L"", L"", L"")
DECLARE_VEN_NAME(VEN_NUMBER, L"", L"", L"")
/*===== Do not modify anything above this line =====*/
/*===== Add new 3rd party name below this line =====*/

DECLARE_VEN_NAME(VEN_FAKE_VENDOR, L"Fake Vendor", L"Fake Vendor", L"Fake Vendor")
DECLARE_VEN_NAME(VEN_TENCENT_MCARE, L"MCare", L"MCare", L"MCare")
DECLARE_VEN_NAME(VEN_SKY_ENGINE, L"Skyengine", L"Skyengine", L"Skyengine")
DECLARE_VEN_NAME(VEN_ZMOL, L"ZMOL", L"ZMOL", L"ZMOL")
DECLARE_VEN_NAME(VEN_SXM_ENGINE, L"SxmEngine", L"SxmEngine", L"SxmEngine")
DECLARE_VEN_NAME(VEN_SXM_ENGINE_EX, L"SxmEngine_EX", L"SxmEngine_EX", L"SxmEngine_EX")
DECLARE_VEN_NAME(VEN_TTS, L"TTS", L"TTS", L"TTS")
DECLARE_VEN_NAME(VEN_SRE, L"SRE", L"SRE", L"SRE")
DECLARE_VEN_NAME(VEN_SOCKET_TEST1, L"VenSocketTest1", L"VenSocketTest1", L"VenSocketTest1")
DECLARE_VEN_NAME(VEN_SOCKET_TEST2, L"VenSocketTest2", L"VenSocketTest2", L"VenSocketTest2")
DECLARE_VEN_NAME(VEN_3RD_ZHANGYUE_EBOOK, L"Zhangyue-ebook", L"Zhangyue-ebook", L"Zhangyue-ebook")
DECLARE_VEN_NAME(VEN_GTSBOX_APP, L"GTSBOX_APP", L"GTSBOX_APP", L"GTSBOX_APP")
 
#ifdef __MMI_KMX_TT__
DECLARE_VEN_NAME(VEN_KMX_TT, L"KMXTT", L"KMXTT", L"KMXTT")
#endif
/*===== Add new 3rd party name above this line =====*/

#endif // __DECLARE_VEN_MMI_TABLE__

/***************************************************************************
 Vendor application configuration table
***************************************************************************/
DECLARE_VEN_APP_TABLE(VEN_INTEGRATION)
/*===== Do not modify anything below this line =====*/
/* Let VEN_ID start from 1 */
MAKE_VEN_APP_ITEM_BEGIN(E_VEN_ID_NULL, VEN_ID_NULL, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#ifdef __SDK_MMI_VENDOR_ENTRY__
DECLARE_VEN_APP_INIT_FUNC(Ven_Init)
MAKE_VEN_APP_ITEM(E_VEN_DEFAULT, VEN_DEFAULT, MNU_STYLE_DYNAMIC, CLSID_VENDORAPP, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, Ven_Init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_DEFAULT, VEN_DEFAULT, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif // __SDK_MMI_VENDOR_ENTRY__
#include "ven_appplatform_pub.h"
/*===== Do not modify anything above this line =====*/



/*===== Add new 3rd party application below this line =====*/
/*
 Rule:
 1. Change XXX of E_VEN_XXX/XXX_Init to a meaningful word (brief function description or vendor product name).
 2. Change X of VEN_TASK_X to a number from 1 to 5
*/
//DECLARE_VEN_APP_INIT_FUNC(XXX_Init)
//MAKE_VEN_APP_ITEM(E_VEN_XXX, VEN_XXX, MNU_STYLE_STATIC, CLSID_XXX_APP, VEN_TASK_X, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, XXX_Init, NULL, NULL, NULL, NULL)

/*===== Add new 3rd party application above this line =====*/
#ifdef __FAKE_VENDOR__
DECLARE_VEN_APP_INIT_FUNC(FakeVendor_Init)
MAKE_VEN_APP_ITEM(E_VEN_FAKE_VENDOR, VEN_FAKE_VENDOR, MNU_STYLE_DYNAMIC, CLSID_FAKE_VENDOR_APP, VEN_TASK_5, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, FakeVendor_Init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_FAKE_VENDOR, VEN_FAKE_VENDOR, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#if defined (__TENCENT_MCARE__) && defined(__TENCENT_MCARE_QXIN__)
DECLARE_VEN_APP_INIT_FUNC(TencentMCare_Init)
MAKE_VEN_APP_ITEM(E_VEN_TENCENT_MCARE, VEN_TENCENT_MCARE, MNU_STYLE_DYNAMIC, CLSID_TENCENT_MCARE_QXIN, VEN_TASK_1, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, TencentMCare_Init, NULL, NULL, NULL, NULL)
#elif defined (__TENCENT_MCARE__)
DECLARE_VEN_APP_INIT_FUNC(TencentMCare_Init)
MAKE_VEN_APP_ITEM(E_VEN_TENCENT_MCARE, VEN_TENCENT_MCARE, MNU_STYLE_DYNAMIC, CLSID_TENCENT_MCARE, VEN_TASK_1, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, TencentMCare_Init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_TENCENT_MCARE, VEN_TENCENT_MCARE, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif





#ifdef __SKYENGINE__
DECLARE_VEN_APP_INIT_FUNC(SkyEngine_Init)
MAKE_VEN_APP_ITEM(E_VEN_SKY_ENGINE, VEN_SKY_ENGINE, MNU_STYLE_DYNAMIC, CLSID_SKY_ENGINE_QQ_APP, VEN_TASK_1, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, SkyEngine_Init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_SKY_ENGINE, VEN_SKY_ENGINE, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __ZMOL__
#ifndef __SDK_SIMULATION__
DECLARE_VEN_APP_INIT_FUNC(zm_vendor_init)
MAKE_VEN_APP_ITEM(E_VEN_ZMOL, VEN_ZMOL, MNU_STYLE_DYNAMIC, CLSID_ZMOL_APP, VEN_TASK_6, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, zm_vendor_init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_ZMOL, VEN_ZMOL, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif
#else
MAKE_VEN_APP_ITEM(E_VEN_ZMOL, VEN_ZMOL, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __SXMENGINE__
DECLARE_VEN_APP_INIT_FUNC(sxm_apple_ven_init)
MAKE_VEN_APP_ITEM(E_VEN_SXM_ENGINE, VEN_SXM_ENGINE, MNU_STYLE_DYNAMIC, CLSID_SXM_VCHAT, VEN_TASK_2, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, sxm_apple_ven_init, NULL, NULL, NULL, NULL)
MAKE_VEN_APP_ITEM(E_VEN_SXM_ENGINE_EX, VEN_SXM_ENGINE_EX, MNU_STYLE_DYNAMIC, CLSID_SXM_VCHAT, VEN_TASK_2, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, sxm_apple_ven_init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_SXM_ENGINE, VEN_SXM_ENGINE, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
MAKE_VEN_APP_ITEM(E_VEN_SXM_ENGINE_EX, VEN_SXM_ENGINE_EX, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __TTS__
DECLARE_VEN_APP_INIT_FUNC(tts_app_init)
MAKE_VEN_APP_ITEM(E_VEN_TTS, VEN_TTS, MNU_STYLE_DYNAMIC, CLSID_TTS, VEN_TASK_3, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, tts_app_init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_TTS, VEN_TTS, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __SRE__
	DECLARE_VEN_APP_INIT_FUNC(DynLoader_Init)
	MAKE_VEN_APP_ITEM(E_VEN_SRE, VEN_SRE, MNU_STYLE_DYNAMIC, CLSID_SRE, VEN_TASK_3, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, DynLoader_Init, NULL, NULL, NULL, NULL)
#else
	MAKE_VEN_APP_ITEM(E_VEN_SRE, VEN_SRE, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __ZYUE_ENGINE__
#ifndef __SDK_SIMULATION__
DECLARE_VEN_APP_INIT_FUNC(pbk_app_init)
MAKE_VEN_APP_ITEM(E_VEN_3RD_ZHANGYUE_EBOOK, VEN_3RD_ZHANGYUE_EBOOK, MNU_STYLE_DYNAMIC, CLSID_3RD_ZHANGYUE_EBOOK, VEN_TASK_2, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, pbk_app_init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_3RD_ZHANGYUE_EBOOK, VEN_3RD_ZHANGYUE_EBOOK, MNU_STYLE_DYNAMIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif
#else
MAKE_VEN_APP_ITEM(E_VEN_3RD_ZHANGYUE_EBOOK, VEN_3RD_ZHANGYUE_EBOOK, MNU_STYLE_DYNAMIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __MMI_GTSBOX__
#ifndef __SDK_SIMULATION__
DECLARE_VEN_APP_INIT_FUNC(Gtsbox_Init)
MAKE_VEN_APP_ITEM(E_VEN_GTSBOX_ENGINE, VEN_GTSBOX_APP, MNU_STYLE_DYNAMIC, CLSID_GTSBOX_APP, VEN_TASK_4, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, Gtsbox_Init, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_GTSBOX_ENGINE, VEN_GTSBOX_APP, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif
#else
MAKE_VEN_APP_ITEM(E_VEN_GTSBOX_ENGINE, VEN_GTSBOX_APP, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif

#ifdef __SDK_MMI_VENDOR_ENTRY__
DECLARE_VEN_APP_INIT_FUNC(Ven_Init)
MAKE_VEN_APP_ITEM(E_VEN_SOCKET_TEST1, VEN_SOCKET_TEST1, MNU_STYLE_DYNAMIC, CLSID_SOCKET_TEST1, VEN_TASK_4, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, NULL, NULL, NULL, NULL, NULL)
MAKE_VEN_APP_ITEM(E_VEN_SOCKET_TEST2, VEN_SOCKET_TEST2, MNU_STYLE_DYNAMIC, CLSID_SOCKET_TEST2, VEN_TASK_5, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, NULL, NULL, NULL, NULL, NULL)
#else
MAKE_VEN_APP_ITEM(E_VEN_SOCKET_TEST1, VEN_SOCKET_TEST1, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
MAKE_VEN_APP_ITEM(E_VEN_SOCKET_TEST2, VEN_SOCKET_TEST2, MNU_STYLE_STATIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
#endif/* __SDK_MMI_VENDOR_ENTRY__ */ /// add for ut

#ifdef __MMI_KMX_TT__
DECLARE_VEN_APP_INIT_FUNC(KmxTT_Init)
MAKE_VEN_APP_ITEM(E_VEN_KMX_TT, VEN_KMX_TT, MNU_STYLE_DYNAMIC, CLSID_KMX_TT_APP, VEN_TASK_3, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, TRUE, KmxTT_Init, NULL, NULL, NULL, NULL)
#endif

    /*===== Do not modify anything below this line =====*/
    MAKE_VEN_APP_ITEM_END(E_VEN_VENDOR_NUMBER, VEN_NUMBER, MNU_STYLE_DYNAMIC, 0, VEN_TASK_NUM, CPU_SPEED_HIGH, VEN_UI_INT_NORMAL, VEN_DBG_GROUP_0, FALSE, NULL, NULL, NULL, NULL, NULL)
    /*===== Do not modify anything above this line =====*/
#endif  /* __VEN_APPTBL_H_ */

