ApBegin(RS,CLSID_EMAILAPP)
	WndBegin(EMAIL_WND_ACCOUNTLIST)
		WdgBegin(CLSID_VTMMENU,vtm_EMAIL_WND_ACCOUNTLIST)
			VtmCreateMenuRC({0,TXT_LIL_N_EMAIL,0,WDG_MENU_ITEM_TYPE_TEXT,0,0,0,0})
			VTMWdgBegin(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,EmialAccountListMenuWdg)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			VTMWdgEnd(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,EmialAccountListMenuWdg)
		WdgEnd(CLSID_VTMMENU,vtm_EMAIL_WND_ACCOUNTLIST)

		WndSetTitleRC({0,TXT_LIL_N_EMAIL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_ACCOUNTLIST)

	WndBegin(EMAIL_WND_ACCOUTLIST_OPTIONMENU)
		WdgBegin(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_ACCOUTLIST_OPTIONMENU)
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,6})
			VtmCreateOptionMenuDataRC(6,\
			{{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_OPEN_ACCOUNT},TXT_OIL1_N_OPEN_ACCOUNT},\
			{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_NEW_ACCOUNT},TXT_OIL1_N_NEW_ACCOUNT},\
			{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_EDIT_ACCOUNT},TXT_OIL1_N_EDIT_ACCOUNT},\
			{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_DELETE_ACCOUNT},TXT_OIL1_N_DELETE_ACCOUNT},\
			{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_SET_DEFEAULT_ACCOUNT},TXT_OIL1_N_SET_DEFEAULT_ACCOUNT},\
			{{TRUE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_EMAIL_ACCOUNT_SETTING},TXT_OIL1_N_ACCOUNT_SETTING}})
		WdgEnd(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_ACCOUTLIST_OPTIONMENU)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_ACCOUTLIST_OPTIONMENU)

	WndBegin(EMAIL_WND_NEWACCOUNT)
		WdgBegin(CLSID_VTMMENU,vtm_EMAIL_WND_NEWACCOUNT)
			VtmCreateMenuRC({0,TXT_OIL1_N_NEW_ACCOUNT,0,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0})
			VTMWdgBegin(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,EmailNewAccountMenuWdg)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT)
				WdgMenuSetCheckStyleRC(0)
				WdgMenuSetFirstItemRC(0)
			VTMWdgEnd(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,EmailNewAccountMenuWdg)
		WdgEnd(CLSID_VTMMENU,vtm_EMAIL_WND_NEWACCOUNT)

		WndSetTitleRC({0,TXT_OIL1_N_NEW_ACCOUNT})
		WndSetAllSoftkeyRC({SK_NEXT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_NEWACCOUNT)

	WndBegin(EMAIL_WND_PUBLICINPUT)
		WdgBegin(CLSID_VTMINPUT,vtm_EMAIL_WND_PUBLICINPUT)
			VtmCreateInputRC({0,0,0,0})
			VTMWdgBegin(CLSID_INPUTWIDGET,INPUT_INPUT_WDG,InputWidgetControl)
				WdgInputSetMultilineRC(TRUE)
				WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
				WdgCommonEnableScrollBarRC(SCROLL_STYLE_V_RIGHT)
				WdgInputSetSoftKeyBoardEnableRC(TRUE)
			VTMWdgEnd(CLSID_INPUTWIDGET,INPUT_INPUT_WDG,InputWidgetControl)
		WdgEnd(CLSID_VTMINPUT,vtm_EMAIL_WND_PUBLICINPUT)

		WndSetTitleRC({0,0})
		WndSetAllSoftkeyRC({SK_OPTION,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_PUBLICINPUT)

	WndBegin(EMAIL_WND_PUBLICINPUTOPTION)
		WdgBegin(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_PUBLICINPUTOPTION)
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
			VtmCreateOptionMenuDataRC(2,{{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_COMMON_TEXT_SAVE},TXT_OIL1_N_SAVE},{{TRUE|MENUMODEL_ITEM_HAS_CHILD,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_COMMON_TEXT_INPUT_MENU},TXT_OIL1_N_INPUT_MENU}})
			VTMWdgBegin(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,PublicInuputOptionMenuWdg)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			VTMWdgEnd(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,PublicInuputOptionMenuWdg)
		WdgEnd(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_PUBLICINPUTOPTION)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_PUBLICINPUTOPTION)

	WndBegin(EMAIL_WND_EDITACCOUNT)
		WdgBegin(CLSID_VTMTABMENU,vtm_EMAIL_WND_EDITACCOUNT)
			VtmCreateTabMenuRC({0,0,3})
			VtmCreateTabMenuDataRC(3,{{EMAIL_IMG_OPTION_PRESSED,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0},{EMAIL_IMG_PREVIOUS_UNPRESSED,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0},{EMAIL_IMG_NEXT_UNPRESSED,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0}})
		WdgEnd(CLSID_VTMTABMENU,vtm_EMAIL_WND_EDITACCOUNT)

		WndSetTitleRC({0,0})
		WndSetAllSoftkeyRC({SK_OPTION,SK_OK,SK_CANCEL})
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_EDITACCOUNT)

	WndBegin(EMAIL_WND_SETTING)
		WdgBegin(CLSID_VTMTABMENU,vtm_EMAIL_WND_SETTING)
			VtmCreateTabMenuRC({0,0,3})
			VtmCreateTabMenuDataRC(3,{{EMAIL_IMG_TAB_GENERAL,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0},{EMAIL_IMG_TAB_CONNECTION_DISABLE,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0},{EMAIL_IMG_TAB_SINGLE_SIM_DISABLE,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,0,0,0,0}})
		WdgEnd(CLSID_VTMTABMENU,vtm_EMAIL_WND_SETTING)

		WndSetTitleRC({0,0})
		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_SETTING)

	WndBegin(EMAIL_WND_POPUPSELECT)
		WdgBegin(CLSID_VTMPOPUPSELECT,vtm_EMAIL_WND_POPUPSELECT)
			VtmCreatePopUpSelectRC(NULL,WDG_MENU_ITEM_TYPE_TEXT,0,0,0,0)
			VTMWdgBegin(CLSID_MENUWIDGET,POP_UP_SELECT_MENU_WDG,EmailPopupSelectWdg)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
				WdgMenuSetCheckStyleRC(0)
				WdgMenuSetFirstItemRC(0)
			VTMWdgEnd(CLSID_MENUWIDGET,POP_UP_SELECT_MENU_WDG,EmailPopupSelectWdg)
		WdgEnd(CLSID_VTMPOPUPSELECT,vtm_EMAIL_WND_POPUPSELECT)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_POPUPSELECT)

	WndBegin(EMAIL_WND_POPUPINPUT)
		WdgBegin(CLSID_VTMPOPUPINPUT,vtm_EMAIL_WND_POPUPINPUT)
			VtmCreatePopUpInputRC({COMMON_IMG_LIST_INFO_BG,0,0,MAE_INPUTMODE_NUMERIC})
			VTMWdgBegin(CLSID_IMAGEWIDGET,POP_UP_INPUT_BG_IMG_WDG,ImageWidgetControl)
				WdgImageSetAutoFitRC(FALSE)
				WdgImageSetEnableUpscaleRC(FALSE)
			VTMWdgEnd(CLSID_IMAGEWIDGET,POP_UP_INPUT_BG_IMG_WDG,ImageWidgetControl)
			VTMWdgBegin(CLSID_INPUTWIDGET,POP_UP_INPUT_INPUT_WDG,InputWidgetControl2)
				WdgInputSetSoftKeyBoardEnableRC(TRUE)
				WdgInputSetDisableSwitchInputModeRC(TRUE)
				WdgInputSetHandWritingEnableRC(FALSE)
				WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_NUMERIC)
			VTMWdgEnd(CLSID_INPUTWIDGET,POP_UP_INPUT_INPUT_WDG,InputWidgetControl2)
		WdgEnd(CLSID_VTMPOPUPINPUT,vtm_EMAIL_WND_POPUPINPUT)

		WndSetTitleRC({0,0})
		WndSetAllSoftkeyRC({DEFAULT_SK,DEFAULT_SK,SK_EXIT})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_POPUPINPUT)

	WndBegin(EMAIL_WND_MAIN_MENU)
		WdgBegin(CLSID_VTMMENU,vtm_EMAIL_WND_MAIN_MENU)
			VtmCreateMenuRC({0,0,0,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,0,0,0,0})
			VTMWdgBegin(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,MenuWidgetControl)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE_TEXT)
				WdgMenuSetCheckStyleRC(0)
				WdgMenuSetFirstItemRC(0)
			VTMWdgEnd(CLSID_MENUWIDGET,VTM_CREATE_MENU_MENU_WDG,MenuWidgetControl)
		WdgEnd(CLSID_VTMMENU,vtm_EMAIL_WND_MAIN_MENU)

		WndSetTitleRC({0,0})
		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_BACK})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_MAIN_MENU)

	WndBegin(EMAIL_WND_EMAIL_EDITOR)
		WndSetTitleRC({0,TXT_LIL_N_EMAIL_TITLE_NEW_EMAIL})
		WndSetAllSoftkeyRC({SK_OPTION,SK_OK,SK_CANCEL})
		WndSetTitleVisiableRC(TRUE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_CONTENT)
			WdgTextCreateForWndRC({{0,6*MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_CONTENT)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_SUBJECT)
			WdgTextCreateForWndRC({{0,5*MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC((ALIGN_H_LEFT|ALIGN_V_BOTTOM))
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_SUBJECT)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_BCC)
			WdgTextCreateForWndRC({{0,4*MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC((ALIGN_H_LEFT|ALIGN_V_MIDDLE))
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_BCC)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_CC)
			WdgTextCreateForWndRC({{0,3*MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC((ALIGN_H_LEFT|ALIGN_V_MIDDLE))
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_CC)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_TO)
			WdgTextCreateForWndRC({{0,2*MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC((ALIGN_H_LEFT|ALIGN_V_MIDDLE))
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_TO)

		WdgBegin(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_FROM)
			WdgTextCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_TITLE_HEIGHT},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,EMAIL_TXT_WDG_FROM)

		WdgBegin(CLSID_VIEWPORTWIDGET,EMAIL_EDITOR_VIEW_PORT_WDG)
			WdgViewportCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_TITLE_WIDTH,MAIN_DEFVIEW_WIDTH},0,ALIGN_H_START|ALIGN_V_TOP})
			WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_TOP)
			WdgViewportSetPanStepRC(0)
		WdgEnd(CLSID_VIEWPORTWIDGET,EMAIL_EDITOR_VIEW_PORT_WDG)

	WndEnd(EMAIL_WND_EMAIL_EDITOR)

	WndBegin(EMAIL_WND_EMAIL_EDITOR_OPTION_MENU)
		WdgBegin(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_EDIT_EMAIL_OPTION_MENU)
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,0})
			VTMWdgBegin(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,OptionMenuWidgetControl2)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			VTMWdgEnd(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,OptionMenuWidgetControl2)
		WdgEnd(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_EDIT_EMAIL_OPTION_MENU)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_EMAIL_EDITOR_OPTION_MENU)

	WndBegin(EMAIL_WND_EMAILBOXLIST)
		WdgBegin(CLSID_VTMTABMENU,vtm_EMAIL_WND_EMAILBOXLIST)
			VtmCreateTabMenuRC({0,TXT_LTL_N_INBOX,4})
			VtmCreateTabMenuDataRC(4,{{EMAIL_IMG_TAB_INBOX,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0},{EMAIL_IMG_TAB_DRAFT_DISABLE,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0},{EMAIL_IMG_TAB_OUTBOX_DISABLE,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0},{EMAIL_IMG_TAB_SENTBOX_DISABLE,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0}})
		WdgEnd(CLSID_VTMTABMENU,vtm_EMAIL_WND_EMAILBOXLIST)

		WndSetTitleRC({0,TXT_LTL_N_INBOX})
		WndSetAllSoftkeyRC({SK_OPTION,SK_OK,SK_CANCEL})
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_EMAILBOXLIST)

	WndBegin(EMAIL_WND_BOXLISTOPTION)
		WdgBegin(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_BOXLISTOPTION)
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,10})
			VtmCreateOptionMenuDataRC(10,{{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_EDIT},TXT_OIL1_N_EDIT},{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_OPEN},TXT_OIL1_N_OPEN},{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_BOXRETRIEVE},TXT_OIL1_N_EMAIL_RETRIEVE},{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_CREATE_NEW},TXT_LIL_N_EMAIL_CREATE_NEW},{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_MARK_UNREAD},TXT_OIL1_N_MARK_AS_UNREAD},{{TRUE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_DELETE},TXT_OIL1_N_DELETE},{{TRUE|MENUMODEL_ITEM_HAS_CHILD,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_MARK},TXT_OIL1_N_MARK},{{TRUE|MENUMODEL_ITEM_HAS_CHILD,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_SORT},TXT_OIL1_N_EMAIL_SORT_BY},{{TRUE|MENUMODEL_ITEM_HAS_CHILD,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},MNU_EMAIL_SEARCH},TXT_OIL1_N_SEARCH}})
			VTMWdgBegin(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,EmailBoxListOptionMenuWdg)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			VTMWdgEnd(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,EmailBoxListOptionMenuWdg)
		WdgEnd(CLSID_VTMOPTIONMENU,vtm_EMAIL_WND_BOXLISTOPTION)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_WND_BOXLISTOPTION)

	WndBegin(EMAIL_WND_MAILBOX_EDITOR)
		WndSetAllSoftkeyRC({SK_OPTION,SK_OK,SK_BACK})

		WdgBegin(CLSID_MENUWIDGET,EMAIL_MAILBOX_EDITOR_MENU_WDG)
			WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,221},WDG_MENU_TYPE_NORMAL})
		WdgEnd(CLSID_MENUWIDGET,EMAIL_MAILBOX_EDITOR_MENU_WDG)

		WdgBegin(CLSID_IMAGEWIDGET,EMAIL_MAILBOX_EDITOR_BG_IMG_WDG)
			WdgImageCreateForWndRC({{0,177},{MAIN_DEFVIEW_WIDTH,51},IMAGE_STYLE_COMMON,{FALSE,0}})
			WdgImageSetDataByIDRC(0)
			WdgImageSetAutoFitRC(FALSE)
			WdgImageSetEnableDefaultImageRC(FALSE)
		WdgEnd(CLSID_IMAGEWIDGET,EMAIL_MAILBOX_EDITOR_BG_IMG_WDG)

		WdgBegin(CLSID_BUTTONWIDGET,EMAIL_MAILBOX_EDITOR_BUTTON_WDG)
			WdgButtonCreateForWndRC({{0,200},{70,30},0})
		WdgEnd(CLSID_BUTTONWIDGET,EMAIL_MAILBOX_EDITOR_BUTTON_WDG)

		WdgBegin(CLSID_INPUTWIDGET,EMAIL_MAILBOX_EDITOR_INPUT_WDG)
			WdgInputCreateForWndRC({{70,193},{123,32},{TRUE,0}})
			WdgInputSetSoftKeyBoardEnableRC(0)
		WdgEnd(CLSID_INPUTWIDGET,EMAIL_MAILBOX_EDITOR_INPUT_WDG)

	WndEnd(EMAIL_WND_MAILBOX_EDITOR)

	WndBegin(EMAIL_MAILBOX_WND_OPTION_MENU)
		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})

		WdgBegin(CLSID_MENUWIDGET,MAILBOX_EDITOR_OPTION_MENU_WDG)
			WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			WdgMenuCreateForWndRC({{2,128},{150,190},WDG_MENU_TYPE_NORMAL})
		WdgEnd(CLSID_MENUWIDGET,MAILBOX_EDITOR_OPTION_MENU_WDG)

	WndEnd(EMAIL_MAILBOX_WND_OPTION_MENU)

	WndBegin(EMAIL_WND_ATTACH_EDITOR)
		WndSetAllSoftkeyRC({SK_OPTION,SK_NONE,SK_BACK})
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

		WdgBegin(CLSID_MENUWIDGET,EMAIL_WND_ATTACH_EDITOR_MENU_WDG)
			WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT - MAIN_TITLE_HEIGHT},WDG_MENU_TYPE_NORMAL})
		WdgEnd(CLSID_MENUWIDGET,EMAIL_WND_ATTACH_EDITOR_MENU_WDG)

	WndEnd(EMAIL_WND_ATTACH_EDITOR)

	WndBegin(EMAIL_ATTACH_EDITOR_WND_OPTION_MENU)
		WdgBegin(CLSID_VTMOPTIONMENU,vtm_EMAIL_ATTACH_EDITOR_WND_OPTION_MENU)
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,0})
			VTMWdgBegin(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,OptionMenuWidgetControl4)
				WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
			VTMWdgEnd(CLSID_OPTIONMENUWIDGET,OPTION_MENU_MENU_WDG,OptionMenuWidgetControl4)
		WdgEnd(CLSID_VTMOPTIONMENU,vtm_EMAIL_ATTACH_EDITOR_WND_OPTION_MENU)

		WndSetAllSoftkeyRC({SK_SELECT,SK_OK,SK_CANCEL})
		WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
		WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

	WndEnd(EMAIL_ATTACH_EDITOR_WND_OPTION_MENU)

ApEnd(RS,CLSID_EMAILAPP)
