#ifndef __MMI_MPLAYERAPP_RS__
#define __MMI_MPLAYERAPP_RS__

#if defined(__LCM_QCIF_PLUS_MMI__)
#define   NOW_PLAYING_RSKID		SK_BACK
#else
#define   NOW_PLAYING_RSKID		SK_PLAYLIST
#endif

#endif /*__MMI_MPLAYERAPP_RS__*/

ApBegin(RS,CLSID_MPLAYERAPP)

    WndBegin(MPLAYER_WND_COVER_FLOW)
            WndSetSoftkeyVisibleRC(FALSE)

            WdgBegin(CLSID_IMAGEWIDGET,Left2CoverImageWdg)
                WdgImageCreateForWndRC({{COVERFLOW_LEFT_2_COVER_X,COVERFLOW_LEFT_2_COVER_Y},{COVERFLOW_LEFT_2_COVER_WIDTH,COVERFLOW_LEFT_2_COVER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgEnd(CLSID_IMAGEWIDGET,Left2CoverImageWdg)
            WdgBegin(CLSID_IMAGEWIDGET,Right2CoverImageWdg)
                WdgImageCreateForWndRC({{COVERFLOW_RIGHT_2_COVER_X,COVERFLOW_RIGHT_2_COVER_Y},{COVERFLOW_RIGHT_2_COVER_WIDTH,COVERFLOW_RIGHT_2_COVER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgEnd(CLSID_IMAGEWIDGET,Right2CoverImageWdg)
            WdgBegin(CLSID_IMAGEWIDGET,Left1CoverImageWdg)
                WdgImageCreateForWndRC({{COVERFLOW_LEFT_1_COVER_X,COVERFLOW_LEFT_1_COVER_Y},{COVERFLOW_LEFT_1_COVER_WIDTH,COVERFLOW_LEFT_1_COVER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgEnd(CLSID_IMAGEWIDGET,Left1CoverImageWdg)
            WdgBegin(CLSID_IMAGEWIDGET,Right1CoverImageWdg)
                WdgImageCreateForWndRC({{COVERFLOW_RIGHT_1_COVER_X,COVERFLOW_RIGHT_1_COVER_Y},{COVERFLOW_RIGHT_1_COVER_WIDTH,COVERFLOW_RIGHT_1_COVER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgEnd(CLSID_IMAGEWIDGET,Right1CoverImageWdg)
            WdgBegin(CLSID_IMAGEWIDGET,MiddleCoverImageWdg)
                WdgImageCreateForWndRC({{COVERFLOW_MIDDLE_COVER_X,COVERFLOW_MIDDLE_COVER_Y},{COVERFLOW_MIDDLE_COVER_WIDTH,COVERFLOW_MIDDLE_COVER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgEnd(CLSID_IMAGEWIDGET,MiddleCoverImageWdg)
            WdgBegin(CLSID_TEXTWIDGET,PlaylistNameTextWdg)
                WdgTextCreateForWndRC({{COVERFLOW_PLAYLIST_NAME_X,COVERFLOW_PLAYLIST_NAME_Y},{COVERFLOW_PLAYLIST_NAME_WIDTH,COVERFLOW_PLAYLIST_NAME_HEIGHT},TEXT_STYLE_COMMON})
                WdgTextSetDataByIDRC(TXT_NULL_ID)
#ifndef __APP_MMI_SMALLROM__
                WdgCommonSetTextColorRC(COLOR_WHITE)
                WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
#else
                WdgCommonSetFontCategoryRC(COVERFLOW_TEXTWIDGET_FONT)
                WdgCommonSetTextColorRC(COVERFLOW_TEXTWIDGET_COLOR)
#endif
                WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgEnd(CLSID_TEXTWIDGET,PlaylistNameTextWdg)
        WndEnd(MPLAYER_WND_COVER_FLOW)



#if defined(__3D_UI_MPLAYER__)
    WndBegin(MPLAYER_WND_NOWPLAYING)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_NONE, SK_BACK} )
        WndSetSoftkeyVisibleRC(TRUE)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BG_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_BG_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_BG_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_BG_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BG_IMAGEWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_LYRICS_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_LYRICS_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_LYRICS_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_LYRICS_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_LYRICS_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_LYRICS_TEXTWIDGET)
#endif

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_TITLE_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_SONG_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_SONG_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_SONG_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_SONG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_ICON_SONG}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_ICON_SONG)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_TITLE_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ALBUM_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_ALBUM_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_ALBUM_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_ALBUM_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_ALBUM_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_ICON_ALBUM}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_ICON_ALBUM)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ALBUM_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ARTIST_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_ARTIST_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_ARTIST_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_ARTIST_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_ARTIST_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_ICON_ARTIST}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_ICON_ARTIST)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ARTIST_IMAGEWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_VOLUME_INCREASE_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_VOLUME_INCREASE_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_VOLUME_INCREASE_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_VOLUME_INCREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_VOLUME_INCREASE_UNPRESSED,GL_MEDIAPLAYER_IMG_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_VOLUME_DECREASE_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_VOLUME_DECREASE_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_VOLUME_DECREASE_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_VOLUME_DECREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_VOLUME_DECREASE_UNPRESSED,GL_MEDIAPLAYER_IMG_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_VOLUME_X_POSITION,GL_MPLAYERAPP_VOLUME_Y_POSITION},{GL_MPLAYERAPP_VOLUME_WIDTH,GL_MPLAYERAPP_VOLUME_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_VOLUME_LEVEL_BG}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_VOLUME_LEVEL_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_VOLUME_X_POSITION,GL_MPLAYERAPP_VOLUME_Y_POSITION},{GL_MPLAYERAPP_VOLUME_WIDTH,GL_MPLAYERAPP_VOLUME_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_VOLUME_LEVEL}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_TITLE_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_SONG_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_SONG_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_SONG_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_SONG_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_TITLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(0xFFF7F7F7)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_TITLE_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_ALBUM_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_ALBUM_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_ALBUM_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_ALBUM_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_ALBUM_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_TITLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(0xFFF7F7F7)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_ALBUM_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_ARTIST_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_ARTIST_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_ARTIST_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_ARTIST_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_ARTIST_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_AUTHOR)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(0xFFF7F7F7)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_ARTIST_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_TIME_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_DURATION_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_DURATION_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_DURATION_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_DURATION_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC((ALIGN_H_RIGHT|ALIGN_V_MIDDLE))
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_TIME_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_DURATION_TOTAL_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_DURATION_TOTAL_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_DURATION_TOTAL_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_DURATION_TOTAL_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_DURATION_TOTAL_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC((ALIGN_H_LEFT|ALIGN_V_MIDDLE))
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_DURATION_TOTAL_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_LISTINDEX_TEXTWIDGET)
            WdgTextCreateForWndRC({{GL_MPLAYERAPP_NUMBER_INDICATION_TEXTWIDGET_X_POSITION,GL_MPLAYERAPP_NUMBER_INDICATION_TEXTWIDGET_Y_POSITION},{GL_MPLAYERAPP_NUMBER_INDICATION_TEXTWIDGET_WIDTH,GL_MPLAYERAPP_NUMBER_INDICATION_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC((ALIGN_H_CENTER|ALIGN_V_MIDDLE))
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_LISTINDEX_TEXTWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_REPEAT_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_REPEAT_SWITCHICONWIDGET_X_POSITION,GL_MPLAYERAPP_REPEAT_SWITCHICONWIDGET_Y_POSITION},{GL_MPLAYERAPP_REPEAT_SWITCHICONWIDGET_WIDTH,GL_MPLAYERAPP_REPEAT_SWITCHICONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_REPEAT_NONE_UNPRESSED,GL_MEDIAPLAYER_IMG_REPEAT_NONE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_REPEAT_BUTTONWIDGET)

#ifdef __MMI_MPLAYER_3DSURROUND_ENABLE__
        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{GL_MPLAYERAPP_3DSURROUND_SWITCHICONWIDGET_X_POSITION,GL_MPLAYERAPP_3DSURROUND_SWITCHICONWIDGET_Y_POSITION},{GL_MPLAYERAPP_3DSURROUND_SWITCHICONWIDGET_WIDTH,GL_MPLAYERAPP_3DSURROUND_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET)
#endif

        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{GL_MPLAYERAPP_SHUFFLE_SWITCHICONWIDGET_X_POSITION,GL_MPLAYERAPP_SHUFFLE_SWITCHICONWIDGET_Y_POSITION},{GL_MPLAYERAPP_SHUFFLE_SWITCHICONWIDGET_WIDTH,GL_MPLAYERAPP_SHUFFLE_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_LYRICS_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_LYRICS_SWITCHICONWIDGET)
#endif

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_REWIND_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_REWIND_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_REWIND_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_REWIND_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_PREVIOUS_UNPRESSED,GL_MEDIAPLAYER_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAY_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_PLAYBACK_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_PLAYBACK_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_PLAYBACK_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_PLAYBACK_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAY_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_FORWARD_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_FORWARD_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_FORWARD_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_FORWARD_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_NEXT_UNPRESSED,GL_MEDIAPLAYER_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET)

#if defined(__MMI_BATTERY_ICON_DISPLAY__)
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,STATUSBAR_IMG_BATTERY_LEVEL4_1}})
            WdgImageSetDataByIDRC(STATUSBAR_IMG_BATTERY_LEVEL4_1)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET)
#endif

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_GLFOTOLIST_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_FOTOLIST_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_FOTOLIST_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_FOTOLIST_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_FOTOLIST_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_DEFAULT_COVER_BG}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_DEFAULT_COVER_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_GLFOTOLIST_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_GLFOTOLIST_WIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_FOTOLIST_WIDGET_X_POSITION,GL_MPLAYERAPP_FOTOLIST_WIDGET_Y_POSITION},{GL_MPLAYERAPP_FOTOLIST_WIDGET_WIDTH,GL_MPLAYERAPP_FOTOLIST_WIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_DEFAULT_COVER}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_DEFAULT_COVER)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_GLFOTOLIST_WIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_COVER_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_FOTOLIST_WIDGET_X_POSITION,GL_MPLAYERAPP_FOTOLIST_WIDGET_Y_POSITION},{GL_MPLAYERAPP_FOTOLIST_WIDGET_WIDTH,GL_MPLAYERAPP_FOTOLIST_WIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_DEFAULT_COVER}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_DEFAULT_COVER)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_COVER_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_CONTROL_BAR_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_CONTROLBAR_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_CONTROLBAR_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_CONTROLBAR_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_CONTROLBAR_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,GL_MEDIAPLAYER_IMG_HIDE_BG}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_HIDE_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_CONTROL_BAR_IMAGEWIDGET)

        WdgBegin(CLSID_INDICATORWIDGET,IndicatorWdg)
            WdgIndicatorCreateForWndRC({{GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_X_POSITION,GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_Y_POSITION},{GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_WIDTH,GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_HEIGHT},LAYOUT_STYLE_HORIZONTAL})
            WdgIndicatorSetDataRC({GL_MPLAYERAPP_PROGRESS_IND_START,GL_MPLAYERAPP_PROGRESS_IND_END,GL_MPLAYERAPP_PROGRESS_IND_POS})
            WdgIndicatorSetBGImageIDRC(GL_MEDIAPLAYER_IMG_TIME_PROGRESS_BG)
            WdgIndicatorSetINDImageIDRC(GL_MEDIAPLAYER_IMG_PROGRESS_SLIDE)
            WdgIndicatorSetINDOffsetRC(GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_IND_OFFSET)
            WdgIndicatorSetFGImageIDRC(GL_MEDIAPLAYER_IMG_TIME_STATUS)
            WdgIndicatorSetFGLeftOffsetRC(GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_LEFT_PADDING)
            WdgIndicatorSetFGRightOffsetRC(GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_RIGHT_PADDING)
            WdgIndicatorSetFGTopOffsetRC(GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_TOP_PADDING)
            WdgIndicatorSetFGBottomOffsetRC(GL_MPLAYERAPP_PROGRESS_INDICATORWIDGET_BOTTOM_PADDING)
        WdgEnd(CLSID_INDICATORWIDGET,IndicatorWdg)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LIST_MENU_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_LIST_MENU_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_LIST_MENU_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_LIST_MENU_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_LIST_MENU_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_ICON_LIST_MENU_UNPRESSED,GL_MEDIAPLAYER_IMG_ICON_LIST_MENU_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LIST_MENU_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LIST_BACK_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_LIST_BACK_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_LIST_BACK_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_LIST_BACK_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_LIST_BACK_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_ICON_LIST_BACK_UNPRESSED,GL_MEDIAPLAYER_IMG_ICON_LIST_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LIST_BACK_BUTTONWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LYRIC_MENU_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_LYRIC_MENU_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_LYRIC_MENU_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_LYRIC_MENU_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_LYRIC_MENU_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_LYRIC_UNPRESSED,GL_MEDIAPLAYER_IMG_LYRIC_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LYRIC_MENU_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LYRIC_BACK_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{GL_MPLAYERAPP_LYRIC_BACK_BUTTONWIDGET_X_POSITION,GL_MPLAYERAPP_LYRIC_BACK_BUTTONWIDGET_Y_POSITION},{GL_MPLAYERAPP_LYRIC_BACK_BUTTONWIDGET_WIDTH,GL_MPLAYERAPP_LYRIC_BACK_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,GL_MEDIAPLAYER_IMG_LYRIC_BACK_UNPRESSED,GL_MEDIAPLAYER_IMG_LYRIC_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_LYRIC_BACK_BUTTONWIDGET)
#endif

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_LIST_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_LIST_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_LIST_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_LIST_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_LIST_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,GL_MEDIAPLAYER_IMG_DEFAULT_COVER_BEHIND_BG}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_DEFAULT_COVER_BEHIND_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_LIST_IMAGEWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_LYRIC_IMAGEWIDGET)
            WdgImageCreateForWndRC({{GL_MPLAYERAPP_LYRIC_IMAGEWIDGET_X_POSITION,GL_MPLAYERAPP_LYRIC_IMAGEWIDGET_Y_POSITION},{GL_MPLAYERAPP_LYRIC_IMAGEWIDGET_WIDTH,GL_MPLAYERAPP_LYRIC_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,GL_MEDIAPLAYER_IMG_LYRIC_MASK}})
            WdgImageSetDataByIDRC(GL_MEDIAPLAYER_IMG_LYRIC_MASK)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_LYRIC_IMAGEWIDGET)
#endif

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_INFO_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_INFO_ABSCONTAINER_X_POSITION,GL_MPLAYERAPP_INFO_ABSCONTAINER_Y_POSITION},{GL_MPLAYERAPP_INFO_ABSCONTAINER_WIDTH,GL_MPLAYERAPP_INFO_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_INFO_ABSCONTAINER)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_GL_FOTOLIST_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_FOTOLIST_CONTAINER_X_POSITION,GL_MPLAYERAPP_FOTOLIST_CONTAINER_Y_POSITION},{GL_MPLAYERAPP_FOTOLIST_CONTAINER_WIDTH,GL_MPLAYERAPP_FOTOLIST_CONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_GL_FOTOLIST_ABSCONTAINER)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_GL_ROTATE_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_FOTOLIST_ROTATE_CONTAINER_X_POSITION,GL_MPLAYERAPP_FOTOLIST_ROTATE_CONTAINER_Y_POSITION},{GL_MPLAYERAPP_FOTOLIST_ROTATE_CONTAINER_WIDTH,GL_MPLAYERAPP_FOTOLIST_ROTATE_CONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_GL_ROTATE_ABSCONTAINER)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_LIST_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_LIST_ABSCONTAINER_X_POSITION,GL_MPLAYERAPP_LIST_ABSCONTAINER_Y_POSITION},{GL_MPLAYERAPP_LIST_ABSCONTAINER_WIDTH,GL_MPLAYERAPP_LIST_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_LIST_ABSCONTAINER)

        WdgBegin(CLSID_MENUWIDGET,MP_NOWPLAYING_LIST_MENU)
            WdgMenuCreateForWndRC({{GL_MPLAYERAPP_LIST_MENUWIDGET_X_POSITION,GL_MPLAYERAPP_LIST_MENUWIDGET_Y_POSITION},{GL_MPLAYERAPP_LIST_MENUWIDGET_WIDTH,GL_MPLAYERAPP_LIST_MENUWIDGET_HEIGHT},WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_MENUWIDGET,MP_NOWPLAYING_LIST_MENU)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_LIST_ROTATE_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_LIST_ROTATE_ABSCONTAINER_X_POSITION,GL_MPLAYERAPP_LIST_ROTATE_ABSCONTAINER_Y_POSITION},{GL_MPLAYERAPP_LIST_ROTATE_ABSCONTAINER_WIDTH,GL_MPLAYERAPP_LIST_ROTATE_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_LIST_ROTATE_ABSCONTAINER)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_LYRIC_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_LYRIC_ABSCONTAINER_X_POSITION,GL_MPLAYERAPP_LYRIC_ABSCONTAINER_Y_POSITION},{GL_MPLAYERAPP_LYRIC_ABSCONTAINER_WIDTH,GL_MPLAYERAPP_LYRIC_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_LYRIC_ABSCONTAINER)

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_CONTROLBAR_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{GL_MPLAYERAPP_CONTROLBAR_WIDGET_X_POSITION,GL_MPLAYERAPP_CONTROLBAR_WIDGET_Y_POSITION},{GL_MPLAYERAPP_CONTROLBAR_WIDGET_WIDTH,GL_MPLAYERAPP_CONTROLBAR_WIDGET_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_CONTROLBAR_ABSCONTAINER)

    WndEnd(MPLAYER_WND_NOWPLAYING)
#else

    WndBegin(MPLAYER_WND_NOWPLAYING)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_NONE, NOW_PLAYING_RSKID} )
        WndSetSoftkeyVisibleRC(TRUE)

#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BG_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_BG_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_BG_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_BG_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BG_IMAGEWIDGET)
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_COVER_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_COVER_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_COVER_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_COVER_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_COVER_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_COVER}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_COVER)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_COVER_IMAGEWIDGET)
#else
        WndSetBgColorRC(COLOR_BLACK)
        WdgBegin(CLSID_IMAGEWIDGET,TitleBarImageWdg)
            WdgImageCreateForWndRC({{VIDEOPLAYERAPP_PANEL_TITLEBAR_BG_IMAGEWIDGET_X_POSITION,VIDEOPLAYERAPP_PANEL_TITLEBAR_BG_IMAGEWIDGET_Y_POSITION},{VIDEOPLAYERAPP_PANEL_TITLEBAR_BG_IMAGEWIDGET_WIDTH,VIDEOPLAYERAPP_PANEL_TITLEBAR_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_TITLEBAR_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_TITLEBAR_BG)
        WdgEnd(CLSID_IMAGEWIDGET,TitleBarImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BgImageWdg)
            WdgImageCreateForWndRC({{VIDEOPLAYERAPP_PANEL_BG_IMAGEWIDGET_X_POSITION,VIDEOPLAYERAPP_PANEL_BG_IMAGEWIDGET_Y_POSITION},{VIDEOPLAYERAPP_PANEL_BG_IMAGEWIDGET_WIDTH,VIDEOPLAYERAPP_PANEL_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,BgImageWdg)
#endif

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_LYRICS_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgTextSetFontHeightRC(MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_FONT_HEIGHT)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_LYRICS_TEXTWIDGET)
#endif

#ifndef __SLIM_MMI__
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_TITLE_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_TITLE_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_TITLE_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_TITLE_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_TITLE_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_ICON_SONG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_ICON_SONG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_TITLE_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ALBUM_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_ALBUM_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_ALBUM_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_ALBUM_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_ALBUM_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_ICON_ALBUM}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_ICON_ALBUM)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ALBUM_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ARTIST_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_ARTIST_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_ARTIST_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_ARTIST_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_ARTIST_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_ICON_ARTIST}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_ICON_ARTIST)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_ARTIST_IMAGEWIDGET)
#endif
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MEDIAPLAYER_IMG_VOLUME_INCREASE_UNPRESSED,MEDIAPLAYER_IMG_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MEDIAPLAYER_IMG_VOLUME_DECREASE_UNPRESSED,MEDIAPLAYER_IMG_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_VOLUME_LEVEL_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_VOLUME_LEVEL_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_VOLUME_LEVEL}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)

#else
        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_VOLUME_INCREASE_UNPRESSED,VIDEOPLAYER_IMG_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_INCREASE_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_VOLUME_DECREASE_UNPRESSED,VIDEOPLAYER_IMG_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_VOLUME_DECREASE_BUTTONWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_VOLUME_PROGRESS_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_VOLUME_PROGRESS_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_EMPTY_VOLUME_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_VOLUME_LEVEL}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_FULL_VOLUME_IMAGEWIDGET)
#endif
        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_TITLE_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_TITLE_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_TITLE_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_TITLE_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_TITLE_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_TITLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_TITLE_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_ALBUM_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_ALBUM_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_ALBUM_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_ALBUM_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_ALBUM_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_TITLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(0)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_ALBUM_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_ARTIST_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_ARTIST_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_ARTIST_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_ARTIST_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_ARTIST_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_AUTHOR)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(0)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_ARTIST_TEXTWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_TIME_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
#ifdef __APP_MMI_SMALLROM__
            WdgCommonSetFontCategoryRC(MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_FONT)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_COLOR)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
#else
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(MPLAYERAPP_NOWPLAYING_TIME_TEXTWIDGET_ALIGNMENT)
#endif
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_TIME_TEXTWIDGET)

#if !defined(__APP_MMI_SMALLROM__)
        WdgBegin(CLSID_INDICATORWIDGET,MP_NOWPLAYING_PROGRESS_INDICATORWIDGET)
            WdgIndicatorCreateForWndRC({{MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_HEIGHT},LAYOUT_STYLE_HORIZONTAL})
            WdgIndicatorSetDataRC({0,1,0})
            WdgIndicatorSetBGImageIDRC(MEDIAPLAYER_IMG_TIMELINE_BG)
            WdgIndicatorSetINDImageIDRC(MEDIAPLAYER_IMG_TIMELINE_BALL_BG)
            WdgIndicatorSetINDOffsetRC(MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_IND_OFFSET)
            WdgIndicatorSetFGImageIDRC(MEDIAPLAYER_IMG_TIMELINE)
            WdgIndicatorSetFGLeftOffsetRC(MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_LEFT_PADDING)
            WdgIndicatorSetFGRightOffsetRC(MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_RIGHT_PADDING)
            WdgIndicatorSetFGTopOffsetRC(MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_TOP_PADDING)
            WdgIndicatorSetFGBottomOffsetRC(MPLAYERAPP_NOWPLAYING_PROGRESS_INDICATORWIDGET_BOTTOM_PADDING)
        WdgEnd(CLSID_INDICATORWIDGET,MP_NOWPLAYING_PROGRESS_INDICATORWIDGET)
#endif

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_LISTINDEX_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
#ifdef __APP_MMI_SMALLROM__
            WdgCommonSetFontCategoryRC(MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_FONT)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_COLOR)
            WdgCommonSetAlignmentRC(ALIGN_H_RIGHT|ALIGN_V_TOP)
#else
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXTWIDGET_ALIGNMENT)
#endif
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_LISTINDEX_TEXTWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_REPEAT_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_REPEAT_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_REPEAT_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_REPEAT_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_REPEAT_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MEDIAPLAYER_IMG_REPEAT_UNPRESSED,MEDIAPLAYER_IMG_REPEAT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_REPEAT_BUTTONWIDGET)

#if defined(__LANTERN_BY_AUDIO__) && !defined(__APP_MMI_SMALLROM__)
        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_SPECTRUM_SWITCHICONWIDGET)
#endif
#ifdef __MMI_MPLAYER_3DSURROUND_ENABLE__
        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{MPLAYERAPP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_3DSURROUND_SWITCHICONWIDGET)
#endif

        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_SHUFFLE_SWITCHICONWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_LYRICS_SWITCHICONWIDGET)
            WdgSwitchIconCreateForWndRC({{MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_LYRICS_SWITCHICONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,MP_NOWPLAYING_LYRICS_SWITCHICONWIDGET)
#endif

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MEDIAPLAYER_IMG_PREVIOUS_UNPRESSED,MEDIAPLAYER_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYPREVIOUS_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAY_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_PLAY_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_PLAY_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_PLAY_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_PLAY_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAY_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MEDIAPLAYER_IMG_NEXT_UNPRESSED,MEDIAPLAYER_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_PLAYNEXT_BUTTONWIDGET)

#if defined(__MMI_BATTERY_ICON_DISPLAY__)
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,STATUSBAR_IMG_BATTERY_BG}})
            WdgImageSetDataByIDRC(STATUSBAR_IMG_BATTERY_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_BG_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,STATUSBAR_IMG_BATTERY_LEVEL4_1}})
            WdgImageSetDataByIDRC(STATUSBAR_IMG_BATTERY_LEVEL4_1)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_BATTERY_STATUS_IMAGEWIDGET)
#endif

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_1ST_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_1ST_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_1ST_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_1ST_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_2ND_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_2ND_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_2ND_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_2ND_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_3RD_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_3RD_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_3RD_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_3RD_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_4TH_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_4TH_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_4TH_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_4TH_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_5TH_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_5TH_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FIVE_BUTTON_5TH_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FIVE_BUTTON_5TH_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_1ST_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_1ST_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_1ST_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_1ST_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_2ND_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_2ND_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_2ND_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_2ND_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_3RD_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_3RD_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_3RD_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_3RD_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_4TH_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_4TH_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_FOUR_BUTTON_4TH_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_FOUR_BUTTON_4TH_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_1ST_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_THREE_BUTTON_1ST_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_THREE_BUTTON_1ST_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_1ST_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_2ND_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_THREE_BUTTON_2ND_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_THREE_BUTTON_2ND_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_2ND_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_3RD_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_THREE_BUTTON_3RD_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_THREE_BUTTON_3RD_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_THREE_BUTTON_3RD_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_TWO_BUTTON_1ST_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_TWO_BUTTON_1ST_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_TWO_BUTTON_1ST_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_TWO_BUTTON_1ST_BUTTONWIDGET)

        WdgBegin(CLSID_BUTTONWIDGET,MP_NOWPLAYING_TWO_BUTTON_2ND_BUTTONWIDGET)
            WdgButtonCreateForWndRC({{MPLAYERAPP_NOWPLAYING_TWO_BUTTON_2ND_BUTTONWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_TWO_BUTTON_2ND_BUTTONWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_FUNCTION_BUTTON_BUTTONWIDGET_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,MP_NOWPLAYING_TWO_BUTTON_2ND_BUTTONWIDGET)

#if defined(__LANTERN_BY_AUDIO__) && !defined(__APP_MMI_SMALLROM__)
        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_ICON_SONG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_ICON_SONG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_TITLE_IMAGEWIDGET)

        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_NO_TITLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgCommonSetAlignmentRC(0)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_SPECTRUM_TITLE_TEXTWIDGET)

#ifdef __MMI_MPLAYER_LYRIC_ENABLE__
        WdgBegin(CLSID_TEXTWIDGET,MP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET)
            WdgTextCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(MPLAYERAPP_NOWPLAYING_TEXTWIDGET_FONT_COLOR)
            WdgTextSetFontHeightRC(MPLAYERAPP_NOWPLAYING_LYRICS_TEXTWIDGET_FONT_HEIGHT)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
        WdgEnd(CLSID_TEXTWIDGET,MP_NOWPLAYING_SPECTRUM_LYRIC_TEXTWIDGET)
#endif

        WdgBegin(CLSID_ABSCONTAINER,MP_NOWPLAYING_SPECTRUM_BARFRAME_ABSCONTAINER)
            WdgAbsContainerCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BARFRAME_ABSCONTAINER_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BARFRAME_ABSCONTAINER_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BARFRAME_ABSCONTAINER_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BARRRAME_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,MP_NOWPLAYING_SPECTRUM_BARFRAME_ABSCONTAINER)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_DEGREE_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_DEGREE_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_DEGREE_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_DEGREE_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_DEGREE_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_DEGREE}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_DEGREE)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_DEGREE_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_BG_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_1_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_2_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_3_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_4_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_5_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_6_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_7_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_8_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_9_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_10_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_11_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_12_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_13_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_14_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_15_IMAGEWIDGET)

        WdgBegin(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET)
            WdgImageCreateForWndRC({{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET_X_POSITION,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET_Y_POSITION},{MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET_WIDTH,MPLAYERAPP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MEDIAPLAYER_IMG_SPECTRUM_BG}})
            WdgImageSetDataByIDRC(MEDIAPLAYER_IMG_SPECTRUM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MP_NOWPLAYING_SPECTRUM_BAR_16_IMAGEWIDGET)
#endif // defined(__LANTERN_BY_AUDIO__) && !defined(__APP_MMI_SMALLROM__)
    WndEnd(MPLAYER_WND_NOWPLAYING)
#endif // defined(__3D_UI_MPLAYER__)

#if defined(ENABLE_SRSWOWHD)
    WndBegin(MPLAYER_WND_SRSSETTING)
        WndSetTitleRC(IMG_NULL_ID, TXT_LIL_N_SRS)
        WndSetAllSoftkeyRC({SK_CHANGE, SK_OK, SK_CANCEL})
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,SRSStatusTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(2, {0,{IMG_NULL_ID,TXT_LIL_N_STATUS}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF},{IMG_NULL_ID,TXT_OIL2_N_ON} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,SRSStatusTextPickWidget)
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,SRSTypeTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(5, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_TYPE}},{{IMG_NULL_ID,TXT_LIL_N_NORMAL},{IMG_NULL_ID,TXT_LIL_N_CLASSIC},{IMG_NULL_ID,TXT_LIL_N_BASS},{IMG_NULL_ID,TXT_LIL_N_HIP_HOP},{IMG_NULL_ID,TXT_LIL_N_PERFORM}})
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,SRSTypeTextPickWidget)
    WndEnd(MPLAYER_WND_SRSSETTING)

    WndBegin(MPLAYER_WND_SRSPARAM)
        WndSetAllSoftkeyRC({SK_OPTION, SK_OK, SK_BACK})
        WdgBegin(CLSID_TEXTPICK_TEXTWIDGET,SRS3DSpaceTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_TEXTPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(1, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_3D_SPACE}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF}})
        WdgEnd(CLSID_TEXTPICK_TEXTWIDGET,SRS3DSpaceTextPickWidget)
        WdgBegin(CLSID_TEXTPICK_TEXTWIDGET,SRS3DCenterTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_TEXTPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(1, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_3D_CENTER}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF}})
        WdgEnd(CLSID_TEXTPICK_TEXTWIDGET,SRS3DCenterTextPickWidget)
        WdgBegin(CLSID_TEXTPICK_TEXTWIDGET,SRSTruBassTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_TEXTPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(1, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_TRUBASS}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF}})
        WdgEnd(CLSID_TEXTPICK_TEXTWIDGET,SRSTruBassTextPickWidget)
        WdgBegin(CLSID_TEXTPICK_TEXTWIDGET,SRSFocusTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_TEXTPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(1, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_FOCUS}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF}})
        WdgEnd(CLSID_TEXTPICK_TEXTWIDGET,SRSFocusTextPickWidget)
        WdgBegin(CLSID_TEXTPICK_TEXTWIDGET,SRSDefinitionTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_TEXTPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(1, {0,{IMG_NULL_ID,TXT_LIL_N_SRS_DEFINITION}},{ {IMG_NULL_ID,TXT_OIL2_N_OFF}})
        WdgEnd(CLSID_TEXTPICK_TEXTWIDGET,SRSDefinitionTextPickWidget)
    WndEnd(MPLAYER_WND_SRSPARAM)
#endif // defined(ENABLE_SRSWOWHD)
ApEnd(RS,CLSID_MPLAYERAPP)

