/**
* @file mmi_camapp_custom.h
*
* @version $Id: mmi_camapp_custom.h 40955 2009-09-21 12:57:55Z young.huang $
*/
#ifndef __MMI_CAMAPP_CUSTOM_H__
#define __MMI_CAMAPP_CUSTOM_H__

#if defined(__ENABLE_CAMERA__) || defined(__ENABLE_CAMCORDER__)

#include "mmi_camerasrv_def.h"

// Define constant config and attribute settings
#define CAM_MAIN_DEFAULT_PIC_ID                               (CAMERASRV_DEV__MAIN)
#define CAM_MAIN_DEFAULT_PIC_TIMER                            (CAMERASRV_TIMER__OFF)
#define CAM_MAIN_DEFAULT_PIC_MULTISHOT                        (CAMERASRV_MULTI_SHOT__OFF)
#define CAM_MAIN_DEFAULT_PIC_VDO_SOUND                        (CAMERASRV_VDO_SOUND__ON)

#define	CAM_MAIN_DEFAULT_PIC_AWB                              (CAMERASRV_AWB__ON)
#define	CAM_MAIN_DEFAULT_PIC_AE                               (CAMERASRV_AE__WHOLE_IMAGE)
#define	CAM_MAIN_DEFAULT_PIC_AF                               (CAMERASRV_AF__OFF)
#define	CAM_MAIN_DEFAULT_PIC_ZOOM                             (CAMERASRV_ZOOM__DEFAULT)
#define	CAM_MAIN_DEFAULT_PIC_EV                               (CAMERASRV_EV__DEFAULT)
#define	CAM_MAIN_DEFAULT_PIC_BANDING                          (CAMERASRV_ANTI_FLICKER__50HZ)
#define	CAM_MAIN_DEFAULT_PIC_EFFECT                           (CAMERASRV_EFFECT__NORMAL)
#define	CAM_MAIN_DEFAULT_PIC_ENV                              (CAMERASRV_NIGHT_MODE__OFF)
#define CAM_MAIN_DEFAULT_PIC_STICKER                          (CAMERASRV_STICKER__NONE)
#define	CAM_MAIN_DEFAULT_PIC_LOMO                             (CAMERASRV_LOMO__OFF)
#define	CAM_MAIN_DEFAULT_PIC_MIRROR                           (CAMERASRV_MIRROR__OFF)
#define	CAM_MAIN_DEFAULT_PIC_PANORAMA                         (CAMERASRV_PANORAMA__OFF)

#define CAM_MAIN_DEFAULT_VDO_ID                               (CAMERASRV_DEV__MAIN)
#define CAM_MAIN_DEFAULT_VDO_TIMER                            (CAMERASRV_TIMER__OFF)
#define CAM_MAIN_DEFAULT_VDO_MULTISHOT                        (CAMERASRV_MULTI_SHOT__OFF)
#define CAM_MAIN_DEFAULT_VDO_VDO_SOUND                        (CAMERASRV_VDO_SOUND__ON)

#define	CAM_MAIN_DEFAULT_VDO_AWB                              (CAMERASRV_AWB__ON)
#define	CAM_MAIN_DEFAULT_VDO_AE                               (CAMERASRV_AE__WHOLE_IMAGE)
#define	CAM_MAIN_DEFAULT_VDO_AF                               (CAMERASRV_AF__OFF)
#define	CAM_MAIN_DEFAULT_VDO_ZOOM                             (CAMERASRV_ZOOM__DEFAULT)
#define	CAM_MAIN_DEFAULT_VDO_EV                               (CAMERASRV_EV__DEFAULT)
#define	CAM_MAIN_DEFAULT_VDO_BANDING                          (CAMERASRV_ANTI_FLICKER__50HZ)
#define	CAM_MAIN_DEFAULT_VDO_EFFECT                           (CAMERASRV_EFFECT__NORMAL)
#define	CAM_MAIN_DEFAULT_VDO_ENV                              (CAMERASRV_NIGHT_MODE__OFF)
#define CAM_MAIN_DEFAULT_VDO_STICKER                          (CAMERASRV_STICKER__NONE)
#define CAM_MAIN_DEFAULT_VDO_STABILIZER                       (CAMERASRV_VDO_STABILIZER__OFF)

#define	CAM_MAIN_DEFAULT_PIC_VDO_FILLLIGHT                    (CAMERA_FILL_LIGHT_OFF)
#define CAM_MAIN_DEFAULT_PIC_START_POSITION                   (ORIENTATION_PORTRAIT)


#if defined(__ENABLE_CAMERA__)
#ifdef __CAMERA_MMI_USE_PHONE_STORAGE__
#define CAM_MAXIMUM_PICTURE_SIZE_CAN_STORE_IN_PHONE           (50*MMI_COMMON_FILESIZE_ONE_KILOBYTE)
#define CAM_MAXIMUM_PICTURE_NUMBER_CAN_STORE_IN_PHONE         (8)
#endif
#endif

#ifdef __NAND_MMI__
#define CAM_MAXIMUM_RESOLUTION_NO_LIMITATION                  (0xFFFF)
#define CAM_LOMO_MAXIMUM_RESOLUTION_SUPPORT                   (CAMERASRV_PIC_RESOLUTION__1600X1200)
#define CAM_MIRROR_MAXIMUM_RESOLUTION_SUPPORT                 (CAMERASRV_PIC_RESOLUTION__1600X1200)
#define CAM_PANORAMA_MAXIMUM_RESOLUTION_SUPPORT               (CAMERASRV_PIC_RESOLUTION__640X480)
#else
#define CAM_LOMO_MAXIMUM_RESOLUTION_SUPPORT                   (CAMERASRV_PIC_RESOLUTION__320X240)
#define CAM_MIRROR_MAXIMUM_RESOLUTION_SUPPORT                 (CAMERASRV_PIC_RESOLUTION__320X240)
#define CAM_PANORAMA_MAXIMUM_RESOLUTION_SUPPORT               (CAMERASRV_PIC_RESOLUTION__320X240)
#endif

#ifdef __CAMERA_PANORAMA_MMI__
#define CAM_MAXIMUM_PANORAMA_CAPTURE_TIMES                    (3)
#define CAMERA_PREVIEW_FOREGROUND_TRANSPARENCY_EFFECT_VALUE   (50) //Transparency value. 0 to 255, 255 is full transparent
#endif

#ifdef __CAMERA_MIRROR_MMI__
#define CAMERA_TRANSLUCENCY_COLOR                             (0x80000000)
#endif

#define CAM_DISABLE_ICON_TIMER                                (6000)
#ifdef __MMI_CAMERA_NUMBER_KEY_ENABLE__
#define CAM_DISABLE_STRING_TIMER                              (3000)
#endif

// Define structure for resolution to max zoom mapping.
typedef struct
{
	u8	Resolution;
	CameraSrvPreviewType_e	ePreviewMode;
} Resolution_To_LandscapePortraitMode_Tbl_t;

const CameraSrvZoomInfo_t Camera_PIC_ZoomInfo_Tbl[] =
{
	{CAMERASRV_RES_TYPE_PIC_CONTACT,    128,            128,              0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__FOR_CONTACT
	{CAMERASRV_RES_TYPE_PIC_WALLPAPER,  MAIN_LCD_WIDTH, MAIN_LCD_HEIGHT,  0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__WALLPAPER
	{CAMERASRV_RES_TYPE_NORMAL,         320,            240,              0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__320X240
	{CAMERASRV_RES_TYPE_NORMAL,         640,            480,              0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__640X480
	{CAMERASRV_RES_TYPE_NORMAL,         800,            600,              0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__800X600
	{CAMERASRV_RES_TYPE_NORMAL,         1027,           768,              0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__1024X768
	{CAMERASRV_RES_TYPE_NORMAL,         1280,           1024,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__1280X1024
	{CAMERASRV_RES_TYPE_NORMAL,         1600,           1200,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__1600X1200
	{CAMERASRV_RES_TYPE_NORMAL,         2048,           1536,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__2048X1536
	{CAMERASRV_RES_TYPE_NORMAL,         2240,           1680,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__2240X1680
	{CAMERASRV_RES_TYPE_NORMAL,         2560,           1920,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__2560X1920
	{CAMERASRV_RES_TYPE_NORMAL,         3032,           2008,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__3032X2008
	{CAMERASRV_RES_TYPE_NORMAL,         3072,           2304,             0,  0,  0}, //CAMERASRV_PIC_RESOLUTION__3072X2304
	{CAMERASRV_RES_TYPE_NORMAL,         3264,           2448,             0,  0,  0}  //CAMERASRV_PIC_RESOLUTION__3264X2448
};

const CameraSrvZoomInfo_t Camera_VDO_ZoomInfo_Tbl[] =
{
	{CAMERASRV_RES_TYPE_NORMAL,		128,    96,     0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__128X96
	{CAMERASRV_RES_TYPE_NORMAL,		176,    144,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__176X144
	{CAMERASRV_RES_TYPE_NORMAL,		352,    288,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__352X288
	{CAMERASRV_RES_TYPE_NORMAL,		704,    576,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__704X576
	{CAMERASRV_RES_TYPE_NORMAL,		320,    240,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__320X240
#ifdef __MMI_WQVGA_RECORD_SUPPORT__
	{CAMERASRV_RES_TYPE_NORMAL,		400,    240,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__400X240
#endif
#ifdef __MMI_HVGA_RECORD_SUPPORT__
	{CAMERASRV_RES_TYPE_NORMAL,		480,    320,    0,  0,  0}, //CAMERASRV_VDO_RESOLUTION__480X320
#endif
	{CAMERASRV_RES_TYPE_NORMAL,		640,    480,    0,  0,  0} //CAMERASRV_VDO_RESOLUTION__640X480
 };

#if  defined(__CAMERA_PRI_LAYOUT_PORTRAIT_ONLY_MMI__) || defined(__CAMERA_SEC_LAYOUT_PORTRAIT_ONLY_MMI__)
const Resolution_To_LandscapePortraitMode_Tbl_t Camera_Portrait_Tbl[] =
{
	{CAMERASRV_PIC_RESOLUTION__FOR_CONTACT,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__WALLPAPER,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__320X240,         CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__640X480,         CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__800X600,         CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__1024X768,        CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__1280X1024,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__1600X1200,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__2048X1536,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__2240X1680,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__2560X1920,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__3032X2008,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__3072X2304,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__3264X2448,       CAMERASRV_PREVIEW_TYPE__PORTRAIT}
};
#endif

#if  defined(__CAMERA_PRI_LAYOUT_LANDSCAPE_ONLY_MMI__) || defined (__CAMERA_SEC_LAYOUT_LANDSCAPE_ONLY_MMI__)
const Resolution_To_LandscapePortraitMode_Tbl_t Camera_Landscape_Tbl[] =
{
	{CAMERASRV_PIC_RESOLUTION__FOR_CONTACT,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__WALLPAPER,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__320X240,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__640X480,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__800X600,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1024X768,        CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1280X1024,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1600X1200,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2048X1536,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2240X1680,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2560X1920,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3032X2008,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3072X2304,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3264X2448,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE}
};
#endif

#if  defined(__CAMERA_PRI_LAYOUT_CUSTOMIZATION_MMI__) || defined(__CAMERA_SEC_LAYOUT_CUSTOMIZATION_MMI__)
// Special handling of Camera to be landscape mode or Portrait mode.
const Resolution_To_LandscapePortraitMode_Tbl_t Camera_customization_Tbl[] =
{
	{CAMERASRV_PIC_RESOLUTION__FOR_CONTACT,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__WALLPAPER,       CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_PIC_RESOLUTION__320X240,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__640X480,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__800X600,         CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1024X768,        CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1280X1024,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__1600X1200,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2048X1536,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2240X1680,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__2560X1920,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3032X2008,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3072X2304,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_PIC_RESOLUTION__3264X2448,       CAMERASRV_PREVIEW_TYPE__LANDSCAPE}
};
#endif

#if  defined(__CAMERA_PRI_LAYOUT_PORTRAIT_ONLY_MMI__) || defined (__CAMERA_SEC_LAYOUT_PORTRAIT_ONLY_MMI__)
// Special handling of CamCorder to be landscape mode or Portrait mode.
const Resolution_To_LandscapePortraitMode_Tbl_t CamCorder_Portrait_Tbl[] =
{
	{CAMERASRV_VDO_RESOLUTION__128X96,      CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_VDO_RESOLUTION__176X144,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_VDO_RESOLUTION__352X288,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_VDO_RESOLUTION__704X576,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
	{CAMERASRV_VDO_RESOLUTION__320X240,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
#ifdef __MMI_WQVGA_RECORD_SUPPORT__
	{CAMERASRV_VDO_RESOLUTION__400X240,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
#endif
#ifdef __MMI_HVGA_RECORD_SUPPORT__
	{CAMERASRV_VDO_RESOLUTION__480X320,     CAMERASRV_PREVIEW_TYPE__PORTRAIT},
#endif
	{CAMERASRV_VDO_RESOLUTION__640X480,     CAMERASRV_PREVIEW_TYPE__PORTRAIT}
 };
#endif

#if  defined(__CAMERA_PRI_LAYOUT_LANDSCAPE_ONLY_MMI__) || defined (__CAMERA_SEC_LAYOUT_LANDSCAPE_ONLY_MMI__) || defined(__CAMERA_PRI_LAYOUT_CUSTOMIZATION_MMI__) || defined(__CAMERA_SEC_LAYOUT_CUSTOMIZATION_MMI__)
// Special handling of CamCorder to be landscape mode or Portrait mode.
const Resolution_To_LandscapePortraitMode_Tbl_t CamCorder_Landscape_Tbl[] =
{
	{CAMERASRV_VDO_RESOLUTION__128X96,      CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_VDO_RESOLUTION__176X144,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_VDO_RESOLUTION__352X288,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_VDO_RESOLUTION__704X576,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
	{CAMERASRV_VDO_RESOLUTION__320X240,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
#ifdef __MMI_WQVGA_RECORD_SUPPORT__
	{CAMERASRV_VDO_RESOLUTION__400X240,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
#endif
#ifdef __MMI_HVGA_RECORD_SUPPORT__
	{CAMERASRV_VDO_RESOLUTION__480X320,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE},
#endif
	{CAMERASRV_VDO_RESOLUTION__640X480,     CAMERASRV_PREVIEW_TYPE__LANDSCAPE}
};
#endif  //defined(__CAMERA_PRI_LAYOUT_LANDSCAPE_ONLY_MMI__) || defined (__CAMERA_SEC_LAYOUT_LANDSCAPE_ONLY_MMI__) || defined(__CAMERA_PRI_LAYOUT_CUSTOMIZATION_MMI__) || defined(__CAMERA_SEC_LAYOUT_CUSTOMIZATION_MMI__)

#if defined(__CAMERA_PRI_LAYOUT_PORTRAIT_ONLY_MMI__)
#define    M_Camera_Layout_Tbl        Camera_Portrait_Tbl
#define    M_Camcorder_Layout_Tbl     CamCorder_Portrait_Tbl
#elif defined(__CAMERA_PRI_LAYOUT_LANDSCAPE_ONLY_MMI__)
#define    M_Camera_Layout_Tbl        Camera_Landscape_Tbl
#define    M_Camcorder_Layout_Tbl     CamCorder_Landscape_Tbl
#elif defined(__CAMERA_PRI_LAYOUT_CUSTOMIZATION_MMI__)
#define    M_Camera_Layout_Tbl        Camera_customization_Tbl
#define    M_Camcorder_Layout_Tbl     CamCorder_Landscape_Tbl
#endif

#ifdef __DUAL_CAMERA_MMI__
#if defined(__CAMERA_SEC_LAYOUT_PORTRAIT_ONLY_MMI__)
#define    S_Camera_Layout_Tbl        Camera_Portrait_Tbl
#define    S_Camcorder_Layout_Tbl     CamCorder_Portrait_Tbl
#elif defined(__CAMERA_SEC_LAYOUT_LANDSCAPE_ONLY_MMI__)
#define    S_Camera_Layout_Tbl        Camera_Landscape_Tbl
#define    S_Camcorder_Layout_Tbl     CamCorder_Landscape_Tbl
#elif defined(__CAMERA_SEC_LAYOUT_CUSTOMIZATION_MMI__)
#define    S_Camera_Layout_Tbl        Camera_customization_Tbl
#define    S_Camcorder_Layout_Tbl     CamCorder_Landscape_Tbl
#endif
#endif

#endif  //if defined(__ENABLE_CAMERA__) || defined(__ENABLE_CAMCORDER__)
#endif  //__MMI_CAMAPP_CUSTOM_H__
