#ifndef __MMI_ANDROID_IDLEAPP_ID_H__
#define __MMI_ANDROID_IDLEAPP_ID_H__
#ifdef __UI_STYLE_MMI_ANDROID_IDLE__
typedef enum IdleWndId_e_
{
    ANDROID_IDLE_WND_DESKTOP = WND_ID_APP_BASE,
    ANDROID_IDLE_WND_WIDGET_SEL

} AndroidIdleWndId_e;


enum
{
    ANDROID_IDLE_BIGWALLPAPER = APP_WDG_START,
#ifdef __UI_STYLE_MMI_ANDROID_4_0__
    ANDROID_IDLE_SEPERATE_LINE_IMGWDG,
    ANDROID_IDLE_LEFT_2_KEYBUTTON,
    ANDROID_IDLE_LEFT_1_KEYBUTTON,
    ANDROID_IDLE_MIDDLE_KEYBUTTON,
    ANDROID_IDLE_RIGHT_1_KEYBUTTON,
    ANDROID_IDLE_RIGHT_2_KEYBUTTON,
#else
    ANDROID_IDLE_LEFTKEYBUTTON,
    ANDROID_IDLE_MIDDLEKEYBUTTON,
    ANDROID_IDLE_RIGHTKEYBUTTON,
#endif // __UI_STYLE_MMI_ANDROID_4_0__
    ANDROID_IDLE_SOFTKEYCONTAINER,
    ANDROID_IDLE_MAINANDROID_ABS,
    ANDROID_IDLE_TRANSITIONWIDGET,
	ANDROID_IDLE_PREVIEW_ABSCON,
    ANDROID_IDLE_PREVIEW_IMGWDG1,
    ANDROID_IDLE_PREVIEW_IMGWDG2,
    ANDROID_IDLE_PREVIEW_IMGWDG3,
    ANDROID_IDLE_PREVIEW_IMGWDG4,
    ANDROID_IDLE_PREVIEW_IMGWDG5,
    ANDROID_IDLE_WDG_MENU,
    ANDROID_IDLE_DESKTOP_WARNING_IMAGEWIDGET,
};

#endif /*__UI_STYLE_MMI_ANDROID_IDLE__*/
#endif //__MMI_ANDROID_IDLEAPP_ID_H__

