#ifndef __MMI_CALENDARAPP_RS__
#define __MMI_CALENDARAPP_RS__

#if defined(__LCM_QCIF_PLUS_MMI__)
#define	WDG_MENU_TYPE 		WDG_MENU_TYPE_NORMAL
#else
#define	WDG_MENU_TYPE 		WDG_MENU_TYPE_GRID
#endif

#endif /*__MMI_CALENDARAPP_RS__*/

ApBegin(RS,CLSID_CALENDARAPP)
    WndBegin(CALENDAR_WND_MONTHLY_VIEW)
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,MonthlyGridBgImageWdg)
            WdgImageCreateForWndRC({{CALENDARAPP_MONTHLY_GRID_BG_IMAGE_X_POSITION,CALENDARAPP_MONTHLY_GRID_BG_IMAGE_Y_POSITION},{MAIN_DEFVIEW_WIDTH,CALENDARAPP_MONTHLY_GRID_BG_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALENDAR_IMG_MONTH_BG}})
            WdgImageSetDataByIDRC(CALENDAR_IMG_MONTH_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MonthlyGridBgImageWdg)
#else
	WdgBegin(CLSID_TEXTWIDGET,MonthlyTopBgTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_MONTHLY_TOPBG_TEXT_POS_X,CALENDARAPP_MONTHLY_TOPBG_TEXT_POS_Y},{CALENDARAPP_MONTHLY_TOPBG_TEXT_WIDTH,CALENDARAPP_MONTHLY_TOPBG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,MonthlyTopBgTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,MonthlyBottomBgTextWdg)
        	WdgTextCreateForWndRC({{CALENDARAPP_MONTHLY_BOTTOMBG_TEXT_POS_X,CALENDARAPP_MONTHLY_BOTTOMBG_TEXT_POS_Y},{CALENDARAPP_MONTHLY_BOTTOMBG_TEXT_WIDTH,CALENDARAPP_MONTHLY_BOTTOMBG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,MonthlyBottomBgTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,MonthlyGirdBGTextWdg)
        	WdgTextCreateForWndRC({{CALENDARAPP_MONTHLY_GIRDBG_TEXT_POS_X,CALENDARAPP_MONTHLY_GIRDBG_TEXT_POS_Y},{CALENDARAPP_MONTHLY_GIRDBG_TEXT_WIDTH,CALENDARAPP_MONTHLY_GIRDBG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,MonthlyGirdBGTextWdg)
#endif
        WdgBegin(CLSID_BUTTONWIDGET,PreviousMonthButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_PREVIOUS_BUTTON_X_POSITION,CALENDARAPP_SWITCH_PREVIOUS_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_PREVIOUS_UNPRESSED,CALENDAR_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PreviousMonthButtonWdg)
        WdgBegin(CLSID_TEXTWIDGET,FocusDayTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_FOCUS_DAY_TEXT_X_POSITION,CALENDARAPP_FOCUS_DAY_TEXT_Y_POSITION},{CALENDARAPP_FOCUS_DAY_TEXT_WIDTH,CALENDARAPP_FOCUS_DAY_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,FocusDayTextWdg)
        WdgBegin(CLSID_BUTTONWIDGET,NextMonthButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_NEXT_BUTTON_X_POSITION,CALENDARAPP_SWITCH_NEXT_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_NEXT_UNPRESSED,CALENDAR_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,NextMonthButtonWdg)
        WdgBegin(CLSID_TEXTWIDGET,LunarInfoTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_LUNAR_INFO_X_POSITION,CALENDARAPP_LUNAR_INFO_Y_POSITION},{MAIN_DEFVIEW_WIDTH,CALENDARAPP_LUNAR_INFO_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,LunarInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,WeekTextWdg)
            WdgTextCreateForWndRC({{0,0},{0,0},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_WEEK)
        WdgEnd(CLSID_TEXTWIDGET,WeekTextWdg)

        WdgBegin(CLSID_HORZ_MENUWIDGET,WeekDayListWdg)
            WdgMenuCreateForWndRC({{0,0},{0,0},WDG_MENU_TYPE_HORZ})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_WEEK_DAY_LIST_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_WEEK_DAY_LIST_ITEM_HEIGHT)
        WdgEnd(CLSID_HORZ_MENUWIDGET,WeekDayListWdg)

        WdgBegin(CLSID_MENUWIDGET,WeekNumListWdg)
            WdgMenuCreateForWndRC({{0,0},{0,0},WDG_MENU_TYPE})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_WEEK_NUM_LIST_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_WEEK_NUM_LIST_ITEM_HEIGHT)
            WdgMenuSetToGridStyleRC({1, 6, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})
        WdgEnd(CLSID_MENUWIDGET,WeekNumListWdg)

        WdgBegin(CLSID_GRID_MENUWIDGET,MonthlyGridGridWdg)
            WdgMenuCreateForWndRC({{0,0},{0,0},WDG_MENU_TYPE_GRID})
            WdgMenuSetToGridStyleRC({CALENDARAPP_MONTHLY_GRID_DIMENSION, CALENDARAPP_MONTHLY_GRID_DIMENSION-1, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_MONTHLY_GRID_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_MONTHLY_GRID_ITEM_HEIGHT)
            WdgMenuSetFixedNumRC((u16)CALENDARAPP_MONTHLY_GRID_DIMENSION)
            WdgCommonSetPaddingDataRC({CALENDARAPP_MONTHLY_GRID_ITEM_PADDING_LEFT, CALENDARAPP_MONTHLY_GRID_ITEM_PADDING_RIGHT, CALENDARAPP_MONTHLY_GRID_ITEM_PADDING_TOP, CALENDARAPP_MONTHLY_GRID_ITEM_PADDING_BOTTOM})
#ifndef __APP_MMI_SMALLROM__
            WdgMenuSetItemFocusImageRC(CALENDAR_IMG_SELECT)
#endif
#ifdef __APP_MMI_SMALLROM__
	    WdgMenuSetColGapRC(1)
            WdgMenuSetRowGapRC(1)
#endif
        WdgEnd(CLSID_GRID_MENUWIDGET,MonthlyGridGridWdg)
        WdgBegin(CLSID_TEXTWIDGET,PreviewCountTextWdg)
            WdgTextCreateForWndRC({{0,0},{CALENDARAPP_PREVIEW_LINE_COUNT_WIDTH,CALENDARAPP_PREVIEW_LINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,PreviewCountTextWdg)
    WndEnd(CALENDAR_WND_MONTHLY_VIEW)

    WndBegin(CALENDAR_WND_WEEKLY_VIEW)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_OK, SK_EXIT} )
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,TimeSlotBgImageWdg)
            WdgImageCreateForWndRC({{CALENDARAPP_WEEKLY_TIME_SLOT_BG_IMAGE_X_POSITION,CALENDARAPP_WEEKLY_TIME_SLOT_BG_IMAGE_Y_POSITION},{MAIN_DEFVIEW_WIDTH,CALENDARAPP_WEEKLY_TIME_SLOT_BG_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALENDAR_IMG_WEEK_BG}})
            WdgImageSetDataByIDRC(CALENDAR_IMG_WEEK_BG)
        WdgEnd(CLSID_IMAGEWIDGET,TimeSlotBgImageWdg)
#else
		WdgBegin(CLSID_TEXTWIDGET,TimeSlotBgTextWdg)
			WdgTextCreateForWndRC({{0,0},{MAIN_LCD_WIDTH,CALENDARAPP_WEEKLY_DAYLIST_POS_Y},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,TimeSlotBgTextWdg)
		WdgBegin(CLSID_IMAGEWIDGET,BitmapImageWdg)
			WdgImageCreateForWndRC({{0,CALENDARAPP_WEEKLY_DAYLIST_POS_Y},{MAIN_LCD_WIDTH,CALENDARAPP_WEEKLY_DAYLIST_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,BitmapImageWdg)
#endif
        WdgBegin(CLSID_BUTTONWIDGET,PreviousWeekButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_PREVIOUS_BUTTON_X_POSITION,CALENDARAPP_SWITCH_PREVIOUS_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_PREVIOUS_UNPRESSED,CALENDAR_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PreviousWeekButtonWdg)
        WdgBegin(CLSID_TEXTWIDGET,WeeklyFocusDayTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_FOCUS_DAY_TEXT_X_POSITION,CALENDARAPP_FOCUS_DAY_TEXT_Y_POSITION},{CALENDARAPP_FOCUS_DAY_TEXT_WIDTH,CALENDARAPP_FOCUS_DAY_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,WeeklyFocusDayTextWdg)
        WdgBegin(CLSID_BUTTONWIDGET,NextWeekButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_NEXT_BUTTON_X_POSITION,CALENDARAPP_SWITCH_NEXT_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_NEXT_UNPRESSED,CALENDAR_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,NextWeekButtonWdg)
        WdgBegin(CLSID_TEXTWIDGET,WeeklyLunarInfoTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_LUNAR_INFO_X_POSITION,CALENDARAPP_LUNAR_INFO_Y_POSITION},{MAIN_DEFVIEW_WIDTH,CALENDARAPP_LUNAR_INFO_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,WeeklyLunarInfoTextWdg)
#ifdef __TOUCH_SCREEN_MMI__
        WdgBegin(CLSID_BUTTONWIDGET,WeeklyPreviousHourButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_HOUR_PREVIOUS_BUTTON_X_POSITION,CALENDARAPP_HOUR_PREVIOUS_BUTTON_Y_POSITION},{CALENDARAPP_HOUR_BUTTON_WIDTH,CALENDARAPP_HOUR_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_UP_UNPRESSED,CALENDAR_IMG_UP_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,WeeklyPreviousHourButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,WeeklyNextHourButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_HOUR_NEXT_BUTTON_X_POSITION,CALENDARAPP_HOUR_NEXT_BUTTON_Y_POSITION},{CALENDARAPP_HOUR_BUTTON_WIDTH,CALENDARAPP_HOUR_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_DOWN_UNPRESSED,CALENDAR_IMG_DOWN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,WeeklyNextHourButtonWdg)
#endif
        WdgBegin(CLSID_MENUWIDGET,TimeSlotListWdg)
            WdgMenuCreateForWndRC({{CALENDARAPP_WEEKLY_TIME_SLOT_LIST_X_POSITION,CALENDARAPP_WEEKLY_TIME_SLOT_LIST_Y_POSITION},{CALENDARAPP_WEEKLY_TIME_SLOT_LIST_WIDTH,CALENDARAPP_WEEKLY_TIME_SLOT_LIST_HEIGHT},WDG_MENU_TYPE})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_WEEKLY_TIME_SLOT_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_WEEKLY_TIME_SLOT_ITEM_HEIGHT)
            WdgMenuSetToGridStyleRC({1, 6, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})

        WdgEnd(CLSID_MENUWIDGET,TimeSlotListWdg)
        WdgBegin(CLSID_HORZ_MENUWIDGET,WeeklyDayMenuWdg)
            WdgMenuCreateForWndRC({{CALENDARAPP_WEEKLY_WEEK_DAY_LIST_X_POSITION,CALENDARAPP_WEEKLY_WEEK_DAY_LIST_Y_POSITION},{CALENDARAPP_WEEKLY_WEEK_DAY_LIST_WIDTH,CALENDARAPP_WEEKLY_WEEK_DAY_LIST_HEIGHT},WDG_MENU_TYPE_HORZ})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_WEEKLY_WEEK_DAY_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_WEEKLY_WEEK_DAY_ITEM_HEIGHT)
        WdgEnd(CLSID_HORZ_MENUWIDGET,WeeklyDayMenuWdg)
        WdgBegin(CLSID_TEXTWIDGET,WeeklyPreviewCountTextWdg)
            WdgTextCreateForWndRC({{0,0},{CALENDARAPP_PREVIEW_LINE_COUNT_WIDTH,CALENDARAPP_PREVIEW_LINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,WeeklyPreviewCountTextWdg)
    WndEnd(CALENDAR_WND_WEEKLY_VIEW)

    WndBegin(CALENDAR_WND_DAILY_VIEW)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_OK, SK_BACK} )
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,DailyTimeSlotBgImageWdg)
            WdgImageCreateForWndRC({{CALENDARAPP_DAILY_TIME_SLOT_BG_IMAGE_X_POSITION,CALENDARAPP_DAILY_TIME_SLOT_BG_IMAGE_Y_POSITION},{MAIN_DEFVIEW_WIDTH,CALENDARAPP_DAILY_TIME_SLOT_BG_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALENDAR_IMG_DAY_BG}})
            WdgImageSetDataByIDRC(CALENDAR_IMG_DAY_BG)
        WdgEnd(CLSID_IMAGEWIDGET,DailyTimeSlotBgImageWdg)
#else
		WdgBegin(CLSID_IMAGEWIDGET,DailyBitmapWdg)
		    WdgImageCreateForWndRC({{CALENDARAPP_DAILY_TIME_SLOT_BG_IMAGE_X_POSITION,CALENDARAPP_DAILY_TIME_SLOT_BG_IMAGE_Y_POSITION},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,DailyBitmapWdg)
#endif
        WdgBegin(CLSID_BUTTONWIDGET,PreviousDayButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_PREVIOUS_BUTTON_X_POSITION,CALENDARAPP_SWITCH_PREVIOUS_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_PREVIOUS_UNPRESSED,CALENDAR_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PreviousDayButtonWdg)
        WdgBegin(CLSID_TEXTWIDGET,DailyFocusDayTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_FOCUS_DAY_TEXT_X_POSITION,CALENDARAPP_FOCUS_DAY_TEXT_Y_POSITION},{CALENDARAPP_FOCUS_DAY_TEXT_WIDTH,CALENDARAPP_FOCUS_DAY_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,DailyFocusDayTextWdg)
        WdgBegin(CLSID_BUTTONWIDGET,NextDayButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_SWITCH_NEXT_BUTTON_X_POSITION,CALENDARAPP_SWITCH_NEXT_BUTTON_Y_POSITION},{CALENDARAPP_SWITCH_BUTTON_WIDTH,CALENDARAPP_SWITCH_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_NEXT_UNPRESSED,CALENDAR_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,NextDayButtonWdg)
#ifdef __TOUCH_SCREEN_MMI__
        WdgBegin(CLSID_BUTTONWIDGET,DailyPreviousHourButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_HOUR_PREVIOUS_BUTTON_X_POSITION,CALENDARAPP_HOUR_PREVIOUS_BUTTON_Y_POSITION},{CALENDARAPP_HOUR_BUTTON_WIDTH,CALENDARAPP_HOUR_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_UP_UNPRESSED,CALENDAR_IMG_UP_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,DailyPreviousHourButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,DailyNextHourButtonWdg)
            WdgButtonCreateForWndRC({{CALENDARAPP_HOUR_NEXT_BUTTON_X_POSITION,CALENDARAPP_HOUR_NEXT_BUTTON_Y_POSITION},{CALENDARAPP_HOUR_BUTTON_WIDTH,CALENDARAPP_HOUR_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,CALENDAR_IMG_DOWN_UNPRESSED,CALENDAR_IMG_DOWN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,DailyNextHourButtonWdg)
#endif
#ifdef __TOUCH_SCREEN_MMI__
        WdgBegin(CLSID_TEXTWIDGET,DailyPreviewCountTextWdg)
            WdgTextCreateForWndRC({{CALENDARAPP_DAILY_PREVIEW_LINE_X_POSITION,0},{CALENDARAPP_DAILY_PREVIEW_LINE_EVENT_WIDTH,CALENDARAPP_PREVIEW_LINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,DailyPreviewCountTextWdg)
#else
        WdgBegin(CLSID_TEXTWIDGET,DailyPreviewCountTextWdg)
            WdgTextCreateForWndRC({{0,0},{CALENDARAPP_PREVIEW_LINE_COUNT_WIDTH,CALENDARAPP_PREVIEW_LINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,DailyPreviewCountTextWdg)
#endif
        WdgBegin(CLSID_MENUWIDGET,DailyTimeSlotListWdg)
            WdgMenuCreateForWndRC({{0,0},{CALENDARAPP_DAILY_TIME_SLOT_LIST_WIDTH,CALENDARAPP_DAILY_TIME_SLOT_LIST_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgMenuSetItemWidthRC((u16)CALENDARAPP_DAILY_TIME_SLOT_ITEM_WIDTH)
            WdgMenuSetItemHeightRC((u16)CALENDARAPP_DAILY_TIME_SLOT_ITEM_HEIGHT)
        WdgEnd(CLSID_MENUWIDGET,DailyTimeSlotListWdg)
    WndEnd(CALENDAR_WND_DAILY_VIEW)

    WndBegin(CALENDAR_WND_EDIT_EVENT)
        WndSetTitleRC({IMG_NULL_ID,TXT_NULL_ID})
        WndSetAllSoftkeyRC( {SK_SAVE, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_DOUBLE_TEXT_WIDGET,EditSubjectWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_DOUBLE_TEXT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_SUBJECT,TXT_NULL_ID})
        WdgEnd(CLSID_DOUBLE_TEXT_WIDGET,EditSubjectWdg)
        WdgBegin(CLSID_DOUBLE_TEXT_WIDGET,EditLocationWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_DOUBLE_TEXT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_LOCATION,TXT_NULL_ID})
        WdgEnd(CLSID_DOUBLE_TEXT_WIDGET,EditLocationWdg)

				WdgBegin(CLSID_TEXT_TIME_WIDGET,EditStartTimeWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_TIME})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_STARTTIME,{0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_TIME_WIDGET,EditStartTimeWdg)

        WdgBegin(CLSID_TEXT_TIME_WIDGET,EditEndTimeWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_TIME})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_ENDTIME,{0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_TIME_WIDGET,EditEndTimeWdg)

        WdgBegin(CLSID_TEXT_DATE_WIDGET,EditStarDatetWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_DATE})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_STARTDATE,{0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_DATE_WIDGET,EditStarDatetWdg)

        WdgBegin(CLSID_TEXT_DATE_WIDGET,EditEndDateWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_DATE})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_ENDDATE,{0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_DATE_WIDGET,EditEndDateWdg)

				WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,EditRepeatWdg)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(5, {0,{IMG_NULL_ID,TXT_LIL_N_REPEAT}},{{IMG_NULL_ID,TXT_LIL_N_OFF},{IMG_NULL_ID,TXT_LIL_N_DAILY},{IMG_NULL_ID,TXT_LIL_N_WEEKLY},{IMG_NULL_ID,TXT_LIL_N_MONTHLY}, {IMG_NULL_ID,TXT_LIL_N_YEARLY}})
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,EditRepeatWdg)

				WdgBegin(CLSID_TEXT_DATE_WIDGET,EditUntilDateWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_DATE})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_REPEAT_UNTIL,{0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_DATE_WIDGET,EditUntilDateWdg)


        WdgBegin(CLSID_DOUBLE_TEXT_WIDGET,EditDescriptionWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_DOUBLE_TEXT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_DESCRIPTION,TXT_NULL_ID})
        WdgEnd(CLSID_DOUBLE_TEXT_WIDGET,EditDescriptionWdg)

        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,EditAlarmWdg)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(8, {0,{IMG_NULL_ID,TXT_LIL_N_ALARM}},{ {IMG_NULL_ID,TXT_LIL_N_OFF},{IMG_NULL_ID,TXT_LIL_N_IMMEDIATE},{IMG_NULL_ID,TXT_LIL_N_FIVEMIN},{IMG_NULL_ID,TXT_LIL_N_TENMIN},{IMG_NULL_ID,TXT_LIL_N_FIFTEENMIN},{IMG_NULL_ID,TXT_LIL_N_THIRTYMIN},{IMG_NULL_ID,TXT_LIL_N_ONEHOUR},{IMG_NULL_ID,TXT_LIL_N_ONEDAY} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,EditAlarmWdg)
    WndEnd(CALENDAR_WND_EDIT_EVENT)

    WndBegin(CALENDAR_WND_SETTINGS)
        WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_SETTINGS})
        WndSetAllSoftkeyRC( {SK_CHANGE, SK_OK, SK_BACK} )
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,DefaultViewWdg)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(2, {0,{IMG_NULL_ID,TXT_LIL_N_DEFAULT_VIEW}},{ {IMG_NULL_ID,TXT_OIL1_N_MONTHLY_VIEW},{IMG_NULL_ID,TXT_OIL1_N_WEEKLY_VIEW} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,DefaultViewWdg)

        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,WeekStartDayWdg)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(7, {0,{IMG_NULL_ID,TXT_LIL_N_WEEK_START_DAY}},{ {IMG_NULL_ID,TXT_LIL_N_SUNDAY},{IMG_NULL_ID,TXT_LIL_N_MONDAY},{IMG_NULL_ID,TXT_LIL_N_TUESDAY},{IMG_NULL_ID,TXT_LIL_N_WEDNESDAY},{IMG_NULL_ID,TXT_LIL_N_THURSDAY},{IMG_NULL_ID,TXT_LIL_N_FRIDAY},{IMG_NULL_ID,TXT_LIL_N_SATURDAY} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,WeekStartDayWdg)
    WndEnd(CALENDAR_WND_SETTINGS)

    WndBegin(CALENDAR_WND_VIEW_EVENT)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CLOSE} )
        WdgBegin(CLSID_TEXTWIDGET,TextWdg)
            VtmCreateInputRC({IMG_NULL_ID,TXT_LTL_N_VIEW_DETAILS, 0, TRUE})
        WdgEnd(CLSID_TEXTWIDGET,TextWdg)
    WndEnd(CALENDAR_WND_VIEW_EVENT)

#ifndef __CALENDARAPP_FIGURE_COMMAND_COMMAND_DATE_TIME__
	WndBegin(CALENDAR_WND_GO_TO_DATE)
	    WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
	   	WdgBegin(CLSID_TEXT_DATE_WIDGET,TextDateWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_DATE})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_DATE, {0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_DATE_WIDGET,TextDateWidget)
	WndEnd(CALENDAR_WND_GO_TO_DATE)
#endif
ApEnd(RS,CLSID_CALENDARAPP)

