
#ifndef __MMI_KINGMOVIEAPP_CFG__H__
#define __MMI_KINGMOVIEAPP_CFG__H__

#include "mmi_mae_filemgr.h"

#define MAX_STORAGE_NUM (3)

#define CONFIG_AMR_KMVAPP_UPDATING_FILE CONFIG_DEFINE(CFGIT_KMVAPP_UPDATING_FILE, boolean, MAX_STORAGE_NUM, {0, 0, 0})
#ifdef __MMI_KING_MOVIE_3D_APP_INDIE__
#define CONFIG_ARM_3DKMVAPP_UPDATING_FILE CONFIG_DEFINE(CFGIT_3DKMVAPP_UPDATING_FILE,boolean,MAX_STORAGE_NUM,{0,0,0})
#else
#define CONFIG_ARM_3DKMVAPP_UPDATING_FILE
#endif

#ifdef __MMI_KING_MOVIE__
#define KINGMOVIEAPP_AMR_ALL_CONFIG \
                          CONFIG_AMR_KMVAPP_UPDATING_FILE \
                          CONFIG_ARM_3DKMVAPP_UPDATING_FILE
#else
#define KINGMOVIEAPP_AMR_ALL_CONFIG
#endif

#endif //__MMI_KINGMOVIEAPP_CFG__H__
