
#ifndef __MMI_CALENDARAPP_CFG__H__
#define __MMI_CALENDARAPP_CFG__H__

#include "mmi_mae_common_def.h"
#define MAX_DAYS_PER_YEAR (366)

/* The default value of display week num list mode for start day of week is Monday. */
#define CALENDAR_STARTDAY_OF_WEEK_IS_MONDAY 1  

enum
{
    CAL_INITIALVIEW_MONTHLY=0,
    CAL_INITIALVIEW_WEEKLY=1
};
typedef u8 CalInitialView_e;
enum
{
    CAL_WEEKDAY_SUN=0,
    CAL_WEEKDAY_MON=1,
    CAL_WEEKDAY_TUE=2,
    CAL_WEEKDAY_WED=3,
    CAL_WEEKDAY_THU=4,
    CAL_WEEKDAY_FRI=5,
    CAL_WEEKDAY_SAT=6
};
typedef u8 CalWeekDays_e;


// Allow Mater Reset

//#define CONFIG_DEFINE(cfgId, type, name, value)
#ifdef CALENDAR_STARTDAY_OF_WEEK_IS_MONDAY
#define CONFIG_AMR_CALENDAR_WEEK_START_DAY  CONFIG_DEFINE(CFGIT_CALENDAR_WEEK_START_DAY, CalWeekDays_e,     1, CAL_WEEKDAY_MON )
#else
#define CONFIG_AMR_CALENDAR_WEEK_START_DAY  CONFIG_DEFINE(CFGIT_CALENDAR_WEEK_START_DAY, CalWeekDays_e,     1, CAL_WEEKDAY_SUN )
#endif
#define CONFIG_AMR_CALENDAR_DAY_START_TIME  CONFIG_DEFINE(CFGIT_CALENDAR_DAY_START_TIME, u8,                1, 8 )
#define CONFIG_AMR_CALENDAR_INITIAL_VIEW    CONFIG_DEFINE(CFGIT_CALENDAR_INITIAL_VIEW, CalInitialView_e,    1, CAL_INITIALVIEW_MONTHLY )
#ifdef __INDIAN_CALENDAR__
#define CONFIG_AMR_INDIANCALENDAR_ENTRY    CONFIG_DEFINE(CFGIT_INDIANCALENDAR_ENTRY, boolean,    1, TRUE )
#define CONFIG_AMR_INDIANCALENDAR_CITYINDEX    CONFIG_DEFINE(CFGIT_INDIANCALENDAR_CITYINDEX, u16, 1, 0 )
#else
#define CONFIG_AMR_INDIANCALENDAR_ENTRY
#define CONFIG_AMR_INDIANCALENDAR_CITYINDEX
#endif

#ifdef __APP_MMI_CALENDAR__
#define CALENDAR_AMR_APP_CONFIG \
                        CONFIG_AMR_CALENDAR_WEEK_START_DAY \
                        CONFIG_AMR_CALENDAR_DAY_START_TIME \
                        CONFIG_AMR_CALENDAR_INITIAL_VIEW \
                        CONFIG_AMR_INDIANCALENDAR_ENTRY \
                        CONFIG_AMR_INDIANCALENDAR_CITYINDEX
#else
#define CALENDAR_AMR_APP_CONFIG
#endif

#endif //__MMI_CALENDARAPP_CFG__H__
