

#ifndef __MMI_PHBSRV_CFG__H__
#define __MMI_PHBSRV_CFG__H__

enum
{
    MMI_PHB_NUMBER_COMPARE_8_DIGITALS=8,
    MMI_PHB_NUMBER_COMPARE_9_DIGITALS=9,
    MMI_PHB_NUMBER_COMPARE_11_DIGITALS=11
};
typedef u8 MMI_PHB_NUMBER_COMPARE_MAX_E;

// Not Allow Mater Reset
//PhoneBook
#define CONFIG_NAMR_PHBSRV_BLACKLIST_NUMBER CONFIG_DEFINE(CFGIT_PHBSRV_BLACKLIST_NUMBER, u8, 1, 0)
#define CONFIG_NAMR_PHBSRV_NUMBER_COMPARE_MAX CONFIG_DEFINE(CFGIT_PHBSRV_NUMBER_COMPARE_MAX, MMI_PHB_NUMBER_COMPARE_MAX_E, 1, MMI_PHB_NUMBER_COMPARE_8_DIGITALS)


#define PHBSRV_NAMR_ALL_CONFIG \
                CONFIG_NAMR_PHBSRV_BLACKLIST_NUMBER \
                CONFIG_NAMR_PHBSRV_NUMBER_COMPARE_MAX

#endif //__MMI_PHBSRV_CFG__H__



