
#ifndef __MMI_EBOOKAPP_CFG__H__
#define __MMI_EBOOKAPP_CFG__H__
enum
{
    EBOOK_DECODE_DEFAULT=0,
    EBOOK_DECODE_GB=1,
    EBOOK_DECODE_BIG5=2,
    EBOOK_DECODE_UCS2=3,
    EBOOK_DECODE_UTF8=4,
    EBOOK_DECODE_UCS2_BIG_ENDIAN=5,
    EBOOK_DECODE_UCS2_LITTLE_ENDIAN=6,
    EBOOK_DECODE_WIN1250=7,
    EBOOK_DECODE_WIN874=8,
    EBOOK_DECODE_WIN1251=9,
    EBOOK_DECODE_WIN1252=10,
    EBOOK_DECODE_WIN1253=11,
    EBOOK_DECODE_WIN1254=12,
    EBOOK_DECODE_WIN1255=13,
    EBOOK_DECODE_WIN1256=14,
    EBOOK_DECODE_WIN1257=15,
    EBOOK_DECODE_WIN1258=16,
    EBOOK_DECODE_ERROR=0xff
};
typedef u16 EBOOK_DECODE_TYPE_e;
enum
{
    EBOOK_SCROLL_1LINE=0,
    EBOOK_SCROLL_3LINE=1,
    EBOOK_SCROLL_6LINE=2,
    EBOOK_SCROLL_PAGE=3
};
typedef u16 EBOOK_SCROLL_TYPE_e;

// Allow Mater Reset

//#define CONFIG_DEFINE(cfgId, type, name, value)
#define CONFIG_AMR_SETTING_EBOOK_DECODE_TYPE  CONFIG_DEFINE(CFGIT_SETTING_EBOOK_DECODE_TYPE, EBOOK_DECODE_TYPE_e,    1,    EBOOK_DECODE_DEFAULT )
#define CONFIG_AMR_SETTING_EBOOK_SCROLL_TYPE  CONFIG_DEFINE(CFGIT_SETTING_EBOOK_SCROLL_TYPE, EBOOK_SCROLL_TYPE_e,    1,    EBOOK_SCROLL_PAGE )

#ifdef __E_BOOK_MMI__
#define EBOOKAPP_AMR_ALL_CONFIG \
                        CONFIG_AMR_SETTING_EBOOK_DECODE_TYPE \
                        CONFIG_AMR_SETTING_EBOOK_SCROLL_TYPE
#else
#define EBOOKAPP_AMR_ALL_CONFIG
#endif

#endif //__MMI_EBOOKAPP_CFG__H__
