
#ifndef __MMI_MAIN_MENU_CFG__H__
#define __MMI_MAIN_MENU_CFG__H__

#define MAIN_MENU_AP_LIST_TOTAL (85)	//__RFID_MMI__

// Allow Mater Reset
//#define CONFIG_DEFINE(cfgId, type, name, value)
#define CONFIG_AMR_MAIN_MENU_AP_LIST                      CONFIG_DEFINE(CFGIT_MAIN_MENU_AP_LIST,                          MainMenuItem_t, MAIN_MENU_AP_LIST_TOTAL, \
{{SHORTCUTS_FUNC_DIALING/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_MESSAGECENTER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CALLLOG/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_MUSICPLAYER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CALENDAR/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_TODOLIST/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_PHOTOVIEWER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CAMERA/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_VIDEOPLAYER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_FILEMANAGER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_MAP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_PHONEBOOK/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_FAVORITEPHB/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CALCULATOR/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CALCULATOR_PLUS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SETTINGS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_LICENSEMGR/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_VIDEORECORDER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_FMRADIO/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_VOICEMEMO/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_PROFILES/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_ALARM/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_AZAN/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_UNITCONVERTER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_STOPWATCH/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_COUNTDOWNTIMER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_WORLDCLOCK/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SHORTCUTS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_BMI/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_E_BOOK/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_DICT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_RFID/*__RFID_MMI__ eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_JAVAAMS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CDWAP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_BLUETOOTH/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_STK_MASTER/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_STK_SLAVE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SWITCHMODE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_MAINMENU_SETTINGS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_NOTEPAD/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SNOTE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_EMAIL/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_ATV/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_ISDBT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_KINGMOVIE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_EVENTCENTER_FULL/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SXM_VCHAT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_VENDOR_GAMES/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_SEARCH/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_BCS/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_PHOTOSLIDE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_TRUE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_QQ/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_TENCENT_DEFAULT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_TENCENT_QQB/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_TENCENT_MAX/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_NATIVE_QQ/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_CALLER_LOCATION/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_TUDOU/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_ZMOL_APP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_ZHANGYUE_EBOOK/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_EMU/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_BIG2/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_FRUIT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_PACMAN/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_GOGOBOX/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_FRUITSLICE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_IPLAYCUBE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_RUBIKCUBE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_LABYRINTH/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_CUTROPE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_ANGRYBIRD/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_GOBANG/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_HAMSTERFIGHT/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_LINKUP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_PUZZLE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_SOKOBAN/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_SUDOKU/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_YOUTUBE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_YOUKU/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_VUCLIP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_BAIDU/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_FISHFURY/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_VAMPIRE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_GAMES_ZOMBIE/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/},{SHORTCUTS_FUNC_NTPAPP/*eShortcutsFuncId*/, \
MAIN_MENU_BOOL_FALSE/*bIsLocked*/, \
MAIN_MENU_BOOL_TRUE/*bIsEnable*/}}/*MainMenuApList*/ )

#ifdef __FEATURE_MGL__
#define CONFIG_AMR_GlMAIN_MENU_ORDER                            CONFIG_DEFINE(CFGIT_GlMAIN_MENU_ORDER,                          u8, SHORTCUTS_FUNC_TOTAL+4, {0xff} )
#define CONFIG_AMR_GlMAIN_MENU_SWITCH_PAGE_TYPE                	CONFIG_DEFINE(CFGIT_GlMAIN_MENU_SWITCH_PAGE_TYPE,               u8, 1, 0)
#else
#define CONFIG_AMR_GlMAIN_MENU_ORDER
#define CONFIG_AMR_GlMAIN_MENU_SWITCH_PAGE_TYPE
#endif

#if defined (__UI_STYLE_MMI_IFONE__) || defined (__UI_STYLE_MMI_STYLE_SWITCH__)
#define CONFIG_AMR_MAINMENUAPP_IFONE_PAGEINFO                   CONFIG_DEFINE(CFGIT_MAINMENUAPP_IFONE_PAGEINFO,                 u8, 11,              {255,255,255,255,255,255,255,255,255,255,255} )
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_BREAKGLASS_ONOFF      CONFIG_DEFINE(CFGIT_MAINMENUAPP_MENUEFFECT_BREAKGLASS_ONOFF,    SetOnOff_e, 1,    SET_ON )
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_CIRCUMGYRATE_ONOFF    CONFIG_DEFINE(CFGIT_MAINMENUAPP_MENUEFFECT_CIRCUMGYRATE_ONOFF,  SetOnOff_e, 1,  SET_ON )
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_FALLDOWN_ONOFF        CONFIG_DEFINE(CFGIT_MAINMENUAPP_MENUEFFECT_FALLDOWN_ONOFF,      SetOnOff_e, 1,       SET_ON )
#define CONFIG_AMR_MAINMENUAPP_IFONE_MENUITEM_NUMBER                CONFIG_DEFINE(CFGIT_MAINMENUAPP_IFONE_MENUITEM_NUMBER, u32, 1, {0})
#else
#define CONFIG_AMR_MAINMENUAPP_IFONE_PAGEINFO
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_BREAKGLASS_ONOFF
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_CIRCUMGYRATE_ONOFF
#define CONFIG_AMR_MAINMENUAPP_MENUEFFECT_FALLDOWN_ONOFF
#define CONFIG_AMR_MAINMENUAPP_IFONE_MENUITEM_NUMBER
#endif

#define MAINMENUAPP_AMR_ALL_CONFIG \
                        CONFIG_AMR_MAIN_MENU_AP_LIST \
                        CONFIG_AMR_GlMAIN_MENU_ORDER \
                        CONFIG_AMR_MAINMENUAPP_IFONE_PAGEINFO \
                        CONFIG_AMR_MAINMENUAPP_MENUEFFECT_BREAKGLASS_ONOFF \
                        CONFIG_AMR_MAINMENUAPP_MENUEFFECT_CIRCUMGYRATE_ONOFF \
                        CONFIG_AMR_MAINMENUAPP_MENUEFFECT_FALLDOWN_ONOFF \
                        CONFIG_AMR_GlMAIN_MENU_SWITCH_PAGE_TYPE \
                        CONFIG_AMR_MAINMENUAPP_IFONE_MENUITEM_NUMBER

#endif //__MMI_MAIN_MENU_CFG__H__
