

#ifndef __MMI_COMMON_NOTALLOW_H__
#define __MMI_COMMON_NOTALLOW_H__

#include "mmi_message_cfg.h"
#include "mmi_mae_taskdb_typedef.h"  //todolist
#include "mmi_cphssrv_def.h"  //voiceMail
#include "mmi_common_cfg.h"

typedef struct _MMI_CFGSRV_VoiceMail_t
{
    MMI_CPHS_Type_e Type;
    u8 Number[MailNumberSize+1];
    u8 bUpdate;
} MMI_CFGSRV_VoiceMail_t;


enum
{
    TodoListSortByCheckStatus=TASKDBATTR_CHECKSTATUS,
    TodoListSortByPriority=TASKDBATTR_PRIORITY,
    TodoListSortByModifyTime=TASKDBATTR_MODIFIED_TIME,
    TodoListSortByDueTime=TASKDBATTR_DUE_TIME
};
typedef u32 TodoListSortByField;

typedef enum
{
   NEGLECT_NONE = 0
,  NEGLECT_BTSRV =      1<< 0
,  NEGLECT_WLANSRV =    1<< 1

} NeglectNetworkOffLineModeList_e;

//NetworkSetting
#define CONFIG_NAMR_ONOFF_OFFLINE_MODE CONFIG_DEFINE(CFGIT_ONOFF_OFFLINE_MODE, boolean, 1, FALSE)
#define CONFIG_NAMR_PROCESS_AIRPLANE_SWITCHING CONFIG_DEFINE(CFGIT_PROCESS_AIRPLANE_SWITCHING, boolean, 1, FALSE)
#define CONFIG_NAMR_NEGLECT_OFFLINE_MODE_LIST CONFIG_DEFINE(CFGIT_NEGLECT_OFFLINE_MODE_LIST, NeglectNetworkOffLineModeList_e, 1, NEGLECT_NONE)
#ifdef __3G_RIL_MMI__
#define CONFIG_NAMR_ONOFF_DEFAULT_BAND CONFIG_DEFINE(CFGIT_ONOFF_DEFAULT_BAND, BandSetting_t, 1, {0,0,0,0})
#endif
//NetworkSetting

//not common
//Setting
#ifdef __UI_STYLE_MMI_MAIN_MENU_ANIMATION__
#define CONFIG_NAMR_SETTING_MAIN_MENU_ANIMATION_STYLE_INFO CONFIG_DEFINE(CFGIT_SETTING_MAIN_MENU_ANIMATION_STYLE_INFO, SettingMainMenuAnimationStyleInfo_t, MAX_MAIN_MENU_ANIMATION_STYLE_INFO, \
{{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_RANDOM/*TextID*/, SET_MENU_ANIMATION_STYLE_RANDOM/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_NONE/*TextID*/, SET_MENU_ANIMATION_STYLE_NONE/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_3DFLIP/*TextID*/, SET_MENU_ANIMATION_STYLE_3DFLIP/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_ROTATE/*TextID*/, SET_MENU_ANIMATION_STYLE_ROTATE/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_SLIDE/*TextID*/, SET_MENU_ANIMATION_STYLE_SLIDE/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_LIQUID/*TextID*/, SET_MENU_ANIMATION_STYLE_LIQUID/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_ZOOM/*TextID*/, SET_MENU_ANIMATION_STYLE_ZOOM/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_2DFLIP/*TextID*/, SET_MENU_ANIMATION_STYLE_2DFLIP/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_DESTRUCT/*TextID*/, SET_MENU_ANIMATION_STYLE_DESTRUCT/*eMenuAnimationStyle*/, {0}/*u8Padding*/},\
{TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_SPLIT/*TextID*/, SET_MENU_ANIMATION_STYLE_SPLIT/*eMenuAnimationStyle*/, {0}/*u8Padding*/}})
#else
#define CONFIG_NAMR_SETTING_MAIN_MENU_ANIMATION_STYLE_INFO
#endif
//Setting end

//Setting
#define CONFIG_NAMR_SETTING_MAIN_MENU_STYLE_INFO CONFIG_DEFINE(CFGIT_SETTING_MAIN_MENU_STYLE_INFO, SettingMainMenuLayoutInfo_t, MAX_MAIN_MENU_LAYOUT_INFO, \
{{TXT_LIL_N_STYLE_1/*TextID*/, SET_MENU_STYLE_IFONE/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_2/*TextID*/, SET_MENU_STYLE_SPIN/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_3/*TextID*/, SET_MENU_STYLE_GRID/*eMenuStylesetting*/, {0}},\
{TXT_LIL_N_STYLE_4/*TextID*/, SET_MENU_STYLE_LIST/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_5/*TextID*/, SET_MENU_STYLE_CELL/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_6/*TextID*/, SET_MENU_STYLE_3D_SPIN/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_7/*TextID*/, SET_MENU_STYLE_3D_GRID/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_LIL_N_STYLE_9/*TextID*/, SET_MENU_STYLE_ANDROID/*eMenuStylesetting*/, {0}/*u8Padding*/},\
{TXT_NULL_ID/*TextID*/, SET_MENU_STYLE_INVALID/*eMenuStylesetting*/, {0}/*u8Padding*/}})
//Setting end

//SMS
#define CONFIG_NAMR_MESSAGE_MASTER_SMS_SERVICE_CENTER CONFIG_DEFINE(CFGIT_MESSAGE_MASTER_SMS_SERVICE_CENTER, Msg_SMS_Service_Center_t, 1, {{0x0,0x31,0x31,0x31,0x31,0x31,0x0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}})
#define CONFIG_NAMR_MESSAGE_SLAVE_SMS_SERVICE_CENTER CONFIG_DEFINE(CFGIT_MESSAGE_SLAVE_SMS_SERVICE_CENTER, Msg_SMS_Service_Center_t, 1, {{0x0,0x35,0x34,0x33,0x34,0x35,0x33,0x34,0x35,0x0,0,0,0,0,0,0,0,0,0,0,0,0}})
//SMS end

//not common
//Todo
#ifdef __APP_MMI_TODOLIST__
#define CONFIG_NAMR_TODOLIST_LIST_SORT_BY CONFIG_DEFINE(CFGIT_TODOLIST_LIST_SORT_BY, TodoListSortByField, 1, TodoListSortByCheckStatus)
#else
#define CONFIG_NAMR_TODOLIST_LIST_SORT_BY
#endif
//Todo end

//Voicemail
#define CONFIG_NAMR_MCA_SIM1_L1_VOICEMAIL_NUMBER CONFIG_DEFINE(CFGID_MCA_SIM1_L1_VOICEMAIL_NUMBER, MMI_CFGSRV_VoiceMail_t, 1, {MMI_TYPE_EMPTY/*Type*/, {0}/*Number*/, 0/*bUpdate*/})
#define CONFIG_NAMR_MCA_SIM1_L2_VOICEMAIL_NUMBER CONFIG_DEFINE(CFGID_MCA_SIM1_L2_VOICEMAIL_NUMBER, MMI_CFGSRV_VoiceMail_t, 1, {MMI_TYPE_EMPTY/*Type*/, {0}/*Number*/, 0/*bUpdate*/})
#define CONFIG_NAMR_MCA_SIM2_L1_VOICEMAIL_NUMBER CONFIG_DEFINE(CFGID_MCA_SIM2_L1_VOICEMAIL_NUMBER, MMI_CFGSRV_VoiceMail_t, 1, {MMI_TYPE_EMPTY/*Type*/, {0}/*Number*/, 0/*bUpdate*/})
#define CONFIG_NAMR_MCA_SIM2_L2_VOICEMAIL_NUMBER CONFIG_DEFINE(CFGID_MCA_SIM2_L2_VOICEMAIL_NUMBER, MMI_CFGSRV_VoiceMail_t, 1, {MMI_TYPE_EMPTY/*Type*/, {0}/*Number*/, 0/*bUpdate*/})
//Voicemail end

//not common
//WLAN
#ifdef __WLAN_MMI__
#define CONFIG_NAMR_WLANSRV_POWER_STATUS CONFIG_DEFINE(CFGIT_WLANSRV_POWER_STATUS, WLANSRV_PowerStatus_e, 1, WLANSRV_POWER_STATUS_OFF)
#define CONFIG_NAMR_WLANSRV_SCAN_NETWORK CONFIG_DEFINE(CFGIT_WLANSRV_SCAN_NETWORK, WLANSRV_ScanNetwork_e, 1, WLANSRV_SCAN_NETWORK_1MIN)
#define CONFIG_NAMR_WLANSRV_SHOW_WLAN CONFIG_DEFINE(CFGIT_WLANSRV_SHOW_WLAN, WLANSRV_ShowWLAN_e, 1, WLANSRV_SHOW_WLAN_OFF)
#else
#define CONFIG_NAMR_WLANSRV_POWER_STATUS
#define CONFIG_NAMR_WLANSRV_SCAN_NETWORK
#define CONFIG_NAMR_WLANSRV_SHOW_WLAN
#endif
//WLAN end

#ifdef __3G_RIL_MMI__
#define COMMON_NOTALLOW_ALL_CONFIG \
            CONFIG_NAMR_ONOFF_OFFLINE_MODE \
            CONFIG_NAMR_ONOFF_DEFAULT_BAND \
			CONFIG_NAMR_PROCESS_AIRPLANE_SWITCHING \
            CONFIG_NAMR_NEGLECT_OFFLINE_MODE_LIST \
            CONFIG_NAMR_SETTING_MAIN_MENU_ANIMATION_STYLE_INFO \
            CONFIG_NAMR_SETTING_MAIN_MENU_STYLE_INFO\
            CONFIG_NAMR_MESSAGE_MASTER_SMS_SERVICE_CENTER \
            CONFIG_NAMR_MESSAGE_SLAVE_SMS_SERVICE_CENTER \
            CONFIG_NAMR_MCA_SIM1_L1_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM1_L2_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM2_L1_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM2_L2_VOICEMAIL_NUMBER \
            CONFIG_NAMR_WLANSRV_POWER_STATUS \
            CONFIG_NAMR_WLANSRV_SCAN_NETWORK \
            CONFIG_NAMR_WLANSRV_SHOW_WLAN \
            CONFIG_NAMR_TODOLIST_LIST_SORT_BY
#else
#define COMMON_NOTALLOW_ALL_CONFIG \
            CONFIG_NAMR_ONOFF_OFFLINE_MODE \
			CONFIG_NAMR_PROCESS_AIRPLANE_SWITCHING \
            CONFIG_NAMR_NEGLECT_OFFLINE_MODE_LIST \
            CONFIG_NAMR_SETTING_MAIN_MENU_ANIMATION_STYLE_INFO \
            CONFIG_NAMR_SETTING_MAIN_MENU_STYLE_INFO\
            CONFIG_NAMR_MESSAGE_MASTER_SMS_SERVICE_CENTER \
            CONFIG_NAMR_MESSAGE_SLAVE_SMS_SERVICE_CENTER \
            CONFIG_NAMR_MCA_SIM1_L1_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM1_L2_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM2_L1_VOICEMAIL_NUMBER \
            CONFIG_NAMR_MCA_SIM2_L2_VOICEMAIL_NUMBER \
            CONFIG_NAMR_WLANSRV_POWER_STATUS \
            CONFIG_NAMR_WLANSRV_SCAN_NETWORK \
            CONFIG_NAMR_WLANSRV_SHOW_WLAN \
            CONFIG_NAMR_TODOLIST_LIST_SORT_BY
#endif

#endif //__MMI_COMMON_NOTALLOW_H__
