#ifndef __SYS_SYS_SLDLM_CFG_H__
#define __SYS_SYS_SLDLM_CFG_H__

//=================================================//
//===== Define User load/unload SLDLM APP ID ======//
//=================================================//
enum {
    USR_SLDLM_APP_NONE = 0,
    USR_SLDLM_APP_ATVDRV,
    USR_SLDLM_APP_AMRNBCODEC,
    USR_SLDLM_APP_MP3DEC,
    USR_SLDLM_APP_SBCENC,
    USR_SLDLM_APP_AUDIO_POSTPROCESS,
    USR_SLDLM_APP_AUDIO_SRC,
    USR_SLDLM_APP_AACDEC,
    USR_SLDLM_APP_MIDI,
    USR_SLDLM_APP_VIDEC_COMMON,
    USR_SLDLM_APP_M4VDEC,
    USR_SLDLM_APP_AVCDEC,
    USR_SLDLM_APP_RVCDEC,
    USR_SLDLM_APP_COOKDEC,
    USR_SLDLM_APP_AVP_PLAYER,
    USR_SLDLM_APP_CAPTURE,
    USR_SLDLM_APP_VDR,
    USR_SLDLM_APP_AMRNBDEC,
    USR_SLDLM_APP_AMRNBENC,
    USR_SLDLM_APP_MAP,
    USR_SLDLM_APP_MAR,
    USR_SLDLM_APP_HANDWRITING,
	USR_SLDLM_APP_WAP,
    USR_SLDLM_APP_AUDIO_ARP,
    USR_SLDLM_APP_SXM_CORE_ENGINE,      /// used for 3rd sxm target engine
    USR_SLDLM_APP_IME_MY,
    USR_SLDLM_APP_MJAVA,
#define USR_SLDLM_APP_MJAVA USR_SLDLM_APP_MJAVA
    USR_SLDLM_APP_GPS,
    USR_SLDLM_APP_GPS_FW,
    USR_SLDLM_APP_CAMERA,
	USR_SLDLM_APP_ZYUE_ENGINE,
	USR_SLDLM_APP_ZMOL_ENGINE,
	USR_SLDLM_APP_SKY_ENGINE,
    USR_SLDLM_APP_TENCENTMCARE,
    USR_SLDLM_PLAT_INIT,
    USR_SLDLM_APP_FMRX,
    USR_SLDLM_APP_BLUETOOTH,
    USR_SLDLM_APP_OAKMONT_JAVA,
    USR_SLDLM_APP_OAKMONT_JAVA_EX,
    USR_SLDLM_APP_USB,
    USR_SLDLM_APP_MP3DECINIT,
    USR_SLDLM_APP_AACDECINIT,
    USR_SLDLM_APP_SRSWOWHD,
    USR_SLDLM_APP_MRFILE_BUFFER,
    USR_SLDLM_APP_EMAPP,
    USR_SLDLM_APP_OFFAPP,
    USR_SLDLM_APP_SOKOBANAPP,    
    USR_SLDLM_APP_CC,                   ///< CC SL-DLM ID    
    USR_SLDLM_APP_SS,                   ///< SS SL-DLM ID    
    USR_SLDLM_APP_SMS,                  ///< SMS SL-DLM ID    
    USR_SLDLM_APP_MMGMM,                ///< MMGMM SL-DLM ID
    USR_SLDLM_APP_INDIANCALENDAR,
    USR_SLDLM_APP_LAST,
    USR_SLDLM_APP_INVALID = 255
};

//=================================================//
//==== Define System load/unload SLDLM APP ID =====//
//=================================================//
enum {
    SYS_SLDLM_APP_NONE = 0,
    SYS_SLDLM_APP_DUMMY,
    SYS_SLDLM_APP_LAST,
    SYS_SLDLM_APP_INVALID = 255
};

//=================================================//
//===== Define User load/unload SLDLM SLOT ID =====//
//=================================================//
enum {
    USR_SLDLM_SLOT_1M_POOL0,
    USR_SLDLM_SLOT_1M_POOL1,
    USR_SLDLM_SLOT_1M_POOL2,
    USR_SLDLM_SLOT_1M_POOL3,
    USR_SLDLM_SLOT_1M_POOL4,
    USR_SLDLM_SLOT_1M_POOL5,
    USR_SLDLM_SLOT_1M_POOL6,
    USR_SLDLM_SLOT_1M_POOL7,
    USR_SLDLM_SLOT_VIDEC_COMMON,
    USR_SLDLM_SLOT_M4VDEC,
    USR_SLDLM_SLOT_AVCDEC,
    USR_SLDLM_SLOT_RVCDEC,
    USR_SLDLM_SLOT_COOKDEC,
    USR_SLDLM_SLOT_AVP_PLAYER,
    USR_SLDLM_SLOT_CAPTURE,
    USR_SLDLM_SLOT_VDR,
    USR_SLDLM_SLOT_AMRNBDEC,
    USR_SLDLM_SLOT_AMRNBENC,
    USR_SLDLM_SLOT_MAP,
    USR_SLDLM_SLOT_MAR,
    USR_SLDLM_SLOT_HANDWRITING,
    USR_SLDLM_SLOT_WAP,
    USR_SLDLM_SLOT_AUDIO_ARP,
    USR_SLDLM_SLOT_SXM_CORE_ENGINE,     /// used for 3rd sxm target engine
    USR_SLDLM_SLOT_IME_MY,
    USR_SLDLM_SLOT_MJAVA,
    USR_SLDLM_SLOT_GPS,
    USR_SLDLM_SLOT_GPS_FW,
    USR_SLDLM_SLOT_CAMERA,
	USR_SLDLM_SLOT_ZYUE_ENGINE,
	USR_SLDLM_SLOT_ZMOL_ENGINE,
	USR_SLDLM_SLOT_SKY_ENGINE,
    USR_SLDLM_SLOT_TENCENTMCARE,
    USR_SLDLM_SLOT_PLATINIT,
    USR_SLDLM_SLOT_FMRX,
    USR_SLDLM_SLOT_BLUETOOTH,
    USR_SLDLM_SLOT_OAKMONT_JAVA,
    USR_SLDLM_SLOT_OAKMONT_JAVA_EX,
    USR_SLDLM_SLOT_USB,
    USR_SLDLM_SLOT_MP3DECINIT,
    USR_SLDLM_SLOT_AACDECINIT,
    USR_SLDLM_SLOT_SRSWOWHD,
    USR_SLDLM_SLOT_MRFILE_BUFFER,
    USR_SLDLM_SLOT_EMAPP,
    USR_SLDLM_SLOT_OFFAPP,
    USR_SLDLM_SLOT_SOKOBANAPP,
    USR_SLDLM_SLOT_CC,    
    USR_SLDLM_SLOT_SS,    
    USR_SLDLM_SLOT_SMS,    
    USR_SLDLM_SLOT_MMGMM,
    USR_SLDLM_SLOT_INDIANCALENDAR,
    USR_SLDLM_SLOT_LAST
};

//=================================================//
//==== Define System load/unload SLDLM SLOT ID ====//
//=================================================//
enum {
    SYS_SLDLM_SLOT_1M_POOL0,
    SYS_SLDLM_SLOT_LAST
};

#endif  /* __SYS_SYS_SLDLM_CFG_H__ */

