#ifndef _IMGCODEC_PLATFORM_H_
#define _IMGCODEC_PLATFORM_H_

#define IMGCODEC_USE_NEW_VERSION
#define IMGCODEC_USE_EXTERNAL_ZLIB
#define IMGCODEC_REDUCE_TRACE_STRING
#define IMGCODEC_SUPPORT_EXIF
#define IMGCODEC_SUPPORT_YUV422I
#define IMGCODEC_SUPPORT_YUV422P
#define IMGCODEC_LINK_TIME_DISPATCH
#undef  IMGCODEC_SMALL_DECODER
#define JPD_USE_SEMAPHORE
#define JPD_ISRAM

#undef  IMGCODEC_JPD_PROGRESSIVE
#define IMGCODEC_SUPPORT_JPG_MULTISCAN
#define IMGCODEC_SUPPORT_APNG
#define IMGCODEC_SUPPORT_WBMP
#define IMGCODEC_SUPPORT_MJPG
#define IMGCODEC_COMPILE_APNG

#ifdef __MDL_DISABLE_WBMP__
  #undef IMGCODEC_SUPPORT_WBMP
#endif

#if defined(__SMALL_ROM__) || defined(__SMALL_ROM_32__)
  #ifdef IMGCODEC_USE_HW_JPD
    #define IMGCODEC_USE_OLD_SW_JPD
  #endif
  #undef  IMGCODEC_SUPPORT_JPG_MULTISCAN
  #undef  IMGCODEC_SUPPORT_APNG
#endif

#ifdef IMGCODEC_SMALL_ROM_32
    #ifdef IMGCODEC_USE_BRAVO_SCL
      #undef  IMGCODEC_SUPPORT_YUV422I
    #endif
    #define IMGCODEC_SMALL_DECODER
    #undef  IMGCODEC_SUPPORT_EXIF
    #undef  IMGCODEC_SUPPORT_MJPG
    #undef  IMGCODEC_COMPILE_APNG
  #endif
#endif
