#ifndef __MMI_TODOLISTAPP_ID_H__
#define __MMI_TODOLISTAPP_ID_H__




#define TODOLIST_RECORDS_MAX_NUM_RS 6


/*============================================*/
// WINDIOW ID
/*============================================*/
typedef enum
{
    TODOLIST_WND_TODOLIST = WND_ID_APP_BASE,
    TODOLIST_WND_TODOLISTOPTION,
    TODOLIST_WND_EDITCONTENT,
    TODOLIST_WND_EDITCONTENTOPTION,
    TODOLIST_WND_PICKPRIORITY,
    TODOLIST_WND_ADDTASK,
    TODOLIST_WND_VIEWTASK,
    TODOLIST_WND_VIEWTASKOPTION,
    TODOLIST_WND_EDITTASK,
    TODOLIST_WND_SORTBY,
    TODOLIST_WND_SEND
} ToDoListWndId_e;

/*============================================*/
// MENU ID
/*============================================*/

typedef enum
{
    MNU_TODOLIST_VIEW=0,
    MNU_TODOLIST_EDIT,
    MNU_TODOLIST_ADD,
    MNU_TODOLIST_DELETE,
    MNU_TODOLIST_DELETEALL,
    MNU_TODOLIST_SORTBY,
    MNU_TODOLIST_SEND
}ToDoListWndToDoListOptMnuId_e;

typedef enum
{
    MNU_TODOLIST_HIGH=0,
    MNU_TODOLIST_NORMAL,
    MNU_TODOLIST_LOW
}ToDoListWndPriorityOptMnuId_e;

typedef enum
{
    MNU_TODOLIST_STATUS=0,
    MNU_TODOLIST_PRIORITY,
    MNU_TODOLIST_DUEDATE
}ToDoListWndSortByOptMnuId_e;

typedef enum
{
    MNU_TODOLIST_ADDTASK_CONTENT=0,
    MNU_TODOLIST_ADDTASK_PAPRIORITY,
    MNU_TODOLIST_ADDTASK_STATUS,
    MNU_TODOLIST_ADDTASK_REMINDER
}ToDoListWndSortBytMnuId_e;


typedef enum
{
    MNU_TODOLIST_SMS=0,
    //now is not support
    //MNU_TODOLIST_MMS
}ToDoListWndSendOptMnuId_e;

typedef enum
{
    MNU_TODOLIST_SET=0,
    MNU_TODOLIST_INPUTMENU
}ToDoListWndEditContentOptMnuId_e;

typedef enum
{
    MNU_TODOLIST_VIEWTASK_EDIT=0,
    MNU_TODOLIST_VIEWTASK_DELETE,
    MNU_TODOLIST_VIEWTASK_CHECK
}ToDoListWndViewTaskOptMnuId_e;

/*============================================*/
// WIDGET ID
/*============================================*/
// ­n§ï±¼
typedef enum
{
    TODOLIST_WDG_PRIORITYMENU=APP_WDG_START,
    TODOLIST_WDG_SORTBYMENU,
    TODOLIST_WDG_SENDMENU,
    TODOLIST_WDG_TEXT_PRIORITY,
    TODOLIST_WDG_TEXT_SORTBY
}ToDoListWdgId_e;

//TODOLIST_WND_ADDTASK WIDGET ID
typedef enum
{
    TODOLISTAPP_ADDTASK_VIEW_BEGIN = APP_WDG_START,
    TODOLISTAPP_ADDTASK_SCROLLBARWIDGET,
    TODOLISTAPP_ADDTASK_MFLCONTAINER,
    TODOLISTAPP_ADDTASK_CONTENT_DOUBLETEXTWIDGET,
    TODOLISTAPP_ADDTASK_PRIORITY_TEXTPICKWIDGET,
    TODOLISTAPP_ADDTASK_STATUS_TEXTPICKWIDGET,
#ifdef __APP_MMI_TODOLIST_VTODO__
    TODOLISTAPP_ADDTASK_DESCRIPTION_DOUBLETEXTWIDGET,
    TODOLISTAPP_ADDTASK_LOCATION_DOUBLETEXTWIDGET,
#endif 
    TODOLISTAPP_ADDTASK_REMINDER_TEXTPICKWIDGET,
    TODOLISTAPP_ADDTASK_DATE_DOUBLETEXTWIDGET,
    TODOLISTAPP_ADDTASK_TIME_DOUBLETEXTWIDGET
}ToDoListAddTaskWdgId_e;


/*============================================*/
// DIALOG ID
/*============================================*/

typedef enum
{
    TODOLISTAPP_DIALOG_INFO_TASKCREATED=0,
    TODOLISTAPP_DIALOG_INFO_TASKSAVED,
    TODOLISTAPP_DIALOG_INFO_TASKDELETED,
    TODOLISTAPP_DIALOG_INFO_STORAGEFULL,
    TODOLISTAPP_DIALOG_WARN_TASKDONOTEXIST,
    TODOLISTAPP_DIALOG_WARN_CREATETASKFAILED,
    TODOLISTAPP_DIALOG_WARN_SAVETASKFAILED,
    TODOLISTAPP_DIALOG_WARN_CONTENYEMPTY,
    TODOLISTAPP_DIALOG_CONFIRM_DELETESELECTTASK,
    TODOLISTAPP_DIALOG_CONFIRM_DELETEALLTASK,
    TODOLISTAPP_DIALOG_CONFIRM_SAVE_ALARMEXPIRED,
    TODOLISTAPP_DIALOG_CONFIRM_SAVE_ALARMPAST,
    TODOLISTAPP_DIALOG_WAITING_DELETING
}ToDoListDlgId_e;

#endif //__MMI_TODOLISTAPP_ID_H__

