#ifndef __MMI_SHORTCUTPHB_ID_H__
#define __MMI_SHORTCUTPHB_ID_H__

enum
{
    SHORTCUTPHB_WND_MAINWND = WND_ID_APP_BASE,
};

enum
{
	SHORTCUTPHB_WDG_MAINWND_IMG_BG = APP_WDG_START,
    SHORTCUTPHB_WDG_MAINWND_IMG_STATUSBAR,
	SHORTCUTPHB_WDG_MAINWND_3DLOADER,        
    SHORTCUTPHB_WDG_MAINWND_BTN_CALL,
    SHORTCUTPHB_WDG_MAINWND_BTN_SEND,
    SHORTCUTPHB_WDG_MAINWND_BTN_DELETE,    
    SHORTCUTPHB_WDG_MAINWND_BTN_BACK,
};

#endif //__MMI_SHORTCUTPHB_ID_H__

