ApBegin(RS,CLSID_SNOTEAPP)
	WndBegin(SNOTE_WND_LIST)
		WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_SKETCH_NOTE})
		WdgBegin(CLSID_MENUWIDGET,SNoteListMenuWdg)
            WdgMenuCreateForWndRC({0,MAIN_TITLE_HEIGHT,{SNOTEAPP_MAINVIEW_WIDTH,SNOTEAPP_NOST_NOSB_HEIGHT},WDG_MENU_TYPE_IMG_GRID})
        WdgEnd(CLSID_MENUWIDGET,SNoteListMenuWdg)
	WndEnd(SNOTE_WND_LIST)
	WndBegin(SNOTE_WND_PICKCOLOR)
		WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_SELECT_NOTE_COLOR})
		WdgBegin(CLSID_MENUWIDGET,SNotePickColorMenuWdg)
            WdgMenuCreateForWndRC({0,MAIN_TITLE_HEIGHT,{SNOTEAPP_MAINVIEW_WIDTH,SNOTEAPP_PICKCOLOR_MENUWIDGET_HEIGHT},WDG_MENU_TYPE_IMG_GRID})
			WdgStaticMenuItemRC(6,
				{{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_1}, {SKETCHNOTE_IMG_COLOR1_BG, TXT_NULL_ID}},\
				{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_2}, {SKETCHNOTE_IMG_COLOR2_BG, TXT_NULL_ID}},\
			    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_3}, {SKETCHNOTE_IMG_COLOR3_BG, TXT_NULL_ID}}, \
			    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_4}, {SKETCHNOTE_IMG_COLOR4_BG, TXT_NULL_ID}}, \
			    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_5}, {SKETCHNOTE_IMG_COLOR5_BG, TXT_NULL_ID}}, \
				{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, SNOTE_BGCOLOR_6}, {SKETCHNOTE_IMG_COLOR6_BG, TXT_NULL_ID}}})
            WdgMenuSetRowGapRC(SNOTEAPP_PICKCOLOR_MENUWDG_ROW_GAP)
            WdgMenuSetColGapRC(SNOTEAPP_PICKCOLOR_MENUWDG_COL_GAP)
            WdgMenuSetItemWidthRC(SNOTEAPP_RS_PICKCOLOR_MENU_ITEM_W)
            WdgMenuSetItemHeightRC(SNOTEAPP_RS_PICKCOLOR_MENU_ITEM_H)
            WdgCommonSetPaddingDataRC( {SNOTEAPP_RS_PICKCOLOR_Padding_L,SNOTEAPP_RS_PICKCOLOR_Padding_R,SNOTEAPP_RS_PICKCOLOR_Padding_T,SNOTEAPP_RS_PICKCOLOR_Padding_B} )
        WdgEnd(CLSID_MENUWIDGET,SNotePickColorMenuWdg)
	WndEnd(SNOTE_WND_PICKCOLOR)

	WndBegin(SNOTE_WND_EDITNOTE)
		WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_SKETCH_NOTE})
		WdgBegin(CLSID_IMAGEWIDGET,EditNoteImage)
            WdgImageCreateForWndRC({{SNOTEAPP_EDITNOTE_TOOLBAR_POS_X,SNOTEAPP_EDITNOTE_TOOLBAR_POS_Y+MAIN_TITLE_HEIGHT},\
            {SNOTEAPP_TOOLBAR_WIDTH,SNTOEAPP_TOOLBAR_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,SKETCHNOTE_IMG_BG}})
			WdgImageSetDataByIDRC(SKETCHNOTE_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,EditNoteImage)

		WdgBegin(CLSID_TEXTWIDGET,EditNoteText)
         WdgTextCreateForWndRC({{SNOTEAPP_EDITNOTE_SKETCHCANVAS_POS_X,SNOTEAPP_EDITNOTE_SKETCHCANVAS_POS_Y+MAIN_TITLE_HEIGHT},\
         {SNOTEAPP_SKETCHCANVAS_WIDTH,SNOTEAPP_SKETCHCANVAS_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,EditNoteText)


		WdgBegin(CLSID_SWITCHICONWIDGET,EditNotePenSwitchIcon)
        WdgSwitchIconCreateForWndRC({{SNOTEAPP_EDITNOTE_PEN_SWITCHICON_POS_X,SNOTEAPP_EDITNOTE_PEN_SWITCHICON_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_EDITNOTE_PEN_SWITCHICON_WIDTH,SNOTEAPP_EDITNOTE_PEN_SWITCHICON_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
		WdgEnd(CLSID_SWITCHICONWIDGET,EditNotePenSwitchIcon)

		WdgBegin(CLSID_SWITCHICONWIDGET,EditNoteStrokeSwitchIcon)
        WdgSwitchIconCreateForWndRC({{SNOTEAPP_EDITNOTE_STROKE_SWITCHICON_POS_X,SNOTEAPP_EDITNOTE_STROKE_SWITCHICON_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_EDITNOTE_STROKE_SWITCHICON_WIDTH,SNOTEAPP_EDITNOTE_STROKE_SWITCHICON_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
		WdgEnd(CLSID_SWITCHICONWIDGET,EditNoteStrokeSwitchIcon)

		WdgBegin(CLSID_SWITCHICONWIDGET,EditNoteColorSwitchIcon)
        WdgSwitchIconCreateForWndRC({{SNOTEAPP_EDITNOTE_COLOR_SWITCHICON_POS_X,SNOTEAPP_EDITNOTE_COLOR_SWITCHICON_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_EDITNOTE_COLOR_SWITCHICON_WIDTH,SNOTEAPP_EDITNOTE_COLOR_SWITCHICON_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
		WdgEnd(CLSID_SWITCHICONWIDGET,EditNoteColorSwitchIcon)

		WdgBegin(CLSID_SWITCHICONWIDGET,EditNoteEraserSwitchIcon)
        WdgSwitchIconCreateForWndRC({{SNOTEAPP_EDITNOTE_ERASER_SWITCHICON_POS_X,SNOTEAPP_EDITNOTE_ERASER_SWITCHICON_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_EDITNOTE_ERASER_SWITCHICON_WIDTH,SNOTEAPP_EDITNOTE_ERASER_SWITCHICON_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
		WdgEnd(CLSID_SWITCHICONWIDGET,EditNoteEraserSwitchIcon)

		WdgBegin(CLSID_BUTTONWIDGET,EditNoteTextButton)
        WdgButtonCreateForWndRC({{SNOTEAPP_EDITNOTE_TEXT_BTNWDG_POS_X,SNOTEAPP_EDITNOTE_TEXT_BTNWDG_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_EDITNOTE_TEXT_BTNWDG_WIDTH,SNOTEAPP_EDITNOTE_TEXT_BTNWDG_HEIGHT},0})
        WdgButtonSetDataByIDRC({TXT_NULL_ID,SKETCHNOTE_IMG_TEXT_UNPRESS,SKETCHNOTE_IMG_TEXT_PRESS})
		WdgEnd(CLSID_BUTTONWIDGET,EditNoteTextButton)



		WdgBegin(CLSID_MENUWIDGET,EditNoteStrokeGrid)
            WdgMenuCreateForWndRC({{SNOTEAPP_EDITNOTE_STROKE_LIST_POS_X,SNOTEAPP_EDITNOTE_STROKE_LIST_POS_Y+MAIN_TITLE_HEIGHT},\
            {SNOTEAPP_EDITNOTE_STROKE_LIST_WIDTH,SNOTEAPP_EDITNOTE_STROKE_LIST_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(3,
				{
					{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_1_UNPRESSED, SKETCHNOTE_IMG_STROKE_1_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_2_UNPRESSED, SKETCHNOTE_IMG_STROKE_2_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_3_UNPRESSED, SKETCHNOTE_IMG_STROKE_3_PRESSED}} \
				})

            WdgMenuSetItemWidthRC(SNOTEAPP_TOOLBAR_STROKE_WIDTH)
            WdgMenuSetItemHeightRC(SNOTEAPP_TOOLBAR_STROKE_HEIGHT)
            WdgMenuSetRowGapRC(0)
            WdgMenuSetColGapRC(0)
            WdgMenuSetFixedNumRC(1)
            
        WdgEnd(CLSID_MENUWIDGET,EditNoteStrokeGrid)

		WdgBegin(CLSID_MENUWIDGET,EditNoteColorGrid)
            WdgMenuCreateForWndRC({{SNOTEAPP_EDITNOTE_COLOR_LIST_POS_X,SNOTEAPP_EDITNOTE_COLOR_LIST_POS_Y+MAIN_TITLE_HEIGHT},\
            {SNOTEAPP_EDITNOTE_COLOR_LIST_WIDTH,SNOTEAPP_EDITNOTE_COLOR_LIST_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(10,
				{
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR1_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR1_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR2_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR2_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR3_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR3_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR4_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR4_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR5_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR5_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR6_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR6_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR7_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR7_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR8_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR8_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR9_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR9_PRESSED}}, \
				    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9}, {TXT_NULL_ID, SKETCHNOTE_IMG_STROKE_COLOR10_UNPRESSED, SKETCHNOTE_IMG_STROKE_COLOR10_PRESSED}} \
				})
    		WdgMenuSetToGridStyleRC({5,2,WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
            WdgMenuSetItemWidthRC(SNOTEAPP_EDITNOTE_COLOR_LIST_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(SNOTEAPP_EDITNOTE_COLOR_LIST_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(SNOTEAPP_EDITNOTE_COLOR_LIST_ITEM_ROW_GAP)
            WdgMenuSetColGapRC(SNOTEAPP_EDITNOTE_COLOR_LIST_ITEM_COL_GAP)
            WdgMenuSetFixedNumRC(SNOTEAPP_EDITNOTE_COLOR_LIST_ITEM_PROP_FIXED_NUM)				
        WdgEnd(CLSID_MENUWIDGET,EditNoteColorGrid)
	WndEnd(SNOTE_WND_EDITNOTE)

	WndBegin(SNOTE_WND_VIEWER)
	    WndSetAllSoftkeyRC({SK_OPTION, SK_OK, SK_BACK})
		WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_SKETCH_NOTE})
		WdgBegin(CLSID_TEXTWIDGET,SNoteViewerTimeStampTxt)
         WdgTextCreateForWndRC({{SNOTEAPP_VIEWER_TIMESTAMP_TEXTWDG_POS_X,MAIN_TITLE_HEIGHT},\
         {SNOTEAPP_VIEWER_TIMESTAMP_TEXTWDG_WIDTH,SNOTEAPP_VIEWER_TIMESTAMP_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,SNoteViewerTimeStampTxt)

		WdgBegin(CLSID_BUTTONWIDGET,SNoteViewerPreBtn)
        WdgButtonCreateForWndRC({{SNOTEAPP_VIEWER_PREVIOUS_BTNWDG_POS_X,SNOTEAPP_VIEWER_PREVIOUS_BTNWDG_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_VIEWER_PREVIOUS_BTNWDG_WIDTH,SNOTEAPP_VIEWER_PREVIOUS_BTNWDG_HEIGHT},0})
        WdgButtonSetDataByIDRC({TXT_NULL_ID,SKETCHNOTE_IMG_PHOTO_PREVIOUS_UNPRESSED,SKETCHNOTE_IMG_PHOTO_PREVIOUS_PRESSED})
		WdgEnd(CLSID_BUTTONWIDGET,SNoteViewerPreBtn)

  		WdgBegin(CLSID_BUTTONWIDGET,SNoteViewerNextBtn)
        WdgButtonCreateForWndRC({{SNOTEAPP_VIEWER_NEXT_BTNWDG_POS_X,SNOTEAPP_VIEWER_NEXT_BTNWDG_POS_Y+MAIN_TITLE_HEIGHT},\
        {SNOTEAPP_VIEWER_NEXT_BTNWDG_WIDTH,SNOTEAPP_VIEWER_NEXT_BTNWDG_HEIGHT},0})
        WdgButtonSetDataByIDRC({TXT_NULL_ID,SKETCHNOTE_IMG_PHOTO_NEXT_UNPRESSED,SKETCHNOTE_IMG_PHOTO_NEXT_PRESSED})
		WdgEnd(CLSID_BUTTONWIDGET,SNoteViewerNextBtn)
	WndEnd(SNOTE_WND_VIEWER)

    WndBegin(SNOTE_WND_SELECT)
		WdgBegin(CLSID_IMAGEWIDGET,ImgWidget)
			WdgImageCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,MAIN_TITLE_HEIGHT+MAIN_LCD_ONELINE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,ImgWidget)

        WdgBegin(CLSID_IMGGRID_MENUWIDGET,MenuGridWidget)           
	        WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_DEFVIEW_HEIGHT},WDG_MENU_TYPE_IMG_GRID})   
	        WdgCommonSetPaddingDataRC( {5,5,8,8} )       
	        WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)     
	        WdgCommonSetBGColorRC(DEF_THM_SNOTEAPP_MENUGRID_BG)      
			WdgStaticMenuItemRC(3,
				{
					{{MENUMODEL_ITEM_VISABLE, {SK_OPTION, SK_OK, SK_EXIT}, 0}, {COMMON_IMG_L_PHONE, TXT_LIL_N_PHONE_MEMORY}},\
					{{MENUMODEL_ITEM_VISABLE, {SK_OPTION, SK_OK, SK_EXIT}, 1}, {COMMON_IMG_L_SD_CARD, TXT_LIL_N_CARD_MEMORY}},\
					{{MENUMODEL_ITEM_VISABLE, {SK_OPTION, SK_OK, SK_EXIT}, 2}, {COMMON_IMG_L_SD_CARD, TXT_LIL_N_CARD2_MEMORY}}
				}
			)		
            WdgMenuSetItemWidthRC(MAIN_THUMBNAIL_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(MAIN_THUMBNAIL_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(MAIN_THUMBNAIL_ITEM_ROW_GAP)
            WdgMenuSetColGapRC(MAIN_THUMBNAIL_ITEM_COL_GAP)                
        WdgEnd(CLSID_IMGGRID_MENUWIDGET,MenuGridWidget)   
     WndEnd(SNOTE_WND_SELECT)
ApEnd(RS,CLSID_SNOTEAPP)

