#ifndef __MMI_SNOTEAPP_ID_H__
#define __MMI_SNOTEAPP_ID_H__

/* id for pickup color menu item*/
enum
{
	SNOTE_BGCOLOR_1 = 1,
	SNOTE_BGCOLOR_2,
	SNOTE_BGCOLOR_3,
	SNOTE_BGCOLOR_4,
	SNOTE_BGCOLOR_5,
	SNOTE_BGCOLOR_6,
};

enum
{
    SNOTE_WND_LIST = WND_ID_APP_BASE,
    SNOTE_WND_PICKCOLOR,
    SNOTE_WND_EDITNOTE,
    SNOTE_WND_INPUTTEXT,
    SNOTE_WND_VIEWER,
    SNOTE_WND_OPTIONMENU,
    SNOTE_WND_SELECT,
    SNOTE_WND_POPUPSELECT
};

enum
{
    SNOTE_LIST_MENU=APP_WDG_START,

    SNOTE_PICKCOLOR_MENU,

    SNOTE_EDIT_IMAGE,
    SNOTE_EDIT_BITMAP,
    SNOTE_EDIT_TEXT,
    SNOTE_EDIT_PEN_SWITCHICON,
    SNOTE_EDIT_STROKE_SWITCHICON,
    SNOTE_EDIT_COLOR_SWITCHICON,
    SNOTE_EDIT_TEXT_BTN,
    SNOTE_EDIT_ERASER_SWITCHICON,
    SNOTE_EDIT_STROKE_GRID,
    SNOTE_EDIT_COLOR_GRID,

    SNOTE_VIEWER_TRANSITION,
    SNOTE_VIEWER_BITMAP,
    SNOTE_VIEWER_TIME_TEXT,
    SNOTE_VIEWER_PREVIOUS_BTN,
    SNOTE_VIEWER_NEXT_BTN,

};

typedef enum
{
	MNU_SNOTEAPP_LIST_OPTION = 0,
	MNU_SNOTEAPP_LO_VIEW,
	MNU_SNOTEAPP_LO_EDIT,
	MNU_SNOTEAPP_LO_ADD,
	MNU_SNOTEAPP_LO_DELETE,
	MNU_SNOTEAPP_LO_DELETE_ALL,
	MNU_SNOTEAPP_EDIT_OPTION,
	MNU_SNOTEAPP_LO_SAVE,
	MNU_SNOTEAPP_LO_CLEAR,
}SnoteMenuId_e;

#endif //__MMI_SNOTEAPP_ID_H__

