/**
 @file ahc_audio_inc.h
 @brief Header File for the AHC audio API.
 @author
 @version 1.0
*/

#ifndef _AHC_AUDIO_INC_H_
#define _AHC_AUDIO_INC_H_

/*===========================================================================
 * Include files
 *===========================================================================*/
//Do not include other files in xxx_inc.h

/*===========================================================================
 * Macro define
 *===========================================================================*/
/*===========================================================================
 * Enum define
 *===========================================================================*/
typedef enum _AHC_AUDIO_CODEC_FORMAT {
    AHC_AUDIO_CODEC_NONE        = 0x0,
    AHC_AUDIO_CODEC_AMR_NB      = 0x1,
    AHC_AUDIO_CODEC_AMR         = 0x1,
    AHC_AUDIO_CODEC_AAC_LC      = 0x2,
    AHC_AUDIO_CODEC_AAC         = 0x2,
    AHC_AUDIO_CODEC_AAC_PLUS    = 0x4,
    AHC_AUDIO_CODEC_MP3         = 0x08,
    AHC_AUDIO_CODEC_WMA         = 0x10,
    AHC_AUDIO_CODEC_AC3         = 0x20,
    AHC_AUDIO_CODEC_WAV         = 0x40,
    AHC_AUDIO_CODEC_RA          = 0x80,
    AHC_AUDIO_CODEC_UNSUPPORTED = 0x100,
    AHC_AUDIO_CODEC_MAX
} AHC_AUDIO_CODEC_FORMAT;

typedef enum _AHC_SOUNDEFFECT_TYPE {
    AHC_SOUNDEFFECT_SHUTTER = 0,
    AHC_SOUNDEFFECT_START,
    AHC_SOUNDEFFECT_BUTTON,
    AHC_SOUNDEFFECT_VR_START,
    //from HCarDV.wifi porting
    AHC_SOUNDEFFECT_VIDEO_REC = AHC_SOUNDEFFECT_VR_START,
    AHC_SOUNDEFFECT_VR_STOP,

    AHC_SOUNDEFFECT_VR_SAVE,
    AHC_SOUNDEFFECT_VR_EMER,
    AHC_SOUNDEFFECT_FOCUS,
    AHC_SOUNDEFFECT_ERROR,
    AHC_SOUNDEFFECT_CONFIRM,
    AHC_SOUNDEFFECT_SELFTIMER,
    AHC_SOUNDEFFECT_NO_SD_CARD,

    AHC_SOUNDEFFECT_POWERON,
    AHC_SOUNDEFFECT_POWEROFF,

    AHC_SOUNDEFFECT_MICON,
    AHC_SOUNDEFFECT_MICOFF,

    AHC_SOUNDEFFECT_FILELOCK,
    AHC_SOUNDEFFECT_FILEUNLOCK,

    AHC_SOUNDEFFECT_CARDFULL,

    AHC_SOUNDEFFECT_TEST,

    AHC_SOUNDEFFECT_SPCAM_START = 0x20,
    AHC_SOUNDEFFECT_SPCAMWARN,
    AHC_SOUNDEFFECT_SPCAMVOICE_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_CHS,

    AHC_SOUNDEFFECT_SPCAMVOICE_RUS,
    AHC_SOUNDEFFECT_SPCAMVOICE_ENG,
    AHC_SOUNDEFFECT_SPCAMRELEASE,
    AHC_SOUNDEFFECT_SPCAMOVERSPEED,
    AHC_SOUNDEFFECT_SPCAMVOICE_15KM_CHT,

    AHC_SOUNDEFFECT_SPCAMVOICE_20KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_25KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_30KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_35KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_40KM_CHT,

    AHC_SOUNDEFFECT_SPCAMVOICE_50KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_60KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_70KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_80KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_90KM_CHT,

    AHC_SOUNDEFFECT_SPCAMVOICE_100KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_110KM_CHT,
    AHC_SOUNDEFFECT_SPCAMVOICE_120KM_CHT,

    AHC_SOUNDEFFECT_SPCAMVOICE_SPEED_DESCRIPTION,
    AHC_SOUNDEFFECT_SPCAMVOICE_SPEED_LIMIT,

    AHC_SOUNDEFFECT_SPCAMVOICE_10,
    AHC_SOUNDEFFECT_SPCAMVOICE_20,
    AHC_SOUNDEFFECT_SPCAMVOICE_30,
    AHC_SOUNDEFFECT_SPCAMVOICE_35,
    AHC_SOUNDEFFECT_SPCAMVOICE_40,
    AHC_SOUNDEFFECT_SPCAMVOICE_50,
    AHC_SOUNDEFFECT_SPCAMVOICE_55,
    AHC_SOUNDEFFECT_SPCAMVOICE_60,
    AHC_SOUNDEFFECT_SPCAMVOICE_65,

    AHC_SOUNDEFFECT_SPCAMVOICE_70,
    AHC_SOUNDEFFECT_SPCAMVOICE_75,
    AHC_SOUNDEFFECT_SPCAMVOICE_80,
    AHC_SOUNDEFFECT_SPCAMVOICE_85,
    AHC_SOUNDEFFECT_SPCAMVOICE_90,
    AHC_SOUNDEFFECT_SPCAMVOICE_100,
    AHC_SOUNDEFFECT_SPCAMVOICE_105,
    AHC_SOUNDEFFECT_SPCAMVOICE_110,
    AHC_SOUNDEFFECT_SPCAMVOICE_115,

    AHC_SOUNDEFFECT_SPCAMVOICE_120,
    AHC_SOUNDEFFECT_SPCAMVOICE_125,
    AHC_SOUNDEFFECT_SPCAMVOICE_130,
    AHC_SOUNDEFFECT_SPCAMVOICE_140,
    AHC_SOUNDEFFECT_SPCAMVOICE_150,

    AHC_SOUNDEFFECT_SPCAMVOICE_160,
    AHC_SOUNDEFFECT_SPCAMVOICE_170,
    AHC_SOUNDEFFECT_SPCAMVOICE_180,
    AHC_SOUNDEFFECT_SPCAMVOICE_190,
    AHC_SOUNDEFFECT_SPCAMVOICE_200,

    AHC_SOUNDEFFECT_SPCAMVOICE_KM,
    AHC_SOUNDEFFECT_SPCAMVOICE_MPH,

    AHC_SOUNDEFFECT_PLAYSOUND_EVENT,

    AHC_SOUNDEFFECT_PARKING,
    AHC_SOUNDEFFECT_CARD_ERROR,
    AHC_SOUNDEFFECT_INSERT_SD_CARD,
    AHC_SOUNDEFFECT_CHECK_SD_CARD,
    AHC_SOUNDEFFECT_FONTT_CAM_ERROR,

    AHC_SOUNDEFFECT_SPCAM_END,

    /////////////////////////////////////////////////////////////////////////////////
    //from HCarDV.wifi
    /////////////////////////////////////////////////////////////////////////////////
    AHC_SOUNDEFFECT_BATWARNING,
    AHC_SOUNDEFFECT_LOCK_DELETE,
    AHC_SOUNDEFFECT_FINDME,
    AHC_SOUNDEFFECT_WIFIFAIL,

    AHC_SOUNDEFFECT_ATTENTION,
    AHC_SOUNDEFFECT_LDWS_WARNING,
    AHC_SOUNDEFFECT_FCWS_WARNING,

    AHC_SOUNDEFFECT_HEADLIGHT_WARNING,
    AHC_SOUNDEFFECT_FATIGUE_ALERT,  //0x3F

    AHC_SOUNDEFFECT_TPMS_ERR,
    AHC_SOUNDEFFECT_PRESSURE_ERR,
    AHC_SOUNDEFFECT_TEMP_ERR,

    AHC_SOUNDEFFECT_GPS_LINK,

    AHC_SOUNDEFFECT_MAX_NUM
}AHC_SOUNDEFFECT_TYPE;

typedef enum _AHC_MSOUND_TYPE {
    AHC_MSOUND_NULL = 0,
    AHC_MSOUND_START,
    AHC_MSOUND_MIDDLE,
    AHC_MSOUND_END
}AHC_MSOUND_TYPE;

typedef enum _AHC_SOUND_IMPORTANCE {
    AHC_SOUND_IMPORTANCE_NECESSARY = 0,     //Necessary
    AHC_SOUND_IMPORTANCE_MAYBELOST      //May be lost
}AHC_SOUND_IMPORTANCE;

typedef enum _AHC_SOUND_EFFECT_STATUS {
    AHC_SOUND_EFFECT_STATUS_START = 0,  ///< play start
    AHC_SOUND_EFFECT_STATUS_PAUSE ,     ///< play pause
    AHC_SOUND_EFFECT_STATUS_STOP  ,     ///< play stop
    AHC_SOUND_EFFECT_STATUS_INVALID     ///< invalid status
}AHC_SOUND_EFFECT_STATUS;


/*===========================================================================
 * Structure define
 *===========================================================================*/
typedef struct _AHC_SOUND_FILE_ATTRIBUTE
{
    char    path[256];
    UINT32  ulStartAddress;
    UINT32  ulSize;
} AHC_SOUND_FILE_ATTRIBUTE;

/*===========================================================================
 * Function prototype
 *===========================================================================*/


#endif // _AHC_AUDIO_INC_H_
