#if defined(__3D_UI_KEYGUARD__)

ApBegin(RS,CLSID_KEYGUARDAPP)
    WndBegin(KEYGUARD_WND_MAIN)
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)
        WndSetAllSoftkeyRC({SK_NONE, SK_NONE, SK_UNLOCK})

#if defined(__3D_UI_KEYGUARD_GLOW__)
        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_SCREEN_LOCK_BG}})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_TOP)
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,UnlockWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_LOCKWIDGET_POS_X,GL_KEYGUARDAPP_LAYOUT_LOCKWIDGET_POS_Y},{GL_KEYGUARDAPP_LAYOUT_LOCKWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_LOCKWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_UNLOCK_SLIDE}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED)
        WdgEnd(CLSID_IMAGEWIDGET,UnlockWdg)

        WdgBegin(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
            WdgMenuCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_BOTTOM)
            WdgStaticMenuItemRC(5, {
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},0},{COMMON_IMG_M303_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},1},{COMMON_IMG_M303_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},2},{COMMON_IMG_M303_LOCKED_SYMBOL, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},3},{COMMON_IMG_M303_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},4},{COMMON_IMG_M303_LOCKED_NUM9, TXT_NULL_ID}},
                            } )

            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(GL_KEYGUARDAPP_LAYOUT_TIMEWIDGET_ITEM_HEIGHT)
            WdgMenuSetFixedNumRC(5)
            WdgMenuSetToGridStyleRC({5, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})


        WdgEnd(CLSID_IMGGRID_MENUWIDGET,TimeWdg)

        WdgBegin(CLSID_TEXTWIDGET,I12HWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_12HWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_12HWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_12HWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_12HWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PDL_N_AM)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TIME_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_BOTTOM)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,I12HWdg)

        WdgBegin(CLSID_TEXTWIDGET,DateWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_DATEWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_DATEWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_DATEWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_DATEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,DateWdg)

        WdgBegin(CLSID_TEXTWIDGET,MediaNameWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,MediaNameWdg)

        WdgBegin(CLSID_IMAGEWIDGET,CountdownWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_COUNTDOWN_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_COUNTDOWN_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_COUNTDOWN_WIDTH,GL_KEYGUARDAPP_LAYOUT_COUNTDOWN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_LOCKED_COUNDOWN_TIMER}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_COUNDOWN_TIMER)
        WdgEnd(CLSID_IMAGEWIDGET,CountdownWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_NETWORK_POS_X,GL_KEYGUARDAPP_LAYOUT_NETWORK_POS_Y},{GL_KEYGUARDAPP_LAYOUT_NETWORK_WIDTH,GL_KEYGUARDAPP_LAYOUT_NETWORK_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkSlaveWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_POS_X,GL_KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_POS_Y},{GL_KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_WIDTH,GL_KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkSlaveWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DialogInfoBGWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_POS_X,GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_POS_Y},{GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_WIDTH,GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_UNLOCK_NOTICE_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_UNLOCK_NOTICE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,DialogInfoBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,DialogInfoTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE|LAYOUT_ELLIPSIS)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,DialogInfoTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MissCallWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_MISS_CALL_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_MISS_CALL_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_MISS_CALL_WIDTH,GL_KEYGUARDAPP_LAYOUT_MISS_CALL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_LOCKED_MISS_CALL}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_LOCKED_MISS_CALL)
        WdgEnd(CLSID_IMAGEWIDGET,MissCallWdg)

        WdgBegin(CLSID_TEXTWIDGET,MissCallTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MissCallTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,NewMsgWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_NEW_MSG_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_NEW_MSG_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_NEW_MSG_WIDTH,GL_KEYGUARDAPP_LAYOUT_NEW_MSG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_LOCKED_MESSAGE}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_LOCKED_MESSAGE)
        WdgEnd(CLSID_IMAGEWIDGET,NewMsgWdg)

        WdgBegin(CLSID_TEXTWIDGET,NewMsgTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NewMsgTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,SlideTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_SLIDE_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_SLIDE_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_SLIDE_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_SLIDE_TEXT_HEIGHT},TEXT_STYLE_HIGHLIGHT})
            WdgTextSetDataByIDRC(TXT_SSL_N_SLIDE_TO_UNLOCK)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,SlideTextWdg)
#endif

        WdgBegin(CLSID_IMAGEWIDGET,EMNum1Wdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_EMNUM_IMAGE_POS_X,GL_KEYGUARDAPP_LAYOUT_EMNUM_IMAGE_POS_Y},{GL_KEYGUARDAPP_LAYOUT_EMNUM_IMAGE_WIDTH,GL_KEYGUARDAPP_LAYOUT_EMNUM_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,EMNum1Wdg)

#if defined(__3D_UI_KEYGUARD_BEAUTY_CLK__)
        WdgBegin(CLSID_IMAGEWIDGET,EMNumBGWdg)
            WdgImageCreateForWndRC({{0,0},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_EMNUM_CNTR_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_EMNUM_CNTR_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,COMMON_IMG_M303_LOCKED_TITLE_BG1}})
        WdgEnd(CLSID_IMAGEWIDGET,EMNumBGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BottomBGWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_BOTTOM_BG_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_BOTTOM_BG_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_BOTTOM_BG_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_BOTTOM_BG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,COMMON_IMG_M303_LOCKED_TITLE_BG2}})
        WdgEnd(CLSID_IMAGEWIDGET,BottomBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyDateWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DATEWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DATEWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DATEWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DATEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyDateWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyMediaNameWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MEDIANAMEWIDGET_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MEDIANAMEWIDGET_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MEDIANAMEWIDGET_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MEDIANAMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyMediaNameWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyNetworkWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyNetworkWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyNetworkSlaveWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_SLAVE_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_SLAVE_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_SLAVE_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NETWORK_SLAVE_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyNetworkSlaveWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BeautyDialogInfoBGWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_BG_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_BG_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_BG_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_UNLOCK_NOTICE_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_UNLOCK_NOTICE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,BeautyDialogInfoBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyDialogInfoTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_DIALOG_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE|LAYOUT_ELLIPSIS)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,BeautyDialogInfoTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BeautyMissCallWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_LOCKED_MISS_CALL}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_LOCKED_MISS_CALL)
        WdgEnd(CLSID_IMAGEWIDGET,BeautyMissCallWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyMissCallTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_MISS_CALL_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyMissCallTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BeautyNewMsgWdg)
            WdgImageCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_POS_X_OFFSET,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_POS_Y_OFFSET},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_LOCKED_MESSAGE}})
            WdgImageSetDataByIDRC(COMMON_IMG_M303_LOCKED_MESSAGE)
        WdgEnd(CLSID_IMAGEWIDGET,BeautyNewMsgWdg)

        WdgBegin(CLSID_TEXTWIDGET,BeautyNewMsgTextWdg)
            WdgTextCreateForWndRC({{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_TEXT_POS_X,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_TEXT_POS_Y},{GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_TEXT_WIDTH,GL_KEYGUARDAPP_LAYOUT_BEAUTY_NEW_MSG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,BeautyNewMsgTextWdg)
#endif

    WndEnd(KEYGUARD_WND_MAIN)
ApEnd(RS,CLSID_KEYGUARDAPP)

#else


ApBegin(RS,CLSID_KEYGUARDAPP)
    WndBegin(KEYGUARD_WND_MAIN)
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)
        WndSetAllSoftkeyRC({SK_UNLOCK, SK_NONE, SK_NONE})
        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
#ifdef __APP_MMI_SMALLROM__
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,WALLPAPER_IMG_04}})
#else
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,WALLPAPER_IMG_06}})
#endif
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,UnlockWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_LOCKWIDGET_POS_X,KEYGUARDAPP_LAYOUT_LOCKWIDGET_POS_Y},{KEYGUARDAPP_LAYOUT_LOCKWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_LOCKWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED)
        WdgEnd(CLSID_IMAGEWIDGET,UnlockWdg)

        WdgBegin(CLSID_FADEOUTWIDGET,DarkWdg)
            WdgFadeoutCreateForWndRC({{KEYGUARDAPP_LAYOUT_DARKNESSWIDGET_POS_X,KEYGUARDAPP_LAYOUT_DARKNESSWIDGET_POS_Y-MAIN_STBAR_HEIGHT},{KEYGUARDAPP_LAYOUT_DARKNESSWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_DARKNESSWIDGET_HEIGHT},FADEOUT_LEVEL_4})
        WdgEnd(CLSID_FADEOUTWIDGET,DarkWdg)

        WdgBegin(CLSID_TEXTWIDGET,EMNumWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_EMNUMWIDGET_POS_X,KEYGUARDAPP_LAYOUT_EMNUMWIDGET_POS_Y-KEYGUARDAPP_LAYOUT_DARKNESSWIDGET_POS_Y},{KEYGUARDAPP_LAYOUT_EMNUMWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_EMNUMWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
#ifndef __LCM_QQVGA_MMI__
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_SUPERLARGE)
#else
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_NORMAL)
#endif
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_DIAL_NUMBER_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,EMNumWdg)
#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_TEXTWIDGET,TimeWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_TIMEWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_TIMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PDL_N_AM)
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_LARGE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TIME_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TimeWdg)
#else
        WdgBegin(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
            WdgMenuCreateForWndRC({{KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_TIMEWIDGET_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_TIMEWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_TIMEWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_BOTTOM)
            WdgStaticMenuItemRC(5, {
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},0},{COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},1},{COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},2},{COMMON_IMG_LOCKED_SYMBOL, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},3},{COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},4},{COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            } )

            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(KEYGUARDAPP_RS_TIME_ITEM_W)
            WdgMenuSetItemHeightRC(KEYGUARDAPP_RS_TIME_ITEM_H)
            WdgMenuSetFixedNumRC(5)
            WdgMenuSetToGridStyleRC({5, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})
        WdgEnd(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
#endif
        WdgBegin(CLSID_TEXTWIDGET,I12HWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_12HWIDGET_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_12HWIDGET_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_12HWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_12HWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PDL_N_AM)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TIME_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_BOTTOM)
        WdgEnd(CLSID_TEXTWIDGET,I12HWdg)

        WdgBegin(CLSID_TEXTWIDGET,DateWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_DATEWIDGET_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_DATEWIDGET_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_DATEWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_DATEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_DATE_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,DateWdg)

        WdgBegin(CLSID_TEXTWIDGET,MediaNameWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_WIDTH,KEYGUARDAPP_LAYOUT_MEDIANAMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
#ifdef __APP_MMI_SMALLROM__
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
#else
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
#endif
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MediaNameWdg)

        WdgBegin(CLSID_IMAGEWIDGET,CountdownWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_COUNTDOWN_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_COUNTDOWN_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_COUNTDOWN_WIDTH,KEYGUARDAPP_LAYOUT_COUNTDOWN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_COUNDOWN_TIMER}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_COUNDOWN_TIMER)
        WdgEnd(CLSID_IMAGEWIDGET,CountdownWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_NETWORK_POS_X,KEYGUARDAPP_LAYOUT_NETWORK_POS_Y},{KEYGUARDAPP_LAYOUT_NETWORK_WIDTH,KEYGUARDAPP_LAYOUT_NETWORK_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkSlaveWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_POS_X,KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_POS_Y},{KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_WIDTH,KEYGUARDAPP_LAYOUT_NETWORK_SLAVE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkSlaveWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DialogInfoBGWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_POS_X,KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_POS_Y},{KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_WIDTH,KEYGUARDAPP_LAYOUT_DIALOG_INFO_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_UNLOCK_NOTICE_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_UNLOCK_NOTICE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,DialogInfoBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,DialogInfoTextWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_POS_X,KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_POS_Y},{KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_WIDTH,KEYGUARDAPP_LAYOUT_DIALOG_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE|LAYOUT_ELLIPSIS)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(KEYGUARDAPP_RS_DLG_FONT_CATE)
        WdgEnd(CLSID_TEXTWIDGET,DialogInfoTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MissCallWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_MISS_CALL_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_MISS_CALL_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_MISS_CALL_WIDTH,KEYGUARDAPP_LAYOUT_MISS_CALL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MISS_CALL}})
#ifdef __DUAL_SIM_MMI__
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MISS_CALL_SIM1)
#else
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MISS_CALL)
#endif
        WdgEnd(CLSID_IMAGEWIDGET,MissCallWdg)

        WdgBegin(CLSID_TEXTWIDGET,MissCallTextWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_POS_X,KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_POS_Y},{KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_WIDTH,KEYGUARDAPP_LAYOUT_MISS_CALL_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MissCallTextWdg)
#ifdef __DUAL_SIM_MMI__
        WdgBegin(CLSID_IMAGEWIDGET,MissCallSlaveWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_WIDTH,KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MISS_CALL}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MISS_CALL_SIM2)
        WdgEnd(CLSID_IMAGEWIDGET,MissCallSlaveWdg)

        WdgBegin(CLSID_TEXTWIDGET,MissCallSlaveTextWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_TEXT_POS_X,KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_TEXT_POS_Y},{KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_TEXT_WIDTH,KEYGUARDAPP_LAYOUT_MISS_CALL_SLAVE_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MissCallSlaveTextWdg)
#endif
        WdgBegin(CLSID_IMAGEWIDGET,NewMsgWdg)
            WdgImageCreateForWndRC({{KEYGUARDAPP_LAYOUT_NEW_MSG_POS_X_OFFSET,KEYGUARDAPP_LAYOUT_NEW_MSG_POS_Y_OFFSET},{KEYGUARDAPP_LAYOUT_NEW_MSG_WIDTH,KEYGUARDAPP_LAYOUT_NEW_MSG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MESSAGE}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MESSAGE)
        WdgEnd(CLSID_IMAGEWIDGET,NewMsgWdg)

        WdgBegin(CLSID_TEXTWIDGET,NewMsgTextWdg)
            WdgTextCreateForWndRC({{KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_POS_X,KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_POS_Y},{KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_WIDTH,KEYGUARDAPP_LAYOUT_NEW_MSG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NewMsgTextWdg)
    WndEnd(KEYGUARD_WND_MAIN)
ApEnd(RS,CLSID_KEYGUARDAPP)

#endif
