#ifndef __OPTION_H__
#define __OPTION_H__

#define __ARMGCC__	1
#define __I_SW__	1
#define __I_SW_OS__	1
#define __I_SW_BOOTFAST__	1
#define __ISW_INFINITY1__	1
#define __NO_GPRS__	1
#define __CORTEX_A7__	1
#define __INFINITY__	1
#define CAMCORDER_FULL_MODE	1
#define __MSC316D__	1
#define __CHIP_STRING__	__MSC316D__
#define __CUS_DEFAULT__	1
#define __LOG_LEVEL_ALL__	1
#define __ENABLE_CAMERA__	1
#define __CAMERA_LOMO__	1
#define __CAMERA_MIRROR__	1
#define __ENABLE_CAMCORDER__	1
#define __SDK_API__	1
#define __WAP__	1
#define __MMS__	1
#define __EMS_MMI_SUPPORT__	1
#define __SMART_MESSAGING_MMI_SUPPORT__	1
#define __MMI_BATTERY_ICON_DISPLAY__	1
#define __CHIP_ADC_CALI_BY_EFUSE__	1
#define LCM_CONFIG_WIDTH	0
#define LCM_CONFIG_HEIGHT	0
#define __PANEL_DPM__	0
#define __BMP_BOOTUP_LOGO__	1
#define __LCM_ROTATE__	1
#define __TOUCH_SCREEN__	1
#define __R_MSTAR__	1
#define __MULTI_TOUCH_SLIM__	1
#define __DUAL_IMEI__	1
#define __HOOKKEY_FAKE_KEY_TIMER__	1
#define __LP_DETECTOR_DRV__	1
#define __MDL_AVI__	1
#define __APP_MMI_SHORTCUT__	1
#define __MMI_CALL_FIREWALL__	1
#define __CALLER_LOCATION__	1
#define __NOSIM_CAMP_ON_TEST_NETWORK__	1
#define __VIDEOPLAYERAPP_FFREWIND_SUPPORT__	1
#define __APP_MMI_FM_RADIO__	1
#define __APP_MMI_FM_RADIO_REC__	1
#define __APP_MMI_SHORTCUTLIST__	1
#define __APP_MMI_VOICE_MEMO__	1
#define __APP_MMI_CALENDAR__	1
#define __CALENDARAPP_SEARCH_MMI__	1
#define __SEARCHAPP_SEARCH_CALENDAR_MMI__	1
#define __CALENDAR_EXPORT_VCS_MMI__	1
#define __CALENDAR_IMPORT_VCS_MMI__	1
#define __EVENTDB_SEARCH_MMI__	1
#define __CALENDAR_SUPPORT_VCS_MMI__	1
#define __FDN_MMI__	1
#define __CAMERA_MIRROR_MMI__	1
#define __CAMERA_LOMO_MMI__	1
#define __DUAL_IMEI_MMI__	1
#define __PHB_SEND_MULTI_VCARD_BY_BT__	1
#define __MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__	1
#define __MMI_STATUSBAR_AUTO_ARRANGE__	1
#define __FEATURE_VECTOR_FONT__	1
#define __CODEPAGE_TO_UNICODE__	1
#define __AUTO_RECORDING_MMI__	1
#define __IN_CALL_RECORDING_MMI__	1
#define __PROGRAM_TEMP_IMEI_MMI__	1
#define __THAI_FONT__	1
#define __MMI_AUDIO_SEEK__	1
#define __MMI_ID3_SUPPORT__	1
#define __ONCHIP_FMRX_ENABLE__	1
#define __MULTIPLE_SENSOR_TABLE_DETECTION__	1
#define __SENSOR_LZF_SUPPORT__	1
#define __SCL_LOW_BANDWIDTH_MODE__	1
#define __DIALUP_NETWORKING__	1
#define __NEW_NOR_ARCH__	1
#define __MMI_SMS_WAPPUSH__	1
#define __DLM_OVER_ARM__	1
#define __MAK_ARM__	1
#define __AVP_ARM_9__	1
#define __MMAUDIO_ARM__	1
#define __RF_LDO_SLEEP_OFF__	1
#define __SLEEP_HANDLER__	1
#define __NAND_PWD_NOTIFY__	1
#define __LOW_BATTERY_DETECT_DEBOUNCE__	1
#define __RIU_INT_CTL__	1
#define __RTK_DBG_INFO__	1
#define __SIM_SRAM__	1
#define __SIM_SRAM_ADDR_B9__	1
#define __MMP_SLEEP_RESET__	1
#define __FCIE_SDIO_SHARE_IP__	1
#define __MMI_SMALL_CALLER_PHOTO__	1
#define __NO_HW_JPD__	1
#define __DRV_NO_HW_DMA__	1
#define __BT_MAC_BLOSSOM__	1
#define __DSP_BLOSSOM__	1
#define __INCENSE_3__	1
#define __SHARE_MEM__	1
#define __LZMA2_PRESET_DICT__	1
#define __NO_ASURA__	1
#define ZLIB_USE_ROM	0
#define ZLIB_BUILD_ROM	0
#define __TARGET_DSP_PATCH_SOLO_BIN__	1
#define __CHIPDRV_MM_TIMER___	1
#define __NO_INTEGRITY_CHK_AT_PWRON__	1
#define __ROMPATCH_SUPPORT__	1
#define __GDMA_SUPPORT__	1
#define __WLED_SHUNT_SUPPORT__	1
#define WLED_LEVEL_COUNT	63
#define __DUAL_CARD__	1
#define __SD1_4_BITS_SD2_4_BITS__	1
#define __SD1_HOT_PLUG_INSERT_LOW__	1
#define __SD2_HOT_PLUG_INSERT_LOW__	1
#define __MEMCARD_HOTPLUG__	1
#define __MEMCARD_HOTPLUG__	1
#define __DOWNGRADE_SD_CLOCK__	50000
#define __STG_IP_SDIO__	1
#define __FMS_RAI_DEBUG__	1
#define __FMS_E2P_DEBUG__	1
#define __RES_MGR_DEBUG__	1
#define __FMS_E2P_STATE__	1
#define __FMS_E2P_FAC_ITF__	1
#define __REGISTER_TEST_TOOL__	1
#define __MMP_PWR_MNGT__	1
#define __EMA_DISPLAY__	1
#define __PERIODIC_CHARGING_STOP_CHECK_BATTERY_VOLT__	1
#define __CHARGER_MECHANISM_SWITCH__	1
#define __DEFAULT_CARD__	1
#define __USB_MODEM__	1
#define __AGC_TOOL_CTRL_ENABLE__	1
#define __FAST_GPIO_ACCESS__	1
#define __ADC_SAR__	1
#define __SHARE_SAR_ADC_ANALOG_FOR_TOUCH_AND_BATT__	1
#define __RX_FREQ_COMP__	1
#define __REMOVE_MSR_IDLE_TIMER__	1
#define _MP_CHANGE_MARK_	1
#define __L1C_EGPRS__	1
#define __NO_OLD_L1C_MSG__	1
#define __NO_HACTIM_TASK__	1
#define __EXTENDED_SLEEP_MODE_PH3__	1
#define __L1_SPEED_MANAGER__	1
#define __DUMMY_PCH_DETECTION__	1
#define __REDUCED_PAGING__	1
#define __REDUCED_BCCH__	1
#define __1R7M_SUPPORT__	1
#define __OPTIMIZED_MON_CELL_LIST_USAGE__	1
#define __SPEED_UP_POWER_CAMPAIGN__	1
#define __QUAD_BAND_SUPPORT__	1
#define __MSTAR_DUAL_SIM__	1
#define __MULTI_DATALINK__	1
#define __RADIO_MULTIRAMP_IN_E2P__	1
#define __TGGE_RF__	1
#define __AUTO_STORE_TRACE_TO_SD__	1
#define __RTK_RELEASE__	1
#define __GKI_HEAP__	1
#define __GMM__	1
#define __MEM_GENERIC__	1
#define __MEM_SHORT_POLLING_CHECK__	1
#define __DEBUG__	1
#define __KERNEL_DEBUG__	1
#define __MEM_CRITICAL_TO_IMI__	1
#define __CHIP_TYPE_EFUSE__	1
#define __TRIVIAL_TRACES__	1
#define __TIME_SLICE_SCHEDULE__	1
#define __BOOT_UNCOMPRESS__	1
#define __SD_DOWNLOAD__	1
#define __CSR_ATI_VML__	1
#define __TEST_SIM_AUTOATTACH__	1
#define __NETWORK_COUNTER_MDL__	1
#define __FEATURE_POWER_CONSUMPTION_LOG__	1
#define __UI_STYLE_MMI_MAIN_MENU_GRID_AND_LIST__	1
#define __MMI_SOFTKEY_AS_CLEAR__	1
#define __CHINESE_S__	1
#define __GB2312_TO_UNICODE__	1
#define __DECODER_USE_GB2312__	1
#define __UNICODE_TO_PINYIN__	1
#define __LUNAR_CALENDAR_MMI__	1
#define __MSERVICES__	1
#define __GPRS_MMI__	1
#define __MMI_POWER_ON_TIME_INF__	1
#define __APP_E2P_MML__	1
#define __XMMI__	1
#define __HOPPER__	1
#define __SPEED_DIALER_MMI__	1
#define __DIAL_SHORTCUT_MMI__	1
#define __MMI_PICVIEWER_SLIDESHOW_ENABLE__	1
#define __MMI_PICVIEWER_SET_CONTACT_ENABLE__	1
#define __MMI_PICVIEWER_ZOOM_ENABLE__	1
#define __PICVIEWER_ZOOM_MOVING_SEAMLESS__	1
#define __EM_AUDIO_B3__	1
#define __APP_MMI_EM_AUDIO_APPTOSD__	1
#define __SIMULATOR_B3__	1
#define __NETWORK_SETTING_CUS__	1
#define __TARGET__	1
#define __FAKE_VENDOR__	1
#define __MSYNC_TOOL__	1
#define __COMPONENT_BASE_CONFIGURATION__	1
#define __COMPATIBLE_CHIP_SUPPORT__	1
#define __TINY_CMD_ADC_CALIBRATION__	1
#define __SLDLM_STACK_L3__	1
#define __MO_CALL_PREEMPT_GPRS__	1
#define __DUAL_SIM_MMI__	1
#define __MSTAR_DUAL_SIM_REDUCE_CODE__	1
#define __MMCFG_2__	1
#define __MM_MIDDLEWARE__	1
#define __AMR_REC__	1
#define ENABLE_MP3_DEC	1
#define ENABLE_AAC_DEC	1
#define ENABLE_AMRNB_DEC	1
#define ENABLE_WAV_DEC	1
#define ENABLE_AMRNB_ENC	1
#define __MDL_VDR__	1
#define __RTK_OS__	1
#define __OPT_ARP_ENGINE_V001__	1
#define __OPT_ARP_RUN_ON_TARGET__	1
#define __OPT_ARP_ENGINE_ENABLE__	1
#define ARP_SW_AGC_ENABLE	1
#define __OPT_APP_ENGINE_V011__	1
#define __OPT_APP_RUN_ON_TARGET__	1
#define __OPT_APP_ENGINE_ENABLE__	1
#define ENABLE_3D_SURROUND	1
#define ENABLE_USER_PEQ	1
#define ENABLE_SPEAKER_PEQ	1
#define ENABLE_VOL_CONTROL_EXP	1
#define ENABLE_DRC_LIMITER_V2	1
#define ENABLE_SC_FADE	1
#define TURNOFF_VIDEO_APP_DRCLIMITER	1
#define TURNOFF_VIDEO_APP_SPEAKERPEQ	1
#define TURNOFF_A2DP_APP_DRCLIMITER	1
#define TURNOFF_A2DP_APP_SPEAKERPEQ	1
#define __NONCACHED_BUFFER__	1
#define __TMT_TRACE_STORE_SD__	1
#define __CHECK_TRACE_LOST__	1
#define __SHARE_MEM_SYS__	1
#define __LCM_ROTATE_DIRECTION_CCW__	
#define __LCM_ROTATE_MMI__	1
#define __TOUCH_SCREEN_DRV__	1
#define __TOUCH_SCREEN_MMI__	1
#define __APP_MMI_BJX__	1
#define __MMI_CAMERA_NUMBER_KEY_ENABLE__	1
#define __MMI_CAMERA_RICH_SETTING_STYLE__	1
#define __ENABLE_DMA2D_HW__	1
#define __MMI_MPLAYER_EQ_ENABLE__	1
#define __MMI_MPLAYER_3DSURROUND_ENABLE__	1
#define __MMI_MPLAYER_LYRIC_ENABLE__	1
#define __IME_MMI_SOFTKEYBOARD__	1
#define __HANDWRITING_MMI__	1
#define __MMI_MENU_DEFAULT_ENABLE_SLIDE_BY_FINGER__	1
#define __SPACE_FULL_STORAGE_SELECTION_MMI__	1
#define __2D_UI_IDLE_SIMPLE__	1
#define __MMI_2DUI__	1
#define __WAP_MMI__	1
#define __WAP_MMI_CDWAP__	1
#define __MMS_MMI_CDMMS__	1
#define __INPUTCONTROLLER_CHINESE_SUPPORT__	1
#define __INPUTCONTROLLER_SMART_SUPPORT__	1
#define __FILEMGRAPP_PHONESTORAGE__	1
#define __VIEW_TRANSITION__	1
#define __RF_WITH_LEGACY__	1
#define __SMART_ALIGNMENT__	1
#define SLDLM_MMAUDIO	1
#define __APP_MMI_CALCULATOR__	1
#define __MMI_CONNECT_SETTING__	1
#define __SOCKETSRV_SUPPORT__	1
#define __NEW_BACK_TRACE__	1
#define NG_COMP_RVCT	1
#define NG_CODE_THUMB	1
#define __VER_UART__	1
#endif
