#ifndef __MMI_EMUAPP_ID_H__
#define __MMI_EMUAPP_ID_H__

typedef enum EmuWndId_e_
{
    EMU_WND_HELP = WND_ID_APP_BASE,
    EMU_WND_SETTINGS,
    EMU_WND_VOLUME,
    EMU_WND_GAME
#if defined(__EMU_VIRTUAL_KEYPAD_ENABLE__)
    ,EMU_WND_SELECT_KEYPAD
    ,EMU_WND_KEYPAD_SETTINGS
#endif // __EMU_VIRTUAL_KEYPAD_ENABLE__
} EmuWndId_e;

enum
{
    EMU_GAME_OSD = APP_WDG_START,
#if defined(__EMU_VIRTUAL_KEYPAD_ENABLE__)
    EMU_GAME_CTNR,
    EMU_GAME_IMG_SELECT,
    EMU_GAME_IMG_START,
    EMU_GAME_CTNR_ABXY,
    EMU_GAME_CTNR_A,
    EMU_GAME_CTNR_B,
    EMU_GAME_CTNR_X,
    EMU_GAME_CTNR_Y,
    EMU_GAME_CTNR_L,
    EMU_GAME_CTNR_R,
    EMU_GAME_IMG_A,
    EMU_GAME_IMG_B,
    EMU_GAME_IMG_X,
    EMU_GAME_IMG_Y,
    EMU_GAME_IMG_L,
    EMU_GAME_IMG_R,
    EMU_GAME_IMG_A_TXT_L,
    EMU_GAME_IMG_A_TXT_M,
    EMU_GAME_IMG_A_TXT_R,
    EMU_GAME_IMG_B_TXT_L,
    EMU_GAME_IMG_B_TXT_M,
    EMU_GAME_IMG_B_TXT_R,
    EMU_GAME_IMG_X_TXT_L,
    EMU_GAME_IMG_X_TXT_M,
    EMU_GAME_IMG_X_TXT_R,
    EMU_GAME_IMG_Y_TXT_L,
    EMU_GAME_IMG_Y_TXT_M,
    EMU_GAME_IMG_Y_TXT_R,
    EMU_GAME_IMG_L_TXT_L,
    EMU_GAME_IMG_L_TXT_M,
    EMU_GAME_IMG_L_TXT_R,
    EMU_GAME_IMG_R_TXT_L,
    EMU_GAME_IMG_R_TXT_M,
    EMU_GAME_IMG_R_TXT_R,
    EMU_GAME_CTNR_JOYSTICK,
    EMU_GAME_IMG_JOYSTICK_BG,
    EMU_GAME_IMG_JOYSTICK_STICK
#endif // __EMU_VIRTUAL_KEYPAD_ENABLE__
};

enum //EMUAPP_SETTINGS_VIEW_enum
{
    eEMU_SETTING_MENU = APP_WDG_START,
}; //EMUAPP_SETTINGS_VIEW_enum

enum //EMUAPP_SETTINGS_VOLUME_VIEW_enum
{
    eEMU_SETTINGS_VOLUME = APP_WDG_START,
}; //EMUAPP_SETTINGS_VOLUME_VIEW_enum

#if defined(__EMU_VIRTUAL_KEYPAD_ENABLE__)
enum
{
    EMU_SELECT_MENU = APP_WDG_START,
};

enum
{
    EMU_KEYPAD_CTNR = APP_WDG_START,
    EMU_KEYPAD_IMG_BG,
    EMU_KEYPAD_TXT_HINT,
    EMU_KEYPAD_BTN_DEFAULT,
    EMU_KEYPAD_FO_DEFAULT,
    EMU_KEYPAD_BTN_OK,
    EMU_KEYPAD_BTN_CANCEL,
    EMU_KEYPAD_IMG_ARROW_BG,
    EMU_KEYPAD_CTNR_JOYSTICK,
    EMU_KEYPAD_IMG_JOYSTICK_BG,
    EMU_KEYPAD_IMG_JOYSTICK,
    EMU_KEYPAD_CTNR_ABXY,
    EMU_KEYPAD_CTNR_A,
    EMU_KEYPAD_CTNR_B,
    EMU_KEYPAD_CTNR_X,
    EMU_KEYPAD_CTNR_Y,
    EMU_KEYPAD_CTNR_L,
    EMU_KEYPAD_CTNR_R,
    EMU_KEYPAD_BTN_A,
    EMU_KEYPAD_BTN_B,
    EMU_KEYPAD_BTN_X,
    EMU_KEYPAD_BTN_Y,
    EMU_KEYPAD_BTN_L,
    EMU_KEYPAD_BTN_R,
    EMU_KEYPAD_IMG_A_TXT_L,
    EMU_KEYPAD_IMG_A_TXT_M,
    EMU_KEYPAD_IMG_A_TXT_R,
    EMU_KEYPAD_IMG_B_TXT_L,
    EMU_KEYPAD_IMG_B_TXT_M,
    EMU_KEYPAD_IMG_B_TXT_R,
    EMU_KEYPAD_IMG_X_TXT_L,
    EMU_KEYPAD_IMG_X_TXT_M,
    EMU_KEYPAD_IMG_X_TXT_R,
    EMU_KEYPAD_IMG_Y_TXT_L,
    EMU_KEYPAD_IMG_Y_TXT_M,
    EMU_KEYPAD_IMG_Y_TXT_R,
    EMU_KEYPAD_IMG_L_TXT_L,
    EMU_KEYPAD_IMG_L_TXT_M,
    EMU_KEYPAD_IMG_L_TXT_R,
    EMU_KEYPAD_IMG_R_TXT_L,
    EMU_KEYPAD_IMG_R_TXT_M,
    EMU_KEYPAD_IMG_R_TXT_R,
    EMU_KEYPAD_BTN_PRE_KEYPAD_STYLE,
    EMU_KEYPAD_BTN_NEXT_KEYPAD_STYLE,
    EMU_KEYPAD_CTNR_KEYPAD_STYLE_INDICATOR,
    EMU_KEYPAD_IMG_KEYPAD_STYLE_INDICATOR1,
    EMU_KEYPAD_IMG_KEYPAD_STYLE_INDICATOR2,
    EMU_KEYPAD_IMG_KEYPAD_STYLE_INDICATOR3,
    EMU_KEYPAD_IMG_KEYPAD_STYLE_INDICATOR4,
    EMU_KEYPAD_CTNR_CONTROLLER,
    EMU_KEYPAD_BTN_CONTROLLER_OK,
    EMU_KEYPAD_BTN_CONTROLLER_CANCEL,
    EMU_KEYPAD_IMG_CONTROLLER_BG,
    EMU_KEYPAD_BTN_EMU8BIT_A,
    EMU_KEYPAD_BTN_EMU8BIT_B,
    EMU_KEYPAD_BTN_SEMU16BIT_A,
    EMU_KEYPAD_BTN_SEMU16BIT_B,
    EMU_KEYPAD_BTN_SEMU16BIT_X,
    EMU_KEYPAD_BTN_SEMU16BIT_Y,
    EMU_KEYPAD_BTN_SEMU16BIT_L,
    EMU_KEYPAD_BTN_SEMU16BIT_R
};
#endif // __EMU_VIRTUAL_KEYPAD_ENABLE__

#endif //__MMI_EMUAPP_ID_H__

