ApBegin(RS,CLSID_G3DMAINMENUAPP)
    WndBegin(G3D_MAIN_MENU_WND_MAIN)
        WndSetSoftkeyVisibleRC(FALSE)
        WndSetStatusBarVisibleRC(FALSE)

        WdgBegin(CLSID_BUTTONWIDGET,PrevButton)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FIRST_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FIRST_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAINMENU_3D_IMG_GRID_PREV_UNPRESSED,MAINMENU_3D_IMG_GRID_PREV_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PrevButton)

        WdgBegin(CLSID_BUTTONWIDGET,HomeButton)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_SECOND_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_SECOND_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAINMENU_3D_IMG_GRID_HOME_UNPRESSED,MAINMENU_3D_IMG_GRID_HOME_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,HomeButton)

        WdgBegin(CLSID_BUTTONWIDGET,TranButton)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_THIRD_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_THIRD_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAINMENU_3D_IMG_GRID_TRANSITION_UNPRESSED,MAINMENU_3D_IMG_GRID_TRANSITION_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,TranButton)

        WdgBegin(CLSID_BUTTONWIDGET,NextButton)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FOURTH_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FOURTH_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAINMENU_3D_IMG_GRID_NEXT_UNPRESSED,MAINMENU_3D_IMG_GRID_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,NextButton)

    WndEnd(G3D_MAIN_MENU_WND_MAIN)
ApEnd(RS,CLSID_G3DMAINMENUAPP)

