#ifndef __MMI_RFIDDEMOAPP_ID_H__
#define __MMI_RFIDDEMOAPP_ID_H__

typedef enum
{
	RFIDDEMO_WND_MAINLIST = WND_ID_APP_BASE,
	RFIDDEMO_WND_ISO15693,
	RFIDDEMO_WND_GET_FW_VER,
	RFIDDEMO_WND_UPDATE_FIRMWARE,

#ifdef __SUPPORT_SIM_SWITCH__
	RFIDDEMO_WND_SIM_SWITCH,
#endif //__SUPPORT_SIM_SWITCH__

#ifdef	__USE_MSR3110__
	RFIDDEMO_WND_ISO14443A,
	RFIDDEMO_WND_ISO14443B,
#endif	//__USE_MSR3110__

#if defined(__USE_MSR3330__) || defined(__USE_MSR3320__)
	RFIDDEMO_WND_C1G2,
#endif	//defined(__USE_MSR3330__) || defined(__USE_MSR3320__)

#ifdef __BARCODE__
	RFIDDEMO_WND_BARCODE,
#endif	//__BARCODE__

#ifdef __SUPPORT_JSR257__
	RFIDDEMO_WND_JSR257LIST,
	RFIDDEMO_WND_NDEF_LISTENER,
	RFIDDEMO_WND_NDEF_READ,
	RFIDDEMO_WND_NDEF_WRITE,
	RFIDDEMO_WND_TARGET_LISTENER,
	RFIDDEMO_WND_ISO14443AMF,

#endif	//__SUPPORT_JSR257__

#ifdef __GPS_MMI__
	RFIDDEMO_WND_GPS,
#endif	//__GPS_MMI__

}RfidDemoWndId_e;

typedef enum
{
	RFIDDEMO_WND_ISO15693_TITLE_WDG = APP_WDG_START,
	RFIDDEMO_WND_ISO15693_TEXT1_WDG,
	RFIDDEMO_WND_ISO15693_TEXT2_WDG,
	RFIDDEMO_WND_ISO15693_TEXT3_WDG,
	RFIDDEMO_WND_ISO15693_TEXT4_WDG,
	RFIDDEMO_WND_ISO15693_TEXT5_WDG,
	RFIDDEMO_WND_ISO15693_TEXT6_WDG,
	RFIDDEMO_WND_UPDATE_FIRMWARE_TITLE_WDG,
	RFIDDEMO_WND_UPDATE_FIRMWARE_TEXT_WDG,
	RFIDDEMO_WND_GET_FW_VER_TITLE_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT1_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT2_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT3_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT4_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT5_WDG,
	RFIDDEMO_WND_GET_FW_VER_TEXT6_WDG,

#ifdef __SUPPORT_SIM_SWITCH__
	RFIDDEMO_WND_SIM_SWITCH_TITLE_WDG,
	RFIDDEMO_WND_SIM_SWITCH_TEXT1_WDG,
	RFIDDEMO_WND_SIM_SWITCH_TEXT2_WDG,
	RFIDDEMO_WND_SIM_SWITCH_TEXT3_WDG,
#endif //__SUPPORT_SIM_SWITCH__

#ifdef	__USE_MSR3110__
    RFIDDEMO_WND_ISO14443A_TITLE_WDG,
	RFIDDEMO_WND_ISO14443A_TEXT1_WDG,
	RFIDDEMO_WND_ISO14443A_TEXT2_WDG,
    RFIDDEMO_WND_ISO14443A_TEXT3_WDG,
	RFIDDEMO_WND_ISO14443A_TEXT4_WDG,
	RFIDDEMO_WND_ISO14443A_TEXT5_WDG,
	RFIDDEMO_WND_ISO14443B_TITLE_WDG,
	RFIDDEMO_WND_ISO14443B_TEXT1_WDG,
	RFIDDEMO_WND_ISO14443B_TEXT2_WDG,
	RFIDDEMO_WND_ISO14443B_TEXT3_WDG,
	RFIDDEMO_WND_ISO14443B_TEXT4_WDG,
	RFIDDEMO_WND_ISO14443B_TEXT5_WDG,
#endif	//__USE_MSR3110__

#if defined(__USE_MSR3330__) || defined(__USE_MSR3320__)
	RFIDDEMO_WND_C1G2_TITLE_WDG,
	RFIDDEMO_WND_C1G2_TEXT1_WDG,
	RFIDDEMO_WND_C1G2_TEXT2_WDG,
	RFIDDEMO_WND_C1G2_TEXT3_WDG,
	RFIDDEMO_WND_C1G2_TEXT4_WDG,
	RFIDDEMO_WND_C1G2_TEXT5_WDG,
	RFIDDEMO_WND_C1G2_TEXT6_WDG,
#endif	//defined(__USE_MSR3330__) || defined(__USE_MSR3320__)

#ifdef __BARCODE__
	RFIDDEMO_WND_BARCODE_TITLE_WDG,
	RFIDDEMO_WND_BARCODE_LABEL_WDG,
	RFIDDEMO_WND_BARCODE_TEXT_WDG,
#endif	//__BARCODE__

#ifdef __SUPPORT_JSR257__
	RFIDDEMO_WND_NDEF_LISTENER_TITLE_WDG,
	RFIDDEMO_WND_NDEF_LISTENER_LABEL_WDG,
	RFIDDEMO_WND_NDEF_LISTENER_TEXT_WDG,

	RFIDDEMO_WND_NDEF_READ_TITLE_WDG,
	RFIDDEMO_WND_NDEF_READ_LABEL_WDG,
	RFIDDEMO_WND_NDEF_READ_TEXT_WDG,

	RFIDDEMO_WND_NDEF_WRITE_TITLE_WDG,
	RFIDDEMO_WND_NDEF_WRITE_LABEL_WDG,
	RFIDDEMO_WND_NDEF_WRITE_TEXT_WDG,

	RFIDDEMO_WND_TARGET_LISTENER_TITLE_WDG,
	RFIDDEMO_WND_TARGET_LISTENER_LABEL_WDG,
	RFIDDEMO_WND_TARGET_LISTENER_TEXT_WDG,

	RFIDDEMO_WND_ISO14443AMF_TITLE_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT1_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT2_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT3_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT4_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT5_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT6_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT7_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT8_WDG,
	RFIDDEMO_WND_ISO14443AMF_TEXT9_WDG,
#endif	//__SUPPORT_JSR257__

#ifdef __GPS_MMI__
	RFIDDEMO_WND_GPS_TITLE_WDG,
	RFIDDEMO_WND_GPS_LABEL_WDG,
	RFIDDEMO_WND_GPS_TEXT_WDG,
#endif	//__GPS_MMI__

} RfidDemoWdgId_e;

#endif /* __MMI_RFIDDEMOAPP_ID_H__ */


