ApBegin(RS,CLSID_CBSAPP)
	WndBegin(CBSETTINGS_WND_SimDuoSelectionView)    
		WdgBegin(CLSID_VTMSIMSELECTION,DuoSimSelect)
			VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_CELL_BROADCAST_SETTINGS})
		WdgEnd(CLSID_VTMSIMSELECTION,DuoSimSelect)    
	WndEnd(CBSETTINGS_WND_SimDuoSelectionView)

 	WndBegin(CBSETTINGS_WND_MainMenu)
        WdgBegin(CLSID_VTMMENU,MainMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CELL_BROADCAST,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,MainMenu)
	WndEnd(CBSETTINGS_WND_MainMenu)

 	WndBegin(CBSETTINGS_WND_TopicList)
        WdgBegin(CLSID_VTMMENU,TopicList)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_TOPIC_LIST,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,TopicList)
	WndEnd(CBSETTINGS_WND_TopicList)

	WndBegin(CBSETTINGS_WND_OptionMenu) 
		WdgBegin(CLSID_VTMOPTIONMENU,OptionMenuWdgList) 
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,0})
		WdgEnd(CLSID_VTMOPTIONMENU,OptionMenuWdgList) 
	WndEnd(CBSETTINGS_WND_OptionMenu) 

 	WndBegin(CBSETTINGS_WND_TopicEditorWithChannelMenu)
        WdgBegin(CLSID_VTMMENU,TopicEditorWithChannelMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_TOPIC,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,TopicEditorWithChannelMenu)
	WndEnd(CBSETTINGS_WND_TopicEditorWithChannelMenu)

 	WndBegin(CBSETTINGS_WND_TopicEditorWithRngChannelMenu)
        WdgBegin(CLSID_VTMMENU,TopicEditorWithRngChannelMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_TOPIC,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,TopicEditorWithRngChannelMenu)
	WndEnd(CBSETTINGS_WND_TopicEditorWithRngChannelMenu)

    WndBegin(CBSETTINGS_WND_EditorInput)
        WdgBegin(CLSID_VTMINPUT,EditorInput)
		VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_DESCRIPTION,0,FALSE})            
        WdgEnd(CLSID_VTMINPUT,EditorInput)
    WndEnd(CBSETTINGS_WND_EditorInput)

	WndBegin(CBSETTINGS_WND_FullEditorOptionMenu) 
		WdgBegin(CLSID_VTMOPTIONMENU,FullEditoryOptionMenu) 
			VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,0})
		WdgEnd(CLSID_VTMOPTIONMENU,FullEditoryOptionMenu) 
	WndEnd(CBSETTINGS_WND_FullEditorOptionMenu) 
    
	WndBegin(CBSETTINGS_WND_PopupInput)
		WdgBegin(CLSID_VTMPOPUPINPUT,PopupInput)
			VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_NULL_ID,MAE_INPUTMODE_NUMERIC})
		WdgEnd(CLSID_VTMPOPUPINPUT,PopupInput)        
	WndEnd(CBSETTINGS_WND_PopupInput)

ApEnd(RS,CLSID_CBSAPP)
