#ifndef __MMI_URL_SRV_COMMON_SCHEME_TBL__
#define __MMI_URL_SRV_COMMON_SCHEME_TBL__

#include "mmi_clstbl.h"

#define _SCHEME_ L"S"
#define _HOST_   L"A" /// To be removed

#define DEFAULT_LAUNCH_TXT     L"Default"
#define MAE_CLOSE_EMBEDDED_APP L"MaeCloseEmbeddedApp"
#define MAE_DEFAULT_LAUNCH     L"MaeDefault"

#define MAE_CLSID_2_SCHEMEID(CLSID) ((UrlSrvUrlScheme_e)CLSID)

typedef enum
{
	/// Start This region is reserved for MAE's App
	URL_SRV_URL_SCHEME_MAE_APP_START = MAE_APPLET_CLASS_BASE,
	/// The url scheme in MAE's App is the same as its ClsId
	URL_SRV_URL_SCHEME_MAE_APP_END = CLSID_END_OF_APPLET,
	URL_SRV_URL_SCHEME_MAE_TASK,
	URL_SRV_URL_SCHEME_UT,
	/// End
	URL_SRV_URL_SCHEME_INVALID,
}UrlSrvUrlScheme_e;

/// Define your App's action
typedef enum
{
	URL_SRV_URL_HOST_LIST_ALL = 0,
	URL_SRV_URL_HOST_VIEW_ALARM,
	URL_SRV_URL_HOST_FIND_CONTENT_ID,
	URL_SRV_URL_HOST_SEND_FILE,
	URL_SRV_URL_HOST_SEND_MULTIPLE_FILE,
	URL_SRV_URL_HOST_SEND_FILE_BY_HANDLEID,
	URL_SRV_URL_HOST_VIEW_EVENT,
	URL_SRV_URL_HOST_IMPORT_EVENT,
	URL_SRV_URL_HOST_EXPORT_EVENT,
	URL_SRV_URL_HOST_SHOW_COST_SETTING,
	URL_SRV_URL_HOST_SHOW_CALLLOG_LIST,
	URL_SRV_URL_HOST_MAKE_CALL,
	URL_SRV_URL_HOST_WAITING_CALL,
	URL_SRV_URL_HOST_INCOMING_CALL,
	URL_SRV_URL_HOST_END_CALL,
	URL_SRV_URL_HOST_GET_PREDEFINEDFILE,
	URL_SRV_URL_HOST_GET_FILES,
	URL_SRV_URL_HOST_BROWSING,
	URL_SRV_URL_HOST_LIST_DIR,
	URL_SRV_URL_HOST_SHOW_MEMORY_DETAIL,
	URL_SRV_URL_HOST_SET_TIME_ZONE,
	URL_SRV_URL_HOST_VIEW_TIME_ZONE,
	URL_SRV_URL_HOST_OPEN_URL,
	URL_SRV_URL_HOST_SAVE_BOOKMARK,
	URL_SRV_URL_HOST_PLAY,
	URL_SRV_URL_HOST_SIMPLE_PLAY,
    URL_SRV_URL_HOST_SIMPLE_PLAY_BUFFER,
	URL_SRV_URL_HOST_SIMPLE_PLAY_AND_SELECT,    
	URL_SRV_URL_HOST_PLAY_AFTER_SAVING,
	URL_SRV_URL_HOST_PLAY_BUFFER,
	URL_SRV_URL_HOST_SLIDE_SHOW,
	URL_SRV_URL_HOST_PLAY_AND_SELECT,
	URL_SRV_URL_HOST_CROP_PIC,
	URL_SRV_URL_HOST_VOICEMEMO,
	URL_SRV_URL_HOST_QUICK_DAIL,
	URL_SRV_URL_HOST_CONTENT,
	URL_SRV_URL_HOST_SAVE_CONTACT,
	URL_SRV_URL_HOST_SAVE_CONTACT_BY_VCARD,
	URL_SRV_URL_HOST_GET_CONTACT,
	URL_SRV_URL_HOST_GET_CONTACT_NUMBER_OR_EMAIL,
	URL_SRV_URL_HOST_GET_CONTACT_AS_VCARD,
	URL_SRV_URL_HOST_IMPORT_CONTACT_BY_URL,
	URL_SRV_URL_HOST_VIEW_CONTACT,
	URL_SRV_URL_HOST_LIST_CERTAIN_SIM,
	URL_SRV_URL_HOST_LIST_PAGESETTING,
	URL_SRV_URL_HOST_LIST_SENDOPTION,
	URL_SRV_URL_HOST_PICKMODE,
	URL_SRV_URL_HOST_CREATE_NEW_MSG_BY_TEMPLATE,
	URL_SRV_URL_HOST_EDIT_DRAFT_SMS,
	URL_SRV_URL_HOST_CREATE_NEW_SMS,
	URL_SRV_URL_HOST_REPLY_SMS,
	URL_SRV_URL_HOST_FORWARD_SMS,
	URL_SRV_URL_HOST_EDIT_DRAFT_MMS,
	URL_SRV_URL_HOST_CREATE_NEW_MMS,
	URL_SRV_URL_HOST_REPLY_MMS,
	URL_SRV_URL_HOST_FORWARD_MMS,
	URL_SRV_URL_HOST_VIEWMSG,
	URL_SRV_URL_HOST_LISTMSG,
	URL_SRV_URL_HOST_VOICEMAIL,
	URL_SRV_URL_HOST_VOICEMAIL_SELECT_SIM,
	URL_SRV_URL_HOST_VOICEMAIL_UNSELECT_SIM,
	URL_SRV_URL_HOST_SHORTCUT_ENTER_NONNUMBER_KEY,
	URL_SRV_URL_HOST_SHORTCUT_ENTER_NUMBER_KEY,
	URL_SRV_URL_HOST_SECURITY_LAUNCH_MENU,
	URL_SRV_URL_HOST_SECURITY_CHECK_CODE,
	URL_SRV_URL_HOST_SECURITY_CHECK_FROM_SIM,
	URL_SRV_URL_HOST_SECURITY_CHECK_APLOCK_VERIFICATION,
	URL_SRV_URL_HOST_E_BOOK_BROWSE,
	URL_SRV_URL_HOST_SENDVIA_SEND_BY_CONTENT,
    URL_SRV_URL_HOST_SENDVIA_SEND_BY_URL,
    URL_SRV_URL_HOST_SENDVIA_SEND_BY_ID,
	URL_SRV_URL_HOST_USB_UNSPECIFIED,
	URL_SRV_URL_HOST_USB_OPEN_REQUEST,
	URL_SRV_URL_HOST_USSD_REQ,
	URL_SRV_URL_HOST_JAVAAMS_INSTALL,
	URL_SRV_URL_HOST_WLAN_BYSETTING,
	URL_SRV_URL_HOST_WLAN_BYLOWSIGNAL,
	URL_SRV_URL_HOST_LAUNCH,
	/// Start Reserved For System
	URL_SRV_URL_HOST_DEFAULT_LAUNCH, /// This is used by system, never use it.
	/// End   Reserved For System
	URL_SRV_URL_HOST_UT,
	URL_SRV_URL_HOST_CLOSE_CUR_EMBEDDED_APP,
	URL_SRV_URL_HOST_NUM,            /// Invalid Item, only use to check error.
	URL_SRV_URL_HOST_INVALID,        /// Invalid Item, only use to check error.
}UrlSrvUrlHost_e;


/// Use to define default launcher
/// Make all the default launcher run in its task
/// URL_SRV_TASK_INFO(AP_SCHEME_START, AP_SCHEME_END, AP_TASK_ID, AP_DEFAULT_LAUNCHER)
// #define URL_SRV_INIT_DEFAULT_LAUNCHER_TBL	\
//     URL_SRV_TASK_AP_LAUNCHER_INFO(URL_SRV_URL_SCHEME_MAE_TASK, CUS_MBX_MMI, UrlSrvMAEDefaultLauncherHandler, NULL)
///	URL_SRV_TASK_AP_LAUNCHER_INFO(URL_SRV_URL_SCHEME_MAE_APP_START, URL_SRV_URL_SCHEME_MAE_APP_END, CUS_MBX_MMI, UrlSrvMAEDefaultLauncherHandler, NULL)


#endif/* __MMI_URL_SRV_COMMON_SCHEME_TBL__ */
