/**
 * @file    mmi_cfgsrv_citem_file_itemid.h
 *
 * @brief   This file is auto generate by XRG tool. Do not modify file directly
 *
 * @version $Id: mmi_cfgsrv_citem_file_itemid.h 29867 2009-05-04 08:08:52Z mike.yeh $
 *
 * @time
 */

#ifndef __MMI_CFGSRV_CITEM_FILE_ITEMID_H__
#define __MMI_CFGSRV_CITEM_FILE_ITEMID_H__

#include "mmi_cfgsrv_common_table.h"

enum
{
    CFGIT_CACHE_ITEMS_FILE_START = CACHE_ITEMS_FILE_START
   ,CFGIT_SETTING_DISPLAY_POWER_SAVING_ITEM
   ,CFGIT_SECURITY_NETWORK_BLOCK_STATUS
#if defined(__DUAL_SIM_MMI__)
   ,CFGIT_SECURITY_NETWORK_BLOCK_STATUS2
#endif
   ,CFGIT_SECURITY_NETWORK_LOCK_CODE
   ,CFGIT_SECURITY_NETWORK_SUBSET_LOCK_CODE
   ,CFGIT_SECURITY_SP_LOCK_CODE
   ,CFGIT_SECURITY_CORPORATE_LOCK_CODE
   ,CFGIT_SECURITY_SIMUSIM_LOCK_CODE
   ,CFGIT_SECURITY_NETWORK_LOCK_FAIL_COUNT
#if defined(__DUAL_SIM_MMI__)
   ,CFGIT_SECURITY_NETWORK_LOCK_FAIL_COUNT2
#endif
   ,CFGIT_SECURITY_MAX_NETWORK_LOCK_FAIL_COUNT
   ,CFGIT_SECURITY_NETWORK_LOCK_INFO
#if defined(__DUAL_SIM_MMI__)
   ,CFGIT_SECURITY_NETWORK_LOCK_INFO2
#endif
   ,CFGIT_SECURITY_NETWORK_LOCK_TABLE
   ,CFGIT_ONOFF_CHECK_LOCK_POINT_MASTER
   ,CFGIT_ONOFF_CHECK_LOCK_POINT_SLAVE
   ,CFGIT_ONOFF_UPDATE_SIM_LANG
   ,CFGIT_ONOFF_NETWORK_ANIM_ENABLE
   ,CFGIT_ONOFF_AUTO_ONOFF_DIALOG_ENABLE
   ,CFGIT_ONOFF_NO_SIM_CHECK_PHONE_LOCK_POINT
   ,CFGIT_ONOFF_ANTISTEAL_LOCK_POINT
   ,CFGIT_COMMON_PHONE_ECC_LIST
   ,CFGIT_SECURITY_KEYGUARD_TYPE
   ,CFGIT_SECURITY_AUTO_KEYPAD_LOCK
   ,CFGIT_CACHE_ITEMS_FILE_END
};

#endif /* __MMI_CFGSRV_CITEM_FILE_ITEMID_H__ */
