/**
* @file mmi_clipboardsrv.h
*
* Service without using State Machine - CLIPBOARDSRV
* Generated by XFSM v1.0, CodeVer=v0.24
*
* Class Id: CLSID_CLIPBOARDSRV
* Interface Id: IID_CLIPBOARDSRV
*
* @version $Id: mmi_clipboardsrv.h 33461 2009-06-16 08:06:40Z mark.yang $
*/
#ifndef __MMI_CLIPBOARDSRV_H__
#define __MMI_CLIPBOARDSRV_H__

#include "mmi_mae_common_def.h"
#include "mmi_mae_applet.h"
#include "mmi_mae_class.h"

/**
 * External Events
 */


/**
 * ICLIPBOARDSRV Interfaces
 */
#define INHERIT_ICLIPBOARDSRV(IName) \
    INHERIT_IHandler(IName); \
    MAE_Ret     (*ClearContent)     ( IName * );  \
    MAE_Ret     (*InsertContent)        ( IName * , MAE_WChar *pContentStr, u32 nContentLength);  \
    void        (*GetContent)       ( IName * , MAE_WChar **pContentStr, u32 *nContentLength)

DEFINE_INTERFACE(ICLIPBOARDSRV);


#define ICLIPBOARDSRV_QueryInterface(pICntlr, id, pp, po)           GET_FUNCTBL((pICntlr), ICLIPBOARDSRV)->QueryInterface(pICntlr, id, pp, po)
#define ICLIPBOARDSRV_HandleEvent(pICntlr, e, p1, p2)               GET_FUNCTBL((pICntlr), ICLIPBOARDSRV)->HandleEvent(pICntlr, e, p1, p2)
/**
 Description: Clear content in clipboard.
Return: MAE_Ret
 */
#define ICLIPBOARDSRV_ClearContent(pICntlr) GET_FUNCTBL((pICntlr), ICLIPBOARDSRV)->ClearContent( pICntlr)
/**
 Description: Insert content string in clipboard.
Param: pContentStr : Content string
Param:  nContentLength : Length of content string
Return: MAE_Ret
 */
#define ICLIPBOARDSRV_InsertContent(pICntlr, p1, p2)    GET_FUNCTBL((pICntlr), ICLIPBOARDSRV)->InsertContent( pICntlr, p1, p2)
/**
 Description: Get content string pointer from clipboard.
Param: pContentStr : Content string
Param:  nContentLength : Length of content string
Return: MAE_Ret
 */
#define ICLIPBOARDSRV_GetContent(pICntlr, p1, p2)   GET_FUNCTBL((pICntlr), ICLIPBOARDSRV)->GetContent( pICntlr, p1, p2)



/**
 * Functions
 */

void CLIPBOARDSRV_Init(void);

__SLDPM_FREE__ MAE_Ret CLIPBOARDSRV_New(MAE_ClsId id, void **ppObj);

#endif /* __MMI_CLIPBOARDSRV_H__ */
