#ifndef __MMI_IDLEPREVIEWAPP_ID_H__
#define __MMI_IDLEPREVIEWAPP_ID_H__

enum
{
    IDLEPREVIEWAPP_WND_MAIN = WND_ID_APP_BASE,    
};

enum
{
	IDLEPREVIEW_BGWIDGET=APP_WDG_START, 
	IDLEPREVIEW_MULTIIDLEPAGEWDG,
};

#endif //__MMI_IDLEPREVIEWAPP_ID_H__

