ApBegin(RS,CLSID_SHORTCUTSAPP)
    WndBegin(SHORTCUTS_WND_SHOWLIST)
        WdgBegin(CLSID_VTMMENU,vtmMenu)
            VtmCreateMenuRC({IMG_NULL_ID,	TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,vtmMenu)
    WndEnd(SHORTCUTS_WND_SHOWLIST)


#ifdef __3D_UI_SHORTCUTAPP__
	WndBegin(SHORTCUTS_WND_ICONLIST)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)
        WndSetSoftkeyTransparencyRC(VIEW_TRANSPTYPE_TRANSP)
        WndSetAllSoftkeyRC({SK_SET, SK_OK, SK_CANCEL})

        WdgBegin(CLSID_IMAGEWIDGET,IconListBgImgWdg)
            WdgImageCreateForWndRC({{SHORTCUTSAPP_LAYOUT_ICONLIST_BG_X,SHORTCUTSAPP_LAYOUT_ICONLIST_BG_Y},{SHORTCUTSAPP_LAYOUT_ICONLIST_BG_W,SHORTCUTSAPP_LAYOUT_ICONLIST_BG_H},IMAGE_STYLE_COMMON,{FALSE,SHORTCUTS_3D_POPUP_MENU_BG}})
            WdgImageSetDataByIDRC(SHORTCUTS_3D_POPUP_MENU_BG)
        WdgEnd(CLSID_IMAGEWIDGET,IconListBgImgWdg)
        
        WdgBegin(CLSID_GRID_MENUWIDGET,IconListGridMenuWdg)
            WdgMenuCreateForWndRC({{SHORTCUTSAPP_LAYOUT_ICONLIST_X,SHORTCUTSAPP_LAYOUT_ICONLIST_Y},{SHORTCUTSAPP_LAYOUT_ICONLIST_W,SHORTCUTSAPP_LAYOUT_ICONLIST_H},WDG_MENU_TYPE_GRID})
            WdgMenuSetToGridStyleRC({SHORTCUTSAPP_LAYOUT_ICON_H_NUM, SHORTCUTSAPP_LAYOUT_ICON_V_NUM, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
            WdgMenuSetItemWidthRC((u16)SHORTCUTSAPP_LAYOUT_ICON_W)
            WdgMenuSetItemHeightRC((u16)SHORTCUTSAPP_LAYOUT_ICON_H)
            WdgMenuSetFixedNumRC((u16)3)          
            WdgMenuSetRowGapRC((u16)SHORTCUTSAPP_LAYOUT_ICON_ROW_GAP)
            WdgMenuSetColGapRC((u16)SHORTCUTSAPP_LAYOUT_ICON_COL_GAP)
            WdgCommonSetBorderDataRC({0,0,0,0,COLOR_WHITE})
        WdgEnd(CLSID_GRID_MENUWIDGET,IconListGridMenuWdg)       

		WdgBegin(CLSID_BUTTONWIDGET,LskBtn)
            WdgButtonCreateForWndRC({ {SHORTCUTSAPP_LAYOUT_BUTTON_LSK_X,SHORTCUTSAPP_LAYOUT_BUTTON_LSK_Y},{SHORTCUTSAPP_LAYOUT_BUTTON_LSK_W,SHORTCUTSAPP_LAYOUT_BUTTON_LSK_H}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,SHORTCUTS_3D_SETTING_UNPRESSED,SHORTCUTS_3D_SETTING_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,LskBtn)

		WdgBegin(CLSID_BUTTONWIDGET,RskBtn)
            WdgButtonCreateForWndRC({ {SHORTCUTSAPP_LAYOUT_BUTTON_RSK_X,SHORTCUTSAPP_LAYOUT_BUTTON_RSK_Y},{SHORTCUTSAPP_LAYOUT_BUTTON_RSK_W,SHORTCUTSAPP_LAYOUT_BUTTON_RSK_H}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,SHORTCUTS_3D_BACK_UNPRESSED,SHORTCUTS_3D_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,RskBtn)

		WdgBegin(CLSID_TEXTWIDGET,ItemTextWdg)
            WdgTextCreateForWndRC({{SHORTCUTSAPP_LAYOUT_ICONLIST_TITLE_X,SHORTCUTSAPP_LAYOUT_ICONLIST_TITLE_Y},{SHORTCUTSAPP_LAYOUT_ICONLIST_TITLE_W,SHORTCUTSAPP_LAYOUT_ICONLIST_TITLE_H},TEXT_STYLE_COMMON})            
        WdgEnd(CLSID_TEXTWIDGET,ItemTextWdg)
        
    WndEnd(SHORTCUTS_WND_ICONLIST)
#endif

    WndBegin(SHORTCUTS_WND_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,vtmOption)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,0})
        WdgEnd(CLSID_VTMOPTIONMENU,vtmOption)
    WndEnd(SHORTCUTS_WND_OPTION)

    WndBegin(SHORTCUTS_WND_KEYASSIGNMENT_FUNCTIONSMENU)
        WndSetStatusBarVisibleRC(VIEWSB_INVISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)

        WdgBegin(CLSID_VTMOPTIONMENU,vtmPopUp)
            VtmCreatePopUpSelectRC({NULL,	WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMOPTIONMENU,vtmPopUp)
    WndEnd(SHORTCUTS_WND_KEYASSIGNMENT_FUNCTIONSMENU)
ApEnd(RS,CLSID_SHORTCUTSAPP)

