#ifndef __MMI_EMAILAPP_ID_H__
#define __MMI_EMAILAPP_ID_H__

typedef enum
{
    WID_NEW_ACCOUNT = 0,
    WID_ACCOUNT_INCOMING,
    WID_ACCOUNT_OUTGOING,
}EmailNewAccountWID_e;

typedef enum
{
    WID_USER_SETTING = 0,
    WID_RETRIEVAL_SETTING,
    WID_SIM_SETTING,
}EmailSettingWID_e;

typedef enum
{
    MNU_EMAIL_OPEN_ACCOUNT = 0,
    MNU_EMAIL_NEW_ACCOUNT,
    MNU_EMAIL_EDIT_ACCOUNT,
    MNU_EMAIL_DELETE_ACCOUNT,
    MNU_EMAIL_SET_DEFEAULT_ACCOUNT,
    MNU_EMAIL_ACCOUNT_SETTING
}EmailAccoutListOptionMenuId_e;

typedef enum
{
  //  MNU_EMAIL_USERNAME = 0,
    MNU_EMAIL_ACCOUNTID = 0,
    MNU_EMAIL_PASSWORD,
    MNU_EMAIL_INCOMING_SERVER,
    MNU_EMAIL_INCOMING_TYPE,
    MNU_EMAIL_INCOMING_SECURITY,
    MNU_EMAIL_INCOMING_PORT,
    MNU_EMAIL_INCOMING_APOP,
    MNU_EMAIL_OUTGOING_SERVER,
    MNU_EMAIL_OUTGOING_TYPE,
    MNU_EMAIL_OUTGOING_SECURITY,
    MNU_EMAIL_OUTGOING_PORT,
    MNU_EMAIL_MYNAME,
    MNU_EMAIL_SIGNATURE,
    MNU_EMAIL_RETRIEVE,
    MNU_EMAIL_RETRIEVALAMOUNT,
#ifdef EMAIL_AUTORETRIEVE_ON
    MNU_EMAIL_AUTORETRIEVAL,
#endif
    MNU_EMAIL_SIM,
    MNU_EMAIL_EDIT_SUBJECT,
    MNU_EMAIL_EDIT_CONTENT
}EmailEditMenuId_e;

typedef enum
{
    EMAIL_EDITOR_WND_OPTION_MNU_EDIT = 0,
    EMAIL_EDITOR_WND_OPTION_MNU_SEND,
    EMAIL_EDITOR_WND_OPTION_MNU_ADD_RECIPIENT,
    EMAIL_EDITOR_WND_OPTION_MNU_ATTACH,
    EMAIL_EDITOR_WND_OPTION_MNU_SAVE_TO_DRAFT,
    EMAIL_EDITOR_WND_OPTION_MNU_ADD_TO,
    EMAIL_EDITOR_WND_OPTION_MNU_ADD_CC,
    EMAIL_EDITOR_WND_OPTION_MNU_ADD_BCC,
    EMAIL_EDITOR_WND_OPTION_MNU_FORWARD,
    EMAIL_EDITOR_WND_OPTION_MNU_REPLY,
    EMAIL_EDITOR_WND_OPTION_MNU_REPLY_ONE,
    EMAIL_EDITOR_WND_OPTION_MNU_REPLY_ALL,
} EmailEditorWndOptionMenuId_e;

 typedef enum
{
    ATTACH_EDITOR_WND_OPTION_MNU_SAVE = 0,
    ATTACH_EDITOR_WND_OPTION_MNU_OPEN,
    ATTACH_EDITOR_WND_OPTION_MNU_DELETE,
    ATTACH_EDITOR_WND_OPTION_MNU_DELETE_ALL,
    ATTACH_EDITOR_WND_OPTION_MNU_ATTACH,
} AttachEditorWndOptionMenuId_e;

typedef enum
{
    EMAIL_WND_ACCOUNTLIST = WND_ID_APP_BASE,
    EMAIL_WND_ACCOUTLIST_OPTIONMENU,
    EMAIL_WND_NEWACCOUNT,
    EMAIL_WND_PUBLICINPUT,
    EMAIL_WND_PUBLICINPUTOPTION,
    EMAIL_WND_EDITACCOUNT,
    EMAIL_WND_SETTING,
    EMAIL_WND_POPUPSELECT,
    EMAIL_WND_POPUPINPUT,
    EMAIL_WND_MAIN_MENU,
    EMAIL_WND_EMAIL_EDITOR,
    EMAIL_WND_EMAIL_EDITOR_OPTION_MENU,
    EMAIL_WND_EMAILBOXLIST,
    EMAIL_WND_BOXLISTOPTION,
    EMAIL_WND_MAILBOX_EDITOR,
    EMAIL_MAILBOX_WND_OPTION_MENU,
    EMAIL_WND_ATTACH_EDITOR,
    EMAIL_ATTACH_EDITOR_WND_OPTION_MENU
}EmailAppId_e;

typedef enum
{
    MNU_EMAIL_MARK = 0,
    MNU_EMAIL_MARK_MARK,
    MNU_EMAIL_MARK_MARKALL,
    MNU_EMAIL_MARK_UNMARK,
    MNU_EMAIL_MARK_UNMARKALL,
    MNU_EMAIL_OPEN,
    MNU_EMAIL_BOXRETRIEVE,
    MNU_EMAIL_CREATE_NEW,
    MNU_EMAIL_MARK_READ,
    MNU_EMAIL_MARK_UNREAD,
    MNU_EMAIL_DELETE,
    MNU_EMAIL_SORT,
    MNU_EMAIL_SORT_BY_SENDER,
    MNU_EMAIL_SORT_BY_TITLE,
    MNU_EMAIL_SORT_BY_TIME,
    MNU_EMAIL_SEARCH,
    MNU_EMAIL_SEARCH_BY_SENDER,
    MNU_EMAIL_SEARCH_BY_TITLE,
    MNU_EMAIL_EDIT,
    MNU_EMAIL_RESEND
}EmailBoxListOptionItem_t;

#endif //__MMI_EMAILAPP_ID_H__
