#ifndef __MMI_CCMTAAPP_ID_H__
#define __MMI_CCMTAAPP_ID_H__
#ifdef __APP_MMI_SMALLROM__
#define __CCMTAAPP_SMALLROM__
#endif

typedef enum CCMTAWndId_e_
{
    CCMTA_WND_INCOMINGCALL = WND_ID_APP_BASE,
	CCMTA_WND_WAITINGCALL,
	CCMTA_WND_WAITINGCALL_OPTIONMENU,
	CCMTA_WND_INCOMINGCALLOPTIONMENU,
	CCMTA_WND_CUS,
#ifdef __DUAL_LCD__
	CCMTA_SUB_WND_INCOMINGCALL = WND_ID_APP_SUB_BASE,
	CCMTA_SUB_WND_WAITINGCALL,
	CCMTA_SUB_WND_CUS
#endif
}CCMTAWndId_e;

#ifdef __UI_STYLE_MMI_IFONE__
typedef enum //CcMtaIncomingCallView_e
{
    CCMTA_INCOMINGCALL_VIEW_BEGIN=APP_WDG_START,
    CCMTA_INCOMINGCALL_VIEW_DarkWdg,
    CCMTA_INCOMINGCALL_VIEW_CallInfoCntr,
	CCMTA_INCOMINGCALL_VIEW_InCallImgWdg,
#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
	CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_VIDEO,
	CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_VIDEO_FIRST_FRAME_IMAGE,
#endif
    CCMTA_INCOMINGCALL_VIEW_InCallInfoTextWdg,
    CCMTA_INCOMINGCALL_VIEW_DuoStateImgWdg,
    CCMTA_INCOMINGCALL_VIEW_CALLSTATE_TEXT,
    CCMTA_INCOMINGCALL_VIEW_BtnCntr,
    CCMTA_INCOMINGCALL_VIEW_RejectBtnWdg,
    CCMTA_INCOMINGCALL_VIEW_HoldBtnWdg,
    CCMTA_INCOMINGCALL_VIEW_OpCntr,
    CCMTA_INCOMINGCALL_VIEW_EndCallBtnWdg,
    CCMTA_INCOMINGCALL_VIEW_AnswerCallBtnWdg,
    CCMTA_INCOMINGCALL_VIEW_END
} CcMtaIncomingCallView_e;
#else
typedef enum //CcMtaIncomingCallView_e
{
    CCMTA_INCOMINGCALL_VIEW_BEGIN=APP_WDG_START,
    CCMTA_INCOMINGCALL_VIEW_CALLSCREEN_BG,
    CCMTA_INCOMINGCALL_VIEW_MAINCONTAINER,
    CCMTA_INCOMINGCALL_VIEW_IMGAREA_CONTAINER,
    CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_IMAGE,
    CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_TEXTAREA_IMAGE,
#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
	CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_VIDEO,
	CCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_VIDEO_FIRST_FRAME_IMAGE,
#endif
    CCMTA_INCOMINGCALL_VIEW_TEXTAREA_CONTAINER,
    CCMTA_INCOMINGCALL_VIEW_CALLINFO_TEXT,
    CCMTA_INCOMINGCALL_VIEW_CALLSTATE_TEXT,
    CCMTA_INCOMINGCALL_VIEW_DUOSTATE_TEXT,
#ifdef __CALLER_LOCATION__
    CCMTA_INCOMINGCALL_VIEW_CALLLOCATION_TEXT,
#endif
    CCMTA_INCOMINGCALL_VIEW_END
} CcMtaIncomingCallView_e;
#endif

typedef enum //CcMtaPetIncomingCallView_e
{
    CCMTA_PET_DIALOG_VIEW_BEGIN=APP_WDG_START,
    CCMTA_PET_DIALOG_VIEW_CONTAINER,
    CCMTA_PET_DIALOG_VIEW_NO_SB_CONTAINER,
    CCMTA_PET_DIALOG_VIEW_BGCONTAINER,
    CCMTA_PET_DIALOG_VIEW_BG_IMAGE,
    CCMTA_PET_DIALOG_VIEW_INCOMINGCALL_IMAGE,
    CCMTA_PET_DIALOG_VIEW_DUOSTATE_IMAGE,
    CCMTA_PET_DIALOG_VIEW_CALLINFO_TEXT,
    CCMTA_PET_DIALOG_VIEW_CALLSTATE,
    CCMTA_PET_DIALOG_INCOMING_ALIVEWIDGET_DOG,
    CCMTA_PET_DIALOG_VIEW_END
} CcMtaPetIncomingCallView_e;

typedef enum
{
	MNU_CCMTA_OPT_REPLACE_ACTIVE = 0,
	MNU_CCMTA_OPT_REPLACE_HOLD,
	MNU_CCMTA_OPT_ANSWER,
	MNU_CCMTA_OPT_QUIET,
	MNU_CCMTA_OPT_BUSY,
	MNU_CCMTA_OPT_DISTORTED_VOICE,
	MNU_CCMTA_OPT_CALL_BACKGROUND_SOUND
}CcMtaOptMenuId_e;

typedef enum VTCCMTAWndId_e_
{
	VTCCMTA_WND_INCOMINGCALL = CCMTA_WND_CUS + 1,
	VTCCMTA_WND_INCOMINGCALL_OPTIONMENU,
	VTCCMTA_WND_WAITINGCALL,
	VTCCMTA_WND_WAITINGCALL_OPTIONMENU,
	VTCCMTA_WND_CUS
}VTCCMTAWndId_e;

typedef enum //VtCcMtaIncomingCallView_e
{
	VTCCMTA_INCOMINGCALL_VIEW_BEGIN = CCMTA_INCOMINGCALL_VIEW_END + 1,
	VTCCMTA_INCOMINGCALL_VIEW_CALLSCREEN_BG,
	VTCCMTA_INCOMINGCALL_VIEW_MAINCONTAINER,
	VTCCMTA_INCOMINGCALL_VIEW_IMGAREA_CONTAINER,
	VTCCMTA_INCOMINGCALL_VIEW_INCOMINGCALL_IMAGE,
	VTCCMTA_INCOMINGCALL_VIEW_TEXTAREA_CONTAINER,
	VTCCMTA_INCOMINGCALL_VIEW_CALLINFO_TEXT,
	VTCCMTA_INCOMINGCALL_VIEW_CALLSTATE_TEXT,
	VTCCMTA_INCOMINGCALL_VIEW_DUOSTATE_TEXT,
	VTCCMTA_INCOMINGCALL_VIEW_END
} VtCcMtaIncomingCallView_e;

typedef enum //VtCcMtaPetIncomingCallView_e
{
	VTCCMTA_PET_DIALOG_VIEW_BEGIN = CCMTA_PET_DIALOG_VIEW_END + 1,
	VTCCMTA_PET_DIALOG_VIEW_CONTAINER,
	VTCCMTA_PET_DIALOG_VIEW_NO_SB_CONTAINER,
	VTCCMTA_PET_DIALOG_VIEW_BGCONTAINER,
	VTCCMTA_PET_DIALOG_VIEW_BG_IMAGE,
	VTCCMTA_PET_DIALOG_VIEW_INCOMINGCALL_IMAGE,
	VTCCMTA_PET_DIALOG_VIEW_DUOSTATE_IMAGE,
	VTCCMTA_PET_DIALOG_VIEW_CALLINFO_TEXT,
	VTCCMTA_PET_DIALOG_VIEW_CALLSTATE,
	VTCCMTA_PET_DIALOG_INCOMING_ALIVEWIDGET_DOG,
	VTCCMTA_PET_DIALOG_VIEW_END
} VtCcMtaPetIncomingCallView_e;

typedef enum
{
	MNU_VTCCMTA_OPT_ANSWER_VIDEO_CALL,
	MNU_VTCCMTA_OPT_ANSWER_VOICE_CALL,
	MNU_VTCCMTA_OPT_QUIET
} VtCcMtaIncomingcallOptionMenuId_e;
#endif //__MMI_CCMTAAPP_ID_H__

