
#ifndef __ESMPCLIENT_STRINGS_h__
#define __ESMPCLIENT_STRINGS_h__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define CJS_STR_ID "id"
#define CJS_STR_WINDOW_OBJECT "window object"
#define CJS_STR_AFTER_NEW_PAGE "gc after new page \n"
#define CJS_STR_NEW_PAGE "new page: \n"
#define CJS_STR_DOCUMENT "document"
#define CJS_STR_FORMS "forms"
#define CJS_STR_ANCHORS "anchors"
#define CJS_STR_LINKS "links"
#define CJS_STR_DOCUMENT_CLASS "document"
#define CJS_STR_TITLE "title"
#define CJS_STR_COOKIE "cookie"
#define CJS_STR_BGCOLOR "bgColor"
#define CJS_STR_FGCOLOR "fgColor"
#define CJS_STR_LINKCOLOR "linkColor"
#define CJS_STR_ALINKCOLOR "alinkColor"
#define CJS_STR_VLINKCOLOR "vlinkColor"
#define CJS_STR_URL "URL"
#define CJS_STR_LOCATION "location"
#define CJS_STR_REFERRER "referrer"
#define CJS_STR_DOMAIN "domain"
#define CJS_STR_WRITE "write"
#define CJS_STR_WRITELN "writeln"
#define CJS_STR_CLEAR "clear"
#define CJS_STR_OPEN "open"
#define CJS_STR_CLOSE "close"
#define CJS_STR_GetElementById "getElementById"	    	//added by will.wang
#define CJS_STR_GetElementByName "getElementsByName"	//added by will.wang

#define CJS_STR_ENTER_AND_NEWLINE "\r\n"
#define CJS_STR_EVENTHANDLER "eventHandler"
#define CJS_STR_EVENT_CLASS "event"
#define CJS_STR_ENENT "event"
#define CJS_STR_TYPE "type"
#define CJS_STR_TIMESTAMP "timeStamp"
#define CJS_STR_TARGET "target"
#define CJS_STR_KEYCODE "keyCode"
#define CJS_STR_EVENT_OBJECT "event object"
#define CJS_STR_NO_LINK_OBJECT "can not find JS Link object"
#define CJS_STR_JAVASCRIPT "javascript:"
#define CJS_STR_ECMASCRIPT "ecmascript:"
#define CJS_STR_FORM_CLASS "Form"
#define CJS_STR_NAME "name"
#define CJS_STR_ACTION "action"
#define CJS_STR_ENCODING "encoding"
#define CJS_STR_ENCTYPE "enctype"
#define CJS_STR_METHOD "method"
#define CJS_STR_LENGTH "length"
#define CJS_STR_SUBMIT "submit"
#define CJS_STR_RESET "reset"
#define CJS_STR_POST "post"
#define CJS_STR_GET "get"
#define CJS_STR_ELEMENT "elements"
#define CJS_STR_TEXT "text"
#define CJS_STR_PASSWORD "password"
#define CJS_STR_CHECKBOX "checkbox"
#define CJS_STR_RADIO "radio"
#define CJS_STR_HIDDEN "hidden"
#define CJS_STR_BUTTON "button"
#define CJS_STR_FILE "file"
#define CJS_STR_SELECT_ONE "select-one"
#define CJS_STR_SELECT_MUL "select-multiple"
#define CJS_STR_TEXTAREA "textarea"
#define CJS_STR_FIELD_CLASS "Field"
#define CJS_STR_VALUE "value"
#define CJS_STR_DEFAULT_VALUE "defaultValue"
#define CJS_STR_SIZE "size"
#define CJS_STR_MAXLENGTH "maxLength"
#define CJS_STR_DEFAULT_CHECKED "defaultChecked"
#define CJS_STR_CHECKED "checked"
#define CJS_STR_COLS "cols"
#define CJS_STR_ROWS "rows"
#define CJS_STR_SELECTED_INDEX "selectedIndex"
#define CJS_STR_DISABLED "disabled"
#define CJS_STR_ACCESSKEY "accessKey"
#define CJS_STR_CLICK "click"
#define CJS_STR_FOCUS "focus"
#define CJS_STR_BLUR "blur"
#define CJS_STR_SELECT "select"
#define CJS_STR_ADD "add"
#define CJS_STR_REMOVE "remove"
#define CJS_STR_FIELD_OBJECT "field object"
#define CJS_STR_OPTIONS "options"
#define CJS_STR_FORM "form"
#define CJS_STR_HISTORY_CLASS "History"
#define CJS_STR_BACK "back"
#define CJS_STR_FORWARD "forward"
#define CJS_STR_GO "go"
#define CJS_STR_HISTORY "history"
#define CJS_STR_COLON ":"
#define CJS_STR_DEFAULT_PORT "80"
#define CJS_STR_LINK_CLASS "Link"
#define CJS_STR_HREF "href"
#define CJS_STR_PROTOCOL "protocol"
#define CJS_STR_HOSTNAME "hostname"
#define CJS_STR_HOST "host"
#define CJS_STR_PORT "port"
#define CJS_STR_PATHNAME "pathname"
#define CJS_STR_HASH "hash"
#define CJS_STR_SEARCH "search"
#define CJS_STR_ONCLICK "onclick"
#define CJS_STR_LOCATION_CLASS "Location"
#define CJS_STR_RELOAD "reload"
#define CJS_STR_REPLACE "replace"
#define CJS_STR_ASSIGN "assign"
#define CJS_STR_NAVIGATOR_CLASS "Navigator"
#define CJS_STR_NAVIGATOR "navigator"
#define CJS_STR_APPNAME "appName"
#define CJS_STR_NAVI_APPNAME "Esmertec u@Wap"
#define CJS_STR_APPVERSION "appVersion"
#define CJS_STR_NAVI_APPVERSION "2.0"
#define CJS_STR_USERAGENT "userAgent"
#define CJS_STR_NAVI_USERAGENT "u@Wap"
#define CJS_STR_LANGUAGE "language"
#define CJS_STR_NAVI_LANGUAGE "zh-cn"
#define CJS_STR_OPTION_CLASS "Option"
#define CJS_STR_DEFAULT_SELECTED "defaultSelected"
#define CJS_STR_SELECTED "selected"
#define CJS_STR_LABEL "label"
#define CJS_STR_NODELIST_CLASS "NodeList"
#define CJS_STR_WINDOW_CLASS "Window"
#define CJS_STR_DEFAULT_STATUS "defaultStatus"
#define CJS_STR_STATUS "status"
#define CJS_STR_OPENER "opener"
#define CJS_STR_SCREEN "screen"
#define CJS_STR_ALERT "alert"
#define CJS_STR_CONFIRM "confirm"
#define CJS_STR_PROMPT "prompt"
#define CJS_STR_SETTIMEOUT "setTimeout"
#define CJS_STR_CLEARTIMEOUT "clearTimeout"

#ifdef SUPPORT_ONLOAD_UNONLOAD
#define CJS_STR_ONLOAD "onload"
#define CJS_STR_UNONLOAD "unonload"
#endif /* SUPPORT_LOAD_UNLOAD */

#define CJS_STR_OPEN_NEW_PAGE "Open a new page?\r\n"
#define CJS_STR_NOT_SUPPORT_WINDOW_OPEN "Not support Window.Open method"
#define CJS_STR_UNDEFINED "undefined"
#define CJS_STR_WINDOW "window"
#define CJS_STR_SELF "self"
#define CJS_STR_TOP "top"
#define CJS_STR_PARENT "parent"
#define CJS_STR_WINDOW_PROTO "windowProto"

#define CJS_STR_CRYPTO_CLASS "crypto"
#define CJS_STR_VERSION "version"
#define CJS_STR_SIGNTEXT "signText"
#define CJS_STR_RANDOM "random"

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __ESMPCLIENT_STRINGS_h__ */
