
#ifndef __RPOV_WBXML_H__
#define __RPOV_WBXML_H__
#ifndef UAPP_PUSH_PROV
//#error "PROV had been disabled"
#endif /* UAPP_PUSH_PROV */

#include <ncc_types.h>

#define PROV_WAP_PROVISIONINGDOC              0x05
#define PROV_CHARACTERISTIC                   0x06
#define PROV_PARM                             0x07
#define PROV_VERSION                          0x45
#define PROV_VERSION_1_0                      0x46
#define PROV_TYPE                             0x50
#define PROV_TYPE_PXLOGICAL                   0x51
#define PROV_TYPE_PXPHYSICAL                  0x52
#define PROV_TYPE_PORT                        0x53
#define PROV_TYPE_VALIDITY                    0x54
#define PROV_TYPE_NAPDEF                      0x55
#define PROV_TYPE_BOOTSTRAP                   0x56
#define PROV_TYPE_VENDORCONFIG                0x57
#define PROV_TYPE_CLIENTIDENTITY              0x58
#define PROV_TYPE_PXAUTHINFO                  0x59
#define PROV_TYPE_NAPAUTHINFO                 0x5A
#define PROV_TYPE_ACCESS                      0x5B
#define PROV_TYPE_PORT                        0x53
#define PROV_TYPE_CLIENTIDENTITY              0x58
#define PROV_TYPE_APPLICATION                 0x55
#define PROV_TYPE_APPADDR                     0x56
#define PROV_TYPE_APPAUTH                     0x57
#define PROV_TYPE_RESOURCE                    0x59
#define PROV_NAME_NAME                        0x07
#define PROV_NAME_NAP_ADDRESS                 0x08
#define PROV_NAME_NAP_ADDRTYPE                0x09
#define PROV_NAME_CALLTYPE                    0x0A
#define PROV_NAME_VALIDUNTIL                  0x0B
#define PROV_NAME_AUTHTYPE                    0x0C
#define PROV_NAME_AUTHNAME                    0x0D
#define PROV_NAME_AUTHSECRET                  0x0E
#define PROV_NAME_LINGER                      0x0F
#define PROV_NAME_BEARER                      0x10
#define PROV_NAME_NAPID                       0x11
#define PROV_NAME_COUNTRY                     0x12
#define PROV_NAME_NETWORK                     0x13
#define PROV_NAME_INTERNET                    0x14
#define PROV_NAME_PROXY_ID                    0x15
#define PROV_NAME_PROXY_PROVIDER_ID           0x16
#define PROV_NAME_DOMAIN                      0x17
#define PROV_NAME_PROVURL                     0x18
#define PROV_NAME_PXAUTH_TYPE                 0x19
#define PROV_NAME_PXAUTH_ID                   0x1A
#define PROV_NAME_PXAUTH_PW                   0x1B
#define PROV_NAME_STARTPAGE                   0x1C
#define PROV_NAME_BASAUTH_ID                  0x1D
#define PROV_NAME_BASAUTH_PW                  0x1E
#define PROV_NAME_PUSHENABLED                 0x1F
#define PROV_NAME_PXADDR                      0x20
#define PROV_NAME_PXADDRTYPE                  0x21
#define PROV_NAME_TO_NAPID                    0x22
#define PROV_NAME_PORTNBR                     0x23
#define PROV_NAME_SERVICE                     0x24
#define PROV_NAME_LINKSPEED                   0x25
#define PROV_NAME_DNLINKSPEED                 0x26
#define PROV_NAME_LOCAL_ADDR                  0x27
#define PROV_NAME_LOCAL_ADDRTYPE              0x28
#define PROV_NAME_CONTEXT_ALLOW               0x29
#define PROV_NAME_TRUST                       0x2A
#define PROV_NAME_MASTER                      0x2B
#define PROV_NAME_SID                         0x2C
#define PROV_NAME_SOC                         0x2D
#define PROV_NAME_WSP_VERSION                 0x2E
#define PROV_NAME_PHYSICAL_PROXY_ID           0x2F
#define PROV_NAME_CLIENT_ID                   0x30
#define PROV_NAME_DELIVERY_ERR_SDU            0x31
#define PROV_NAME_DELIVERY_ORDER              0x32
#define PROV_NAME_TRAFFIC_CLASS               0x33
#define PROV_NAME_MAX_SDU_SIZE                0x34
#define PROV_NAME_MAX_BITRATE_UPLINK          0x35
#define PROV_NAME_MAX_BITRATE_DNLINK          0x36
#define PROV_NAME_RESIDUAL_BER                0x37
#define PROV_NAME_SDU_ERROR_RATIO             0x38
#define PROV_NAME_TRAFFIC_HANDL_PRIO          0x39
#define PROV_NAME_TRANSFER_DELAY              0x3A
#define PROV_NAME_GUARANTEED_BITRATE_UPLINK   0x3B
#define PROV_NAME_GUARANTEED_BITRATE_DNLINK   0x3C
#define PROV_NAME_PXADDR_FQDN                 0x3D
#define PROV_NAME_PROXY_PW                    0x3E
#define PROV_NAME_PPGAUTH_TYPE                0x3F
#define PROV_NAME_PULLENABLED                 0x47
#define PROV_NAME_DNS_ADDR                    0x48
#define PROV_NAME_MAX_NUM_RETRY               0x49
#define PROV_NAME_FIRST_RETRY_TIMEOUT         0x4A
#define PROV_NAME_REREG_THRESHOLD             0x4B
#define PROV_NAME_T_BIT                       0x4C
#define PROV_NAME_AUTH_ENTITY                 0x4E
#define PROV_NAME_SPI                         0x4F
#define PROV_NAME_INTERNET                    0x14
#define PROV_NAME_STARTPAGE                   0x1C
#define PROV_NAME_TO_NAPID                    0x22
#define PROV_NAME_PORTNBR                     0x23
#define PROV_NAME_SERVICE                     0x24
#define PROV_NAME_AACCEPT                     0x2E
#define PROV_NAME_AAUTHDATA                   0x2F
#define PROV_NAME_AAUTHLEVEL                  0x30
#define PROV_NAME_AAUTHNAME                   0x31
#define PROV_NAME_AAUTHSECRET                 0x32
#define PROV_NAME_AAUTHTYPE                   0x33
#define PROV_NAME_ADDR                        0x34
#define PROV_NAME_ADDRTYPE                    0x35
#define PROV_NAME_APPID                       0x36
#define PROV_NAME_APROTOCOL                   0x37
#define PROV_NAME_PROVIDER_ID                 0x38
#define PROV_NAME_TO_PROXY                    0x39
#define PROV_NAME_URI                         0x3A
#define PROV_NAME_RULE                        0x3B
#define PROV_IPV4                             0x85
#define PROV_IPV6                             0x86
#define PROV_E164                             0x87
#define PROV_ALPHA                            0x88
#define PROV_APN                              0x89
#define PROV_SCODE                            0x8A
#define PROV_TETRA_ITSI                       0x8B
#define PROV_MAN                              0x8C
#define PROV_IPV6                             0x86
#define PROV_E164                             0x87
#define PROV_ALPHA                            0x88
#define PROV_APPSRV                           0x8D
#define PROV_OBEX                             0x8E
#define PROV_ANALOG_MODEM                     0x90
#define PROV_V_120                            0x91
#define PROV_V_110                            0x92
#define PROV_X_31                             0x93
#define PROV_BIT_TRANSPARENT                  0x94
#define PROV_DIRECT_ASYNCHRONOUS_DATA_SERVICE 0x95
#define PROV_PAP                              0x9A
#define PROV_CHAP                             0x9B
#define PROV_HTTP_BASIC                       0x9C
#define PROV_HTTP_DIGEST                      0x9D
#define PROV_WTLS_SS                          0x9E
#define PROV_MD5                              0x9F
#define PROV_GSM_USSD                         0xA2
#define PROV_GSM_SMS                          0xA3
#define PROV_ANSI_136_GUTS                    0xA4
#define PROV_IS_95_CDMA_SMS                   0xA5
#define PROV_IS_95_CDMA_CSD                   0xA6
#define PROV_IS_95_CDMA_PACKET                0xA7
#define PROV_ANSI_136_CSD                     0xA8
#define PROV_ANSI_136_GPRS                    0xA9
#define PROV_GSM_CSD                          0xAA
#define PROV_GSM_GPRS                         0xAB
#define PROV_AMPS_CDPD                        0xAC
#define PROV_PDC_CSD                          0xAD
#define PROV_PDC_PACKET                       0xAE
#define PROV_IDEN_SMS                         0xAF
#define PROV_IDEN_CSD                         0xB0
#define PROV_IDEN_PACKET                      0xB1
#define PROV_FLEX_REFLEX                      0xB2
#define PROV_PHS_SMS                          0xB3
#define PROV_PHS_CSD                          0xB4
#define PROV_TETRA_SDS                        0xB5
#define PROV_TETRA_PACKET                     0xB6
#define PROV_ANSI_136_GHOST                   0xB7
#define PROV_MOBITEX_MPAK                     0xB8
#define PROV_CDMA2000_1X_SIMPLE_IP            0xB9
#define PROV_CDMA2000_1X_MOBILE_IP            0xBA
#define PROV_AUTOBAUDING                      0xC5
#define PROV_CL_WSP                           0xCA
#define PROV_CO_WSP                           0xCB
#define PROV_CL_SEC_WSP                       0xCC
#define PROV_CO_SEC_WSP                       0xCD
#define PROV_CL_SEC_WTA                       0xCE
#define PROV_CO_SEC_WTA                       0xCF
#define PROV_OTA_HTTP_TO                      0xD0
#define PROV_OTA_HTTP_TLS_TO                  0xD1
#define PROV_OTA_HTTP_PO                      0xD2
#define PROV_OTA_HTTP_TLS_PO                  0xD3
#define PROV_COMMA_CHARACTER                  0x90
#define PROV_HTTP_                            0x91
#define PROV_BASIC                            0x92
#define PROV_DIGEST                           0x93
#define PROV_AAA                              0xE0
#define PROV_HA                               0xE1

#define PROV_NAME_EQUE                        0x05
#define PROV_VALUE_EQUE                       0x06

XML_BOOL prov_getAttr(int32_t codePage, uint8_t tagChar,
                      int8_t attrChar, int8_t *name, int8_t *value);
XML_BOOL prov_getTag(int32_t codePage, uint8_t tagChar, int8_t *name);

#endif /* __RPOV_WBXML_H__ */
