ApBegin(RS,CLSID_PHBAP)

    WndBegin(PHB_WND_INIT)
        WdgBegin(CLSID_VTMMENU,vtmInitMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_PHONEBOOK,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,vtmInitMenu)
    WndEnd(PHB_WND_INIT)

#ifndef __SMALL_PHB_MMI__ 
    WndBegin(PHB_WND_ViewPhbListSelectNumToSave)
        WdgBegin(CLSID_VTMMENU,vtmListSelectMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,MMI_PHB_NUMBER_MAX_RS,0,0})
        WdgEnd(CLSID_VTMMENU,vtmListSelectMenu)
    WndEnd(PHB_WND_ViewPhbListSelectNumToSave)
#endif // #ifndef __SMALL_PHB_MMI__ 

    WndBegin(PHB_WND_ViewPhbListOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmListOption)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,19)
            VtmCreateOptionMenuDataRC(19, {
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_CONTACT}, TXT_OIL1_N_VIEW },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MAKE_CALL}, TXT_OIL1_N_CALL },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIDEO_CALL}, TXT_OIL1_N_VIDEO_CALL },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_IP_CALL}, TXT_OIL1_N_IP_CALL },
                        {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_LTL_N_SEND },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_NEW_CONTACT}, TXT_OIL1_N_NEW },
                        {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_NEW_CONTACT_OPTION}, TXT_OIL1_N_NEW },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_DELETE_CONTACT}, TXT_OIL1_N_DELETE },
                        {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK_MODE_OPTION}, TXT_OIL1_N_MARK },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_TO_PHONE}, TXT_OIL1_N_COPY_TO_PHONE },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_TO_SIM}, TXT_OIL1_N_COPY_TO_SIM } ,
                        {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_OPTION}, TXT_OIL1_N_COPY },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST } ,
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_GROUP}, TXT_OIL1_N_ASSIGN_TO_GROUP } ,
                        {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VCARD_OPTION}, TXT_OIL1_N_VCARD } ,
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_FDN}, TXT_OIL1_N_FDN } ,
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEARCH_OPTIONS}, TXT_OIL1_N_SEARCH_OPTIONS },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEMORY_DETAILS}, TXT_OIL1_N_MEMORY_DETAILS },
                        {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SXM_VIDEO}, TXT_OIL2_N_VIDEO_CHAT }  })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmListOption)
    WndEnd(PHB_WND_ViewPhbListOption)

    WndBegin(PHB_WND_ViewContactOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmContactOption)
#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__        
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,13)
            VtmCreateOptionMenuDataRC(13, {
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_CONTACT}, TXT_OIL1_N_VIEW },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MAKE_CALL}, TXT_OIL1_N_CALL },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIDEO_CALL}, TXT_OIL1_N_VIDEO_CALL },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_IP_CALL}, TXT_OIL1_N_IP_CALL },
            {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_CONTACT}, TXT_OIL1_N_EDIT },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_DELETE_CONTACT}, TXT_OIL1_N_DELETE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SET_PICTURE}, TXT_OIL1_N_SET_PICTURE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SET_RINGTONE}, TXT_OIL1_N_SET_RINGTONE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SET_VIDEOTONE}, TXT_OIL1_N_SET_VIDEOTONE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_GROUP}, TXT_OIL1_N_ASSIGN_TO_GROUP } ,
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SXM_VIDEO}, TXT_OIL2_N_VIDEO_CHAT }  })
#else
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,12)
            VtmCreateOptionMenuDataRC(12, {
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_CONTACT}, TXT_OIL1_N_VIEW },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MAKE_CALL}, TXT_OIL1_N_CALL },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIDEO_CALL}, TXT_OIL1_N_VIDEO_CALL },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_IP_CALL}, TXT_OIL1_N_IP_CALL },
            {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_CONTACT}, TXT_OIL1_N_EDIT },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_DELETE_CONTACT}, TXT_OIL1_N_DELETE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SET_PICTURE}, TXT_OIL1_N_SET_PICTURE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SET_RINGTONE}, TXT_OIL1_N_SET_RINGTONE },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST },
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_GROUP}, TXT_OIL1_N_ASSIGN_TO_GROUP } ,
            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SXM_VIDEO}, TXT_OIL2_N_VIDEO_CHAT }  })
#endif
        WdgEnd(CLSID_VTMOPTIONMENU,vtmContactOption)
    WndEnd(PHB_WND_ViewContactOption)

    WndBegin(PHB_WND_EditContactFullEditOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmEditContact)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,2)
            VtmCreateOptionMenuDataRC(2, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_SAVE}, TXT_LSK_N_OK },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_INPUT_MENU}, TXT_OIL1_N_INPUT_MENU} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmEditContact)
    WndEnd(PHB_WND_EditContactFullEditOption)

    WndBegin(PHB_WND_EditSelectionShowNewOrExist)
        WdgBegin(CLSID_VTMMENU,vtmEditSelectionShow)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SAVE_TO,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,2,0,0})
            VtmCreateMenuDataRC(2, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, TXT_LIL_N_NEW_CONTACT}, {IMG_NULL_ID,TXT_LIL_N_NEW_CONTACT} },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, TXT_LIL_N_EXISTING_CONTACT}, {IMG_NULL_ID,TXT_LIL_N_EXISTING_CONTACT}} })
        WdgEnd(CLSID_VTMMENU,vtmEditSelectionShow)
    WndEnd(PHB_WND_EditSelectionShowNewOrExist)

    WndBegin(PHB_WND_EditSelectionShowSaveTo)
        WdgBegin(CLSID_VTMMENU,vtmShowSaveTo)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SAVE_TO,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,3,0,0})
            VtmCreateMenuDataRC(3, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, TXT_LIL_N_PHONE}, {IMG_NULL_ID,TXT_LIL_N_PHONE}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, TXT_LIL_N_MASTER_SIM}, {IMG_NULL_ID,TXT_LIL_N_MASTER_SIM}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, TXT_LIL_N_SLAVE_SIM}, {IMG_NULL_ID,TXT_LIL_N_SLAVE_SIM}}   })
        WdgEnd(CLSID_VTMMENU,vtmShowSaveTo)
    WndEnd(PHB_WND_EditSelectionShowSaveTo)

#ifndef __SMALL_PHB_MMI__
    WndBegin(PHB_WND_EditSelectionShowNumType)
        WdgBegin(CLSID_VTMMENU,vtmShowNumType)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NEW_CONTACT,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_MOBILE}, {IMG_NULL_ID,TXT_LIL_N_MOBILE} },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_HOME}, {IMG_NULL_ID,TXT_LIL_N_HOME_NUMBER} },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_OFFICE}, {IMG_NULL_ID,TXT_LIL_N_OFFICE} },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_EDIT_OTHER}, {IMG_NULL_ID,TXT_LIL_N_OTHER}}   })
        WdgEnd(CLSID_VTMMENU,vtmShowNumType)
    WndEnd(PHB_WND_EditSelectionShowNumType)
#endif

#ifndef __MMI_PHBAP_DISABLE_GROUP__
    WndBegin(PHB_WND_ViewGroupGroupListOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmGroupListOption)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,6)
            VtmCreateOptionMenuDataRC(6, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_GROUP}, TXT_OIL1_N_VIEW },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_GROUPS_ADD}, TXT_OIL1_N_ADD },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_GROUPS_EDIT}, TXT_OIL1_N_EDIT },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_DELETE_CONTACT}, TXT_OIL1_N_DELETE },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEMORY_DETAILS}, TXT_OIL1_N_MEMORY_DETAILS} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmGroupListOption)
    WndEnd(PHB_WND_ViewGroupGroupListOption)

    WndBegin(PHB_WND_ViewGroupEditGroup)
        WdgBegin(CLSID_VTMMENU,vtmGroupEditMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_EDIT_GROUP,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,vtmGroupEditMenu)
    WndEnd(PHB_WND_ViewGroupEditGroup)

    WndBegin(PHB_WND_ViewGroupEditGroupNameOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmNameOption)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,2)
            VtmCreateOptionMenuDataRC(2, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_SAVE}, TXT_OIL1_N_SAVE },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_INPUT_MENU}, TXT_OIL1_N_INPUT_MENU} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmNameOption)
    WndEnd(PHB_WND_ViewGroupEditGroupNameOption)
#endif // #ifndef __MMI_PHBAP_DISABLE_GROUP__

#ifndef __MMI_PHB_DISABLE_BLACKLIST__
    WndBegin(PHB_WND_BKListEmptyOptionItem)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMemberList1)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,3)
            VtmCreateOptionMenuDataRC(3, {
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_BLACKLIST_ADD_NEW}, TXT_OIL1_N_ADD_TOBLACKLIST_NEW },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_BLACKLIST_ADD_FROM_PHB}, TXT_OIL1_N_ADD_TOBLACKLIST_FROM_PHONEBOOK },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEMORY_DETAILS}, TXT_OIL1_N_MEMORY_DETAILS}  })
        WdgEnd(CLSID_VTMOPTIONMENU, vtmMemberList1)
    WndEnd(PHB_WND_BKListEmptyOptionItem)

    WndBegin(PHB_WND_BKListOptionItem)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMemberList2)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,9)
            VtmCreateOptionMenuDataRC(9, {
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_CONTACT}, TXT_OIL1_N_VIEW },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MAKE_CALL}, TXT_OIL1_N_CALL },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIDEO_CALL}, TXT_OIL1_N_VIDEO_CALL },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_IP_CALL}, TXT_OIL1_N_IP_CALL },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ADD_BLACKLIST_OPTION}, TXT_OIL1_N_ADD_BLACKLIST_MEMBER },
                	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_BLACKLIST_DELETE}, TXT_OIL1_N_REMOVE },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK_MODE_OPTION}, TXT_OIL1_N_MARK },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEMORY_DETAILS}, TXT_OIL1_N_MEMORY_DETAILS }  })
        WdgEnd(CLSID_VTMOPTIONMENU, vtmMemberList2)
    WndEnd(PHB_WND_BKListOptionItem)
#endif // #ifndef __MMI_PHB_DISABLE_BLACKLIST__

#ifndef __MMI_PHBAP_DISABLE_GROUP__
    WndBegin(PHB_WND_ViewGroupMemberListOption)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMemberList3)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,13)
            VtmCreateOptionMenuDataRC(13, {
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIEW_CONTACT}, TXT_OIL1_N_VIEW },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MAKE_CALL}, TXT_OIL1_N_CALL },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VIDEO_CALL}, TXT_OIL1_N_VIDEO_CALL },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_IP_CALL}, TXT_OIL1_N_IP_CALL },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_GROUP_ADD_MEMBER}, TXT_OIL1_N_ADD },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_GROUP_REMOVE_MEMBER}, TXT_OIL1_N_REMOVE },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK_MODE_OPTION}, TXT_OIL1_N_MARK },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST } ,
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_ASSIGN_TO_GROUP}, TXT_OIL1_N_ASSIGN_TO_GROUP },
                    {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VCARD_OPTION}, TXT_OIL1_N_VCARD },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEARCH_OPTIONS}, TXT_OIL1_N_SEARCH_OPTIONS },
                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEMORY_DETAILS}, TXT_OIL1_N_MEMORY_DETAILS } })
        WdgEnd(CLSID_VTMOPTIONMENU, vtmMemberList3)
    WndEnd(PHB_WND_ViewGroupMemberListOption)
#endif // #ifndef __MMI_PHBAP_DISABLE_GROUP__

    WndBegin(PHB_WND_MultiSelectOption1)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMultiSlect1)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,10)
            VtmCreateOptionMenuDataRC(10, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK}, TXT_OIL1_N_MARK },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_UNMARK}, TXT_OIL1_N_UNMARK },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_OPTION}, TXT_OIL1_N_COPY },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_DELETE_CONTACT}, TXT_OIL1_N_DELETE },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_TO_PHONE}, TXT_OIL1_N_COPY_TO_PHONE },
                {{MENUMODEL_ITEM_VISABLE , {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_COPY_TO_SIM}, TXT_OIL1_N_COPY_TO_SIM },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VCARD_OPTION}, TXT_OIL1_N_VCARD },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK_ALL}, TXT_OIL1_N_MARK_ALL },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_UNMARK_ALL}, TXT_OIL1_N_UNMARK_ALL} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmMultiSlect1)
    WndEnd(PHB_WND_MultiSelectOption1)

    WndBegin(PHB_WND_MultiSelectOption2)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMultiSlect2)
            VtmCreateOptionMenuRC(WDG_MENU_ITEM_TYPE_TEXT,7)
            VtmCreateOptionMenuDataRC(7, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK}, TXT_OIL1_N_MARK },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_UNMARK}, TXT_OIL1_N_UNMARK },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_GROUP_REMOVE_MEMBER}, TXT_OIL1_N_REMOVE },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEND}, TXT_OIL1_N_SEND },
                {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_VCARD_OPTION}, TXT_OIL1_N_VCARD },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MARK_ALL}, TXT_OIL1_N_MARK_ALL },
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_UNMARK_ALL}, TXT_OIL1_N_UNMARK_ALL} })
        WdgEnd(CLSID_VTMOPTIONMENU, vtmMultiSlect2)
    WndEnd(PHB_WND_MultiSelectOption2)


    WndBegin(PHB_WND_SelectImageIDShowChangeMenu)
        WdgBegin(CLSID_VTMPOPUPSELECT,vtmShowChange)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0 } )
            VtmCreatePopUpSelectDataRC(2, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_USE_DEFAULT}, TXT_OIL1_N_USE_DEFAULT},
                        	                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_SELECT_NEW}, TXT_LIL_N_SELECT_PICTURE} })
        WdgEnd(CLSID_VTMPOPUPSELECT,vtmShowChange)
    WndEnd(PHB_WND_SelectImageIDShowChangeMenu)

    WndBegin(PHB_WND_SelectRingIDShowChangeMenu)
        WdgBegin(CLSID_VTMPOPUPSELECT,vtmSelectRingID)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0 } )
            VtmCreatePopUpSelectDataRC(2, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_USE_DEFAULT}, TXT_OIL1_N_USE_DEFAULT},
                                        	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_SELECT_NEW}, TXT_LIL_N_SELECT_MUSIC} })
        WdgEnd(CLSID_VTMPOPUPSELECT,vtmSelectRingID)
    WndEnd(PHB_WND_SelectRingIDShowChangeMenu)

#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
    WndBegin(PHB_WND_SelectVideoIDShowChangeMenu)
        WdgBegin(CLSID_VTMPOPUPSELECT,vtmSelectVideoID)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0 } )
            VtmCreatePopUpSelectDataRC(2, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_USE_DEFAULT}, TXT_LIL_N_NONE},
                                        	{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_MEDIA_SELECT_NEW}, TXT_LIL_N_SELECT_VIDEOTONE} })
        WdgEnd(CLSID_VTMPOPUPSELECT,vtmSelectVideoID)
    WndEnd(PHB_WND_SelectVideoIDShowChangeMenu)
#endif

#ifndef __MMI_PHBAP_DISABLE_GROUP__
    WndBegin(PHB_WND_SelectGroupListGroup)
        WdgBegin(CLSID_VTMMENU,vtmSelectGroupList)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_PML_N_NONE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,vtmSelectGroupList)
    WndEnd(PHB_WND_SelectGroupListGroup)
#endif // #ifndef __MMI_PHBAP_DISABLE_GROUP__

    WndBegin(PHB_WND_CopyToMenu)
    	WdgBegin(CLSID_VTMSIMSELECTION,vtmCopyToMenu)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_COPY_TO})
        WdgEnd(CLSID_VTMSIMSELECTION,vtmCopyToMenu)
    WndEnd(PHB_WND_CopyToMenu)

#ifndef __SMALL_PHB_MMI__ 
    WndBegin(PHB_WND_SelectNumber)
        WdgBegin(CLSID_VTMPOPUPSELECT,vtmSelectNumber)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0 } )
        WdgEnd(CLSID_VTMPOPUPSELECT,vtmSelectNumber)
    WndEnd(PHB_WND_SelectNumber)
#endif

    WndBegin(PHB_WND_TabView)
        WndSetTitleRC( {IMG_NULL_ID,TXT_LIL_N_PHONEBOOK} )

        WdgBegin(CLSID_TAB_WIDGET, TabViewTab )
            WdgTabCreateForWndRC( { {0,0},{PHBAP_TABLIST_MAINVIEW_WIDTH,PHBAP_TABLIST_TABWDG_HEIGHT},0  } )
            WdgTabSetActiveWidthRC(PHBAP_TABLIST_TABWDG_ACTIVE_WIDTH)
            WdgTabSetInactiveWidthRC(PHBAP_TABLIST_TABWDG_INACTIVE_WIDTH)
            WdgTabSetTabPaddingLeftRC(PHBAP_TABLIST_TABWDG_TAB_LEFT_PADDING)
            WdgTabSetTabPaddingRightRC(PHBAP_TABLIST_TABWDG_TAB_RIGHT_PADDING)
            WdgTabSetTabGapRC(PHBAP_TABLIST_TABWDG_TAB_GAP)
        WdgEnd(CLSID_TAB_WIDGET, TabViewTab)

        WdgBegin(CLSID_MENUWIDGET,TabViewMenu)
            WdgMenuCreateForWndRC({ {0,0},{0 ,0 },WDG_MENU_TYPE_NORMAL})
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
        WdgEnd(CLSID_MENUWIDGET,TabViewMenu)

        WdgBegin(CLSID_TEXTWIDGET,TabViewText)
            WdgTextCreateForWndRC({ {0,0}, {MAIN_DEFVIEW_WIDTH,PHBAP_TABLIST_INFOTEXT_HEIGHT}, TEXT_STYLE_COMMON })
            WdgTextSetDataByIDRC(TXT_PML_N_FDN_ACTIVE_MESSAGE)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_BREAKONWORD)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_PHBAPP_TEXT)
        WdgEnd(CLSID_TEXTWIDGET,TabViewText)

        WdgBegin(CLSID_IMAGEWIDGET,pSearchBGImageWidget)
            WdgImageCreateForWndRC({ {0,0},{MAIN_DEFVIEW_WIDTH,PHBAP_INPUT_SEARCH_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_SEARCH_BG} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_SEARCH_BG)
        WdgEnd(CLSID_IMAGEWIDGET,pSearchBGImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pSearchImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_INPUT_SEARCH_IMG_X,PHBAP_INPUT_SEARCH_IMG_Y},{PHBAP_INPUT_SEARCH_IMG_WIDTH,PHBAP_INPUT_SEARCH_IMG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_SEARCH} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_SEARCH)
        WdgEnd(CLSID_IMAGEWIDGET,pSearchImageWidget)

        WdgBegin(CLSID_INPUTWIDGET,pSearchInputWidget)
            WdgInputCreateForWndRC({ {PHBAP_INPUT_SEARCH_INPUT_X,PHBAP_INPUT_SEARCH_INPUT_Y},{PHBAP_INPUT_SEARCH_INPUT_WIDTH,PHBAP_INPUT_SEARCH_INPUT_HEIGHT},{TRUE,SKBOARD_ENABLE} })
            WdgInputSetModeMaskRC(MAE_MODEMASK_PHB_SEARCH)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_MT_abc_EN)
        WdgEnd(CLSID_INPUTWIDGET,pSearchInputWidget)
    WndEnd(PHB_WND_TabView)

#ifndef __MMI_PHBAP_DISABLE_GROUP__
    WndBegin(PHB_WND_ViewGroupShowMemberList)
        WndSetTitleRC( {IMG_NULL_ID,TXT_LIL_N_PHONEBOOK} )

        WdgBegin(CLSID_MENUWIDGET,ViewGroupMemberMenu)
            WdgMenuCreateForWndRC({ {0,0},{0 ,0 },WDG_MENU_TYPE_NORMAL})
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_TEXT)
        WdgEnd(CLSID_MENUWIDGET,ViewGroupMemberMenu)

        WdgBegin(CLSID_IMAGEWIDGET,pMemberSearchBGImageWidget)
            WdgImageCreateForWndRC({ {0,0},{MAIN_DEFVIEW_WIDTH,PHBAP_INPUT_SEARCH_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_SEARCH_BG} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_SEARCH_BG)
        WdgEnd(CLSID_IMAGEWIDGET,pMemberSearchBGImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pMemberSearchImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_INPUT_SEARCH_IMG_X,PHBAP_INPUT_SEARCH_IMG_Y},{PHBAP_INPUT_SEARCH_IMG_WIDTH,PHBAP_INPUT_SEARCH_IMG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_SEARCH} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_SEARCH)
        WdgEnd(CLSID_IMAGEWIDGET,pMemberSearchImageWidget)

        WdgBegin(CLSID_INPUTWIDGET,pMemberSearchInputWidget)
            WdgInputCreateForWndRC({ {PHBAP_INPUT_SEARCH_INPUT_X,PHBAP_INPUT_SEARCH_INPUT_Y},{PHBAP_INPUT_SEARCH_INPUT_WIDTH,PHBAP_INPUT_SEARCH_INPUT_HEIGHT},{TRUE, SKBOARD_ENABLE} })
            WdgInputSetModeMaskRC(MAE_MODEMASK_PHB_SEARCH)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_MT_abc_EN)
        WdgEnd(CLSID_INPUTWIDGET,pMemberSearchInputWidget)
    WndEnd(PHB_WND_ViewGroupShowMemberList)
#endif // #ifndef __MMI_PHBAP_DISABLE_GROUP__

#if defined(__3D_UI_PHONEBOOK__)

    WndBegin(PHB_WND_ViewContactShowDetail)
        WndSetTitleRC( {IMG_NULL_ID,TXT_LIL_N_PHONEBOOK} )

        WdgBegin(CLSID_IMAGEWIDGET,pContactBGImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_TOP_HALF_BG_X,PHBAP_VIEW_CONTACT_TOP_HALF_BG_Y},{PHBAP_VIEW_CONTACT_TOP_HALF_BG_WIDTH ,PHBAP_VIEW_CONTACT_TOP_HALF_BG_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE,PHONEBOOK_IMG_VIEW_M303_BG} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_VIEW_M303_BG)
        WdgEnd(CLSID_IMAGEWIDGET,pContactBGImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactHeadImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_HEAD_PIC_X,PHBAP_VIEW_CONTACT_HEAD_PIC_Y},{PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH,PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT},IMAGE_STYLE_COMMON, {FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,pContactHeadImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactHeadBlistImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_BLIST_ICON_X,PHBAP_VIEW_CONTACT_BLIST_ICON_Y},{PHBAP_VIEW_CONTACT_BLIST_ICON_WIDTH,PHBAP_VIEW_CONTACT_BLIST_ICON_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_BLACKLIST_THUMBNAIL} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_BLACKLIST_THUMBNAIL)
        WdgEnd(CLSID_IMAGEWIDGET,pContactHeadBlistImageWidget)

        WdgBegin(CLSID_TEXTWIDGET,pContactNameTextWidget)
            WdgTextCreateForWndRC({ {PHBAP_VIEW_CONTACT_NAME_X,PHBAP_VIEW_CONTACT_NAME_Y}, {PHBAP_VIEW_CONTACT_NAME_WIDTH ,PHBAP_VIEW_CONTACT_NAME_HEIGHT},TEXT_STYLE_COMMON })
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_ELLIPSIS)
            WdgTextSetSlideDirectionRC(SLIDE_TO_UP)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,pContactNameTextWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactDualSimImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_DUALSIM_X,PHBAP_VIEW_CONTACT_DUALSIM_Y},{PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT,PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,pContactDualSimImageWidget)

         WdgBegin(CLSID_MENUWIDGET,pContactMenuWidget)
            WdgMenuCreateForWndRC({ {PHBAP_VIEW_CONTACT_LISTMENU_X,PHBAP_VIEW_CONTACT_LISTMENU_Y}, {PHBAP_VIEW_CONTACT_LISTMENU_WIDTH,PHBAP_VIEW_CONTACT_LISTMENU_HEIGHT},WDG_MENU_TYPE_NORMAL })
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE_TEXT)
        WdgEnd(CLSID_MENUWIDGET,pContactMenuWidget)
    WndEnd(PHB_WND_ViewContactShowDetail)

#else

    WndBegin(PHB_WND_ViewContactShowDetail)
        WndSetTitleRC( {IMG_NULL_ID,TXT_LIL_N_PHONEBOOK} )

        WdgBegin(CLSID_IMAGEWIDGET,pContactBGImageWidget)
#ifdef __APP_MMI_SMALLROM__
            WdgImageCreateForWndRC({ {0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH ,(PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT-PHBAP_MENU_WITH_IMAGE_ID_HEIGHT) }, IMAGE_STYLE_COMMON, {FALSE,IMG_NULL_ID} })
#else	// ! __APP_MMI_SMALLROM__        
            WdgImageCreateForWndRC({ {0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH ,(PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT-PHBAP_MENU_WITH_IMAGE_ID_HEIGHT) }, IMAGE_STYLE_COMMON, {FALSE,PHONEBOOK_IMG_VIEW_BG} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_VIEW_BG)
#endif	// !__APP_MMI_SMALLROM__
        WdgEnd(CLSID_IMAGEWIDGET,pContactBGImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactHeadImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_HEAD_PIC_X,PHBAP_VIEW_CONTACT_HEAD_PIC_Y+MAIN_TITLE_HEIGHT},{PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH,PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT},IMAGE_STYLE_COMMON, {FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,pContactHeadImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactHeadBlistImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_BLIST_ICON_X,PHBAP_VIEW_CONTACT_BLIST_ICON_Y+MAIN_TITLE_HEIGHT},{PHBAP_VIEW_CONTACT_BLIST_ICON_WIDTH,PHBAP_VIEW_CONTACT_BLIST_ICON_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_BLACKLIST_THUMBNAIL} })
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_BLACKLIST_THUMBNAIL)
        WdgEnd(CLSID_IMAGEWIDGET,pContactHeadBlistImageWidget)

        WdgBegin(CLSID_TEXTWIDGET,pContactNameTextWidget)
            WdgTextCreateForWndRC({ {PHBAP_VIEW_CONTACT_NAME_X,PHBAP_VIEW_CONTACT_NAME_Y+MAIN_TITLE_HEIGHT}, {PHBAP_VIEW_CONTACT_NAME_WIDTH ,(PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT-PHBAP_MENU_WITH_IMAGE_ID_HEIGHT) },TEXT_STYLE_COMMON })
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_ELLIPSIS)
            WdgTextSetSlideDirectionRC(SLIDE_TO_UP)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,pContactNameTextWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pContactDualSimImageWidget)
            WdgImageCreateForWndRC({ {PHBAP_VIEW_CONTACT_DUALSIM_X,PHBAP_VIEW_CONTACT_DUALSIM_Y+MAIN_TITLE_HEIGHT},{PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT,PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,pContactDualSimImageWidget)

         WdgBegin(CLSID_MENUWIDGET,pContactMenuWidget)
            WdgMenuCreateForWndRC({ {0,PHBAP_MENU_WITH_IMAGE_ID_POS_Y+MAIN_TITLE_HEIGHT}, {MAIN_DEFVIEW_WIDTH,PHBAP_MENU_WITH_IMAGE_ID_HEIGHT},WDG_MENU_TYPE_NORMAL })
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE_TEXT)
        WdgEnd(CLSID_MENUWIDGET,pContactMenuWidget)
    WndEnd(PHB_WND_ViewContactShowDetail)

#endif //__3D_UI_PHONEBOOK__

    WndBegin(PHB_WND_EditContactShowEdit)
        WndSetAllSoftkeyRC({SK_SAVE, SK_OK, SK_CANCEL})

        WdgBegin(CLSID_IT_STEXT_WIDGET,pNameDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_NAME,PHONEBOOK_IMG_CONTACT,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pNameDoubleTextWidget)

        WdgBegin(CLSID_IT_SINPUT_WIDGET,pMobileTextInputWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_SINPUT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_MOBILE,PHONEBOOK_IMG_MOBILE,TXT_NULL_ID})

            ChildBegin(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownMobileTextInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
                WdgInputSetHandWritingEnableRC(FALSE)
            ChildEnd(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownMobileTextInput)
        WdgEnd(CLSID_IT_SINPUT_WIDGET,pMobileTextInputWidget)

#ifndef __MMI_PHBAP_DISABLE_GROUP__
        WdgBegin(CLSID_IT_STEXT_WIDGET,pGroupDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_OIL1_N_GROUPS,PHONEBOOK_IMG_GROUP,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pGroupDoubleTextWidget)
#endif // #ifndef __MMI_PHBAP_DISABLE_GROUP__

        WdgBegin(CLSID_IT_STEXT_WIDGET,pPictureDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_PICTURE,PHONEBOOK_IMG_PICTURE,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pPictureDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pRingtoneDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_RINGTONE,PHONEBOOK_IMG_RINGTONE,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pRingtoneDoubleTextWidget)

#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
        WdgBegin(CLSID_IT_STEXT_WIDGET,pVideotoneDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_VIDEOTONE,PHONEBOOK_IMG_VIDEOTONE,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pVideotoneDoubleTextWidget)
#endif

#ifndef __SMALL_PHB_MMI__ 
        WdgBegin(CLSID_IT_SINPUT_WIDGET,pHomeTextInputWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_SINPUT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_HOME_NUMBER,PHONEBOOK_IMG_HOME,TXT_NULL_ID})

            ChildBegin(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownHomeInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
                WdgInputSetHandWritingEnableRC(FALSE)
            ChildEnd(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownHomeInput)
        WdgEnd(CLSID_IT_SINPUT_WIDGET,pHomeTextInputWidget)

        WdgBegin(CLSID_IT_SINPUT_WIDGET,pOfficeTextInputWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_SINPUT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_OFFICE,PHONEBOOK_IMG_OFFICE,TXT_NULL_ID})

            ChildBegin(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownOfficeInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
                WdgInputSetHandWritingEnableRC(FALSE)
            ChildEnd(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownOfficeInput)
        WdgEnd(CLSID_IT_SINPUT_WIDGET,pOfficeTextInputWidget)

        WdgBegin(CLSID_IT_SINPUT_WIDGET,pOtherTextInputWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_SINPUT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_OTHER,PHONEBOOK_IMG_OTHER,TXT_NULL_ID})

            ChildBegin(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownOtherInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
                WdgInputSetHandWritingEnableRC(FALSE)
            ChildEnd(CLSID_INPUTWIDGET,CHILD_SECOND_ORDER,pDownOtherInput)
        WdgEnd(CLSID_IT_SINPUT_WIDGET,pOtherTextInputWidget)
        
        WdgBegin(CLSID_IT_STEXT_WIDGET,pCompanyDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_COMPANY,PHONEBOOK_IMG_COMPANY,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pCompanyDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pDepartmentDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_DEPARTMENT,PHONEBOOK_IMG_DEPARTMENT,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pDepartmentDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pPositionDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_POSITION,PHONEBOOK_IMG_POSITION,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pPositionDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pAddressDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_ADDRESS,PHONEBOOK_IMG_ADDRESS,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pAddressDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pEmailDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_EMAIL,PHONEBOOK_IMG_EMAIL,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pEmailDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pUrlDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_URL,PHONEBOOK_IMG_URL,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pUrlDoubleTextWidget)

        WdgBegin(CLSID_IT_STEXT_WIDGET,pNoteDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_IT_STEXT})
            WdgDoubleItemITSTextSetDataByIDRC({TXT_LIL_N_NOTE,PHONEBOOK_IMG_NOTE,TXT_NULL_ID})
        WdgEnd(CLSID_IT_STEXT_WIDGET,pNoteDoubleTextWidget)
#endif // #ifndef __SMALL_PHB_MMI__         
    WndEnd(PHB_WND_EditContactShowEdit)

    WndBegin(PHB_WND_SelectImageIDShowCurrent)
        WndSetAllSoftkeyRC({SK_CHANGE, SK_NONE, SK_BACK})
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_PICTURE})

        WdgBegin(CLSID_IMAGEWIDGET,pIImageWidget)
            WdgImageCreateForWndRC({ {((MAIN_DEFVIEW_WIDTH-PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH)/2), ((PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT-PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT)/2)},
                                     {PHBAP_VIEW_CONTACT_HEAD_PIC_WIDTH,PHBAP_VIEW_CONTACT_HEAD_PIC_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,pIImageWidget)
    WndEnd(PHB_WND_SelectImageIDShowCurrent)

    WndBegin(PHB_WND_SelectRingIDShowCurrent)
        WndSetAllSoftkeyRC({SK_CHANGE, SK_PLAY, SK_BACK})
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_RINGTONE})

        WdgBegin(CLSID_TEXTWIDGET,pTextWidget)
            WdgTextCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_ELLIPSIS)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,pTextWidget)
    WndEnd(PHB_WND_SelectRingIDShowCurrent)

    WndBegin(PHB_WND_SetSearchOptions)
        WdgBegin(CLSID_VTMMENU,vtmSelectSearchSetting)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_CHECK,2,0,0 } )
            VtmCreatePopUpSelectDataRC(2, { {{MENUMODEL_ITEM_VISABLE, {SK_SAVE, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEARCH_NUMBER}, TXT_LIL_N_PHBAPP_SEARCH_NUMBER},
                                        	{{MENUMODEL_ITEM_VISABLE, {SK_SAVE, DEFAULT_SK, DEFAULT_SK}, MNU_PHBAP_SEARCH_DIGIT_TO_ALPHABET}, TXT_LIL_N_PHBAPP_SEARCH_DIGIT_TO_ALPHABET} })
        WdgEnd(CLSID_VTMMENU,vtmSelectSearchSetting)
    WndEnd(PHB_WND_SetSearchOptions)

#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
    WndBegin(PHB_WND_SelectVideoIDShowCurrent)
        WndSetAllSoftkeyRC({SK_CHANGE, SK_PLAY, SK_BACK})
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_VIDEOTONE})

        WdgBegin(CLSID_TEXTWIDGET,pVideoTextWidget)
            WdgTextCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,PHBAP_DEFVIEW_WITHOUT_TITLE_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_ELLIPSIS)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,pVideoTextWidget)
    WndEnd(PHB_WND_SelectVideoIDShowCurrent)
#endif
ApEnd(RS,CLSID_PHBAP)


