/**
* @file mmi_vendorapp.h
*
* Application without using State Machine - VENDORAPP
* Generated by XFSM v1.0, CodeVer=v0.24
*
* Class Id: CLSID_VENDORAPP
* Interface Id: IID_VENDORAPP
*
* @version $Id: mmi_vendorapp.h 41096 2009-09-23 02:17:05Z code.lin $
*/
#ifndef __MMI_VENDORAPP_H__
#define __MMI_VENDORAPP_H__

#include "mmi_mae_common_def.h"

#include "mmi_UrlSrvClientHelper.h"
#include "mmi_launcher_vendor.h"
#include "mmi_common_vendor_type.h"

VendorApp_StartParam_t* VendorAppGetVenStartParam(void);
void VendorAppSetVenStartParam(VendorApp_StartParam_t *psStartParm);
MAE_Ret VendorAppNew(MAE_ClsId id, void **ppObj);


/*=============================================================*/
// Global function definition
/*=============================================================*/

/** VendorAppPreNew
* @brief        Prenew function to Launch Vendor to run midlet
*
*/
void VendorAppPreNew(void);
#endif /* __MMI_VENDORAPP_H__ */
