#ifndef __MMI_SCREENSAVERAPP_ID_H__
#define __MMI_SCREENSAVERAPP_ID_H__

typedef enum SCREENSAVERWndId_e_
{
    SCREENSAVER_WND_MAIN = WND_ID_APP_BASE,

} SCREENSAVERWndId_e;

typedef enum
{
    SCREENSAVER_VIEW_BEGIN = APP_WDG_START,
    SCREENSAVER_ANIM_IMAGE,
    SCREENSAVER_VIEW_END
}SCREENSAVERView_e;

#endif //__MMI_SCREENSAVERAPP_ID_H__

