#ifndef __MMI_KINGMOVIEAPP_ID_H__
#define __MMI_KINGMOVIEAPP_ID_H__

typedef enum KingMovieWndId_e_
{
    KMV_WND_CATEGORY_LIST = WND_ID_APP_BASE,
    KMV_WND_CATEGORY_LIST_OPTION,
    KMV_WND_MOVIE_LIST,
    KMV_WND_MOVIE_LIST_OPTION,
    KMV_WND_MOVIE_INFO,
    KMV_WND_MOVIE_INFO_OPTION,
#if defined(__3D_UI_KINGMOVIE__)
    KMV_WND_3DMOVIE_INFO,
    KMV_WND_GLCIRCLE_LIST,
#endif
} KingMovieWndId_e;

typedef enum // KMV_MOVIE_LIST_VIEW_enum
{
    KMV_MOVIE_LIST_VIEW_BEGIN = APP_WDG_START,
#if defined(__3D_UI_KINGMOVIE__)
    KMV_MOVIE_LIST_GLCIRCLELIST_WDG,
    KMV_MOVIE_LIST_RELOADBTN_WDG,
    KMV_MOVIE_LIST_BACKBTN_WDG,
    KMV_MOVIE_LIST_MENUTAB_WDG,
    KMV_MOVIE_LIST_MOVIELIST_CNT,
    KMV_MOVIE_LIST_SUBMENU_WDG,
    KMV_MOVIE_LIST_SUSPEND_BGIMAGE_WDG,
#endif
    KMV_MOVIE_LIST_VIEW_END
} KMVMovieListView_e;

typedef enum // KMV_MOVIE_INFO_VIEW_enum
{
    KMV_MOVIE_INFO_VIEW_BEGIN = APP_WDG_START,
    KMV_MOVIE_INFO_TITLETEXT_WDG,
    KMV_MOVIE_INFO_IMAGE_WDG,
    KMV_MOVIE_INFO_NAMETEXT_WDG,
    KMV_MOVIE_INFO_SCROLLBAR_WDG,
    KMV_MOVIE_INFO_VIEWPORT_WDG,
    KMV_MOVIE_INFO_INFOTEXT_WDG,
    KMV_MOVIE_INFO_SWITCH_CONTAINER,
    KMV_MOVIE_INFO_MOVIE_SWITCH_TEXT_WDG,
    KMV_MOVIE_INFO_LEFT_ARROW_BTN_WDG,
    KMV_MOVIE_INFO_RIGHT_ARROW_BTN_WDG,
#if defined(__3D_UI_KINGMOVIE__)
	KMV_MOVIE_INFO_INFOVIEWPORT_WDG,
    KMV_MOVIE_INFO_TIMETEXT_WDG,
    KMV_MOVIE_INFO_PLAYBTN_WDG,
    KMV_MOVIE_INFO_BACKBTN_WDG,
    KMV_MOVIE_INFO_PAGETEXT_WDG,
    KMV_MOVIE_INFO_PREVBTN_WDG,
    KMV_MOVIE_INFO_NEXTBTN_WDG,
#endif
    KMV_MOVIE_INFO_VIEW_END
} KMVMovieInfoView_e;

enum
{
    /*Menu Item ID*/
    //Category list item begin
    MNU_KMV_LAST_PLAYED = 1,
    MNU_KMV_ACTION,
    MNU_KMV_ADVENTURE,
    MNU_KMV_ANIMATION,
    MNU_KMV_COMEDY,
    MNU_KMV_DOCUMENTARY,
    MNU_KMV_DRAMA,
    MNU_KMV_FAMILYANDKIDS,
    MNU_KMV_FANTASY,
    MNU_KMV_HORROR,
    MNU_KMV_MUSIC,
    MNU_KMV_MYSTERY,
    MNU_KMV_PERFORMINGARTS,
    MNU_KMV_ROMANCE,
    MNU_KMV_SCI_FI,
    MNU_KMV_SPORTS,
    MNU_KMV_SUSPENSE,
    MNU_KMV_WAR,
    MNU_KMV_WESTERN,
    MNU_KMV_OTHERS,
    MNU_KMV_MY_FAVORITES,
    /* Option Menu Item ID*/
    MNU_KMV_OPTION_OPEN,
    MNU_KMV_OPTION_UPDATELIST,
    MNU_KMV_OPTION_PASSWORD_MANAGER,
    //Movie list item begin
    /* Option Menu Item ID*/
    MNU_KMV_OPTION_CONT_PLAY,
    MNU_KMV_OPTION_PLAY,
    MNU_KMV_OPTION_DELETE,
    MNU_KMV_OPTION_DELETE_ALL,
    MNU_KMV_OPTION_MOVIEINFO,
    MNU_KMV_OPTION_VIEW_DETAILS,
    MNU_KMV_OPTION_ADDTOFAVORITES,
    MNU_KMV_END
};

#endif //__MMI_KINGMOVIEAPP_ID_H__

