#ifndef __MMI_CALCULATORPLUSAPP_ID_H__
#define __MMI_CALCULATORPLUSAPP_ID_H__

#ifdef __APP_MMI_SMALLROM__
#define __CALCULATORPLUSAPP_SMALLROM__
#endif

typedef enum
{
    CALCULATORPLUS_WND_MAIN = WND_ID_APP_BASE,
}CalculatorPlusWndId_e;

typedef enum
{
    CALCULATORPLUS_RESULT_TEXT = APP_WDG_START,

}CalculatorPlusWdgId_e;

typedef enum
{
    CALCULATOR_OPERATOR_ADDITION = 0,
    CALCULATOR_OPERATOR_SUBSTRACTION,
    CALCULATOR_OPERATOR_MULTIPLICATION,
    CALCULATOR_OPERATOR_DIVISION,
    CALCULATOR_OPERATOR_EQUAL,
}CalculatorOperatorId_e;

#endif  //__MMI_CALCULATORPLUSAPP_ID_H__

