/**
* @file mmi_simsrv_sm.h
*
* State Machine Service - SIMSRV
* Generated by XFSM v1.0, CodeVer=v0.24
*
* Class Id: CLSID_SIMSRV
*
*
* @version $Id$
*/
#ifndef __MMI_SIMSRV_SM_H__
#define __MMI_SIMSRV_SM_H__

#include "mmi_mae_sm.h"
#include "mmi_class.h"

/**
 * Mode Tree Properties
 */
#define cSIMSRV_ModeNumbers             28
#define cSIMSRV_DependencyNumbers				55

/**
 * Modes (index should begin from 0 and increase continuously)
 */
#define cSIMSRV_MODE_SIMSRV             0
#define cSIMSRV_MODE_Active             1
#define cSIMSRV_MODE_Active_Idle                2
#define cSIMSRV_MODE_Active_Initial             3
#define cSIMSRV_MODE_Active_Initial_GetBasicInfo                4
#define cSIMSRV_MODE_Active_Initial_VerifyPIN               5
#define cSIMSRV_MODE_Active_Initial_UnblockPIN              6
#define cSIMSRV_MODE_Active_Initial_GetIMSI             7
#define cSIMSRV_MODE_Active_Initial_GetSIMOPFile                8
#define cSIMSRV_MODE_Active_Initial_GetSST              9
#define cSIMSRV_MODE_Active_Operation               10
#define cSIMSRV_MODE_Active_Operation_ActivateMasterSIM             11
#define cSIMSRV_MODE_Active_Operation_ActivateSlaveSIM              12
#define cSIMSRV_MODE_Active_Operation_EnablePIN             13
#define cSIMSRV_MODE_Active_Operation_DisablePIN                14
#define cSIMSRV_MODE_Active_Operation_VerifyPIN             15
#define cSIMSRV_MODE_Active_Operation_ChangePIN             16
#define cSIMSRV_MODE_Active_Operation_UnblockPIN                17
#define cSIMSRV_MODE_Active_Operation_ReadSIMFile               18
#define cSIMSRV_MODE_Active_Operation_WriteSIMFile              19
#define cSIMSRV_MODE_Active_Operation_SetLanguage               20
#define cSIMSRV_MODE_Active_Operation_STKRefreshMaster              21
#define cSIMSRV_MODE_Active_Operation_STKRefreshSlave               22
#define cSIMSRV_MODE_Active_Operation_StatusSIMFile             23
#define cSIMSRV_MODE_Active_Operation_DeactivateSIMforShutdown              24
#define cSIMSRV_MODE_Active_Operation_ActivateBothSIM               25
#define cSIMSRV_MODE_Active_Operation_PreSIMSrror               26
#define cSIMSRV_MODE_Active_Error               27


/**
 * Internal Events
 */
#define SIMSRV_IEVT_InitNext                (CLSID_SIMSRV << 16 | 53)
#define SIMSRV_IEVT_SIMError                (CLSID_SIMSRV << 16 | 54)
#define SIMSRV_IEVT_BackToIdle              (CLSID_SIMSRV << 16 | 55)
#define SIMSRV_IEVT_InitSIM             (CLSID_SIMSRV << 16 | 56)
#define SIMSRV_IEVT_InitSIMReady                (CLSID_SIMSRV << 16 | 57)
#define SIMSRV_IEVT_SIMErrorPreProcess              (CLSID_SIMSRV << 16 | 58)
#define SIMSRV_IEVT_SIMErrorReq             (CLSID_SIMSRV << 16 | 59)


/**
 * Macros for triggering internal events
 */
#define TRIGGER_EVT_SIMSRV_IEVT_InitNext(pSM, p1, p2)   MAE_TriggerEvent(pSM, SIMSRV_IEVT_InitNext, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_SIMError(pSM, p1, p2)   MAE_TriggerEvent(pSM, SIMSRV_IEVT_SIMError, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_BackToIdle(pSM, p1, p2) MAE_TriggerEvent(pSM, SIMSRV_IEVT_BackToIdle, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_InitSIM(pSM, p1, p2)    MAE_TriggerEvent(pSM, SIMSRV_IEVT_InitSIM, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_InitSIMReady(pSM, p1, p2)   MAE_TriggerEvent(pSM, SIMSRV_IEVT_InitSIMReady, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_SIMErrorPreProcess(pSM, p1, p2) MAE_TriggerEvent(pSM, SIMSRV_IEVT_SIMErrorPreProcess, p1, p2)
#define TRIGGER_EVT_SIMSRV_IEVT_SIMErrorReq(pSM, p1, p2)    MAE_TriggerEvent(pSM, SIMSRV_IEVT_SIMErrorReq, p1, p2)


/*-------------------------------------------------------------------------*/
extern const SM_Mode_t SIMSRV_modeTree[];
extern const SM_Transition_t SIMSRV_transition[];
extern const SM_TransitionForEvent_t SIMSRV_transForEvent[];
extern const SM_EventDep_t SIMSRV_eventDependency[];

#endif /* __MMI_SIMSRV_SM_H__ */
