#ifndef __MMI_MESSAGETEMPLATEAPP_VIEW_ID_H__
#define __MMI_MESSAGETEMPLATEAPP_VIEW_ID_H__

#include "mmi_view_id_range.h"
#include "mmi_message_cfg.h"

#define MTA_EDITOR_MAX_BYTE MSG_TEXT_TEMPLATE_MAX_CHAR*sizeof(MAE_WChar)

enum
{
/* View ID start */
	MTA_TEMPLATE_MENU_VIEW =  MMI_VIEW_ID_AP_BEGIN,
	MTA_TEMPLATE_TEXT_EDITOR_VIEW,
	MTA_TEMPLATE_OPTION_MODEL,
	MTA_TEMPLATE_CREATE_MSG_OPTION_MODEL,
	MTA_TEMPLATE_TEXT_EDITOR_OPTION_MODEL
/* View ID end */
};

enum
{
/* Widget ID start */
    MTA_TEMPLATE_TITLE = 1,
	MTA_TEMPLATE_MENU,
	MTA_TEXT_EDITOR_TITLE,
	MTA_TEXT_EDITOR_SCROLLBAR,
	MTA_TEXT_EDITOR_INPUTE,
/* Widget ID end */
};

enum e_MTA_OPTION
{
/* Binary ID start */
    /*e_MENU_OPTION*/
    MTA_MENU_OPTION_CREATE,
    MTA_MENU_OPTION_EDIT,
#ifdef __MMS_MMI_CDMMS_TEMPLATE__
    MTA_MENU_OPTION_PREVIEW,
#endif    
    MTA_MENU_OPTION_DELETE,
    MTA_MENU_OPTION_DELETE_ALL,
    MTA_MENU_OPTION_NEW,

    /*e_Editor_OPTION */
    MTA_EDITOR_OPTION_START,
    MTA_EDITOR_SAVE=MTA_EDITOR_OPTION_START,
    MTA_EDITOR_INPUT_MENU,

    /*e_CREATE_MSG_OPTION */
    MTA_MENU_CREATE_OPTION_START,
    MTA_MENU_CREATE_SMS=MTA_MENU_CREATE_OPTION_START,
    MTA_MENU_CREATE_MMS
/* Binary ID end */
};
#endif /* __MMI_MESSAGETEMPLATEAPP_VIEW_ID_H__ */
