#ifndef __MMI_ONAPPVIEW_ID_H__
#define __MMI_ONAPPVIEW_ID_H__

#include "mae_menulabel.h"
#include "mmi_wdg_image.h"
#include "mae_textlabel.h"
#include "mmi_mae_menumodel.h"
#include "mmi_view_id_range.h"

enum
{
/* View ID start */
	VID_ONAPP_START = MMI_VIEW_ID_AP_BEGIN,
	VID_ONAPP_CHARGING,
	VID_ONAPP_CHARGING_FULL,
	VID_ONAPP_LOGO,
	VID_ONAPP_GREETING,
	VID_ONAPP_POWERONANIM,
	VID_ONAPP_NETWORK,
	VID_ONAPP_EMERGENCYCALL_LIST,
	VID_ONAPP_STANDBYMODE,
	VID_ONAPP_END = 0x1FFF
/* View ID end */
};

enum
{
/* Widget ID start */
  WID_ONAPP_START = 0x2000,
  WID_ONAPP_MAINCONTAINER,
  WID_ONAPP_IMAGEAREA_CONTAINER,
  WID_ONAPP_CHARGING,
  WID_ONAPP_CHARGING_IMAGE,
  WID_ONAPP_CHARGING_FULL,
  WID_ONAPP_CHARGING_FULL_IMAGE,
  WID_ONAPP_LOGO,
  WID_ONAPP_LOGO_IMAGE,
  WID_ONAPP_GREETING,
  WID_ONAPP_GREETING_IMAGE,
  WID_ONAPP_POWERONANIM,
  WID_ONAPP_POWERONANIM_CONTAINER,
  WID_ONAPP_POWERONANIM_IMAGE,
  WID_ONAPP_NETWORK,
  WID_ONAPP_NETWORK_IMAGE,
  WID_ONAPP_TITLEWIDGET,
  WID_ONAPP_MENUWIDGET,
  WID_ONAPP_END = 0x2FFF
/* Widget ID end */
};

#endif /* __MMI_ONAPPVIEW_ID_H__ */
