////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// User Code Begin:APP:INFO
// User Code End

#ifndef __MMI_QQAPP_ID_H__
#define __MMI_QQAPP_ID_H__

#ifndef __NCCQQ_MMI_TEST_STUB__
#define __NCCQQ_MMI_TEST_STUB__
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef enum
{
    QQ_WND_LOADING_BEGIN = APP_WDG_START,
    QQ_WND_LOADING_IMAGE,
    QQ_WND_LOADING_END
}QQAppQQ_WND_LOADING_e;

typedef enum
{
    QQ_WND_LOGIN_BEGIN = APP_WDG_START,
    QQ_WND_LOGIN_ID_TXT_WDG,
    QQ_WND_LOGIN_ID_INPUT_WDG,
    QQ_WND_LOGIN_ID_HISTORY_WDG,
    QQ_WND_LOGIN_PSW_TXT_WDG,
    QQ_WND_LOGIN_PSW_INPUT_WDG,
    QQ_WND_LOGIN_REM_PSW_SWITCH_ICON,
    QQ_WND_LOGIN_REM_PSW_TXT_WDG,
    QQ_WND_LOGIN_RECV_GROUP_MSG_SWITCH_ICON,
    QQ_WND_LOGIN_RECV_GROUP_MSG_TXT_WDG,
    QQ_WND_LOGIN_HIDE_LOGIN_SWITCH_ICON,
    QQ_WND_LOGIN_HIDE_LOGIN_TXT_WDG,
    QQ_WND_LOGIN_VIBRATE_ON_SWITCH_ICON,
    QQ_WND_LOGIN_VIBRATE_ON_TXT_WDG,
    QQ_WND_LOGIN_SOUND_ON_SWITCH_ICON,
    QQ_WND_LOGIN_SOUND_ON_TXT_WDG,
    QQ_WND_LOGIN_END
}QQAppQQ_WND_LOGIN_e;

typedef enum
{
    QQ_WND_LOGIN_OPTIONMENU_BEGIN = APP_WDG_START,
    vtm_QQ_WND_LOGIN_OPTIONMENU,
    QQ_WND_LOGIN_OPTIONMENU_END
}QQAppQQ_WND_LOGIN_OPTIONMENU_e;

typedef enum
{
    QQ_WND_OPERATE_CMD_BEGIN = APP_WDG_START,
    QQ_WND_OPERATE_CMD_INPUT_TEXT,
    QQ_WND_OPERATE_CMD_END
}QQAppQQ_WND_OPERATE_CMD_e;

typedef enum
{
    QQ_WND_LOGINING_BEGIN = APP_WDG_START,
    QQ_WND_LOGINING_IMAGE,
    QQ_WND_LOGINING_END
}QQAppQQ_WND_LOGINING_e;

typedef enum
{
    QQ_WND_VERIFY_BEGIN = APP_WDG_START,
    QQ_WND_VERIFY_SHOWINFO_TEXT,
    QQ_WND_VERIFY_IMAGE,
    QQ_WND_VERIFY_INPUT_TEXT,
    QQ_WND_VERIFY_END
}QQAppQQ_WND_VERIFY_e;

typedef enum
{
    QQ_WND_SHOWLIST_BEGIN = APP_WDG_START,
    QQ_WND_TAB_MENU,
    QQ_IMG_WDG_MSG_ICON,
    QQ_WND_SHOWLIST_END
}QQAppQQ_WND_SHOWLIST_e;

typedef enum
{
    MENU_QQAPP_OPT_LOGIN = 0,
    MENU_QQAPP_OPT_HELP,
    MENU_QQAPP_OPT_CLEAN_LOGIN_INFO,
    MENU_QQAPP_OPT_EXIT
}QQLoginWndOptionMenuId_e;

typedef enum
{
    QQ_WND_READMESSAGE_BEGIN = 0,
    QQ_WND_READMESSAGE_SHOW_RECEIVED_INPUT,
    QQ_WND_READMESSAGE_END
}QQAppQQ_WND_READMESSAGE_e;

typedef enum
{
    QQ_MAINMENU_MENU_SEND_MESSAGE = 0,
    QQ_MAINMENU_MENU_EXPAND_GROUP,
    QQ_MAINMENU_MENU_CLOSE_GROUP,
    QQ_MAINMENU_MENU_USER_INFO,
    QQ_MAINMENU_MENU_MESSAGE_HISTROY,
    QQ_MAINMENU_MENU_FRIENDS_ADMIN,
    QQ_MAINMENU_MENU_SHOW_ALL_CONTACTS,
    QQ_MAINMENU_MENU_SHOW_ONLINE_CONTACTS_ONLY,
    QQ_MAINMENU_MENU_ADD_BUDDY,
    QQ_MAINMENU_MENU_SETTING,
    QQ_MAINMENU_MENU_HELP,
    QQ_MAINMENU_MENU_LOGIN,
    QQ_MAINMENU_MENU_LOGOUT,
    QQ_MAINMENU_MENU_EXIT,
    QQ_MAINMENU_MENU_DELETE_FRIEND,
    QQ_MAINMENU_MENU_MOVE_TO_BLACKLIST
}QQMainMenuId_e;

typedef enum
{
    QQ_WND_SENDMESSAGE_BEGIN = APP_WDG_START,
    QQ_WND_SENDMESSAGE_INPUT_TEXT,
    QQ_WND_SENDMESSAGE_END
}QQSendMessageId_e;

typedef enum
{
    SENDMESSAGE_MENU_QQAPP_OPT_SEND = 0,
#ifdef QQ_SEND_MESSAGE_INSERT_FACE
    SENDMESSAGE_MENU_QQAPP_OPT_INSERT_FACE,
#endif // #ifdef QQ_SEND_MESSAGE_INSERT_FACE
    SENDMESSAGE_MENU_QQAPP_OPT_INSERT_PRESET_MESSAGE
}QQSendMessageLOGIN_OPTIONMENUId_e;

typedef enum
{
    SENDMESSAGE_MENU_PRESET_MESSAGE1 = 0,
    SENDMESSAGE_MENU_PRESET_MESSAGE2,
    SENDMESSAGE_MENU_PRESET_MESSAGE3,
    SENDMESSAGE_MENU_PRESET_MESSAGE4,
    SENDMESSAGE_MENU_PRESET_MESSAGE5,
    SENDMESSAGE_MENU_PRESET_MESSAGE6,
    SENDMESSAGE_MENU_PRESET_MESSAGE7
}QQSendMessagePresetMessageId_e;

typedef enum
{
    QQ_WND_USER_INFO_BEGIN = APP_WDG_START,
    QQ_WND_USER_INFO_SHOW_USER_INFO_INPUT,
    QQ_WND_USER_INFO_END
}QQUserInfoId_e;

typedef enum
{
   QQ_WND_MESSAGE_HISTORY_BEGIN = APP_WDG_START,
   QQ_WND_MESSAGE_HISTORY_SHOW_MESSAGE_HISTORY_INPUT,
   QQ_WND_MESSAGE_HISTORY_END
}QQ_WND_MESSAGE_HISTORY_e;

typedef enum
{
    MENU_QQAPP_OPT_MESSAGE_HISTORY_FIRST_PAGE,
    MENU_QQAPP_OPT_MESSAGE_HISTORY_LAST_PAGE,
    MENU_QQAPP_OPT_MESSAGE_HISTORY_FRONT_PAGE,
    MENU_QQAPP_OPT_MESSAGE_HISTORY_NEXT_PAGE,
}QQMessageHistoryOptionMenu_e;

typedef enum
{
    QQ_WND_ADD_BUDDY_BEGIN = APP_WDG_START,
    QQ_WND_ADD_BUDDY_ID_TEXT,
    QQ_WND_ADD_BUDDY_INPUT_ID,
    QQ_WND_ADD_BUDDY_END
}QQAppQQ_WND_ADD_BUDDY_e;

typedef enum
{
    QQ_WND_SEARCH_RESULT_OPTIONMENU_BEGIN = APP_WDG_START,
    vtm_QQ_WND_SEARCH_RESULT_OPTIONMENU,
    QQ_WND_SEARCH_RESULT_OPTIONMENU_END
}QQAppQQ_WND_SEARCH_RESULT_OPTIONMENU_e;

typedef enum
{
    MENU_QQAPP_OPT_VIEW_USER_INFO = 0,
    MENU_QQAPP_OPT_ADD_FRIEND
}QQSearchResultWndOptionMenuId_e;

typedef enum
{
    QQ_WND_SETTING_MYSTATUS_MENU = 0,
    QQ_WND_SETTING_SOUND_MENU,
    QQ_WND_SETTING_VIBRATE_MENU,
    QQ_WND_SETTING_GROUP_MSG_SETTINGS_MENU,
    QQ_WND_SETTING_DEL_MSG_HISTORY_MENU,
}BASIC_SETTING_Id_e;

typedef enum
{
    QQ_WND_ADD_BUDDY_OPT_MENU_ACCEPT = 0,
    QQ_WND_ADD_BUDDY_OPT_MENU_ACCEPT_AND_ADD_AS_BUDDY,
    QQ_WND_ADD_BUDDY_OPT_MENU_DECLINE
} QQAddBuddyOptMenuID_e;

typedef enum
{
    POPUPSELECT_TYPE_STATUS = 0,
    POPUPSELECT_TYPE_SOUND,
    POPUPSELECT_TYPE_VIBRATE,
    POPUPSELECT_TYPE_GROUP_MSG_SETTINGS,
    POPUPSELECT_TYPE_ID_HISTORY,
    POPUPSELECT_TYPE_ID_ENDKEY,
}QQAppQQ_WND_POPUPSELECT_TYPE_e;

typedef enum
{
    QQ_WND_ANSWER_QUESTION_BEGIN = APP_WDG_START,
    QQ_WND_ANSWER_QUESTION_NUMBER_TEXT,
    QQ_WND_ANSWER_QUESTION_QUESTION_TEXT,
    QQ_WND_ANSWER_QUESTION_ANSWER_INPUT,
    QQ_WND_ANSWER_QUESTION_END
}QQAppQQ_WND_ANSWER_QUESTION_e;

typedef enum
{
    QQ_WND_LOADING = WND_ID_APP_BASE,
    QQ_WND_DUALSIM,
    QQ_WND_LOGIN,
    QQ_WND_LOGIN_OPTIONMENU,
    QQ_WND_OPERATE_CMD,
    QQ_WND_VERIFY,
    QQ_WND_LOGINING,
    QQ_WND_SHOWLIST,
    QQ_WND_READMESSAGE,
    QQ_WND_MAINMENU,
    QQ_WND_SENDMESSAGE,
    QQ_WND_SENDMESSAGE_OPTIONMENU,
    QQ_WND_PRESET_MESSAGE,
    QQ_WND_USER_INFO,
    QQ_WND_MESSAGE_HISTORY,
    QQ_WND_MESSAGE_HISTORY_OPTIONMENU,
    QQ_WND_ADD_BUDDY,
    QQ_WND_POPUPSELECT,
    QQ_WND_SETTING,
    QQ_WND_ANSWER_QUESTION,
    QQ_WND_ADD_BUDDY_OPTIONMENU,
}QQAppId_e;

typedef enum
{
    WID_QQ_FRIEND_LIST = 0,
    WID_QQ_GROUP_LIST,
#ifdef  __MULTIPLE_QQ__
    WID_QQ_ACCOUNT_LIST
#endif
}QQAppShowListWID_e;

#ifdef __cplusplus
}
#endif

#endif /* __MMI_QQAPP_ID_H__ */

