#ifndef __MMI_COMMON_SETTING_TYPE_H__
#define __MMI_COMMON_SETTING_TYPE_H__

#include "mmi_mae_common_def.h"
/*
 * Data type definition of settingapp that is used by other libraries
 * */

 typedef enum
{
  SETTINGAPType_Normal = 0,     /* unknown reason. */
  SETTINGAPType_DateTime,
  SETTINGAPType_Time,
  SETTINGAPType_AutoOnOff,
  SETTINGAPType_PhoneSettings,
  SETTINGAPType_DisplaySettings,
  SETTINGAPType_RingtoneSettings,
  SETTINGAPType_CallSettings,
  SETTINGAPType_ConnectSettings,
  SETTINGAPType_NetworkSettings,
  SETTINGAPType_Security,
#ifdef __DUAL_CAMERA_MMI__
  SETTINGAPType_CameraType,
#endif
#ifdef __SCREEN_EFFECTS_SUPPORT__
  SETTINGAPType_ScreenEffect_Type,
#endif  
  SETTINGAPType_Wallpaper3DEffect,
  SETTINGAPType_IdleWallpaper3DEffect,
  SETTINGAPType_END = (s32) 0xFFFFFFFF
} SettingAppApStartType_e;  /* All start reasons for launching EM AP */

typedef enum
{
	MNU_SETTING_PERSONALIZATION=0,
	MNU_SETTING_PERSONALIZATION_DISPLAY,
	MNU_SETTING_PERSONALIZATION_STANDBY_MODE,
	MNU_SETTING_PERSONALIZATION_RINGTONE_SETTINGS,
	MNU_SETTING_PERSONALIZATION_LANGUAGE,
//#ifdef __BREATHLIGHT_MMI__
	MNU_SETTING_PERSONALIZATION_BREATHLIGHT,
//#endif
//#ifdef __MULTI_THEMES_ENABLED__
	MNU_SETTING_CHANGE_THEME_STYLE,
//#endif
	MNU_SETTING_ENGLISH,
	MNU_SETTING_SIMPLE_CHINESE,
	MNU_SETTING_TRADITIONAL_CHINESE,
	MNU_SETTING_CHOOSE_DEFAULT,
	MNU_SETTING_AVAILABLE_LIST,
	MNU_SETTING_DATE_TIME,
	MNU_SETTING_TIME_ZONE,
	MNU_SETTING_SECOND_TIME_ZONE,
	MNU_SETTING_AUTOMATIC_UPDATE_ON,
	MNU_SETTING_AUTOMATIC_UPDATE_OFF,
	MNU_SETTING_AUTOMATIC_UPDATE_CONFIRM_FIRST,
	MNU_SETTING_DATE_FORMAT_YYYYMMDD,
	MNU_SETTING_DATE_FORMAT_DDMMYYYY,
	MNU_SETTING_DATE_FORMAT_MMDDYYYY,
	MNU_SETTING_DATE_FORMAT_WKMMDD,
	MNU_SETTING_DATE_FORMAT_DDMMWK,
	MNU_SETTING_DATE_FORMAT_MMDDWK,
	MNU_SETTING_TIME_FORMAT_12_HOURS,
	MNU_SETTING_TIME_FORMAT_24_HOURS,
	MNU_SETTING_POWER_ON_OFF,
	MNU_SETTING_AUTO_ON_OFF,
	MNU_SETTING_AUTO_POWER_ON,
	MNU_SETTING_AUTO_POWER_OFF,
	MNU_SETTING_INFORMATION,
	MNU_SETTING_IMEI,
	MNU_SETTING_MEMORY_DETAILS,
	MNU_SETTING_SOFTWARE_VERSION,
	MNU_SETTING_CALIBRATION,
	MNU_SETTING_MASTER_SIM,
	MNU_SETTING_SLAVE_SIM,
	MNU_SETTING_RESTORE_SETTINGS,
	MNU_SETTING_STYLE_1,
	MNU_SETTING_STYLE_2,
	MNU_SETTING_IDLE_SCREEN,
	MNU_SETTING_BACKLIGHT_DURATION_ALWAYS_ON,
	MNU_SETTING_BACKLIGHT_DURATION_5_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_10_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_15_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_20_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_25_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_30_SECONDS,
	MNU_SETTING_BACKLIGHT_DURATION_60_SECONDS,
	MNU_SETTING_MAIN_MENU_STYLE,
	MNU_SETTING_TRANSITION,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_2DFLIP,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_3DFLIP,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_DESTRUCT,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_LIQUID,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_NONE,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_RANDOM,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_ROTATE,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_SLIDE,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_SPLIT,
	MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_ZOOM,
	MNU_SETTING_DATA_ACCOUNTS,
	MNU_SETTING_WAP_SETTINGS,
	MNU_SETTING_MMS_SETTINGS,
	MNU_SETTING_JAVA_SETTINGS,
	MNU_SETTING_MMTV_SETTINGS,
	MNU_SETTING_IPTV_SETTINGS,
	MNU_SETTING_LBS_SETTINGS,
	MNU_SETTING_WLAN_SETTINGS,
	MNU_SETTING_EMAIL_SETTINGS,
    MNU_SETTING_QQ_SETTINGS,   
    MNU_SETTING_STREAMING_SETTINGS,
	MNU_SETTING_NTP_SETTINGS,
    MNU_SETTING_NETWORK_COUNTER,    
	MNU_SETTING_THEME,
	MNU_SETTIMG_THEME_OPT_INSTALL,
	MNU_SETTIMG_THEME_OPT_PREVIEW,
	MNU_SETTIMG_THEME_OPT_DELETE,
	MNU_SETTIMG_THEME_OPT_EXPORTUSEDTHEME,
	MNU_SETTING_OTHER_SETTINGS,
	MNU_SETTING_POWER_SWITCH_SETTINGS,
    MNU_SETTING_POWER_SWITCH_BATTERY_MASTER,
 //#ifdef __G_SENSOR_MMI__
	MNU_SETTING_GSENSOR,
    MNU_SETTING_GSENSOR_WND_AUTOROTATE,
	MNU_SETTING_GSENSOR_SHAKE_WALLPAPER,
	MNU_SETTING_GSENSOR_SHAKE_SONG,
	MNU_SETTING_GSENSOR_CHANGE_PICTURE,
	MNU_SETTING_GSENSOR_ROTATE_PICTURE,
	MNU_SETTING_GSENSOR_FLIP_SILENT,
//#endif
#ifdef __APP_MMI_SOHU_UPDATER__
    MNU_SETTING_SOHU_UPDATER,
#endif

    MNU_SETTING_POWER_SWITCH_BATTERY_SLAVE,
#ifdef __LIVE_WALLPAPER__
    MNU_SETTING_WALLPAPER_3D_EFFECT_SNAKELINE,
    MNU_SETTING_WALLPAPER_3D_EFFECT_COMET,
    MNU_SETTING_WALLPAPER_3D_EFFECT_EARTHROT,
    MNU_SETTING_WALLPAPER_3D_EFFECT_FALLSNOW,
    MNU_SETTING_WALLPAPER_3D_EFFECT_FLUTTERSNOW,
    MNU_SETTING_WALLPAPER_3D_EFFECT_FISH,
    MNU_SETTING_WALLPAPER_3D_EFFECT_SEASHORE,
    MNU_SETTING_WALLPAPER_3D_EFFECT_SOLARSYSTEM,
    MNU_SETTING_WALLPAPER_3D_EFFECT_JUMPGATE,
    MNU_SETTING_WALLPAPER_3D_EFFECT_WEATHER,
    MNU_SETTING_WALLPAPER_3D_EFFECT_GRASSTRACE,
	MNU_SETTING_WALLPAPER_3D_EFFECT_FARM,
	MNU_SETTING_WALLPAPER_3D_EFFECT_BIRD,
	MNU_SETTING_WALLPAPER_3D_EFFECT_DROPLET,	
	MNU_SETTING_WALLPAPER_3D_EFFECT_INWATER,
	MNU_SETTING_WALLPAPER_3D_EFFECT_INWATERSHOOT,	
    MNU_SETTING_WALLPAPER_3D_EFFECT_IMAGE,

    MNU_SETTING_WALLPAPER_OPTION_SELECT,
    MNU_SETTING_WALLPAPER_OPTION_EDIT,
#endif

	MNU_SETTING_SCREEN_SAVER,
	MNU_SETTING_SCREEN_SAVER_STATUS,
	MNU_SETTING_SCREEN_SAVER_3D_EFFECT,
	MNU_SETTING_SCREEN_SAVER_DURATION,
	MNU_SETTING_SCREEN_SAVER_DURATION_5_SECONDS,
	MNU_SETTING_SCREEN_SAVER_DURATION_15_SECONDS,
	MNU_SETTING_SCREEN_SAVER_DURATION_30_SECONDS,
	MNU_SETTING_SCREEN_SAVER_DURATION_60_SECONDS,
	MNU_SETTING_SCREEN_SAVER_DISPLAY,

    MNU_SETTING_FONT_STYLE,

    MNU_SETTING_NONE,
}SettingMenuId_e;

#endif // __MMI_COMMON_SETTING_TYPE_H__
