
#ifndef __MMI_COMMONPOPUP_ID_H__
#define __MMI_COMMONPOPUP_ID_H__

enum
{
/* Widget ID start */
	COMMON_POPUPSELECT_WIDGET = 0,
	COMMON_POPUP_PROPCONTAINER,
	COMMON_POPUP_PADDING_ABSCONTAINER,
	COMMON_POPUP_ABSCONTAINER,
	COMMON_POPUP_TITLEWIDGET,
	COMMON_POPUP_TITLE_TEXTWIDGET,
	COMMON_POPUP_INFO_TEXTWIDGET,
	COMMON_POPUP_INPUTWIDGET,
	COMMON_POPUP_IPWIDGET,
	COMMON_POPUP_SCROLLBARWDG,
	COMMON_POPUP_FADEOUTWIDGET,
	COMMON_POPUP_INPUT_BG_IMAGEWIDGET,
	COMMON_POPUP_BG_IMAGEWIDGET,
	COMMON_POPUP_VIEWPORTWIDGET,
	COMMON_POPUP_IMG_TEXT_CONTAINER,
	COMMON_POPUP_IMG_ABSCONTAINER,
	COMMON_POPUP_INPUT_TITLE_IMG_WIDGET
/* Widget ID end */
};

#endif /* __MMI_COMMONPOPUP_ID_H__ */
