#ifndef _MMI_COMMON_THMID_H_
#define _MMI_COMMON_THMID_H_

#include "img_data.h"


#ifdef __APP_MMI_SMALLROM__
#define __MAINMENUAPP_SMALLROM__
#endif	// __APP_MMI_SMALLROM__


#define THM_COMMON_IMG_LIST_INFO_BG        		COMMON_IMG_LIST_INFO_BG
#define THM_COMMON_IMG_LIST_INFO_TWO_LINES_BG   COMMON_IMG_LIST_INFO_TWO_LINES_BG
#define THM_COMMON_IMG_LIST_SEL_1        		COMMON_IMG_LIST_SEL_1
#define THM_COMMON_IMG_LIST_SEL_2        		COMMON_IMG_LIST_SEL_2
#define THM_COMMON_IMG_LIST_TITLE_BG        	COMMON_IMG_LIST_TITLE_BG
#define THM_COMMON_IMG_LIST_TITLE_TWO_LINES_BG  COMMON_IMG_LIST_TITLE_TWO_LINE_BG
#ifndef __SMALL_ROM_32__
#define THM_COMMON_IMG_OPTION_BG        		COMMON_IMG_OPTION_BG
#define THM_COMMON_IMG_OPTION_SUB_BG        	COMMON_IMG_OPTION_SUB_BG
#endif  //__SMALL_ROM_32__
#define THM_COMMON_IMG_POPUP_THREE_LINE_BG      COMMON_IMG_POPUP_THREE_LINE_BG
#define THM_COMMON_IMG_SCROLL_BG_CENTER        	COMMON_IMG_SCROLL_BG_CENTER
#define THM_COMMON_IMG_SCROLL_BG_DOWN        	COMMON_IMG_SCROLL_BG_DOWN
#define THM_COMMON_IMG_SCROLL_BG_UP        		COMMON_IMG_SCROLL_BG_UP
#define THM_COMMON_IMG_SCROLL_CENTER        	COMMON_IMG_SCROLL_CENTER
#define THM_COMMON_IMG_SCROLL_CENTER_BG        	COMMON_IMG_SCROLL_CENTER_BG
#define THM_COMMON_IMG_SCROLL_DOWN        		COMMON_IMG_SCROLL_DOWN
#define THM_COMMON_IMG_SCROLL_DOWN_PRESSED      COMMON_IMG_SCROLL_DOWN_PRESSED
#define THM_COMMON_IMG_SCROLL_DOWN_UNPRESSED    COMMON_IMG_SCROLL_DOWN_UNPRESSED
#define THM_COMMON_IMG_SCROLL_UP        		COMMON_IMG_SCROLL_UP
#define THM_COMMON_IMG_SCROLL_UP_PRESSED        COMMON_IMG_SCROLL_UP_PRESSED
#define THM_COMMON_IMG_SCROLL_UP_UNPRESSED      COMMON_IMG_SCROLL_UP_UNPRESSED
#define THM_COMMON_IMG_SOFTKEY_BG        		COMMON_IMG_SOFTKEY_BG
#define THM_COMMON_IMG_SOFTKEY_C_PRESSED        COMMON_IMG_SOFTKEY_C_PRESSED
#define THM_COMMON_IMG_SOFTKEY_LR_PRESSED       COMMON_IMG_SOFTKEY_LR_PRESSED
#define THM_COMMON_IMG_SYSTEM_BG        		COMMON_IMG_SYSTEM_BG
#define THM_COMMON_IMG_TAB_BG        			COMMON_IMG_TAB_BG
#define THM_COMMON_IMG_TAB_BG_ACT        		COMMON_IMG_TAB_BG_ACT
#define THM_COMMON_IMG_TAB_BG_INACT        		COMMON_IMG_TAB_BG_INACT
#define THM_IDLE_IMG_BG        					IDLE_IMG_BG
#define THM_MAINMENU_IMG_BG        				MAINMENU_IMG_BG
#ifdef __MAINMENUAPP_SMALLROM__
#define THM_MAINMENU_IMG_GRID_FOCUS_01        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_02        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_03        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_04        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_05        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_06        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_07        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_08        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_09        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_10        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_11        MAINMENU_IMG_GRID_FOCUS
#define THM_MAINMENU_IMG_GRID_FOCUS_12        MAINMENU_IMG_GRID_FOCUS
#else	// !__MAINMENUAPP_SMALLROM__
#define THM_MAINMENU_IMG_GRID_FOCUS_01        MAINMENU_IMG_GRID_FOCUS_01
#define THM_MAINMENU_IMG_GRID_FOCUS_02        MAINMENU_IMG_GRID_FOCUS_02
#define THM_MAINMENU_IMG_GRID_FOCUS_03        MAINMENU_IMG_GRID_FOCUS_03
#define THM_MAINMENU_IMG_GRID_FOCUS_04        MAINMENU_IMG_GRID_FOCUS_04
#ifdef __MMI_KING_MOVIE__
#define THM_MAINMENU_IMG_GRID_FOCUS_05        MAINMENU_IMG_GRID_FOCUS_KM_05
#define THM_MAINMENU_IMG_GRID_FOCUS_06        MAINMENU_IMG_GRID_FOCUS_KM_06
#else
#define THM_MAINMENU_IMG_GRID_FOCUS_05        MAINMENU_IMG_GRID_FOCUS_05
#define THM_MAINMENU_IMG_GRID_FOCUS_06        MAINMENU_IMG_GRID_FOCUS_06
#endif
#define THM_MAINMENU_IMG_GRID_FOCUS_07        MAINMENU_IMG_GRID_FOCUS_07
#define THM_MAINMENU_IMG_GRID_FOCUS_08        MAINMENU_IMG_GRID_FOCUS_08
#define THM_MAINMENU_IMG_GRID_FOCUS_09        MAINMENU_IMG_GRID_FOCUS_09
#define THM_MAINMENU_IMG_GRID_FOCUS_10        MAINMENU_IMG_GRID_FOCUS_10
#define THM_MAINMENU_IMG_GRID_FOCUS_11        MAINMENU_IMG_GRID_FOCUS_11
#define THM_MAINMENU_IMG_GRID_FOCUS_12        MAINMENU_IMG_GRID_FOCUS_12
#endif	// !__MAINMENUAPP_SMALLROM__
#ifdef __USER_DEFINE_MAINMENU_VIDEO__
#define THM_MAINMENU_IMG_DEFAULT_BG           MAINMENU_IMG_DEFAULT_BG
#define THM_MAINMENU_IMG_UNSUPPORTED_BG       IMG_UNSUPPORTED_IMG
#endif
#define THM_NOTICE_IMG_BG        NOTICE_IMG_BG
#define THM_NOTICE_IMG_PROGRESS        NOTICE_IMG_PROGRESS
#define THM_NOTICE_IMG_PROGRESS_BG        NOTICE_IMG_PROGRESS_BG
#define THM_STATUSBAR_IMG_BG        STATUSBAR_IMG_BG

#endif /* _MMI_COMMON_THMID_H_ */
