/**
 * @file    mmi_common_hotkey_def.h
 * @brief   The document describes the hotkey definitions
 *
 */

#ifndef __MMI_COMMON_HOTKEY_DEF_H__
#define __MMI_COMMON_HOTKEY_DEF_H__

#include "mmi_mae_common_def.h"
#include "mmi_class.h"
#include "mmi_coresrv.h"

/**
 * Here lists all hotkey definitions
 * The Max. number of hotkey supported here is 16.
 */
#define HOTKEY_LONGPRESS_START      (16)
#define HOTKEY_DISABLE_ALL          (0)

#define HOTKEY_POWERMODE            (1 << CORESRV_LAUNCH_FUNC_POWERMODE)
#define HOTKEY_CAMERA               (1 << CORESRV_LAUNCH_FUNC_CAMERA)
#define HOTKEY_MP3                  (1 << CORESRV_LAUNCH_FUNC_MP3)
#define HOTKEY_FM                   (1 << CORESRV_LAUNCH_FUNC_FM)
#define HOTKEY_MSG                  (1 << CORESRV_LAUNCH_FUNC_MSG)
#define HOTKEY_MAIL                 (1 << CORESRV_LAUNCH_FUNC_MAIL)
#define HOTKEY_ATV                  (1 << CORESRV_LAUNCH_FUNC_ATV)
#define HOTKEY_AUTO_KEYGUARD        (1 << CORESRV_LAUNCH_FUNC_AUTO_KEYGUARD)
#define HOTKEY_SCREENSAVER          (1 << CORESRV_LAUNCH_FUNC_SCREENSAVER)

#define HOTKEY_LONGPRESS_POWERMODE  (HOTKEY_POWERMODE | (HOTKEY_POWERMODE << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_CAMERA     (HOTKEY_CAMERA | (HOTKEY_CAMERA << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_MP3        (HOTKEY_MP3 | (HOTKEY_MP3 << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_FM         (HOTKEY_FM | (HOTKEY_FM << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_MSG        (HOTKEY_MSG | (HOTKEY_MSG << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_MAIL       (HOTKEY_MAIL | (HOTKEY_MAIL << HOTKEY_LONGPRESS_START))
#define HOTKEY_LONGPRESS_ATV        (HOTKEY_ATV | (HOTKEY_ATV << HOTKEY_LONGPRESS_START))

#define HOTKEY_ENABLE_ALL           (0xFFFFFFFF)

typedef struct
{
    MAE_ClsId   nClsId;
    u32         nEnabledHotkey;
}HotkeyMapping_t;

#define AUTOTESTAPP_HOTKEY      (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define CAMAPP_HOTKEY           (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define CCAPP_HOTKEY            (HOTKEY_DISABLE_ALL)
#define CCMTA_HOTKEY            (HOTKEY_DISABLE_ALL)
#define CDWAPAPP_HOTKEY         (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define EMUAPP_HOTKEY           (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define E_BOOK_HOTKEY           (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define FMRADIOAPP_HOTKEY       (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define IDLEAPP_HOTKEY          (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_MP3|HOTKEY_FM|HOTKEY_MSG|HOTKEY_MAIL|HOTKEY_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define JAVAAPP_HOTKEY          (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#ifdef __APP_MMI_SCREENSAVER__
#define KEYGUARDAPP_HOTKEY      (HOTKEY_SCREENSAVER) // allow screen saver only
#define SCREENSAVER_HOTKEY      (HOTKEY_DISABLE_ALL) // avoid to launch itself
#else
#define KEYGUARDAPP_HOTKEY      (HOTKEY_DISABLE_ALL) // avoid to launch itself
#endif
#define MAINMENUAPP_HOTKEY      (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_MP3|HOTKEY_FM|HOTKEY_MSG|HOTKEY_MAIL|HOTKEY_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define MAPAPP_HOTKEY           (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define MCA_HOTKEY              (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define MPLAYERAPP_HOTKEY       (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#define NATIVEGAME_HOTKEY       (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#define OFFAPP_HOTKEY           (HOTKEY_DISABLE_ALL)
#define ONAPP_HOTKEY            (HOTKEY_DISABLE_ALL)

#ifdef __SXMENGINE__
#define VEN_VCHAT_HOTKEY          (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#endif
#ifdef __ZMOL__
#define VEN_ZMOL_HOTKEY          (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV)
#endif
#define DEFAULT_HOTKEY          (HOTKEY_LONGPRESS_POWERMODE|HOTKEY_LONGPRESS_CAMERA|HOTKEY_LONGPRESS_MP3|HOTKEY_LONGPRESS_FM|HOTKEY_LONGPRESS_MSG|HOTKEY_LONGPRESS_MAIL|HOTKEY_LONGPRESS_ATV|HOTKEY_AUTO_KEYGUARD|HOTKEY_SCREENSAVER)
#endif /* __MMI_COMMON_HOTKEY_DEF_H__ */

