/**
 * @file    mmi_common_transition.h
 * @brief   
 * @author  
 * @version $Id: mmi_common_transition.h 37859 2009-08-14 10:27:23Z lena.lin $
 */

#ifndef __MMI_COMMON_TRANSITION_H__
#define __MMI_COMMON_TRANSITION_H__

#include "mmi_mae_transition.h"
#include "mmi_mae_view_defines.h"

#define MMI_VIEWTRANSITION_CAT_NORMAL_MAX     0x00ffffff
#define MMI_VIEWTRANSITION_CAT_MENU_START     0x01000000

#define VIEWTRANSITION_ID_NONE    0
#define VIEWTRANSITION_ID_START  1

typedef enum
{
	MMI_VIEWTRANSITION_NONE         = VIEWTRANSITION_ID_NONE,       ///< no transition
	MMI_VIEWTRANSITION_FULLSCR_LEFT = VIEWTRANSITION_ID_START,      ///< push right
	MMI_VIEWTRANSITION_FULLSCR_RIGHT,               ///< push right
	MMI_VIEWTRANSITION_FULLSCR_UP,                  ///< push up
	MMI_VIEWTRANSITION_FULLSCR_DOWN,                ///< push down
	MMI_VIEWTRANSITION_FULLSCR_ROLLING_LEFT,        ///< rolling left
	MMI_VIEWTRANSITION_FULLSCR_ROLLING_RIGHT,       ///< rolling right
	MMI_VIEWTRANSITION_FULLSCR_ROLLING_UP,          ///< rolling up
	MMI_VIEWTRANSITION_FULLSCR_ROLLING_DOWN,        ///< rolling down

	MMI_VIEWTRANSITION_FULLSCR_REND,
    MMI_VIEWTRANSITION_FULLSCR_DOOR_IN,
    MMI_VIEWTRANSITION_FULLSCR_DOOR_OUT,
    
	MMI_VIEWTRANSITION_FULLSCR_ZOOM_IN,             ///< zoom in
	MMI_VIEWTRANSITION_FULLSCR_ZOOM_OUT,            ///< zoom out
	MMI_VIEWTRANSITION_MPLAYER_FLIPOVER_LEFT,       ///< flip over left, full screen except softkey
	MMI_VIEWTRANSITION_MPLAYER_FLIPOVER_RIGHT,      ///< flip over right, full screen except softkey
	MMI_VIEWTRANSITION_FULLSCR_FLIPOVER_LEFT,  
	MMI_VIEWTRANSITION_FULLSCR_FLIPOVER_RIGHT, 
	MMI_VIEWTRANSITION_CALENDAR_FLIPPAPER,          ///< flip paper, full screen except softkey
	MMI_VIEWTRANSITION_CALENDAR_FLIPPAPER_LEFT,          ///< flip paper, full screen except softkey

	// main screen type transition start, only transition the content of two window, background is invariable
	MMI_VIEWTRANSITION_TRANSLUCENT_TYPE_START,
	MMI_VIEWTRANSITION_TRANSLUCENT_UP = MMI_VIEWTRANSITION_TRANSLUCENT_TYPE_START,			// push up
	MMI_VIEWTRANSITION_TRANSLUCENT_DOWN,			// push down
	MMI_VIEWTRANSITION_TRANSLUCENT_LEFT,			// push left
	MMI_VIEWTRANSITION_TRANSLUCENT_RIGHT,			// push right
	MMI_VIEWTRANSITION_TRANSLUCENT_FADEOUT_UP,			// push up and fade out old frame
	MMI_VIEWTRANSITION_TRANSLUCENT_FADEOUT_DOWN,			// push down and fade out old frame
	MMI_VIEWTRANSITION_TRANSLUCENT_FADEOUT_LEFT,			// push left and fade out old frame
	MMI_VIEWTRANSITION_TRANSLUCENT_FADEOUT_RIGHT,			// push right and fade out old frame
	MMI_VIEWTRANSITION_TRANSLUCENT_FLIPOVER_UP,			// flip over up
	MMI_VIEWTRANSITION_TRANSLUCENT_FLIPOVER_DOWN,			// flip over down
	MMI_VIEWTRANSITION_TRANSLUCENT_FLIPOVER_LEFT,			// flip over left
	MMI_VIEWTRANSITION_TRANSLUCENT_FLIPOVER_RIGHT,			// flip over right
	MMI_VIEWTRANSITION_TRANSLUCENT_TYPE_END = MMI_VIEWTRANSITION_TRANSLUCENT_FLIPOVER_RIGHT,
	// main screen type transition end

	MMI_VIEWTRANSIION_END = 0x7FFFFFFF              //define as s32 data type
}WndTransitionType_e;

enum
{
	MMI_VIEWSCENELEVEL_NONE	= 0,
	MMI_VIEWSCENELEVEL_1,
	MMI_VIEWSCENELEVEL_2,
	MMI_VIEWSCENELEVEL_3,
	MMI_VIEWSCENELEVEL_4,
	MMI_VIEWSCENELEVEL_5,
};

// This transition id can be turn off by setting of menu transition
enum
{
	MMI_VIEWTRANSITION_MENU_PUSHLEFT = MMI_VIEWTRANSITION_CAT_MENU_START, 
	MMI_VIEWTRANSITION_MENU_PUSHRIGHT, 
	MMI_VIEWTRANSITION_MENU_PUSHDOWN, 
	MMI_VIEWTRANSITION_MENU_PUSHUP, 

    MMI_VIEWTRANSITION_MENU_ROLLINGLEFT, 
    MMI_VIEWTRANSITION_MENU_ROLLINGRIGHT, 
    MMI_VIEWTRANSITION_MENU_ROLLINGDOWN, 
    MMI_VIEWTRANSITION_MENU_ROLLINGUP, 

    MMI_VIEWTRANSITION_MENU_REND,
    MMI_VIEWTRANSITION_MENU_DOOR_IN,
    MMI_VIEWTRANSITION_MENU_DOOR_OUT,

    MMI_VIEWTRANSITION_MENU_MULTIPAGEGRID_EXIT,   //exit mainmenu, enter app.    //for ifone
	MMI_VIEWTRANSITION_MENU_MULTIPAGEGRIN_ENTRY,  //exit app, enter mainmenu.   //for ifone

	MMI_VIEWTRANSITION_CAT_MENU_DUMMY,
	MMI_VIEWTRANSITION_CAT_MENU_END = MMI_VIEWTRANSITION_CAT_MENU_DUMMY-1,
};

/**
** Menu List Transition Type for MainmenuApp and All AP vdf
**
**/
#define MENULIST_ENTRY_TRANSITION_ID				MMI_VIEWTRANSITION_MENU_PUSHLEFT
#define MENULIST_EXIT_TRANSITION_ID					MMI_VIEWTRANSITION_MENU_PUSHRIGHT

#define LAUNCH_SHORTCUTSLIST_ENTRY_TRANSITION_ID	MMI_VIEWTRANSITION_NONE
#define LAUNCH_SHORTCUTSLIST_EXIT_TRANSITION_ID		MMI_VIEWTRANSITION_NONE

#define LAUNCH_NAVIKEY_ENTRY_TRANSITION_ID			MMI_VIEWTRANSITION_NONE
#define LAUNCH_NAVIKEY_EXIT_TRANSITION_ID			MMI_VIEWTRANSITION_NONE

#define LAUNCH_SOFTKEY_ENTRY_TRANSITION_ID			MMI_VIEWTRANSITION_NONE
#define LAUNCH_SOFTKEY_EXIT_TRANSITION_ID			MMI_VIEWTRANSITION_NONE

#define LAUNCH_NUMKEY_ENTRY_TRANSITION_ID			MMI_VIEWTRANSITION_NONE
#define LAUNCH_NUMKEY_EXIT_TRANSITION_ID			MMI_VIEWTRANSITION_NONE

const ViewTransition_t* MMI_Common_Get_Transition_By_ID(u32 id);
boolean MMI_Common_IsTranslucentTypeTransition(u32 nType);

#endif /* __MMI_COMMON_TRANSITION_H__ */

