/**
 *  @file   mmi_common_dialog_id.h
 *  @brief
 *  @version $Id: mmi_common_dialog_id.h 31515 2009-05-20 15:46:16Z lih.wang $
 */

#ifndef __MMI_COMMON_DIALOG_ID_H__
#define __MMI_COMMON_DIALOG_ID_H__

#include "mmi_view_id_range.h"
#include "mmi_common_thmid.h"
#include "mmi_wdg_text.h"
#include "mmi_common_dialog.h"

enum
{
/* View ID start */
	COMMON_DIALOG_NORMALDIALOG = MMI_VIEW_ID_COMMON_BEGIN,
	COMMON_DIALOG_VOLUMEDIALOG,
	COMMON_DIALOG_VOLUMEDIALOG_NEW,
	COMMON_DIALOG_REDIALDIALOG,
	COMMON_DIALOG_WAITINGDIALOG,
	COMMON_DIALOG_PROCESSDIALOG,
	COMMON_DIALOG_INFODIALOG,
	COMMON_DIALOG_CONFIRMDIALOG,
	COMMON_DIALOG_WARNINGDIALOG,
	COMMON_DIALOG_BATTFULLDIALOG,
	COMMON_DIALOG_BATTLOWDIALOG,
	COMMON_DIALOG_BATTCHGDIALOG,
	COMMON_DIALOG_SMSDIALOG,
	COMMON_DIALOG_MMCDIALOG,
	COMMON_DIALOG_MCALLDIALOG,
	COMMON_DIALOG_ALARMDIALOG,
	COMMON_DIALOG_HEADSETDIALOG,
	COMMON_DIALOG_CALLFAILDIALOG,
	COMMON_DIALOG_SIMLOCKDIALOG,
	COMMON_DIALOG_MSGFAILDIALOG,
	COMMON_DIALOG_MSGSUCCDIALOG,
	COMMON_DIALOG_CBDIALOG,
	COMMON_DIALOG_TEXTWDGSLIDEMODE,
#ifdef __APP_MMI_ANSWERING_MACHINE__
	COMMON_DIALOG_VOICEBOXDIALOG,
#endif
#ifdef __NCC_3RD_JAVA_PORTING_LAYER__
    COMMON_DIALOG_WARNINGDIALOG_CONFIRM,
#endif
	COMMON_DIALOG_RECORDINGDIALOG,

	/* Add for New Feature #437 */
	COMMON_DIALOG_BTSTATUSDIALOG,
    COMMON_DIALOG_SMSNOTRECEIVEDDIALOG,
/* View ID end */
};

enum
{
/* Widget ID start */
	COMMON_VOLUMEDIALOG_MAINCONTAINER,
	COMMON_VOLUMEDIALOG_BGWIDGET,
	COMMON_VOLUMEDIALOG_IMAGEWIDGET,
	COMMON_VOLUMEWIDGET,
	COMMON_REDIALDIALOG_MAINCONTAINER,
	COMMON_REDIALDIALOG_IMAGEWIDGET,
	COMMON_REDIALDIALOG_INFOTEXTWIDGET,
	COMMON_REDIALDIALOG_PROGRESSWDG,
	COMMON_REDIALDIALOG_BGWIDGET,
	COMMON_RECORDINGDIALOG_INFOTEXTWIDGET,
	COMMON_DIALOG_TIMEWIDGET,

	COMMON_DIALOG_MAINCONTAINER,
	COMMON_DIALOG_BGCONTAINER,
	COMMON_DIALOG_BGWIDGET,
	COMMON_DIALOG_TEXTWIDGET,
	COMMON_DIALOG_TITLETEXTWIDGET,
	COMMON_DIALOG_IMAGEWIDGET,
	COMMON_DIALOG_PROGRESSWIDGET
/* Widget ID end */
};

#endif /* __MMI_COMMON_DIALOG_ID_H__ */
