#ifndef __MMI_COMMON_COLOR_DEF_H__
#define __MMI_COMMON_COLOR_DEF_H__
#include "mmi_mae_common_def.h"

#define		COLOR_BLACK		   		(0xFF000000)		//(0,0,0)
#define		COLOR_GREY_1			(0xFF303030)		//(48,48,48)
#define		COLOR_GREY_2			(0xFF505050)		//(80,80,80)
#define		COLOR_GREY_3			(0xFF707070)		//(112,112,112)
#define		COLOR_GREY_4			(0xFF909090)		//(144,144,144)
#define		COLOR_GREY_5			(0xFFD0D0D0)		//(208,208,208)
#define     COLOR_GREY_6			(0XFF414141)   		//(65,65,65)
#define     COLOR_GREY_7			(0XFF5a5a5a)   		//(90,90,90)
#define		COLOR_WHITE		  	    (0xFFFFFFFF)		//(255,255,255)
#define     COLOR_WHITE_1       	(0xFFEAEAEA)        //(234,234,234)
#define     COLOR_WHITE_2       	(0xFFF9F9F9)        //(253,253,253)
#define		COLOR_BLUE_1			(0xFF003080)		//(0,48,128)
#define		COLOR_BLUE_2			(0xFF0050A0)		//(0,80,160)
#define		COLOR_BLUE_3			(0xFF2070D0)		//(32,112,208)
#define		COLOR_BLUE_4			(0xFF5090B0)		//(80,144,176)
#define		COLOR_BLUE_5			(0xFF30D0F0)		//(48,208,240)
#define		COLOR_BLUE_6			(0xFF70F0F0)		//(112,240,240)
#define		COLOR_BLUE_7			(0xFF90C0F0)		//(144,192,240)
#define		COLOR_BLUE_8			(0xFF1E7C95)
#define		COLOR_BLUE_9			(0xFF00598a)
#define		COLOR_BLUE_10			(0xFF4982a0)
#define		COLOR_ANDROID_BLUE_1	(0xFF33B5E5)
#define		COLOR_GREEN_1			(0xFF105040)		//(16,80,64)
#define		COLOR_GREEN_2			(0xFF408060)		//(64,128,96)
#define		COLOR_GREEN_3			(0xFF80B050)		//(128,176,80)
#define		COLOR_GREEN_4			(0xFF60D030)		//(96,208,48)
#define		COLOR_GREEN_5			(0xFFB0E050)		//(176,224,80)
#define		COLOR_GREEN_6			(0xFF80F050)		//(128,240,80)
#define		COLOR_GREEN_7			(0xFFD0F090)		//(208,240,144)
#define     COLOR_GREEN_8			(0xFFF4FFD8)		//(244,255,216)
#define     COLOR_GREEN_9			(0XFF416464)		//(65,100,100)
#define		COLOR_ORANGE_1			(0xFFD03000)		//(208,48,0)
#define		COLOR_ORANGE_2			(0xFFD05020)		//(208,80,32)
#define		COLOR_ORANGE_3			(0xFFF07020)		//(240,112,32)
#define		COLOR_ORANGE_4			(0xFFF0B020)		//(240,176,32)
#define		COLOR_ORANGE_5			(0xFFF0D000)		//(240,208,0)
#define		COLOR_ORANGE_6			(0xFFF0F050)		//(240,240,80)
#define		COLOR_ORANGE_7			(0xFFF0F0C0)		//(240,240,192)
#define		COLOR_BROWN_1			(0xFF401000)		//(64,16,0)
#define		COLOR_BROWN_2			(0xFF603000)		//(96,48,0)
#define		COLOR_BROWN_3			(0xFF906030)		//(144,96,48)
#define		COLOR_BROWN_4			(0xFFB07030)		//(176,112,48)
#define		COLOR_BROWN_5			(0xFFC09030)		//(192,144,48)
#define		COLOR_BROWN_6			(0xFFD0B060)		//(208,176,96)
#define		COLOR_BROWN_7			(0xFFE0D090)		//(224,208,144)
#define     COLOR_BROWN_8  			(0xFFFFE182)		//(225,225,130)
#define		COLOR_RED_1		 	  	(0xFF800000)		//(96,0,0)
#define		COLOR_RED_2		 		(0xFFA01010)		//(160,16,16)
#define		COLOR_RED_3		 	 	(0xFFC00000)		//(192,0,0)
#define		COLOR_RED_4		   		(0xFFD00040)		//(208,0,64)
#define		COLOR_RED_5		  		(0xFFF00000)		//(240,0,0)
#define		COLOR_RED_6		  	    (0xFFE06060)		//(224,96,96)
#define		COLOR_RED_7		  	    (0xFFF0C0C0)		//(240,192,192)
#define		COLOR_PURPLE_1			(0xFF300030)		//(48,0,48)
#define		COLOR_PURPLE_2			(0xFF400040)		//(64,0,64)
#define		COLOR_PURPLE_3			(0xFF600060)		//(96,0,96)
#define		COLOR_PURPLE_4			(0xFF9000B0)		//(144,0,176)
#define		COLOR_PURPLE_5			(0xFFC060D0)		//(192,96,208)
#define		COLOR_PURPLE_6			(0xFFD090D0)		//(208,144,208)
#define		COLOR_PURPLE_7			(0xFFE0C0E0)		//(224,192,224)
#define		COLOR_TRANSPARENCY		(0xFFFF6BFF)		//(255,107,255)
#define     COLOR_RED				(0xFFFF0000)    	//(255,0,0)
#define     COLOR_GREY				(0xFF404040)
#define     COLOR_GREEN      		(0xFF00FF00)

// mapping to ThemeColor[THEME_COLOR_NUMBER] in mmi_common_themeColor.rs
enum
{
	eTHM_COMMON_DEFAULT_BG,
	eTHM_COMMON_COLOR_LIST_TITLE_TEXT,
	eTHM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE,
	eTHM_COMMON_COLOR_LIST_TITLE_NUMBER_TEXT,
	eTHM_COMMON_COLOR_SOFTKEY_TEXT,
	eTHM_COMMON_COLOR_SOFTKEY_OUTLINE,
	eTHM_COMMON_COLOR_TAB_TEXT,
	eTHM_COMMON_COLOR_TAB_HIGHLIGHT_TEXT,
	eTHM_COMMON_COLOR_LIST_TEXT,
	eTHM_COMMON_COLOR_LIST_HIGHLIGHT_TEXT,
	eTHM_COMMON_COLOR_LIST_INFO_TEXT,
	eTHM_INPUT_COLOR_BORDER,
	eTHM_INPUT_COLOR_ACTIVE_BG,
	eTHM_INPUT_COLOR_ACTIVE_TEXT,
	eTHM_INPUT_COLOR_HIGHLIGHT_BG,
	eTHM_INPUT_COLOR_HIGHLIGHT_TEXT,
	eTHM_INPUT_COLOR_CURSOR,
	eTHM_NOTICE_COLOR_TEXT,
	eTHM_DISABLE_COLOR_TEXT,
	eTHM_IDLE_COLOR_OPERATOR_NAME_TEXT,
	eTHM_IDLE_COLOR_OPERATOR_NAME_TEXT_OUTLINE,
	eTHM_IDLE_COLOR_DATE_TEXT,
	eTHM_IDLE_COLOR_DATE_TEXT_OUTLINE,
	eTHM_IDLE_COLOR_TIME1_TEXT,
	eTHM_IDLE_COLOR_TIME1_TEXT_OUTLINE,
	eTHM_IDLE_COLOR_TIME2_TEXT,
	eTHM_IDLE_COLOR_TIME2_TEXT_OUTLINE,
	eTHM_BJX_FOCUS_COLOR_BG,
	eTHM_BJX_COLOR_BG,
	eTHM_COMMON_COLOR_OUTLINE1,
	eTHM_COMMON_COLOR_OUTLINE2,


	eTHM_COMMON_COLOR_LIST_TITLE_BG,
	eTHM_COMMON_COLOR_LIST_INFO_BG,
	eTHM_COMMON_COLOR_SYSTEM_BG,
	eTHM_COMMON_COLOR_LIST_SEL_1,
	eTHM_COMMON_COLOR_LIST_SEL_2,
	eTHM_COMMON_COLOR_OPTION_BG_5,
	eTHM_COMMON_COLOR_OPTION_BG_3,
	eTHM_NOTICE_COLOR_BG,
	eTHM_NOTICE_COLOR_PROGRESS_BG,
	eTHM_NOTICE_COLOR_PROGRESS,



	//BUTTON WIDGET
	eTHM_WDG_BUTTON_PRESS_TEXT,
	eTHM_WDG_BUTTON_PRESS_OUTLINE_TEXT,
	eTHM_WDG_BUTTON_UNPRESS_TEXT,
	eTHM_WDG_BUTTON_UNPRESS_OUTLINE_TEXT,

	//TEXT WIDGET
	eTHM_WDG_TEXT_TEXT,
	eTHM_WDG_TEXT_OUTLINE_TEXT,
	eTHM_WDG_TEXT_HIGHLIGHT_TEXT,
	eTHM_WDG_TEXT_HIGHLIGHT_OUTLINE_TEXT,
	eTHM_WDG_TEXT_HIGHLIGHT_BG,
	eTHM_WDG_TEXT_FCS_ITEM_BG,

	//INPUT CANDIDATE WIDGET
	eTHM_WDG_INPUTCANDIDATE_SPELLING_FONT,
	eTHM_WDG_INPUTCANDIDATE_SPELLING_HIGHLIGHT,
	eTHM_WDG_INPUTCANDIDATE_SPELLING_FOCUSED_BG,
	eTHM_WDG_INPUTCANDIDATE_SPELLING_NOT_FOCUSED_BG,
	eTHM_WDG_INPUTCANDIDATE_CANDIDATE_FONT,
	eTHM_WDG_INPUTCANDIDATE_CANDIDATE_HIGHLIGHT,

	eTHM_WDG_INPUTCANDIDATE_COMPONENT_FONT,
	eTHM_WDG_INPUTCANDIDATE_COMPONENT_HIGHLIGHT,
	eTHM_WDG_INPUTCANDIDATE_COMPONENT_FOCUSED_BG,

	eTHM_WDG_INPUTCANDIDATE_HANDWRITING_CANDIDATE_FONT,
	eTHM_WDG_INPUTCANDIDATE_SELECTNO,

	//INPUT WIDGET
	eTHM_WDG_INPUT_TEXT,
	eTHM_WDG_INPUT_BG,
	eTHM_WDG_INPUT_HIGHLIGHT_TEXT,
	eTHM_WDG_INPUT_HIGHLIGHT_BG,
	eTHM_WDG_INPUT_UNDERLINE,
	eTHM_WDG_INPUT_CURSOR,
	eTHM_WDG_INPUT_BORDER,
	eTHM_WDG_INPUT_INACTIVE_TEXT,
	eTHM_WDG_INPUT_MSGEDITOR_UNDERLINE,
	eTHM_WDG_INPUT_DROP_DOWN_LIST_BORDER,

	//PROGRESS WIDGET
	eTHM_WDG_PROGRESS_FG_BORDER,
	eTHM_WDG_PROGRESS_FG_FILL,
	eTHM_WDG_PROGRESS_BG_BORDER,
	eTHM_WDG_PROGRESS_BG_FILL,

	//MENU WIDGET
	eTHM_WDG_MENU_EMPTY_TEXT,
	eTHM_WDG_MENU_ITEM_TEXT,
	eTHM_WDG_MENU_HIGHLIGHT_ITEM_TEXT,
	eTHM_WDG_MENU_BORDER,

	//SOFTKEY WIDGET
	eTHM_WDG_SOFTKEY_OUTLINE_TEXT,

	//TITLE WIDGET
	eTHM_WDG_TITLE_BG,


	//TAB WIDGET
	eTHM_COMMON_COLOR_TAB_BG,
	eTHM_COMMON_COLOR_TAB_INACT,
	eTHM_COMMON_COLOR_TAB_ACT,

	//MAIN MENU APP
	eTHM_MAINMENUAPP_TEXT,
	eTHM_MAINMENUAPP_TEXT_OUTLINE,

	//DIALER APP
	eTHM_DIALERAPP_BG,
	eTHM_DIALERAPP_TEXT,

	//PULL DOWN WIDGET
	eTHM_WDG_PULLDOWN_TEXT,
	eTHM_WDG_PULLDOWN_UNFOCUS_BG,
	eTHM_WDG_PULLDOWN_HIGHLIGHT_TEXT,
	eTHM_WDG_PULLDOWN_FOCUS_BG,
	eTHM_WDG_PULLDOWN_DROPLIST_BORDER,

	//MFL WIDGET
	eTHM_WDG_MFL_BORDER_COLOR,

	//LINE2INFOPICK WIDGET
	eTHM_WDG_L2INFOPICK_BG,
	eTHM_WDG_L2INFOPICK_HIGHLIGHT_BG,

	//SKB WIDGET,
	eTHM_WDG_SKB_HIGHTLIGHT_TEXT,
	eTHM_WDG_SKB_UNPRESSED_TEXT,
    eTHM_WDG_SKB_PRESSED_TEXT,
    eTHM_WDG_SKB_INVALID_KRY_TEXT,

	//DATE ICON
	eTHM_WDG_DATEICON_MONTH_TEXT,
	eTHM_WDG_DATEICON_MONTH_OUTLINE,
	eTHM_WDG_DATEICON_DAY_TEXT,
	eTHM_WDG_DATEICON_DAY_OUTLINE,
	eTHM_WDG_DATEICON_TIME_TEXT,
	eTHM_WDG_DATEICON_TIME_OUTLINE,

	//HAND WRITING
	eTHM_WDG_HANDWRITING_DRAW_COLOR,

	//BMI APP
	eTHM_BMIAPP_VALUE_BG,

	//CALENDAR APP
	eTHM_CALENDARAPP_WEEKDAY_TEXT,
	eTHM_CALENDARAPP_DAY_HIGHLIGHT_TEXT,

	//BT APP
	eTHM_BTAPP_DOWNITEM_HIGHLIGHT_TEXT,

	//MESSAGE EDITOR APP_MMS
	eTHM_MSGEDITORAPP_MMS_ADDTEXT_BG,
	eTHM_MSGEDITORAPP_MMS_NO_CONTENT_TEXT,

	eTHM_COLOR_NUMBER
};



#define THEME_COLOR_NUMBER  (eTHM_COLOR_NUMBER)

extern u32 *g_pCurrThmColor;

#define	RS_THM_COMMON_DEFAULT_BG 										(*(u32*)(g_pCurrThmColor + eTHM_COMMON_DEFAULT_BG))
#define	RS_THM_COMMON_COLOR_LIST_TITLE_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_TITLE_TEXT))
#define	RS_THM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE 					(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE))
#define	RS_THM_COMMON_COLOR_LIST_TITLE_NUMBER_TEXT 						(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_TITLE_NUMBER_TEXT))
#define	RS_THM_COMMON_COLOR_SOFTKEY_TEXT 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_SOFTKEY_TEXT))
#define	RS_THM_COMMON_COLOR_SOFTKEY_OUTLINE 							(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_SOFTKEY_OUTLINE))
#define	RS_THM_COMMON_COLOR_TAB_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_TAB_TEXT))
#define	RS_THM_COMMON_COLOR_TAB_HIGHLIGHT_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_TAB_HIGHLIGHT_TEXT))
#define	RS_THM_COMMON_COLOR_LIST_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_TEXT))
#define	RS_THM_COMMON_COLOR_LIST_HIGHLIGHT_TEXT 						(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_HIGHLIGHT_TEXT))
#define	RS_THM_COMMON_COLOR_LIST_INFO_TEXT 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_INFO_TEXT))
#define	RS_THM_INPUT_COLOR_BORDER 										(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_BORDER))
#define	RS_THM_INPUT_COLOR_ACTIVE_BG 									(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_ACTIVE_BG))
#define	RS_THM_INPUT_COLOR_ACTIVE_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_ACTIVE_TEXT))
#define	RS_THM_INPUT_COLOR_HIGHLIGHT_BG 								(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_HIGHLIGHT_BG))
#define	RS_THM_INPUT_COLOR_HIGHLIGHT_TEXT 								(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_HIGHLIGHT_TEXT))
#define	RS_THM_INPUT_COLOR_CURSOR 										(*(u32*)(g_pCurrThmColor + eTHM_INPUT_COLOR_CURSOR))
#define	RS_THM_NOTICE_COLOR_TEXT 										(*(u32*)(g_pCurrThmColor + eTHM_NOTICE_COLOR_TEXT))
#define	RS_THM_DISABLE_COLOR_TEXT 										(*(u32*)(g_pCurrThmColor + eTHM_DISABLE_COLOR_TEXT))
#define	RS_THM_IDLE_COLOR_OPERATOR_NAME_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_OPERATOR_NAME_TEXT))
#define	RS_THM_IDLE_COLOR_OPERATOR_NAME_TEXT_OUTLINE 					(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_OPERATOR_NAME_TEXT_OUTLINE))
#define	RS_THM_IDLE_COLOR_DATE_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_DATE_TEXT))
#define	RS_THM_IDLE_COLOR_DATE_TEXT_OUTLINE 							(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_DATE_TEXT_OUTLINE))
#define	RS_THM_IDLE_COLOR_TIME1_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_TIME1_TEXT))
#define	RS_THM_IDLE_COLOR_TIME1_TEXT_OUTLINE 							(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_TIME1_TEXT_OUTLINE))
#define	RS_THM_IDLE_COLOR_TIME2_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_TIME2_TEXT))
#define	RS_THM_IDLE_COLOR_TIME2_TEXT_OUTLINE 							(*(u32*)(g_pCurrThmColor + eTHM_IDLE_COLOR_TIME2_TEXT_OUTLINE))
#define	RS_THM_BJX_FOCUS_COLOR_BG 										(*(u32*)(g_pCurrThmColor + eTHM_BJX_FOCUS_COLOR_BG))
#define	RS_THM_BJX_COLOR_BG 											(*(u32*)(g_pCurrThmColor + eTHM_BJX_COLOR_BG))
#define	RS_THM_COMMON_COLOR_OUTLINE1									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_OUTLINE1))
#define	RS_THM_COMMON_COLOR_OUTLINE2									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_OUTLINE2))

#define	RS_THM_COMMON_COLOR_LIST_TITLE_BG 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_TITLE_BG))
#define	RS_THM_COMMON_COLOR_LIST_INFO_BG 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_INFO_BG))
#define	RS_THM_COMMON_COLOR_SYSTEM_BG 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_SYSTEM_BG))
#define	RS_THM_COMMON_COLOR_LIST_SEL_1 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_SEL_1))
#define	RS_THM_COMMON_COLOR_LIST_SEL_2 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_LIST_SEL_2))
#define	RS_THM_COMMON_COLOR_OPTION_BG_5 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_OPTION_BG_5))
#define	RS_THM_COMMON_COLOR_OPTION_BG_3 								(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_OPTION_BG_3))
#define	RS_THM_NOTICE_COLOR_BG 											(*(u32*)(g_pCurrThmColor + eTHM_NOTICE_COLOR_BG))
#define	RS_THM_NOTICE_COLOR_PROGRESS_BG 								(*(u32*)(g_pCurrThmColor + eTHM_NOTICE_COLOR_PROGRESS_BG))
#define	RS_THM_NOTICE_COLOR_PROGRESS 									(*(u32*)(g_pCurrThmColor + eTHM_NOTICE_COLOR_PROGRESS))

	//BUTTON WIDGET
#define	RS_THM_WDG_BUTTON_PRESS_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_BUTTON_PRESS_TEXT))
#define	RS_THM_WDG_BUTTON_PRESS_OUTLINE_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_WDG_BUTTON_PRESS_OUTLINE_TEXT))
#define	RS_THM_WDG_BUTTON_UNPRESS_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_BUTTON_UNPRESS_TEXT))
#define	RS_THM_WDG_BUTTON_UNPRESS_OUTLINE_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_WDG_BUTTON_UNPRESS_OUTLINE_TEXT))

	//TEXT WIDGET
#define	RS_THM_WDG_TEXT_TEXT 											(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_TEXT))
#define	RS_THM_WDG_TEXT_OUTLINE_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_OUTLINE_TEXT))
#define	RS_THM_WDG_TEXT_HIGHLIGHT_TEXT 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_HIGHLIGHT_TEXT))
#define	RS_THM_WDG_TEXT_HIGHLIGHT_OUTLINE_TEXT 							(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_HIGHLIGHT_OUTLINE_TEXT))
#define	RS_THM_WDG_TEXT_HIGHLIGHT_BG 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_HIGHLIGHT_BG))
#define RS_THM_WDG_TEXT_FCS_ITEM_BG   									(*(u32*)(g_pCurrThmColor + eTHM_WDG_TEXT_FCS_ITEM_BG))

	//INPUT CANDIDATE WIDGET
#define RS_THM_WDG_INPUTCANDIDATE_SPELLING_FONT							(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_SPELLING_FONT))
#define RS_THM_WDG_INPUTCANDIDATE_SPELLING_HIGHLIGHT					(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_SPELLING_HIGHLIGHT))
#define RS_THM_WDG_INPUTCANDIDATE_SPELLING_FOCUSED_BG					(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_SPELLING_FOCUSED_BG))
#define RS_THM_WDG_INPUTCANDIDATE_SPELLING_NOT_FOCUSED_BG				(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_SPELLING_NOT_FOCUSED_BG))
#define RS_THM_WDG_INPUTCANDIDATE_CANDIDATE_FONT						(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_CANDIDATE_FONT))
#define RS_THM_WDG_INPUTCANDIDATE_CANDIDATE_HIGHLIGHT					(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_CANDIDATE_HIGHLIGHT))

#define RS_THM_WDG_INPUTCANDIDATE_COMPONENT_FONT						(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_COMPONENT_FONT))
#define RS_THM_WDG_INPUTCANDIDATE_COMPONENT_HIGHLIGHT					(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_COMPONENT_HIGHLIGHT))
#define RS_THM_WDG_INPUTCANDIDATE_COMPONENT_FOCUSED_BG					(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_COMPONENT_FOCUSED_BG))

#define RS_THM_WDG_INPUTCANDIDATE_HANDWRITING_CANDIDATE_FONT			(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_HANDWRITING_CANDIDATE_FONT))
#define RS_THM_WDG_INPUTCANDIDATE_SELECTNO								(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUTCANDIDATE_SELECTNO))

	//INPUT WIDGET
#define RS_THM_WDG_INPUT_TEXT											(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_TEXT))
#define RS_THM_WDG_INPUT_BG												(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_BG))
#define RS_THM_WDG_INPUT_HIGHLIGHT_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_HIGHLIGHT_TEXT))
#define RS_THM_WDG_INPUT_HIGHLIGHT_BG									(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_HIGHLIGHT_BG))
#define RS_THM_WDG_INPUT_UNDERLINE										(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_UNDERLINE))
#define RS_THM_WDG_INPUT_CURSOR											(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_CURSOR))
#define RS_THM_WDG_INPUT_BORDER											(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_BORDER))
#define RS_THM_WDG_INPUT_INACTIVE_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_INACTIVE_TEXT))
#define RS_THM_WDG_INPUT_MSGEDITOR_UNDERLINE							(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_MSGEDITOR_UNDERLINE))
#define RS_THM_WDG_INPUT_DROP_DOWN_LIST_BORDER							(*(u32*)(g_pCurrThmColor + eTHM_WDG_INPUT_DROP_DOWN_LIST_BORDER))

	//PROGRESS WIDGET
#define	RS_THM_WDG_PROGRESS_FG_BORDER 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PROGRESS_FG_BORDER))
#define	RS_THM_WDG_PROGRESS_FG_FILL 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PROGRESS_FG_FILL))
#define	RS_THM_WDG_PROGRESS_BG_BORDER 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PROGRESS_BG_BORDER))
#define	RS_THM_WDG_PROGRESS_BG_FILL 									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PROGRESS_BG_FILL))

	//MENU WIDGET
#define	RS_THM_WDG_MENU_EMPTY_TEXT 										(*(u32*)(g_pCurrThmColor + eTHM_WDG_MENU_EMPTY_TEXT))
#define	RS_THM_WDG_MENU_ITEM_TEXT										(*(u32*)(g_pCurrThmColor + eTHM_WDG_MENU_ITEM_TEXT))
#define RS_THM_WDG_MENU_HIGHLIGHT_ITEM_TEXT								(*(u32*)(g_pCurrThmColor + eTHM_WDG_MENU_HIGHLIGHT_ITEM_TEXT))
#define	RS_THM_WDG_MENU_BORDER 											(*(u32*)(g_pCurrThmColor + eTHM_WDG_MENU_BORDER))

	//SOFTKEY WIDGET
#define	RS_THM_WDG_SOFTKEY_OUTLINE_TEXT 								(*(u32*)(g_pCurrThmColor + eTHM_WDG_SOFTKEY_OUTLINE_TEXT))

	//TITLE WIDGET
#define RS_THM_WDG_TITLE_BG												(*(u32*)(g_pCurrThmColor + eTHM_WDG_TITLE_BG))


#define	RS_THM_COMMON_COLOR_TAB_BG 										(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_TAB_BG))
#define	RS_THM_COMMON_COLOR_TAB_INACT 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_TAB_INACT))
#define	RS_THM_COMMON_COLOR_TAB_ACT 									(*(u32*)(g_pCurrThmColor + eTHM_COMMON_COLOR_TAB_ACT))

	//BMI APP
#define RS_THM_BMIAPP_VALUE_BG											(*(u32*)(g_pCurrThmColor + eTHM_BMIAPP_VALUE_BG))

	//MAIN MENU APP
#define	RS_THM_MAINMENUAPP_TEXT_OUTLINE 								(*(u32*)(g_pCurrThmColor + eTHM_MAINMENUAPP_TEXT_OUTLINE))
#define RS_THM_MAINMENUAPP_TEXT											(*(u32*)(g_pCurrThmColor + eTHM_MAINMENUAPP_TEXT))

	//CALENDAR APP
#define RS_THM_CALENDARAPP_WEEKDAY_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_CALENDARAPP_WEEKDAY_TEXT))
#define RS_THM_CALENDARAPP_DAY_HIGHLIGHT_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_CALENDARAPP_DAY_HIGHLIGHT_TEXT))

	//DIALER APP
#define	RS_THM_DIALERAPP_TEXT 											(*(u32*)(g_pCurrThmColor + eTHM_DIALERAPP_TEXT))
#define	RS_THM_DIALERAPP_BG 											(*(u32*)(g_pCurrThmColor + eTHM_DIALERAPP_BG))

	//PULLDOWN WIDGET
#define RS_THM_WDG_PULLDOWN_TEXT           								(*(u32*)(g_pCurrThmColor + eTHM_WDG_PULLDOWN_TEXT))
#define RS_THM_WDG_PULLDOWN_UNFOCUS_BG									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PULLDOWN_UNFOCUS_BG))
#define RS_THM_WDG_PULLDOWN_HIGHLIGHT_TEXT 								(*(u32*)(g_pCurrThmColor + eTHM_WDG_PULLDOWN_HIGHLIGHT_TEXT))
#define RS_THM_WDG_PULLDOWN_FOCUS_BG									(*(u32*)(g_pCurrThmColor + eTHM_WDG_PULLDOWN_FOCUS_BG))
#define RS_THM_WDG_PULLDOWN_DROPLIST_BORDER								(*(u32*)(g_pCurrThmColor + eTHM_WDG_PULLDOWN_DROPLIST_BORDER))


//MFL WIDGET
#define RS_THM_WDG_MFL_BORDER_COLOR										(*(u32*)(g_pCurrThmColor + eTHM_WDG_MFL_BORDER_COLOR))

//LINE2INFOPICK WIDGET
#define RS_THM_WDG_L2INFOPICK_BG  										(*(u32*)(g_pCurrThmColor + eTHM_WDG_L2INFOPICK_BG))
#define RS_THM_WDG_L2INFOPICK_HIGHLIGHT_BG  							(*(u32*)(g_pCurrThmColor + eTHM_WDG_L2INFOPICK_HIGHLIGHT_BG))

//SKB WIDGET
#define RS_THM_WDG_SKB_HIGHTLIGHT_TEXT  								(*(u32*)(g_pCurrThmColor + eTHM_WDG_SKB_HIGHTLIGHT_TEXT))
#define RS_THM_WDG_SKB_UNPRESSED_TEXT  									(*(u32*)(g_pCurrThmColor + eTHM_WDG_SKB_UNPRESSED_TEXT))
#define RS_THM_WDG_SKB_PRESSED_TEXT  									(*(u32*)(g_pCurrThmColor + eTHM_WDG_SKB_PRESSED_TEXT))
#define RS_THM_WDG_SKB_INVALID_KRY_TEXT  								(*(u32*)(g_pCurrThmColor + eTHM_WDG_SKB_INVALID_KRY_TEXT))


//DATE ICON
#define RS_THM_WDG_DATEICON_MONTH_TEXT  								(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_MONTH_TEXT))
#define RS_THM_WDG_DATEICON_MONTH_OUTLINE								(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_MONTH_OUTLINE))
#define RS_THM_WDG_DATEICON_DAY_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_DAY_TEXT))
#define RS_THM_WDG_DATEICON_DAY_OUTLINE  								(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_DAY_OUTLINE))
#define RS_THM_WDG_DATEICON_TIME_TEXT									(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_TIME_TEXT))
#define RS_THM_WDG_DATEICON_TIME_OUTLINE								(*(u32*)(g_pCurrThmColor + eTHM_WDG_DATEICON_TIME_OUTLINE))

//HAND WRITING
#define RS_THM_WDG_HANDWRITING_DRAW_COLOR  								(*(u32*)(g_pCurrThmColor + eTHM_WDG_HANDWRITING_DRAW_COLOR))

// BT APP
#define RS_THM_BTAPP_DOWNITEM_HIGHLIGHT_TEXT							(*(u32*)(g_pCurrThmColor + eTHM_BTAPP_DOWNITEM_HIGHLIGHT_TEXT))

//MESSAGE EDITOR APP_MMS
#define RS_THM_MSGEDITORAPP_MMS_ADDTEXT_BG								(*(u32*)(g_pCurrThmColor + eTHM_MSGEDITORAPP_MMS_ADDTEXT_BG))
#define RS_THM_MSGEDITORAPP_MMS_NO_CONTENT_TEXT							(*(u32*)(g_pCurrThmColor + eTHM_MSGEDITORAPP_MMS_NO_CONTENT_TEXT))



#if defined(__THEME_COLOR_DEFAULT__)
//
// Group: default theme color
//
#define	DEF_THM_COMMON_DEFAULT_BG										(COLOR_WHITE)		//C18
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT							(COLOR_GREY_1)		//C01 	THM_WDG_TITLE_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE					(COLOR_WHITE)		//C1_2
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_NUMBER_TEXT						(COLOR_GREY_1)		//C02 	THM_WDG_TITLE_SMS_TEXT, THM_COMMON_PAGE_NUM_TEXT
#define	DEF_THM_COMMON_COLOR_SOFTKEY_TEXT								(COLOR_GREY_1)		//C03	THM_WDG_SOFTKEY_TEXT
#define	DEF_THM_COMMON_COLOR_SOFTKEY_OUTLINE							(COLOR_WHITE)		//C03_2	THM_WDG_SOFTKEY_TEXT
#define	DEF_THM_COMMON_COLOR_TAB_TEXT									(COLOR_GREY_5)		//C04	THM_WDG_TAB_TEXT
#define	DEF_THM_COMMON_COLOR_TAB_HIGHLIGHT_TEXT							(COLOR_WHITE)		//c05	THM_WDG_TAB_HIGHLIGHT_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_TEXT									(COLOR_BLACK)		//C06	THM_WDG_MENU_ITEM_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_HIGHLIGHT_TEXT						(COLOR_WHITE)		//C07	THM_WDG_MENU_ITEM_HIGHLIGHT_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_INFO_TEXT								(COLOR_WHITE)		//C08	THM_WDG_MENU_TITLE2_TEXT
#define	DEF_THM_INPUT_COLOR_BORDER										(COLOR_GREY_5)		//C09	THM_WDG_INPUT_BORDER
#define	DEF_THM_INPUT_COLOR_ACTIVE_BG									(COLOR_WHITE)		//C10	THM_WDG_INPUT_ACTIVE_BG
#define	DEF_THM_INPUT_COLOR_ACTIVE_TEXT									(COLOR_GREY_1)		//C11	THM_WDG_INUPT_TEXT
#define	DEF_THM_INPUT_COLOR_HIGHLIGHT_BG								(0xFF369FFA)		//C12	THM_WDG_INPUT_HIGHLIGHT_BG 			COLOR_GREY_4 ???
#define	DEF_THM_INPUT_COLOR_HIGHLIGHT_TEXT								(COLOR_WHITE)		//C13	THM_WDG_INPUT_HIGHLIGHT_TEXT
#define	DEF_THM_INPUT_COLOR_CURSOR										(COLOR_BLACK)		//C14	THM_WDG_INPUT_CURSOR
#define	DEF_THM_NOTICE_COLOR_TEXT										(COLOR_BLACK)		//C15	THM_DIALOG_TEXT
#define	DEF_THM_DISABLE_COLOR_TEXT										(COLOR_GREY_4)		//C17	THM_COMMON_DISABLED_TEXT
#define	DEF_THM_IDLE_COLOR_OPERATOR_NAME_TEXT							(COLOR_WHITE)		//A01	THM_IDLEAPP_OPERATOR_NAME_TEXT
#define DEF_THM_IDLE_COLOR_OPERATOR_NAME_TEXT_OUTLINE  					(COLOR_GREY_3)		//A01_2
#define	DEF_THM_IDLE_COLOR_DATE_TEXT									(COLOR_WHITE)		//A02	THM_IDLEAPP_OPERATOR_DATE_TEXT
#define	DEF_THM_IDLE_COLOR_DATE_TEXT_OUTLINE	 						(COLOR_GREY_3)		//A02_2
#define	DEF_THM_IDLE_COLOR_TIME1_TEXT									(COLOR_BLUE_6)		//A03	THM_IDLEAPP_OPERATOR_TIME1_TEXT
#define	DEF_THM_IDLE_COLOR_TIME1_TEXT_OUTLINE							(COLOR_GREY_3)		//A03_2
#define	DEF_THM_IDLE_COLOR_TIME2_TEXT									(COLOR_ORANGE_4)	//A04	THM_IDLEAPP_OPERATOR_TIME2_TEXT
#define	DEF_THM_IDLE_COLOR_TIME2_TEXT_OUTLINE							(COLOR_GREY_3)		//A04_2
#define	DEF_THM_BJX_FOCUS_COLOR_BG										(COLOR_GREY_3)		//
#define	DEF_THM_BJX_COLOR_BG											(COLOR_GREY_5)		//
#define	DEF_THM_COMMON_COLOR_OUTLINE1									(COLOR_WHITE)		//S01	THM_COMMON_OUTLINE1
#define	DEF_THM_COMMON_COLOR_OUTLINE2									(COLOR_GREY_3)		//S02	THM_COMMON_OUTLINE2

#define	DEF_THM_COMMON_COLOR_LIST_TITLE_BG								(0XFFE7E7E7)		//	THM_WDG_TITLE_BG
#define	DEF_THM_COMMON_COLOR_LIST_INFO_BG								(0XFF3880B8)		//
#define	DEF_THM_COMMON_COLOR_SYSTEM_BG									(0XFFC0D8E8)		//	THM_COMMON_SYSTEM_BG
#define	DEF_THM_COMMON_COLOR_LIST_SEL_1									(0)		//	THM_WDG_MENU_LIST_BG
#define	DEF_THM_COMMON_COLOR_LIST_SEL_2									(0XFF50D0E0)		//	THM_WDG_MFL_BG(SELECT ITEM BG)
#define	DEF_THM_COMMON_COLOR_OPTION_BG_5								(0XFFE0F8F8)		//	THM_WDG_MENU_POPUP_SELECT_BG
#define	DEF_THM_COMMON_COLOR_OPTION_BG_3								(0XFF9AE8F8)		//	THM_WDG_MENU_OPTION_SELECT_BG
#define	DEF_THM_NOTICE_COLOR_BG											(0XFFFFE898)		//---
#define	DEF_THM_NOTICE_COLOR_PROGRESS_BG								(0XFFB8B8B8)		//---
#define	DEF_THM_NOTICE_COLOR_PROGRESS									(COLOR_WHITE)		//---

	//BUTTON WIDGET
#define DEF_THM_WDG_BUTTON_PRESS_TEXT									(COLOR_WHITE)		//pressed text color
#define DEF_THM_WDG_BUTTON_PRESS_OUTLINE_TEXT							(COLOR_WHITE)		//pressed text outline color
#define DEF_THM_WDG_BUTTON_UNPRESS_TEXT									(COLOR_BLACK)		//un-pressed text color
#define DEF_THM_WDG_BUTTON_UNPRESS_OUTLINE_TEXT							(COLOR_BLACK)		//un-pressed text outline color

	//TEXT WIDGET
#define DEF_THM_WDG_TEXT_TEXT											(COLOR_BLACK)		//C21 DEFAULT_TEXT_COLOR
#define DEF_THM_WDG_TEXT_OUTLINE_TEXT									(COLOR_GREY)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_OUTLINE_TEXT							(COLOR_WHITE)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_BG									(0x00000000)
#define DEF_THM_WDG_TEXT_FCS_ITEM_BG									(0x00000000)

	//INPUT CANDIDATE WIDGET -- defined
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_FONT						(COLOR_BLACK)  	 //
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_HIGHLIGHT					(COLOR_BLACK)    //HIGHLIGHT TEXT COLOR
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_FOCUSED_BG					(COLOR_BLUE_7)   //
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_NOT_FOCUSED_BG				(COLOR_GREY_3)   //UN-FOCUS TEXT COLOR
#define DEF_THM_WDG_INPUTCANDIDATE_CANDIDATE_FONT						(COLOR_WHITE)	 //
#define DEF_THM_WDG_INPUTCANDIDATE_CANDIDATE_HIGHLIGHT					(COLOR_BLACK)	 //

#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_FONT						(COLOR_WHITE)	 //
#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_HIGHLIGHT					(COLOR_BLACK)	 //
#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_FOCUSED_BG					(COLOR_BLUE_7) 	 //

#define DEF_THM_WDG_INPUTCANDIDATE_HANDWRITING_CANDIDATE_FONT			(COLOR_BLACK)	 //
#define DEF_THM_WDG_INPUTCANDIDATE_SELECTNO								(MAKE_RGB(240,135,32))	//

	//INPUT WIDGET
#define DEF_THM_WDG_INPUT_TEXT											(COLOR_GREY_1)
#define DEF_THM_WDG_INPUT_BG											(COLOR_WHITE)
#define DEF_THM_WDG_INPUT_HIGHLIGHT_TEXT								(COLOR_WHITE)
#define DEF_THM_WDG_INPUT_HIGHLIGHT_BG									(COLOR_GREY_4)
#define DEF_THM_WDG_INPUT_UNDERLINE										(0x00AEAEAE)
#define DEF_THM_WDG_INPUT_CURSOR										(COLOR_BLACK)
#define DEF_THM_WDG_INPUT_BORDER										(COLOR_GREY_4)
#define DEF_THM_WDG_INPUT_INACTIVE_TEXT									(COLOR_GREY_1)
#define DEF_THM_WDG_INPUT_MSGEDITOR_UNDERLINE							(COLOR_GREY_5)	//MSG Edite underline color
#define DEF_THM_WDG_INPUT_DROP_DOWN_LIST_BORDER							(COLOR_GREY_5)

	//PROGRESS WIDGET
#define DEF_THM_WDG_PROGRESS_FG_BORDER									(0xFFA0D0F0)	//FG border
#define DEF_THM_WDG_PROGRESS_FG_FILL									(0xFF30B060)	//FG fill
#define DEF_THM_WDG_PROGRESS_BG_BORDER									(0xFF104020)	//BG border
#define DEF_THM_WDG_PROGRESS_BG_FILL									(0xFFD0F0E0)

	//MENU WIDGET
#define DEF_THM_WDG_MENU_EMPTY_TEXT										(DEF_THM_WDG_TEXT_TEXT) //COLOR_BLACK
#define DEF_THM_WDG_MENU_ITEM_TEXT										(COLOR_BLACK)
#define DEF_THM_WDG_MENU_HIGHLIGHT_ITEM_TEXT		  					(DEF_THM_WDG_TEXT_HIGHLIGHT_TEXT) //COLOR_WHITE
#define DEF_THM_WDG_MENU_BORDER											(COLOR_GREY_5)	//C22

	//SOFTKEY WIDGET
#define DEF_THM_WDG_SOFTKEY_OUTLINE_TEXT								(COLOR_WHITE)  	//C03_2

	//TITLE WIDGET
#define DEF_THM_WDG_TITLE_BG											(0XFFE7E7E7)


//***************NOT RS_************************

	//LINE2INFOPICK WIDGET
#define DEF_THM_WDG_L2INFOPICK_BG  										(COLOR_GREY_5)  //C19
#define DEF_THM_WDG_L2INFOPICK_HIGHLIGHT_BG  							(COLOR_BLUE_7)	//C20

	//LINE2INFO WIDGET
#define DEF_THM_WDG_L2INFO_UNFOCUS_BG      								(COLOR_GREY_5)	//C19
#define DEF_THM_WDG_L2INFO_HIGHLIGHT_TEXT								(COLOR_WHITE)
#define DEF_THM_WDG_L2INFO_FOCUS_BG      								(0xFF52B6FF)	//C20

	//STATUS BAR WIDGET
#if defined(__UI_STYLE_MMI_ANDROID_4_0__)
#define DEF_THM_WDG_STATUS_BAR_TEXT  									(COLOR_ANDROID_BLUE_1)
#else
#if !defined(__APP_MMI_SMALLROM__) && !defined(__LCM_QCIF_PLUS_MMI__) && !defined(__LCM_QQVGA_MMI__)
#define DEF_THM_WDG_STATUS_BAR_TEXT  									(COLOR_BLACK)	//defined
#else
#define DEF_THM_WDG_STATUS_BAR_TEXT  									(COLOR_GREY_5)	//defined
#endif
#endif // __UI_STYLE_MMI_ANDROID_4_0__

	//CANVAS WIDGET --- USELESS
#define DEF_THM_WDG_CANVAS_BG											(COLOR_GREEN)
#define DEF_THM_WDG_CANVAS_FG											(COLOR_WHITE)
#define DEF_THM_WDG_CANVAS_LINE											(COLOR_RED)
#define DEF_THM_WDG_CANVAS_FONT											(COLOR_WHITE)
#define DEF_THM_WDG_CANVAS_FONT_OUTLINE									(COLOR_BLACK)

	//SCROLL BAR WIDGET
#define DEF_THM_WDG_SCROLLBAR_BAR_BORDER    							(0xFF30B060)	//???
#define DEF_THM_WDG_SCROLLBAR_BAR_FILL									(0xFFC0F0D0)	//???
#define DEF_THM_WDG_SCROLLBAR_INDICATOR_BORDER							(0xFF30B0F0)	//???
#define DEF_THM_WDG_SCROLLBAR_INDICATOR_FILL							(0xFF90E0FF)	//???

	//TIMER FORMAT WIDGET  --- USELESS
#define DEF_THM_WDG_TIMER_FORMAT_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_TIMER_FORMAT_OUTLINE								(COLOR_WHITE)

	// MFL WIDGET
#define DEF_THM_WDG_MFL_BORDER_COLOR									(COLOR_GREY_5)

	//SKB WIDGET
#define DEF_THM_WDG_SKB_HIGHTLIGHT_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_SKB_UNPRESSED_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_SKB_PRESSED_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_SKB_INVALID_KRY_TEXT								(COLOR_GREY_4)

	//DATE ICON
#define DEF_THM_WDG_DATEICON_MONTH_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_MONTH_OUTLINE								(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_DAY_TEXT									(COLOR_GREY_1)
#define DEF_THM_WDG_DATEICON_DAY_OUTLINE								(COLOR_GREY_1)
#define DEF_THM_WDG_DATEICON_TIME_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_TIME_OUTLINE								(COLOR_WHITE)

  //HAND WRITING
#define DEF_THM_WDG_HANDWRITING_DRAW_COLOR								(COLOR_RED)

  //VTM
#define DEF_THM_COMMON_COLOR_POPUP_INPUT_BG   							(0xFF515B67)
#define DEF_THM_COMMON_VTM_IMG_BG										(COLOR_BLACK)
#define DEF_THM_COMMON_VTM_IMG_THUMB_BG									(COLOR_BLACK)
#define DEF_THM_COMMON_VTM_PROMPT_BORDER								(COLOR_GREY_3)
#define DEF_THM_COMMON_VTM_POP_INPUT_BORDER								(COLOR_GREY_3)
#define DEF_THM_COMMON_VTM_VIEWPORT_BG									(DEF_THM_COMMON_DEFAULT_BG)

 //ATV APP
#define DEF_THM_ATVAPP_CHANNEL_NAME_TEXT  								(COLOR_WHITE)

 //BJX APP
#define DEF_THM_BJXAPP_ALPHABET_GRID_BORDER  							(COLOR_BLACK)

 //BMI APP
#define DEF_THM_BMIAPP_VALUE_BG											(COLOR_BLUE_7)
#define DEF_THM_BMIAPP_VALUE_BORDER										(COLOR_GREY_4)

 //CALCULATOR APP
#define DEF_THM_CALCULATORAPP_RESULT_TEXT  								(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERAND1_TEXT  							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERATOR_TEXT  							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERAND_BTN_TEXT  						(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERATOR_BTN_TEXT  						(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_BACKGROUND  						        MAKE_RGB(0x30, 0x30, 0x30)
#define DEF_THM_CALCULATORAPP_SIMPLY_LSK_TEXT 							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_SIMPLY_RSK_TEXT 							(COLOR_WHITE)

	// CC APP
#define DEF_THM_CCAPP_TOUCHDIALING_INPUT  								(COLOR_WHITE)
#define DEF_THM_CCAPP_DIALING_INPUT  									(COLOR_WHITE)

  // CCMTA APP
#define DEF_THM_CCMTAAPP_WND_BG  										(COLOR_GREY_5)

  // COUNT DOWN TIMER APP
//#define DEF_THM_COUNTDOWNTIMERAPP_SET_TEXT   							(COLOR_BLACK)
//#define DEF_THM_COUNTDOWNTIMERAPP_TEXT   								(COLOR_WHITE)


	//EBOOK APP
//#define DEF_THM_EBOOKAPP_TEXT   										(COLOR_BLACK)
//#define DEF_THM_EBOOKAPP_OUTLINE   									(COLOR_WHITE)

  //ENGINEER MODE APP
#define DEF_THM_EMAPP_TOUCHPANELTEST_TEXT 								(COLOR_BLACK)
#define DEF_THM_EMAPP_TEXT 												(COLOR_WHITE)

  //EVENT CENTER APP
#define DEF_THM_EVTCENTERAPP_TEXT 										(COLOR_WHITE)

  //FILE MANAGER APP
#define DEF_THM_FILEMGRAPP_BG 											(COLOR_WHITE)

  //FM RADIO APP
//#define DEF_THM_FMRADIOAPP_TEXT 										(COLOR_WHITE)
//#define DEF_THM_FMRADIOAPP_BG 										(COLOR_BLACK)
//#define DEF_THM_FMRADIOAPP_POS_TEXT 									(COLOR_BLUE_8)

//FRUIT GAMBLE GAME APP
//#define DEF_THM_FRUITGAMBLEAPP_TEXT 									(COLOR_WHITE)
//#define DEF_THM_FRUITGAMBLEAPP_INPUT_TEXT 							(COLOR_RED_5)

	//KEY GUARD APP
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_TIME_TEXT  		  			(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_TEXT  				  		(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_DIAL_NUMBER_TEXT   			(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_DATE_TEXT   				(COLOR_GREY_5)

	//MAP APP
#define DEF_THM_MAPAPP_CALENDAR_HIGHLIGHT_BORDER  						(COLOR_BLUE_3)
#define DEF_THM_MAPAPP_CALENDAR_DAY_TEXT  								(COLOR_WHITE)
#define DEF_THM_MAPAPP_BG	  											(COLOR_BLACK)

	//MESSAGE EDITOR APP
#define DEF_THM_MSGEDITORAPP_RECIPIENT_FONT  							(COLOR_BLACK)
#define DEF_THM_MSGEDITORAPP_FONT_DEFAULT  								(COLOR_BLACK)

	//MPLAYER APP
//#define DEF_THM_MPLAYERAPP_PLAYLIST_TEXT  							(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_BG  							(COLOR_BLACK)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_LYRICS_TEXT  					(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_TITLE_TEXT  					(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_ALBUM_TEXT  					(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_ARTIST_TEXT 					(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_TIME_TEXT  						(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXT  				(COLOR_GREY_4)

	//OFF APP
#define DEF_THM_OFFAPP_BUTTON_TEXT  									(COLOR_GREY_1)

	//ON APP
//#define DEF_THM_ONAPP_BG  											(COLOR_BLACK)

	//PHONE BOOK APP
#define DEF_THM_PHBAPP_TEXT 											(COLOR_BLACK)

	//PROFILE APP
#define DEF_THM_PROFILEAPP_BG 											(COLOR_WHITE)

	//SEC APP
#define DEF_THM_SECAPP_BG 												(COLOR_GREY_3)

	//SNOTE APP
#define DEF_THM_SNOTEAPP_MENUGRID_BG 									(COLOR_WHITE)

	//VIDEO PLAYER APP
#define DEF_THM_VIDEOPLAYERAPP_TEXT_1 									(COLOR_ORANGE_4)
#define DEF_THM_VIDEOPLAYERAPP_TEXT_2 									(COLOR_WHITE)
#define DEF_THM_VIDEOPLAYERAPP_TEXT_3									(COLOR_WHITE)

	//VIDEO TELEPHONE APP
#define DEF_THM_VIDEOTELEAPP_STATES_TEXT 								(COLOR_GREEN_2)
#define DEF_THM_VIDEOTELERAPP_OUTLINE 		 							(COLOR_WHITE)
#define DEF_THM_VIDEOTELERAPP_INFO_1_TEXT  								(COLOR_BLUE_1)
#define DEF_THM_VIDEOTELERAPP_INFO_2_TEXT  								(COLOR_GREEN_2)
#define DEF_THM_VIDEOTELERAPP_INFO_3_TEXT  								(COLOR_BLACK)
#define DEF_THM_VIDEOTELERAPP_INPUT 			 						(COLOR_WHITE)

	//VOICE MEMO APP
#define DEF_THM_VOICEMEMOAPP_TEXT  										(COLOR_RED_5)

//***************END NOT RS_************************

// BT APP
#define DEF_THM_BTAPP_DOWNITEM_HIGHLIGHT_TEXT							(COLOR_BLACK)

//MESSAGE EDITOR APP_MMS
#define DEF_THM_MSGEDITORAPP_MMS_ADDTEXT_BG								(0xFF3399FF)
#define DEF_THM_MSGEDITORAPP_MMS_NO_CONTENT_TEXT						(COLOR_GREY_4)

	//CALENDAR APP
#define	DEF_THM_CALENDARAPP_WEEKDAY_TEXT								(COLOR_GREY_2)
#define DEF_THM_CALENDARAPP_DAY_HIGHLIGHT_TEXT							(COLOR_BLACK)

	//MAIN MENU APP
	#define DEF_THM_MAINMENUAPP_TEXT									(COLOR_WHITE)   //C23
#define DEF_THM_MAINMENUAPP_TEXT_OUTLINE		 						(COLOR_BLACK)   //C23_2

	//DIALER APP
#define DEF_THM_DIALERAPP_BG											(COLOR_BLACK)
#define DEF_THM_DIALERAPP_TEXT											(COLOR_WHITE)
#define DEF_THM_DIALERAPP_CURSOR										(COLOR_WHITE)

#define	DEF_THM_COMMON_COLOR_TAB_BG										(0XFFD8E8F8)		//
#define	DEF_THM_COMMON_COLOR_TAB_INACT									(0XFF68B8C8)		//
#define	DEF_THM_COMMON_COLOR_TAB_ACT									(0XFFC8D0D8)		//
//#define		DEF_THM_COMMON_COLOR_LIST_INFO_TWO_LINE_BG				(0XFF3880B8)		//no one used

#define DEF_THM_WDG_PULLDOWN_TEXT										(COLOR_BLACK)
#define DEF_THM_WDG_PULLDOWN_UNFOCUS_BG									(RGBCOLOR_WHITE)
#define DEF_THM_WDG_PULLDOWN_HIGHLIGHT_TEXT								(RGBCOLOR_WHITE)
#define DEF_THM_WDG_PULLDOWN_FOCUS_BG									(RGBCOLOR_BLUE)
#define DEF_THM_WDG_PULLDOWN_DROPLIST_BORDER							(RGBCOLOR_BLUE)

#endif //__THEME_COLOR_DEFAULT__


#if defined(__THEME_COLOR_THEME2__)
//
// Group: default theme color
//
#define	DEF_THM_COMMON_DEFAULT_BG										(COLOR_GREY_7)		//C18
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT							(COLOR_WHITE)		//C01 	THM_WDG_TITLE_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE					(COLOR_GREY_2)		//C1_2
#define	DEF_THM_COMMON_COLOR_LIST_TITLE_NUMBER_TEXT						(COLOR_GREY_1)		//C02 	THM_WDG_TITLE_SMS_TEXT, THM_COMMON_PAGE_NUM_TEXT
#define	DEF_THM_COMMON_COLOR_SOFTKEY_TEXT								(COLOR_WHITE)		//C03	THM_WDG_SOFTKEY_TEXT
#define	DEF_THM_COMMON_COLOR_SOFTKEY_OUTLINE							(COLOR_GREY_2)		//C03_2	THM_WDG_SOFTKEY_TEXT
#define	DEF_THM_COMMON_COLOR_TAB_TEXT									(COLOR_GREY_5)		//C04	THM_WDG_TAB_TEXT
#define	DEF_THM_COMMON_COLOR_TAB_HIGHLIGHT_TEXT							(COLOR_WHITE)		//C05	THM_WDG_TAB_HIGHLIGHT_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_TEXT									(COLOR_WHITE)		//c06	THM_WDG_MENU_ITEM_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_HIGHLIGHT_TEXT						(COLOR_BLACK)		//C07	THM_WDG_MENU_ITEM_HIGHLIGHT_TEXT
#define	DEF_THM_COMMON_COLOR_LIST_INFO_TEXT								(COLOR_GREEN_8)		//C08	THM_WDG_MENU_TITLE2_TEXT
#define	DEF_THM_INPUT_COLOR_BORDER										(COLOR_GREY_5)		//C09	THM_WDG_INPUT_BORDER
#define	DEF_THM_INPUT_COLOR_ACTIVE_BG									(COLOR_GREEN_8)		//C10	THM_WDG_INPUT_ACTIVE_BG
#define	DEF_THM_INPUT_COLOR_ACTIVE_TEXT									(COLOR_BLACK)		//C11	THM_WDG_INUPT_TEXT
#define	DEF_THM_INPUT_COLOR_HIGHLIGHT_BG								(COLOR_GREEN_4)		//C12	THM_WDG_INPUT_HIGHLIGHT_BG 			COLOR_GREY_4 ???
#define	DEF_THM_INPUT_COLOR_HIGHLIGHT_TEXT								(COLOR_BLACK)		//C13	THM_WDG_INPUT_HIGHLIGHT_TEXT
#define	DEF_THM_INPUT_COLOR_CURSOR										(COLOR_BLACK)		//C14	THM_WDG_INPUT_CURSOR
#define	DEF_THM_NOTICE_COLOR_TEXT										(COLOR_WHITE)		//C15	THM_DIALOG_TEXT
#define	DEF_THM_DISABLE_COLOR_TEXT										(COLOR_GREY_4)		//C17	THM_COMMON_DISABLED_TEXT
#define	DEF_THM_IDLE_COLOR_OPERATOR_NAME_TEXT							(COLOR_WHITE)		//A01	THM_IDLEAPP_OPERATOR_NAME_TEXT
#define DEF_THM_IDLE_COLOR_OPERATOR_NAME_TEXT_OUTLINE					(COLOR_GREY_1)		//A01_2
#define	DEF_THM_IDLE_COLOR_DATE_TEXT									(COLOR_WHITE)		//A02	THM_IDLEAPP_OPERATOR_DATE_TEXT
#define	DEF_THM_IDLE_COLOR_DATE_TEXT_OUTLINE							(COLOR_GREY_1)		//A02_2
#define	DEF_THM_IDLE_COLOR_TIME1_TEXT									(COLOR_GREEN_8)		//A03	THM_IDLEAPP_OPERATOR_TIME1_TEXT
#define	DEF_THM_IDLE_COLOR_TIME1_TEXT_OUTLINE							(COLOR_GREY_6)		//A03_2
#define	DEF_THM_IDLE_COLOR_TIME2_TEXT									(COLOR_BROWN_8)		//A04	THM_IDLEAPP_OPERATOR_TIME2_TEXT
#define	DEF_THM_IDLE_COLOR_TIME2_TEXT_OUTLINE							(COLOR_GREY_7)		//A04_2
#define	DEF_THM_BJX_FOCUS_COLOR_BG										(COLOR_GREY_3)		//
#define	DEF_THM_BJX_COLOR_BG											(COLOR_GREY_5)		//
#define	DEF_THM_COMMON_COLOR_OUTLINE1									(COLOR_GREY_3)		//S01	THM_COMMON_OUTLINE1
#define	DEF_THM_COMMON_COLOR_OUTLINE2									(COLOR_GREY_3)		//S02	THM_COMMON_OUTLINE2

#define	DEF_THM_COMMON_COLOR_LIST_TITLE_BG								(0XFFE7E7E7)		//	THM_WDG_TITLE_BG
#define	DEF_THM_COMMON_COLOR_LIST_INFO_BG								(0XFF3880B8)		//
#define	DEF_THM_COMMON_COLOR_SYSTEM_BG									(0XFFC0D8E8)		//	THM_COMMON_SYSTEM_BG
#define	DEF_THM_COMMON_COLOR_LIST_SEL_1									(0)		//	THM_WDG_MENU_LIST_BG
#define	DEF_THM_COMMON_COLOR_LIST_SEL_2									(COLOR_GREEN_8)		//	THM_WDG_MFL_BG(SELECT ITEM BG)
#define	DEF_THM_COMMON_COLOR_OPTION_BG_5								(0XFFE0F8F8)		//	THM_WDG_MENU_POPUP_SELECT_BG
#define	DEF_THM_COMMON_COLOR_OPTION_BG_3								(0XFF9AE8F8)		//	THM_WDG_MENU_OPTION_SELECT_BG
#define	DEF_THM_NOTICE_COLOR_BG											(0XFFFFE898)		//
#define	DEF_THM_NOTICE_COLOR_PROGRESS_BG								(0XFFB8B8B8)		//
#define	DEF_THM_NOTICE_COLOR_PROGRESS									(COLOR_WHITE)		//

	//BUTTON WIDGET
#define DEF_THM_WDG_BUTTON_PRESS_TEXT									(COLOR_WHITE)		//pressed text color
#define DEF_THM_WDG_BUTTON_PRESS_OUTLINE_TEXT							(COLOR_WHITE)		//pressed text outline color
#define DEF_THM_WDG_BUTTON_UNPRESS_TEXT									(COLOR_BLACK)		//un-pressed text color
#define DEF_THM_WDG_BUTTON_UNPRESS_OUTLINE_TEXT							(COLOR_BLACK)		//un-pressed text outline color

	//TEXT WIDGET
#define DEF_THM_WDG_TEXT_TEXT											(COLOR_WHITE)		//C21 DEFAULT_TEXT_COLOR
#define DEF_THM_WDG_TEXT_OUTLINE_TEXT									(COLOR_GREY)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_OUTLINE_TEXT							(COLOR_WHITE)
#define DEF_THM_WDG_TEXT_HIGHLIGHT_BG									(0x00000000)	// 0
#define DEF_THM_WDG_TEXT_FCS_ITEM_BG									(0x00000000)	// 0

	//INPUT CANDIDATE WIDGET
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_FONT						(COLOR_BLACK)
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_HIGHLIGHT					(COLOR_BLACK)
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_FOCUSED_BG					(COLOR_GREEN_8)
#define DEF_THM_WDG_INPUTCANDIDATE_SPELLING_NOT_FOCUSED_BG				(COLOR_GREY_2)	//SPELLING  UNFOCUS TEXT COLOR
#define DEF_THM_WDG_INPUTCANDIDATE_CANDIDATE_FONT						(COLOR_WHITE)
#define DEF_THM_WDG_INPUTCANDIDATE_CANDIDATE_HIGHLIGHT					(COLOR_BLACK)

#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_FONT						(COLOR_BLACK)
#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_HIGHLIGHT					(COLOR_BLACK)
#define DEF_THM_WDG_INPUTCANDIDATE_COMPONENT_FOCUSED_BG					(COLOR_GREEN_8)

#define DEF_THM_WDG_INPUTCANDIDATE_HANDWRITING_CANDIDATE_FONT			(COLOR_BLACK)
#define DEF_THM_WDG_INPUTCANDIDATE_SELECTNO								(COLOR_GREEN_6)

			//INPUT WIDGET
#define DEF_THM_WDG_INPUT_TEXT											(COLOR_WHITE)
#define DEF_THM_WDG_INPUT_BG											(COLOR_GREY_4)
#define DEF_THM_WDG_INPUT_HIGHLIGHT_TEXT								(COLOR_GREY_2)
#define DEF_THM_WDG_INPUT_HIGHLIGHT_BG									(COLOR_GREEN_5)
#define DEF_THM_WDG_INPUT_UNDERLINE										(0x00AEAEAE)
#define DEF_THM_WDG_INPUT_CURSOR										(COLOR_WHITE)
#define DEF_THM_WDG_INPUT_BORDER										(COLOR_GREY_5)
#define DEF_THM_WDG_INPUT_INACTIVE_TEXT									(COLOR_GREEN_7)
#define DEF_THM_WDG_INPUT_MSGEDITOR_UNDERLINE							(COLOR_WHITE)	//MSG Edeite underline color
#define DEF_THM_WDG_INPUT_DROP_DOWN_LIST_BORDER							(COLOR_GREY_5)

	//PROGRESS WIDGET
#define DEF_THM_WDG_PROGRESS_FG_BORDER									(0xFFA0D0F0)	//FG border
#define DEF_THM_WDG_PROGRESS_FG_FILL									(0xFF30B060)	//FG fill
#define DEF_THM_WDG_PROGRESS_BG_BORDER									(0xFF104020)	//BG border
#define DEF_THM_WDG_PROGRESS_BG_FILL									(0xFFD0F0E0)

	//MENU WIDGET
#define DEF_THM_WDG_MENU_EMPTY_TEXT										(DEF_THM_WDG_TEXT_TEXT) //COLOR_WHITE
#define DEF_THM_WDG_MENU_ITEM_TEXT										(COLOR_WHITE)
#define DEF_THM_WDG_MENU_HIGHLIGHT_ITEM_TEXT		  					(DEF_THM_WDG_TEXT_HIGHLIGHT_TEXT) //COLOR_BLACK
#define DEF_THM_WDG_MENU_BORDER											(COLOR_WHITE)	//C22

	//SOFTKEY WIDGET
#define DEF_THM_WDG_SOFTKEY_OUTLINE_TEXT								(COLOR_GREY_2)	//C03_2

	//TITLE WIDGET
#define DEF_THM_WDG_TITLE_BG											(0XFFE7E7E7)


//***************NOT RS_************************

	//LINE2INFOPICK WIDGET
#define DEF_THM_WDG_L2INFOPICK_BG  										(COLOR_GREY_6)  //C19
#define DEF_THM_WDG_L2INFOPICK_HIGHLIGHT_BG  							(COLOR_GREEN_8)	//C20

	//LINE2INFO WIDGET
#define DEF_THM_WDG_L2INFO_UNFOCUS_BG      								(COLOR_GREY_6)	//C19
#define DEF_THM_WDG_L2INFO_HIGHLIGHT_TEXT								(COLOR_BLACK)
#define DEF_THM_WDG_L2INFO_FOCUS_BG      								(COLOR_GREEN_8)	//C20

	//STATUS BAR WIDGET
#if defined(__UI_STYLE_MMI_ANDROID_4_0__)
#define DEF_THM_WDG_STATUS_BAR_TEXT  									(COLOR_ANDROID_BLUE_1)
#else
#define DEF_THM_WDG_STATUS_BAR_TEXT  									(COLOR_GREY_5)
#endif // __UI_STYLE_MMI_ANDROID_4_0__

	//CANVAS WIDGET --- USELESS
#define DEF_THM_WDG_CANVAS_BG											(COLOR_GREEN)
#define DEF_THM_WDG_CANVAS_FG											(COLOR_WHITE)
#define DEF_THM_WDG_CANVAS_LINE											(COLOR_RED)
#define DEF_THM_WDG_CANVAS_FONT											(COLOR_WHITE)
#define DEF_THM_WDG_CANVAS_FONT_OUTLINE									(COLOR_BLACK)

	//SCROLL BAR WIDGET
#define DEF_THM_WDG_SCROLLBAR_BAR_BORDER    							(0xFF30B060)
#define DEF_THM_WDG_SCROLLBAR_BAR_FILL									(0xFFC0F0D0)
#define DEF_THM_WDG_SCROLLBAR_INDICATOR_BORDER							(0xFF30B0F0)
#define DEF_THM_WDG_SCROLLBAR_INDICATOR_FILL							(0xFF90E0FF)

	//TIMER FORMAT WIDGET
#define DEF_THM_WDG_TIMER_FORMAT_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_TIMER_FORMAT_OUTLINE								(COLOR_WHITE)

	 // MFL WIDGET
#define DEF_THM_WDG_MFL_BORDER_COLOR									(COLOR_GREY_5)

	 //SKB WIDGET
#define DEF_THM_WDG_SKB_HIGHTLIGHT_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_SKB_UNPRESSED_TEXT									(COLOR_WHITE)
#define DEF_THM_WDG_SKB_PRESSED_TEXT									(COLOR_BLACK)
#define DEF_THM_WDG_SKB_INVALID_KRY_TEXT								(COLOR_GREY_4)

	 //DATE ICON
#define DEF_THM_WDG_DATEICON_MONTH_TEXT								  	(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_MONTH_OUTLINE							  	(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_DAY_TEXT									(COLOR_GREY_1)
#define DEF_THM_WDG_DATEICON_DAY_OUTLINE						  		(COLOR_GREY_1)
#define DEF_THM_WDG_DATEICON_TIME_TEXT								  	(COLOR_WHITE)
#define DEF_THM_WDG_DATEICON_TIME_OUTLINE								 (COLOR_WHITE)

	//HAND WRITING
#define DEF_THM_WDG_HANDWRITING_DRAW_COLOR								(COLOR_GREEN_5)

  //VTM
#define DEF_THM_COMMON_COLOR_POPUP_INPUT_BG   							(0xFF515B67)
#define DEF_THM_COMMON_VTM_IMG_BG										(COLOR_BLACK)
#define DEF_THM_COMMON_VTM_IMG_THUMB_BG									(COLOR_BLACK)
#define DEF_THM_COMMON_VTM_PROMPT_BORDER								(COLOR_GREY_3)
#define DEF_THM_COMMON_VTM_POP_INPUT_BORDER								(COLOR_GREY_3)
#define DEF_THM_COMMON_VTM_VIEWPORT_BG									(DEF_THM_COMMON_DEFAULT_BG)

 //ATV APP
#define DEF_THM_ATVAPP_CHANNEL_NAME_TEXT  								(COLOR_WHITE)

 //BJX APP
#define DEF_THM_BJXAPP_ALPHABET_GRID_BORDER  							(COLOR_BLACK)

 //BMI APP
#define DEF_THM_BMIAPP_VALUE_BG											(COLOR_GREEN_3)
#define DEF_THM_BMIAPP_VALUE_BORDER										(COLOR_GREY_4)

 //CALCULATOR APP
#define DEF_THM_CALCULATORAPP_RESULT_TEXT  								(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERAND1_TEXT  							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERATOR_TEXT  							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERAND_BTN_TEXT  						(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_OPERATOR_BTN_TEXT  						(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_BACKGROUND  						        MAKE_RGB(0x30, 0x30, 0x30)
#define DEF_THM_CALCULATORAPP_SIMPLY_LSK_TEXT 							(COLOR_WHITE)
#define DEF_THM_CALCULATORAPP_SIMPLY_RSK_TEXT 							(COLOR_WHITE)

	// CC APP
#define DEF_THM_CCAPP_TOUCHDIALING_INPUT  								(COLOR_BLACK)
#define DEF_THM_CCAPP_DIALING_INPUT 									(COLOR_BLACK)

  // CCMTA APP
#define DEF_THM_CCMTAAPP_WND_BG  										(COLOR_GREY_5)

  // COUNT DOWN TIMER APP
//#define DEF_THM_COUNTDOWNTIMERAPP_SET_TEXT   							(COLOR_BLACK)
//#define DEF_THM_COUNTDOWNTIMERAPP_TEXT   								(COLOR_WHITE)


	//EBOOK APP
//#define DEF_THM_EBOOKAPP_TEXT   										(COLOR_BLACK)
//#define DEF_THM_EBOOKAPP_OUTLINE	   									(COLOR_WHITE)

  //ENGINEER MODE APP
#define DEF_THM_EMAPP_TOUCHPANELTEST_TEXT 								(COLOR_BLACK)
#define DEF_THM_EMAPP_TEXT 												(COLOR_WHITE)

  //EVENT CENTER APP
#define DEF_THM_EVTCENTERAPP_TEXT 										(COLOR_WHITE)

  //FILE MANAGER APP
#define DEF_THM_FILEMGRAPP_BG 											(COLOR_WHITE)

  //FM RADIO APP
//#define DEF_THM_FMRADIOAPP_TEXT 										(COLOR_WHITE)
//#define DEF_THM_FMRADIOAPP_BG 										(COLOR_BLACK)
//#define DEF_THM_FMRADIOAPP_POS_TEXT 									(COLOR_BLUE_8)

//FRUIT GAMBLE GAME APP
//#define DEF_THM_FRUITGAMBLEAPP_TEXT 									(COLOR_WHITE)
//#define DEF_THM_FRUITGAMBLEAPP_INPUT_TEXT								(COLOR_RED_5)

//KEY GUARD APP
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_TIME_TEXT 					(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_TEXT   						(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_DIAL_NUMBER_TEXT   			(COLOR_WHITE)
//#define DEF_THM_KEYGUARDAPP_KEYPAD_LOCKED_DATE_TEXT 					(COLOR_GREY_5)

	//MAP APP
#define DEF_THM_MAPAPP_CALENDAR_HIGHLIGHT_BORDER  						(COLOR_BLUE_3)
#define DEF_THM_MAPAPP_CALENDAR_DAY_TEXT  								(COLOR_WHITE)
#define DEF_THM_MAPAPP_BG	  											(COLOR_BLACK)

	//MESSAGE EDITOR APP
#define DEF_THM_MSGEDITORAPP_RECIPIENT_FONT  							(COLOR_BLACK)
#define DEF_THM_MSGEDITORAPP_FONT_DEFAULT  								(COLOR_BLACK)

	//MPLAYER APP
//#define DEF_THM_MPLAYERAPP_PLAYLIST_TEXT								(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_BG								(COLOR_BLACK)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_LYRICS_TEXT						(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_TITLE_TEXT						(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_ALBUM_TEXT						(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_ARTIST_TEXT						(COLOR_GREY_5)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_TIME_TEXT						(COLOR_WHITE)
//#define DEF_THM_MPLAYERAPP_NOWPLAYING_LISTINDEX_TEXT					(COLOR_GREY_4)

	//OFF APP
#define DEF_THM_OFFAPP_BUTTON_TEXT  									(COLOR_GREY_1)

	//ON APP
//#define DEF_THM_ONAPP_BG												(COLOR_BLACK)

	//PHONE BOOK APP
#define DEF_THM_PHBAPP_TEXT 											(COLOR_BLACK)

	//PROFILE APP
#define DEF_THM_PROFILEAPP_BG 											(COLOR_WHITE)

	//SEC APP
#define DEF_THM_SECAPP_BG 												(COLOR_GREY_3)

	//SNOTE APP
#define DEF_THM_SNOTEAPP_MENUGRID_BG 									(COLOR_WHITE)

	//VIDEO PLAYER APP
#define DEF_THM_VIDEOPLAYERAPP_TEXT_1 									(COLOR_ORANGE_4)
#define DEF_THM_VIDEOPLAYERAPP_TEXT_2 									(COLOR_WHITE)
#define DEF_THM_VIDEOPLAYERAPP_TEXT_3									(COLOR_WHITE)

	//VIDEO TELEPHONE APP
#define DEF_THM_VIDEOTELEAPP_STATES_TEXT 								(COLOR_GREEN_2)
#define DEF_THM_VIDEOTELERAPP_OUTLINE 									(COLOR_WHITE)
#define DEF_THM_VIDEOTELERAPP_INFO_1_TEXT 								(COLOR_BLUE_1)
#define DEF_THM_VIDEOTELERAPP_INFO_2_TEXT 								(COLOR_GREEN_2)
#define DEF_THM_VIDEOTELERAPP_INFO_3_TEXT 								(COLOR_BLACK)
#define DEF_THM_VIDEOTELERAPP_INPUT 									(COLOR_WHITE)

	//VOICE MEMO APP
#define DEF_THM_VOICEMEMOAPP_TEXT 										(COLOR_ORANGE_4)

//***************END NOT RS_************************

// BT APP
#define DEF_THM_BTAPP_DOWNITEM_HIGHLIGHT_TEXT							(COLOR_GREY_7)

//MESSAGE EDITOR APP_MMS
#define DEF_THM_MSGEDITORAPP_MMS_ADDTEXT_BG								(COLOR_GREEN_8)
#define DEF_THM_MSGEDITORAPP_MMS_NO_CONTENT_TEXT						(COLOR_GREY_3)

	//CALENDAR APP
#define	DEF_THM_CALENDARAPP_WEEKDAY_TEXT								(COLOR_WHITE)
#define DEF_THM_CALENDARAPP_DAY_HIGHLIGHT_TEXT							(COLOR_BLACK)

	//MAIN MENU APP
	#define DEF_THM_MAINMENUAPP_TEXT									(COLOR_GREEN_9) //C23
#define DEF_THM_MAINMENUAPP_TEXT_OUTLINE								(COLOR_WHITE)   //C23_2

	//DIALER APP
#define DEF_THM_DIALERAPP_BG											(COLOR_GREY_4)
#define DEF_THM_DIALERAPP_TEXT											(COLOR_BLACK)
#define DEF_THM_DIALERAPP_CURSOR										(COLOR_BLACK)

#define	DEF_THM_COMMON_COLOR_TAB_BG										(0XFFD8E8F8)		//
#define	DEF_THM_COMMON_COLOR_TAB_INACT									(0XFF68B8C8)		//
#define	DEF_THM_COMMON_COLOR_TAB_ACT									(0XFFC8D0D8)		//

#define DEF_THM_WDG_PULLDOWN_TEXT										(COLOR_BLACK)
#define DEF_THM_WDG_PULLDOWN_UNFOCUS_BG									(RGBCOLOR_WHITE)
#define DEF_THM_WDG_PULLDOWN_HIGHLIGHT_TEXT								(RGBCOLOR_WHITE)
#define DEF_THM_WDG_PULLDOWN_FOCUS_BG									(RGBCOLOR_BLUE)
#define DEF_THM_WDG_PULLDOWN_DROPLIST_BORDER							(RGBCOLOR_BLUE)


#endif //__THEME_COLOR_THEME2__


#endif //__MMI_COMMON_COLOR_DEF_H__

