
#ifndef __MMI_COMMON_FMSCH_TYPE_H__
#define __MMI_COMMON_FMSCH_TYPE_H__

typedef enum
{
    FMSCHAPP_START_TYPE_NORMAL = 0,

    FMSCHAPP_START_TYPE_FM_SCHEDULE = FMSCHAPP_START_TYPE_NORMAL,
    FMSCHAPP_START_TYPE_FM_SCHEDULE_RECORD,

    FMSCHAPP_START_TYPE_MAX,

} FmSchAppStartType_e;

#endif //__MMI_COMMON_FMSCH_TYPE_H__
