/**
 * @file	mmi_common_rai_id.h
 * @brief	This file defines the RAI id used in MMI.
 * @version	$Id: mmi_common_rai_id.h 41287 2009-09-24 06:22:46Z joe.hsu $
 */
#ifndef __MMI_COMMON_RAI_ID_H__
#define __MMI_COMMON_RAI_ID_H__

#include "mmi_mae_rai_id.h"

//#include "mmi_notepadapp.h"
#include "mmi_phbsrv_def.h"
#include "mmi_phbsrv_data_handle.h"
#include "mmi_common_sms_master.h"
#include "mmi_cfgsrv.h"
#include "mmi_wlan_msgdef.h"

typedef struct
{
    u32 startId;
    u32 endId;
} RAI_Class_t;

enum
{
    MMI_RAI_CONFIG = 0,
    MMI_RAI_SMS,
    MMI_RAI_PHONEBOOK,
    MMI_RAI_CALLLOG,
    MMI_RAI_NOTEPAD,
    MMI_RAI_ALARMSRV,
    MMI_RAI_SCHEDULERSRV,
    MMI_RAI_CALIBRATION,
    MMI_RAI_BLUETOOTH,
    MMI_RAI_CALLSETTING,
    MMI_RAI_MMSRV,
    MMI_RAI_BMI,
    MMI_RAI_INPUT,
    MMI_RAI_HASHMAP,
    MMI_RAI_ATV,
    MMI_RAI_WLAN,
    MMI_RAI_MSGBLACKLIST,
    MMI_RAI_MSGBLACKLIST_KEYWORD,
    MMI_RAI_GADGET,
#if defined (__UI_STYLE_MMI_IFONE__) || defined(__UI_STYLE_MMI_STYLE_SWITCH__)
    MMI_RAI_MAINMENU,
#endif
    MMI_RAI_SHORTCUTPHB,
    MMI_RAI_HAMSTERFIGHT,
    MMI_RAI_LINKUP,
    MMI_RAI_PUZZLE,
    MMI_RAI_SUDOKU,
#ifdef __APP_MMI_TUDOU__
    MMI_RAI_TUDOU,
#endif
    MMI_RAI_EMU
};

/*
=======================================Notice=====================================
 Todo!	If there is new RAI class, RAI_Class_Table_ID should also be updated.
 		RAI_Class_Table_ID defined at end of this file.
 ================================================================================
 */
enum
{
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_CONFIG),


    MMI_FS_RAI_ITEM_CONFIG_CITEM_START,
    MMI_FS_RAI_ITEM_CONFIG_CITEM_END = (MMI_FS_RAI_ITEM_CONFIG_CITEM_START+CFGSRV_SUPPORT_MAX_FILES_IN_CACHE_CLASS-1),


    MMI_FS_RAI_ITEM_CONFIG_ALLOW_MR_MITEM_START,
    MMI_FS_RAI_ITEM_CONFIG_ALLOW_MR_MITEM_END = (MMI_FS_RAI_ITEM_CONFIG_ALLOW_MR_MITEM_START+CFGSRV_SUPPORT_MAX_FILES_IN_MR_CLASS-1),


    MMI_FS_RAI_ITEM_CONFIG_NOT_ALLOW_MR_MITEM_START,
    MMI_FS_RAI_ITEM_CONFIG_NOT_ALLOW_MR_MITEM_END = (MMI_FS_RAI_ITEM_CONFIG_NOT_ALLOW_MR_MITEM_START+CFGSRV_SUPPORT_MAX_FILES_IN_NMR_CLASS-1),


    MMI_FS_RAI_ITEM_INFO_ITEM_START,
    MMI_FS_RAI_ITEM_INFO_ITEM_END = (MMI_FS_RAI_ITEM_INFO_ITEM_START+CFGSRV_SUPPORT_MAX_FILES_IN_INFO_CLASS-1),

    MMI_FS_RAI_ITEM_CONFIG_EM_SETTING,

    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CONFIG),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_SMS),

    MMI_FS_RAI_ITEM_SMS_RAWDATA_START,
    MMI_FS_RAI_ITEM_SMS_RAWDATA_END = (MMI_FS_RAI_ITEM_SMS_RAWDATA_START + MAX_PHONE_MSG_AMOUNT),

    MMI_FS_RAI_ITEM_SMS_CURRENT_MAP,

    MMI_FS_RAI_ITEM_SMS_INBOX_1,
    MMI_FS_RAI_ITEM_SMS_INBOX_2,
    MMI_FS_RAI_ITEM_SMS_INBOX_3,
    MMI_FS_RAI_ITEM_SMS_INBOX_4,
    MMI_FS_RAI_ITEM_SMS_INBOX_5,

    MMI_FS_RAI_ITEM_SMS_OUTBOX_1,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_2,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_3,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_4,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_5,

    MMI_FS_RAI_ITEM_SMS_SENTBOX_1,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_2,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_3,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_4,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_5,

    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_1,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_2,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_3,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_4,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_5,
    MMI_FS_RAI_ITEM_SMS_PMBOX_1,
    MMI_FS_RAI_ITEM_SMS_PMBOX_2,
    MMI_FS_RAI_ITEM_SMS_PMBOX_3,
    MMI_FS_RAI_ITEM_SMS_PMBOX_4,
    MMI_FS_RAI_ITEM_SMS_PMBOX_5,

    MMI_FS_RAI_ITEM_SMS_TNBOX_1,
    MMI_FS_RAI_ITEM_SMS_TNBOX_2,

    MMI_FS_RAI_ITEM_SMS_INBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_INBOX_TEMP_2,
    MMI_FS_RAI_ITEM_SMS_INBOX_TEMP_3,
    MMI_FS_RAI_ITEM_SMS_INBOX_TEMP_4,
    MMI_FS_RAI_ITEM_SMS_INBOX_TEMP_5,

    MMI_FS_RAI_ITEM_SMS_OUTBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_TEMP_2,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_TEMP_3,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_TEMP_4,
    MMI_FS_RAI_ITEM_SMS_OUTBOX_TEMP_5,

    MMI_FS_RAI_ITEM_SMS_SENTBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_TEMP_2,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_TEMP_3,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_TEMP_4,
    MMI_FS_RAI_ITEM_SMS_SENTBOX_TEMP_5,

    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_TEMP_2,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_TEMP_3,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_TEMP_4,
    MMI_FS_RAI_ITEM_SMS_DRAFTBOX_TEMP_5,

    MMI_FS_RAI_ITEM_SMS_PMBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_PMBOX_TEMP_2,
    MMI_FS_RAI_ITEM_SMS_PMBOX_TEMP_3,
    MMI_FS_RAI_ITEM_SMS_PMBOX_TEMP_4,
    MMI_FS_RAI_ITEM_SMS_PMBOX_TEMP_5,

    MMI_FS_RAI_ITEM_SMS_TNBOX_TEMP_1,
    MMI_FS_RAI_ITEM_SMS_TNBOX_TEMP_2,

    MMI_FS_RAI_ITEM_SMS_MSGIDFILE,
    MMI_FS_RAI_ITEM_SMS_MSGIDFILE_TEMP,
    MMI_FS_RAI_ITEM_SMS_RAWDATA_TEMP,

    MMI_FS_RAI_ITEM_SMS_RAWDATA_MEMOREISE_LIST,
    MMI_FS_RAI_ITEM_SMS_RAWDATA_MEMOREISE_LIST_LEN,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SMS),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_PHONEBOOK),

    MMI_FS_RAI_ITEM_PHB_ADR_START,
    MMI_FS_RAI_ITEM_PHB_ADR_END = (MMI_FS_RAI_ITEM_PHB_ADR_START + MMI_PHB_ADR_SUPPORT_MAX),

    MMI_FS_RAI_ITEM_PHB_ADN_M_BACKUP_DATA_START,
    MMI_FS_RAI_ITEM_PHB_ADN_M_BACKUP_DATA_END = (MMI_FS_RAI_ITEM_PHB_ADN_M_BACKUP_DATA_START + MMI_PHB_ADN_SUPPORT_MAX),
    MMI_FS_RAI_ITEM_PHB_ADN_S_BACKUP_DATA_START,
    MMI_FS_RAI_ITEM_PHB_ADN_S_BACKUP_DATA_END = (MMI_FS_RAI_ITEM_PHB_ADN_S_BACKUP_DATA_START + MMI_PHB_ADN_SUPPORT_MAX),

#ifndef __MMI_PHB_DISABLE_BLACKLIST__
    MMI_FS_RAI_ITEM_PHB_BLACKLIST_STORE_DATA_START,
    MMI_FS_RAI_ITEM_PHB_BLACKLIST_STORE_DATA_END = (MMI_FS_RAI_ITEM_PHB_BLACKLIST_STORE_DATA_START + MMI_PHB_BLACKLIST_SUPPORT_MAX),
#endif // #ifndef __MMI_PHB_DISABLE_BLACKLIST__

    MMI_FS_RAI_ITEM_PHB_HASH_BY_NUMBER_TABLE,
    MMI_FS_RAI_ITEM_PHB_HASH_BY_NUMBER_TABLE_MAX = (MMI_FS_RAI_ITEM_PHB_HASH_BY_NUMBER_TABLE+MMI_PHB_HASH_BY_NUMBER_TABLE_MAX_RAI_PARTITION),

    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_ADR_ADN_M_ADN_S,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_ADR_ADN_M_ADN_S_MAX = (MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_ADR_ADN_M_ADN_S+MMI_PHB_SORT_BY_NAME_ADR_ADN_M_ADN_S_MAX_RAI_PARTITION),

    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_FIRST_CHAR,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_ALPHABET,

#ifdef __NAND_MMI__				/* to store more information in sorting table for NAND slowly READ */
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NAME,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NAME_MAX = (MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NAME+MMI_PHB_SORT_BY_NAME_NAME_MAX_RAI_PARTITION),

    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NUMBER,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NUMBER_MAX = (MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_NUMBER+MMI_PHB_SORT_BY_NAME_NUMBER_MAX_RAI_PARTITION),

    MMI_FS_RAI_ITEM_PHB_PRE_NUM_LIST, /* for PreNumList   2010-08-06 by Robin */

#ifdef __UNICODE_TO_STROKE__
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_STROKE,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_STROKE_MAX = (MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_STROKE+MMI_PHB_SORT_BY_NAME_STROKE_MAX_RAI_PARTITION),
#endif /* __UNICODE_TO_STROKE__ */
#endif /* __NAND_MMI__ */

    MMI_FS_RAI_ITEM_PHB_GROUP_CG01,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG02,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG03,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG04,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG05,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG06,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG07,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG08,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG09,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG10,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG11,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG12,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG13,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG14,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG15,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG16,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG17,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG18,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG19,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG20,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG21,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG22,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG23,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG24,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG25,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG26,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG27,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG28,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG29,
    MMI_FS_RAI_ITEM_PHB_GROUP_CG30,
    MMI_FS_RAI_ITEM_PHB_GROUP_ALL,

    MMI_FS_RAI_ITEM_PHB_GROUP_BLACK_LIST,
    MMI_FS_RAI_ITEM_PHB_GROUP_URL,
    MMI_FS_RAI_ITEM_PHB_GROUP_EMAIL,

    MMI_FS_RAI_ITEM_PHB_ADR_FILTER,

    MMI_FS_RAI_ITEM_PHB_FDN_BACKUP,
    MMI_FS_RAI_ITEM_PHB_CHECKSUM_M,
    MMI_FS_RAI_ITEM_PHB_CHECKSUM_S,
    MMI_FS_RAI_ITEM_PHB_ADN_RECOVERY,
    MMI_FS_RAI_ITEM_PHB_SRV_INFO,

#ifndef __MMI_PHB_DISABLE_BLACKLIST__
#ifdef __MMI_PHB_BK_WITH_SORTING__
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_BK,
    MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_BK_MAX = (MMI_FS_RAI_ITEM_PHB_SORT_BY_NAME_BK+MMI_PHB_SORT_BY_NAME_BK_MAX_RAI_PARTITION),
#endif
#endif // #ifndef __MMI_PHB_DISABLE_BLACKLIST__
    MMI_FS_RAI_ITEM_PHB_HASH_BY_NUMBER_TABLE_BK,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_PHONEBOOK),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_CALLLOG),
    MMI_FS_RAI_ITEM_CALLLOG_HEADER,
    MMI_FS_RAI_ITEM_CALLLOG_MISSED,
    MMI_FS_RAI_ITEM_CALLLOG_RECEIVED,
    MMI_FS_RAI_ITEM_CALLLOG_DIALED,
#if !defined(__MMI_PHB_DISABLE_BLACKLIST__) && defined(__MMI_CALLLOG_SUPPORT_BKLOG__)
    MMI_FS_RAI_ITEM_CALLLOG_BLOCK,
#endif /* __MMI_CALLLOG_SUPPORT_BKLOG__ */
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALLLOG),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_NOTEPAD),
    MMI_FS_RAI_ITEM_NOTEPAD_IDX_TBL,
    MMI_FS_RAI_ITEM_NOTEPAD_NOTE_START,
    MMI_FS_RAI_ITEM_NOTE_END = (MMI_FS_RAI_ITEM_NOTEPAD_NOTE_START + MMI_NOTEPAD_MAX_NOTE),
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_NOTEPAD),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_ALARMSRV),
    MMI_FS_RAI_ITEM_ALARM_1,
    MMI_FS_RAI_ITEM_ALARM_2,
    MMI_FS_RAI_ITEM_ALARM_3,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_ALARMSRV),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_SCHEDULERSRV),
    MMI_FS_RAI_ITEM_SCHSRV_INFO,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SCHEDULERSRV),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_CALIBRATION),
    MMI_FS_RAI_ITEM_CALIBRATION_FILE_ID,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALIBRATION),
/*
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_MMSRV),
	MMI_FS_RAI_ITEM_NITZ_NETWORK_INFO,
	MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MMSRV),
*/
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_CALLSETTING),
    MMI_FS_RAI_ITEM_CALL_DIVERT_NO,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALLSETTING),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_BLUETOOTH),
    MMI_FS_RAI_ITEM_BLUETOOTH_FILE_ID,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_BLUETOOTH),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_BMI),
    MMI_FS_RAI_ITEM_BMI_RECORD,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_BMI),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_INPUT),
    MAE_FS_RAI_ITEM_INPUT_LATIN_WORD_DICTIONARY,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_INPUT),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_HASHMAP),
    MMI_FS_RAI_ITEM_HASHMAP_IDX_TBL,
    MMI_FS_RAI_ITEM_HASHMAP_START,
    MMI_FS_RAI_ITEM_HASHMAP_END = (MMI_FS_RAI_ITEM_HASHMAP_START + COMMON_STORE_MAX),
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_HASHMAP),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_ATV),
    MMI_FS_RAI_ITEM_ATV_INFO_ID,
    MMI_FS_RAI_ITEM_ATV_CHANNEL_ID,
    MMI_FS_RAI_ITEM_ISDBT_INFO_ID,
    MMI_FS_RAI_ITEM_ISDBT_CHANNEL_ID,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_ATV),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_WLAN),
    MMI_FS_RAI_ITEM_WLAN_CONNECT_INFO,
    MMI_FS_RAI_ITEM_WLAN_FILTER_INFO,
    MMI_FS_RAI_ITEM_WLAN_CERT,
    MMI_FS_RAI_ITEM_WLAN_CERT_CONTENT_START,
    MMI_FS_RAI_ITEM_WLAN_CERT_CONTENT_END=MMI_FS_RAI_ITEM_WLAN_CERT_CONTENT_START + WLANSRV_MAX_CERT_NUM*WLANSRV_CERT_FORMAT_PATHPAIR - 1,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_WLAN),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_MSGBLACKLIST),
    MMI_FS_RAI_ITEM_MSG_BLACKLIST_STORE_DATA,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MSGBLACKLIST),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_MSGBLACKLIST_KEYWORD),
    MMI_FS_RAI_ITEM_MSG_BLACKLIST_KEYWORD_STORE_DATA,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MSGBLACKLIST_KEYWORD),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_GADGET),
    MMI_FS_RAI_ITEM_GADGET_INFO,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_GADGET),

#if defined (__UI_STYLE_MMI_IFONE__) || defined (__UI_STYLE_MMI_STYLE_SWITCH__)
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_MAINMENU),
    MMI_FS_RAI_ITEM_MAINMENU_IFONE_MENUITEM,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MAINMENU),
#endif

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_SHORTCUTPHB),
    MMI_FS_RAI_ITEM_SHORTCUTPHB_INFO,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SHORTCUTPHB),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_LINKUP),
    MMI_FS_RAI_ITEM_LINKUP_RECORD_SOUND,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_LINKUP),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_PUZZLE),
    MMI_FS_RAI_ITEM_PUZZLE_SETTING,
    MMI_FS_RAI_ITEM_PUZZLE_SOUND,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_PUZZLE),

    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_SUDOKU),
    MMI_FS_RAI_ITEM_SUDOKU_TIME,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SUDOKU),

#ifdef __APP_MMI_TUDOU__
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_TUDOU),
    MMI_FS_RAI_ITEM_TUDOU_SEARCH_HISTORY,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_TUDOU),
#endif
    MMI_FS_RAI_ITEM_START_ID(MMI_RAI_EMU),
    MMI_FS_RAI_ITEM_EMU_KEYPAD_SETTINGS,
    MMI_FS_RAI_ITEM_END_ID(MMI_RAI_EMU)

};

#define RAI_CLASS_NUM (22)
#ifdef __MAE_UTIL_FS_C__
const RAI_Class_t RAI_Class_Table_ID[RAI_CLASS_NUM] =
{
    /* Todo! We cannot get the range of MAE rai items. We can only hack it
    by adding a contant. Currently it is 2048.*/
    {MAE_FS_RAI_START_ID, MAE_FS_RAI_START_ID+2048},
    {DRM_KEY_RAI_START_ID, DRM_KEY_RAI_START_ID+DRM_KEY_RAI_SIZE-1},
    {M_MMI_RAI_CONFIG_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CONFIG)},
    {M_MMI_RAI_SMS_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SMS)},
    {M_MMI_RAI_PHONEBOOK_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_PHONEBOOK)},
    {M_MMI_RAI_CALLLOG_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALLLOG)},
    {M_MMI_RAI_NOTEPAD_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_NOTEPAD)},
    {M_MMI_RAI_ALARMSRV_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_ALARMSRV)},
    {M_MMI_RAI_CALIBRATION_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALIBRATION)},
	//{M_MMI_RAI_MMSRV_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MMSRV)},
    {M_MMI_RAI_CALLSETTING_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_CALLSETTING)},
    {M_MMI_RAI_BLUETOOTH_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_BLUETOOTH)},
    {M_MMI_RAI_BMI_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_BMI)},
    {M_MMI_RAI_INPUT_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_INPUT)},
    {M_MMI_RAI_HASHMAP_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_HASHMAP)},
    {M_MMI_RAI_ATV_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_ATV)},
    {M_MMI_RAI_WLAN_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_WLAN)},
    {M_MMI_RAI_MSGBLACKLIST_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MSGBLACKLIST)}, // add by dongnan
    {M_MMI_RAI_MSGBLACKLIST_KEYWORD_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_MSGBLACKLIST_KEYWORD)}, // add by dongnan
    {M_MMI_RAI_GADGET_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_GADGET)},
    {M_MMI_RAI_SHORTCUTPHB_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_SHORTCUTPHB)},
    {M_MMI_RAI_EMU_START, MMI_FS_RAI_ITEM_END_ID(MMI_RAI_EMU)}
};
#else
extern const RAI_Class_t RAI_Class_Table_ID[RAI_CLASS_NUM];
#endif

#endif /*__MMI_COMMON_RAI_ID_H__ */
