/**
 * @file	widget_layout_hvga_320_480.h
 * @brief
 * @author
 * @version	2011/08/04, 15:28:51
*/

#ifndef __WIDGET_LAYOUT_HVGA_320_480_H__
#define __WIDGET_LAYOUT_HVGA_320_480_H__

#define	    STATUSBAR_ICON_SEGMENT_PROPORTION_RIGHT  1
#define	    STATUSBAR_ICON_SEGMENT_PROPORTION_LEFT   0

// Define right-side icon to be 1, and left-side icon to be 0
#define	    STATUSBAR_ICON_POS_SIDE_BG               1
#define	    STATUSBAR_ICON_POS_SIDE_TIMETEXT         1
#define	    STATUSBAR_ICON_POS_SIDE_USRPROFILE       1
#define	    STATUSBAR_ICON_POS_SIDE_VIBRATEING       1
#define	    STATUSBAR_ICON_POS_SIDE_BATT             1
#define	    STATUSBAR_ICON_POS_SIDE_RSSI             1
#define	    STATUSBAR_ICON_POS_SIDE_SLAVE_RSSI       1
#define	    STATUSBAR_ICON_POS_SIDE_ROAMING          1
#define	    STATUSBAR_ICON_POS_SIDE_NTYPE_HEGPRS     1
#define	    STATUSBAR_ICON_POS_SIDE_SLAVE_NTYPE      1
#define	    STATUSBAR_ICON_POS_SIDE_NTYPE_WIFI       1
#define	    STATUSBAR_ICON_POS_SIDE_CCSS             1
#define	    STATUSBAR_ICON_POS_SIDE_SLAVE_CCSS       1
#define	    STATUSBAR_ICON_POS_SIDE_WAPMSG1          1
#define	    STATUSBAR_ICON_POS_SIDE_WAPMSG2          1
#define	    STATUSBAR_ICON_POS_SIDE_BLOCKCALL        1
#define	    STATUSBAR_ICON_POS_SIDE_MISSCALL         1
#define	    STATUSBAR_ICON_POS_SIDE_ALARM            1
#define	    STATUSBAR_ICON_POS_SIDE_OTHERIMG         1
#define	    STATUSBAR_ICON_POS_SIDE_MEDIAPLAYING     1
#define	    STATUSBAR_ICON_POS_SIDE_QQ               1
#define	    STATUSBAR_ICON_POS_SIDE_BT               1

enum StatusBarIconPriority_Right_tag
{
	STATUSBAR_PRIORITY_BG,
    STATUSBAR_PRIORITY_TIMETEXT,
	STATUSBAR_PRIORITY_USRPROFILE,
#if !defined(__LCM_QQVGA_MMI__) && !defined(__MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__)
	STATUSBAR_PRIORITY_VIBRATEING,
#endif
	STATUSBAR_PRIORITY_BATT,
	STATUSBAR_PRIORITY_RSSI,
#ifdef __DUAL_SIM_MMI__
	STATUSBAR_PRIORITY_SLAVE_RSSI,
#endif
	STATUSBAR_PRIORITY_ROAMING,
	STATUSBAR_PRIORITY_NTYPE_HEGPRS,
#if defined(__DUAL_SIM_MMI__) && defined(__SLAVE_NTYPE_IN_STATBAR__)
	STATUSBAR_PRIORITY_SLAVE_NTYPE,
#endif
#ifdef __WLAN_MMI__
	STATUSBAR_PRIORITY_NTYPE_WIFI,
#endif
	STATUSBAR_PRIORITY_CCSS,
#ifdef __DUAL_SIM_MMI__
	STATUSBAR_PRIORITY_SLAVE_CCSS,
#endif
	STATUSBAR_PRIORITY_WAPMSG1,
	STATUSBAR_PRIORITY_WAPMSG2,
#if !defined(__MMI_PHB_DISABLE_BLACKLIST__) && defined(__MMI_CALLLOG_SUPPORT_BKLOG__)
	STATUSBAR_PRIORITY_BLOCKCALL,
#endif
#ifdef __MMI_STATUSBAR_SUPPORT_MISSED_CALL__
	STATUSBAR_PRIORITY_MISSCALL,
#endif
	STATUSBAR_PRIORITY_ALARM,
	STATUSBAR_PRIORITY_OTHERIMG,
	STATUSBAR_PRIORITY_MEDIAPLAYING,
#ifdef __NCCQQ_MMI__
    STATUSBAR_PRIORITY_QQ,
#endif
	STATUSBAR_PRIORITY_BT
};
/*
enum StatusBarIconPriority_Left_tag
{

};
*/

#ifdef __DUAL_LCD__     /*<----- Sub LCD -----*/

#define	    SUB_STATUSBAR_ICON_SEGMENT_PROPORTION_RIGHT  1
#define	    SUB_STATUSBAR_ICON_SEGMENT_PROPORTION_LEFT   0

// Define right-side icon to be 1, and left-side icon to be 0

#define	    SUB_STATUSBAR_ICON_POS_SIDE_BG               1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_TIMETEXT         1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_USRPROFILE       1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_VIBRATEING       1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_BATT             1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_RSSI             1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_SLAVE_RSSI       1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_ROAMING          1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_NTYPE_HEGPRS     1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_SLAVE_NTYPE      1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_NTYPE_WIFI       1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_CCSS             1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_SLAVE_CCSS       1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_WAPMSG1          1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_WAPMSG2          1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_BLOCKCALL        1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_MISSCALL         1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_ALARM            1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_OTHERIMG         1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_MEDIAPLAYING     1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_QQ               1
#define	    SUB_STATUSBAR_ICON_POS_SIDE_BT               1

enum Sub_StatusBarIconPriority_Right_tag
{
	SUB_STATUSBAR_PRIORITY_BG,
    SUB_STATUSBAR_PRIORITY_TIMETEXT,
	SUB_STATUSBAR_PRIORITY_USRPROFILE,
#if !defined(__LCM_QQVGA_MMI__) && !defined(__MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__)
	SUB_STATUSBAR_PRIORITY_VIBRATEING,
#endif
    SUB_STATUSBAR_PRIORITY_BATT,
    SUB_STATUSBAR_PRIORITY_RSSI,
#ifdef __DUAL_SIM_MMI__
	SUB_STATUSBAR_PRIORITY_SLAVE_RSSI,
#endif
	SUB_STATUSBAR_PRIORITY_ROAMING,
	SUB_STATUSBAR_PRIORITY_NTYPE_HEGPRS,
#if defined(__DUAL_SIM_MMI__) && defined(__SLAVE_NTYPE_IN_STATBAR__)
	SUB_STATUSBAR_PRIORITY_SLAVE_NTYPE,
#endif
#ifdef __WLAN_MMI__
	SUB_STATUSBAR_PRIORITY_NTYPE_WIFI,
#endif
	SUB_STATUSBAR_PRIORITY_CCSS,
#ifdef __DUAL_SIM_MMI__
	SUB_STATUSBAR_PRIORITY_SLAVE_CCSS,
#endif
	SUB_STATUSBAR_PRIORITY_WAPMSG1,
	SUB_STATUSBAR_PRIORITY_WAPMSG2,
#if !defined(__MMI_PHB_DISABLE_BLACKLIST__) && defined(__MMI_CALLLOG_SUPPORT_BKLOG__)
	SUB_STATUSBAR_PRIORITY_BLOCKCALL,
#endif
#ifdef __MMI_STATUSBAR_SUPPORT_MISSED_CALL__
	SUB_STATUSBAR_PRIORITY_MISSCALL,
#endif
	SUB_STATUSBAR_PRIORITY_ALARM,
	SUB_STATUSBAR_PRIORITY_OTHERIMG,
	SUB_STATUSBAR_PRIORITY_MEDIAPLAYING,
#ifdef __NCCQQ_MMI__
    SUB_STATUSBAR_PRIORITY_QQ,
#endif
	SUB_STATUSBAR_PRIORITY_BT
};
/*
enum Sub_StatusBarIconPriority_Left_tag
{

};
*/

#endif  /* __DUAL_LCD__ */

#endif	/* __MMI_LAYOUT_HVGA_320_480_H__ */
