ApBegin(RS,CLSID_EMAPP)
	WndBegin(EMAPP_WND_MAINLIST)
		WdgBegin(CLSID_VTMMENU, MainListVtm)
            VtmCreateMenuRC(IMG_NULL_ID,TXT_LTL_N_NO_TITLE,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0)
        WdgEnd(CLSID_VTMMENU,MainListVtm)
    WndEnd(EMAPP_WND_MAINLIST)

    WndBegin(EMAPP_WND_EDIT)
        WdgBegin(CLSID_VTMINPUT, EditVtm)
			VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,0,FALSE})
		WdgEnd(CLSID_VTMINPUT, EditVtm)
    WndEnd(EMAPP_WND_EDIT)

    WndBegin(EMAPP_WND_DISPLAYAUTOTESTRESULT)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_BACK})
        WndSetTitleRC({IMG_NULL_ID,TXT_NULL_ID})
        WdgBegin(CLSID_INPUTWIDGET,InputWidget)
            WdgInputCreateForWndRC({{0,0},{0,0},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetMaxByteLengthRC(60)
            WdgInputSetMultilineRC(TRUE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_VIEWONLY)
            WdgInputSetFontSizeRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_INPUTWIDGET,InputWidget)
        WdgBegin(CLSID_BUTTONWIDGET,SendKeyButtonWidget)
            WdgButtonCreateForWndRC({{0,0},{0,0},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,IMG_NULL_ID})
        WdgEnd(CLSID_BUTTONWIDGET,SendKeyButtonWidget)
        WdgBegin(CLSID_BUTTONWIDGET,EndKeyButtonWidget)
            WdgButtonCreateForWndRC({{0,0},{0,0},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IMG_NULL_ID,IMG_NULL_ID})
        WdgEnd(CLSID_BUTTONWIDGET,EndKeyButtonWidget)
    WndEnd(EMAPP_WND_DISPLAYAUTOTESTRESULT)

    WndBegin(EMAPP_WND_MENUHISTORY)
		WdgBegin(CLSID_VTMMENU,MenuHistoryVtm)
            VtmCreateMenuRC(IMG_NULL_ID,TXT_LTL_N_NO_TITLE,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0)
        WdgEnd(CLSID_VTMMENU,MenuHistoryVtm)
    WndEnd(EMAPP_WND_MENUHISTORY)

    WndBegin(EMAPP_WND_ASYNCINFO)
        WdgBegin(CLSID_VTMMENU, AsyncInfoVtm)
			VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,0,TRUE})
		WdgEnd(CLSID_VTMMENU, AsyncInfoVtm)
    WndEnd(EMAPP_WND_ASYNCINFO)

    WndBegin(EMAPP_WND_SYNCINFO)
        WdgBegin(CLSID_VTMMENU, SyncInfoVtm)
			VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,0,TRUE})
		WdgEnd(CLSID_VTMMENU, SyncInfoVtm)
    WndEnd(EMAPP_WND_SYNCINFO)

    WndBegin(EMAPP_WND_FMRADIO)
        WdgBegin(CLSID_VTMMENU, FmRadioVtm)
			VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,0,TRUE})
		WdgEnd(CLSID_VTMMENU, FmRadioVtm)
    WndEnd(EMAPP_WND_FMRADIO)

/*
    WndBegin(EMAPP_WND_KEYPADTEST)

    WndEnd(EMAPP_WND_KEYPADTEST)
*/
    WndBegin(EMAPP_WND_TOUCHPANELTEST)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_NONE, SK_CANCEL})
        WdgBegin(CLSID_TEXTWIDGET,TextWidget)
            WdgTextCreateForWndRC({{MAIN_DEFVIEW_X,MAIN_DEFVIEW_Y},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_EMAPP_TOUCHPANELTEST_TEXT)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_ELLIPSIS)
            WdgTextSetFontHeightRC(MAIN_LCD_ONELINE_HEIGHT)
        WdgEnd(CLSID_TEXTWIDGET,TextWidget)
    WndEnd(EMAPP_WND_TOUCHPANELTEST)
    WndBegin(EMAPP_WND_ATV)
        WndSetAllSoftkeyRC({SK_NONE, SK_NONE, SK_BACK})
        WdgBegin(CLSID_OSDWIDGET,OsdWidget)
            WdgOsdCreateForWndRC({{0,0},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT}})
        WdgEnd(CLSID_OSDWIDGET,OsdWidget)
        WdgBegin(CLSID_TEXTWIDGET,TfTextWidget)
            WdgTextCreateForWndRC({{EMAPP_ATV_TF_TEXTWIDGET_X_POSITION,EMAPP_ATV_TF_TEXTWIDGET_Y_POSITION},{EMAPP_ATV_TF_TEXTWIDGET_WIDTH,EMAPP_ATV_TF_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_EMAPP_TEXT)
            WdgCommonSetAlignmentRC(0)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetFontTypeRC(FONT_TYPE_EXPAND1)
        WdgEnd(CLSID_TEXTWIDGET,TfTextWidget)
        WdgBegin(CLSID_TEXTWIDGET,TgTextWidget)
            WdgTextCreateForWndRC({{EMAPP_ATV_TG_TEXTWIDGET_X_POSITION,EMAPP_ATV_TG_TEXTWIDGET_Y_POSITION},{EMAPP_ATV_TG_TEXTWIDGET_WIDTH,EMAPP_ATV_TG_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_EMAPP_TEXT)
            WdgCommonSetAlignmentRC(0)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetFontTypeRC(FONT_TYPE_EXPAND1)
        WdgEnd(CLSID_TEXTWIDGET,TgTextWidget)
        WdgBegin(CLSID_TEXTWIDGET,Bit2TextWidget)
            WdgTextCreateForWndRC({{EMAPP_ATV_BIT2_TEXTWIDGET_X_POSITION,EMAPP_ATV_BIT2_TEXTWIDGET_Y_POSITION},{EMAPP_ATV_BIT2_TEXTWIDGET_WIDTH,EMAPP_ATV_BIT2_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON,})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_EMAPP_TEXT)
            WdgCommonSetAlignmentRC(0)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetFontTypeRC(FONT_TYPE_EXPAND1)
        WdgEnd(CLSID_TEXTWIDGET,Bit2TextWidget)
        WdgBegin(CLSID_TEXTWIDGET,ChannelTextWidget)
            WdgTextCreateForWndRC({{EMAPP_ATV_CHANNEL_TEXTWIDGET_X_POSITION,EMAPP_ATV_CHANNEL_TEXTWIDGET_Y_POSITION},{EMAPP_ATV_CHANNEL_TEXTWIDGET_WIDTH,EMAPP_ATV_CHANNEL_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_EMAPP_TEXT)
            WdgCommonSetAlignmentRC(0)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetFontTypeRC(FONT_TYPE_EXPAND1)
        WdgEnd(CLSID_TEXTWIDGET,ChannelTextWidget) 
    
/*AbsContainerWidget({{0,0},{0,0}})*/
    WndEnd(EMAPP_WND_ATV)

	WndBegin(EMAPP_WND_WIFITEST)
		WdgBegin(CLSID_VTMMENU, WifiTestVtm)
            VtmCreateMenuRC(IMG_NULL_ID,TXT_LTL_N_NO_TITLE,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0)
        WdgEnd(CLSID_VTMMENU,WifiTestVtm)
    WndEnd(EMAPP_WND_WIFITEST)
    
    WndBegin(EMAPP_WND_WIFITEST_SETPARAM)
		WdgBegin(CLSID_VTMMENU, WifiTestSetParamVtm)
            VtmCreateMenuRC(IMG_NULL_ID,TXT_LTL_N_NO_TITLE,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0)
        WdgEnd(CLSID_VTMMENU,WifiTestSetParamVtm)
    WndEnd(EMAPP_WND_WIFITEST_SETPARAM)
    
    WndBegin(EMAPP_WND_MULTITOUCHTEST)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)
        WndSetAllSoftkeyRC({SK_NONE,SK_NONE,SK_BACK})
        WdgBegin(CLSID_TEXTWIDGET,GestureTextWidget)
            WdgTextCreateForWndRC({{0,MAIN_LCD_TWOLINE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_LCD_ONELINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,GestureTextWidget)
        WdgBegin(CLSID_TEXTWIDGET,FRQTextWidget)
            WdgTextCreateForWndRC({{0,MAIN_LCD_ONELINE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_LCD_ONELINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,FRQTextWidget)        
    WndEnd(EMAPP_WND_MULTITOUCHTEST)    
    
    WndBegin(EMAPP_WND_TOUCHSRV_WDG_TEST)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)
        WndSetAllSoftkeyRC({SK_NEXT,SK_NONE,SK_BACK})
    WndEnd(EMAPP_WND_TOUCHSRV_WDG_TEST)   

    WndBegin(EMAPP_WND_PINCH_INOUT_TEST)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)
        WndSetAllSoftkeyRC({SK_NONE,SK_NONE,SK_BACK})
        WdgBegin(CLSID_TEXTWIDGET,SlimGestureTextWidget)
            WdgTextCreateForWndRC({{0,MAIN_LCD_ONELINE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_LCD_TWOLINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,SlimGestureTextWidget)     
    WndEnd(EMAPP_WND_PINCH_INOUT_TEST) 

ApEnd(RS,CLSID_EMAPP)

