#ifndef __MMI_ATVAPP_ID_H__
#define __MMI_ATVAPP_ID_H__

#ifdef __APP_MMI_SMALLROM__
#define __ATVAPP_SMALLROM__
#endif

#ifdef __ATV_CMMB__
#define     MMI_ATVAPP_CHANNEL_NAME_MAX	        24
#else
#define     MMI_ATVAPP_CHANNEL_NAME_MAX	        12
#endif

typedef enum
{
    ATV_WND_MAINMENU = WND_ID_APP_BASE,
	ATV_WND_WATCH,
	ATV_WND_CAPTURE,
	ATV_WND_CHANNELLIST,
	ATV_WND_CHANNELLIST_EDIT,
	ATV_WND_AREA,
	ATV_WND_RATIO,
	ATV_WND_CHANNELLIST_OPTION
} AtvWndId_e;

typedef enum
{
    WATCH_OSD_WIDGET=APP_WDG_START,
    WATCH_IMG_WAITING,
    WATCH_IMG_SIGNAL,
    WATCH_TEXT_CHANNEL_NAME,
#ifdef __ATVAPP_SMALLROM__
    WATCH_ABSCONTAINER_STATUS,
    WATCH_BUTTON_ABSCONTAINER_STATUS_BG,
#else
#if defined(__MMI_BATTERY_ICON_DISPLAY__)
    WATCH_IMG_BATTERY,
#endif
    WATCH_ABSCONTAINER_VOLUME,
#endif
    WATCH_IMG_VOLUME_ADJUST_BG,
    WATCH_IMG_VOLUME_ADJUST_LEVEL,
    WATCH_ABSCONTAINER_CONTROL,
	WATCH_BUTTON_ABSCONTAINER_BG,
#ifdef __ATVAPP_SMALLROM__
    WATCH_BUTTON_RETURN,
#else
    WATCH_BUTTON_POWER_OFF,
#endif
	WATCH_BUTTON_VOLUME_INCREASE,
    WATCH_BUTTON_VOLUME_DECREASE,
	WATCH_BUTTON_CAPUTRE,
	WATCH_BUTTON_CHANNEL_PREVIOUS,
	WATCH_BUTTON_CHANNEL_NEXT,
	WATCH_BUTTON_SCREEN_RATIO,
} AtvWatchWdgList_e;

typedef enum
{
    CAPTURE_IMG_CAPTURE_PIC=APP_WDG_START,
    CAPTURE_IMG_PREVIEW_ICON,
} AtvCaptureWdgList_e;

typedef enum
{
	MNU_ATV_ATV_MAIN_MENU = 0,
	MNU_ATV_MY_TV,
	MNU_ATV_CHANNEL_LIST,
	MNU_ATV_SEARCH_CHANNEL,
	MNU_ATV_TV_PICTURES,
	MNU_ATV_AREA_SETTINGS,
	MNU_ATV_RATIO_SETTINGS,
#ifndef __ATVAPP_SMALLROM__
	MNU_ATV_STORAGE_SETTINGS,
#endif //!__ATVAPP_SMALLROM__
	MNU_ATV_ATV_RATIO_MENU,
	MNU_ATV_RATIO_4_3,
	MNU_ATV_RATIO_16_9,
	MNU_ATV_ATV_REGION_MENU,
	MNU_ATV_REGION_USA,
	MNU_ATV_REGION_CANADA,
	MNU_ATV_REGION_KOREA,
	MNU_ATV_REGION_TAIWAN,
	MNU_ATV_REGION_MEXICO,
	MNU_ATV_REGION_CHILE,
	MNU_ATV_REGION_VENEZUELA,
	MNU_ATV_REGION_PHILIPPINES,
	MNU_ATV_REGION_JAMAICA,
	MNU_ATV_REGION_CHINA,
	MNU_ATV_REGION_SHENZHEN,
	MNU_ATV_REGION_VIETNAM,
	MNU_ATV_REGION_WESTERNEUROPE,
	MNU_ATV_REGION_TURKEY,
	MNU_ATV_REGION_UAE,
	MNU_ATV_REGION_AFGHANISTAN,
	MNU_ATV_REGION_SINGAPORE,
	MNU_ATV_REGION_THAILAND,
	MNU_ATV_REGION_CAMBODIA,
	MNU_ATV_REGION_INDONESIA,
	MNU_ATV_REGION_MALAYSIA,
	MNU_ATV_REGION_LAOS,
	MNU_ATV_REGION_PORTUGAL,
	MNU_ATV_REGION_SWEDEN,
	MNU_ATV_REGION_PAKISTAN,
	MNU_ATV_REGION_SPAIN,
	MNU_ATV_REGION_JAPAN,
	MNU_ATV_REGION_UK,
	MNU_ATV_REGION_HONGKONG,
	MNU_ATV_REGION_SOUTHAFRICA,
	MNU_ATV_REGION_BRAZIL,
	MNU_ATV_REGION_ARGENTINA,
	MNU_ATV_REGION_INDIA,
	MNU_ATV_REGION_BURMA,
	MNU_ATV_REGION_SUDAN,
	MNU_ATV_REGION_YEMEN,
	MNU_ATV_REGION_PERU,
	MNU_ATV_REGION_BOLIVIA,
	MNU_ATV_REGION_ECUADOR,
	MNU_ATV_REGION_SURINAME,
	MNU_ATV_REGION_AUSTRALIA,
	MNU_ATV_REGION_NEWZEALAND,
	MNU_ATV_REGION_COLUMBIA,
	MNU_ATV_REGION_COSTARICA,
	MNU_ATV_REGION_HONDURAS,
	MNU_ATV_REGION_GERMAN,
	MNU_ATV_REGION_ITALY,
}AtvMenuId_e;

#define ATV_COLOR_CHANNEL_NAME_TEXT COLOR_WHITE

enum
{
	/* Channel List Option Menu ID start */
	MNU_ATV_CHANNEL_PLAY = 1,
	MNU_ATV_CHANNEL_RENAME,
	MNU_ATV_CHANNEL_SEARCH
	/* Channel List Option Menu ID end */
};

#endif //__MMI_ATVAPP_ID_H__

