#ifndef __MMI_G3DMAINMENUAPP_ID_H__
#define __MMI_G3DMAINMENUAPP_ID_H__

typedef enum
{
    G3D_MAIN_MENU_WND_MAIN = WND_ID_APP_BASE,
} G3dMainMenuWndId_e;

enum
{
    G3D_MAINMENU_VIEW_BEGIN = APP_WDG_START,
    G3D_MAINMENU_GL_MENU_WIDGET,
    G3D_MAINMENU_IMG_CAPTURE_BG,
    G3D_MAINMENU_VIEW_END,
};

enum
{	
    WID_G3DMAINMENUAPP_PREV_BUTTON, 
    WID_G3DMAINMENUAPP_HOME_BUTTON, 
    WID_G3DMAINMENUAPP_TRAN_BUTTON, 
    WID_G3DMAINMENUAPP_NEXT_BUTTON,     
    WID_G3DMAINMENUAPP_ARROW_BUTTON_TOTAL
};

#endif //__MMI_G3DMAINMENUAPP_ID_H__

