
/*===========================================================================
 * Include file 
 *===========================================================================*/ 
#include "Customer_config.h"
 
#include "ahc_menu.h"
#include "ahc_display.h"
#include "ahc_message.h"
#include "ahc_sensor.h"
#include "ahc_parameter.h"
#include "ahc_dcf.h"
#include "ui_drawgeneral.h"
#include "IconDefine.h"
#include "IconPosition.h"
#include "MenuCommon.h"
#include "drawstatevideofunc.h"
#include "drawstatecamerafunc.h"
#include "drawstatebrowserfunc.h"
#include "drawstatemoviepbfunc.h"
#include "drawstatephotopbfunc.h"
#include "drawstateslideshowfunc.h"
#include "drawstatetvfunc.h"
#include "drawstatehdmifunc.h"
#include "DrawStateMenuSetting.h"
#include "MenuDrawingFunc.h"


typedef	void (DRAW_EVENT)(UINT32 Event);
typedef	void (DRAW_MENUEVENT)(PSMENUSTRUCT pMenu);

/*===========================================================================
 * Global variable
 *===========================================================================*/

DRAW_EVENT			*DrawEventHandler			= NULL;
DRAW_MENUEVENT		*DrawMenuEventHandler		= NULL;

#ifndef _OEM_DRAW_ //Use Default Drawing Set
UI_DARW_SET m_VideoDraw_Lcd[] =
{
	{VIDEO_GUI_MOVIE_RES, 	POS_ICON_MOVIE_RES_X, 	POS_ICON_MOVIE_RES_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MovieSize},
	{VIDEO_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{VIDEO_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{VIDEO_GUI_WB_MODE	, 	POS_ICON_WB_MODE_X, 	POS_ICON_WB_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{VIDEO_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{VIDEO_GUI_SCENE	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{VIDEO_GUI_FLASH	, 	POS_ICON_FLASHLIGHT_X, 	POS_ICON_FLASHLIGHT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecFlashMode},
	{VIDEO_GUI_REC_STATE, 	POS_VIDEO_STATE_X, 		POS_VIDEO_STATE_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecStatus},
	{VIDEO_GUI_ZOOM_BAR	, 	POS_ZOOM_BAR_X, 		POS_ZOOM_BAR_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoZoomBar},
	{VIDEO_GUI_EV		, 	POS_ICON_EV_X, 			POS_ICON_EV_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{VIDEO_GUI_REMAIN_TIME, POS_VIDEO_REMAIN_TIME_X,POS_VIDEO_REMAIN_TIME_Y,AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoAvailableRecordTime},
	{VIDEO_GUI_REC_TIME	, 	POS_VIDEO_REC_TIME_X, 	POS_VIDEO_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoCurrentRecordTime},
	{VIDEO_GUI_RTC_TIME	, 	POS_VIDEO_RTC_TIME_X, 	POS_VIDEO_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{VIDEO_GUI_LOCK_FILE, 	POS_VIDEO_LOCK_FILE_X, 	POS_VIDEO_LOCK_FILE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLockFileStatus},
	{VIDEO_GUI_LOCK_NUM , 	POS_VIDEO_LOCK_NUM_X, 	POS_VIDEO_LOCK_NUM_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLockFileNum},
	{VIDEO_GUI_MUTE		, 	POS_VIDEO_MUTE_X, 		POS_VIDEO_MUTE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMuteRecord},
	{VIDEO_GUI_REC_POINT, 	POS_VIDEO_REC_POINT_X, 	POS_VIDEO_REC_POINT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X,  DrawVideoRecording},
	{VIDEO_GUI_GPS_STATE, 	POS_GPS_STATE_X, 		POS_GPS_STATE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{VIDEO_GUI_VMD_STATE, 	POS_ICON_VMD_X, 		POS_ICON_VMD_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMotionDtc},
	{VIDEO_GUI_VTL_STATE, 	POS_ICON_VTL_X, 		POS_ICON_VTL_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoTimeLapse},		// VIDEO_REC_TIMELAPSE_EN
	{VIDEO_GUI_DRIVER_ID, 	POS_DRIVER_ID_X, 		POS_DRIVER_ID_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_DriverId},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
	{VIDEO_GUI_WIFI,		POS_ICON_WIFI_X, 		POS_ICON_WIFI_Y, 		AHC_TRUE, NORMAL_SIZE, MAG_1X, DrawVideoWiFi},
	{VIDEO_GUI_WIFI_SWITCH, POS_ICON_WIFI_SWITCH_X, POS_ICON_WIFI_SWITCH_Y, AHC_TRUE, NORMAL_SIZE, MAG_1X, DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
	{VIDEO_GUI_LDWS_LINE,	0,						0,						AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
	{VIDEO_GUI_FCWS_INFO,	0,						0,						AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoFCWS_Info},
#endif
	{VIDEO_GUI_MAX		,   0,						0,						AHC_FALSE, NORMAL_SIZE, MAG_1X, NULL},
	{AUDIO_GUI_REC_TIME, 	POS_VIDEO_REC_TIME_X, 	POS_VIDEO_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioCurRecordTime},
	{AUDIO_GUI_REC_POINT, 	POS_VIDEO_REC_POINT_X, 	POS_VIDEO_REC_POINT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_DSCDraw_Lcd[] = 
{
	{DSC_GUI_IMAGE_RES	, 	POS_ICON_IMAGE_RES_X, 	POS_ICON_IMAGE_RES_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_ImageSize},
	{DSC_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{DSC_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{DSC_GUI_WB_MODE	, 	POS_ICON_WB_MODE_X, 	POS_ICON_WB_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{DSC_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{DSC_GUI_SCENE		, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{DSC_GUI_FLASH		, 	POS_ICON_FLASHLIGHT_X, 	POS_ICON_FLASHLIGHT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureFlashMode},
	{DSC_GUI_SELF_TIMER , 	POS_ICON_SELFTIMER_X, 	POS_ICON_SELFTIMER_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SelfTimer},
	{DSC_GUI_BURST		, 	POS_ICON_BURST_X, 		POS_ICON_BURST_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BurstShot},
	{DSC_GUI_ZOOM_BAR	, 	POS_ZOOM_BAR_X, 		POS_ZOOM_BAR_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureZoomBar},
	{DSC_GUI_EV			, 	POS_ICON_EV_X, 			POS_ICON_EV_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{DSC_GUI_REMAIN_NUM	, 	POS_DSC_REMAIN_NUM_X,	POS_DSC_REMAIN_NUM_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureRemainNum},
	{DSC_GUI_RTC_TIME	, 	POS_VIDEO_RTC_TIME_X, 	POS_VIDEO_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{DSC_GUI_GPS_STATE  , 	POS_GPS_STATE_X, 		POS_GPS_STATE_Y, 		AHC_FALSE, NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{DSC_GUI_VMD_STATE  , 	POS_ICON_VMD_X, 		POS_ICON_VMD_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureMotionDtc},
	{DSC_GUI_DRIVER_ID  , 	POS_DRIVER_ID_X, 		POS_DRIVER_ID_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_DriverId},
	{0xFFFF}
};
#endif

UI_DARW_SET m_BrowserDraw_Lcd[] = 
{
	{BROWSER_GUI_FILENAME	, 		POS_BROW_FILENAME_X, 	POS_BROW_FILENAME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawBrowser_NameInfo},
	{BROWSER_GUI_UI_MODE	, 		POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{BROWSER_GUI_SD_STATE	, 		POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{BROWSER_GUI_FILE_DATE 	, 		POS_BROW_FILEDATE_X, 	POS_BROW_FILEDATE_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawBrowser_DateInfo},
	{BROWSER_GUI_BATTERY	, 		POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{BROWSER_GUI_MOV_TOTAL_TIME	, 	POS_BROW_TOTAL_TIME_X, 	POS_BROW_TOTAL_TIME_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawBrowser_TotalTime},
#if defined(POS_BROW_RESOLUTION_SHOW)&& POS_BROW_RESOLUTION_SHOW
    {BROWSER_GUI_RESOLUTION	, 	    POS_BROW_RESOLUTION_X, 	POS_BROW_RESOLUTION_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawBrowser_ResolutionInfo},
#endif
	{0xFFFF}
};

UI_DARW_SET m_MovPBDraw_Lcd[] = 
{
	{MOVPB_GUI_STATUS, 		POS_MOVPB_STATUS_X, 	POS_MOVPB_STATUS_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_Status},
	{MOVPB_GUI_FILE_INDEX, 	POS_MOVPB_FILE_IDX_X, 	POS_MOVPB_FILE_IDX_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_FileIndex},
	{MOVPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{MOVPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{MOVPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{MOVPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NORMAL_SIZE, MAG_1X, NULL}, // TBD
	{MOVPB_GUI_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 	POS_MOVPB_LOCK_FILE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_LockCurFile},
	{MOVPB_GUI_FILENAME , 	POS_MOVPB_FILENAME_X, 	POS_MOVPB_FILENAME_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_FileInfo},
	{MOVPB_GUI_CUR_TIME	, 	POS_MOVPB_CUR_TIME_X, 	POS_MOVPB_CUR_TIME_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_PlayInfo},
	{MOVPB_GUI_TOTAL_TIME, 	POS_MOVPB_TOTAL_TIME_X, POS_MOVPB_TOTAL_TIME_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawMovPb_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_AudPBDraw_Lcd[] = 
{
	{AUDPB_GUI_STATUS, 		POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{AUDPB_GUI_FILE_INDEX, 	POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_TRUE,  DrawAudPb_FileIndex},
	{AUDPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE,  OSDDrawSetting_UIMode},
	{AUDPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE,  OSDDrawSetting_MediaType},
	{AUDPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE,  OSDDrawSetting_BatteryStatus},
	{AUDPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, NORMAL_SIZE, MAG_1X, NULL}, // TBD
	{AUDPB_GUI_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_TRUE,  DrawAudPb_LockCurFile},
	{AUDPB_GUI_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{AUDPB_GUI_CUR_TIME	, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{AUDPB_GUI_TOTAL_TIME, 	POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_JpgPBDraw_Lcd[] = 
{
	{JPGPB_GUI_FILE_INDEX, 	POS_JPGPB_FILE_IDX_X, 	POS_JPGPB_FILE_IDX_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawJpgPb_FileIndex},
	{JPGPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{JPGPB_GUI_SD_STATE	, 	POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{JPGPB_GUI_BATTERY	, 	POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{JPGPB_GUI_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 	POS_JPGPB_LOCK_FILE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawJpgPb_LockCurFile},
	{JPGPB_GUI_FILENAME , 	POS_JPGPB_FILENAME_X, 	POS_JPGPB_FILENAME_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawJpgPb_FileInfo},
	{JPGPB_GUI_FILEDATE, 	POS_JPGPB_FILEDATE_X, 	POS_JPGPB_FILEDATE_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawJpgPb_DateInfo},
	{0xFFFF}
};

/*===========================================================================
 * Global variable : TV Drawing
 *===========================================================================*/

#if (TVOUT_ENABLE)

#if (TVOUT_PREVIEW_EN)
UI_DARW_SET m_VideoDraw_Tv[] = 
{
	{VIDEO_GUI_MOVIE_RES	, 	POS_ICON_TV_MOVIE_RES_X, 	POS_ICON_TV_MOVIE_RES_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_MovieSize},
	{VIDEO_GUI_UI_MODE	, 	POS_ICON_TV_UI_MODE_X, 		POS_ICON_TV_UI_MODE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{VIDEO_GUI_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 		POS_ICON_TV_MEDIA_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{VIDEO_GUI_WB_MODE	, 	POS_ICON_TV_WB_MODE_X, 		POS_ICON_TV_WB_MODE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_WB_Mode},
	{VIDEO_GUI_BATTERY	, 	POS_ICON_TV_BATT_X, 		POS_ICON_TV_BATT_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{VIDEO_GUI_SCENE		, 	POS_ICON_TV_SCENE_X, 		POS_ICON_TV_SCENE_Y,	 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_SceneMode},
	{VIDEO_GUI_FLASH		, 	POS_ICON_TV_FLASHLIGHT_X, 	POS_ICON_TV_FLASHLIGHT_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoRecFlashMode},
	{VIDEO_GUI_REC_STATE	, 	POS_VIDEO_TV_STATE_X, 		POS_VIDEO_TV_STATE_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoRecStatus},
	{VIDEO_GUI_ZOOM_BAR	, 	POS_TV_ZOOM_BAR_X, 			POS_TV_ZOOM_BAR_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoZoomBar},
	{VIDEO_GUI_EV		, 	POS_ICON_TV_EV_X, 			POS_ICON_TV_EV_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_EV},
	{VIDEO_GUI_REMAIN_TIME, 	POS_VIDEO_TV_REMAIN_TIME_X,	POS_VIDEO_TV_REMAIN_TIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoAvailableRecordTime},
	{VIDEO_GUI_REC_TIME	, 	POS_VIDEO_TV_REC_TIME_X, 	POS_VIDEO_TV_REC_TIME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoCurrentRecordTime},
	{VIDEO_GUI_RTC_TIME	, 	POS_VIDEO_TV_RTC_TIME_X, 	POS_VIDEO_TV_RTC_TIME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDraw_CurrentRTCTime},
	{VIDEO_GUI_LOCK_FILE	, 	POS_VIDEO_TV_LOCK_FILE_X, 	POS_VIDEO_TV_LOCK_FILE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoLockFileStatus},
	{VIDEO_GUI_LOCK_NUM	, 	POS_VIDEO_TV_LOCK_NUM_X, 	POS_VIDEO_TV_LOCK_NUM_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, DrawVideoLockFileNum},
	{VIDEO_GUI_MUTE		, 	POS_VIDEO_TV_MUTE_X, 		POS_VIDEO_TV_MUTE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoMuteRecord},
	{VIDEO_GUI_REC_POINT	, 	POS_VIDEO_TV_REC_POINT_X, 	POS_VIDEO_TV_REC_POINT_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoRecording},
	{VIDEO_GUI_GPS_STATE	, 	POS_TV_GPS_STATE_X, 		POS_TV_GPS_STATE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDraw_GPSStatus},
	{VIDEO_GUI_VMD_STATE , 	POS_ICON_TV_VMD_X, 			POS_ICON_TV_VMD_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
	{VIDEO_GUI_WIFI,		    POS_ICON_TV_WIFI_X, 		POS_ICON_TV_WIFI_Y,         AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoWiFi},
	{VIDEO_GUI_WIFI_SWITCH,  POS_ICON_TV_WIFI_SWITCH_X,  POS_ICON_TV_WIFI_SWITCH_Y,  AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
	{VIDEO_GUI_LDWS_LINE,0,							0,							AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
	{VIDEO_GUI_FCWS_INFO,0,							0,							AHC_TRUE , LARGE_SIZE, MAG_2X, DrawVideoFCWS_Info},
#endif
	{VIDEO_GUI_MAX		,   0,							0,							AHC_FALSE, LARGE_SIZE, MAG_2X, NULL},
	{AUDIO_GUI_REC_TIME  , 	POS_VIDEO_TV_REC_TIME_X, 	POS_VIDEO_TV_REC_TIME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudioCurRecordTime},
	{AUDIO_GUI_REC_POINT , 	POS_VIDEO_TV_REC_POINT_X, 	POS_VIDEO_TV_REC_POINT_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_DSCDraw_Tv[] = 
{
	{DSC_GUI_IMAGE_RES	, 	POS_ICON_TV_IMAGE_RES_X, 	POS_ICON_TV_IMAGE_RES_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_ImageSize},
	{DSC_GUI_UI_MODE		, 	POS_ICON_TV_UI_MODE_X, 		POS_ICON_TV_UI_MODE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{DSC_GUI_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 		POS_ICON_TV_MEDIA_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{DSC_GUI_WB_MODE		, 	POS_ICON_TV_WB_MODE_X, 		POS_ICON_TV_WB_MODE_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_WB_Mode},
	{DSC_GUI_BATTERY		, 	POS_ICON_TV_BATT_X, 		POS_ICON_TV_BATT_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{DSC_GUI_SCENE		, 	POS_ICON_TV_SCENE_X, 		POS_ICON_TV_SCENE_Y,	 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_SceneMode},
	{DSC_GUI_FLASH		, 	POS_ICON_TV_FLASHLIGHT_X, 	POS_ICON_TV_FLASHLIGHT_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawCaptureFlashMode},
	{DSC_GUI_SELF_TIMER , 	POS_ICON_TV_SELFTIMER_X, 	POS_ICON_TV_SELFTIMER_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_SelfTimer},
	{DSC_GUI_BURST		, 	POS_ICON_TV_BURST_X, 		POS_ICON_TV_BURST_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_BurstShot},
	{DSC_GUI_ZOOM_BAR	, 	POS_TV_ZOOM_BAR_X, 			POS_TV_ZOOM_BAR_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, DrawCaptureZoomBar},
	{DSC_GUI_EV			, 	POS_ICON_TV_EV_X, 			POS_ICON_TV_EV_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_EV},
	{DSC_GUI_REMAIN_NUM	, 	POS_DSC_TV_REMAIN_NUM_X,	POS_DSC_TV_REMAIN_NUM_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawCaptureRemainNum},
	{DSC_GUI_RTC_TIME	, 	POS_VIDEO_TV_RTC_TIME_X, 	POS_VIDEO_TV_RTC_TIME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDraw_CurrentRTCTime},
	{DSC_GUI_GPS_STATE	, 	POS_TV_GPS_STATE_X, 		POS_TV_GPS_STATE_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDraw_GPSStatus},
	{DSC_GUI_VMD_STATE	, 	POS_ICON_TV_VMD_X, 			POS_ICON_TV_VMD_Y, 			AHC_TRUE , LARGE_SIZE, MAG_2X, DrawCaptureMotionDtc},
	{0xFFFF}
};
#endif
#endif

UI_DARW_SET m_BrowserDraw_Tv[] =
{
	{BROWSER_GUI_FILENAME	, 		POS_BROW_FILENAME_X, 	POS_BROW_FILENAME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_NameInfo},
	{BROWSER_GUI_UI_MODE	, 		POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, NULL},
	{BROWSER_GUI_SD_STATE	, 		POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{BROWSER_GUI_FILE_DATE 	, 		POS_BROW_FILEDATE_X, 	POS_BROW_FILEDATE_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_DateInfo},
	{BROWSER_GUI_BATTERY	, 		POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{BROWSER_GUI_MOV_TOTAL_TIME	, 	POS_BROW_TOTAL_TIME_X, 	POS_BROW_TOTAL_TIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_TotalTime},
#if defined(POS_BROW_RESOLUTION_SHOW)&& POS_BROW_RESOLUTION_SHOW
    {BROWSER_GUI_RESOLUTION	, 	    POS_BROW_RESOLUTION_X, 	POS_BROW_RESOLUTION_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_ResolutionInfo},
#endif
	{0xFFFF}
};

UI_DARW_SET m_MovPBDraw_Tv[] = 
{
	{MOVPB_GUI_STATUS, 		POS_TV_MOV_STATE_X, 	POS_TV_MOV_STATE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_Status},
	{MOVPB_GUI_FILE_INDEX, 	POS_TV_MOV_FILEIDX_X, 	POS_TV_MOV_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileIndex},
	{MOVPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{MOVPB_GUI_SD_STATE	, 	POS_ICON_TV_MEDIA_X,    POS_ICON_TV_MEDIA_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{MOVPB_GUI_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{MOVPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, LARGE_SIZE, MAG_2X, NULL}, // TBD
	{MOVPB_GUI_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 	POS_MOVPB_LOCK_FILE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, DrawMovPb_LockCurFile},
	{MOVPB_GUI_FILENAME , 	POS_TV_MOV_NAME_X, 		POS_TV_MOV_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileInfo},
	{MOVPB_GUI_CUR_TIME	, 	POS_TV_MOV_CURTIME_X, 	POS_TV_MOV_CURTIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_PlayInfo},
	{MOVPB_GUI_TOTAL_TIME, 	POS_TV_MOV_TOTALTIME_X, POS_TV_MOV_TOTALTIME_Y, AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_AudPBDraw_Tv[] = 
{
	{AUDPB_GUI_STATUS, 		POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudPb_Status},
	{AUDPB_GUI_FILE_INDEX, 	POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, DrawAudPb_FileIndex},
	{AUDPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{AUDPB_GUI_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 	POS_ICON_TV_MEDIA_Y,	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{AUDPB_GUI_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{AUDPB_GUI_VOL_BAR	, 	POS_ICON_SCENE_X, 		POS_ICON_SCENE_Y,	 	AHC_FALSE, LARGE_SIZE, MAG_2X, NULL},
	{AUDPB_GUI_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, DrawAudPb_LockCurFile},
	{AUDPB_GUI_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudPb_FileInfo},
	{AUDPB_GUI_CUR_TIME	, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudPb_PlayInfo},
	{AUDPB_GUI_TOTAL_TIME, 	POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE , LARGE_SIZE, MAG_2X, DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_JpgPBDraw_Tv[] = 
{
	{JPGPB_GUI_FILE_INDEX, 	POS_TV_JPG_FILEIDX_X, 	POS_TV_JPG_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileIndex},
	{JPGPB_GUI_UI_MODE	, 	POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{JPGPB_GUI_SD_STATE	, 	POS_ICON_TV_MEDIA_X, 	POS_ICON_TV_MEDIA_Y,	AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{JPGPB_GUI_BATTERY	, 	POS_ICON_TV_BATT_X,		POS_ICON_TV_BATT_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{JPGPB_GUI_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 	POS_JPGPB_LOCK_FILE_Y, 	AHC_FALSE, LARGE_SIZE, MAG_2X, DrawJpgPb_LockCurFile},
	{JPGPB_GUI_FILENAME , 	POS_TV_JPG_NAME_X, 		POS_TV_JPG_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileInfo},
	{JPGPB_GUI_FILEDATE , 	POS_TV_JPG_FILEDATE_X, 	POS_TV_JPG_FILEDATE_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_DateInfo},
	{0xFFFF}
};

#endif // #if (TVOUT_ENABLE)

/*===========================================================================
 * Global variable : HDMI Drawing
 *===========================================================================*/

#if (HDMI_ENABLE)

#if (HDMI_PREVIEW_EN)
UI_DARW_SET m_VideoDraw_Hdmi_1080P[] = 
{
	{VIDEO_GUI_MOVIE_RES	, 	POS_ICON_HDMI_1080P_MOVIE_RES_X, 	POS_ICON_HDMI_1080P_MOVIE_RES_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MovieSize},
	{VIDEO_GUI_UI_MODE		, 	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{VIDEO_GUI_SD_STATE	, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{VIDEO_GUI_WB_MODE		, 	POS_ICON_HDMI_1080P_WB_MODE_X, 		POS_ICON_HDMI_1080P_WB_MODE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{VIDEO_GUI_BATTERY		, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{VIDEO_GUI_SCENE		, 	POS_ICON_HDMI_1080P_SCENE_X, 		POS_ICON_HDMI_1080P_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{VIDEO_GUI_FLASH		, 	POS_ICON_HDMI_1080P_FLASHLIGHT_X, 	POS_ICON_HDMI_1080P_FLASHLIGHT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecFlashMode},
	{VIDEO_GUI_REC_STATE	, 	POS_ICON_HDMI_1080P_STATE_X, 		POS_ICON_HDMI_1080P_STATE_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecStatus},
	{VIDEO_GUI_ZOOM_BAR	, 	POS_ICON_HDMI_1080P_ZOOM_BAR_X, 	POS_ICON_HDMI_1080P_ZOOM_BAR_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoZoomBar},
	{VIDEO_GUI_EV			, 	POS_ICON_HDMI_1080P_EV_X, 			POS_ICON_HDMI_1080P_EV_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{VIDEO_GUI_REMAIN_TIME, 	POS_ICON_HDMI_1080P_REMAIN_TIME_X,	POS_ICON_HDMI_1080P_REMAIN_TIME_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoAvailableRecordTime},
	{VIDEO_GUI_REC_TIME	, 	POS_ICON_HDMI_1080P_REC_TIME_X, 	POS_ICON_HDMI_1080P_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoCurrentRecordTime},
	{VIDEO_GUI_RTC_TIME	, 	POS_ICON_HDMI_1080P_RTC_TIME_X, 	POS_ICON_HDMI_1080P_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{VIDEO_GUI_LOCK_FILE	, 	POS_ICON_HDMI_1080P_LOCK_FILE_X, 	POS_ICON_HDMI_1080P_LOCK_FILE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLockFileStatus},
	{VIDEO_GUI_LOCK_NUM	, 	POS_ICON_HDMI_1080P_LOCK_NUM_X, 	POS_ICON_HDMI_1080P_LOCK_NUM_Y, 	AHC_FALSE, NORMAL_SIZE, MAG_1X, DrawVideoLockFileNum},
	{VIDEO_GUI_MUTE		, 	POS_ICON_HDMI_1080P_MUTE_X, 		POS_ICON_HDMI_1080P_MUTE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMuteRecord},
	{VIDEO_GUI_REC_POINT	, 	POS_ICON_HDMI_1080P_REC_POINT_X, 	POS_ICON_HDMI_1080P_REC_POINT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecording},
	{VIDEO_GUI_GPS_STATE	, 	POS_ICON_HDMI_1080P_GPS_STATE_X, 	POS_ICON_HDMI_1080P_GPS_STATE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{VIDEO_GUI_VMD_STATE 	, 	POS_ICON_HDMI_1080P_VMD_X, 			POS_ICON_HDMI_1080P_VMD_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
//	{VIDEO_GUI_WIFI,		    POS_ICON_TV_WIFI_X, 		    	POS_ICON_HDMI_WIFI_Y,       		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoWiFi},
//	{VIDEO_GUI_WIFI_SWITCH,    POS_ICON_TV_WIFI_SWITCH_X,      	POS_ICON_HDMI_WIFI_SWITCH_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
//	{VIDEO_GUI_LDWS_LINE,  0,  								0,									AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
//	{VIDEO_GUI_FCWS_INFO,  0,							    	0,									AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoFCWS_Info},
#endif
	{VIDEO_GUI_MAX			,   0,									0,									AHC_FALSE, NORMAL_SIZE, MAG_1X, NULL},
	{AUDIO_GUI_REC_TIME  , 	POS_ICON_HDMI_1080P_REC_TIME_X, 	POS_ICON_HDMI_1080P_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioCurRecordTime},
	{AUDIO_GUI_REC_POINT , 	POS_ICON_HDMI_1080P_REC_POINT_X, 	POS_ICON_HDMI_1080P_REC_POINT_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioRecording},
	{0xFFFF}
};

UI_DARW_SET m_VideoDraw_Hdmi_720P[] = 
{
	{VIDEO_GUI_MOVIE_RES	, 	POS_ICON_HDMI_720P_MOVIE_RES_X, 	POS_ICON_HDMI_720P_MOVIE_RES_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MovieSize},
	{VIDEO_GUI_UI_MODE		, 	POS_ICON_HDMI_720P_UI_MODE_X, 		POS_ICON_HDMI_720P_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{VIDEO_GUI_SD_STATE	, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{VIDEO_GUI_WB_MODE		, 	POS_ICON_HDMI_720P_WB_MODE_X, 		POS_ICON_HDMI_720P_WB_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{VIDEO_GUI_BATTERY		, 	POS_ICON_HDMI_720P_BATT_X, 			POS_ICON_HDMI_720P_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{VIDEO_GUI_SCENE		, 	POS_ICON_HDMI_720P_SCENE_X, 		POS_ICON_HDMI_720P_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{VIDEO_GUI_FLASH		, 	POS_ICON_HDMI_720P_FLASHLIGHT_X, 	POS_ICON_HDMI_720P_FLASHLIGHT_Y,AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecFlashMode},
	{VIDEO_GUI_REC_STATE	, 	POS_ICON_HDMI_720P_STATE_X, 		POS_ICON_HDMI_720P_STATE_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecStatus},
	{VIDEO_GUI_ZOOM_BAR	, 	POS_ICON_HDMI_720P_ZOOM_BAR_X, 		POS_ICON_HDMI_720P_ZOOM_BAR_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoZoomBar},
	{VIDEO_GUI_EV			, 	POS_ICON_HDMI_720P_EV_X, 			POS_ICON_HDMI_720P_EV_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{VIDEO_GUI_REMAIN_TIME, 	POS_ICON_HDMI_720P_REMAIN_TIME_X,	POS_ICON_HDMI_720P_REMAIN_TIME_Y,AHC_TRUE, NORMAL_SIZE, MAG_1X, DrawVideoAvailableRecordTime},
	{VIDEO_GUI_REC_TIME	, 	POS_ICON_HDMI_720P_REC_TIME_X, 		POS_ICON_HDMI_720P_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoCurrentRecordTime},
	{VIDEO_GUI_RTC_TIME	, 	POS_ICON_HDMI_720P_RTC_TIME_X, 		POS_ICON_HDMI_720P_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{VIDEO_GUI_LOCK_FILE	, 	POS_ICON_HDMI_720P_LOCK_FILE_X, 	POS_ICON_HDMI_720P_LOCK_FILE_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLockFileStatus},
	{VIDEO_GUI_LOCK_NUM	, 	POS_ICON_HDMI_720P_LOCK_NUM_X, 		POS_ICON_HDMI_720P_LOCK_NUM_Y, 	AHC_FALSE, NORMAL_SIZE, MAG_1X, DrawVideoLockFileNum},
	{VIDEO_GUI_MUTE		, 	POS_ICON_HDMI_720P_MUTE_X, 			POS_ICON_HDMI_720P_MUTE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMuteRecord},
	{VIDEO_GUI_REC_POINT	, 	POS_ICON_HDMI_720P_REC_POINT_X, 	POS_ICON_HDMI_720P_REC_POINT_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoRecording},
	{VIDEO_GUI_GPS_STATE	, 	POS_ICON_HDMI_720P_GPS_STATE_X, 	POS_ICON_HDMI_720P_GPS_STATE_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{VIDEO_GUI_VMD_STATE 	, 	POS_ICON_HDMI_720P_VMD_X, 			POS_ICON_HDMI_720P_VMD_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoMotionDtc},
#if defined(WIFI_PORT) && (WIFI_PORT == 1)
//	{VIDEO_GUI_WIFI,		    POS_ICON_TV_WIFI_X, 		    	POS_ICON_HDMI_720P_WIFI_Y,      AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoWiFi},
//	{VIDEO_GUI_WIFI_SWITCH,    POS_ICON_TV_WIFI_SWITCH_X,      	POS_ICON_HDMI_720P_WIFI_SWITCH_Y,AHC_TRUE, NORMAL_SIZE, MAG_1X, DrawVideoWiFiStreaming},
#endif
#if (ENABLE_ADAS_LDWS)
//	{VIDEO_GUI_LDWS_LINE,  0,  								0,								AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoLDWS_Line},
#endif
#if (ENABLE_ADAS_FCWS)
//	{VIDEO_GUI_FCWS_INFO,  0,							    	0,								AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawVideoFCWS_Info},
#endif
	{VIDEO_GUI_MAX			,   0,									0,								AHC_FALSE, NORMAL_SIZE, MAG_1X,  NULL},
	{AUDIO_GUI_REC_TIME  , 	POS_ICON_HDMI_720P_REC_TIME_X, 		POS_ICON_HDMI_720P_REC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioCurRecordTime},
	{AUDIO_GUI_REC_POINT , 	POS_ICON_HDMI_720P_REC_POINT_X, 	POS_ICON_HDMI_720P_REC_POINT_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawAudioRecording},
	{0xFFFF}
};

#if (DSC_MODE_ENABLE)
UI_DARW_SET m_DSCDraw_Hdmi_1080P[] =
{
	{DSC_GUI_IMAGE_RES	, 	POS_ICON_HDMI_1080P_IMAGE_RES_X, 	POS_ICON_HDMI_1080P_IMAGE_RES_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_ImageSize},
	{DSC_GUI_UI_MODE	,	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{DSC_GUI_SD_STATE	, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{DSC_GUI_WB_MODE	, 	POS_ICON_HDMI_1080P_WB_MODE_X, 		POS_ICON_HDMI_1080P_WB_MODE_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{DSC_GUI_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{DSC_GUI_SCENE		, 	POS_ICON_HDMI_1080P_SCENE_X, 		POS_ICON_HDMI_1080P_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{DSC_GUI_FLASH		, 	POS_ICON_HDMI_1080P_FLASHLIGHT_X, 	POS_ICON_HDMI_1080P_FLASHLIGHT_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureFlashMode},
	{DSC_GUI_SELF_TIMER, 	POS_ICON_HDMI_1080P_SELFTIMER_X, 	POS_ICON_HDMI_1080P_SELFTIMER_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SelfTimer},
	{DSC_GUI_BURST		, 	POS_ICON_HDMI_1080P_BURST_X, 		POS_ICON_HDMI_1080P_BURST_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BurstShot},
	{DSC_GUI_ZOOM_BAR	, 	POS_ICON_HDMI_1080P_ZOOM_BAR_X, 	POS_ICON_HDMI_1080P_ZOOM_BAR_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureZoomBar},
	{DSC_GUI_EV		, 	POS_ICON_HDMI_1080P_EV_X, 			POS_ICON_HDMI_1080P_EV_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{DSC_GUI_REMAIN_NUM, 	POS_ICON_HDMI_1080P_REMAIN_NUM_X,	POS_ICON_HDMI_1080P_REMAIN_NUM_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureRemainNum},
	{DSC_GUI_RTC_TIME	, 	POS_ICON_HDMI_1080P_RTC_TIME_X, 	POS_ICON_HDMI_1080P_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{DSC_GUI_GPS_STATE	, 	POS_ICON_HDMI_1080P_GPS_STATE_X, 	POS_ICON_HDMI_1080P_GPS_STATE_Y, 	AHC_FALSE, NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{DSC_GUI_VMD_STATE	, 	POS_ICON_HDMI_1080P_VMD_X, 			POS_ICON_HDMI_1080P_VMD_Y, 			AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureMotionDtc},
	{0xFFFF}
};

UI_DARW_SET m_DSCDraw_Hdmi_720P[] = 
{
	{DSC_GUI_IMAGE_RES	, 	POS_ICON_HDMI_720P_IMAGE_RES_X, POS_ICON_HDMI_720P_IMAGE_RES_Y, AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_ImageSize},
	{DSC_GUI_UI_MODE	,	POS_ICON_HDMI_720P_UI_MODE_X, 	POS_ICON_HDMI_720P_UI_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_UIMode},
	{DSC_GUI_SD_STATE	, 	POS_ICON_HDMI_720P_MEDIA_X, 	POS_ICON_HDMI_720P_MEDIA_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_MediaType},
	{DSC_GUI_WB_MODE	, 	POS_ICON_HDMI_720P_WB_MODE_X, 	POS_ICON_HDMI_720P_WB_MODE_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_WB_Mode},
	{DSC_GUI_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 		POS_ICON_HDMI_720P_BATT_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BatteryStatus},
	{DSC_GUI_SCENE		, 	POS_ICON_HDMI_720P_SCENE_X, 	POS_ICON_HDMI_720P_SCENE_Y,	 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SceneMode},
	{DSC_GUI_FLASH		, 	POS_ICON_HDMI_720P_FLASHLIGHT_X,POS_ICON_HDMI_720P_FLASHLIGHT_Y,AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureFlashMode},
	{DSC_GUI_SELF_TIMER, 	POS_ICON_HDMI_720P_SELFTIMER_X, POS_ICON_HDMI_720P_SELFTIMER_Y,	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_SelfTimer},
	{DSC_GUI_BURST		, 	POS_ICON_HDMI_720P_BURST_X, 	POS_ICON_HDMI_720P_BURST_Y,		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_BurstShot},
	{DSC_GUI_ZOOM_BAR	, 	POS_ICON_HDMI_720P_ZOOM_BAR_X, 	POS_ICON_HDMI_720P_ZOOM_BAR_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureZoomBar},
	{DSC_GUI_EV		, 	POS_ICON_HDMI_720P_EV_X, 		POS_ICON_HDMI_720P_EV_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDrawSetting_EV},
	{DSC_GUI_REMAIN_NUM, 	POS_ICON_HDMI_720P_REMAIN_NUM_X,POS_ICON_HDMI_720P_REMAIN_NUM_Y,AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureRemainNum},
	{DSC_GUI_RTC_TIME	, 	POS_ICON_HDMI_720P_RTC_TIME_X, 	POS_ICON_HDMI_720P_RTC_TIME_Y, 	AHC_TRUE , NORMAL_SIZE, MAG_1X, OSDDraw_CurrentRTCTime},
	{DSC_GUI_GPS_STATE	, 	POS_ICON_HDMI_720P_GPS_STATE_X, POS_ICON_HDMI_720P_GPS_STATE_Y, AHC_FALSE, NORMAL_SIZE, MAG_1X, OSDDraw_GPSStatus},
	{DSC_GUI_VMD_STATE	, 	POS_ICON_HDMI_720P_VMD_X, 		POS_ICON_HDMI_720P_VMD_Y, 		AHC_TRUE , NORMAL_SIZE, MAG_1X, DrawCaptureMotionDtc},
	{0xFFFF}
};
#endif
#endif //#if (HDMI_PREVIEW_EN)
UI_DARW_SET m_BrowserDraw_Hdmi[] =
{
	{BROWSER_GUI_FILENAME	, 		POS_BROW_FILENAME_X, 	POS_BROW_FILENAME_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawHdmiBrowser_NameDateInfo},//draw Name & Date info in one API
	{BROWSER_GUI_UI_MODE	, 		POS_ICON_UI_MODE_X, 	POS_ICON_UI_MODE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, NULL},
	{BROWSER_GUI_SD_STATE	, 		POS_ICON_MEDIA_X, 		POS_ICON_MEDIA_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{BROWSER_GUI_FILE_DATE 	, 		POS_BROW_FILEDATE_X, 	POS_BROW_FILEDATE_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, NULL},
	{BROWSER_GUI_BATTERY	, 		POS_ICON_BATT_X, 		POS_ICON_BATT_Y, 		AHC_TRUE , LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{BROWSER_GUI_MOV_TOTAL_TIME	, 	POS_BROW_TOTAL_TIME_X, 	POS_BROW_TOTAL_TIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_TotalTime},
#if defined(POS_BROW_RESOLUTION_SHOW)&& POS_BROW_RESOLUTION_SHOW
//    {BROWSER_GUI_RESOLUTION	, 	    POS_BROW_RESOLUTION_X, 	POS_BROW_RESOLUTION_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawBrowser_ResolutionInfo},
#endif
	{0xFFFF}
};

UI_DARW_SET m_MovPBDraw_Hdmi_1080P[] =
{
	{MOVPB_GUI_STATUS, 		POS_ICON_HDMI_1080P_MOV_STATE_X, 	POS_ICON_HDMI_1080P_MOV_STATE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_Status},
	{MOVPB_GUI_FILE_INDEX, POS_ICON_HDMI_1080P_MOV_FILEIDX_X, 	POS_ICON_HDMI_1080P_MOV_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileIndex},
	{MOVPB_GUI_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{MOVPB_GUI_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{MOVPB_GUI_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{MOVPB_GUI_VOL_BAR	, 	POS_ICON_HDMI_1080P_SCENE_X, 		POS_ICON_HDMI_1080P_SCENE_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, NULL}, // TBD
	{MOVPB_GUI_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 				POS_MOVPB_LOCK_FILE_Y, 				AHC_FALSE, LARGE_SIZE, MAG_2X, DrawMovPb_LockCurFile},
	{MOVPB_GUI_FILENAME , 	POS_ICON_HDMI_1080P_MOV_NAME_X, 	POS_ICON_HDMI_1080P_MOV_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileInfo},
	{MOVPB_GUI_CUR_TIME, 	POS_ICON_HDMI_1080P_MOV_CURTIME_X, 	POS_ICON_HDMI_1080P_MOV_CURTIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_PlayInfo},
	{MOVPB_GUI_TOTAL_TIME, 	POS_ICON_HDMI_1080P_MOV_TOTALTIME_X,POS_ICON_HDMI_1080P_MOV_TOTALTIME_Y,AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_TotalTime},
	{0xFFFF}
};

UI_DARW_SET m_MovPBDraw_Hdmi_720P[] = 
{
	{MOVPB_GUI_STATUS, 	POS_ICON_HDMI_720P_MOV_STATE_X, 	POS_ICON_HDMI_720P_MOV_STATE_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_Status},
	{MOVPB_GUI_FILE_INDEX, POS_ICON_HDMI_720P_MOV_FILEIDX_X, 	POS_ICON_HDMI_720P_MOV_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileIndex},
	{MOVPB_GUI_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X, 		POS_ICON_HDMI_720P_UI_MODE_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{MOVPB_GUI_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{MOVPB_GUI_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 			POS_ICON_HDMI_720P_BATT_Y, 			AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{MOVPB_GUI_VOL_BAR	, 	POS_ICON_HDMI_720P_SCENE_X, 		POS_ICON_HDMI_720P_SCENE_Y,			AHC_FALSE, LARGE_SIZE, MAG_2X, NULL}, // TBD
	{MOVPB_GUI_LOCK_FILE, 	POS_MOVPB_LOCK_FILE_X, 				POS_MOVPB_LOCK_FILE_Y, 				AHC_FALSE, LARGE_SIZE, MAG_2X, DrawMovPb_LockCurFile},
	{MOVPB_GUI_FILENAME , 	POS_ICON_HDMI_720P_MOV_NAME_X, 		POS_ICON_HDMI_720P_MOV_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_FileInfo},
	{MOVPB_GUI_CUR_TIME, 	POS_ICON_HDMI_720P_MOV_CURTIME_X, 	POS_ICON_HDMI_720P_MOV_CURTIME_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_PlayInfo},
	{MOVPB_GUI_TOTAL_TIME, POS_ICON_HDMI_720P_MOV_TOTALTIME_X, POS_ICON_HDMI_720P_MOV_TOTALTIME_Y, AHC_TRUE , LARGE_SIZE, MAG_2X, DrawMovPb_TotalTime},
	{0xFFFF}
};

#if (AUDIO_REC_PLAY_EN)
UI_DARW_SET m_HdmiAudPBDraw_1080P[] =
{
	{AUDPB_GUI_STATUS, 	POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{AUDPB_GUI_FILE_INDEX, POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, DrawAudPb_FileIndex},
	{AUDPB_GUI_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X,POS_ICON_HDMI_1080P_UI_MODE_Y,AHC_FALSE, OSDDrawSetting_UIMode},
	{AUDPB_GUI_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 	POS_ICON_HDMI_1080P_MEDIA_Y, 	AHC_FALSE, OSDDrawSetting_MediaType},
	{AUDPB_GUI_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 	POS_ICON_HDMI_1080P_BATT_Y, 	AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{AUDPB_GUI_VOL_BAR	, 	POS_ICON_HDMI_1080P_SCENE_X, 	POS_ICON_HDMI_1080P_SCENE_Y,	AHC_FALSE, NULL},
	{AUDPB_GUI_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, DrawAudPb_LockCurFile},
	{AUDPB_GUI_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{AUDPB_GUI_CUR_TIME, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{AUDPB_GUI_TOTAL_TIME, POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
UI_DARW_SET m_AudPBDraw_Hdmi[] = 
{
	{AUDPB_GUI_STATUS, 	POS_AUDPB_STATUS_X, 	POS_AUDPB_STATUS_Y, 	AHC_TRUE,  DrawAudPb_Status},
	{AUDPB_GUI_FILE_INDEX, POS_AUDPB_FILE_IDX_X, 	POS_AUDPB_FILE_IDX_Y, 	AHC_FALSE, DrawAudPb_FileIndex},
	{AUDPB_GUI_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X,POS_ICON_HDMI_720P_UI_MODE_Y,AHC_FALSE, OSDDrawSetting_UIMode},
	{AUDPB_GUI_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 	POS_ICON_HDMI_720P_MEDIA_Y, 	AHC_FALSE, OSDDrawSetting_MediaType},
	{AUDPB_GUI_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 	POS_ICON_HDMI_720P_BATT_Y, 	AHC_FALSE, OSDDrawSetting_BatteryStatus},
	{AUDPB_GUI_VOL_BAR	, 	POS_ICON_HDMI_720P_SCENE_X, 	POS_ICON_HDMI_720P_SCENE_Y,	AHC_FALSE, NULL},
	{AUDPB_GUI_LOCK_FILE, 	POS_AUDPB_LOCK_FILE_X, 	POS_AUDPB_LOCK_FILE_Y, 	AHC_FALSE, DrawAudPb_LockCurFile},
	{AUDPB_GUI_FILENAME , 	POS_AUDPB_FILENAME_X, 	POS_AUDPB_FILENAME_Y,	AHC_TRUE,  DrawAudPb_FileInfo},
	{AUDPB_GUI_CUR_TIME, 	POS_AUDPB_CUR_TIME_X, 	POS_AUDPB_CUR_TIME_Y,	AHC_TRUE,  DrawAudPb_PlayInfo},
	{AUDPB_GUI_TOTAL_TIME, POS_AUDPB_TOTAL_TIME_X, POS_AUDPB_TOTAL_TIME_Y, AHC_TRUE,  DrawAudPb_TotalTime},
	{0xFFFF}
};
#endif

UI_DARW_SET m_JpgPBDraw_Hdmi_1080P[] =
{
	{JPGPB_GUI_FILE_INDEX, POS_ICON_HDMI_1080P_JPG_FILEIDX_X, 	POS_ICON_HDMI_1080P_JPG_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileIndex},
	{JPGPB_GUI_UI_MODE	, 	POS_ICON_HDMI_1080P_UI_MODE_X, 		POS_ICON_HDMI_1080P_UI_MODE_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{JPGPB_GUI_SD_STATE, 	POS_ICON_HDMI_1080P_MEDIA_X, 		POS_ICON_HDMI_1080P_MEDIA_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{JPGPB_GUI_BATTERY	, 	POS_ICON_HDMI_1080P_BATT_X, 		POS_ICON_HDMI_1080P_BATT_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{JPGPB_GUI_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 				POS_JPGPB_LOCK_FILE_Y, 				AHC_FALSE, LARGE_SIZE, MAG_2X, DrawJpgPb_LockCurFile},
	{JPGPB_GUI_FILENAME , 	POS_ICON_HDMI_1080P_JPG_NAME_X, 	POS_ICON_HDMI_1080P_JPG_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileInfo},
	{JPGPB_GUI_FILEDATE , 	POS_ICON_HDMI_1080P_JPG_FILEDATE_X, POS_ICON_HDMI_1080P_JPG_FILEDATE_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_DateInfo},
	{0xFFFF}
};
UI_DARW_SET m_JpgPBDraw_Hdmi_720P[] = 
{
	{JPGPB_GUI_FILE_INDEX, POS_ICON_HDMI_720P_JPG_FILEIDX_X, 	POS_ICON_HDMI_720P_JPG_FILEIDX_Y, 	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileIndex},
	{JPGPB_GUI_UI_MODE	, 	POS_ICON_HDMI_720P_UI_MODE_X, 		POS_ICON_HDMI_720P_UI_MODE_Y,		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_UIMode},
	{JPGPB_GUI_SD_STATE, 	POS_ICON_HDMI_720P_MEDIA_X, 		POS_ICON_HDMI_720P_MEDIA_Y, 		AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_MediaType},
	{JPGPB_GUI_BATTERY	, 	POS_ICON_HDMI_720P_BATT_X, 			POS_ICON_HDMI_720P_BATT_Y, 			AHC_FALSE, LARGE_SIZE, MAG_2X, OSDDrawSetting_BatteryStatus},
	{JPGPB_GUI_LOCK_FILE, 	POS_JPGPB_LOCK_FILE_X, 				POS_JPGPB_LOCK_FILE_Y, 				AHC_FALSE, LARGE_SIZE, MAG_2X, DrawJpgPb_LockCurFile},
	{JPGPB_GUI_FILENAME , 	POS_ICON_HDMI_720P_JPG_NAME_X, 		POS_ICON_HDMI_720P_JPG_NAME_Y,		AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_FileInfo},
	{JPGPB_GUI_FILEDATE , 	POS_ICON_HDMI_720P_JPG_FILEDATE_X, 	POS_ICON_HDMI_720P_JPG_FILEDATE_Y,	AHC_TRUE , LARGE_SIZE, MAG_2X, DrawJpgPb_DateInfo},
	{0xFFFF}
};
#endif // #if (HDMI_ENABLE)

#else   // _OEM_DRAW_

extern UI_DARW_SET m_VideoDraw_Lcd[];
extern UI_DARW_SET m_DSCDraw_Lcd[];
extern UI_DARW_SET m_BrowserDraw_Lcd[];
extern UI_DARW_SET m_MovPBDraw_Lcd[];
extern UI_DARW_SET m_AudPBDraw_Lcd[];
extern UI_DARW_SET m_JpgPBDraw_Lcd[];
extern UI_DARW_SET m_VideoDraw_Tv[];
extern UI_DARW_SET m_DSCDraw_Tv[];
extern UI_DARW_SET m_MovPBDraw_Tv[];
extern UI_DARW_SET m_AudPBDraw_Tv[];
extern UI_DARW_SET m_JpgPBDraw_Tv[];
extern UI_DARW_SET m_HdmiVideoDraw[];
extern UI_DARW_SET m_HdmiDSCDraw[];
extern UI_DARW_SET m_HdmiMovPBDraw[];
extern UI_DARW_SET m_AudPBDraw_Hdmi[];
extern UI_DARW_SET m_HdmiJpgPBDraw[];

#endif // #ifndef _OEM_DRAW_

UI_DARW_SET *m_UIDrawSet = (UI_DARW_SET *)m_VideoDraw_Lcd;
extern AHC_BOOL 	Deleting_InBrowser;
extern AHC_BOOL 	Protecting_InBrowser;

extern AHC_BOOL		Delete_File_Confirm;
extern AHC_BOOL		Protect_File_Confirm;
extern AHC_BOOL		UnProtect_File_Confirm;
extern AHC_BOOL 	PowerOff_InProcess;

/*===========================================================================
 * Main body 
 *===========================================================================*/ 
AHC_BOOL SwitchUIDrawSetVideoRecordMode(void)
{
    AHC_BOOL    ahc_ret = AHC_TRUE;

#if (TVOUT_ENABLE)
    if (AHC_IsTVConnectEx()){
        m_UIDrawSet = (UI_DARW_SET *)m_VideoDraw_Tv;
        printc("m_UIDrawSet = m_VideoDraw_Tv \r\n");
    }else
#endif
#if (HDMI_ENABLE)
    if (AHC_IsHdmiConnect()){
        if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P){
            m_UIDrawSet = (UI_DARW_SET *)m_VideoDraw_Hdmi_1080P;
            printc("m_UIDrawSet = m_VideoDraw_Hdmi_1080P \r\n");
        }
        else{
            m_UIDrawSet = (UI_DARW_SET *)m_VideoDraw_Hdmi_720P;
            printc("m_UIDrawSet = m_VideoDraw_Hdmi_720P \r\n");
        }
    }else
#endif
    {
        m_UIDrawSet = (UI_DARW_SET *)m_VideoDraw_Lcd;
        printc("m_UIDrawSet = m_VideoDraw_Lcd \r\n");
    }  

    return ahc_ret;
}

#if (DSC_MODE_ENABLE)
AHC_BOOL SwitchUIDrawSetCameraMode(void)
{
    AHC_BOOL    ahc_ret = AHC_TRUE;

#if (TVOUT_ENABLE)
	if (AHC_IsTVConnectEx()){
		m_UIDrawSet = (UI_DARW_SET *)m_DSCDraw_Tv;
		printc("m_UIDrawSet = m_DSCDraw_Tv \r\n");
	}else
#endif    
#if (HDMI_ENABLE)
    if (AHC_IsHdmiConnect()){
        if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P){
            m_UIDrawSet = (UI_DARW_SET *)m_DSCDraw_Hdmi_1080P;
            printc("m_UIDrawSet = m_DSCDraw_Hdmi_1080P \r\n");
        }
        else{
            m_UIDrawSet = (UI_DARW_SET *)m_DSCDraw_Hdmi_720P;
            printc("m_UIDrawSet = m_DSCDraw_Hdmi_720P \r\n");
        }
    }else
#endif
    {
        m_UIDrawSet = (UI_DARW_SET *)m_DSCDraw_Lcd;
        printc("m_UIDrawSet = m_DSCDraw_Lcd \r\n");
    }
    
    return ahc_ret;
}
#endif

AHC_BOOL SwitchUIDrawSetBrowserMode(void)
{
    AHC_BOOL    ahc_ret = AHC_TRUE;

#if (TVOUT_ENABLE)
	if (AHC_IsTVConnectEx()){
		m_UIDrawSet = (UI_DARW_SET *)m_BrowserDraw_Tv;
		printc("m_UIDrawSet = m_BrowserDraw_Tv \r\n");
	}else
#endif
#if (HDMI_ENABLE)
    if (AHC_IsHdmiConnect()){
        if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P){
            m_UIDrawSet = (UI_DARW_SET *)m_BrowserDraw_Hdmi;
            printc("m_UIDrawSet = m_BrowserDraw_Hdmi_1080P \r\n");
        }
        else{
            m_UIDrawSet = (UI_DARW_SET *)m_BrowserDraw_Hdmi;
            printc("m_UIDrawSet = m_BrowserDraw_Hdmi_720P \r\n");
        }
    }else
#endif
    {
        m_UIDrawSet = (UI_DARW_SET *)m_BrowserDraw_Lcd;
        printc("m_UIDrawSet = m_BrowserDraw_Lcd \r\n");
    }  

    return ahc_ret;
}

AHC_BOOL SwitchUIDrawSetPlaybackMode(void)
{
    AHC_BOOL    ahc_ret = AHC_TRUE;

    if (GetCurrentOpMode() == MOVPB_MODE )//|| GetCurrentOpMode() == JPGPB_MODE || GetCurrentOpMode() == JPGPB_MOVPB_MODE
    {
		#if (TVOUT_ENABLE)
    	if (AHC_IsTVConnectEx()){
    		m_UIDrawSet = (UI_DARW_SET *)m_MovPBDraw_Tv;
    		printc("m_UIDrawSet = m_MovPBDraw_Tv \r\n");
    	}else
		#endif    
    	#if (HDMI_ENABLE)
    	if (AHC_IsHdmiConnect()){
    		if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
    		{
    			m_UIDrawSet = (UI_DARW_SET *)m_MovPBDraw_Hdmi_1080P;
    			printc("m_UIDrawSet = m_MovPBDraw_Hdmi_1080P \r\n");
    		}
    		else
    		{
    			m_UIDrawSet = (UI_DARW_SET *)m_MovPBDraw_Hdmi_720P;
    			printc("m_UIDrawSet = m_MovPBDraw_Hdmi_720P \r\n");
    		}
    	}else
    	#endif
    	{
    		m_UIDrawSet = (UI_DARW_SET *)m_MovPBDraw_Lcd;
    		printc("m_UIDrawSet = m_MovPBDraw_Lcd \r\n");
    	}
    }else if (GetCurrentOpMode() == JPGPB_MODE)
    {
		#if (TVOUT_ENABLE)
    	if (AHC_IsTVConnectEx()){
    		m_UIDrawSet = (UI_DARW_SET *)m_JpgPBDraw_Tv;
    		printc("m_UIDrawSet = m_JpgPBDraw_Tv \r\n");
    	}else
		#endif    
    	#if (HDMI_ENABLE)
    	if (AHC_IsHdmiConnect()){
    		if(MenuSettingConfig()->uiHDMIOutput == HDMI_OUTPUT_1080P)
    		{
    			m_UIDrawSet = (UI_DARW_SET *)m_JpgPBDraw_Hdmi_1080P;
    			printc("m_UIDrawSet = m_JpgPBDraw_Hdmi_1080P \r\n");
    		}
    		else
    		{
    			m_UIDrawSet = (UI_DARW_SET *)m_JpgPBDraw_Hdmi_720P;
    			printc("m_UIDrawSet = m_JpgPBDraw_Hdmi_720P \r\n");
    		}
    	}else
    	#endif
    	{
    		m_UIDrawSet = (UI_DARW_SET *)m_JpgPBDraw_Lcd;
    		printc("m_UIDrawSet = m_JpgPBDraw_Lcd \r\n");
    	}
    }
#if (AUDIO_REC_PLAY_EN)
    else if (GetCurrentOpMode() == AUDPB_MODE)
    {

    }
#endif
  
    return ahc_ret;
}

void UIDrawEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
	UINT8 i;

	for (i = 0; m_UIDrawSet[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_UIDrawSet[i].m_BlockID == idx)
		{
			if ((m_UIDrawSet[i].m_Enable == AHC_TRUE) && (m_UIDrawSet[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_UIDrawSet[i].m_DrawFunc(ubID, m_UIDrawSet[i].m_PosX, m_UIDrawSet[i].m_PosY, m_UIDrawSet[i].m_bLarge, m_UIDrawSet[i].m_ubMag, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_UIDrawSet[i].m_DrawFunc(ubID, m_UIDrawSet[i].m_PosX, m_UIDrawSet[i].m_PosY, m_UIDrawSet[i].m_bLarge, m_UIDrawSet[i].m_ubMag, AHC_TRUE, bkColor, Para1);
			}
		}
	}
}

void UIDrawAudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_AudPBDraw_Lcd[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_AudPBDraw_Lcd[i].m_BlockID == idx)
		{
			if ((m_AudPBDraw_Lcd[i].m_Enable == AHC_TRUE) && (m_AudPBDraw_Lcd[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_AudPBDraw_Lcd[i].m_DrawFunc(ubID, m_AudPBDraw_Lcd[i].m_PosX, m_AudPBDraw_Lcd[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_AudPBDraw_Lcd[i].m_DrawFunc(ubID, m_AudPBDraw_Lcd[i].m_PosX, m_AudPBDraw_Lcd[i].m_PosY, NORMAL_SIZE, MAG_1X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif
}

void UIDrawTV_AudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (TVOUT_ENABLE) && (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_AudPBDraw_Tv[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_AudPBDraw_Tv[i].m_BlockID == idx)
		{
			if ((m_AudPBDraw_Tv[i].m_Enable == AHC_TRUE) && (m_AudPBDraw_Tv[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_AudPBDraw_Tv[i].m_DrawFunc(ubID, m_AudPBDraw_Tv[i].m_PosX, m_AudPBDraw_Tv[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_AudPBDraw_Tv[i].m_DrawFunc(ubID, m_AudPBDraw_Tv[i].m_PosX, m_AudPBDraw_Tv[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

void UIDrawHdmi_AudPBFuncEx(UINT16 ubID, UINT8 idx, AHC_BOOL bClear, AHC_BOOL bShow, GUI_COLOR bkColor, INT32 Para1)
{
#if (HDMI_ENABLE) && (AUDIO_REC_PLAY_EN)

	UINT8 i;

	for (i = 0; m_AudPBDraw_Hdmi[i].m_BlockID != 0xFFFF; i++)
	{
		if (m_AudPBDraw_Hdmi[i].m_BlockID == idx)
		{
			if ((m_AudPBDraw_Hdmi[i].m_Enable == AHC_TRUE) && (m_AudPBDraw_Hdmi[i].m_DrawFunc != NULL))
			{
				if (bClear)
					m_AudPBDraw_Hdmi[i].m_DrawFunc(ubID, m_AudPBDraw_Hdmi[i].m_PosX, m_AudPBDraw_Hdmi[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_FALSE, bkColor, Para1);

				if (bShow)
					m_AudPBDraw_Hdmi[i].m_DrawFunc(ubID, m_AudPBDraw_Hdmi[i].m_PosX, m_AudPBDraw_Hdmi[i].m_PosY, LARGE_SIZE, MAG_2X, AHC_TRUE, bkColor, Para1);
			}
		}
	}

#endif	
}

AHC_BOOL AHC_DrawRotateEvent(UINT32 Event)
{
	UINT8 		LCDdir, SNRdir, UImode;
    AHC_BOOL 	ubOSDFlipEn, ubSNRFlipEn;

	if(Event==EVENT_LCD_COVER_NORMAL)
	{
		LCDdir = AHC_LCD_NORMAL;
		SNRdir = AHC_SNR_NORMAL;
	}
	else if(Event==EVENT_LCD_COVER_ROTATE)
	{
		LCDdir = AHC_LCD_REVERSE;
		SNRdir = AHC_SNR_REVERSE;
    }
    else
		return AHC_TRUE;

    //Check Filp Condition
	switch( AHC_GetRotateSrc() )
	{
		case SRC_KEY:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_KEY);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_KEY);
		break;
		case SRC_HALL_SNR:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_HALL_SNR);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_HALL_SNR);
		break;
		case SRC_G_SNR:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_G_SNR);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_G_SNR);
		break;
		default:
			ubOSDFlipEn = AHC_FALSE;
			ubSNRFlipEn = AHC_FALSE;
		break;
	}

	//Set Drawing Function
	UImode = uiGetCurrentState();

    switch( UImode )
    {
        case UI_CAMERA_STATE    :
			DrawEventHandler = (DRAW_EVENT*) DrawStateCaptureUpdate;
        break;

        case UI_VIDEO_STATE     :
			DrawEventHandler = (DRAW_EVENT*) DrawStateVideoRecUpdate;
        break;

        case UI_BROWSER_STATE   :
			DrawEventHandler = (DRAW_EVENT*) DrawStateLCDBrowserUpdate;
        break;

        case UI_PLAYBACK_STATE  :
			if( JPGPB_MODE == GetCurrentOpMode())
			{
				DrawEventHandler = (DRAW_EVENT*) DrawStatePhotoPb_handler_Lcd;
			}
			else if( MOVPB_MODE == GetCurrentOpMode() )
			{
				DrawEventHandler = (DRAW_EVENT*) DrawStateMovPlaybackUpdate;
			}
			else if( AUDPB_MODE == GetCurrentOpMode() )
			{
				DrawEventHandler = (DRAW_EVENT*) DrawStateAudPlaybackUpdate;
			}
			else if( JPGPB_MOVPB_MODE == GetCurrentOpMode())
			{
			    UINT32 uiCurrentIdx;
                UINT8  ubFileType;
				AHC_UF_GetCurrentIndex(&uiCurrentIdx);
                AHC_UF_GetFileTypebyIndex(uiCurrentIdx, &ubFileType);
                if ( ubFileType == DCF_OBG_JPG )
				    DrawEventHandler = (DRAW_EVENT*) DrawStatePhotoPb_handler_Lcd;
				 else
				    DrawEventHandler = (DRAW_EVENT*) DrawStateMovPlaybackUpdate;   
			}
			
        break;

        default                       :
			DrawEventHandler = NULL;
        break;
    }

    //Set LCD/Sensor Status
    if(ubOSDFlipEn)
		AHC_SetParam(PARAM_ID_LCD_STATUS, LCDdir);

	if(ubSNRFlipEn)
	    AHC_SNR_SetSnrDirStatus(SNRdir);

	//Rotate LCD/Sensors
	LedCtrl_LcdBackLight(AHC_FALSE);
	AHC_SetKitDirection(LCDdir, ubOSDFlipEn ,SNRdir, ubSNRFlipEn);

	if(DrawEventHandler && ubOSDFlipEn)
	{
		DrawEventHandler(Event);
		DrawEventHandler = NULL;
	}

	LedCtrl_LcdBackLight(AHC_TRUE);
	AHC_SetRotateSrc(SRC_MAX);//Reset

	return AHC_TRUE;
}

AHC_BOOL AHC_DrawMenuRotateEvent(UINT32 Event, PSMENUSTRUCT pMenu)
{
	UINT8 		LCDdir, SNRdir;
    AHC_BOOL 	ubOSDFlipEn,ubSNRFlipEn;
	UINT32		MenuId = pMenu->iMenuId;

	if(Event==MENU_LCD_NORMAL)
	{
		LCDdir = AHC_LCD_NORMAL;
		SNRdir = AHC_SNR_NORMAL;
	}
	else if(Event==MENU_LCD_ROTATE)
	{
		LCDdir = AHC_LCD_REVERSE;
		SNRdir = AHC_SNR_REVERSE;
    }
    else
    	return AHC_TRUE;

    //Check Filp Condition
	switch( AHC_GetRotateSrc() )
	{
		case SRC_KEY:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_KEY);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_KEY);
		break;
		case SRC_HALL_SNR:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_HALL_SNR);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_HALL_SNR);
		break;
		case SRC_G_SNR:
			ubOSDFlipEn = AHC_CheckOSDFlipEn(CTRL_BY_G_SNR);
			ubSNRFlipEn = AHC_CheckSNRFlipEn(CTRL_BY_G_SNR);
		break;
		default:
			ubOSDFlipEn = AHC_FALSE;
			ubSNRFlipEn = AHC_FALSE;
		break;
	}

	//Set Special Drawing Function
	if(Deleting_InBrowser || Protecting_InBrowser)
	{
		if( (Deleting_InBrowser && Delete_File_Confirm) 		||
			(Protecting_InBrowser==1 && Protect_File_Confirm) 	||
			(Protecting_InBrowser==2 && UnProtect_File_Confirm)	)
			DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_EditOneFile;

		goto L_Set;
	}
	else if(PowerOff_InProcess==AHC_TRUE)
	{
		#if (POWER_OFF_CONFIRM_PAGE_EN)
		DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_PowerOff;
		#endif
		goto L_Set;
	}

	//Set Drawing Function
	if( MenuId >= MENUID_QUICK_MENU_VIDEO && MenuId <= MENUID_MAIN_MENU_EXIT )//Main Menu
	{
		switch( MenuId )
		{
			#if (USB_MODE_SELECT_EN)
			case MENUID_MODE_SELECT:
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawMainPage_ModeSelect;
			break;
			#endif

			#if (TOP_MENU_PAGE_EN)
			case MENUID_TOP_MENU:
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawTopMenuPage;
			break;
			#endif

			default:
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawMainPage;
			break;
		}
	}
	else
	{
	    switch( MenuId )
	    {
	        case MENUID_SUB_MENU_FLASH_LEVEL    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_FlashLevel;
	        break;

	        case MENUID_SUB_MENU_DELETE_ALL_VIDEO     :
			case MENUID_SUB_MENU_DELETE_ALL_IMAGE	  :
			case MENUID_SUB_MENU_PROTECT_ALL_VIDEO    :
			case MENUID_SUB_MENU_PROTECT_ALL_IMAGE    :
			case MENUID_SUB_MENU_UNPROTECT_ALL_VIDEO  :
			case MENUID_SUB_MENU_UNPROTECT_ALL_IMAGE  :
			case MENUID_SUB_MENU_FORMAT_SD_CARD    	  :
	        case MENUID_SUB_MENU_RESET_SETUP    	  :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_ConfirmPage;
	        break;

	        case MENUID_SUB_MENU_CLOCK_SETTINGS    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_ClockSetting;
	        break;

			#if (MENU_GENERAL_DRIVER_ID_SETTING_EN)
			case MENUID_SUB_MENU_DRIVER_ID_SETTINGS:
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_DriverIdSetting;
			break;
			#endif

	        case MENUID_SUB_MENU_FW_VERSION_INFO    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_FwVersionInfo;
	        break;

			#if (MENU_GENERAL_GPSINFO_EN)
	        case MENUID_SUB_MENU_GPS_INFO    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_GPSInfo;
	        break;
	        #endif

	        case MENUID_SUB_MENU_EV    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_EV;
	        break;

	        case MENUID_SUB_MENU_SD_CARD_INFO    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_StorageInfo;
	        break;

	        case MENUID_SUB_MENU_VOLUME    :
				DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage_Volume;
	        break;

	        default                       :
	        	DrawMenuEventHandler = (DRAW_MENUEVENT*) MenuDrawSubPage;
	        break;
	    }
    }

L_Set:

    //Set LCD/Sensor Status
	if(ubOSDFlipEn)
		AHC_SetParam(PARAM_ID_LCD_STATUS, LCDdir);

	if(ubSNRFlipEn)
	    AHC_SNR_SetSnrDirStatus(SNRdir);

	//Rotate LCD/Sensors
	LedCtrl_LcdBackLight(AHC_FALSE);
	AHC_SetKitDirection(LCDdir, ubOSDFlipEn, SNRdir, ubSNRFlipEn);

	if(DrawMenuEventHandler && ubOSDFlipEn)
	{
		DrawMenuEventHandler(pMenu);
		DrawMenuEventHandler = NULL;
	}

	LedCtrl_LcdBackLight(AHC_TRUE);
	AHC_SetRotateSrc(SRC_MAX);//Reset

	return AHC_TRUE;
}


