#ifdef __UI_STYLE_MMI_ANDROID_KEYGUARD__

#ifndef __MMI_ANDROID_KEYGUARDAPP_ID_H__
#define __MMI_ANDROID_KEYGUARDAPP_ID_H__

#include "mmi_wdg_ballslide.h"

typedef enum KeyGuardWndId_e_
{
    ANDROID_KEYGUARD_WND_MAIN = WND_ID_APP_BASE,
} AndroidKeyGuardWndId_e;

typedef enum
{
    KEYGUARD_VIEW_BEGIN =APP_WDG_START,
    KEYGUARD_BG,
    KEYGUARD_UNLOCK,
    KEYGUARD_DARK,
    KEYGUARD_EM_NUM,
    KEYGUARD_IDLE_INFO,
    KEYGUARD_TIME,
    KEYGUARD_I12H,
    KEYGUARD_DATE,
    KEYGUARD_MEDIA_NAME,
    KEYGUARD_COUNT_DOWN,
    KEYGUARD_NETWORK,
    KEYGUARD_NETWORK_SLAVE,
    KEYGUARD_DIALOG_INFO_BG,
    KEYGUARD_DIALOG_INFO_TEXT,
    KEYGUARD_NEW_MSG,
    KEYGUARD_NEW_MSG_TEXT,
    KEYGUARD_MISS_CALL,
    KEYGUARD_MISS_CALL_TEXT,
    ANDROID_KEYGUARD_UNLOCK_CNTR,
#ifndef __UI_STYLE_MMI_ANDROID_4_0__
    ANDROID_KEYGUARD_UPBG,
    ANDROID_KEYGUARD_DOWNBG,
    ANDROID_KEYGUARD_LOCKTXT,
    ANDROID_KEYGUARD_LOCKICON,
    ANDROID_KEYGUARD_LEFTANIM,
    ANDROID_KEYGUARD_RIGHTANIM,
    ANDROID_KEYGUARD_DOWN_UNLOCK,
    ANDROID_KEYGUARD_DOWNTXTTOIMG,
#endif // !__UI_STYLE_MMI_ANDROID_4_0__
    KEYGUARD_VIEW_END
}KeyGuardView_e;
#endif /*__MMI_KEYGUARDAPP_ID_H__*/
#endif //__UI_STYLE_MMI_ANDROID_KEYGUARD__

