#ifndef __MMI_MMSSETTINGAPP_VIEW_ID_H__
#define __MMI_MMSSETTINGAPP_VIEW_ID_H__

#include "mmi_message_cfg.h"
#include "mmi_view_id_range.h"
#include "mmi_mmssettingapp.h"
#include "mmi_common_thmid.h"

enum
{
/* View ID start */
	MMSA_SETTINGMENU_VIEW = MMI_VIEW_ID_AP_BEGIN,
	MMSA_SETTINGITEMMENU_VIEW,

	MMSA_SET_MULTIMEDIA_RETRIEVAL_VIEW,
	MMSA_SET_ALLOW_ANONYMOUS_MSGS_VIEW,
	MMSA_SET_RECEIVE_ADVERTS_VIEW,
	MMSA_SET_STATUS_REPORT_VIEW,
	MMSA_SET_DENY_REPORT_SENDING_VIEW,
	MMSA_SET_VALIDITY_PERIOD_VIEW,
	MMSA_SET_BACKUP_SENT_VIEW,
	MMSA_DUO_SELECTION_VIEW,

	MMSA_MMS_RADIOLIST_VIEW,
	MMSA_RADIOLIST_TEXTLOCATION_MODEL,
	MMSA_RADIOLIST_IMAGESIZE_MODEL,
	MMSA_DURATIONEDITOR_VIEW,
    MMSA_MM_RETRIEVAL_MODEL,
	MMSA_MM_VALIDITY_PERIOD_MODEL
/* View ID end */
};

enum
{
/* Widget ID start */
	MMSA_SETTINGMENU_TITLE = 1,
	MMSA_SETTINGMENU_MENU,
	MMSA_SETTINGITEMMENU_TITLEWIDGET,
	MMSA_SETTINGITEMMENU_MENUWIDGET,
	MMSA_SET_IMAGE_SIZE_TITLEWIDGET,
	MMSA_SET_IMAGE_SIZE_MENU,
	MMSA_SET_MULTIMEDIA_RETRIEVAL_TITLEWIDGET,
	MMSA_SET_MULTIMEDIA_RETRIEVAL_MENU,
	MMSA_SET_ALLOW_ANONYMOUS_MSGS_TITLEWIDGET,
	MMSA_SET_ALLOW_ANONYMOUS_MSGS_MENU,
    MMSA_SET_RECEIVE_ADVERTS_TITLEWIDGET,
    MMSA_SET_RECEIVE_ADVERTS_MENU,
    MMSA_SET_STATUS_REPORT_TITLEWIDGET,
    MMSA_SET_STATUS_REPORT_MENU,
    MMSA_SET_DENY_REPORT_SENDING_TITLEWIDGET,
    MMSA_SET_DENY_REPORT_SENDING_MENU,
    MMSA_SET_VALIDITY_PERIOD_TITLEWIDGET,
    MMSA_SET_VALIDITY_PERIOD_MENU,
    MMSA_SET_BACKUP_SENT_TITLEWIDGET,

    MMSA_DUO_SELECTION_TITLEWIDGET,
    MMSA_DUO_SELECTION_MENU,
	MMSA_MMS_RADIOLIST_TITLE,
	MMSA_MMS_RADIOLIST_MENUWDG,
	MMSA_DURATIONEDITOR_TITLEWIDGET,
	MMSA_DURATIONEDITOR_ABSCONTAINER,
	MMSA_DURATIONEDITOR_TEXTWIDGET,
	MMSA_DURATIONEDITOR_INPUTWIDGET

/* Widget ID end */
};

enum e_DUO_SELECTION_MENU_ITEM
{
    /* Binary ID start */
    MNU_MMSA_DUO_MASTER,
    MNU_MMSA_DUO_SLAVE,
};


#endif /* __MMI_MMSSETTINGAPP_VIEW_ID_H__ */
