typedef enum
{
    NTP_WND_MAIN = WND_ID_APP_BASE,
    NTP_WND_SELECT_SIM,
    NTP_WND_SELECT_SERVER,
} NtpWndId_e;

typedef enum
{
    NTP_WDG_MFLCNTR = WND_ID_APP_BASE,
	NTP_WDG_IPCNTR,
	NTP_WDG_IPTEXT,
	NTP_WDG_IP,
#ifndef __MMI_WISE_MINI_WQVGA__
	NTP_WDG_ONCNTR,
	NTP_WDG_ONTEXT,
	NTP_WDG_ON,
#endif
	NTP_WDG_OFFCNTR,
	NTP_WDG_OFFTEXT,
	NTP_WDG_OFF,
	NTP_WDG_SIMCNTR,
	NTP_WDG_SIMTEXT,
	NTP_WDG_SIM,
} NtpWdgId_e;

typedef enum
{
    MNU_NTP_START_SYNC = 0,
    MNU_NTP_SELECT_SERVER,
	MNU_NTP_IP_NTSC,
	MNU_NTP_IP_MICROSOFT,
	MNU_NTP_SIM1,
	MNU_NTP_SIM2,
}NtpMenuId_e;

