#ifndef __MMI_MAE_SOFTKEYBOARD_RESOURCE_ID_H__
#define __MMI_MAE_SOFTKEYBOARD_RESOURCE_ID_H__

enum
{
/* Widget ID start */
	//for language input
	MAE_SOFTKEYBOARD_EN_CAPITAL = 0,			//English uppercase
	MAE_SOFTKEYBOARD_EN_LC,					//English lowercase
	MAE_SOFTKEYBOARD_CN_PINYIN,				//Chinses PINYIN
	MAE_SOFTKEYBOARD_CN_STROKE,				//Chinese Stroke
	MAE_SOFTKEYBOARD_CN_BPMF,				//Chinese BPMF
	MAE_SOFTKEYBOARD_ES_CAPITAL,			//Spanish uppercase
	MAE_SOFTKEYBOARD_ES_LC,					//Spanish lowercase
	MAE_SOFTKEYBOARD_VN_CAPITAL,			//Vietnam	uppercase
	MAE_SOFTKEYBOARD_VN_LC,					//Vietnam lowercase
	MAE_SOFTKEYBOARD_RU_CAPITAL,			//Russian uppercase
	MAE_SOFTKEYBOARD_RU_LC,					//Russian lowercase
	MAE_SOFTKEYBOARD_FR_CAPITAL,			//France uppercase
	MAE_SOFTKEYBOARD_FR_LC,					//France lowercase
	MAE_SOFTKEYBOARD_IN_CAPITAL,			//Indonesia uppercase
	MAE_SOFTKEYBOARD_IN_LC,					//Indonesia lowercase
	MAE_SOFTKEYBOARD_PT_CAPITAL,			//Portugal uppercase
	MAE_SOFTKEYBOARD_PT_LC,					//Portugal lowercase
	MAE_SOFTKEYBOARD_MA_CAPITAL,			//Malaysia uppercase
	MAE_SOFTKEYBOARD_MA_LC,					//Malaysia lowercase
	MAE_SOFTKEYBOARD_TR_CAPITAL,			//Trukish uppercase
	MAE_SOFTKEYBOARD_TR_LC,					//Turkish lowercase
	MAE_SOFTKEYBOARD_TH_CAPITAL,			//Thai uppercase
	MAE_SOFTKEYBOARD_TH_LC,					//Thai lowercase
	MAE_SOFTKEYBOARD_ARABIC,				//Arabic
	MAE_SOFTKEYBOARD_PERSIAN,				//PERSIAN
	MAE_SOFTKEYBOARD_GM_CAPITAL,		//German uppercase
	MAE_SOFTKEYBOARD_GM_LC,				//German lowercase
	MAE_SOFTKEYBOARD_IT_CAPITAL,			//Italian uppercase
	MAE_SOFTKEYBOARD_IT_LC,				//Italian lowercase
	MAE_SOFTKEYBOARD_HINDI_1,					//Hindi
	MAE_SOFTKEYBOARD_HINDI_2,					//Hindi
	MAE_SOFTKEYBOARD_TAMIL_1,					//Tamil
	MAE_SOFTKEYBOARD_TAMIL_2,					//Tamil
	MAE_SOFTKEYBOARD_TELUGU_1,					//Telugu
	MAE_SOFTKEYBOARD_TELUGU_2,					//Telugu
	MAE_SOFTKEYBOARD_BURMESE_1,					//Burmese
	MAE_SOFTKEYBOARD_BURMESE_2,					//Burmese
	MAE_SOFTKEYBOARD_PUNJABI_1,					//Punjabi
	MAE_SOFTKEYBOARD_PUNJABI_2,					//Punjabi
	MAE_SOFTKEYBOARD_CS_CAPITAL,		//CZECH uppercase
	MAE_SOFTKEYBOARD_CS_LC,				//CZECH lowercase
	MAE_SOFTKEYBOARD_EL_CAPITAL,		//GREEK uppercase
	MAE_SOFTKEYBOARD_EL_LC,				//GREEK lowercase
	MAE_SOFTKEYBOARD_PL_CAPITAL,		//POLISH uppercase
	MAE_SOFTKEYBOARD_PL_LC,				//POLISH lowercase
	MAE_SOFTKEYBOARD_NL_CAPITAL,		//Dutch uppercase
	MAE_SOFTKEYBOARD_NL_LC,				//Dutch lowercase
	MAE_SOFTKEYBOARD_BENGALI_1,				//BENGALI
	MAE_SOFTKEYBOARD_BENGALI_2,				//BENGALI
	MAE_SOFTKEYBOARD_URDU_1,				//Urdu
	MAE_SOFTKEYBOARD_URDU_2,				//Urdu
	MAE_SOFTKEYBOARD_SMART,                 //Smart ABC
	//for special usages
	MAE_SOFTKEYBOARD_SYMBOL,
	MAE_SOFTKEYBOARD_CHSYMBOL,
	MAE_SOFTKEYBOARD_SYMBOL_PAGE2,
	MAE_SOFTKEYBOARD_NUMERIC,
	MAE_SOFTKEYBOARD_FORMATINPUT,
	MAE_SOFTKEYBOARD_RATE,
	MAE_SOFTKEYBOARD_PIN,
	MAE_SOFTKEYBOARD_DIALING,
/* Widget ID end */
	MAE_SOFTKEYBOARD_ID_TOTAL_COUNT
};

#endif /*__MAE_SOFTKEYBOARD_RESOURCE_ID_H__ */

