#ifndef __MMI_WDG_HEADERS_H__
#define __MMI_WDG_HEADERS_H__

/*=============================================================*/
// include
/*=============================================================*/
#include "mmi_wdg_common_interface.h"
#include "mmi_common_color_def.h"
#include "mmi_common_color_id.h"
#include "mmi_layout_gen.h"

#include "mmi_wdg_abscontainer.h"
#include "mmi_wdg_animationcontainer.h"
#include "mmi_wdg_basicbitmap.h"
#include "mmi_wdg_bitmap.h"
#include "mmi_wdg_button.h"
#include "mmi_wdg_commonpickitem.h"
#include "mmi_wdg_date.h"
#include "mmi_wdg_dateicon.h"
#include "mmi_wdg_doubleitem.h"
#include "mmi_wdg_dummy.h"
#include "mmi_wdg_event.h"
#include "mmi_wdg_fadeout.h"
#include "mmi_wdg_fcdate.h"
#include "mmi_wdg_fctime.h"
#include "mmi_wdg_fliptext.h"
#include "mmi_wdg_glowtext.h"
#include "mmi_wdg_gltimeindwidget.h"
#if defined (__UI_STYLE_MMI_IFONE__) || defined (__UI_STYLE_MMI_STYLE_SWITCH__)
#include "mmi_wdg_ifone.h"
#endif
#include "mmi_wdg_image.h"
#include "mmi_wdg_overlayimage.h"
#include "mmi_wdg_image_doubleitem.h"
#include "mmi_wdg_image_text_image.h"
#include "mmi_wdg_imeassist.h"
#include "mmi_wdg_indicator.h"
#include "mmi_wdg_input.h"
#include "mmi_wdg_ip.h"
#include "mmi_wdg_list.h"
#include "mmi_wdg_menu.h"
#include "mmi_wdg_itf_menu.h"
#include "mmi_wdg_animated_menu.h"
#include "mmi_wdg_mflcontainer.h"
#include "mmi_wdg_osd.h"
#include "mmi_wdg_pick.h"
#include "mmi_wdg_progress.h"
#include "mmi_wdg_propcontainer.h"
#include "mmi_wdg_pulldown.h"
#include "mmi_wdg_ringlist.h"
#include "mmi_wdg_scrollbar.h"
#include "mmi_wdg_scroll_indicator.h"
#include "mmi_wdg_sheetcontainer.h"
#include "mmi_wdg_shortcutbar.h"
#include "mmi_wdg_slideswitch.h"
#include "mmi_wdg_snapshot.h"
#include "mmi_wdg_softkey.h"
#include "mmi_wdg_statusbar.h"
#include "mmi_wdg_switchicon.h"
#include "mmi_wdg_switchiconitem.h"
#include "mmi_wdg_tab.h"
#include "mmi_wdg_text.h"
#include "mmi_wdg_textbubble.h"
#include "mmi_wdg_time.h"
#include "mmi_wdg_timerformat.h"
#include "mmi_wdg_title.h"
#include "mmi_wdg_transition.h"
#include "mmi_wdg_viewercontainer.h"
#include "mmi_wdg_viewport.h"
#include "mmi_wdg_volume.h"

#endif //__MMI_WDG_HEADERS_H__
