ApBegin(RS,CLSID_PICVIEWERAPP)
    WndBegin(PICVIEWER_WND_VIEW)
        WdgBegin(CLSID_IMAGEWIDGET,ImageWdg)
            WdgImageCreateForWndRC({{0,0},{PICVIEWERAPP_DEFAULT_SCREEN_WIDTH,PICVIEWERAPP_DEFAULT_SCREEN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,ImageWdg)
#if defined(__MULTI_TOUCH__) || defined(__MULTI_TOUCH_SLIM__)
        WdgBegin(CLSID_VIEWPORTWIDGET,ZmViewportEx)
            WdgViewportCreateForWndRC({{0,0},{PICVIEWERAPP_DEFAULT_SCREEN_WIDTH,PICVIEWERAPP_DEFAULT_SCREEN_HEIGHT},10,ALIGN_H_CENTER|ALIGN_V_MIDDLE})
        WdgEnd(CLSID_VIEWPORTWIDGET,ZmViewportEx)
#endif  //defined(__MULTI_TOUCH__) || defined(__MULTI_TOUCH_SLIM__)
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,ActionBarBgImageWdg)
            WdgImageCreateForWndRC({{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_AP_SOFTKEY_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_AP_SOFTKEY_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ActionBarBgImageWdg)
        WdgBegin(CLSID_BUTTONWIDGET,PreviousButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_PREVIOUS_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_PREVIOUS_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_PREVIOUS_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_PREVIOUS_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_PREVIOUS_UNPRESS,PHOTOVIEWER_IMG_PREVIOUS_PRESS})
        WdgEnd(CLSID_BUTTONWIDGET,PreviousButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,NextButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_NEXT_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_NEXT_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_NEXT_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_NEXT_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_NEXT_UNPRESS,PHOTOVIEWER_IMG_NEXT_PRESS})
        WdgEnd(CLSID_BUTTONWIDGET,NextButtonWdg)
#endif
#ifndef __APP_MMI_SMALLROM__
#ifdef __MMI_PICVIEWER_SLIDESHOW_ENABLE__
        WdgBegin(CLSID_BUTTONWIDGET,ViewSliceShow)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,COMMON_IMG_AP_PLAY_UNPRESSED,COMMON_IMG_AP_PLAY_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ViewSliceShow)
 #endif
        WdgBegin(CLSID_BUTTONWIDGET,BackButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,COMMON_IMG_AP_BACK_UNPRESSED,COMMON_IMG_AP_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,BackButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,DeleteLSKButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_DELETE_LSK_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_DELETE_LSK_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_DELETE_LSK_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_DELETE_LSK_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_DELETE_UNPRESSED,PHOTOVIEWER_IMG_DELETE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,DeleteLSKButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,OptionButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_OPTION_UNPRESS,PHOTOVIEWER_IMG_OPTION_PRESS})
        WdgEnd(CLSID_BUTTONWIDGET,OptionButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,OkButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_ACTION_KEY_X_POS,PICVIEWERAPP_DISPLAY_ACTION_KEY_Y_POS},{PICVIEWERAPP_DISPLAY_ACTION_KEY_WIDTH,PICVIEWERAPP_DISPLAY_ACTION_KEY_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_SET_UNPRESSED,PHOTOVIEWER_IMG_SET_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,OkButtonWdg)
         WdgBegin(CLSID_BUTTONWIDGET,BlogButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_SLIDESHOW_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_OPTION_UNPRESS,PHOTOVIEWER_IMG_OPTION_PRESS})
        WdgEnd(CLSID_BUTTONWIDGET,BlogButtonWdg)
#endif
        WdgBegin(CLSID_TEXTWIDGET,PicIdxTextWdg)
            WdgTextCreateForWndRC({{PICVIEWERAPP_DISPLAY_PIC_IDX_X_POSITION,PICVIEWERAPP_DISPLAY_PIC_IDX_Y_POSITION},{PICVIEWERAPP_DISPLAY_PIC_IDX_WIDTH,PICVIEWERAPP_DISPLAY_PIC_IDX_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,PicIdxTextWdg)
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_MENUWIDGET,PicMenu)
            WdgMenuCreateForWndRC({{PICVIEWERAPP_DISPLAY_QUICKMENU_X_POS,PICVIEWERAPP_DISPLAY_QUICKMENU_Y_POS},{PICVIEWERAPP_DISPLAY_QUICKMENU_WIDTH,PICVIEWERAPP_DISPLAY_QUICKMENU_HEIGHT},WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_MENUWIDGET,PicMenu)
        WdgBegin(CLSID_BUTTONWIDGET,SelectButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_OPTION_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_SELECT_UNPRESSED,PHOTOVIEWER_IMG_SELECT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SelectButtonWdg)
#endif
    WndEnd(PICVIEWER_WND_VIEW)
#ifdef __MMI_PICVIEWER_SLIDESHOW_ENABLE__
    WndBegin(PICVIEWER_WND_SLIDESHOW)
        WdgBegin(CLSID_IMAGEWIDGET,SlideImg)
            WdgImageCreateForWndRC({{0,0},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,SlideImg)
    WndEnd(PICVIEWER_WND_SLIDESHOW)
#endif
    WndBegin(PICVIEWER_WND_SETWALLPAPER)
        WdgBegin(CLSID_IMAGEWIDGET,WallImg)
            WdgImageCreateForWndRC({{0,0},{PICVIEWERAPP_DEFAULT_SCREEN_WIDTH,PICVIEWERAPP_DEFAULT_SCREEN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,WallImg)
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,ZoomInButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_CROPPING_ZOOM_IN_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_CROPPING_ZOOM_IN_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_CROPPING_ZOOM_IN_BUTTONWIDGET_WIDTH,PICVIEWERAPP_CROPPING_ZOOM_IN_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_OPTIONS_ZOOM_IN_UNPRESSED,PHOTOVIEWER_IMG_OPTIONS_ZOOM_IN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZoomInButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,ZoomOutButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_CROPPING_ZOOM_OUT_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_CROPPING_ZOOM_OUT_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_CROPPING_ZOOM_OUT_BUTTONWIDGET_WIDTH,PICVIEWERAPP_CROPPING_ZOOM_OUT_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_OPTIONS_ZOOM_OUT_UNPRESSED,PHOTOVIEWER_IMG_OPTIONS_ZOOM_OUT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZoomOutButtonWdg)
        WdgBegin(CLSID_IMAGEWIDGET,WallActBg)
            WdgImageCreateForWndRC({{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_AP_SOFTKEY_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_AP_SOFTKEY_BG)
        WdgEnd(CLSID_IMAGEWIDGET,WallActBg)
        WdgBegin(CLSID_BUTTONWIDGET,WallBack)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_BACK_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,COMMON_IMG_AP_BACK_UNPRESSED,COMMON_IMG_AP_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,WallBack)
        WdgBegin(CLSID_BUTTONWIDGET,SetButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_CROPPING_SET_WALLPAPER_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_CROPPING_SET_WALLPAPER_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_CROPPING_SET_WALLPAPER_BUTTONWIDGET_WIDTH,PICVIEWERAPP_CROPPING_SET_WALLPAPER_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_SET_AS_WALLPAPER_UNPRESSED,PHOTOVIEWER_IMG_SET_AS_WALLPAPER_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SetButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,ZoomSwitchButtonWdg)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_CROPPING_ZOOM_SWITCH_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_CROPPING_ZOOM_SWITCH_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_CROPPING_ZOOM_SWITCH_BUTTONWIDGET_WIDTH,PICVIEWERAPP_CROPPING_ZOOM_SWITCH_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_ZOOM_UNPRESSED,PHOTOVIEWER_IMG_ZOOM_PRESS})
        WdgEnd(CLSID_BUTTONWIDGET,ZoomSwitchButtonWdg)
#endif
    WndEnd(PICVIEWER_WND_SETWALLPAPER)
#ifdef __MMI_PICVIEWER_ZOOM_ENABLE__
    WndBegin(PICVIEWER_WND_ZOOM)
        WndSetAllSoftkeyRC({SK_ZOOM_OUT, SK_NONE, SK_ZOOM_IN})
        WdgBegin(CLSID_IMAGEWIDGET,ZmImg)
            WdgImageCreateForWndRC({{0,0},{PICVIEWERAPP_DEFAULT_SCREEN_WIDTH,PICVIEWERAPP_DEFAULT_SCREEN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,ZmImg)
        WdgBegin(CLSID_VIEWPORTWIDGET,ZmViewport)
            WdgViewportCreateForWndRC({{0,0},{PICVIEWERAPP_DEFAULT_SCREEN_WIDTH,PICVIEWERAPP_DEFAULT_SCREEN_HEIGHT},10,ALIGN_H_CENTER|ALIGN_V_MIDDLE})
        WdgEnd(CLSID_VIEWPORTWIDGET,ZmViewport)
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,ZmActBg)
            WdgImageCreateForWndRC({{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_SK_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_AP_SOFTKEY_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_AP_SOFTKEY_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ZmActBg)
        WdgBegin(CLSID_BUTTONWIDGET,ZmIn)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_ZOOM_IN_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_ZOOM_IN_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_ZOOM_IN_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_ZOOM_IN_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_ZOOMIN_UNPRESSED,PHOTOVIEWER_IMG_ZOOMIN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZmIn)
        WdgBegin(CLSID_BUTTONWIDGET,ZmBack)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_ZOOM_BACK_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_ZOOM_BACK_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_ZOOM_BACK_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_ZOOM_BACK_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,COMMON_IMG_AP_BACK_UNPRESSED,COMMON_IMG_AP_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZmBack)
        WdgBegin(CLSID_BUTTONWIDGET,ZmOut)
            WdgButtonCreateForWndRC({{PICVIEWERAPP_DISPLAY_ZOOM_OUT_BUTTONWIDGET_X_POSITION,PICVIEWERAPP_DISPLAY_ZOOM_OUT_BUTTONWIDGET_Y_POSITION},{PICVIEWERAPP_DISPLAY_ZOOM_OUT_BUTTONWIDGET_WIDTH,PICVIEWERAPP_DISPLAY_ZOOM_OUT_BUTTONWIDGET_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,PHOTOVIEWER_IMG_ZOOMOUT_UNPRESSED,PHOTOVIEWER_IMG_ZOOMOUT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZmOut)
#endif
		WndEnd(PICVIEWER_WND_ZOOM)
#endif

    WndBegin(PICVIEWER_WND_SETAS)
        WdgBegin(CLSID_VTMMENU,SetAsVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SET_AS,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
#ifdef __USER_DEFINE_POWERONOFF_ANIM__
#ifdef __APP_MMI_SCREENSAVER__
#ifdef __MMI_PICVIEWER_SET_CONTACT_ENABLE__
            WdgMenuItemTextRC(5, { TXT_OIL2_N_CONTACT, TXT_LIL_N_WALLPAPER, TXT_LIL_N_POWER_ON,TXT_LIL_N_POWER_OFF,TXT_LIL_N_SCREENSAVER })
            WdgDynamicMenuItemInfRC(5, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_CONTACT, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWERON_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWEROFF_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_SCREENSAVER_ANIM, 0} })
#else
            WdgMenuItemTextRC(4, { TXT_LIL_N_WALLPAPER, TXT_LIL_N_POWER_ON,TXT_LIL_N_POWER_OFF,TXT_LIL_N_SCREENSAVER })
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWERON_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWEROFF_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_SCREENSAVER_ANIM, 0} })
#endif  /* __MMI_PICVIEWER_SET_CONTACT_ENABLE__ */
#else
#ifdef __MMI_PICVIEWER_SET_CONTACT_ENABLE__
            WdgMenuItemTextRC(4, { TXT_OIL2_N_CONTACT, TXT_LIL_N_WALLPAPER , TXT_LIL_N_POWER_ON,TXT_LIL_N_POWER_OFF })
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_CONTACT, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWERON_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWEROFF_ANIM, 0} })
#else
            WdgMenuItemTextRC(3, { TXT_LIL_N_WALLPAPER, TXT_LIL_N_POWER_ON,TXT_LIL_N_POWER_OFF })
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWERON_ANIM, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_POWEROFF_ANIM, 0} })
#endif  /* __MMI_PICVIEWER_SET_CONTACT_ENABLE__ */
#endif  /* __APP_MMI_SCREENSAVER__ */
#else
#ifdef __MMI_PICVIEWER_SET_CONTACT_ENABLE__
            WdgMenuItemTextRC(2, { TXT_OIL2_N_CONTACT, TXT_LIL_N_WALLPAPER })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_CONTACT, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0} })
#else
            WdgMenuItemTextRC(1, { TXT_LIL_N_WALLPAPER })
            WdgDynamicMenuItemInfRC(1, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_PICVIEWER_SET_AS_WALLPAPER, 0} })
#endif  /* __MMI_PICVIEWER_SET_CONTACT_ENABLE__ */
#endif  /* __USER_DEFINE_POWERONOFF_ANIM__ */
        WdgEnd(CLSID_VTMMENU,SetAsVtm)
	WndEnd(PICVIEWER_WND_SETAS)


ApEnd(RS,CLSID_PICVIEWERAPP)

