////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

/**
* @file mmi_emapp_menuinfo.h
*
* Class Id:
*
*/
#ifndef __MMI_EMAPP_MENUINFO_H__
#define __MMI_EMAPP_MENUINFO_H__

#include "mmi_emapp_custom.h"

typedef enum
{
    EM_MNU_SOFTWARE_VERSION                             ,
    EM_MNU_USER_SOFTWARE_VERSION                        ,
    EM_MNU_AUTO_TEST_USER_SOFTWARE_VERSION              ,
    EM_MNU_DEVICE_INFO                                  ,
    EM_MNU_IMEI                                         ,
    EM_MNU_STANDBY_TIME                                 ,
    EM_MNU_GSM_GPRS_MAIN_MENU                           ,
    EM_MNU_GSM_GPRS                                     ,
    EM_MNU_BAND_SELECTION                               ,
    EM_MNU_AUDIO_SETTING                                ,
    EM_MNU_NETWORK_INFO                                 ,
    EM_MNU_DATA_INFO                                    ,
    EM_MNU_LAYER1_INFO                                  ,
    EM_MNU_DRIVER                                       ,
#ifdef __DUAL_SIM_MMI__
    EM_MNU_GPRS_MASTER_SIM                              ,
    EM_MNU_GPRS_SLAVE_SIM                               ,
#endif

    EM_MNU_GSM_OFF                                      ,
    EM_MNU_B                                            ,
    EM_MNU_C_GPRS                                       ,
    EM_MNU_C_GSM                                        ,
    EM_MNU_GPRS_ATTACH                                  ,
    EM_MNU_GPRS_DETACH                                  ,
    EM_MNU_GPRS_STATE                                   ,
    EM_MNU_PDP_CONFIG                                   ,
    EM_MNU_PDP_CONFIG_PDP_TYPE_IP                       ,
    EM_MNU_PDP_CONFIG_PDP_TYPE_PPP                      ,
    EM_MNU_PDP_CONFIG_APN                               ,
    EM_MNU_PDP_CONFIG_PDP_ADDRESS                       ,
    EM_MNU_PDP_CONFIG_DATA_COMPRESSION_ON               ,
    EM_MNU_PDP_CONFIG_DATA_COMPRESSION_OFF              ,
    EM_MNU_PDP_CONFIG_HEADER_COMPRESSION_ON             ,
    EM_MNU_PDP_CONFIG_HEADER_COMPRESSION_OFF            ,
    EM_MNU_PDP_CONFIG_SEND_AT_CMD_DEFINE_PDP_CONTEXT    ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED                     ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_PRECEDENCE_CLASS    ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_DELAY_CLASS         ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_RELIABILITY_CLASS   ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_PEAK_THROUGHPUT     ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_MEAN_THROUGHPUT     ,
    EM_MNU_PDP_CONFIG_QOS_REQUESTED_SEND_AT_CMD         ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM                       ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_PRECEDENCE_CLASS      ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_DELAY_CLASS           ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_RELIABILITY_CLASS     ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_PEAK_THROUGHPUT       ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_MEAN_THROUGHPUT       ,
    EM_MNU_PDP_CONFIG_QOS_MINIMUM_SEND_AT_CMD           ,
    EM_MNU_PDP_CONFIG_RESET                             ,
    EM_MNU_PDP_ACTIVATION                               ,
    EM_MNU_PDP_DEACTIVATION                             ,
    EM_MNU_SEND_CONFIG_DATA_LENGTH                      ,
    EM_MNU_SEND_CONFIG_NUMBER_OF_REPEAT                 ,
    EM_MNU_SEND_CONFIG_RESET                            ,
    EM_MNU_SEND_DATA                                    ,
    EM_MNU_PLMN_FAILURE                                 ,
    // } EM_GSM_GPRS_MENU_ID_e;
    //
    // enum {
    EM_MNU_CELL_ENVIRONMENT                             ,
    EM_MNU_CHANGE_BAND_MENU                             ,
    EM_MNU_BAND_850                                     ,
    EM_MNU_BAND_900                                     ,
    EM_MNU_BAND_1800                                    ,
    EM_MNU_BAND_1900                                    ,
    EM_MNU_BAND_850_1900                                ,
    EM_MNU_BAND_900_1800                                ,
    EM_MNU_BAND_900_1900                                ,
    EM_MNU_QUAD_BAND_AUTO                               ,
    EM_MNU_DEDICATED_MODE                               ,
    EM_MNU_CELL_LOCK                                    ,
    EM_MNU_PREFERRED_CODEC                              ,
    EM_MNU_SPEECH_CODING								,
    EM_MNU_EMMI_RSSI_SMOOTH_ALGORITHM                   ,
	EM_MNU_EMMI_RSSI_SMOOTH_ALGORITHM_ENABLE            ,
    EM_MNU_EMMI_RSSI_SMOOTH_ALGORITHM_DISABLE           ,
    // } EM_NETWORK_INFO_MENU_ID_e;
    //
    // enum {
    EM_MNU_FTP_CLIENT                                   ,
    EM_MNU_PACKAGE_TRANSFER_CONFIGURATION               ,
    EM_MNU_TCP_IP_CONFIGURATION                         ,
    // } EM_DATA_INFO_MENU_ID_e;
    //
    // enum {
    EM_MNU_LAYER_1_INFO                                 ,
    // } EM_LAYER1_INFO_MENU_ID_e;
    //
    // enum {
    EM_MNU_AUDIO_TEST                                   ,
    EM_MNU_BACKLIGHT_TEST                               ,
    EM_MNU_KEYPAD_TEST                                  ,
    EM_MNU_KEYPAD_LIGHT_TEST                            ,
    EM_MNU_LCD_TEST                                     ,
#if defined(__ENABLE_CAMERA__) || defined(__ENABLE_CAMCORDER__)
    EM_MNU_DSC_TEST                                     ,
#endif
#if defined(__ENABLE_CAMCORDER__)
    EM_MNU_VIDEO_TEST                                   ,
#endif
#if defined(__DUAL_CAMERA_MMI__)  && (defined(__ENABLE_CAMERA__) || defined(__ENABLE_CAMCORDER__))
    EM_MNU_DSC_TEST1                                ,
#endif
    EM_MNU_RTC_TEST                                     ,
    EM_MNU_MP3_TEST                                     ,
    EM_MNU_VIBRATION_TEST                               ,
    EM_MNU_SD_TEST_MENU                                  ,
    EM_MNU_SD_TEST                                      ,
#ifdef __DUAL_CARD__
    EM_MNU_SD2_TEST                                     ,
#endif
    EM_MNU_SD_WRITE_1KB_TEST                            ,
    EM_MNU_SD_WRITE_1MB_TEST                            ,
    EM_MNU_SD_READ_1KB_TEST                             ,
    EM_MNU_SD_READ_1MB_TEST                             ,
    EM_MNU_SD_WRITE_RANDOM_TEST                         ,
    EM_MNU_SD_READ_RANDOM_TEST                          ,
#ifdef __DUAL_CARD__
    EM_MNU_SD_READ_SD1_TO_SD2_TEST                      ,
#endif
    EM_MNU_SD_CONFIG_MENU                               ,
    EM_MNU_SD_CONFIG_INFO                               ,
    EM_MNU_SD_CONFIG_LOG_SWITCH                         ,
    EM_MNU_SD_CONFIG_LOG_SWITCH_TMT                     ,
    EM_MNU_SD_CONFIG_LOG_SWITCH_UART                    ,
    EM_MNU_SD_CONFIG_DRIVING_STRENGH                    ,
    EM_MNU_SD_CONFIG_DRIVING_STRENGH__8MA               ,
    EM_MNU_SD_CONFIG_DRIVING_STRENGH_16MA               ,
    EM_MNU_SD_CONFIG_PRFOMNS_CALC                       ,
    EM_MNU_SD_CONFIG_PRFOMNS_CALC_DISABLE               ,
    EM_MNU_SD_CONFIG_PRFOMNS_CALC_ENABLE                ,
    EM_MNU_SD_CONFIG_CLOCK_LIMIT                        ,
    EM_MNU_SD_CONFIG_CLOCK_LIMIT_NONE                   ,
    EM_MNU_SD_CONFIG_CLOCK_LIMIT_25M                    ,
    EM_MNU_SD_CONFIG_CLOCK_LIMIT_15M                    ,
    EM_MNU_SD_CONFIG_CLOCK_LIMIT__5M                    ,
    EM_MNU_SD_CONFIG_BURST_MODE_SW                      ,
    EM_MNU_SD_CONFIG_BURST_MODE_SW_DISABLE              ,
    EM_MNU_SD_CONFIG_BURST_MODE_SW_ENABLE               ,

    EM_MNU_SD_PERFORMANCE_MENU                          ,
    EM_MNU_SD1_SEQUENCE_W                               ,
    EM_MNU_SD1_SEQUENCE_R                               ,
    EM_MNU_SD1_RANDOM_W                                 ,
    EM_MNU_SD1_RANDOM_R                                 ,
    EM_MNU_SD2_SEQUENCE_W                               ,
    EM_MNU_SD2_SEQUENCE_R                               ,
    EM_MNU_SD2_RANDOM_W                                 ,
    EM_MNU_SD2_RANDOM_R                                 ,

    EM_MNU_REGISTER_WRITE                               ,
    EM_MNU_REGISTER_READ                                ,
    EM_MNU_BATTERY_CHARGE                               ,
    EM_MNU_AUX_ADC                                      ,
    EM_MNU_HEADSET                                      ,
    EM_MNU_USB_TEST                                     ,
    EM_MNU_IO_STATUS                                    ,
    EM_MNU_HANDWRITING_SPEED                            ,
    EM_MNU_FMRMENU										,
    EM_MNU_FMRAIDO										,
    EM_MNU_FMR_RF_TEST									,
    EM_MNU_FMR_AUTO_LIST								,
    EM_MNU_FMR_AUTO_LIST_EX                             ,
    EM_MNU_FMR_RF_PERFORMANCE                           ,
    EM_MNU_FMR_SET_AREA									,
    EM_MNU_FMR_AREA_CHINA								,
    EM_MNU_FMR_AREA_TAIWAN								,
    EM_MNU_FMR_SET_DEEMPHASIS                                          ,
    EM_MNU_FMR_DEEMPHASIS_50US                                        ,
    EM_MNU_FMR_DEEMPHASIS_75US                                        ,
    EM_MNU_FMR_SET_STEPSPACE                                             ,
    EM_MNU_FMR_STEP_50KHZ                                                  ,
    EM_MNU_FMR_STEP_100KHZ                                                ,
    EM_MNU_FMR_STEP_200KHZ                                                ,
    EM_MNU_FMR_STEP_30KHZ                                                  ,
    EM_MNU_FMR_STEP_300KHZ                                                ,
    EM_MNU_FMR_SET_BPFIR                                                     ,
    EM_MNU_FMR_BPFIR_100KHZ                                               ,
    EM_MNU_FMR_BPFIR_120KHZ                                               ,
    EM_MNU_FMR_BPFIR_150KHZ                                               ,
    EM_MNU_FMR_BPFIR_200KHZ                                               ,
    EM_MNU_FMR_SET_BEGINRANGE                                           ,
    EM_MNU_FMR_FROM_66MHZ                                                ,
    EM_MNU_FMR_FROM_68MHZ                                                ,
    EM_MNU_FMR_FROM_73MHZ                                                ,
    EM_MNU_FMR_FROM_76MHZ                                                ,
    EM_MNU_FMR_FROM_87_5MHZ                                            ,
    EM_MNU_FMR_FROM_87_8MHZ                                            ,
    EM_MNU_FMR_FROM_88MHZ                                                ,
    EM_MNU_FMR_FROM_100MHZ                                              ,
    EM_MNU_FMR_SET_ENDRANGE                                              ,
    EM_MNU_FMR_TO_68MHZ                                                   ,
    EM_MNU_FMR_TO_73MHZ                                                   ,
    EM_MNU_FMR_TO_74MHZ                                                   ,
    EM_MNU_FMR_TO_87_5MHZ                                                ,
    EM_MNU_FMR_TO_90MHZ                                                   ,
    EM_MNU_FMR_TO_100MHZ                                                 ,
    EM_MNU_FMR_TO_108MHZ                                                 ,
    EM_MNU_FMR_SET_CARRIERON							 ,
    EM_MNU_FMR_SET_CARRIEROFF							 ,
    EM_MNU_FMR_AREA_VALUES      							 ,
    EM_MNU_CLIBRATE                                     ,
    EM_MNU_MULTITOUCH_TEST                              ,
#if defined(__EM_TOUCHSCREEN_TEST_ENHANCE__)
    EM_MNU_TOUCH_PANEL_MENU,
    EM_MNU_TOUCH_PANEL_DRAW_GRID_TEST,
#if defined(__HANDWRITING_MMI__)
    EM_MNU_TOUCH_PANEL_DRAW_POINTS_TEST,
    EM_MNU_TOUCH_PANEL_DRAW_CROSSLINE_TEST,
    EM_MNU_TOUCH_PANEL_DRAW_VLINE_TEST,
    EM_MNU_TOUCH_PANEL_DRAW_HLINE_TEST,
#endif
#endif //defined(__EM_TOUCHSCREEN_TEST_ENHANCE__)
#if defined(__TOUCH_SCREEN_MMI__)
#if defined(__HANDWRITING_MMI__)
    EM_MNU_TOUCH_PANEL_TEST                             ,
#else
	EM_MNU_TOUCH_PANEL_TEST_USE_CLIBRATE                ,
#endif
#endif
#ifdef __BLUETOOTH_MMI__
    EM_MNU_BT                                           ,
#ifdef __BLUETOOTH_NEW_CONTINUOUS_TX_FEATURE__
    EM_MNU_BT_SET_DATA_MODE                             ,
    EM_MNU_BT_SET_PAYLOAD_DATA                          ,
#endif
    EM_MNU_BT_HOST_VERSION                              ,
    EM_MNU_BT_PROD_TEST                                 ,
    EM_MNU_BT_ADDR                                      ,
    EM_MNU_BT_POW_LEVEL                                 ,
    EM_MNU_BT_RSSI                                      ,
    EM_MNU_BT_CONTI_RX                                  ,
    EM_MNU_BT_CONTI_TX                                  ,
    EM_MNU_BT_GSM_ENABLE,
	EM_MNU_BT_GSM_DISABLE,
    EM_MNU_BT_AUTO_TEST                                 ,
    EM_MNU_BT_AUTO_TEST_WITH_GSM                        ,
#endif//__BLUETOOTH_MMI__
#ifdef __G_SENSOR_MMI__
    EM_MNU_GENSOR                                       ,
#endif
#ifdef __ATV_MMI__
    EM_MNU_ATV                                          ,
    EM_MNU_ISDBT                                        ,
    EM_MNU_CMMB                                         ,
    EM_MNU_ATV_TEST_CHANNEL_1                           ,
    EM_MNU_ATV_TEST_CHANNEL_2                           ,
    EM_MNU_ATV_TEST_CHANNEL_3                           ,
    EM_MNU_ATV_SWITCH_REGION                            ,
#endif  //__ATV_MMI__
    EM_MNU_LCM                                          ,
    EM_MNU_MCP                                          ,
    EM_MNU_MCP_ONOFF                                    ,
    EM_MNU_MCP_ON                                       ,
    EM_MNU_MCP_OFF                                      ,
    EM_MNU_MCP_RESULT                                   ,
    EM_MNU_MCP_BENCHMARK                                   ,
    EM_MNU_MCP_BENCH_MEMCPY                 ,
    EM_MNU_MCP_BENCH_NOR                        ,
    EM_MNU_MCP_BENCH_NOR_BIT                 ,
    EM_MNU_MCP_BENCH_NOR_READ                 ,
    EM_MNU_MCP_BENCH_NOR_WRITE                ,
    EM_MNU_MCP_BENCH_NOR_BIT_1               ,
    EM_MNU_MCP_BENCH_NOR_BIT_2               ,
    EM_MNU_MCP_BENCH_NOR_BIT_4               ,
    EM_MNU_MCP_BENCH_RIU                        ,
    EM_MNU_MCP_BENCH_MMP                        ,
    EM_MNU_MCP_SPI_NOR_DRIVING                 			,
	EM_MNU_MCP_SPI_NOR_DRIVING_00						,
	EM_MNU_MCP_SPI_NOR_DRIVING_01						,
	EM_MNU_MCP_SPI_NOR_DRIVING_10						,
	EM_MNU_MCP_SPI_NOR_DRIVING_11						,
	EM_MNU_MCP_SPI_NOR_CLOCK                 			,
	EM_MNU_MCP_SPI_NOR_CLOCK_26						    ,
	EM_MNU_MCP_SPI_NOR_CLOCK_77						    ,
	EM_MNU_MCP_SPI_NOR_CLOCK_96						,
    EM_MNU_MCP_STRESS            			,
#ifdef __WLAN_MMI__
    EM_MNU_WIFI                                         ,
    EM_MNU_WIFI_OFF                                     ,
    EM_MNU_WIFI_ON                                      ,
    EM_MNU_WIFI_RESET                                   ,
    EM_MNU_WIFI_GSM_OFF_WIFI_ON                         ,
    EM_MNU_WIFI_GSM_ON_WIFI_ON                          ,
    EM_MNU_WIFI_AQUARIUD_SW_VERSION                     ,
    EM_MNU_WIFI_CONTINUOUS_TX                           ,
    EM_MNU_WIFI_DEST_MAC                                ,
    EM_MNU_WIFI_RATE                                    ,
    EM_MNU_WIFI_RATE_PARAM0                             ,
    EM_MNU_WIFI_RATE_PARAM1                             ,
    EM_MNU_WIFI_RATE_PARAM2                             ,
    EM_MNU_WIFI_RATE_PARAM3                             ,
    EM_MNU_WIFI_RATE_PARAM5                             ,
    EM_MNU_WIFI_RATE_PARAM6                             ,
    EM_MNU_WIFI_RATE_PARAM7                             ,
    EM_MNU_WIFI_RATE_PARAM8                             ,
    EM_MNU_WIFI_RATE_PARAM9                             ,
    EM_MNU_WIFI_RATE_PARAM10                            ,
    EM_MNU_WIFI_RATE_PARAM11                            ,
    EM_MNU_WIFI_RATE_PARAM12                            ,
    EM_MNU_WIFI_RATE_PARAM13                            ,
    EM_MNU_WIFI_RATE_PARAM14                            ,
    EM_MNU_WIFI_RATE_PARAM15                            ,
    EM_MNU_WIFI_CHANNEL                                 ,
    EM_MNU_WIFI_PACKET_LENGTH                           ,
    EM_MNU_WIFI_PACKET_NUMBER                           ,
    EM_MNU_WIFI_PGA                                     ,
    EM_MNU_WIFI_SEND_TX                                 ,
    EM_MNU_WIFI_STOP_TX                                 ,
    EM_MNU_WIFI_CONTINUOUS_RX                           ,
    EM_MNU_WIFI_RX_RATE                                 ,
    EM_MNU_WIFI_RX_LEN                                  ,
    EM_MNU_WIFI_RX_CHAN                                 ,
    EM_MNU_WIFI_RX_FILTER_MAC                           ,
    EM_MNU_WIFI_SET_RX                                  ,
    EM_MNU_WIFI_GET_RX                                  ,
    EM_MNU_WIFI_REG_WRITE_READ                          ,
    EM_MNU_WIFI_RF_REG_WRITE_READ                       ,
    EM_MNU_WIFI_RF_REG_WRITE_READ_REG                   ,
    EM_MNU_WIFI_RF_REG_WRITE_READ_VALUE                 ,
    EM_MNU_WIFI_RF_REG_WRITE_COMMAND                    ,
    EM_MNU_WIFI_RF_REG_READ_COMMAND                     ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ                     ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_ADDR                ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_VALUE               ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_LEN                 ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_LEN_1BYTE           ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_LEN_2BYTES          ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_READ_LEN_4BYTES          ,
    EM_MNU_WIFI_AQUA_MEM_WRITE_COMMAND                  ,
    EM_MNU_WIFI_AQUA_MEM_READ_COMMAND                   ,
    EM_MNU_WIFI_GET_IP                                  ,
    EM_MNU_WIFI_SET_TX_SINETONE                         ,
    EM_MNU_WIFI_SET_TX_SINETONE_SEND                    ,
    EM_MNU_WIFI_SET_TX_SINETONE_STOP                    ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM1                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM2                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM3                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM4                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM5                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM6                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM7                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM8                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM9                  ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM10                 ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM11                 ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM12                 ,
    EM_MNU_WIFI_SET_TX_SINETONE_PARAM13                 ,
    EM_MNU_WIFI_REG_BANK                                ,
    EM_MNU_WIFI_REG_OFFSET                              ,
    EM_MNU_WIFI_REG_WRITE_VALUE                         ,
    EM_MNU_WIFI_WRITE_REG_COMMAND                       ,
    EM_MNU_WIFI_READ_REG_COMMAND                        ,
    EM_MNU_WIFI_SCAN_DEVICE_TEST                        ,
    EM_MNU_WIFI_THROUGHPUT_TEST                         ,
    EM_MNU_WIFI_TX_THROUGHPUT_TEST                      ,
    EM_MNU_WIFI_RX_THROUGHPUT_TEST                      ,
    EM_MNU_WIFI_THROUGHPUT_SET_IP                       ,
    EM_MNU_WIFI_PRODUCTION_TEST                         ,
    EM_MNU_WIFI_PRODUCTION_TX                           ,
    EM_MNU_WIFI_PRODUCTION_RX                           ,
    EM_MNU_WIFI_PRODUCTION_PARAM1                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM2                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM3                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM4                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM5                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM6                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM7                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM8                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM9                       ,
    EM_MNU_WIFI_PRODUCTION_PARAM10                      ,
    EM_MNU_WIFI_PRODUCTION_PARAM11                      ,
#endif
    EM_MNU_BACKLIGHT_OFF                                ,
    EM_MNU_KEYPAD_LIGHT_OFF                             ,
#ifdef __FLASHLIGHT_MMI__
    EM_MNU_FLASHLIGHT_OFF								,
#endif
#ifdef __FILLLIGHT_MMI__
	EM_MNU_FILLLIGHT_OFF								,
#endif
#ifdef __TTS__
    EM_MNU_TTS_OFF                                      ,
#endif
    EM_MNU_HOT_KEY_EXCEPTION                            ,
    EM_MNU_TRACK_PATCH_MECHANISM                        ,
    EM_MNU_SET_EGSM_BAND_ONLY                           ,
    EM_MNU_SET_PGSM_BAND_ONLY                           ,
    EM_MNU_SET_DSC_BAND_ONLY                            ,
    EM_MNU_SET_EGSM_DSC                                 ,
    EM_MNU_SET_PGSM_DSC                                 ,
#ifdef __3G_RIL_MMI__
    EM_MNU_SET_2G_BAND           ,
    EM_MNU_SET_3G_BAND           ,
    EM_MNU_SET_AUTO_BAND       ,
#endif // __3G_RIL_MMI__

    EM_MNU_SPEAKER_VOLUMN                               ,
    EM_MNU_MICROPHONE_VOLUMN                            ,
    EM_MNU_SIDETONE_VOLUMN                              ,
    EM_MNU_SET_CURRENT_PARAMETER                        ,
    EM_MNU_DEACTIVE_PARAMETER_SET                       ,
    EM_MNU_ACTIVE_PARAMETER_SET_0                       ,
    EM_MNU_ACTIVE_PARAMETER_SET_1                       ,
    EM_MNU_ACTIVE_PARAMETER_SET_2                       ,
    EM_MNU_EMMI_DEBUG                                   ,
    EM_MNU_EMMI_SMS                                     ,
    EM_MNU_EMMI_SMS_CRASH_LOG_ENABLE                    ,
    EM_MNU_EMMI_SMS_CRASH_LOG_DISABLE                   ,
    EM_MNU_EMMI_SMS_CRASH_LOG_NUMBER                    ,
    EM_MNU_EMMI_SMS_RESEND_ENABLE                       ,
    EM_MNU_EMMI_SMS_RESEND_DISABLE                      ,
    EM_MNU_EMMI_USB_MENU_ENABLE                         ,
    EM_MNU_EMMI_USB_MENU_DISABLE                        ,
    EM_MNU_EMMI_DISPLAY_MEMORY_INFO_ON                  ,
    EM_MNU_EMMI_DISPLAY_MEMORY_INFO_OFF                 ,
    EM_MNU_EMMI_DISPLAY_UPDATE_INDICATION_ON            ,
    EM_MNU_EMMI_DISPLAY_UPDATE_INDICATION_OFF           ,
    EM_MNU_EMMI_DISPLAY_UPDATE_TIME_ON                  ,
    EM_MNU_EMMI_DISPLAY_UPDATE_TIME_OFF                 ,
    EM_MNU_EMMI_DUMP_RAI_TO_SD                          ,
    EM_MNU_EMMI_MEM_INFO                                ,
    EM_MNU_EMMI_POWER_ONOFF_CAUSE                       ,
    EM_MNU_EMMI_DUMP_STACK_PROFILE_TO_SD                ,
    EM_MNU_EMMI_QUERY_STATION_STATUS_INFO               ,
    EM_MNU_EMMI_TEXT_FONT_CHECK                         ,
    EM_MNU_NEW_AUTO_TEST_MENU                           ,
    EM_MNU_NEW_AUTO_TEST_MENU_ON                        ,
    EM_MNU_NEW_AUTO_TEST_MENU_OFF                       ,
    EM_MNU_HIDDEN_PARTITION_MENU                        ,
    EM_MNU_HIDDEN_PARTITION_MENU_ON                     ,
    EM_MNU_HIDDEN_PARTITION_MENU_OFF                    ,
    EM_MNU_SET_UART_SHARE_WITH_DBBUS                    ,
#ifdef __EM_AUDIO__
    EM_MNU_AUDIO										,
    EM_MNU_AUDIO_SPEECH									,
    EM_MNU_AUDIO_SPEECH_HANDSET							,
    EM_MNU_AUDIO_SPEECH_HEADSET							,
    EM_MNU_AUDIO_SPEECH_HANDSFREE						,
    EM_MNU_AUDIO_SPEECH_BT								,
    EM_MNU_AUDIO_SPEECH_GAIN							,
    EM_MNU_AUDIO_SPEECH_BT_GAIN							,
    EM_MNU_AUDIO_SPEECH_ME_GAIN							,
    EM_MNU_AUDIO_SPEECH_HS_GAIN							,
    EM_MNU_AUDIO_SPEECH_HF_GAIN							,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN					,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_MAIN		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN			,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_7dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_10dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_13dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_16dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_17dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_19dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_20dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_22dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_25dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_23dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_26dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_28dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_29dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_32dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_35dB		,
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_MIC_GAIN_38dB		,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_UL_GAIN_DPGA_GAIN			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN					,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_1			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_2			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_3			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_4			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_5			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_6			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_7			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_GAIN_LEVEL_8			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN				,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_1X			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_2X			,
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_ME			,	// 8533x (handset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_ME_N_3DB	,	// 8533x (handset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_ME_0DB		,	// 8533x (handset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_ME_3DB		,	// 8533x (handset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_ME_6DB		,	// 8533x (handset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HS			,	// 8533x (headset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HS_N_4_4DB	,	// 8533x (headset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HS_N_1_9DB	,	// 8533x (headset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HS_1_6DB	,	// 8533x (headset)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF			,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_N_4_4DB	,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_1_6DB	,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_3DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_6DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_9DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_10DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_ANALOG_GAIN_HF_12DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CLASS_D_GAIN			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CLASS_D_GAIN_HF_6DB		,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CLASS_D_GAIN_HF_12DB	,	// 8533x (hands free)
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN				,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_0DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_6DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_12DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_18DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_24DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_30DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_DL_CNG_GAIN_N_36DB			,	// 8533x
    EM_MNU_AUDIO_SPEECH_GAIN_SIDE_TONE_GAIN				,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR						,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_E2P				,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_SET_1			,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_SET_2			,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_SET_3			,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_SET_4			,
    EM_MNU_AUDIO_SPEECH_LOAD_DL_FIR_FIR_SET_5			,
    EM_MNU_AUDIO_SPEECH_AEC								,
    EM_MNU_AUDIO_SPEECH_AEC_NLP							,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_STATUS					,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_STATUS_ON				,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_STATUS_OFF				,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_MIN_GAIN				,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_SMOOTHNESS				,
    EM_MNU_AUDIO_SPEECH_AEC_NLP_CNG						,
    EM_MNU_AUDIO_SPEECH_AEC_NS							,
    EM_MNU_AUDIO_SPEECH_AEC_NS_STATUS					,
    EM_MNU_AUDIO_SPEECH_AEC_NS_STATUS_ON				,
    EM_MNU_AUDIO_SPEECH_AEC_NS_STATUS_OFF				,
    EM_MNU_AUDIO_SPEECH_AEC_NS_MAX_SUPPRESSION			,
    EM_MNU_AUDIO_SPEECH_AEC_RS							,
    EM_MNU_AUDIO_SPEECH_AEC_RS_STATUS					,
    EM_MNU_AUDIO_SPEECH_AEC_RS_STATUS_ON				,
    EM_MNU_AUDIO_SPEECH_AEC_RS_STATUS_OFF				,
    EM_MNU_AUDIO_SPEECH_AEC_RS_MAX_MAGNITUDE			,
    EM_MNU_AUDIO_SPEECH_AEC_START_IN_HALF_DUPLEX_STATUS	,
    EM_MNU_AUDIO_SPEECH_AEC_START_IN_HALF_DUPLEX_STATUS_ON	,
    EM_MNU_AUDIO_SPEECH_AEC_START_IN_HALF_DUPLEX_STATUS_OFF	,
    EM_MNU_AUDIO_SPEECH_AEC_HALF_DUPLEX_STATUS			,
    EM_MNU_AUDIO_SPEECH_AEC_HALF_DUPLEX_STATUS_ON		,
    EM_MNU_AUDIO_SPEECH_AEC_HALF_DUPLEX_STATUS_OFF		,
    EM_MNU_AUDIO_SPEECH_AGC								,
    EM_MNU_AUDIO_SPEECH_AGC_STATUS						,
    EM_MNU_AUDIO_SPEECH_AGC_STATUS_ON					,
    EM_MNU_AUDIO_SPEECH_AGC_STATUS_OFF					,
    EM_MNU_AUDIO_SPEECH_AGC_TARGET_LEVEL				,
    EM_MNU_AUDIO_SPEECH_AGC_CLIPPING_LEVEL				,
    EM_MNU_AUDIO_SPEECH_AGC_MAX_GAIN					,
    EM_MNU_AUDIO_SPEECH_AGC_MIN_GAIN					,
    EM_MNU_AUDIO_SPEECH_AGC_ATTACK_RATE					,
    EM_MNU_AUDIO_SPEECH_AGC_RELEASE_RATE				,
    EM_MNU_AUDIO_MULTIMEDIA								,
    EM_MNU_AUDIO_MULTIMEDIA_HANDSET						,
    EM_MNU_AUDIO_MULTIMEDIA_HANDSET_KEYPAD_TONE			,
    EM_MNU_AUDIO_MULTIMEDIA_HEADSET						,
    EM_MNU_AUDIO_MULTIMEDIA_HANDSFREE					,
    EM_MNU_AUDIO_MULTIMEDIA_BT							,
    EM_MNU_AUDIO_MULTIMEDIA_KEYPAD_TONE					,
    EM_MNU_AUDIO_MULTIMEDIA_MUSIC						,
    EM_MNU_AUDIO_MULTIMEDIA_VIDEO						,
    EM_MNU_AUDIO_MULTIMEDIA_IPTV						,
    EM_MNU_AUDIO_MULTIMEDIA_FM							,
    EM_MNU_AUDIO_MULTIMEDIA_DTMF						,
    EM_MNU_AUDIO_MULTIMEDIA_ATV							,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_1			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_2			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_3			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_4			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_5			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_6			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_7			,
    EM_MNU_AUDIO_MULTIMEDIA_STEREO_GAIN_LEVEL_8			,
#ifdef __APP_MMI_EM_AUDIO_APPTOSD__
    EM_MNU_AUDIO_APPTOSD								,
    EM_MNU_AUDIO_APPTOSD_SAVE_APP_TO_SD					,
    EM_MNU_AUDIO_APPTOSD_LOAD_APP_FROM_SD				,
#endif
    EM_MNU_AUDIO_OTHERS									,
    EM_MNU_AUDIO_OTHERS_REC_MIC_GAIN					,
    EM_MNU_AUDIO_OTHERS_REC_MIC_GAIN_VOICE_MEMO			,
    EM_MNU_AUDIO_OTHERS_REC_MIC_GAIN_CAMCORDER			,
    EM_MNU_AUDIO_OTHERS_REC_MIC_GAIN_PCM_RECORDING		,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR					,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY		,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_250_HZ	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_500_HZ	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_1000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_1500_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_2000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_3000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_4000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_6000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_8000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_12000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_FREQUENCY_16000_HZ,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN				,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_0_DB		,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_6_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_12_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_18_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_24_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_30_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_36_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_42_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_48_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_54_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_60_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_66_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_72_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_78_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_84_DB	,
    EM_MNU_AUDIO_OTHERS_TONE_GENERATOR_GAIN_MINUS_90_DB	,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL					,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_OUTPUT_DRIVER_STATUS,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_OUTPUT_DRIVER_STATUS_ON,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_OUTPUT_DRIVER_STATUS_OFF,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_MIC_STATUS			,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_MIC_STATUS_MUTE	,
    EM_MNU_AUDIO_OTHERS_PATH_CONTROL_MIC_STATUS_UNMUTE	,
    EM_MNU_AUDIO_OTHERS_CTA_MODE_STATUS					,
    EM_MNU_AUDIO_OTHERS_CTA_MODE_STATUS_ON				,
    EM_MNU_AUDIO_OTHERS_CTA_MODE_STATUS_OFF				,
    EM_MNU_AUDIO_OTHERS_AMP_OFFSET_GAIN	                ,
    EM_MNU_AUDIO_SET_DL_FIXED_FIR_STATUS                ,
    EM_MNU_AUDIO_SET_DL_FIXED_FIR_STATUS_ON             ,
    EM_MNU_AUDIO_SET_DL_FIXED_FIR_STATUS_OFF            ,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_MENU					,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_ENABLE				,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_DISABLE				,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_SET_TONE_500HZ,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_SET_TONE_1KHZ,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_SET_TONE_2KHZ,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_SET_MLS,
    EM_MNU_AUDIO_OTHERS_TEST_SEQUENCE_SET_PINK_NOISE,
#else
    EM_MNU_VOICE                                        ,
    EM_MNU_INPUT_GAIN                                   ,
    EM_MNU_OUTPUT_GAIN                                  ,
    EM_MNU_HANDSET_HEADSET                              ,
    EM_MNU_SPEAKER_PHONE                                ,
    EM_MNU_RECEIVER_TEST                                ,
    EM_MNU_AEC_FIXED_DELAY                              ,
    EM_MNU_AEC_NS_MIN_WEIGHT                            ,
    EM_MNU_AEC_MAX_CNG_MAG                              ,
    EM_MNU_AEC_NLP_MIN_GAIN                             ,
    EM_MNU_AEC_NLP_SHIFT                                ,
    EM_MNU_AEC_DT_THR                                   ,
    EM_MNU_AEC_DT_SENS_THR                              ,
    EM_MNU_AEC_FREQ_DT_THR                              ,
    EM_MNU_AEC_LPF_CUT_OFF                              ,
    EM_MNU_AEC_ENHANCED_NS_ENABLE                       ,
#endif
    EM_MNU_PRODUCTION_TEST                              ,
    EM_MNU_AUTO_TEST                                    ,
//#ifdef __PC_SIMULATOR__ // ViewTester
//    EM_MNU_EMMI_VIEW_TESTER                             ,
//#endif // __PC_SIMULATOR__
    EM_MNU_UNIT_TEST                                    ,
#ifdef __WAP_MMI__
    EM_MNU_WAP                                          ,
#endif /* __WAP_MMI__ */
#if defined(__MMS_MMI_CDMMS__) && defined(__WAP_MMI__)
    EM_MNU_EMMI_SEND_MMS_SETTINGS                       ,
#endif //  defined(__MMS_MMI_CDMMS__) && defined(__WAP_MMI__)
#ifdef __JAVA_MMI__
    EM_MNU_JAVA                                         ,
#endif /* __JAVA_MMI__ */

#ifdef __SDK_MMI_VENDOR_ENTRY__
#ifdef __SDK_MMI_TEST__
    EM_MNU_SDK_V2_TEST                                  ,
#else
    EM_MNU_SDK_ENTRY                                    ,
#endif /* __SDK_MMI_TEST__ */
#endif /* __SDK_MMI_VENDOR_ENTRY__ */

#ifdef __VT_3G324M__ //VT engineer test mode
    EM_MNU_VT                                           ,
    EM_MNU_VT_MEDIA_LOOPBACK_TEST_ON                    ,
    EM_MNU_VT_STACK_LOOPBACK_TEST_ON                    ,
    EM_MNU_VT_LOOPBACK_TEST_OFF                         ,
    EM_MNU_Enable_VT_uplink_dump             ,
    EM_MNU_Disable_VT_uplink_dump            ,
    EM_MNU_Enable_VT_downlink_dump         ,
    EM_MNU_Disable_VT_downlink_dump        ,
    EM_MNU_Enable_VT_Internal_Test_All         ,
    EM_MNU_Enable_VT_Internal_Test_Screen         ,
    EM_MNU_Enable_VT_Internal_Test_Reserved         ,
    EM_MNU_Disable_VT_Internal_Test         ,
    EM_MNU_Enable_VT_File_Logging         ,
    EM_MNU_Disable_VT_File_Logging         ,
    EM_MNU_Display_Heap_Memory         ,
    EM_MNU_Reduce_Heap_Memory         ,
    EM_MNU_Switch_Screen_Size         ,
#endif

#ifdef __FEATURE_POWER_CONSUMPTION_LOG__
    EM_MNU_POWER_CONSUMPTION                            ,
    EM_MNU_POWER_CONSUMPTION_LOG_STATUS                 ,
    EM_MNU_POWER_CONSUMPTION_LOG_ENABLE                 ,
    EM_MNU_POWER_CONSUMPTION_LOG_DISABLE                ,
#endif//__FEATURE_POWER_CONSUMPTION_LOG__

#if defined(__MGL_DEMO__)
    EM_MNU_MGL_3D_DEMO_ENTRY                            ,
    EM_MNU_MGL_3D_DEMO_1                                ,
    EM_MNU_MGL_3D_DEMO_2                                ,
    EM_MNU_MGL_3D_DEMO_3                                ,
    EM_MNU_MGL_3D_DEMO_4                                ,
    EM_MNU_MGL_3D_DEMO_5                                ,
    EM_MNU_MGL_3D_DEMO_6                                ,
    EM_MNU_MGL_3D_DEMO_7                                ,
    EM_MNU_MGL_3D_DEMO_8                                ,
#endif

#if defined(__G3D_MMI__) && defined(__MGL_DEMO__)
    EM_MNU_OGL_DEMO_ENTRY                               ,
    EM_MNU_OGL_DEMO_02                                  ,
    EM_MNU_OGL_DEMO_03                                  ,
    EM_MNU_OGL_DEMO_04                                  ,
    EM_MNU_OGL_DEMO_05                                  ,
    EM_MNU_OGL_DEMO_06                                  ,
    EM_MNU_OGL_DEMO_07                                  ,
    EM_MNU_OGL_DEMO_08                                  ,
    EM_MNU_OGL_DEMO_09                                  ,
    EM_MNU_OGL_DEMO_10                                  ,
    EM_MNU_OGL_DEMO_11                                  ,
    EM_MNU_OGL_DEMO_12                                  ,
    EM_MNU_OGL_DEMO_16                                  ,
    EM_MNU_OGL_DEMO_17                                  ,
    EM_MNU_OGL_DEMO_18                                  ,
    EM_MNU_OGL_DEMO_19                                  ,
    EM_MNU_OGL_DEMO_20                                  ,
    EM_MNU_OGL_DEMO_25                                  ,
    EM_MNU_OGL_DEMO_28                                  ,
    EM_MNU_OGL_DEMO_29                                  ,
    EM_MNU_OGL_DEMO_30                                  ,
    EM_MNU_OGL_DEMO_31                                  ,
    EM_MNU_OGL_DEMO_33                                  ,
    EM_MNU_OGL_DEMO_34                                  ,
    EM_MNU_OGL_DEMO_36                                  ,
    EM_MNU_OGL_DEMO_40                                  ,
    EM_MNU_OGL_DEMO_42                                  ,
    EM_MNU_OGL_DEMO_45                                  ,
    EM_MNU_OGL_DEMO_48                                  ,

#if defined (__APP_MMI_WDG3DEMO__)
    EM_MNU_WDG_3D_DEMO_ENTRY                            ,
    EM_MNU_WDG_3D_DEMO_1                                ,
    EM_MNU_WDG_3D_DEMO_2                                ,
    EM_MNU_WDG_3D_DEMO_3                                ,
    EM_MNU_WDG_3D_DEMO_4                                ,
    EM_MNU_WDG_3D_DEMO_5                                ,
    EM_MNU_WDG_3D_DEMO_6                                ,
    EM_MNU_WDG_3D_DEMO_7                                ,
    EM_MNU_WDG_3D_DEMO_8                                ,
    EM_MNU_WDG_3D_DEMO_9                                ,
    EM_MNU_WDG_3D_DEMO_10                                ,
    EM_MNU_WDG_3D_DEMO_11                                ,
#endif

#endif // defined(__G3D_MMI__) && defined(__MGL_DEMO__)

    EM_MNU_EMMI_STK_GCF_ENABLE                          ,
    EM_MNU_EMMI_STK_GCF_DISABLE                         ,

    EM_MNU_ANTF_TRACE_MENU								,
    EM_MNU_ANTF_TRACE_ENABLE							,
    EM_MNU_ANTF_TRACE_DISABLE							,
    EM_MNU_ANTF_TRACE_SET_FILTER_VIA_SMS				,
    EM_MNU_ANTF_TRACE_SET_FILTER_VIA_SD					,
    EM_MNU_ANTF_TRACE_SET_AUDIO_1_FILTER					,
    EM_MNU_ANTF_TRACE_SET_AUDIO_2_FILTER					,
    EM_MNU_ANTF_TRACE_SET_AUDIO_3_FILTER					,
    EM_MNU_ANTF_TRACE_SET_DEFAULT_FILTER				,
#if 0//ndef __EM_REDUCTION_CODE_SIZE__
    EM_MNU_ANTF_TRACE_SET_SMS_FILTER					,
    EM_MNU_ANTF_TRACE_SET_MMS_FILTER					,
    EM_MNU_ANTF_TRACE_SET_WAP_FILTER					,
    EM_MNU_ANTF_TRACE_SET_JAVA_FILTER					,
    EM_MNU_ANTF_TRACE_SET_SS_FILTER						,
    EM_MNU_ANTF_TRACE_SET_BT_FILTER						,
    EM_MNU_ANTF_TRACE_SET_USB_FILTER					,
    EM_MNU_ANTF_TRACE_SET_CAM_FILTER					,
    EM_MNU_ANTF_TRACE_SET_FILESYS_FILTER				,
    EM_MNU_ANTF_TRACE_SET_FM_FILTER						,
    EM_MNU_ANTF_TRACE_SET_ATV_FILTER					,
	EM_MNU_ANTF_TRACE_SET_QQ_FILTER                     ,
#endif
    EM_MNU_MMP_CONTROL_MAIN_MENU                        ,
    EM_MNU_MMP_CONTROL_QUERY_STATUS                     ,
    EM_MNU_MMP_CONTROL_ENABLE_FORCE_TO_ACTIVE           ,
    EM_MNU_MMP_CONTROL_DISABLE_FORCE_TO_ACTIVE          ,
    EM_MNU_MMP_CONTROL_MMP_BIST_TEST                    ,
    EM_MNU_MMP_CONTROL_ENABLE_MMP_CMD_TIMEOUT_TEST		,
    EM_MNU_MMP_CONTROL_DISABLE_MMP_CMD_TIMEOUT_TEST		,

#ifdef __GPS_MMI__
    EM_MNU_GPS_TEST_MAIN_MENU							,
#if 1
    EM_MNU_GPS_OPEN_GPS									,
    EM_MNU_GPS_OPEN_GPS_VBI_OUTPUT					    ,
    EM_MNU_GPS_OPEN_GPS_LOG_VBI_TO_SD				    ,
    EM_MNU_GPS_OPEN_GPS_VBI_ALL				            ,
    EM_MNU_GPS_CLOSE_GPS								,
    EM_MNU_GPS_GET_GPS_STATUS							,
    EM_MNU_GPS_GET_BB_VERSION							,
    EM_MNU_GPS_POWER_SAVIMG_MODE						,
    EM_MNU_GPS_ENABLE_VBI_LOG_TO_SD					    ,
    EM_MNU_GPS_DISABLE_VBI_LOG_TO_SD			        ,
    EM_MNU_GPS_COLD_START								,
    EM_MNU_GPS_COLD_START_1_TIME						,
    EM_MNU_GPS_COLD_START_5_TIMES                       ,
    EM_MNU_GPS_COLD_START_50_TIMES						,
    EM_MNU_GPS_WARM_START								,
    EM_MNU_GPS_WARM_START_1_TIME						,
    EM_MNU_GPS_WARM_START_5_TIMES						,
    EM_MNU_GPS_WARM_START_50_TIMES						,
    EM_MNU_GPS_HOT_START								,
    EM_MNU_GPS_HOT_START_1_TIME							,
    EM_MNU_GPS_HOT_START_5_TIMES						,
    EM_MNU_GPS_HOT_START_50_TIMES						,
    EM_MNU_GPS_ENABLE_NMEA_TO_SD			            ,
    EM_MNU_GPS_DISABLE_NMEA_TO_SD                       ,
    EM_MNU_GPS_ENABLE_VBI_OUTPUT			            ,
    EM_MNU_GPS_DISABLE_VBI_OUTPUT                       ,
#else
    EM_MNU_GPS_INIT_GPS									,
    EM_MNU_GPS_CLOSE_GPS								,
    EM_MNU_GPS_READ_NMEA								,
    EM_MNU_GPS_STOP_READ_NMEA							,
    EM_MNU_GPS_ENABLE_GPS_LOG_VBI						,
    EM_MNU_GPS_DISABLE_GPS_STOP_LOG_VBI					,
    EM_MNU_GPS_SUSPEND_GPS								,
    EM_MNU_GPS_RESUME_GPS								,
    EM_MNU_GPS_STOP_LOG_VBI_TO_SD						,
    EM_MNU_GPS_ENABLE_LOG_ASSERT						,
    EM_MNU_GPS_DISABLE_LOG_ASSERT						,
    EM_MNU_GPS_CHANNELS									,
    EM_MNU_GPS_CHANNEL_6								,
    EM_MNU_GPS_CHANNEL_9								,
    EM_MNU_GPS_CHANNEL_12								,
    EM_MNU_GPS_CHANNEL_16								,
    EM_MNU_GPS_GET_GPS_STATUS							,
    EM_MNU_GPS_SET_TCXO_VALUE							,
    EM_MNU_GPS_SET_TCXO_VALUE_16369000					,
    EM_MNU_GPS_SET_TCXO_VALUE_16367600					,
#endif
#endif

    EM_MNU_LIBVER_MAIN_MENU								,
    EM_MNU_LIBVER_MMS_LIB								,
    EM_MNU_LIBVER_MMS_WAP_COMMON_LIB					,
    EM_MNU_LIBVER_BROWSER_LIB							,
    EM_MNU_LIBVER_DSP_LIB								,
    EM_MNU_LIBVER_DELTA_JAVA_LIB						,
    EM_MNU_LIBVER_OAKMONT_JAVA_LIB			,
    EM_MNU_LIBVER_BT_LIB								,
    EM_MNU_LIBVER_BOOTROM_LIB							,
    EM_MNU_LIBVER_MAP_LIB								,
    EM_MNU_LIBVER_IME_LIB								,
    EM_MNU_LIBVER_HANDWRITING_LIB                       ,

#if defined(__FT_AUTO_TEST__)
    EM_MNU_FT_AUTO_TEST_MAIN_MENU                       ,
    EM_MNU_FT_AUTO_TEST_RUN_TEST                        ,
    EM_MNU_FT_AUTO_TEST_ENTER_SIM1_NUMBER               ,
    EM_MNU_FT_AUTO_TEST_ENTER_SIM2_NUMBER               ,
    EM_MNU_FT_AUTO_TEST_ENTER_MO_NUMBER                 ,
    EM_MNU_FT_AUTO_TEST_SET_TO_MASTER_MODE              ,
    EM_MNU_FT_AUTO_TEST_SET_TO_SLAVE_MODE               ,
    EM_MNU_FT_AUTO_TEST_ENTER_SMS_REPORT_LOCATION       ,
#endif

    EM_MNU_PQ_TEST                                      ,
    EM_MNU_PQ_PHOTO_VIEWER                              ,
    EM_MNU_PQ_FILEMANAGER                               ,

    EM_MNU_AUTO_TEST_INFO                               ,

    EM_MNU_EMMI_HOPPER_MENU_ENABLE_LOCK_AP              ,
    EM_MNU_EMMI_HOPPER_MENU_DISABLE_LOCK_AP             ,
    EM_MNU_EMMI_HOPPER_MENU_RUN                         ,
    EM_MNU_EMMI_HOPPER_MENU_STOP                        ,
    EM_MNU_EMMI_HOPPER_MENU_RECORD                      ,
    EM_MNU_EMMI_HOPPER_MENU_REPLAY                      ,
#if defined(__EM_AUDIO_B3__) && defined(__UNIT_TEST_APP__) && !defined(__SDK_SIMULATION__)
    EM_MNU_EMMI_UT_MDL_MENU_START                       ,
    EM_MNU_EMMI_UT_MDL_MENU_CHECK                       ,
    EM_MNU_EMMI_UT_MDL_MENU_STOP                        ,
    EM_NMU_EMMI_UT_VIRTUAL_DEV                          ,
    EM_MNU_EMMI_UT_VIRTUAL_HEADSET_PLUGIN               ,
    EM_MNU_EMMI_UT_VIRTUAL_HEADSET_PLUGOUT              ,
    EM_MNU_EMMI_UT_DISABLE_VIRTUAL_HEADSET              ,
    EM_MNU_EMMI_UT_VIRTUAL_CHARGER_PLUGIN               ,
    EM_MNU_EMMI_UT_VIRTUAL_CHARGER_PLUGOUT              ,
    EM_MNU_EMMI_UT_DISABLE_VIRTUAL_CHARGER              ,
    EM_MNU_EMMI_UT_VIRTUAL_BATTERY_LOW                  ,
    EM_MNU_EMMI_UT_VIRTUAL_BATTERY_FULL                 ,
    EM_MNU_EMMI_UT_VIRTUAL_BATTERY_NORMAL               ,
    EM_MNU_EMMI_UT_DISABLE_VIRTUAL_BATTERY              ,
#endif
#ifdef __WAP_MMI_CDWAP__
    EM_MNU_EMMI_WAP_VIEW_HTTPHEADER                     ,
    EM_MNU_EMMI_WAP_EDIT_USERAGENT                      ,
#endif /* __WAP_MMI_CDWAP__ */
    EM_MNU_EMMI_MULTI_TOUCH_GESTURE_TEST                ,
    EM_MNU_EMMI_MULTI_TOUCH_TOUCHSRV_WIDGET_TEST        ,
    EM_MNU_EMMI_MULTI_TOUCH_RTYPE_PINCH_TEST            ,
#ifdef __3G_RIL_MMI__
    EM_MNU_LOAD_DBB_GENIE_FILTER                        ,
    EM_MNU_3G_MAIN_MENU                                 ,
    EM_MNU_3G_LOCK_CELL                                 ,
    EM_MNU_3G_UNLOCK_CELL                               ,
    EM_MNU_3G_LOCK_ARFCN                                ,
    EM_MNU_3G_UNLOCK_ARFCN                              ,
    EM_MNU_3G_FULL_FREQ_SCAN                            ,
    EM_MNU_3G_LOCK_TDD_GSM                              ,
    EM_MNU_3G_SOFTWARE_VERSION                          ,
    EM_MNU_3G_IMEI                                      ,
    EM_MNU_3G_IMSI                                      ,
    EM_MNU_3G_PLMN_FROM_UICC                            ,
    EM_MNU_3G_SET_ANTF_SD                               ,
    EM_MNU_3G_CUSTOME_CMD                               ,
    EM_MNU_3G_SILENT_REBOOT                             ,
    EM_MNU_3G_SILENT_REBOOT_ON                          ,
    EM_MNU_3G_SILENT_REBOOT_OFF                         ,
    EM_MNU_3G_GENIE_ON                          ,
    EM_MNU_3G_GENIE_OFF                         ,
#endif //__3G_RIL_MMI__
#if defined(__G1__)   && !defined(__PC_SIMULATOR__)
    EM_MNU_GET_SLEEP_MODE_STAUTS,
    EM_MNU_SET_SLEEP_MODE_DISABLE                   ,
    EM_MNU_SET_SLEEP_MODE_POWER_ON_ENABLE,
    EM_MNU_SET_SLEEP_MODE_POWER_DOWN_ENABLE,
#endif
#ifdef __ENABLE_EGPRS_STATS__
    EM_MNU_EGPRS_STAT_FLUSH                             ,
#endif
#ifdef __V24_COMPOSITE_USB___
    EM_MNU_EMMI_USB_COMPOSITE_ENABLE                    ,
    EM_MNU_EMMI_USB_COMPOSITE_DISABLE                   ,
#endif
    EM_MNU_PITCH_STRETCH_TEST                           ,
#ifdef __TOUCH_SCREEN_FWUPDATE_MMI__
    EM_MNU_UPGRADE_TS_FIRMWARE                          ,
#endif
    EM_MNU_LCD_STREAM                                   ,
    EM_MNU_LCD_STREAM_WRITE_REG                         ,
    EM_MNU_LCD_STREAM_READ_REG                          ,
#ifdef __STREAMING_MODULE__
    EM_MNU_VIDEO_STREAMING_TEST                         ,
    EM_MNU_VIDEO_STREAMING_LOAD                         ,
    EM_MNU_VIDEO_STREAMING_MODE                         ,
    EM_MNU_VIDEO_STREAMING_FILE_MODE                    ,
    EM_MNU_VIDEO_STREAMING_MEM_MODE                     ,
    EM_MNU_VIDEO_STREAMING_EDIT                         ,
    EM_MNU_VIDEO_STREAMING_START_TEST                   ,
#ifdef __RTSP_STREAMING__
    EM_MNU_RTSP_SIM_STREAMING_TEST                      ,
    //EM_MNU_RTSP_SIM_STREAMING_START_TEST                ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_START                ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_PLAY_100MS = EM_MNU_RTSP_SIM_STREAMING_TEST_START,
    EM_MNU_RTSP_SIM_STREAMING_TEST_PLAY_5MS             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_PLAY_2000MS          ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_01             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_02             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_03             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_04             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_05             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_06             ,
    //EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_07             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_08             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_09             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_10             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_11             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_12             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_13             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_14             ,
    EM_MNU_RTSP_SIM_STREAMING_TEST_ERROR_15             ,

    EM_MNU_RTSP_MDL_SIM_TEST                            ,
    EM_MNU_RTSP_MDL_SIM_TEST_PLAY_NORMAL                ,
    EM_MNU_RTSP_MDL_SIM_TEST_PLAY_5S                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_PLAY_PAUSE_RESUME          ,
    EM_MNU_RTSP_MDL_SIM_TEST_PLAY_SEEK                  ,

    EM_MNU_RTSP_MDL_SIM_TEST_CASE_01                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_02                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_03                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_04                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_05                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_06                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_07                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_08                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_09                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_10                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_11                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_12                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_13                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_14                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_15                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_16                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_17                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_18                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_19                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_20                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_21                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_22                    ,
    EM_MNU_RTSP_MDL_SIM_TEST_CASE_23                    ,
#endif //__RTSP_STREAMING__
#endif //__STREAMING_MODULE__
    EM_MNU_MP_FLAG_TRUN_ONOFF_RAM_DUMP                  ,
    EM_MNU_MP_FLAG_TRUN_ONOFF_RAM_DUMP_ON               ,
    EM_MNU_MP_FLAG_TRUN_ONOFF_RAM_DUMP_OFF              ,
    EM_MNU_IQ_DUMP_MENU                                ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_MENU                 ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_CASE1                ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_CASE2                ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_CASE3                ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_CASE4                ,
    EM_MNU_IQ_DUMP_FILTER_SETTING_CASE5                ,
    EM_MNU_IQ_DUMP_ENABLE_VIA_E2P_MENU                 ,
    EM_MNU_IQ_DUMP_ENABLE_VIA_E2P_ON                   ,
    EM_MNU_IQ_DUMP_ENABLE_VIA_E2P_OFF                  ,
    EM_MNU_EMMI_ENABLE_MEM_HISTORY                      ,
    EM_MNU_EMMI_DISABLE_MEM_HISTORY                     ,
    EM_MNU_EMMI_HIGH_CPU_SPEED_SLEEP_RECORD             ,
    EM_MNU_EMMI_PREFER_NETWORK                          ,
    EM_MNU_EMMI_PREFER_NETWORK_ON                       ,
    EM_MNU_EMMI_PREFER_NETWORK_OFF                      ,
    EM_MNU_LAST                                         ,
    /*}EM_DRIVER_INFO_ID_e;  */
} EmAppMenuId_e;

#endif
