
#ifndef KMX_IME_CONFIG_H
#define KMX_IME_CONFIG_H

#include "kmximeapi.h"

#ifdef __cplusplus 
extern "C"{ 
#endif 

/* User Data */
#define    KMX_PINYIN_USER_DATA_SIZE         8  
#define    KMX_BOPOMOFO_USER_DATA_SIZE       8  
#define    KMX_STROKE_USER_DATA_SIZE         1  
#define    KMX_ALPHABETIC_USER_DATA_SIZE     4  

/* User Data Size Definition  */
typedef enum
{
//#if defined(KMX_CFG_LANG_ARABIC)
    KMX_ARABIC_USER_DATA_START,
    KMX_ARABIC_USER_DATA_LAST = KMX_ARABIC_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ARABIC) */

//#if defined(KMX_CFG_LANG_BENGALI)
    KMX_BENGALI_USER_DATA_START,
    KMX_BENGALI_USER_DATA_LAST = KMX_BENGALI_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_BENGALI) */

//#if defined(KMX_CFG_LANG_BULGARIAN)
    KMX_BULGARIAN_USER_DATA_START,
    KMX_BULGARIAN_USER_DATA_LAST = KMX_BULGARIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_BULGARIAN) */

//#if defined(KMX_CFG_LANG_CZECH)
    KMX_CZECH_USER_DATA_START,
    KMX_CZECH_USER_DATA_LAST = KMX_CZECH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_CZECH) */

//#if defined(KMX_CFG_LANG_DANISH)
    KMX_DANISH_USER_DATA_START,
    KMX_DANISH_USER_DATA_LAST = KMX_DANISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_DANISH) */

//#if defined(KMX_CFG_LANG_DUTCH)
    KMX_DUTCH_USER_DATA_START,
    KMX_DUTCH_USER_DATA_LAST = KMX_DUTCH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_DUTCH) */

//#if defined(KMX_CFG_LANG_ENGLISH)
    KMX_ENGLISH_USER_DATA_START,
    KMX_ENGLISH_USER_DATA_LAST = KMX_ENGLISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ENGLISH) */

//#if defined(KMX_CFG_LANG_ENGLISH_INTL)
    KMX_ENGLISH_INTL_USER_DATA_START,
    KMX_ENGLISH_INTL_USER_DATA_LAST = KMX_ENGLISH_INTL_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ENGLISH_INTL) */

//#if defined(KMX_CFG_LANG_FINNISH)
    KMX_FINNISH_USER_DATA_START,
    KMX_FINNISH_USER_DATA_LAST = KMX_FINNISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_FINNISH) */

//#if defined(KMX_CFG_LANG_FRENCH)
    KMX_FRENCH_USER_DATA_START,
    KMX_FRENCH_USER_DATA_LAST = KMX_FRENCH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_FRENCH) */

//#if defined(KMX_CFG_LANG_GERMAN)
    KMX_GERMAN_USER_DATA_START,
    KMX_GERMAN_USER_DATA_LAST = KMX_GERMAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_GERMAN) */

//#if defined(KMX_CFG_LANG_GREEK)
    KMX_GREEK_USER_DATA_START,
    KMX_GREEK_USER_DATA_LAST = KMX_GREEK_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_GREEK) */

//#if defined(KMX_CFG_LANG_HEBREW)
    KMX_HEBREW_USER_DATA_START,
    KMX_HEBREW_USER_DATA_LAST = KMX_HEBREW_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_HEBREW) */

//#if defined(KMX_CFG_LANG_HINDI)
    KMX_HINDI_USER_DATA_START,
    KMX_HINDI_USER_DATA_LAST = KMX_HINDI_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_HINDI) */

//#if defined(KMX_CFG_LANG_HINGLISH)
    KMX_HINGLISH_USER_DATA_START,
    KMX_HINGLISH_USER_DATA_LAST = KMX_HINGLISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_HINGLISH) */

//#if defined(KMX_CFG_LANG_HUNGARIAN)
    KMX_HUNGARIAN_USER_DATA_START,
    KMX_HUNGARIAN_USER_DATA_LAST = KMX_HUNGARIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_HUNGARIAN) */

//#if defined(KMX_CFG_LANG_INDONESIAN)
    KMX_INDONESIAN_USER_DATA_START,
    KMX_INDONESIAN_USER_DATA_LAST = KMX_INDONESIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_INDONESIAN) */

//#if defined(KMX_CFG_LANG_ITALIAN)
    KMX_ITALIAN_USER_DATA_START,
    KMX_ITALIAN_USER_DATA_LAST = KMX_ITALIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ITALIAN) */

//#if defined(KMX_CFG_LANG_LITHUANIAN)
    KMX_LITHUANIAN_USER_DATA_START,
    KMX_LITHUANIAN_USER_DATA_LAST = KMX_LITHUANIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ITALIAN) */
//#if defined(KMX_CFG_LANG_MALAY)
    KMX_MALAY_USER_DATA_START,
    KMX_MALAY_USER_DATA_LAST = KMX_MALAY_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_MALAY) */
//#if defined(KMX_CFG_LANG_THAI)
    KMX_THAI_USER_DATA_START,
    KMX_THAI_USER_DATA_LAST = KMX_THAI_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_THAI) */

//#if defined(KMX_CFG_LANG_NORWEGIAN)
    KMX_NORWEGIAN_USER_DATA_START,
    KMX_NORWEGIAN_USER_DATA_LAST = KMX_NORWEGIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_NORWEGIAN) */

//#if defined(KMX_CFG_LANG_PERSIAN)
    KMX_PERSIAN_USER_DATA_START,
    KMX_PERSIAN_USER_DATA_LAST = KMX_PERSIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_PERSIAN) */

//#if defined(KMX_CFG_LANG_POLISH)
    KMX_POLISH_USER_DATA_START,
    KMX_POLISH_USER_DATA_LAST = KMX_POLISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_POLISH) */

//#if defined(KMX_CFG_LANG_SWEDISH)
    KMX_SWEDISH_USER_DATA_START,
    KMX_SWEDISH_USER_DATA_LAST = KMX_SWEDISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_SWEDISH) */
//#if defined(KMX_CFG_LANG_PORTUGUESE)
    KMX_PORTUGUESE_USER_DATA_START,
    KMX_PORTUGUESE_USER_DATA_LAST = KMX_PORTUGUESE_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_PORTUGUESE) */
//#if defined(KMX_CFG_LANG_SPANISH)
    KMX_SPANISH_USER_DATA_START,
    KMX_SPANISH_USER_DATA_LAST = KMX_SPANISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_SPANISH) */

//#if defined(KMX_CFG_LANG_ROMANIAN)
    KMX_ROMANIAN_USER_DATA_START,
    KMX_ROMANIAN_USER_DATA_LAST = KMX_ROMANIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_ROMANIAN) */

//#if defined(KMX_CFG_LANG_RUSSIAN)
    KMX_RUSSIAN_USER_DATA_START,
    KMX_RUSSIAN_USER_DATA_LAST = KMX_RUSSIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_RUSSIAN) */

//#if defined(KMX_CFG_LANG_SLOVAK)
    KMX_SLOVAK_USER_DATA_START,
    KMX_SLOVAK_USER_DATA_LAST = KMX_SLOVAK_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_SLOVAK) */

//#if defined(KMX_CFG_LANG_SLOVENIAN)
    KMX_SLOVENIAN_USER_DATA_START,
    KMX_SLOVENIAN_USER_DATA_LAST = KMX_SLOVENIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_SLOVENIAN) */

//#if defined(KMX_CFG_LANG_SWAHILI)
    KMX_SWAHILI_USER_DATA_START,
    KMX_SWAHILI_USER_DATA_LAST = KMX_SWAHILI_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_SWAHILI) */

//#if defined(KMX_CFG_LANG_TURKISH)
    KMX_TURKISH_USER_DATA_START,
    KMX_TURKISH_USER_DATA_LAST = KMX_TURKISH_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_TURKISH) */
//#if defined(KMX_CFG_LANG_UKRAINIAN)
    KMX_UKRAINIAN_USER_DATA_START,
    KMX_UKRAINIAN_USER_DATA_LAST = KMX_UKRAINIAN_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_UKRAINIAN) */
//#if defined(KMX_CFG_LANG_VIETNAMESE)
    KMX_VIETNAMESE_USER_DATA_START,
    KMX_VIETNAMESE_USER_DATA_LAST = KMX_VIETNAMESE_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_VIETNAMESE) */

//#if defined(KMX_CFG_LANG_CHINESE_SIMPLIFIED)
    KMX_CHS_PINYIN_USER_DATA_START,
    KMX_CHS_PINYIN_USER_DATA_LAST = KMX_CHS_PINYIN_USER_DATA_START + KMX_PINYIN_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_CHINESE_SIMPLIFIED) */

//#if defined(KMX_CFG_LANG_CHINESE_TRADITIONAL)
    KMX_CHT_BOPOMOFO_USER_DATA_START,
    KMX_CHT_BOPOMOFO_USER_DATA_LAST = KMX_CHT_BOPOMOFO_USER_DATA_START + KMX_BOPOMOFO_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_CHINESE_TRADITIONAL) */

//#if defined(KMX_CFG_LANG_CHINESE_SIMPLIFIED)
    KMX_CHS_STROKE_USER_DATA_START,
    KMX_CHS_STROKE_USER_DATA_LAST = KMX_CHS_STROKE_USER_DATA_START + KMX_STROKE_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_CHINESE_SIMPLIFIED) */

//#if defined(KMX_CFG_LANG_CHINESE_TRADITIONAL)
    KMX_CHT_STROKE_USER_DATA_START,
    KMX_CHT_STROKE_USER_DATA_LAST = KMX_CHT_STROKE_USER_DATA_START + KMX_STROKE_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_CHINESE_TRADITIONAL) */
	
//#if defined(KMX_CFG_LANG_URDU)
    KMX_URDU_USER_DATA_START,
    KMX_URDU_USER_DATA_LAST = KMX_URDU_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_URDU) */
//#if defined(KMX_CFG_LANG_UYGHUR)
    KMX_UYGHUR_USER_DATA_START,
    KMX_UYGHUR_USER_DATA_LAST = KMX_UYGHUR_USER_DATA_START + KMX_ALPHABETIC_USER_DATA_SIZE - 1,
//#endif /* #if defined(KMX_CFG_LANG_UYGHUR) */
    KMX_TOTAL_USER_DATA_SIZE
} kmx_user_data_size_enum;

const KMX_PT_IM_CONFIG * kmx_im_get_config(int language);
void kmx_im_make_config(int language, unsigned int *im_list, KMX_PT_IM_CONFIG *config);

#ifdef __cplusplus 
}
#endif 

#endif /*  KMX_IME_CONFIG_H */

