#ifndef __MMI_BEAUTYCLKSETTINGAPP_ID_H__
#define __MMI_BEAUTYCLKSETTINGAPP_ID_H__

typedef enum
{
    BEAUTYCLKSETTING_WND_MAIN = WND_ID_APP_BASE,
} BeautyClkSettingAppWndId_e;

typedef enum
{
    BEAUTYCLKSETTING_MAIN_VIEW_BEGIN =APP_WDG_START,

    BEAUTYCLKSETTING_MAIN_VIEW_BG,
    BEAUTYCLKSETTING_MAIN_VIEW_CLOTH_EFFECT,

    BEAUTYCLKSETTING_MAIN_VIEW_INFO_BG,
    BEAUTYCLKSETTING_MAIN_VIEW_TIME,
    BEAUTYCLKSETTING_MAIN_VIEW_I12H,

    BEAUTYCLKSETTING_MAIN_VIEW_CNTR,
    BEAUTYCLKSETTING_MAIN_VIEW_BTN,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_CNTR,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_BG,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_TITLE,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_ICON,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_ON,
    BEAUTYCLKSETTING_MAIN_VIEW_SWITCH_OFF,
    BEAUTYCLKSETTING_MAIN_VIEW_EXIT_BG,
    BEAUTYCLKSETTING_MAIN_VIEW_EXIT_TITLE,

    BEAUTYCLKSETTING_MAIN_VIEW_MAGNIFY,

    BEAUTYCLKSETTING_MAIN_VIEW_END
}BeautyClkSettingMainView_e;

typedef enum
{
	MNU_BCS_KEYGUARD_APP = 0,
	MNU_BCS_KEYGUARD_ON,
	MNU_BCS_KEYGUARD_OFF,
	MNU_BCS_ALARM_APP,
	MNU_BCS_ALARM_ON,
	MNU_BCS_ALARM_OFF,
}BeautyClkSettingMenuId_e;

#endif //__MMI_BEAUTYCLKSETTINGAPP_ID_H__

