#ifndef __MMI_NETWORKAPP_VIEW_ID_H__
#define __MMI_NETWORKAPP_VIEW_ID_H__

#include "mmi_view_id_range.h"

#define NETWORK_DUAL_MASTER     (0)
#define NETWORK_DUAL_SLAVE      (1)

enum
{
/* View ID start */
    VID_NETWORK_MAIN_LIST_VIEW = MMI_VIEW_ID_AP_BEGIN,
    VID_NETWORK_PREFERRED_LIST_VIEW,
    VID_NETWORK_NET_ACCESS_VIEW,
    VID_NETWORK_NET_SELECTION_VIEW,
    VID_NETWORK_BAND_SELECTION_VIEW,
    VID_NETWORK_LINE_SELECTION_VIEW,
    VID_NETWORK_AVALIABLE_LIST_VIEW,
    VID_NETWORK_ALL_PLMN_LIST_VIEW,
    MID_NETWORK_OPTIONMENU_MENUMODEL_L1,
    VID_NETWORK_SELECT_DUALSIM_VIEW,
    VID_NETWORK_AIRPLANE_MODE_VIEW
/* View ID end */
};

enum
{
/* Widget ID start */
    WID_NETWORK_TITLEWIDGET = 1,
    WID_NETWORK_MENUWIDGET,
    WID_NETWORK_NET_ACCESS_MENU_MODEL,
    WID_NETWORK_NET_SELECTION_MENU_MODEL,
    WID_NETWORK_LINE_SELECTION_MENU_MODEL,
    WID_NETWORK_BAND_SELECTION_MENU_MODEL
/* Widget ID end */
};


#endif /* __MMI_NETWORKAPP_VIEW_ID_H__ */
