typedef enum
{
	MNU_NETWORK_PREFERRED_LIST_OPTION = 0,
	MNU_NETWORK_EDIT,
	MNU_NETWORK_REMOVE,
	MNU_NETWORK_REMOVE_ALL,
	MNU_NETWORK_PREFERRED_LIST,
	MNU_NETWORK_EMPTY_1,
	MNU_NETWORK_EMPTY_2,
	MNU_NETWORK_EMPTY_3,
	MNU_NETWORK_EMPTY_4,
	MNU_NETWORK_EMPTY_5,
	MNU_NETWORK_EMPTY_6,
	MNU_NETWORK_NET_SELECTION_MODE,
	MNU_NETWORK_AUTO,
	MNU_NETWORK_MANUAL,
#ifdef __GPRS_MMI__
	MNU_NETWORK_NET_ACCESS_MODE,
	MNU_NETWORK_GSM_ONLY,
	MNU_NETWORK_GPRS_PREFERRED,
#endif //__GPRS_MMI__	
	MNU_NETWORK_BAND_SELECTION,
	MNU_NETWORK_QUAD_AUTO,
	MNU_NETWORK_850_MHZ,
	MNU_NETWORK_900_MHZ,
	MNU_NETWORK_1800_MHZ,
	MNU_NETWORK_1900_MHZ,
	MNU_NETWORK_9001800_MHZ,
	MNU_NETWORK_850_1900_MHZ,
	MNU_NETWORK_LINE_SELECTION,
	MNU_NETWORK_LINE_1,
	MNU_NETWORK_LINE_2,

#ifdef __3G_RIL_MMI__
	MNU_NETWORK_BAND_AUTO,
	MNU_NETWORK_BAND_3G,
	MNU_NETWORK_BAND_2G,
#endif
}NetworkMenuId_e;
