#ifndef __MMI_CHECKDISKAPP_RS__
#define __MMI_CHECKDISKAPP_RS__

#endif /* __MMI_CHECKDISKAPP_RS__ */

ApBegin(RS,CLSID_CHECKDISKAPP)   
    WndBegin(CHECKDISK_WND_TEXT)
        WdgBegin(CLSID_VTMMENU,TextVtm)
        		VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_AZAZ_SOUND, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU,TextVtm)
    WndEnd(CHECKDISK_WND_TEXT)
ApEnd(RS,CLSID_CHECKDISKAPP)

