ApBegin(RS,CLSID_VIDEOTELEPHONYAPP)
    WndBegin(VIDEOTELEPHONY_WND_OUTGOINGCALL)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CANCEL} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

        WdgBegin(CLSID_IMAGEWIDGET,CallScreenBGWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,CallScreenBGWdg)
        WdgBegin(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_OUTGOING_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_OUTGOINGCALL_ANIM}})
            WdgImageSetDataByIDRC(VT_IMG_OUTGOINGCALL_ANIM)
        WdgEnd(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)
        WdgBegin(CLSID_TEXTWIDGET,CallStatesTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLSTATE_POS_X,CCAPP_OUTGOING_CALLSTATE_POS_Y},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            WdgTextSetDataByIDRC(TXT_CCL_N_VIDEO_CALLING)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELEAPP_STATES_TEXT)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(DEF_THM_VIDEOTELERAPP_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,CallStatesTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLINFO_POS_X,CCAPP_OUTGOING_CALLINFO_POS_Y},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INFO_1_TEXT)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(DEF_THM_VIDEOTELERAPP_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,DuoStateTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLDUO_POS_X,CCAPP_OUTGOING_CALLDUO_POS_Y},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INFO_2_TEXT)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(DEF_THM_VIDEOTELERAPP_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,DuoStateTextWdg)
    WndEnd(VIDEOTELEPHONY_WND_OUTGOINGCALL)


	WndBegin(VIDEOTELEPHONY_WND_INCALLSCREEN)
		WndSetAllSoftkeyRC( {SK_OPTION, SK_NONE, SK_NONE} )
		WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

		WdgBegin(CLSID_IMAGEWIDGET,CallScreenBgImgWdg)
			WdgImageCreateForWndRC({{0,0},{VIDEOTELEPHONYAPP_DEFAULT_VIEW_WIDTH,VIDEOTELEPHONYAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
			WdgImageSetDataByIDRC(VT_IMG_DIALING_BG)
		WdgEnd(CLSID_IMAGEWIDGET,CallScreenBgImgWdg)

		WdgBegin(CLSID_IMAGEWIDGET,VideoCallBgImgWdg)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_VIDEOCALL_BG_POS_X,VIDEOTELEPHONYAPP_VIDEOCALL_BG_POS_Y},{VIDEOTELEPHONYAPP_VIDEOCALL_BG_WIDTH,VIDEOTELEPHONYAPP_VIDEOCALL_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_VIDEO_CALL_BG}})
			WdgImageSetDataByIDRC(VT_IMG_VIDEO_CALL_BG)
		WdgEnd(CLSID_IMAGEWIDGET,VideoCallBgImgWdg)

		WdgBegin(CLSID_OSDWIDGET,VideoCallOsdWdg)
			WdgOsdCreateForWndRC({{VIDEOTELEPHONYAPP_OSD_VIEW_POS_X,VIDEOTELEPHONYAPP_OSD_VIEW_POS_Y},{VIDEOTELEPHONYAPP_OSD_VIEW_WIDTH,VIDEOTELEPHONYAPP_OSD_VIEW_HEIGHT}})
		WdgEnd(CLSID_OSDWIDGET,VideoCallOsdWdg)

		WdgBegin(CLSID_OSDWIDGET,VideoCallLocalOsdWdg)
			WdgOsdCreateForWndRC({{VIDEOTELEPHONYAPP_SMALL_VIEW_POS_X,VIDEOTELEPHONYAPP_SMALL_VIEW_POS_Y},{VIDEOTELEPHONYAPP_SMALL_VIEW_WIDTH,VIDEOTELEPHONYAPP_SMALL_VIEW_HEIGHT}})
		WdgEnd(CLSID_OSDWIDGET,VideoCallLocalOsdWdg)
		
		WdgBegin(CLSID_IMAGEWIDGET,VideoCallSmallBgImgWdg)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_VIDEOCALL_SMALL_BG_POS_X,VIDEOTELEPHONYAPP_VIDEOCALL_SMALL_BG_POS_Y},{VIDEOTELEPHONYAPP_VIDEOCALL_SMALL_BG_WIDTH,VIDEOTELEPHONYAPP_VIDEOCALL_SMALL_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_VIDEO_CALL_SMALL_BG}})
			WdgImageSetDataByIDRC(VT_IMG_VIDEO_CALL_SMALL_BG)
		WdgEnd(CLSID_IMAGEWIDGET,VideoCallSmallBgImgWdg)
	        
		/*
		WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg1)
			WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg1)
		WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg2)
			WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg2)
		WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg3)
			WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg3)
		WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg4)
			WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg4)
		WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg5)
			WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg5)
		*/
	        
		WdgBegin(CLSID_IMAGEWIDGET,DuoImgWdg)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_DUO_IMAGE_POS_X,VIDEOTELEPHONYAPP_DUO_IMAGE_POS_Y},{VIDEOTELEPHONYAPP_DUO_IMAGE_WIDTH,VIDEOTELEPHONYAPP_DUO_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
			WdgImageSetDataByIDRC(IMG_NULL_ID)
		WdgEnd(CLSID_IMAGEWIDGET,DuoImgWdg)
		
        WdgBegin(CLSID_IMAGEWIDGET,RecordImgWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORD_IMAGE_POS_X,CCAPP_RECORD_IMAGE_POS_Y},{16,16},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_CALL_RECORD_STATE}})
            WdgImageSetDataByIDRC(VT_IMG_CALL_RECORD_STATE)
        WdgEnd(CLSID_IMAGEWIDGET,RecordImgWdg)
		
		WdgBegin(CLSID_IMAGEWIDGET,MuteImgWdg)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_MUTE_IMAGE_POS_X,VIDEOTELEPHONYAPP_MUTE_IMAGE_POS_Y},{VIDEOTELEPHONYAPP_MUTE_IMAGE_WIDTH,VIDEOTELEPHONYAPP_MUTE_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_MUTE_STATE}})
			WdgImageSetDataByIDRC(VT_IMG_MUTE_STATE)
		WdgEnd(CLSID_IMAGEWIDGET,MuteImgWdg)

		WdgBegin(CLSID_IMAGEWIDGET,AudioSourceImgWdg)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_AUDIOSOURCE_OFF_IMAGE_POS_X,VIDEOTELEPHONYAPP_AUDIOSOURCE_OFF_IMAGE_POS_Y},{VIDEOTELEPHONYAPP_AUDIOSOURCE_OFF_IMAGE_WIDTH,VIDEOTELEPHONYAPP_AUDIOSOURCE_OFF_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_SPEAKER_OFF}})
			WdgImageSetDataByIDRC(VT_IMG_SPEAKER_OFF)
		WdgEnd(CLSID_IMAGEWIDGET,AudioSourceImgWdg)
		
        WdgBegin(CLSID_IMAGEWIDGET,TextAreaBgImgWdg)
            WdgImageCreateForWndRC({{0,278-MAIN_STBAR_HEIGHT},{240,82},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_TEXTAREA_BG}})
            WdgImageSetDataByIDRC(VT_IMG_TEXTAREA_BG)
        WdgEnd(CLSID_IMAGEWIDGET,TextAreaBgImgWdg)
	        
		WdgBegin(CLSID_IMAGEWIDGET,CallInfoImgWdg1)
			WdgImageCreateForWndRC({{VIDEOTELEPHONYAPP_TEXTAREA_LINE1_IMG_POS_X,VIDEOTELEPHONYAPP_TEXTAREA_LINE1_IMG_POS_Y},{VIDEOTELEPHONYAPP_TEXTAREA_CALLINFO_IMG_WIDTH,VIDEOTELEPHONYAPP_CALLINFO_ITEM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_CALL_ACTIVE}})
			WdgImageSetDataByIDRC(VT_IMG_CALL_ACTIVE)
		WdgEnd(CLSID_IMAGEWIDGET,CallInfoImgWdg1)
	        
		WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg1)
			WdgTextCreateForWndRC({{VIDEOTELEPHONYAPP_TEXTAREA_LINE1_TEXT_POS_X,VIDEOTELEPHONYAPP_TEXTAREA_LINE1_TEXT_POS_Y},{VIDEOTELEPHONYAPP_TEXTAREA_CALLINFO_TEXT_WIDTH,VIDEOTELEPHONYAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
			WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INFO_3_TEXT)
			/*
			WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
			WdgTextSetTextOutlineColorRC(COLOR_WHITE)
			*/
		WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg1)
		
		/*
		WdgBegin(CLSID_MENUWIDGET,CallInfoMptyListWidget)        
			WdgMenuCreateForWndRC({{CCAPP_TEXTAREA_LINE1_TEXT_POS_X,CCAPP_TEXTAREA_LINE1_TEXT_POS_Y},{CCAPP_TEXTAREA_CALLINFO_TEXT_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},WDG_MENU_TYPE_HORZ})    
			WdgMenuSetItemWidthRC((u16)CCAPP_TEXTAREA_LINE1_MPTY_IMG_WIDTH)
			WdgMenuSetItemHeightRC((u16)CCAPP_CALLINFO_ITEM_HEIGHT)
			WdgMenuSetFixedNumRC(6)
		WdgEnd(CLSID_MENUWIDGET,CallInfoMptyListWidget)

		WdgBegin(CLSID_IMAGEWIDGET,CallInfoImgWdg2)
			WdgImageCreateForWndRC({{CCAPP_TEXTAREA_LINE2_IMG_POS_X,CCAPP_TEXTAREA_LINE2_IMG_POS_Y},{CCAPP_TEXTAREA_CALLINFO_IMG_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VT_IMG_CALL_HOLD}})
			WdgImageSetDataByIDRC(VT_IMG_CALL_HOLD)
		WdgEnd(CLSID_IMAGEWIDGET,CallInfoImgWdg2)

		WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg2)
			WdgTextCreateForWndRC({{CCAPP_TEXTAREA_LINE2_TEXT_POS_X,CCAPP_TEXTAREA_LINE2_TEXT_POS_Y},{CCAPP_TEXTAREA_CALLINFO_TEXT_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
			WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
			WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetTextColorRC(COLOR_GREY_3)
			WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
			WdgTextSetTextOutlineColorRC(COLOR_WHITE)
		WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg2)
		*/
	WndEnd(VIDEOTELEPHONY_WND_INCALLSCREEN)


	WndBegin(VIDEOTELEPHONY_WND_INCALLEDITOR)
		WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CANCEL} )
		WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

        WdgBegin(CLSID_INPUTWIDGET,InputWidget)
            WdgInputCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgInputSetMultilineRC(TRUE)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
            WdgInputSetCursorColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(VIDEOTELEPHONYAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
            WdgInputSetHandWritingEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,InputWidget)
        WdgBegin(CLSID_TEXTWIDGET,ShortcutWidget)
            WdgTextCreateForWndRC({{0,0},{DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START | ALIGN_V_MIDDLE)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
	WdgEnd(CLSID_TEXTWIDGET,ShortcutWidget)
        
        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg1)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(12,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_01}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_02}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_03}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_04}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_05}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_06}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_07}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_08}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_09}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_10}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 10}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_11}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 11}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_12}}}) \
	      WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_COLNUM)            
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg1)
        
        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg2)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_HEIGHT}, WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(5,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_SIM1}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_MESSAGE  }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_ADD      }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CLEAR    }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, TXT_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_SIM2 }}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_COLNUM)   
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg2)
        
        WdgBegin(CLSID_INPUTWIDGET,ActInputWidget)
            WdgInputCreateForWndRC({{0,0},{0,MAIN_DEFVIEW_WIDTH},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetTextColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
            WdgInputSetCursorColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(VIDEOTELEPHONYAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,ActInputWidget)
        WdgBegin(CLSID_TEXTWIDGET,ActShortcutWidget)
            WdgTextCreateForWndRC({{0,0},{0,MAIN_DEFVIEW_WIDTH},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
            WdgCommonSetTextColorRC(DEF_THM_VIDEOTELERAPP_INPUT)
        WdgEnd(CLSID_TEXTWIDGET,ActShortcutWidget)
    WndEnd(VIDEOTELEPHONY_WND_INCALLEDITOR)

    WndBegin(VIDEOTELEPHONY_WND_IPNUMBEREDITOR)
        WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_IP_NUMBER})
        WndSetAllSoftkeyRC( {SK_SAVE, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_INPUTWIDGET,IpNumInput)
            WdgInputCreateForWndRC({{0,0},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT_WITH_SB},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetMultilineRC(FALSE)
            WdgInputSetMaxByteLengthRC(VIDEOTELEPHONYAPP_IPCALL_MAX_NUM_LEN)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP)
        WdgEnd(CLSID_INPUTWIDGET,IpNumInput)
    WndEnd(VIDEOTELEPHONY_WND_IPNUMBEREDITOR)

    /*
    WndBegin(VIDEOTELEPHONY_WND_MULTIPARTYLIST)
        WdgBegin(CLSID_VTMMENU,MutiList)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_MULTIPARTY,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,MutiList)
    WndEnd(VIDEOTELEPHONY_WND_MULTIPARTYLIST)
    */
    WndBegin(VIDEOTELEPHONY_WND_IPNUMBERLIST)
        WdgBegin(CLSID_VTMMENU,IpNumber)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_IP_NUMBER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,IpNumber)
    WndEnd(VIDEOTELEPHONY_WND_IPNUMBERLIST)

    WndBegin(VIDEOTELEPHONY_WND_INCALLEDITOROPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,InCallMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_ADD},TXT_OIL1_N_SAVE},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SEND},TXT_OIL1_N_SEND}})
        WdgEnd(CLSID_VTMOPTIONMENU,InCallMenu)
    WndEnd(VIDEOTELEPHONY_WND_INCALLEDITOROPTIONMENU)

    /*
    WndBegin(VIDEOTELEPHONY_WND_MULTIPARTYOPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,MultiMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SPLIT},TXT_OIL1_N_SPLIT},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_END_SELECTED_},TXT_OIL1_N_END_SELECTED_CALL}})
        WdgEnd(CLSID_VTMOPTIONMENU,MultiMenu)
    WndEnd(VIDEOTELEPHONY_WND_MULTIPARTYOPTIONMENU)
    */
    
    WndBegin(VIDEOTELEPHONY_WND_INCALLSCREENOPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,InCallScreen)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,19})
            VtmCreateOptionMenuDataRC(19,
            {{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SPEAKER},TXT_OIL1_N_SPEAKER},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_HANDSET},TXT_OIL1_N_HANDSET},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_BT_HEADSET},TXT_OIL1_N_VT_BTHEADSET},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_MUTE},TXT_RSK_N_MUTE},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_UNMUTE},TXT_RSK_N_UNMUTE},\
             {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_AUDIO_SOURCE_ON},TXT_OIL1_N_VT_AUDIO_SOURCE_ON},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_AUDIO_SOURCE_OFF},TXT_OIL1_N_VT_AUDIO_SOURCE_OFF},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_HOLD},TXT_OIL1_N_VT_HOLD},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_RETRIEVE},TXT_OIL1_N_VT_RETRIEVE},\
            /*
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SWAP},TXT_OIL1_N_SWAP},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_VIEW},TXT_OIL1_N_VIEW},\
            */
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_END_ACTIVE},TXT_OIL1_N_END_ACTIVE_CALL},\
            
            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_ZOOM},TXT_OIL1_N_VT_ZOOM},\
            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_LIGHT},TXT_OIL1_N_VT_LIGHT},\
            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SETTINGS},TXT_OIL1_N_SETTINGS},\
            /*
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_END_HOLD},TXT_OIL1_N_END_HOLD_CALL},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_MULTIPARTY},TXT_OIL1_N_MULTIPARTY},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_TRANSFER},TXT_OIL1_N_TRANSFER},\
            */
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_VOLUME},TXT_LIL_N_VOLUME},\
            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_DTMF},TXT_OIL1_N_VT_DTMF},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_RECORD},TXT_LIL_N_RECORD_VIDEO},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_STOP_RECORD},TXT_OIL1_N_VT_STOP_RECORD},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_PHONEBOOK},TXT_LIL_N_PHONEBOOK},\
            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_MESSAGE},TXT_LIL_N_MESSAGES}})
        WdgEnd(CLSID_VTMOPTIONMENU,InCallScreen)
    WndEnd(VIDEOTELEPHONY_WND_INCALLSCREENOPTIONMENU)

	WndBegin(VIDEOTELEPHONY_WND_INCALLSCREENMODE)
		WdgBegin(CLSID_VTMMENU,InCallScreenMode)
			VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,4,0,0})
			WdgStaticMenuItemRC(4, {
				{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_SMALL, TXT_LIL_N_VT_LOCAL_SMALL},
				{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_LARGE, TXT_LIL_N_VT_LOCAL_LARGE},
				{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_REMOTE_ONLY, TXT_LIL_N_VT_REMOTE_ONLY},
				{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_VIDEOTELEPHONY_OPT_SETTINGS_SCREEN_MODE_LOCAL_ONLY, TXT_LIL_N_VT_LOCAL_ONLY}})
		WdgEnd(CLSID_VTMMENU,InCallScreenMode)
	WndEnd(VIDEOTELEPHONY_WND_INCALLSCREENMODE)
	
	WndBegin(VIDEOTELEPHONY_WND_INCALLSCREENSOURCE)
		WdgBegin(CLSID_VTMPOPUPSELECT,InCallScreenSource)
			VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
			VtmCreatePopUpSelectDataRC(2,
			{{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SETTINGS_SOURCE_FROM_CAMERA},TXT_LIL_N_CAMERA},\
			{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_VIDEOTELEPHONY_OPT_SETTINGS_SOURCE_FROM_FILE},TXT_LIL_N_SELECT_PICTURE}})
		WdgEnd(CLSID_VTMPOPUPSELECT,InCallScreenSource)
	WndEnd(VIDEOTELEPHONY_WND_INCALLSCREENSOURCE)

	WndBegin(VIDEOTELEPHONY_WND_DTMFNUMBERINPUT)
		WndSetAllSoftkeyRC( {SK_SELECT, SK_OK, SK_BACK} )
		WdgBegin(CLSID_VTMPOPUPINPUT,DtmfInput)
			VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_PML_N_VT_DTMF_NUMBER,MAE_INPUTMODE_DIALING})
		WdgEnd(CLSID_VTMPOPUPINPUT,DtmfInput)
	WndEnd(VIDEOTELEPHONY_WND_DTMFNUMBERINPUT)

	WndBegin(VIDEOTELEPHONY_WND_DUALMENU)
		WdgBegin(CLSID_VTMSIMSELECTION,DualMenu)
			VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_CALL})
		WdgEnd(CLSID_VTMSIMSELECTION,DualMenu)
	WndEnd(VIDEOTELEPHONY_WND_DUALMENU)

	WndBegin(VIDEOTELEPHONY_WND_CUS)
		RSCustomize(Pos_t,tTalkViewImgAreaCntnrPos,{VIDEOTELEPHONYAPP_IMGAREA_POS_X,VIDEOTELEPHONYAPP_IMGAREA_POS_Y})
		RSCustomize(Pos_t,tTalkViewTimeAreaCntnrPos,{VIDEOTELEPHONYAPP_TIMEAREA_POS_X,VIDEOTELEPHONYAPP_TIMEAREA_POS_Y})
		RSCustomize(Pos_t,tTalkViewTextAreaCntnrPos,{VIDEOTELEPHONYAPP_TEXTAREA_POS_X,VIDEOTELEPHONYAPP_TEXTAREA_POS_Y})
		RSCustomize(WProp_t,tOutgoingImgAreaCntnrPos,{TRUE,1})
		RSCustomize(WProp_t,tOutgoingTextAreaCntnrPos,{TRUE,1})
	WndEnd(VIDEOTELEPHONY_WND_CUS)
ApEnd(RS,CLSID_VIDEOTELEPHONYAPP)

