#ifndef __MMI_JAVAAMSAPP_ID_H__
#define __MMI_JAVAAMSAPP_ID_H__

enum
{
	MNU_JAVAAMSAPP_OPTION_LAUNCH,
	MNU_JAVAAMSAPP_OPTION_RST_NETPROFILE,
	MNU_JAVAAMSAPP_OPTION_UNINSTALL,
	MNU_JAVAAMSAPP_OPTION_SET_PROFILE,
	MNU_JAVAAMSAPP_OPTION_UPDATE,
	MNU_JAVAAMSAPP_OPTION_PERMISSIONS,
	MNU_JAVAAMSAPP_OPTION_INFORMATION,
	MNU_JAVAAMSAPP_OPTION_MEMORYSTATUS,
	MNU_JAVAAMSAPP_OPTION_OPEN,
};

enum
{
	MNU_JAVAAMSAPP_RADIO_ALLOW = 0,
	MNU_JAVAAMSAPP_RADIO_BLANKET,
	MNU_JAVAAMSAPP_RADIO_BLANKET_GRANTED,
	MNU_JAVAAMSAPP_RADIO_SESSION,
	MNU_JAVAAMSAPP_RADIO_ONESHOT,
	MNU_JAVAAMSAPP_RADIO_DENY_SESSION,
	MNU_JAVAAMSAPP_RADIO_DENY,
	MNU_JAVAAMSAPP_RADIO_USER_DENIED,
	MNU_JAVAAMSAPP_RADIO_NEVER,
};

enum
{
	MNU_JAVAAMSAPP_PERMISSION_NETWORK_ACCESS = 0,
	MNU_JAVAAMSAPP_PERMISSION_MULTIMEDIA_RECORDING,
	MNU_JAVAAMSAPP_PERMISSION_WIRELESS_MESSAGING,
	MNU_JAVAAMSAPP_PERMISSION_APPLICATION_AUTO_INVOCATION,
	MNU_JAVAAMSAPP_PERMISSION_LOCAL_CONNECTIVITY,
	MNU_JAVAAMSAPP_PERMISSION_USER_DATA_READ,
	MNU_JAVAAMSAPP_PERMISSION_USER_DATA_WRITE,
};

enum
{
    MNU_JAVAAMSAPP_BACKGROUND_RESUME = 0,
    MNU_JAVAAMSAPP_BACKGROUND_STOP,
};

enum
{
    MNU_JAVAAMSAPP_STORAGE_PHONE = 0,
    MNU_JAVAAMSAPP_STORAGE_CARD,
    MNU_JAVAAMSAPP_STORAGE_CARD2,
    MNU_JAVAAMSAPP_MAX_NUM,
};

typedef enum
{
    JAVAAMS_WND_Home = WND_ID_APP_BASE,
    JAVAAMS_WND_ShowList,
	JAVAAMS_WND_Install,
    JAVAAMS_WND_OptionMenu,
	JAVAAMS_WND_Permission,
	JAVAAMS_WND_RadioList,
	JAVAAMS_WND_Information,
	//JAVAAMS_WND_BGRadioSelect
}JavaAmsWndId_e;

#endif //__MMI_JAVAAMSAPP_ID_H__

