ApBegin(RS, CLSID_SOHUUPDATERAPP)
    WndBegin(SOHU_UPDATER_WND_MAIN)
        WdgBegin(CLSID_VTMMENU, MainMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SOGO_INPUT_SETTINGS, WDG_MENU_TYPE_NUMERIC, WDG_MENU_ITEM_TYPE_IMAGE_TEXT, WDG_MENU_CHECK_STYLE_NONE, 3, 0, 0})
            VtmCreateMenuDataRC(3, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_SKIN_MANAGER}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SKIN_MANAGER}}, {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_LIB_UPDATE}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_LIB_UPDATE}}, {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_UPDATE_SETTING}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_UPDATE_SETTINGS}}})
        WdgEnd(CLSID_VTMMENU, MainMenu)    
    WndEnd(SOHU_UPDATER_WND_MAIN)
    
    WndBegin(SOHU_UPDATER_WND_SKIN_MANAGER)
        WdgBegin(CLSID_VTMMENU, SkinMgrMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SKIN_MANAGER, WDG_MENU_TYPE_NUMERIC, WDG_MENU_ITEM_TYPE_IMAGE_TEXT, WDG_MENU_CHECK_STYLE_NONE, 2, 0, 0})
            VtmCreateMenuDataRC(2, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_SKIN_SELECTION}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SKIN_SELECTION}}, {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_MORE_SKIN}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_MORE_SKIN}}})
        WdgEnd(CLSID_VTMMENU, SkinMgrMenu)    
    WndEnd(SOHU_UPDATER_WND_SKIN_MANAGER)   

    WndBegin(SOHU_UPDATER_WND_CONNECT_REMIND)
        WndSetTitleRC(IMG_NULL_ID,TXT_LIL_N_SOHUUPDATER_CONNECT_PROMPT)
        WndSetAllSoftkeyRC({SK_YES, SK_NONE, SK_NO})
        
        WdgBegin(CLSID_TEXTWIDGET,pRmdTextWdg)
            WdgTextCreateForWndRC({{10,MAIN_TITLE_HEIGHT+18},{MAIN_DEFVIEW_WIDTH-10,MAIN_DEFVIEW_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_SOHUUPDATER_CONNECT_REMIND)
            WdgTextSetLayoutFlagRC((u32)LAYOUT_MULTILINE)
        WdgEnd(CLSID_TEXTWIDGET,pRmdTextWdg)
    WndEnd(SOHU_UPDATER_WND_CONNECT_REMIND)   

    WndBegin(SOHU_UPDATER_WND_SKIN_SELECTION)
        WdgBegin(CLSID_VTMMENU, SkinSelectMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SKIN_SELECTION, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_TEXT, WDG_MENU_CHECK_STYLE_RADIO, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU, SkinSelectMenu)
    WndEnd(SOHU_UPDATER_WND_SKIN_SELECTION)   
    
    WndBegin(SOHU_UPDATER_WND_SKIN_DOWNLOAD)
        WdgBegin(CLSID_VTMMENU, SkinDownloadMenu)
						VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SKIN_DOWNLOAD, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGE_TEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU, SkinDownloadMenu)
    WndEnd(SOHU_UPDATER_WND_SKIN_DOWNLOAD)   
                    
    WndBegin(SOHU_UPDATER_WND_SKIN_OPTION)
        WndSetAllSoftkeyRC({SK_SELECT, SK_OK, SK_CANCEL})
        WdgBegin(CLSID_VTMOPTIONMENU, SkinOptMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 3})
            VtmCreateOptionMenuDataRC(3, { \
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_SOHU_VIEW}, TXT_LSK_N_VIEW},	\
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_SOHU_SET}, TXT_LTL_N_SOHUUPDATER_ENABLE},	\
								{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_SOHU_DELETE}, TXT_LSK_N_DELETE}})
        WdgEnd(CLSID_VTMOPTIONMENU, SkinOptMenu)
    WndEnd(SOHU_UPDATER_WND_SKIN_OPTION)  
            
    WndBegin(SOHU_UPDATER_WND_SETTINGS)
        WdgBegin(CLSID_VTMMENU, SettingsMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_UPDATE_SETTINGS, WDG_MENU_TYPE_NUMERIC, WDG_MENU_ITEM_TYPE_IMAGE_TEXT, WDG_MENU_CHECK_STYLE_NONE, 2, 0, 0})
            VtmCreateMenuDataRC(2, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_SYSTEM_UPDATE_SETTING}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SYSTEM_UPDATE_SETTING}}, {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SOHU_AUTO_UPDATE_SETTING}, {IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_AUTO_UPDATE_SETTING}}})
        WdgEnd(CLSID_VTMMENU, SettingsMenu)    
    WndEnd(SOHU_UPDATER_WND_SETTINGS) 
    
    WndBegin(SOHU_UPDATER_WND_SYS_UPDATE_SETTING)
        WdgBegin(CLSID_VTMMENU, SysUpdateMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_SYSTEM_UPDATE_SETTING, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU, SysUpdateMenu)
    WndEnd(SOHU_UPDATER_WND_SYS_UPDATE_SETTING)     
    
    WndBegin(SOHU_UPDATER_WND_RADIO_MENU)
        WdgBegin(CLSID_VTMPOPUPSELECT, tDynamicMenuData)
            VtmCreatePopUpSelectRC({NULL, WDG_MENU_ITEM_TYPE_TEXT, WDG_MENU_CHECK_STYLE_RADIO, 0, 0, 0})
        WdgEnd(CLSID_VTMPOPUPSELECT, tDynamicMenuData)
    WndEnd(SOHU_UPDATER_WND_RADIO_MENU)
    
    WndBegin(SOHU_UPDATER_WND_AUTO_UPDATE_SETTING)
        WndSetAllSoftkeyRC({SK_SAVE, SK_OK, SK_CANCEL})  
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_AUTO_UPDATE_SETTING})
        WdgBegin(CLSID_DOUBLE_TEXT_WIDGET, FrequencyDoubleTextWidget)
            WdgDoubleItemCreateForWndRC({{0,0}, {0,0}, DOUBLEITEM_STYLE_DOUBLE_TEXT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_SOHUUPDATER_LIB_UPDATE_FREQUENCY, TXT_NULL_ID})
        WdgEnd(CLSID_DOUBLE_TEXT_WIDGET, FrequencyDoubleTextWidget)
        WdgBegin(CLSID_TEXT_TIME_WIDGET, TimeTextTimeWidget)
            WdgDoubleItemCreateForWndRC({{0,0}, {0,0}, DOUBLEITEM_STYLE_TEXT_TIME})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_SOHUUPDATER_LIB_UPDATE_TIME, {0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_TIME_WIDGET, TimeTextTimeWidget)
    WndEnd(SOHU_UPDATER_WND_AUTO_UPDATE_SETTING)  

    WndBegin(SOHU_UPDATER_WND_RADIO_MENU_FREQ)
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_SOHUUPDATER_LIB_UPDATE_FREQUENCY})
        WdgBegin(CLSID_VTMPOPUPSELECT, tStaticMenuData)
            VtmCreatePopUpSelectRC({NULL, WDG_MENU_ITEM_TYPE_TEXT, WDG_MENU_CHECK_STYLE_RADIO, 5, 0, 0})
            VtmCreatePopUpSelectDataRC(5, {{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_BACK}, SOHU_FREQUENCY_DAILY}, TXT_LIL_N_SOHUUPDATER_FREQ_DAILY}, 
            								{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_BACK}, SOHU_FREQUENCY_WEEKLY}, TXT_LIL_N_SOHUUPDATER_FREQ_WEEKLY},
            								{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_BACK}, SOHU_FREQUENCY_HALFMONTHLY}, TXT_LIL_N_SOHUUPDATER_FREQ_HALFMONTHLY},
            								{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_BACK}, SOHU_FREQUENCY_MONTHLY}, TXT_LIL_N_SOHUUPDATER_FREQ_MONTHLY},
            								{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_BACK}, SOHU_FREQUENCY_NEVER}, TXT_LIL_N_SOHUUPDATER_FREQ_NEVER}})
        WdgEnd(CLSID_VTMPOPUPSELECT, tStaticMenuData)
    WndEnd(SOHU_UPDATER_WND_RADIO_MENU_FREQ)

ApEnd(RS, CLSID_SOHUUPDATERAPP)

