ApBegin(RS,CLSID_SOKOBANAPP)
    WndBegin(SOKOBAN_WND_COMMON)
        RSCustomize(u16, nMaxX, SOKOBAN_MAX_X)
        RSCustomize(u16, nMaxY, SOKOBAN_MAX_Y)
		RSCustomize(u16, nOffsetY, SOKOBAN_OFFSET_Y)
		RSCustomize(u16,nImgSize,SOKOBAN_IMG_SIZE)
		RSCustomize(u16,nImgIncDecSize,SOKOBAN_IMG_INC_DEC_SIZE)
		RSCustomize(u16,nColNum,SOKOBAN_COL_NUM)
		RSCustomize(u16,nSKLeftX1,SOKOBAN_SK_LEFT_X1)
		RSCustomize(u16,nSKLeftX2,SOKOBAN_SK_LEFT_X2)
		RSCustomize(u16,nSKMiddleX1,SOKOBAN_SK_MIDDLE_X1)
		RSCustomize(u16,nSKMiddleX2,SOKOBAN_SK_MIDDLE_X2) 
		RSCustomize(u16,nSKRightX1,SOKOBAN_SK_RIGHT_X1)
		RSCustomize(u16,nSKRightX2,SOKOBAN_SK_RIGHT_X2)
		RSCustomize(u16,nSKY1,SOKOBAN_SOFTKEY_Y1)
		RSCustomize(u16,nSKY2,SOKOBAN_SOFTKEY_Y2)
		RSCustomize(u16,nDecX1,SOKOBAN_DEC_X1)
		RSCustomize(u16,nDecX2,SOKOBAN_DEC_X2)
		RSCustomize(u16,nIncDecY1,SOKOBAN_INC_DEC_Y1)
		RSCustomize(u16,nIncDecY2,SOKOBAN_INC_DEC_Y2)    
		RSCustomize(u16,nIncX1,SOKOBAN_INC_X1)
		RSCustomize(u16,nIncX2,SOKOBAN_INC_X2)
		RSCustomize(u16,nNumX,SOKOBAN_NUM_X)
		RSCustomize(u16,nNumY,SOKOBAN_NUM_Y)
		RSCustomize(u16,nTitleY,SOKOBAN_TITLE_Y)         

		RSCustomize(u32,nOptionBGColor,SOKOBAN_OPTION_BG_COLOR)       
		RSCustomize(u32,nOptionTextOutlineClr,SOKOBAN_OPTION_TEXT_OUTLINE_CLR)
		RSCustomize(u32,nOptionTextOptionFontCat,SOKOBAN_OPTION_TEXT_OPTION_FONT_CAT)       
		RSCustomize(u32,nOptionTextOptionFontType,SOKOBAN_OPTION_TEXT_OPTION_FONT_TYPE)     
		RSCustomize(u32,nOptionTextNOFontCat,SOKOBAN_OPTION_TEXT_NO_FONT_CAT)       
		RSCustomize(u32,nOptionTextNOFontType,SOKOBAN_OPTION_TEXT_NO_FONT_TYPE) 
		RSCustomize(u32,nOptionTextBackFontCat,SOKOBAN_OPTION_TEXT_BACK_FONT_CAT)       
		RSCustomize(u32,nOptionTextBackFontType,SOKOBAN_OPTION_TEXT_BACK_FONT_TYPE)    

		RSCustomize(u32,nPlayBGColor,SOKOBAN_PLAY_BG_COLOR)       
		RSCustomize(u32,nPlayTextOutlineClr,SOKOBAN_PLAY_TEXT_OUTLINE_CLR) 
		RSCustomize(u32,nPlayTextOptionFontCat,SOKOBAN_PLAY_TEXT_OPTION_FONT_CAT)       
		RSCustomize(u32,nPlayTextOptionFontType,SOKOBAN_PLAY_TEXT_OPTION_FONT_TYPE)      
		RSCustomize(u32,nPlayTextNOFontCat,SOKOBAN_PLAY_TEXT_NO_FONT_CAT)       
		RSCustomize(u32,nPlayTextNOFontType,SOKOBAN_PLAY_TEXT_NO_FONT_TYPE)    
		RSCustomize(u32,nPlayTextExitFontCat,SOKOBAN_PLAY_TEXT_EXIT_FONT_CAT)       
		RSCustomize(u32,nPlayTextExitFontType,SOKOBAN_PLAY_TEXT_EXIT_FONT_TYPE)    
		RSCustomize(u32,nPlayTextResetFontCat,SOKOBAN_PLAY_TEXT_RESET_FONT_CAT)       
		RSCustomize(u32,nPlayTextResetFontType,SOKOBAN_PLAY_TEXT_RESET_FONT_TYPE)   

		RSCustomize(u32,nPlayTextNOID,TXT_LIL_N_SOKOBAN_PLAY_NO)  
		RSCustomize(u32,nPlayTextResetID,TXT_LIL_N_SOKOBAN_PLAY_RESET)  
		RSCustomize(u32,nPlayTextOptionID,TXT_LIL_N_SOKOBAN_PLAY_OPTION)  
		RSCustomize(u32,nPlayTextExitID,TXT_LIL_N_SOKOBAN_PLAY_EXIT)  
		RSCustomize(u32,nOptionTextNOID,TXT_LIL_N_SOKOBAN_OPTION_NO)  
		RSCustomize(u32,nOptionTextOption,TXT_LIL_N_SOKOBAN_OPTION)  
		RSCustomize(u32,nOptionTextExit,TXT_LIL_N_SOKOBAN_OPTION_BACK)  

		RSCustomize(u32,nImgIDMap,SOKOBAN_IMG_MAP)  
		RSCustomize(u32,nImgIDUD,SOKOBAN_IMG_UD)  
		
    WndEnd(SOKOBAN_WND_COMMON)
ApEnd(RS,CLSID_SOKOBANAPP)
