/**
 * @file mmi_messageeditorapp_view_id.h
 *
 * @version $Id: mmi_sea_view_id.h 29726 2009-04-30 13:12:39Z chunmin.lin $
 */
#ifndef __MMI_MESSAGEEDITORAPP_VIEW_ID_H__
#define __MMI_MESSAGEEDITORAPP_VIEW_ID_H__

#include "mmi_view_id_range.h"
#include "mmi_messageeditorapp.h"

enum
{
/* View ID start */
	SMS_EDITOR_VIEW = MMI_VIEW_ID_AP_BEGIN,
	MMS_EDITOR_VIEW,

	RECIPIENT_VIEW,
	SEA_DUALSIM_MENU_VIEW,
    SEA_MMS_RADIOLIST_VIEW,
    SEA_MMS_SETTINGLIST_VIEW,
    SEA_MMS_NUMBER_EDITOR_VIEW,
    SEA_MMS_OBJECT_LIST_VIEW,
    SMS_VIEW_END = SEA_MMS_OBJECT_LIST_VIEW,

    SEA_OPTION_MENU_SMS_EDITOR_MODEL,
    SEA_OPTION_MENU_SMS_INSERT_L2_MODEL,
    SEA_OPTION_MENU_MMS_EDITOR_MODEL,
    SEA_OPTION_MENU_MMS_INSERT_L2_MODEL,
    SEA_OPTION_MENU_MMS_INSERT_OBJECT_L2_MODEL,
    SEA_OPTION_MENU_MMS_INSERT_SLIDE_L2_MODEL,
    SEA_OPTION_MENU_MMS_REMOVE_OBJECT_L2_MODEL,
    SEA_OPTION_MENU_RECIPIENT_MODEL,   
    SEA_OPTION_MENU_FULL_EDITOR_MODEL,
    SEA_OPTION_MENU_OBJECT_LIST_MODEL,
    
    SEA_RADIOLIST_DURATION_MODEL,
    SEA_RADIOLIST_TEXTLOCATION_MODEL,
    SEA_RADIOLIST_IMAGESIZE_MODEL,
    SEA_RADIOLIST_STATUSREPORT_MODEL,
    SEA_RADIOLIST_VALIDITYPERIOD_MODEL,
	SEA_OPTION_MENU_SEND_OPTION_L2_MODEL,
	SEA_OPTION_MENU_MMS_ADD_RECIPIENT_L2_MODEL,
    
    
/* View ID end */
};

enum
{
/* Widget ID start */
	EDITOR_TITLEWIDGET = 1,
	EDITOR_OPTION_MENU,
	EDITOR_SCROLLBARWDG,
	EDITOR_INPUTWIDGET,
	
	RECIPIENT_TITLEWIDGET,
    RECIPIENT_PROPCONTAINER,
    //RECIPIENT_ABSCONTAINER,
	RECIPIENT_MENUWIDGET,
	RECIPIENT_EDITOR_ABSCONTAINER,
	RECIPIENT_EDITOR_BG,
	RECIPIENT_EDITOR_IMG,
	RECIPIENT_INPUTWIDGET,
	RECIPIENT_OPTION_MENU,
	
    
	SEA_DUALSIM_MENU_TITLE,
	SEA_DUALSIM_MENU_MENUWIDGET,
	
    MMS_EDITOR_MAINCONTAINER,

    MMS_EDITOR_TITLE_CONTAINER, // abs container
    MMS_TITLE_TEXTWIDGET,
    MMS_SIZE_TEXTWIDGET,
    MMS_EDITOR_TITLEWIDGET,
    
    MMS_PAGE_PICKCONTAINER,
    MMS_PAGESWITCH_LEFT_ARROW_BUTTONWDG,
    MMS_PAGESWITCH_RIGHT_ARROW_BUTTONWDG,
    MMS_PAGESWITCH_PAGE_TEXTWDG,
    
    MMS_EDITOR_AREA_SCROLLBARWDG,
    MMS_EDITOR_AREA_VIEWPOINTWDG,
    MMS_EDITOR_AREA_PROPCONTAINER,
    
    MMS_TO_DISPLAY_WDG, /*from this until MMS_SUBJECT_DISPLAY_WDG don't insert other widget id , it is used for one loop*/
  
    MMS_CC_DISPLAY_WDG,
 
    MMS_BCC_DISPLAY_WDG,

    MMS_SUBJECT_DISPLAY_WDG, /***********************/

    MMS_PROPCONTAINER_ICON_LIST,
    MMS_AUDIO_ICON_IMAGEWDG,
    MMS_VIDEO_ICON_IMAGEWDG,
    MMS_ATTACHMENT_ICON_IMAGEWDG,
    
    MMS_EDITOR_INPUTWIDGET,  
    MMS_EDITOR_SLIDE_IMAGE_CONTNR,
    MMS_EDITOR_SLIDE_IMAGE_IMGWDG,
    
    SEA_MMS_RADIOLIST_TITLE,
    SEA_MMS_RADIOLIST_MENUWDG,

    SEA_MMS_OBJECT_LIST_MENUWDG,
    SEA_MMS_SETTINGLIST_MENUWDG,

/* Widget ID end */
};
enum e_SEA_MENU
{
/* Binary ID start */

    MNU_SEA_MASTERSIM,
    MNU_SEA_SLAVESIM,

/* Binary ID end */
};
#endif /* __MMI_MESSAGEEDITORAPP_VIEW_ID_H__ */
