ApBegin(RS,CLSID_MSA)
 	WndBegin(MSA_WND_MAIN_MENU_VIEW)
        WdgBegin(CLSID_VTMMENU,MainMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SMS_SETTINGS,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(8, { MNU_MSG_SET_SERVICE_CENTER_NO, TXT_LIL_N_BEARER_MODE, TXT_LIL_N_VALIDITY_PERIOD, TXT_LIL_N_MESSAGE_TYPE, TXT_LIL_N_STATUS_REPORT, TXT_LIL_N_DIRECT_REPLY, 
            TXT_LIL_N_INBOX_LOCATION,TXT_LIL_N_BACKUP_SENT})
            WdgDynamicMenuItemInfRC(8, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_SERVICE_CENTER_NO, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_BEARER_MODE, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_VALIDITY_PERIOD, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_MESSAGE_TYPE, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_STATUS_REPORT, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_DIRECT_REPLY, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_INBOX_LOCATION, 0},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_MSG_SET_BACKUP_SENT_MSGS, 0}
                              })
        WdgEnd(CLSID_VTMMENU,MainMenu)
	WndEnd(MSA_WND_MAIN_MENU_VIEW)

	WndBegin(MSA_WND_DUALSIMSELECT_MENU_VIEW)    
	   WdgBegin(CLSID_VTMSIMSELECTION,DualSim)
	        VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_SMS_SETTINGS})
	    WdgEnd(CLSID_VTMSIMSELECTION,DualSim)    
	WndEnd(MSA_WND_DUALSIMSELECT_MENU_VIEW)

	WndBegin(MSA_WND_POPUP_EDITOR_VIEW)
		WdgBegin(CLSID_VTMPOPUPINPUT,PopupEditor)
			VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_LTL_N_SC_NUMBER,MAE_INPUTMODE_DIALING})
		WdgEnd(CLSID_VTMPOPUPINPUT,PopupEditor)        
	WndEnd(MSA_WND_POPUP_EDITOR_VIEW)

    WndBegin(MSA_WND_POPUP_RADIOLIST_VIEW)
        WdgBegin(CLSID_VTMMENU,PopupRadioList)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,PopupRadioList)
    WndEnd(MSA_WND_POPUP_RADIOLIST_VIEW)	
                    
ApEnd(RS,CLSID_MSA)


