/**
* @file mmi_venapps.h
*
* @author Steve.Lee
*
* @version $Id: mmi_venapps.h 37151 2009-08-04 14:04:08Z code.lin $
*
*/

#if defined VEN_DECLARE_FUNC

#ifdef MAKE_APP
#undef MAKE_APP
#endif

#define MAKE_APP(_ApId, _ClsId, _MediaAppId, _pfnInit, _pfnDispMainView, _pfnTerminate, _bSbVis, _bSkVis, _eAttribute) \
    MAE_Ret _pfnInit(VendorAppData_t *pThis); \
    MAE_Ret _pfnDispMainView(VenMainViewData_t* pData); \
    MAE_Ret _pfnTerminate(VendorAppData_t *pThis);

#elif defined VEN_TABLEITEM

	#ifdef MAKE_APP
	#undef MAKE_APP
	#endif

	#define MAKE_APP(_ApId, _ClsId, _MediaAppId, _pfnInit, _pfnDispMainView, _pfnTerminate, _bSbVis, _bSkVis, _eAttribute) \
		{_ApId, _ClsId, _MediaAppId, {_pfnInit, _pfnDispMainView, _pfnTerminate}, _bSbVis, _bSkVis, _eAttribute},

#endif

#ifdef __WAP_MMI__
MAKE_APP(VEN_WAP,  CLSID_WAPAPP, RES_MGR_APP_ID__INVALID, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif // __WAP_MMI__

#if defined(__JAVA_MMI__) || defined(__DALVIK__)

#if defined(__JAVA_OAKMONT__) //only Java OAKNONT customer support  background music non suspend attribute
#ifdef __JAVA_OAKMONT_LOW_MEMORY__
MAKE_APP(VEN_JAVA, CLSID_JAVAAPP, RES_MGR_APP_ID__JAVA, Java_Init, Common_DispDefaultView, Java_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP))
#else
#ifdef __APP_MMI_BACKGROUND_EXECUTION__
MAKE_APP(VEN_JAVA, CLSID_JAVAAPP, RES_MGR_APP_ID__JAVA, Java_Init, Common_DispDefaultView, Java_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#else
MAKE_APP(VEN_JAVA, CLSID_JAVAAPP, RES_MGR_APP_ID__JAVA, Java_Init, Common_DispDefaultView, Java_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#endif //__APP_MMI_BACKGROUND_EXECUTION__
#endif
#else //__JAVA_OAKMONT__
#if defined(__APP_MMI_BACKGROUND_EXECUTION__) &&  !defined(__NCC_3RD_JAVA_PORTING_LAYER__)
MAKE_APP(VEN_JAVA, CLSID_JAVAAPP, RES_MGR_APP_ID__JAVA, Java_Init, Common_DispDefaultView, Java_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND))
#else
MAKE_APP(VEN_JAVA, CLSID_JAVAAPP, RES_MGR_APP_ID__JAVA, Java_Init, Common_DispDefaultView, Java_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP))
#endif //__APP_MMI_BACKGROUND_EXECUTION__
#endif //__JAVA_OAKMONT__
#endif // __JAVA_MMI__ || __DALVIK__

#ifdef __TENCENT_MCARE__
#ifdef __TENCENT_MCARE_QXIN__
#ifdef __NAND__ //no need T_CARD for NAND product
MAKE_APP(VEN_TENCENT_MCARE, CLSID_TENCENT_MCARE_QXIN, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_USB_PHB | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND| VENDORAPP_ATTR_USB_INUSED | VENDORAPP_ATTR_USE_ENDKEY | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#else
MAKE_APP(VEN_TENCENT_MCARE, CLSID_TENCENT_MCARE_QXIN, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_USB_PHB | VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND| VENDORAPP_ATTR_USB_INUSED | VENDORAPP_ATTR_USE_ENDKEY | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#endif //__NAND__
#else
#ifdef __NAND__ //no need T_CARD for NAND product
MAKE_APP(VEN_TENCENT_MCARE, CLSID_TENCENT_MCARE, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND| VENDORAPP_ATTR_USB_INUSED | VENDORAPP_ATTR_USE_ENDKEY | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#else
MAKE_APP(VEN_TENCENT_MCARE, CLSID_TENCENT_MCARE, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND| VENDORAPP_ATTR_USB_INUSED | VENDORAPP_ATTR_USE_ENDKEY | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#endif //__NAND__
#endif
#endif //__TENCENT_MCARE__

#ifdef __FAKE_VENDOR__
MAKE_APP(VEN_FAKE_VENDOR, CLSID_FAKE_VENDOR_APP, RES_MGR_APP_ID__SDK5, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif // __FAKE_VENDOR__

#ifdef __ZYUE_ENGINE__
MAKE_APP(VEN_3RD_ZHANGYUE_EBOOK, CLSID_3RD_ZHANGYUE_EBOOK, RES_MGR_APP_ID__SDK2, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif

#ifdef __SKYENGINE__
#ifdef __APP_MMI_BACKGROUND_EXECUTION__
MAKE_APP(VEN_SKY_ENGINE, CLSID_SKY_ENGINE_QQ_APP, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_INTERACTIVE_BACKGROUND| VENDORAPP_ATTR_USB_INUSED))
#else
MAKE_APP(VEN_SKY_ENGINE, CLSID_SKY_ENGINE_QQ_APP, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_USB_INUSED))
#endif
MAKE_APP(VEN_SKY_ENGINE, CLSID_SKY_ENGINE_GAME_APP, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_USB_INUSED))
#endif /* __SKYENGINE__ */

#ifdef __ZMOL__
MAKE_APP(VEN_ZMOL, CLSID_ZMOL_APP, RES_MGR_APP_ID__SDK1, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INTERACTIVE_STOP | VENDORAPP_ATTR_EXIT_WITH_COMFIRM | VENDORAPP_ATTR_USB_INUSED |VENDORAPP_ATTR_INSERT_SIM_CARD))
#endif/* __ZMOL__ */

#ifdef __SXMENGINE__
MAKE_APP(VEN_SXM_ENGINE, CLSID_SXM_VCHAT, RES_MGR_APP_ID__SDK2, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INSERT_SIM_CARD | VENDORAPP_ATTR_INTERACTIVE_STOP))
MAKE_APP(VEN_SXM_ENGINE, CLSID_SXM_BOOK,  RES_MGR_APP_ID__SDK2, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INSERT_SIM_CARD | VENDORAPP_ATTR_INTERACTIVE_STOP))
MAKE_APP(VEN_SXM_ENGINE, CLSID_SXM_GAME,  RES_MGR_APP_ID__SDK2, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INSERT_SIM_CARD | VENDORAPP_ATTR_INTERACTIVE_STOP))
#endif /* __SKYENGINE__ */

#ifdef __TTS__
MAKE_APP(VEN_TTS, CLSID_TTS, RES_MGR_APP_ID__SDK3, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDERAPP_ATTR_NON_SUSPEND_BACKGROUND_MUSIC))
#endif /* __TTS__ */

#ifdef __SRE__
MAKE_APP(VEN_SRE, CLSID_SRE, RES_MGR_APP_ID__VENDOR, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif /*__SRE__*/

#ifdef __MMI_GTSBOX__
MAKE_APP(VEN_GTSBOX_APP, CLSID_GTSBOX_APP, RES_MGR_APP_ID__SDK4, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_DATA_LINK | VENDORAPP_ATTR_INSERT_SIM_CARD | VENDORAPP_ATTR_EXTERNAL_MEM_CARD))
#endif /* __MMI_GTSBOX__ */

#ifdef __SDK_MMI_VENDOR_ENTRY__
MAKE_APP(VEN_SOCKET_TEST1, CLSID_SOCKET_TEST1, RES_MGR_APP_ID__SDK4, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
MAKE_APP(VEN_SOCKET_TEST2, CLSID_SOCKET_TEST2, RES_MGR_APP_ID__SDK5, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif/* __SDK_MMI_VENDOR_ENTRY__ */

#if (defined __SDK_MMI_VENDOR_ENTRY__) && (!(defined __SDK_MMI_TEST__))	// For vendor ap test
MAKE_APP(VEN_DEFAULT, CLSID_VENDORAPP, RES_MGR_APP_ID__VENDOR, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_INTERACTIVE_STOP)
#else
MAKE_APP(VEN_DEFAULT, CLSID_VENDORAPP, RES_MGR_APP_ID__VENDOR, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, VENDORAPP_ATTR_NONE)
#endif

#ifdef __MMI_KMX_TT__
MAKE_APP(VEN_KMX_TT, CLSID_KMX_TT_APP, RES_MGR_APP_ID__SDK3, Common_Init, Common_DispDefaultView, Common_Terminate, FALSE, FALSE, (VENDORAPP_ATTR_EXTERNAL_MEM_CARD | VENDORAPP_ATTR_DATA_LINK))
#endif

