#ifndef __MMI_MESSAGECENTERAPP_ID_H__
#define __MMI_MESSAGECENTERAPP_ID_H__

typedef enum MCAWndId_e_
{
    MCA_WND_LISTMENU = WND_ID_APP_BASE,
    MCA_WND_MAINMENU,
    MCA_WND_NEWMSGMENU,
    MCA_WND_OPTMENU,
    MCA_WND_SETTINGMENU,
	MCA_WND_MEMSTATUS,
	MCA_WND_DUALSIMMENU,
	MCA_WND_TEMPLATEMENU,
	MCA_WND_VIEWMSGDETAIL,
	MCA_WND_LISTMENU_BOX_TAB_VIEW,
	MCA_WND_LISTMENU_NORMAL_VIEW,
	MCA_WND_LISTMENU_DUALSIM_TAB_VIEW,
	MCA_WND_LISTMENU_ONESIM_TAB_VIEW,

	MCA_WND_SETTINGMENU_BLACKLIST,
	MCA_WND_SETTINGMENU_BLACKLIST_NUMBER,
	MCA_WND_OPTMENU_BLACKLIST_NUMBER,
	MCA_WND_OPTMENU_BLACKLIST_ADD_NEW,

	MCA_WND_SEARCHBOXMENU,
	MCA_WND_SEARCHLISTVIEW,

    MCA_WND_CHATLISTMENU,
    MCA_WND_CHATLISTOPTMENU,
    MCA_WND_CHATITEMMENU,
    MCA_WND_CHATITEMOPTMENU,
#ifdef __SMS_MMI_SIM_MESSAGE_BOX_SUPPORT__
    MCA_WND_SIMMSGBOXMENU,
	MCA_WND_MAINBOXMENU,
	MCA_WND_NEW_MSG_BOX_SELECT_MENU,
#endif


} MCAWndId_e;

typedef enum //MCA_MSG_MEMORY_STATUS_VIEW_enum
{
	MCA_MEM_STATUS_VIEW_BEGIN=APP_WDG_START,
    MCA_MEM_STATUS_SCROLLBAR,
    MCA_MEM_STATUS_VIEWPORT,
    MCA_MEM_STATUS_MAIN_CONTAINER,
    MCA_MEM_STATUS_PHONE_MSG_SMS_TXT,
    MCA_MEM_STATUS_PHONE_MSG_MMS_TXT,
    MCA_MEM_STATUS_PHONE_MESSAGE_CB_TXT,
    MCA_MEM_STATUS_PHONE_MESSAGE_WAP_TXT,
    MCA_MEM_STATUS_SIM_MSG_TXT,
    MCA_MEM_STATUS_SIM_MSG_SINGLE_TXT,
    MCA_MEM_STATUS_SIM_MSG_MASTER_TXT,
    MCA_MEM_STATUS_SIM_MSG_SLAVE_TXT,
    MCA_MEM_STATUS_MOBILE_MEM_TXT,
    MCA_MEM_STATUS_MOBILE_USED_TXT,
    MCA_MEM_STATUS_MOBILE_AVAILABLE_TXT,
    MCA_MEM_STATUS_MOBILE_TOTAL_TXT,
    MCA_MEM_STATUS_MMS_MEM_TXT,
    MCA_MEM_STATUS_MMS_USED_TXT,
    MCA_MEM_STATUS_MMS_AVAILABLE_TXT,
    MCA_MEM_STATUS_MMS_TOTAL_TXT,
    MCA_MEM_STATUS_BUTTON_ABSCONTAINER,
    MCA_MEM_STATUS_BUTTON_OPTION,
    MCA_MEM_STATUS_BUTTON_REPLY,
    MCA_MEM_STATUS_BUTTON_DELETE,
    MCA_MEM_STATUS_BUTTON_BACK,
    MCA_MEM_STATUS_VIEW_END
} McaMemStatusView_e;

typedef enum
{
	MNU_MSG_MCA_MESSAGES = 0,
	MNU_MSG_MCA_CREATE_NEW,
	MNU_MSG_MCA_SMS,
	MNU_MSG_MCA_MMS,
	MNU_MSG_MCA_INBOX,
	MNU_MSG_MCA_OUTBOX,
	MNU_MSG_MCA_SENT_BOX,
	MNU_MSG_MCA_DRAFT_BOX,
	MNU_MSG_MCA_PRIVATE_FOLDER,
	MNU_MSG_MCA_VOICE_MAIL,
#ifdef __SMS_MMI_SIM_MESSAGE_BOX_SUPPORT__
	MNU_MSG_MCA_MASTER_SIM,
	MNU_MSG_MCA_SLAVE_SIM,
	MNU_MSG_MCA_NEW_SELECT_MASTER_SIM,
	MNU_MSG_MCA_NEW_SELECT_SLAVE_SIM,
	MNU_MSG_MCA_NEW_SELECT_MMS,
#endif
	MNU_MSG_MTA_TEMPLATE,
	MNU_MSG_MTA_TEXT,
	MNU_MSG_MTA_MULTIMEDIA,
	MNU_MSG_SET_SETTINGS,
	MNU_MSG_SET_SMS,
	MNU_MSG_SET_CELL_BROADCAST,
}MCAMenuId_e;

enum
{
    eSearchList_PROPCONTAINER = APP_WDG_START,
	eSearchList_MENUWIDGET,
	eSearchList_TITLEWIDGET,
	eSearchList_ABSCONTAINER,
	eSearchList_BGIMGWDG,
	eSearchList_BUTTONWDG,
	eSearchList_INPUTWIDGET,
};
typedef u16 eSearchListWdgId;

#ifdef __MMI_SMS_CHAT__
enum
{
    eSMSChatItem_MAINPROPCONTAINER = APP_WDG_START,
	eSMSChatItem_VIEWPORTWIDGET,
	eSMSChatItem_TITLEWIDGET,
	eSMSChatItem_BGIMGWDG,
	eSMSChatItem_SCROLLBARWDG,
	eSMSChatItem_INPUTWIDGET,
	eSMSChatItem_INPUTBGIMGWDG,
	eSMSChatItem_INPUTABSCONTAINER,
	eSMSChatItem_PROPCONTAINER,
	eSMSChatItem_OLDERBTNABSCONTAINER,
	eSMSChatItem_OLDERBUTTON,
	eSMSChatItem_NEWERBTNABSCONTAINER,
	eSMSChatItem_NEWERBUTTON,

	eSMSChatItem_INCOMMINGABS,
	eSMSChatItem_INCOMMINGBG,
	eSMSChatItem_INCOMMINGBUTTON,
	eSMSChatItem_INCOMMINGBUBBLE,
	eSMSChatItem_INCOMMINGTIMETEXT,

	eSMSChatItem_DATEABS,
	eSMSChatItem_DATEBUBBLE,

	eSMSChatItem_SENTABS,
	eSMSChatItem_SENTBG,
	eSMSChatItem_SENTBUTTON,
	eSMSChatItem_SENTBUBBLE,
	eSMSChatItem_SENTTIMETEXT,
};
typedef u16 eChatItemWdgId;
#endif

#endif //__MMI_MESSAGECENTERAPP_ID_H__

