#include "mmi_cdwapapp_id.h"

ApBegin(RS,CLSID_CDWAPAPP)
    WndBegin(CDWAP_WND_MAINPAGELIST)
        WdgBegin(CLSID_VTMTABMENU,MainMenu)
            VtmCreateTabMenuRC({0,0,2})
            VtmCreateTabMenuDataRC(2,{{CDWAP_IMG_BOOKMARK_PRESSED,TXT_LIL_N_BOOKMARKS,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0},		{CDWAP_IMG_LOCALPAGE_UNPRESS,TXT_LIL_N_CDW_LOCAL_PAGE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0}})
        WdgEnd(CLSID_VTMTABMENU,MainMenu)
    WndEnd(CDWAP_WND_MAINPAGELIST)

    WndBegin(CDWAP_WND_FILE_MANAGE)
        WdgBegin(CLSID_VTMMENU,FileMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SEND_VIA,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,FileMenu)
    WndEnd(CDWAP_WND_FILE_MANAGE)

    WndBegin(CDWAP_WND_EDIT_BOOKMARK)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_CDW_ADD_BOOKMARK})
        WndSetAllSoftkeyRC( {SK_SAVE, SK_NONE, SK_BACK} )
        WdgBegin(CLSID_TEXT_INPUT_WIDGET,TextInputNameWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_INPUT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_CDW_NAME,TXT_NULL_ID})
            WdgInputSetShowBorderWhenLoseFocusRC((boolean)TRUE)
            WdgInputSetHandWritingEnableRC((boolean)FALSE)
        WdgEnd(CLSID_TEXT_INPUT_WIDGET,TextInputNameWdg)
        WdgBegin(CLSID_TEXT_INPUT_WIDGET,TextInputURLWdg)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_INPUT})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_CDW_ADDRESS,TXT_NULL_ID})
            WdgInputSetShowBorderWhenLoseFocusRC((boolean)TRUE)
            WdgInputSetCurrentInputModeRC((u32)MAE_INPUTMODE_MT_abc)
            WdgInputSetDisableSwitchInputModeRC((boolean)TRUE)
            WdgInputSetSmartInputOffRC(TRUE)
            WdgInputSetCurrentInputLanguageRC(MAE_LANG_ENGLISH)
            WdgInputSetHandWritingEnableRC(FALSE)
        WdgEnd(CLSID_TEXT_INPUT_WIDGET,TextInputURLWdg)
    WndEnd(CDWAP_WND_EDIT_BOOKMARK)

    WndBegin(CDWAP_WND_INPUT_URL)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_GOTO_URL})
        WdgBegin(CLSID_INPUTWIDGET,InputUrlEdit)
            WdgInputCreateForWndRC({{16,2+MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH-32,MAIN_LCD_ONELINE_HEIGHT},{TRUE, SKBOARD_ENABLE}})
            WdgInputSetShowBorderWhenLoseFocusRC((boolean)TRUE)
            WdgInputSetCurrentInputModeRC((u32)MAE_INPUTMODE_MT_abc)
            WdgInputSetDisableSwitchInputModeRC((boolean)TRUE)
        WdgEnd(CLSID_INPUTWIDGET,InputUrlEdit)

        WdgBegin(CLSID_MENUWIDGET,InputUrdMenu)
            WdgMenuCreateForWndRC({{0,CDWAPAPP_RS_URD_MENU_POS_Y+MAIN_TITLE_HEIGHT},{CDWAPAPP_MAINVIEW_WIDTH,CDWAPAPP_EDIT_H-2-MAIN_LCD_ONELINE_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgInputSetSmartInputOffRC(TRUE)
            WdgInputSetCurrentInputLanguageRC(MAE_LANG_ENGLISH)
        WdgEnd(CLSID_MENUWIDGET,InputUrdMenu)
    WndEnd(CDWAP_WND_INPUT_URL)

    WndBegin(CDWAP_WND_INPUT_URL_OPTION_MENU)
        WndSetAllSoftkeyRC( {SK_SELECT,SK_OK,SK_CANCEL} )
        WdgBegin(CLSID_VTMOPTIONMENU, tCdWapInputUrlEditOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,3})
            VtmCreateOptionMenuDataRC(3,
                {
                    {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_OPEN               },TXT_LSK_N_SELECT  },	\
                    {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_INPUT_URL_CLEAR    },TXT_OIL1_N_CLEAR    },	\
                    {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_INPUT_URL_CLEAR_ALL},TXT_OIL1_N_CLEAR_ALL}
                })
        WdgEnd(CLSID_VTMOPTIONMENU, tCdWapInputUrlEditOptionMenu)
    WndEnd(CDWAP_WND_INPUT_URL_OPTION_MENU)

    WndBegin(CDWAP_WND_SETTINGS)
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_CDW_EXPLORER_SET})
        WndSetAllSoftkeyRC({SK_SELECT, SK_NONE, SK_BACK} )
        WdgBegin(CLSID_TEXT_LINE2INFO_WIDGET, DoubleTextWdg)
            WdgDoubleItemCreateForWndRC({{0, MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH, CDWAPAPP_RS_SETTING_DBTXT_HEIGHT},DOUBLEITEM_STYLE_TEXT_LINE2INFO})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_CDW_LOAD_IMAGE,TXT_NULL_ID})
        WdgEnd(CLSID_TEXT_LINE2INFO_WIDGET, DoubleTextWdg)
        WdgBegin(CLSID_TEXT_LINE2INFO_WIDGET, FontSizeTextWdg)
            WdgDoubleItemCreateForWndRC({{0,CDWAPAPP_RS_SETTING_FONT_SIZE_POS_Y},{MAIN_LCD_WIDTH, CDWAPAPP_RS_SETTING_FONT_SIZE_HEIGHT},DOUBLEITEM_STYLE_TEXT_LINE2INFO})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_LIL_N_CDW_FONT_SIZE, TXT_NULL_ID})
        WdgEnd(CLSID_TEXT_LINE2INFO_WIDGET, FontSizeTextWdg)
        WdgBegin(CLSID_TEXT_LINE2INFO_WIDGET, DoubleStorageTypeTextWdg)
            WdgDoubleItemCreateForWndRC({{0,CDWAPAPP_RS_SETTING_DBSTORAGE_POS_Y},{MAIN_LCD_WIDTH, CDWAPAPP_RS_SETTING_DBSTORAGE_HEIGHT},DOUBLEITEM_STYLE_TEXT_LINE2INFO})
            WdgDoubleItemDBTextSetDataByIDRC({TXT_OIL1_N_STORAGE, TXT_NULL_ID})
        WdgEnd(CLSID_TEXT_LINE2INFO_WIDGET, DoubleStorageTypeTextWdg)
    WndEnd(CDWAP_WND_SETTINGS)

    WndBegin(CDWAP_WND_SETTINGS_RADIO_MENU_FONT_SIZE)
        WdgBegin(CLSID_VTMPOPUPSELECT,FontSizeWdg)
            VtmCreatePopUpSelectRC( {NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,5,0,0  } )
            VtmCreatePopUpSelectDataRC(5, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, CDWAPAPP_FONT_SIZE_SMALLEST}, TXT_LIL_N_CDW_FONT_SIZE_SMALLEST },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, CDWAPAPP_FONT_SIZE_SMALL}, TXT_LIL_N_CDW_FONT_SIZE_SMALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, CDWAPAPP_FONT_SIZE_NORMAL}, TXT_LIL_N_CDW_FONT_SIZE_NORMAL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, CDWAPAPP_FONT_SIZE_LARGE}, TXT_LIL_N_CDW_FONT_SIZE_LARGE },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, CDWAPAPP_FONT_SIZE_LARGEST}, TXT_LIL_N_CDW_FONT_SIZE_LARGEST}  } )
        WdgEnd(CLSID_VTMPOPUPSELECT,FontSizeWdg)
    WndEnd(CDWAP_WND_SETTINGS_RADIO_MENU_FONT_SIZE)

    WndBegin(CDWAP_WND_EXPLORER)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_OK, SK_BACK} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WndSetTitleRC({TOOLS_BLUETOOTH_IMG_SEARCH_ANIM,TXT_NULL_ID})
    WndEnd(CDWAP_WND_EXPLORER)

    WndBegin(CDWAP_WND_EDIT_FOLDER)
        WdgBegin(CLSID_VTMINPUT,FolderInput)
            VtmCreateInputRC({0,0,0,FALSE})

         	VTMWdgBegin (CLSID_INPUTWIDGET, INPUT_INPUT_WDG, VtmFolderInput)
                WdgInputSetMultilineRC(TRUE)
                WdgInputSetChineseInputOffRC(FALSE)
		    VTMWdgEnd (CLSID_INPUTWIDGET, INPUT_INPUT_WDG, VtmFolderInput)

        WdgEnd(CLSID_VTMINPUT,FolderInput)
    WndEnd(CDWAP_WND_EDIT_FOLDER)

    WndBegin(CDWAP_WND_VIEW_PAGE_IMAGE)
        WdgBegin(CLSID_VTMINPUT,PageInput)
            VtmCreateInputRC({0,0,0,FALSE})
        WdgEnd(CLSID_VTMINPUT,PageInput)
    WndEnd(CDWAP_WND_VIEW_PAGE_IMAGE)

    WndBegin(CDWAP_WND_SAVE_BOOKMARK_OR_PAGE)
        WdgBegin(CLSID_VTMINPUT,BookMarkInput)
            VtmCreateInputRC({0,0,0,FALSE})
        WdgEnd(CLSID_VTMINPUT,BookMarkInput)
    WndEnd(CDWAP_WND_SAVE_BOOKMARK_OR_PAGE)

    WndBegin(CDWAP_WND_DUALSIM)
        WdgBegin(CLSID_VTMSIMSELECTION,DualSim)
            VtmCreateSimSelectionRC({0,TXT_LIL_N_CDW_SIM_SELECTED})
        WdgEnd(CLSID_VTMSIMSELECTION,DualSim)
    WndEnd(CDWAP_WND_DUALSIM)

    WndBegin(CDWAP_WND_OPTION_MENU)
        WndSetAllSoftkeyRC( {SK_SELECT,SK_OK,SK_CANCEL} )

#ifdef __3G_RIL_MMI__
        WdgBegin(CLSID_VTMOPTIONMENU,OptMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,16})
            VtmCreateOptionMenuDataRC(16,\
                {{{MENUMODEL_ITEM_VISABLE                        ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_OPEN}              ,TXT_OIL1_N_CDW_OPEN},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_HISTORY}           ,TXT_LIL_N_HISTORY},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_GUIDANCE}          ,TXT_OIL1_N_CDW_GUIDE},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_RECORD}             ,TXT_LIL_N_RECORD},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MANAGE_BOOKMARK}   ,TXT_OIL1_N_CDW_BOOKMARK_MANAGE},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_LOCAL_PAGE}        ,TXT_LIL_N_CDW_LOCAL_PAGE},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_FOLDER}            ,TXT_PML_N_CAPITAL_FOLDER},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_REFRESH}           ,TXT_OIL1_N_CDW_REFRESH},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_TOOLS}             ,TXT_OIL1_N_CDW_TOOLS},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MARK}              ,TXT_OIL1_N_MARK},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_CLEAN}             ,TXT_OIL1_N_CDW_CLEAN},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_SETTING}           ,TXT_LIL_N_SETTINGS},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_DOWNLOAD_DIRECTORY},TXT_OIL1_N_CDW_LOAD_DIR},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_DIAL}              ,TXT_LIL_N_DIAL},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_EXIT}              ,TXT_OIL1_N_EXIT},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_EXIT_EXPLOR}       ,TXT_OIL1_N_CDW_EXIT_EXPLOR}})
        WdgEnd(CLSID_VTMOPTIONMENU,OptMenu)
#else //#ifdef __3G_RIL_MMI__
        WdgBegin(CLSID_VTMOPTIONMENU,OptMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,16})
            VtmCreateOptionMenuDataRC(16,\
                {{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_OPEN}              ,TXT_OIL1_N_CDW_OPEN},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_HISTORY}           ,TXT_LIL_N_HISTORY},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_GUIDANCE}          ,TXT_OIL1_N_CDW_GUIDE},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_RECORD}             ,TXT_LIL_N_RECORD},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MANAGE_BOOKMARK}   ,TXT_OIL1_N_CDW_BOOKMARK_MANAGE},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_LOCAL_PAGE}        ,TXT_LIL_N_CDW_LOCAL_PAGE},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_FOLDER}            ,TXT_PML_N_CAPITAL_FOLDER},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_REFRESH}           ,TXT_OIL1_N_CDW_REFRESH},	\
				{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_TOOLS}             ,TXT_OIL1_N_CDW_TOOLS},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MARK}              ,TXT_OIL1_N_MARK},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_CLEAN}             ,TXT_OIL1_N_CDW_CLEAN},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_SETTING}           ,TXT_LIL_N_SETTINGS},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_DOWNLOAD_DIRECTORY},TXT_OIL1_N_CDW_LOAD_DIR},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_EXIT}              ,TXT_OIL1_N_EXIT},	\
				{{MENUMODEL_ITEM_VISABLE                         ,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_EXIT_EXPLOR}       ,TXT_OIL1_N_CDW_EXIT_EXPLOR}})
        WdgEnd(CLSID_VTMOPTIONMENU,OptMenu)
#endif //#ifdef __3G_RIL_MMI__
    WndEnd(CDWAP_WND_OPTION_MENU)

    WndBegin(CDWAP_WND_MARK_OPTION_MENU)
        WndSetAllSoftkeyRC( {SK_SELECT,SK_OK,SK_CANCEL} )
        WdgBegin(CLSID_VTMOPTIONMENU,tCdWapMarkOptionMenuL1Table)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,5})
            VtmCreateOptionMenuDataRC(5,
                {{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MO_MARK      },TXT_OIL1_N_MARK      },	\
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MO_UNMARK    },TXT_OIL1_N_UNMARK    },	\
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MO_MARK_ALL  },TXT_OIL1_N_MARK_ALL  },	\
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MO_UNMARK_ALL},TXT_OIL1_N_UNMARK_ALL},	\
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_MO_DELETE    },TXT_OIL1_N_DELETE    }})
        WdgEnd(CLSID_VTMOPTIONMENU,tCdWapMarkOptionMenuL1Table)
    WndEnd(CDWAP_WND_MARK_OPTION_MENU)

    WndBegin(CDWAP_WND_EDIT_OPTION_MENU)
        WndSetAllSoftkeyRC( {SK_SELECT,SK_OK,SK_CANCEL} )
        WdgBegin(CLSID_VTMOPTIONMENU,tCdWapEditOptionMenuL1Table)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_COMMON_TEXT_SAVE},TXT_OIL1_N_SAVE},	{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_COMMON_TEXT_INPUT_MENU},TXT_OIL1_N_INPUT_MENU}})
        WdgEnd(CLSID_VTMOPTIONMENU,tCdWapEditOptionMenuL1Table)
    WndEnd(CDWAP_WND_EDIT_OPTION_MENU)

    WndBegin(CDWAP_WND_POPUP_MENU)
        WdgBegin(CLSID_VTMPOPUPSELECT,PopUpSelect)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_NONE,2,0,0})
            VtmCreatePopUpSelectDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_GOTOURL},TXT_LIL_N_GOTO_URL},	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CDWAPAPP_HOMEPAGE},TXT_LIL_N_HOMEPAGE}	})
        WdgEnd(CLSID_VTMPOPUPSELECT,PopUpSelect)
    WndEnd(CDWAP_WND_POPUP_MENU)

    WndBegin(CDWAP_WND_MARK_MODE)
        WdgBegin(CLSID_VTMMENU,MarkMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,MarkMenu)
    WndEnd(CDWAP_WND_MARK_MODE)

    WndBegin(CDWAP_WND_MOVE_FILES)
        WdgBegin(CLSID_VTMMENU,MoveMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_NULL_ID,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,MoveMenu)
    WndEnd(CDWAP_WND_MOVE_FILES)

    WndBegin(CDWAP_WND_EDIT_CONTENT)
        WndSetAllSoftkeyRC( {SK_SAVE, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMINPUT,EditInput)
            VtmCreateInputRC({IMG_NULL_ID,TXT_OIL1_N_EDIT,0,FALSE})
        WdgEnd(CLSID_VTMINPUT,EditInput)
    WndEnd(CDWAP_WND_EDIT_CONTENT)

#ifdef __MMI_OMA_DRM_V1__
    WndBegin(CDWAP_WND_VIEW_OMA_DD)
        WdgBegin(CLSID_INPUTWIDGET,ViewOMADDInputWidget)
            WdgInputCreateForWndRC({{MAINVIEW_X,0},{MAINVIEW_WIDTH,MAINVIEW_HEIGHT},{TRUE,0}})
            WdgCommonEnableScrollBarRC(SCROLL_STYLE_V_RIGHT)
            WdgInputSetMultilineRC(TRUE)
        WdgEnd(CLSID_INPUTWIDGET,ViewOMADDInputWidget)
    WndEnd(CDWAP_WND_VIEW_OMA_DD)
#endif
ApEnd(RS,CLSID_CDWAPAPP)

