ApBegin(RS,CLSID_CALLLOGAPP)
    WndBegin(CALLLOG_WND_DETAILTIME_SHOW_DETAIL)
        WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_RECENT_CALLS})
    WndEnd(CALLLOG_WND_DETAILTIME_SHOW_DETAIL)
    
#if !defined(__MMI_PHB_DISABLE_BLACKLIST__) && defined(__MMI_CALLLOG_SUPPORT_BKLOG__)
#ifdef __APP_VIDEO_TELEPHONY__
    WndBegin(CALLLOG_WND_LIST)
        WdgBegin(CLSID_VTMTABMENU,MainMenu)
            VtmCreateTabMenuRC({IMG_NULL_ID,TXT_LTL_N_RECENT_CALLS,5})
            VtmCreateTabMenuDataRC(5,{{CALLHISTORY_IMG_TAB_ALL, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_MISSED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_RECEIVED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_DIALED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_BLOCKED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0}})
			WdgTabSetActiveWidthRC(CALLLOGAPP_5_TAB_WIDTH_ACTIVE)
			WdgTabSetInactiveWidthRC(CALLLOGAPP_5_TAB_WIDTH_INACTIVE)
			WdgTabSetTabPaddingLeftRC(CALLLOGAPP_5_TAB_LEFT_PADDING)
			WdgTabSetTabPaddingRightRC(CALLLOGAPP_5_TAB_RIGHT_PADDING)
			WdgTabSetTabGapRC(CALLLOGAPP_5_TAB_GAP)
        WdgEnd(CLSID_VTMTABMENU,MainMenu)
    WndEnd(CALLLOG_WND_LIST)
#else
    WndBegin(CALLLOG_WND_LIST)
        WdgBegin(CLSID_VTMTABMENU,MainMenu)
            VtmCreateTabMenuRC({IMG_NULL_ID,TXT_LTL_N_RECENT_CALLS,5})
            VtmCreateTabMenuDataRC(5,{{CALLHISTORY_IMG_TAB_ALL, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_MISSED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_RECEIVED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_DIALED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_BLOCKED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0}})
			WdgTabSetActiveWidthRC(CALLLOGAPP_5_TAB_WIDTH_ACTIVE)
			WdgTabSetInactiveWidthRC(CALLLOGAPP_5_TAB_WIDTH_INACTIVE)
			WdgTabSetTabPaddingLeftRC(CALLLOGAPP_5_TAB_LEFT_PADDING)
			WdgTabSetTabPaddingRightRC(CALLLOGAPP_5_TAB_RIGHT_PADDING)
			WdgTabSetTabGapRC(CALLLOGAPP_5_TAB_GAP)
        WdgEnd(CLSID_VTMTABMENU,MainMenu)
    WndEnd(CALLLOG_WND_LIST)
#endif
#else
#ifdef __APP_VIDEO_TELEPHONY__
    WndBegin(CALLLOG_WND_LIST)
        WdgBegin(CLSID_VTMTABMENU,MainMenu)
            VtmCreateTabMenuRC({IMG_NULL_ID,TXT_LTL_N_RECENT_CALLS,4})
            VtmCreateTabMenuDataRC(4,{{CALLHISTORY_IMG_TAB_ALL, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_MISSED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_RECEIVED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_DIALED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXTIMAGE, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0}})
			WdgTabSetActiveWidthRC(CALLLOGAPP_4_TAB_WIDTH_ACTIVE)
			WdgTabSetInactiveWidthRC(CALLLOGAPP_4_TAB_WIDTH_INACTIVE)
			WdgTabSetTabPaddingLeftRC(CALLLOGAPP_4_TAB_LEFT_PADDING)
			WdgTabSetTabPaddingRightRC(CALLLOGAPP_4_TAB_RIGHT_PADDING)
			WdgTabSetTabGapRC(CALLLOGAPP_4_TAB_GAP)
        WdgEnd(CLSID_VTMTABMENU,MainMenu)
    WndEnd(CALLLOG_WND_LIST)
#else
    WndBegin(CALLLOG_WND_LIST)
        WdgBegin(CLSID_VTMTABMENU,MainMenu)
            VtmCreateTabMenuRC({IMG_NULL_ID,TXT_LTL_N_RECENT_CALLS,4})
            VtmCreateTabMenuDataRC(4,{{CALLHISTORY_IMG_TAB_ALL, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_MISSED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_RECEIVED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0},
                                         {CALLHISTORY_IMG_TAB_DIALED, TXT_NULL_ID, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0}})
			WdgTabSetActiveWidthRC(CALLLOGAPP_4_TAB_WIDTH_ACTIVE)
			WdgTabSetInactiveWidthRC(CALLLOGAPP_4_TAB_WIDTH_INACTIVE)
			WdgTabSetTabPaddingLeftRC(CALLLOGAPP_4_TAB_LEFT_PADDING)
			WdgTabSetTabPaddingRightRC(CALLLOGAPP_4_TAB_RIGHT_PADDING)
			WdgTabSetTabGapRC(CALLLOGAPP_4_TAB_GAP)
        WdgEnd(CLSID_VTMTABMENU,MainMenu)
    WndEnd(CALLLOG_WND_LIST)
#endif
#endif

	WndBegin(CALLLOG_WND_SELECT_DISPLAY_SIM)
         WndSetAllSoftkeyRC( {SK_SELECT, SK_OK, SK_BACK} )
        WdgBegin(CLSID_VTMMENU,DisplaySimMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CDW_SIM_SELECTED,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,3,0,0})
            VtmCreateMenuDataRC(3,  { {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_DISPLAY_ALL},{0, TXT_LIL_N_TOTAL     }},
                                               {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_DISPLAY_SIM1},  {0, TXT_LIL_N_MASTER_SIM}},
                                               {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_DISPLAY_SIM2},    {0, TXT_LIL_N_SLAVE_SIM  }}})
        WdgEnd(CLSID_VTMMENU,DisplaySimMenu)
    WndEnd(CALLLOG_WND_SELECT_DISPLAY_SIM)
    
    WndBegin(CALLLOG_WND_TIMER_MENU)
         WndSetAllSoftkeyRC( {SK_SELECT, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMMENU,TimerMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_CALL_TIMERS,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4,  { {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_CT_LAST_CALL},{0, TXT_LIL_N_LAST_CALL     }},
                                               {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_CT_RECEIVED_CALLS},  {0, TXT_LIL_N_RECEIVED_CALLS}},
                                               {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_CT_DIALED_CALLS},    {0, TXT_LIL_N_DIALED_CALLS  }},
                                               {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CALLLOGAPP_CT_RESET},           {0, TXT_LIL_N_RESET         }}})
        WdgEnd(CLSID_VTMMENU,TimerMenu)
    WndEnd(CALLLOG_WND_TIMER_MENU)

    WndBegin(CALLLOG_WND_COST_MENU)
        WndSetAllSoftkeyRC( {SK_SELECT, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMMENU,CostMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CALL_COST,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4,  { {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CH_LAST_CALL},       {0, TXT_LIL_N_LAST_CALL      }},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CH_TOTAL_CALL_COST}, {0, TXT_LIL_N_TOTAL_CALL_COST}},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CH_CREDIT},          {0, TXT_LIL_N_CREDIT         }},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CH_RESET_COST},      {0, TXT_LIL_N_RESET_COST     }}})
        WdgEnd(CLSID_VTMMENU,CostMenu)
    WndEnd(CALLLOG_WND_COST_MENU)

    WndBegin(CALLLOG_WND_COST_SETTING_MENU)
        WdgBegin(CLSID_VTMMENU,SettingMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CALL_COST_SETTING,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,3,0,0})

         	VTMWdgBegin (CLSID_MENUWIDGET, VTM_CREATE_MENU_MENU_WDG, VtmCostMenu)
                WdgMenuSetFirstItemRC(0)
                WdgMenuSetHighlightedItemRC(0)
		    VTMWdgEnd (CLSID_INPUTWIDGET, VTM_CREATE_MENU_MENU_WDG, VtmCostMenu)           

        WdgEnd(CLSID_VTMMENU,SettingMenu)
    WndEnd(CALLLOG_WND_COST_SETTING_MENU)

    WndBegin(CALLLOG_WND_COST_SETTING_SETUNIT)
        WndSetAllSoftkeyRC( {SK_OK_TEXT, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMPROMPTINPUT,SetUnitInput)
            VtmCreatePromptInputRC({IMG_NULL_ID, TXT_LIL_N_CALL_COST_SETTING, TXT_LIL_N_AOC_PPU, MMI_CALL_COST_MAX_UNIT_SIZE})
            VTMWdgBegin (CLSID_INPUTWIDGET, PROMPT_INPUT_INPUT_WDG, SettingUnitInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
                WdgInputSetPasswordStyleRC(FALSE)
                WdgInputSetDecimalPointEnableRC(TRUE)
                WdgInputSetMaxlenAfterDecimalPointRC(4)
                WdgInputSetDisableSymbolTableRC(FALSE)
            VTMWdgEnd(CLSID_INPUTWIDGET, PROMPT_INPUT_INPUT_WDG, SettingUnitInput)
        WdgEnd(CLSID_VTMPROMPTINPUT,SetUnitInput)
    WndEnd(CALLLOG_WND_COST_SETTING_SETUNIT)

    WndBegin(CALLLOG_WND_COST_SETTING_SETCURRENCY)
        WndSetAllSoftkeyRC( {SK_OK_TEXT, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMPROMPTINPUT,SetCurrencyInput)
            VtmCreatePromptInputRC({IMG_NULL_ID, TXT_LIL_N_CALL_COST_SETTING, TXT_LIL_N_AOC_CURRENCY, MMI_CALL_COST_MAX_CURRENCY_SIZE})
            VTMWdgBegin(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingCurInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_MT_Abc)
                WdgInputSetPasswordStyleRC(FALSE)
            VTMWdgEnd(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingCurInput)
        WdgEnd(CLSID_VTMPROMPTINPUT,SetCurrencyInput)
    WndEnd(CALLLOG_WND_COST_SETTING_SETCURRENCY)

    WndBegin(CALLLOG_WND_COST_SETTING_SETMAXUNIT)
        WndSetAllSoftkeyRC( {SK_OK_TEXT, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_VTMPROMPTINPUT,SetMaxUnitInput)
            VtmCreatePromptInputRC({IMG_NULL_ID, TXT_LIL_N_CALL_COST_SETTING, TXT_LIL_N_AOC_MAX_UNIT, MMI_CALL_COST_MAX_UNIT_SIZE})
            VTMWdgBegin(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingMaxUInput)
                WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_NUMERIC)
                WdgInputSetPasswordStyleRC(FALSE)
            VTMWdgEnd(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingMaxUInput) 
        WdgEnd(CLSID_VTMPROMPTINPUT,SetMaxUnitInput)
    WndEnd(CALLLOG_WND_COST_SETTING_SETMAXUNIT)

    WndBegin(CALLLOG_WND_COST_SETTING_ENTERPIN2)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CANCEL} )
        WdgBegin(CLSID_VTMPROMPTINPUT,EnterPin2Input)
            VtmCreatePromptInputRC({IMG_NULL_ID, TXT_LIL_N_CALL_COST_SETTING, TXT_LIL_N_ENTER_PIN2, MAX_PIN2_PASSWORD_LEN})
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_NUMERIC)
            VTMWdgBegin(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingP2Input)
                WdgInputSetPasswordStyleRC(FALSE)
            VTMWdgEnd(CLSID_INPUTWIDGET,PROMPT_INPUT_INPUT_WDG,SettingP2Input)  
        WdgEnd(CLSID_VTMPROMPTINPUT,EnterPin2Input)
    WndEnd(CALLLOG_WND_COST_SETTING_ENTERPIN2)

    WndBegin(CALLLOG_WND_COST_RESETACCOUNT_ENTERPIN2)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CANCEL} )
        WdgBegin(CLSID_VTMPROMPTINPUT,ResetEnterPin2Input)
            VtmCreatePromptInputRC({IMG_NULL_ID, TXT_LIL_N_CALL_COST_SETTING, TXT_LIL_N_ENTER_PIN2, MAX_PIN2_PASSWORD_LEN})
        WdgEnd(CLSID_VTMPROMPTINPUT,ResetEnterPin2Input)
    WndEnd(CALLLOG_WND_COST_RESETACCOUNT_ENTERPIN2)

    WndBegin(CALLLOG_WND_TIMER_SELECT_SIM)
        WdgBegin(CLSID_VTMSIMSELECTION,TimerDualSim)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_CALL_TIMERS})
        WdgEnd(CLSID_VTMSIMSELECTION,TimerDualSim)
    WndEnd(CALLLOG_WND_TIMER_SELECT_SIM)

    WndBegin(CALLLOG_WND_COST_SELECT_SIM)
        WdgBegin(CLSID_VTMSIMSELECTION,CostDualSim)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LIL_N_CALL_COST})
        WdgEnd(CLSID_VTMSIMSELECTION,CostDualSim)
    WndEnd(CALLLOG_WND_COST_SELECT_SIM)

#ifdef __APP_VIDEO_TELEPHONY__
    WndBegin(CALLLOG_WND_LIST_SHOW_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,ListShowOpt)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,12})
            VtmCreateOptionMenuDataRC(12,{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIEW}, TXT_OIL1_N_VIEW },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL}, TXT_OIL1_N_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIDEOCALL}, TXT_OIL1_N_VIDEO_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_IPCALL}, TXT_OIL1_N_IP_CALL },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SEND}, TXT_OIL1_N_SEND },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SAVE}, TXT_OIL1_N_SAVE },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE}, TXT_OIL1_N_DELETE },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE_ALL}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_DELETE_ALL_NO_SELECT}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_ADD_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL_TIMERS}, TXT_OIL1_N_CALL_TIMERS },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CH_CALL_COST}, TXT_LIL_N_CALL_COST }})

        WdgEnd(CLSID_VTMOPTIONMENU,ListShowOpt)
    WndEnd(CALLLOG_WND_LIST_SHOW_OPTION)

    WndBegin(CALLLOG_WND_DETAILTIME_SHOW_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,DetailTimeShowOpt)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,10})
            VtmCreateOptionMenuDataRC(10,{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIEW}, TXT_OIL1_N_VIEW },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL}, TXT_OIL1_N_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIDEOCALL}, TXT_OIL1_N_VIDEO_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_IPCALL}, TXT_OIL1_N_IP_CALL },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SEND}, TXT_OIL1_N_SEND },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SAVE}, TXT_OIL1_N_SAVE },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE}, TXT_OIL1_N_DELETE },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE_ALL}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL_TIMERS}, TXT_OIL1_N_CALL_TIMERS },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CH_CALL_COST}, TXT_LIL_N_CALL_COST }})
        WdgEnd(CLSID_VTMOPTIONMENU,DetailTimeShowOpt)
    WndEnd(CALLLOG_WND_DETAILTIME_SHOW_OPTION)
#else
    WndBegin(CALLLOG_WND_LIST_SHOW_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,ListShowOpt)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,12})
            VtmCreateOptionMenuDataRC(12,{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIEW}, TXT_OIL1_N_VIEW },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL}, TXT_OIL1_N_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_IPCALL}, TXT_OIL1_N_IP_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_EDIT_BEFORE_CALL}, TXT_OIL1_N_EDIT_BEFORE_CALL },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SEND}, TXT_OIL1_N_SEND },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SAVE}, TXT_OIL1_N_SAVE },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE}, TXT_OIL1_N_DELETE },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE_ALL}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_DELETE_ALL_NO_SELECT}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_ADD_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL_TIMERS}, TXT_OIL1_N_CALL_TIMERS },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CH_CALL_COST}, TXT_LIL_N_CALL_COST }})

        WdgEnd(CLSID_VTMOPTIONMENU,ListShowOpt)
    WndEnd(CALLLOG_WND_LIST_SHOW_OPTION)

    WndBegin(CALLLOG_WND_DETAILTIME_SHOW_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,DetailTimeShowOpt)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,11})
            VtmCreateOptionMenuDataRC(11,{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_VIEW}, TXT_OIL1_N_VIEW },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL}, TXT_OIL1_N_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_IPCALL}, TXT_OIL1_N_IP_CALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_EDIT_BEFORE_CALL}, TXT_OIL1_N_EDIT_BEFORE_CALL },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SEND}, TXT_OIL1_N_SEND },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_SAVE}, TXT_OIL1_N_SAVE },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE}, TXT_OIL1_N_DELETE },
                                            {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_DELETE_ALL}, TXT_OIL1_N_DELETE_ALL },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_ADD_TO_BLACKLIST}, TXT_LIL_N_NEW_BLACKLIST },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CALLLOGAPP_LO_CALL_TIMERS}, TXT_OIL1_N_CALL_TIMERS },
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_CH_CALL_COST}, TXT_LIL_N_CALL_COST }})
        WdgEnd(CLSID_VTMOPTIONMENU,DetailTimeShowOpt)
    WndEnd(CALLLOG_WND_DETAILTIME_SHOW_OPTION)
#endif

	WndBegin(CALLLOG_WND_CUS)
		RSCustomize(u16,detailViewItemNum,CALLLOGAPP_DETAIL_VIEW_NUM)
	WndEnd(CALLLOG_WND_CUS)
	
ApEnd(RS,CLSID_CALLLOGAPP)

