ApBegin(RS,CLSID_BCSAPP)
#if defined(__MMI_BEAUTY_CLK_APP__)
    WndBegin(BEAUTYCLKSETTING_WND_MAIN)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_BEAUTY_CLOCK})
        WndSetTitleVisiableRC(FALSE)
        WndSetStatusBarVisibleRC(VIEWSK_INVISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)

        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_BG}})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_TOP)
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,InfoBGWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_INFOBG_POS_X,GL_BEAUTYCLKAPP_CLK_INFOBG_POS_Y},{GL_BEAUTYCLKAPP_CLK_INFOBG_WIDTH,GL_BEAUTYCLKAPP_CLK_INFOBG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,BEAUTY_IMG_TITLE_BG}})
            WdgImageSetDataByIDRC(BEAUTY_IMG_TITLE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,InfoBGWdg)

        WdgBegin(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
            WdgMenuCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_POS_X,GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_POS_Y},{GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_WIDTH,GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_BOTTOM)
            WdgStaticMenuItemRC(GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_GRID_NUMBER, {
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},0},{BEAUTY_IMG_NUMBER_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},1},{BEAUTY_IMG_NUMBER_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},2},{BEAUTY_IMG_SYMBOL, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},3},{BEAUTY_IMG_NUMBER_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},4},{BEAUTY_IMG_NUMBER_9, TXT_NULL_ID}},
                            } )
            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_ITEM_HEIGHT)
            WdgMenuSetFixedNumRC(GL_BEAUTYCLKAPP_CLK_TIMEWIDGET_GRID_NUMBER)
        WdgEnd(CLSID_IMGGRID_MENUWIDGET,TimeWdg)

        WdgBegin(CLSID_IMAGEWIDGET,I12HWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_12HWIDGET_POS_X,GL_BEAUTYCLKAPP_CLK_12HWIDGET_POS_Y},{GL_BEAUTYCLKAPP_CLK_12HWIDGET_WIDTH,GL_BEAUTYCLKAPP_CLK_12HWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,I12HWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BtnWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_BTN_POS_X,GL_BEAUTYCLKAPP_CLK_BTN_POS_Y},{GL_BEAUTYCLKAPP_CLK_BTN_WIDTH,GL_BEAUTYCLKAPP_CLK_BTN_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,BEAUTY_IMG_OPTION_OPEN_BTN}})
        WdgEnd(CLSID_IMAGEWIDGET,BtnWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SwitchWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_POS_X_OFF,GL_BEAUTYCLKAPP_CLK_SWITCH_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,BEAUTY_IMG_SWITCH}})
        WdgEnd(CLSID_IMAGEWIDGET,SwitchWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SwitchBGWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_BG_POS_X,GL_BEAUTYCLKAPP_CLK_SWITCH_BG_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_BG_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_BG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,BEAUTY_IMG_OPTION_BG}})
        WdgEnd(CLSID_IMAGEWIDGET,SwitchBGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SwitchIconWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_ICON_POS_X,GL_BEAUTYCLKAPP_CLK_SWITCH_ICON_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_ICON_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_ICON_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,BEAUTY_IMG_SWITCH_BG}})
        WdgEnd(CLSID_IMAGEWIDGET,SwitchIconWdg)

        WdgBegin(CLSID_TEXTWIDGET,SwitchOnWdg)
            WdgTextCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_ON_POS_X,GL_BEAUTYCLKAPP_CLK_SWITCH_ON_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_ON_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_ON_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_ON)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,SwitchOnWdg)

        WdgBegin(CLSID_TEXTWIDGET,SwitchOffWdg)
            WdgTextCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_OFF_POS_X,GL_BEAUTYCLKAPP_CLK_SWITCH_OFF_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_OFF_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_OFF_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_OFF)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,SwitchOffWdg)

        WdgBegin(CLSID_TEXTWIDGET,SwitchTitleWdg)
            WdgTextCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_SWITCH_TITLE_POS_X,GL_BEAUTYCLKAPP_CLK_SWITCH_TITLE_POS_Y},{GL_BEAUTYCLKAPP_CLK_SWITCH_TITLE_WIDTH,GL_BEAUTYCLKAPP_CLK_SWITCH_TITLE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_OIL1_N_SET_AS_SCREEN_LOCK)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,SwitchTitleWdg)

        WdgBegin(CLSID_IMAGEWIDGET,ExitBGWdg)
            WdgImageCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_EXIT_BG_POS_X,GL_BEAUTYCLKAPP_CLK_EXIT_BG_POS_Y},{GL_BEAUTYCLKAPP_CLK_EXIT_BG_WIDTH,GL_BEAUTYCLKAPP_CLK_EXIT_BG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,BEAUTY_IMG_OPTION_BG}})
        WdgEnd(CLSID_IMAGEWIDGET,ExitBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,ExitTitleWdg)
            WdgTextCreateForWndRC({{GL_BEAUTYCLKAPP_CLK_EXIT_TITLE_POS_X,GL_BEAUTYCLKAPP_CLK_EXIT_TITLE_POS_Y},{GL_BEAUTYCLKAPP_CLK_EXIT_TITLE_WIDTH,GL_BEAUTYCLKAPP_CLK_EXIT_TITLE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_RSK_N_EXIT)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,ExitTitleWdg)
    WndEnd(BEAUTYCLKSETTING_WND_MAIN)
#endif
ApEnd(RS,CLSID_BCSAPP)
