ApBegin(RS,CLSID_ATVAPP)

    WndBegin(ATV_WND_MAINMENU)
#ifdef __ATV_CMMB__
        WdgBegin(CLSID_VTMMENU,MainMenuMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CMMB,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,CHECK_RADIO_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_MY_TV}, {IMG_NULL_ID, TXT_LIL_N_MY_TV} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_CHANNEL_LIST}, {IMG_NULL_ID, TXT_LIL_N_CHANNEL_LIST} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_SEARCH_CHANNEL}, {IMG_NULL_ID, TXT_LIL_N_SEARCH_CHANNEL} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_RATIO_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_RATIO_SETTINGS} },
                                   }
                               )
        WdgEnd(CLSID_VTMMENU,MainMenuMenu)
#else
#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_VTMMENU,MainMenuMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_ATV,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,CHECK_RADIO_STYLE_NONE,ATV_RS_MAINMENU_ITEMCOUNT,0,0})
            VtmCreateMenuDataRC(5, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_MY_TV}, {IMG_NULL_ID, TXT_LIL_N_MY_TV} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_CHANNEL_LIST}, {IMG_NULL_ID, TXT_LIL_N_CHANNEL_LIST} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_SEARCH_CHANNEL}, {IMG_NULL_ID, TXT_LIL_N_SEARCH_CHANNEL} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_AREA_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_AREA_SETTINGS} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_RATIO_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_RATIO_SETTINGS} }
                                   }
                               )
        WdgEnd(CLSID_VTMMENU,MainMenuMenu)
#else // !__APP_MMI_SMALLROM__
        WdgBegin(CLSID_VTMMENU,MainMenuMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_ATV,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,CHECK_RADIO_STYLE_NONE,7,0,0})
            VtmCreateMenuDataRC(7, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_MY_TV}, {IMG_NULL_ID, TXT_LIL_N_MY_TV} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_CHANNEL_LIST}, {IMG_NULL_ID, TXT_LIL_N_CHANNEL_LIST} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_SEARCH_CHANNEL}, {IMG_NULL_ID, TXT_LIL_N_SEARCH_CHANNEL} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_TV_PICTURES}, {IMG_NULL_ID, TXT_LIL_N_TV_PICTURES} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_AREA_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_AREA_SETTINGS} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_RATIO_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_RATIO_SETTINGS} },
									 {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_STORAGE_SETTINGS}, {IMG_NULL_ID, TXT_OIL1_N_STORAGE} }
                                   }
                               )
        WdgEnd(CLSID_VTMMENU,MainMenuMenu)
#endif //__APP_MMI_SMALLROM__
#ifdef __ATV_ISDBT__
        WdgBegin(CLSID_VTMMENU, ISDBTMainMenuMenu)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_ISDBT, WDG_MENU_TYPE_NUMERIC, WDG_MENU_ITEM_TYPE_IMAGE_TEXT, CHECK_RADIO_STYLE_NONE, 5, 0, 0})
            VtmCreateMenuDataRC(5, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_ATV_MY_TV}, {IMG_NULL_ID, TXT_LIL_N_MY_TV} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_ATV_CHANNEL_LIST}, {IMG_NULL_ID, TXT_LIL_N_CHANNEL_LIST} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_ATV_SEARCH_CHANNEL}, {IMG_NULL_ID, TXT_LIL_N_SEARCH_CHANNEL} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_ATV_AREA_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_AREA_SETTINGS} },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_ATV_RATIO_SETTINGS}, {IMG_NULL_ID, TXT_LIL_N_RATIO_SETTINGS} },
                                   }
                               )
        WdgEnd(CLSID_VTMMENU, ISDBTMainMenuMenu)
#endif // __ATV_ISDBT__
#endif //__ATV_CMMB__
    WndEnd(ATV_WND_MAINMENU)

    WndBegin(ATV_WND_WATCH)
        WdgBegin(CLSID_OSDWIDGET,OsdWdg)
            WdgOsdCreateForWndRC({{0,0},{ATV_RS_OSD_WIDTH,ATV_RS_OSD_HEIGHT}})
        WdgEnd(CLSID_OSDWIDGET,OsdWdg)

#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_ABSCONTAINER,StatusAbsCntr)
            WdgAbsContainerCreateForWndRC({{ATV_STATUS_CONTAINER_POS_X,ATV_STATUS_CONTAINER_POS_Y},{ATV_STATUS_CONTAINER_WIDTH,ATV_STATUS_CONTAINER_HEIGHT},0})
	    WdgEnd(CLSID_ABSCONTAINER,StatusAbsCntr)
        WdgBegin(CLSID_BUTTONWIDGET,StatusAbsBGBtnWdg)
            WdgButtonCreateForWndRC({{ATV_STATUS_BAR_BG_POS_X,ATV_STATUS_BAR_BG_POS_Y},{ATV_STATUS_BAR_BG_IMAGE_WIDTH,ATV_STATUS_BAR_BG_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_OSD_BG,VIDEOPLAYER_IMG_OSD_BG})
        WdgEnd(CLSID_BUTTONWIDGET,StatusAbsBGBtnWdg)
#endif // __APP_MMI_SMALLROM__

        WdgBegin(CLSID_IMAGEWIDGET, WaitingImgWdg)
            WdgImageCreateForWndRC({{ATV_WAITING_IMAGE_POS_X, ATV_WAITING_IMAGE_POS_Y}, {ATV_WAITING_IMAGE_WIDTH, ATV_WAITING_IMAGE_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, TOOLS_BLUETOOTH_IMG_SEARCH_ANIM}})
        WdgEnd(CLSID_IMAGEWIDGET, WaitingImgWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SignalImgWdg)
            WdgImageCreateForWndRC({{ATV_SIGNAL_POS_X,ATV_SIGNAL_POS_Y},{ATV_SIGNAL_IMAGE_WIDTH,ATV_SIGNAL_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,ATV_IMG_SIGNAL_NO_SERVICE}})
        WdgEnd(CLSID_IMAGEWIDGET,SignalImgWdg)

        WdgBegin(CLSID_TEXTWIDGET,ChannelNameTextWdg)
            WdgTextCreateForWndRC({{ATV_CHANNEL_NAME_POS_X,ATV_CHANNEL_NAME_POS_Y},{ATV_CHANNEL_NAME_TEXT_WIDTH,ATV_CHANNEL_NAME_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetTextColorRC(DEF_THM_ATVAPP_CHANNEL_NAME_TEXT)
            WdgCommonSetAlignmentRC(ATV_STATUS_TEXT_ALIGN)
            WdgCommonSetFontCategoryRC(ATV_FONT_CAT_DEFAULT)
            WdgCommonSetFontTypeRC(FONT_TYPE_EXPAND1)
        WdgEnd(CLSID_TEXTWIDGET,ChannelNameTextWdg)
#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,AdjustBGVolumeImgWdg)
            WdgImageCreateForWndRC({{ATV_VOLUME_ADJUST_BG_POS_X,ATV_VOLUME_ADJUST_BG_POS_Y},{ATV_VOLUME_ADJUST_BG_IMAGE_WIDTH,ATV_VOLUME_ADJUST_BG_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_OSD_VOLUME_PROGRESS_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_OSD_VOLUME_PROGRESS_BG)
        WdgEnd(CLSID_IMAGEWIDGET,AdjustBGVolumeImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,AdjustLevelVolumeImgWdg)
            WdgImageCreateForWndRC({{ATV_VOLUME_ADJUST_LEVEL_POS_X,ATV_VOLUME_ADJUST_LEVEL_POS_Y},{ATV_VOLUME_ADJUST_LEVEL_IMAGE_WIDTH,ATV_VOLUME_ADJUST_LEVEL_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_OSD_VOLUME_LEVEL}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_OSD_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,AdjustLevelVolumeImgWdg)
#else
#if defined(__MMI_BATTERY_ICON_DISPLAY__)
        WdgBegin(CLSID_IMAGEWIDGET,BatteryImgWdg)
            WdgImageCreateForWndRC({{ATV_BATTERY_POS_X,ATV_BATTERY_POS_Y},{ATV_BATTERY_IMAGE_WIDTH,ATV_BATTERY_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,BatteryImgWdg)
#endif
        WdgBegin(CLSID_ABSCONTAINER,VolumeAbsCntr)
            WdgAbsContainerCreateForWndRC({{ATV_VOLUME_CONTAINER_POS_X,ATV_VOLUME_CONTAINER_POS_Y},{ATV_VOLUME_CONTAINER_WIDTH,ATV_VOLUME_CONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,VolumeAbsCntr)
        WdgBegin(CLSID_IMAGEWIDGET,AdjustBGVolumeImgWdg)
            WdgImageCreateForWndRC({{ATV_VOLUME_ADJUST_BG_POS_X,ATV_VOLUME_ADJUST_BG_POS_Y},{ATV_VOLUME_ADJUST_BG_IMAGE_WIDTH,ATV_VOLUME_ADJUST_BG_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,ATV_IMG_VOLUME_ADJUST_BG}})
        WdgEnd(CLSID_IMAGEWIDGET,AdjustBGVolumeImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,AdjustLevelVolumeImgWdg)
            WdgImageCreateForWndRC({{ATV_VOLUME_ADJUST_LEVEL_POS_X,ATV_VOLUME_ADJUST_LEVEL_POS_Y},{ATV_VOLUME_ADJUST_LEVEL_IMAGE_WIDTH,ATV_VOLUME_ADJUST_LEVEL_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,AdjustLevelVolumeImgWdg)
#endif // __APP_MMI_SMALLROM__

        WdgBegin(CLSID_ABSCONTAINER,ControlAbsCntr)
            WdgAbsContainerCreateForWndRC({{ATV_CONTROL_CONTAINER_POS_X,ATV_CONTROL_CONTAINER_POS_Y},{ATV_CONTROL_CONTAINER_WIDTH,ATV_CONTROL_CONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,ControlAbsCntr)

#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,AbsBGBtnWdg)
            WdgButtonCreateForWndRC({{ATV_CONTROL_BAR_BG_POS_X,ATV_CONTROL_BAR_BG_POS_Y},{ATV_CONTROL_BAR_BG_IMAGE_WIDTH,ATV_CONTROL_BAR_BG_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_OSD_BG,VIDEOPLAYER_IMG_OSD_BG})
        WdgEnd(CLSID_BUTTONWIDGET,AbsBGBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,ReturnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_RETURN_POS_X,ATV_BUTTON_RETURN_POS_Y},{ATV_BUTTON_RETURN_IMAGE_WIDTH,ATV_BUTTON_RETURN_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_OSD_RETURN_UNPRESSED,VIDEOPLAYER_IMG_OSD_RETURN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ReturnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,VolumeIncBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_VOLUME_INCREASE_POS_X,ATV_BUTTON_VOLUME_INCREASE_POS_Y},{ATV_BUTTON_VOLUME_IMAGE_WIDTH,ATV_BUTTON_VOLUME_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_OSD_VOLUME_INCREASE_UNPRESSED,VIDEOPLAYER_IMG_OSD_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeIncBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,VolumeDecBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_VOLUME_DECREASE_POS_X,ATV_BUTTON_VOLUME_DECREASE_POS_Y},{ATV_BUTTON_VOLUME_IMAGE_WIDTH,ATV_BUTTON_VOLUME_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_OSD_VOLUME_DECREASE_UNPRESSED,VIDEOPLAYER_IMG_OSD_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeDecBtnWdg)
#else
        WdgBegin(CLSID_BUTTONWIDGET,AbsBGBtnWdg)
            WdgButtonCreateForWndRC({{ATV_CONTROL_BAR_BG_POS_X,ATV_CONTROL_BAR_BG_POS_Y},{ATV_CONTROL_BAR_BG_IMAGE_WIDTH,ATV_CONTROL_BAR_BG_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_CONTROL_BAR_BG,ATV_IMG_CONTROL_BAR_BG})
        WdgEnd(CLSID_BUTTONWIDGET,AbsBGBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,PowerOffBGBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_POWER_OFF_POS_X,ATV_BUTTON_POWER_OFF_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_POWER_OFF_UNPRESSED,ATV_IMG_POWER_OFF_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PowerOffBGBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,VolumeIncBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_VOLUME_INCREASE_POS_X,ATV_BUTTON_VOLUME_INCREASE_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_VOLUME_INCREASE_UNPRESSED,ATV_IMG_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeIncBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,VolumeDecBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_VOLUME_DECREASE_POS_X,ATV_BUTTON_VOLUME_DECREASE_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_VOLUME_DECREASE_UNPRESSED,ATV_IMG_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeDecBtnWdg)
#endif // __APP_MMI_SMALLROM__
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,CaptureBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_CAPUTRE_POS_X,ATV_BUTTON_CAPUTRE_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_CAPUTRE_UNPRESSED,ATV_IMG_CAPUTRE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,CaptureBtnWdg)
#endif  // !__APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,ChannelPreBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_CHANNEL_PREVIOUS_POS_X,ATV_BUTTON_CHANNEL_PREVIOUS_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_CHANNEL_PREVIOUS_UNPRESSED,ATV_IMG_CHANNEL_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ChannelPreBtnWdg)
        WdgBegin(CLSID_BUTTONWIDGET,ChannelNextBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_CHANNEL_NEXT_POS_X,ATV_BUTTON_CHANNEL_NEXT_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,ATV_IMG_CHANNEL_NEXT_UNPRESSED,ATV_IMG_CHANNEL_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ChannelNextBtnWdg)
#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,ScreenRatioBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_SCREEN_RATIO_POS_X,ATV_BUTTON_SCREEN_RATIO_POS_Y},{ATV_BUTTON_SCREEN_RATIO_IMAGE_WIDTH,ATV_BUTTON_SCREEN_RATIO_IMAGE_HEIGHT},0})
        WdgEnd(CLSID_BUTTONWIDGET,ScreenRatioBtnWdg)
#else
        WdgBegin(CLSID_BUTTONWIDGET,ScreenRatioBtnWdg)
            WdgButtonCreateForWndRC({{ATV_BUTTON_SCREEN_RATIO_POS_X,ATV_BUTTON_SCREEN_RATIO_POS_Y},{ATV_BUTTON_IMAGE_WIDTH,ATV_BUTTON_IMAGE_HEIGHT},0})
        WdgEnd(CLSID_BUTTONWIDGET,ScreenRatioBtnWdg)
#endif // __APP_MMI_SMALLROM__
    WndEnd(ATV_WND_WATCH)
#ifndef __APP_MMI_SMALLROM__
    WndBegin(ATV_WND_CAPTURE)
        WdgBegin(CLSID_IMAGEWIDGET,CapturePicImgWdg)
            WdgImageCreateForWndRC({{0,0},{MAIN_LCD_HEIGHT,MAIN_LCD_WIDTH},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,CapturePicImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,PreviewIconImgWdg)
            WdgImageCreateForWndRC({{ATV_CAPTURE_POS_X,ATV_CAPTURE_POS_Y},{ATV_CAPTURE_IMAGE_WIDTH,ATV_CAPTURE_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,ATV_IMG_PREVIEW}})
        WdgEnd(CLSID_IMAGEWIDGET,PreviewIconImgWdg)
    WndEnd(ATV_WND_CAPTURE)
#endif // !__APP_MMI_SMALLROM__
    WndBegin(ATV_WND_CHANNELLIST)
        WdgBegin(CLSID_VTMMENU,ChannelListMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CHANNEL_LIST,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,ChannelListMenu)
    WndEnd(ATV_WND_CHANNELLIST)

    WndBegin(ATV_WND_CHANNELLIST_EDIT)
        WdgBegin(CLSID_VTMINPUT,ChannelListEdit)
            VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_CHANNEL_NAME, MMI_ATVAPP_CHANNEL_NAME_MAX,FALSE})
        WdgEnd(CLSID_VTMINPUT,ChannelListEdit)
    WndEnd(ATV_WND_CHANNELLIST_EDIT)

    WndBegin(ATV_WND_AREA)
        WdgBegin(CLSID_VTMMENU,AreaMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_AREA_SETTINGS,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,47,0,0})
            VtmCreateMenuDataRC(47, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_CHINA}, TXT_PML_N_REGION_CHINA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SHENZHEN}, TXT_PML_N_REGION_SHENZHEN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_AFGHANISTAN}, TXT_PML_N_REGION_AFGHANISTAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_ARGENTINA}, TXT_PML_N_REGION_ARGENTINA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_AUSTRALIA}, TXT_PML_N_REGION_AUSTRALIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_BOLIVIA}, TXT_PML_N_REGION_BOLIVIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_BURMA}, TXT_PML_N_REGION_BURMA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_BRAZIL}, TXT_PML_N_REGION_BRAZIL },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_CAMBODIA}, TXT_PML_N_REGION_CAMBODIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_CANADA}, TXT_PML_N_REGION_CANADA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_CHILE}, TXT_PML_N_REGION_CHILE },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_COLUMBIA}, TXT_PML_N_REGION_COLUMBIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_COSTARICA}, TXT_PML_N_REGION_COSTARICA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_ECUADOR}, TXT_PML_N_REGION_ECUADOR },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_GERMAN}, TXT_PML_N_REGION_GERMAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_HONDURAS}, TXT_PML_N_REGION_HONDURAS },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_HONGKONG}, TXT_PML_N_REGION_HONGKONG },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_INDIA}, TXT_PML_N_REGION_INDIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_INDONESIA}, TXT_PML_N_REGION_INDONESIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_ITALY}, TXT_PML_N_REGION_ITALY },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_JAMAICA}, TXT_PML_N_REGION_JAMAICA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_JAPAN}, TXT_PML_N_REGION_JAPAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_KOREA}, TXT_PML_N_REGION_KOREA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_LAOS}, TXT_PML_N_REGION_LAOS },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_MALAYSIA}, TXT_PML_N_REGION_MALAYSIA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_MEXICO}, TXT_PML_N_REGION_MEXICO },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_NEWZEALAND}, TXT_PML_N_REGION_NEWZEALAND },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_PAKISTAN}, TXT_PML_N_REGION_PAKISTAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_PERU}, TXT_PML_N_REGION_PERU },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_PHILIPPINES}, TXT_PML_N_REGION_PHILIPPINES },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_PORTUGAL}, TXT_PML_N_REGION_PORTUGAL },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SINGAPORE}, TXT_PML_N_REGION_SINGAPORE },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SOUTHAFRICA}, TXT_PML_N_REGION_SOUTHAFRICA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SPAIN}, TXT_PML_N_REGION_SPAIN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SUDAN}, TXT_PML_N_REGION_SUDAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SURINAME}, TXT_PML_N_REGION_SURINAME },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_SWEDEN}, TXT_PML_N_REGION_SWEDEN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_TAIWAN}, TXT_PML_N_REGION_TAIWAN },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_THAILAND}, TXT_PML_N_REGION_THAILAND },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_TURKEY}, TXT_PML_N_REGION_TURKEY },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_UAE}, TXT_PML_N_REGION_UAE },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_UK}, TXT_PML_N_REGION_UK },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_USA}, TXT_PML_N_REGION_USA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_VENEZUELA}, TXT_PML_N_REGION_VENEZUELA },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_VIETNAM}, TXT_PML_N_REGION_VIETNAM },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_WESTERNEUROPE}, TXT_PML_N_REGION_WESTERNEUROPE },
                                      {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_REGION_YEMEN}, TXT_PML_N_REGION_YEMEN }
                                   }
                               )
        WdgEnd(CLSID_VTMMENU,AreaMenu)
    WndEnd(ATV_WND_AREA)

    WndBegin(ATV_WND_RATIO)
        WdgBegin(CLSID_VTMMENU,RatioMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_RATIO_SETTINGS,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            VtmCreateMenuDataRC(2, { {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_RATIO_4_3}, TXT_PML_N_RATIO_4_3 },
                                     {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK,DEFAULT_SK,DEFAULT_SK}, MNU_ATV_RATIO_16_9}, TXT_PML_N_RATIO_16_9 }
                                   }
                               )
        WdgEnd(CLSID_VTMMENU,RatioMenu)
    WndEnd(ATV_WND_RATIO)

    WndBegin(ATV_WND_CHANNELLIST_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,ChannelListOptionWdg)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,3})
            VtmCreateOptionMenuDataRC(3,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_ATV_CHANNEL_PLAY},TXT_OIL1_N_PLAY},
                                        {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_ATV_CHANNEL_RENAME},TXT_OIL1_N_RENAME},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_ATV_CHANNEL_SEARCH}, TXT_OIL1_N_SEARCH}
                                     })
        WdgEnd(CLSID_VTMOPTIONMENU,ChannelListOptionWdg)
    WndEnd(ATV_WND_CHANNELLIST_OPTION)
ApEnd(RS,CLSID_ATVAPP)
