
/**
 * @file    mmi_phbapp_view_id.h
 * 
 * @version $Id $
 */
 
#ifndef __MMI_PHBAPP_VIEW_ID_H__
#define __MMI_PHBAPP_VIEW_ID_H__     

#include "mmi_wdg_menu.h"
#include "mae_menulabel.h"
#include "mmi_mae_menumodel.h"
#include "mmi_view_id_range.h"
#include "mmi_wdg_image_text_image.h"
#include "mmi_wdg_scrollbar.h"
#include "mmi_mae_inputcontroller.h"
#include "mmi_wdg_text.h"
#include "mmi_mae_font.h"
#include "mmi_common_thmid.h"

/* View ID */
enum
{                           
	VID_PHB_INVALID_VIEW                = MMI_VIEW_ID_AP_BEGIN,
	VID_PHB_NOT_CREATE_VIEW,

	VID_PHB_TABLIST_SHOWMENU_VIEW,
	
	VID_PHB_SHOW_MENU_LIST_VIEW,
	VID_PHB_SETTINGS_MENU_VIEW,
	VID_PHB_SETTINGS_COPY_TO_SIM_MENU_VIEW,
    VID_PHB_VIEW_CONTACT_VIEW,
	VID_PHB_ADD_EDIT_CONTACT_ADN_VIEW,
	VID_PHB_ADD_EDIT_CONTACT_VIEW,
	VID_PHB_FULLEDIT_VIEW,
	VID_PHB_EDIT_SELECTION_VIEW,
	VID_PHB_SAVE_TO_NUM_TYPE_VIEW,
	VID_PHB_SAVE_TO_VIEW,
	VID_PHB_SHOW_MEMORY_DETAILS,
	VID_PHB_SHOW_GROUP_LIST_VIEW,
	VID_PHB_EDIT_GROUP_VIEW,
	VID_PHB_SETPIC_VIEW,
	VID_PHB_SETRING_VIEW,
	VID_PHB_CHANGE_RINGTONE_VIEW,
	VID_PHB_CHANGE_PIC_VIEW,
	VID_PHB_SELECT_NUM_VIEW,
	VID_PHB_MEMBER_LIST_VIEW,
	VID_PHB_VIEW_ITEM_DETAILS
};

typedef s32 MMI_PHB_AP_VID_E;


/* Widget ID */
enum
{
	// for Tab View

	WID_PHB_TABLIST_TITLEWIDGET = 1,
	WID_PHB_TABLIST_PROPCONTAINER,
	WID_PHB_TABLIST_TABWIDGET,
	WID_PHB_TABLIST_MENUWIDGET,
	WID_PHB_TABLIST_TEXTWIDGET,

	WID_PHB_TITLEWIDGET,
	WID_PHB_MENUWIDGET,
	WID_PHB_POPUPSELECTWIDGET,

	//WID_PHB_BAIJIAXING_BUTTONWIDGET,
	WID_PHB_SHOW_DETAILS_CONTAINER,
	WID_PHB_PADDING_SPACE,
	WID_PHB_TEXTWIDGET_1,
	WID_PHB_TEXTWIDGET_2,
	WID_PHB_TEXTWIDGET_3,
	WID_PHB_TEXTWIDGET_4,
	WID_PHB_TEXTWIDGET_5,
	WID_PHB_TEXTWIDGET_6,
	WID_PHB_TEXTWIDGET_7,
	//MSZ_GARY added 09-07-10 for blacklist
	WID_PHB_TEXTWIDGET_8,
	//MSZ_GARY end

	WID_PHB_VIEW_CONTACT_TITLEWIDGET,
	WID_PHB_VIEW_CONTACT_ABSCONTAINER,
	WID_PHB_VIEW_CONTACT_BG_IMAGEWIDGET,
	WID_PHB_VIEW_CONTACT_HEAD_IMAGEWIDGET,
	WID_PHB_VIEW_CONTACT_HEAD_BLIST_IMAGEWIDGET,
	WID_PHB_VIEW_CONTACT_NAME_TEXTWIDGET,
	WID_PHB_VIEW_CONTACT_DUALSIM_IMAGEWIDGET,
	WID_PHB_VIEW_CONTACT_MENUWIDGET,
//Cosmo, start Fix PR 5035.
	WID_PHB_VIEW_CONTACT_ITEM_DETAIL_SCROLLBARWIDGET,
	WID_PHB_VIEW_CONTACT_ITEM_DETAILS_INPUTWIDGET,
//Cosmo, end Fix PR 5035.
	WID_PHB_ADDEDIT_CONTACT_TITLEWIDGET,
	//WID_PHB_ADDEDIT_CONTACT_MENUWIDGET,
	WID_PHB_ADDEDIT_CONTACT_SCROLLBARWIDGET,
	WID_PHB_ADDEDIT_CONTACT_MFLCONTAINER,
	WID_PHB_ADDEDIT_CONTACT_NAME_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_NUMBER1_TEXTINPUTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_NUMBER2_TEXTINPUTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_NUMBER3_TEXTINPUTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_NUMBER4_TEXTINPUTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_GROUP_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_PICTURE_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_RINGTONE_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_COMPANY_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_DEPARTMENT_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_POSITION_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_ADDRESS_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_EMAIL_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_URL_DOUBLETEXTWIDGET,
	WID_PHB_ADDEDIT_CONTACT_NOTE_DOUBLETEXTWIDGET,

	WID_PHB_FULLEDIT_TITLEWIDGET,
	WID_PHB_FULLEDIT_SCROLLBARWIDGET,
	WID_PHB_FULLEDIT_INPUTWIDGET,
	WID_PHB_SETPIC_TITLEWIDGET,
	WID_PHB_SETPIC_ABSCONTAINER,
	WID_PHB_SETPIC_IMAGEWIDGET,
	WID_PHB_SETRING_TITLEWIDGET,
	WID_PHB_SETRING_VIEW_ABSCONTAINER,
	WID_PHB_SETRING_VIEW_TEXTWIDGET,
	WID_PHB_TABLIST_SEARCH_ABSCONTAINER,
	WID_PHB_TABLIST_SEARCH_IMGWIDGET,
	WID_PHB_TABLIST_SEARCH_BG_IMGWIDGET,
	WID_PHB_TABLIST_SEARCH_INPUTWIDGET,
	WID_PHB_SELECT_NUM_VIEW_TITLEWIDGET,
	WID_PHB_SELECT_NUM_VIEW_MENUWIDGET,

	// member list
	WID_PHB_MEMBER_LIST_TITLEWIDGET,
	WID_PHB_MEMBER_LIST_PROPCONTAINER,
	WID_PHB_MEMBER_LIST_MENUWIDGET
};

typedef s32 MMI_PHB_AP_WID_E;


/* Model ID */
enum
{
	MID_PHB_OPTION_L1_SHOW_CONTACT_LIST	= 1,
    //MID_PHB_OPTION_L2_MANAGE_CONTACT,

	MID_PHB_OPTION_L2_SEND,
	MID_PHB_OPTION_L2_SELECT_SIM,
	MID_PHB_OPTION_L1_VIEW_CONTACT,
//	MID_PHB_OPTION_L2_ADD_NUMBER,
    /*@@~ only support SMS
    MID_PHB_OPTION_L2_SEND_VCARD,
    */
	MID_PHB_OPTION_L1_ADDEDIT_CONTACT,
	MID_PHB_OPTION_L2_CHANGE_TYPE,
	MID_PHB_OPTION_L1_SETPIC,
	MID_PHB_OPTION_L1_SHOW_GROUP_LIST,
	MID_PHB_OPTION_L1_EDIT_GROUP_NAME_LIST,
	MID_PHB_OPTION_L1_EDIT_SEARCH_CONTACT_LIST,
	MID_PHB_OPTION_L1_SHOW_MEMBER_LIST,
	MID_PHB_OPTION_L1_MARK_MODE,
	MID_PHB_OPTION_L1_MARK_MEMBER_LIST,	
	MID_PHB_OPTION_L2_CONTACT_FULLEDITOR,
	MID_PHB_OPTION_L2_MARK,
	MID_PHB_OPTION_L2_COPY,
	MID_PHB_OPTION_L2_ASSIGN_TO_GROUP,
	MID_PHB_OPTION_L2_VCARD,
	MID_PHB_OPTION_L1_BK_EMPTY_LIST
	/* @@~ move the advance menu
	MID_PHB_OPTION_L2_IMPORT_CSV,
	MID_PHB_OPTION_L2_SIM_CONTACTS*/
};

typedef s32 MMI_PHB_AP_MID_E;


#endif /* __MMI_PHBAPP_VIEW_ID_H__ */
