#ifndef __MMI_MESSAGEVIEWERAPP_ID_H__
#define __MMI_MESSAGEVIEWERAPP_ID_H__

typedef enum MsgvwWndId_e_
{
    MSGVW_WND_SmsViewerForm = WND_ID_APP_BASE,
    MSGVW_WND_Class0SmsViewerForm,
    MSGVW_WND_MmsViewerForm,
    MSGVW_WND_MmsSlideSelectionView,
    MSGVW_WND_MmsViewRecipients,
    MSGVW_WND_MmsObjectsList,
    MSGVW_WND_MmsObjectsListOptionMenu,
    MSGVW_WND_ShowOptionMenu,
    MSGVW_WND_ViewDetail,
    MSGVW_WND_PlayAudioView,
#ifdef __MMI_VIEW_MSG_IN_OUTBOX_SUPPORT__
	MSGVW_WND_DualSimMenu,
#endif
    MSGVW_WND_InstallProvisionProfileView
}MsgvwWndId_e;

typedef enum
{
	MMS_VIEWER_DETAIL_VIEW_BEGIN=APP_WDG_START,
    MMS_VIEWER_DETAIL_SCROLLBAR,
    MMS_VIEWER_DETAIL_VIEWPORT,
    MMS_VIEWER_DETAIL_MAIN_CONTAINER,
    MMS_VIEWER_DETAIL_SUBJECT_TXT,
    MMS_VIEWER_DETAIL_TYPE_TXT,
    MMS_VIEWER_DETAIL_DATE_TXT,
    MMS_VIEWER_DETAIL_TIME_TXT,
    MMS_VIEWER_DETAIL_SIZE_TXT,
    MMS_VIEWER_DETAIL_FROM_TXT,
    MMS_VIEWER_DETAIL_TO_TXT,
    MMS_VIEWER_DETAIL_CC_TXT,
    MMS_VIEWER_DETAIL_BCC_TXT,
    MMS_VIEWER_DETAIL_VIEW_END
} MMS_VIEWER_DetailView_e;

enum //SMS_VIEWER_VIEW_enum
{
    //eSMS_VIEWER_MAINCONTAINER=APP_WDG_START,
    eSMS_VIEWER_TITLE_CONTAINER=APP_WDG_START,
    eSMS_VIEWER_TITLE_TXTWDG,
    eSMS_VIEWER_MESSAGE_SWITCH_CONTNR,
    eSMS_VIEWER_MESSAGE_SWITCH_LEFT_ARROW_BTNWDG,
    eSMS_VIEWER_MESSAGE_SWITCH_INFO_TXTWDG,
    eSMS_VIEWER_MESSAGE_SWITCH_RIGHT_ARROW_BTNWDG,
    eSMS_VIEWER_AREA_SCROLLBARWDG,
    eSMS_VIEWER_INPUTWIDGET,
	#ifdef __TOUCH_SCREEN_MMI__
	eSMS_VIEWER_AREA_VPTWDG,
#endif
}; //SMS_VIEWER_VIEW_enum

enum //MMS_VIEWER_VIEW_enum
{
    eMMS_VIEWER_MAINCONTAINER=APP_WDG_START,
    eMMS_VIEWER_TITLE_CONTAINER,
    eMMS_VIEWER_TITLE_TXTWDG,
    eMMS_VIEWER_SUB_TITLE_TXTWDG,
    eMMS_VIEWER_MESSAGE_SWITCH_CONTNR,
    eMMS_VIEWER_MESSAGE_SWITCH_LEFT_ARROW_BTNWDG,
    eMMS_VIEWER_MESSAGE_SWITCH_INFO_TXTWDG,
    eMMS_VIEWER_MESSAGE_SWITCH_RIGHT_ARROW_BTNWDG,
    eMMS_VIEWER_SENDER_WDG,
#ifdef __CALLER_LOCATION__
	eMMS_VIEWER_CALLER_LOCATION_WDG,
#endif
    eMMS_VIEWER_ATTACH_ICON_IMGWDG,
    eMMS_VIEWER_SLIDE_SWITCH_CONTNR,
    eMMS_VIEWER_SLIDE_SWITCH_LEFT_ARROW_BTNWDG,
    eMMS_VIEWER_SLIDE_SWITCH_INFO_TXTWDG,
    eMMS_VIEWER_SLIDE_SWITCH_RIGHT_ARROW_BTNWDG,
    eMMS_VIEWER_AREA_SCROLLBARWDG,
    eMMS_VIEWER_AREA_VPTWDG,
    eMMS_VIEWER_AREA_PROPCONTAINER,
    eMMS_VIEWER_PROPCONTAINER_ICON_LIST,
    eMMS_VIEWER_AUDIO_ICON_IMGWDG,
    eMMS_VIEWER_VIDEO_ICON_IMGWDG,
    eMMS_VIEWER_SLIDE_TEXT_TXTWDG,
    eMMS_VIEWER_SLIDE_IMAGE_CONTNR,
    eMMS_VIEWER_SLIDE_IMAGE_IMGWDG,
}; //MMS_VIEWER_VIEW_enum

typedef enum
{
	MNU_SVA_VIEWER = 0,
	MNU_SVA_VIEW_SENDER,
	MNU_SVA_VIEW_RECIPIENTS,
	MNU_SVA_VIEW_IMAGE,
	MNU_SVA_PLAY_SOUND,
	MNU_SVA_PLAY_VIDEO,
	MNU_SVA_REPLY,
	MNU_SVA_REPLY_SMS,
	MNU_SVA_REPLY_MMS,
	MNU_SVA_FORWARD,
	MNU_SVA_OPEN_LINK,
	MNU_SVA_INSTALL,
	MNU_SVA_DELETE,
	MNU_SVA_CALL_SENDER,
	MNU_SVA_CALL_RECIPIENT,
	MNU_SVA_CALL_NUMBER,
	MNU_SVA_IP_CALL,
	MNU_SVA_PLAY_MESSAGE,
	MNU_SVA_JUMP_TO,
	MNU_SVA_SAVE_SENDER,
	MNU_SVA_SAVE_TO_NEWSENDER,
	MNU_SVA_SAVE_TO_EXISTSENDER,
	MNU_SVA_SAVE_RECIPIENT,
	MNU_SVA_SAVE_TO_NEWRECIPIENT,
	MNU_SVA_SAVE_TO_EXISTRECIPIENT,
	MNU_SVA_SAVE_NUMBER,
	MNU_SVA_SAVE_TO_NEWNUM,
	MNU_SVA_SAVE_TO_EXISTNUM,
	MNU_SVA_SAVE_EMAIL,
	MNU_SVA_SAVE_TO_NEWEMAIL,
	MNU_SVA_SAVE_TO_EXISTEMAIL,
	MNU_SVA_SAVE_URL,
	MNU_SVA_SAVE_AS_CONTACT,
	MNU_SVA_SAVE_AS_BOOKMARK,
	MNU_SVA_SAVE_OBJECTS,
	MNU_SVA_MOVE_TO,
	MNU_SVA_MOVE_TO_SIM,
	MNU_SVA_MOVE_TO_PHONE,
	MNU_SVA_MOVE_TO_PRIVATE,
	MNU_SVA_MOVE_TO_INBOX,
	MNU_SVA_MOVE_TO_SIM_MASTER,
	MNU_SVA_MOVE_TO_SIM_SLAVE,
	MNU_SVA_OBJECTS,
	MNU_SVA_OPEN,
	MNU_SVA_SAVE,
	MNU_SVA_SEND,
	MNU_SVA_MMS,
	MNU_SVA_BLUETOOTH,
	MNU_SVA_COPY_TO_PHONE,
	MNU_SVA_COPY_TO_SIM,
	MNU_SVA_COPY_TO_SIM_MASTER,
	MNU_SVA_COPY_TO_SIM_SLAVE,
	MNU_SVA_VIEW_DETAILS,
	MNU_SVA_VIDEO_CALL_SENDER,
	MNU_SVA_VIDEO_CALL_RECIPIENT,
	MNU_SVA_VIDEO_CALL_NUMBER,
#ifdef __MMI_VIEW_MSG_IN_OUTBOX_SUPPORT__
	MNU_SVA_RESEND,
	MNU_SVA_MOVE_TO_DRAFT,
#endif
}SVAMenuId_e;

enum e_DualSIM_MenuItem
{
    MNU_SVA_MASTERSIM =0,
    MNU_SVA_SLAVESIM
};

#endif //__MMI_MESSAGEVIEWERAPP_ID_H__

