
#ifndef _MENU_STATE_GENERAL_SETTING_MENU_H_
#define _MENU_STATE_GENERAL_SETTING_MENU_H_

/*===========================================================================
 * Include file
 *===========================================================================*/

#include "ahc_common.h"
#include "ahc_gui.h"

/*===========================================================================
 * Enum define
 *===========================================================================*/

typedef enum {
    ITEMID_BEEP=1,
#if (MENU_GENERAL_BEEP_ON_EN)
    ITEMID_BEEP_ON,
#endif
#if (MENU_GENERAL_BEEP_OFF_EN)
    ITEMID_BEEP_OFF,
#endif

    ITEMID_LCD_BRIGHTNESS,
#if (MENU_GENERAL_LCD_BRIGHTNESS_NORMAL_EN)
    ITEMID_LCD_BRIGHT_NORMAL,
#endif
#if (MENU_GENERAL_LCD_BRIGHTNESS_BRIGHTNESS_EN)
    ITEMID_LCD_BRIGHT_BRIGHT,
#endif

    ITEMID_LCD_ROTATE,
#if (MENU_GENERAL_LCD_ROTATE_ON_EN)
	ITEMID_LCD_ROTATE_ON,
#endif
#if (MENU_GENERAL_LCD_ROTATE_OFF_EN)
	ITEMID_LCD_ROTATE_OFF,
#endif

    ITEMID_AUTO_POWER_OFF,
#if (MENU_GENERAL_AUTO_POWEROFF_NEVER_EN)
    ITEMID_AUTO_POWER_OFF_NEVER,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_15SEC_EN)
    ITEMID_AUTO_POWER_OFF_15SEC,
#endif

#if (MENU_GENERAL_AUTO_POWEROFF_30SEC_EN)
    ITEMID_AUTO_POWER_OFF_30SEC,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_1MIN_EN)
    ITEMID_AUTO_POWER_OFF_1MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_2MIN_EN)
    ITEMID_AUTO_POWER_OFF_2MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_3MIN_EN)
    ITEMID_AUTO_POWER_OFF_3MIN,
#endif
#if (MENU_GENERAL_AUTO_POWEROFF_5MIN_EN)
    ITEMID_AUTO_POWER_OFF_5MIN,
#endif

    ITEMID_CLOCK_SETTINGS,
    ITEMID_DATETIME_YEAR,
    ITEMID_DATETIME_MONTH,
    ITEMID_DATETIME_DAY,
    ITEMID_DATETIME_HOUR,
    ITEMID_DATETIME_MINUTE,
    ITEMID_DATETIME_SEC,
    ITEMID_DATETIME_OK,
    ITEMID_DATETIME_CANCEL,

    ITEMID_DATETIME_FORMAT,
#if (MENU_GENERAL_DATE_FORMAT_NONE_EN)
    ITEMID_DATETIME_NONE,
#endif
#if (MENU_GENERAL_DATE_FORMAT_YMD_EN)
    ITEMID_DATETIME_YMD,
#endif
#if (MENU_GENERAL_DATE_FORMAT_MDY_EN)
    ITEMID_DATETIME_MDY,
#endif
#if (MENU_GENERAL_DATE_FORMAT_DMY_EN)
    ITEMID_DATETIME_DMY,
#endif

    ITEMID_LANGUAGE,

#if (MENU_GENERAL_LANGUAGE_ENGLISH_EN)
    ITEMID_LANGUAGES_ENGLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_SPANISH_EN)
    ITEMID_LANGUAGES_SPANISH,
#endif
#if (MENU_GENERAL_LANGUAGE_PORTUGUESE_EN)
    ITEMID_LANGUAGES_PORTUGUESE,
#endif
#if (MENU_GENERAL_LANGUAGE_RUSSIAN_EN)
    ITEMID_LANGUAGES_RUSSIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SCHINESE_EN)
    ITEMID_LANGUAGES_SCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_TCHINESE_EN)
    ITEMID_LANGUAGES_TCHINESE,
#endif
#if (MENU_GENERAL_LANGUAGE_GERMAN_EN)
    ITEMID_LANGUAGES_GERMAN,
#endif
#if (MENU_GENERAL_LANGUAGE_ITALIAN_EN)
    ITEMID_LANGUAGES_ITALIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_LATVIAN_EN)
    ITEMID_LANGUAGES_LATVIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_POLISH_EN)
    ITEMID_LANGUAGES_POLISH,
#endif
#if (MENU_GENERAL_LANGUAGE_ROMANIAN_EN)
    ITEMID_LANGUAGES_ROMANIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_SLOVAK_EN)
    ITEMID_LANGUAGES_SLOVAK,
#endif
#if (MENU_GENERAL_LANGUAGE_UKRANINIAN_EN)
    ITEMID_LANGUAGES_UKRANINIAN,
#endif
#if (MENU_GENERAL_LANGUAGE_FRENCH_EN)
    ITEMID_LANGUAGES_FRENCH,
#endif
#if (MENU_GENERAL_LANGUAGE_JAPANESE_EN)
    ITEMID_LANGUAGES_JAPANESE,
#endif
#if (MENU_GENERAL_LANGUAGE_KOREAN_EN)
    ITEMID_LANGUAGES_KOREAN,
#endif
#if (MENU_GENERAL_LANGUAGE_CZECH_EN)
    ITEMID_LANGUAGES_CZECH,
#endif


    ITEMID_TV_SYSTEM,
#if (MENU_GENERAL_TV_SYSTEM_NTSC_EN)
    ITEMID_TV_NTSC,
#endif
#if (MENU_GENERAL_TV_SYSTEM_PAL_EN)
    ITEMID_TV_PAL,
#endif

    ITEMID_HDMI_OUTPUT,
#if (MENU_GENERAL_HDMI_OUTPUT_1080P_EN)
    ITEMID_HDMI_OUTPUT_1080P,
#endif
#if (MENU_GENERAL_HDMI_OUTPUT_1080I_EN)
    ITEMID_HDMI_OUTPUT_1080I,
#endif
#if (MENU_GENERAL_HDMI_OUTPUT_720P_EN)
    ITEMID_HDMI_OUTPUT_720P,
#endif
#if (MENU_GENERAL_HDMI_OUTPUT_480P_EN)
    ITEMID_HDMI_OUTPUT_480P,
#endif

    ITEMID_RESET_SETUP,
#if (MENU_GENERAL_RESET_SETUP_YES_EN)
    ITEMID_RESET_YES,
#endif
#if (MENU_GENERAL_RESET_SETUP_NO_EN)
    ITEMID_RESET_NO,
#endif

    ITEMID_FLICKER,
#if (MENU_GENERAL_FLICKER_50HZ_EN)
    ITEMID_FLICKER_50HZ,
#endif
#if (MENU_GENERAL_FLICKER_60HZ_EN)
    ITEMID_FLICKER_60HZ,
#endif

    ITEMID_GSENSOR,
    ITEMID_GSENSOR_CLOSE,
    ITEMID_GSENSOR_2G,
    ITEMID_GSENSOR_3G,
    ITEMID_GSENSOR_4G,
    ITEMID_GSENSOR_5G,
    ITEMID_GSENSOR_6G,

    ITEMID_GPS_INFO_CHART,
    ITEMID_GPS_INFO,

	ITEMID_TIME_ZONE,           //0x43
	ITEMID_TIME_ZONE_GMT_M_12,  //01
	ITEMID_TIME_ZONE_GMT_M_11,
	ITEMID_TIME_ZONE_GMT_M_10,
	ITEMID_TIME_ZONE_GMT_M_9,
	ITEMID_TIME_ZONE_GMT_M_8,   //05
	ITEMID_TIME_ZONE_GMT_M_7,
	ITEMID_TIME_ZONE_GMT_M_6,
	ITEMID_TIME_ZONE_GMT_M_5,
	ITEMID_TIME_ZONE_GMT_M_4,
	ITEMID_TIME_ZONE_GMT_M_3_30,//10
	ITEMID_TIME_ZONE_GMT_M_3,
	ITEMID_TIME_ZONE_GMT_M_2,
	ITEMID_TIME_ZONE_GMT_M_1,
	ITEMID_TIME_ZONE_GMT,
	ITEMID_TIME_ZONE_GMT_P_1,   //15
	ITEMID_TIME_ZONE_GMT_P_2,
	ITEMID_TIME_ZONE_GMT_P_3,
	ITEMID_TIME_ZONE_GMT_P_3_30,
	ITEMID_TIME_ZONE_GMT_P_4,
	ITEMID_TIME_ZONE_GMT_P_4_30,//20
	ITEMID_TIME_ZONE_GMT_P_5,
	ITEMID_TIME_ZONE_GMT_P_5_30,
	ITEMID_TIME_ZONE_GMT_P_5_45,
	ITEMID_TIME_ZONE_GMT_P_6,
	ITEMID_TIME_ZONE_GMT_P_6_30,//25
	ITEMID_TIME_ZONE_GMT_P_7,
	ITEMID_TIME_ZONE_GMT_P_8,
	ITEMID_TIME_ZONE_GMT_P_9,
	ITEMID_TIME_ZONE_GMT_P_9_30,
	ITEMID_TIME_ZONE_GMT_P_10,  //30
	ITEMID_TIME_ZONE_GMT_P_11,
	ITEMID_TIME_ZONE_GMT_P_12,
	ITEMID_TIME_ZONE_GMT_P_13,  //33

    ITEMID_FW_VERSION_INFO,
    ITEMID_FW_VERSION,

	ITEMID_USB_FUNCTION,
#if (MENU_GENERAL_USB_FUNCTION_MSDC_EN)
	ITEMID_USB_MSDC,
#endif
#if (MENU_GENERAL_USB_FUNCTION_PCAM_EN)
	ITEMID_USB_PCAM,
#endif

	ITEMID_LCD_POWER_SAVE,
#if (MENU_GENERAL_LCD_POWER_SAVE_OFF_EN)
	ITEMID_LCD_POWER_SAVE_OFF,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_1MIN_EN)
	ITEMID_LCD_POWER_SAVE_1MIN,
#endif
#if (MENU_GENERAL_LCD_POWER_SAVE_3MIN_EN)
	ITEMID_LCD_POWER_SAVE_3MIN,
#endif

	ITEMID_LED_FLASH,
#if (MENU_GENERAL_FLASH_LED_ON_EN)
	ITEMID_LED_FLASH_ON,
#endif
#if (MENU_GENERAL_FLASH_LED_OFF_EN)
	ITEMID_LED_FLASH_OFF,
#endif

	ITEMID_GSENSOR_SENSITIVITY,
#if (MENU_GENERAL_GSENSOR_OFF_EN)
	ITEMID_GSENSOR_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL0_EN)
	ITEMID_GSENSOR_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL1_EN)
	ITEMID_GSENSOR_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL2_EN)
	ITEMID_GSENSOR_SENSITIVITY_L2,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL3_EN)
	ITEMID_GSENSOR_SENSITIVITY_L3,
#endif
#if (MENU_GENERAL_GSENSOR_LEVEL4_EN)
	ITEMID_GSENSOR_SENSITIVITY_L4,
#endif

	ITEMID_DATE_LOGO_STAMP,
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_LOGO_EN)
	ITEMID_STAMP_DATELOGO,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_DATE_EN)
	ITEMID_STAMP_DATE,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_LOGO_EN)
	ITEMID_STAMP_LOGO,
#endif
#if (MENU_GENERAL_DATE_LOGO_STAMP_OFF_EN)
	ITEMID_STAMP_OFF,
#endif

	ITEMID_GPS_STAMP,
#if (MENU_GENERAL_GPS_STAMP_ON_EN)
	ITEMID_GPS_STAMP_ON,
#endif
#if (MENU_GENERAL_GPS_STAMP_OFF_EN)
	ITEMID_GPS_STAMP_OFF,
#endif

	ITEMID_SPEED_STAMP,
#if (MENU_GENERAL_SPEED_STAMP_ON_EN)
	ITEMID_SPEED_STAMP_ON,
#endif
#if (MENU_GENERAL_SPEED_STAMP_OFF_EN)
	ITEMID_SPEED_STAMP_OFF,
#endif

	ITEMID_MOTION_DETECT,
#if (MENU_GENERAL_MOTION_DTC_OFF_EN)
	ITEMID_MOTION_DETECT_OFF,
#endif
#if (MENU_GENERAL_MOTION_DTC_LOW_EN)
	ITEMID_MOTION_DETECT_LOW,
#endif
#if (MENU_GENERAL_MOTION_DTC_MID_EN)
	ITEMID_MOTION_DETECT_MID,
#endif
#if (MENU_GENERAL_MOTION_DTC_HIGH_EN)
	ITEMID_MOTION_DETECT_HIGH,
#endif

	ITEMID_BOOTUP_MODE,
#if (MENU_GENERAL_BOOT_UP_VR_MODE_EN)
	ITEMID_BOOTUP_MODE_VR,
#endif
#if (MENU_GENERAL_BOOT_UP_DSC_MODE_EN)
	ITEMID_BOOTUP_MODE_DSC,
#endif
#if (MENU_GENERAL_BOOT_UP_BURST_MODE_EN)
	ITEMID_BOOTUP_MODE_BURST,
#endif
#if (MENU_GENERAL_BOOT_UP_TIMELAPSE_MODE_EN)
	ITEMID_BOOTUP_MODE_TIMELAPSE,
#endif

#if (MENU_GENERAL_POWERON_GSENSOR_EN)
	ITEMID_GSENSOR_POWERON_SENSITIVITY,
	#if (MENU_GENERAL_POWERON_GSENSOR_OFF_EN)
	ITEMID_GSENSOR_POWERON_SENSITIVITY_OFF,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL0_EN)
	ITEMID_GSENSOR_POWERON_SENSITIVITY_L0,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL1_EN)
	ITEMID_GSENSOR_POWERON_SENSITIVITY_L1,
#endif
#if (MENU_GENERAL_POWER_ON_GSENSOR_LEVEL2_EN)
	ITEMID_GSENSOR_POWERON_SENSITIVITY_L2,
#endif
#endif

#if (MENU_GENERAL_WIFI_EN)
	ITEMID_WIFI_MODE,
#if (MENU_GENERAL_WIFI_ON_EN)
	ITEMID_WIFI_MODE_ON,
#endif
#if (MENU_GENERAL_WIFI_OFF_EN)
	ITEMID_WIFI_MODE_OFF,
#endif
#endif

#if (MENU_GENERAL_DRIVER_ID_SETTING_EN)
	ITEMID_DRIVER_ID_SETTINGS,
	ITEMID_DRIVER_ID_D0,
	ITEMID_DRIVER_ID_D1,
	ITEMID_DRIVER_ID_D2,
	ITEMID_DRIVER_ID_D3,
	ITEMID_DRIVER_ID_D4,
	ITEMID_DRIVER_ID_D5,
	ITEMID_DRIVER_ID_D6,
	ITEMID_DRIVER_ID_D7,
	ITEMID_DRIVER_ID_D8,
	ITEMID_DRIVER_ID_OK,
	ITEMID_DRIVER_ID_CANCEL,
#endif

#if MENU_RD_LDWS_CALIBRATION_EN
	ITEMID_LDWS_CALIBRATION,
	ITEMID_SUB_LDWS_CALIBRATION,
#endif
#if (MENU_GENERAL_LDWS_CALIBRATION_EN)
	ITEMID_USER_LDWS_CALIBRATION,
	ITEMID_SUB_USER_LDWS_CALIBRATION,
#endif

#if (VIRTUAL_KEY_BOARD)
	ITEMID_VIRUAL_KEYBOARD,
	ITEMID_KEYBOARD,
#endif

	ITMEID_PQ_CONTRAST,
#if (MENU_GENERAL_PQ_CONTRAST_EN)
	ITMEID_PQ_CONTRAST_DEC,
	ITMEID_PQ_CONTRAST_INC,
#endif
	ITEMID_PQ_BRIGHTNESS,
#if (MENU_GENERAL_PQ_BRIGHTNESS_EN)
	ITEMID_PQ_BRIGHTNESS_DEC,
	ITEMID_PQ_BRIGHTNESS_INC,
#endif
	ITEMID_PQ_SATURATION,
#if (MENU_GENERAL_PQ_SATURATION_EN)
	ITEMID_PQ_SATURATION_DEC,
	ITEMID_PQ_SATURATION_INC,
#endif
	ITEMID_PQ_COLORTEMP,
#if (MENU_GENERAL_PQ_COLORTEMP_EN)
	ITEMID_PQ_COLORTEMP_OFF,
	ITEMID_PQ_COLORTEMP_MODE1,
	ITEMID_PQ_COLORTEMP_MODE2,
	ITEMID_PQ_COLORTEMP_MODE3,
	ITEMID_PQ_COLORTEMP_MODE4,
#endif

	ITEMID_GENERAL_END

} GENERALSETTINGITEMID;

#endif //_MENU_STATE_GENERAL_SETTING_MENU_H_


