
#ifndef _MENU_STATE_MANUAL_SETTING_MENU_H_
#define _MENU_STATE_MANUAL_SETTING_MENU_H_

/*===========================================================================
 * Include file
 *===========================================================================*/

#include "ahc_common.h"
#include "ahc_gui.h"

/*===========================================================================
 * Enum define
 *===========================================================================*/

typedef enum {
    ITEMID_SCENE=1,
#if (MENU_MANUAL_SCENE_AUTO_EN)
    ITEMID_SCENE_AUTO     ,
#endif
#if (MENU_MANUAL_SCENE_SPORT_EN)
    ITEMID_SCENE_SPORTS   ,
#endif
#if (MENU_MANUAL_SCENE_PORTRAIT_EN)
    ITEMID_SCENE_PORTRAIT   ,
#endif
#if (MENU_MANUAL_SCENE_LANDSCAPE_EN)
    ITEMID_SCENE_LANDSCAPE   ,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_PORTRAIT_EN)
    ITEMID_SCENE_TWILIGHT_PORTRAIT ,
#endif
#if (MENU_MANUAL_SCENE_TWILIGHT_EN)
    ITEMID_SCENE_TWILIGHT ,
#endif
#if (MENU_MANUAL_SCENE_SNOW_EN)
    ITEMID_SCENE_SNOW     ,
#endif
#if (MENU_MANUAL_SCENE_BEACH_EN)
    ITEMID_SCENE_BEACH    ,
#endif
#if (MENU_MANUAL_SCENE_FIREWORKS_EN)
    ITEMID_SCENE_FIREWORKS,
#endif

    ITEMID_FOCUSWINDOW    ,
#if (MENU_MANUAL_FOCUS_MULTI_EN)
    ITEMID_FOCUSWINDOW_MULTI ,
#endif
#if (MENU_MANUAL_FOCUS_CENTERSPOT_EN)
    ITEMID_FOCUSWINDOW_CENTER_SPOT,
#endif
    ITEMID_FOCUSWINDOW_TOUCH_SPOT ,

    ITEMID_FOCUSRANGE    ,
#if (MENU_MANUAL_FOCUS_RANGE_NORMAL_EN)
    ITEMID_FOCUSRANGE_NORMAL ,
#endif
#if (MENU_MANUAL_FOCUS_RANGE_MACRO_EN)
    ITEMID_FOCUSRANGE_MACRO,
#endif

    ITEMID_METERING    ,
#if (MENU_MANUAL_METERING_MULTI_EN)
    ITEMID_METERING_MULTI ,
#endif
#if (MENU_MANUAL_METERING_WEIGHTED_EN)
    ITEMID_METERING_CENTER_WEIGHTED,
#endif
#if (MENU_MANUAL_METERING_CENTER_SPOT_EN)
    ITEMID_METERING_CENTER_SPOT,
#endif
    ITEMID_METERING_TOUCH_SPOT,

    ITEMID_EV,
#if (MENU_MANUAL_EV_N20_EN)
    ITEMID_EV_N20,
#endif
#if (MENU_MANUAL_EV_N17_EN)
    ITEMID_EV_N17,
#endif
#if (MENU_MANUAL_EV_N13_EN)
    ITEMID_EV_N13,
#endif
#if (MENU_MANUAL_EV_N10_EN)
    ITEMID_EV_N10,
#endif
#if (MENU_MANUAL_EV_N07_EN)
    ITEMID_EV_N07,
#endif
#if (MENU_MANUAL_EV_N03_EN)
    ITEMID_EV_N03,
#endif
#if (MENU_MANUAL_EV_00_EN)
    ITEMID_EV_00,
#endif
#if (MENU_MANUAL_EV_P03_EN)
    ITEMID_EV_P03,
#endif
#if (MENU_MANUAL_EV_P07_EN)
    ITEMID_EV_P07,
#endif
#if (MENU_MANUAL_EV_P10_EN)
    ITEMID_EV_P10,
#endif
#if (MENU_MANUAL_EV_P13_EN)
    ITEMID_EV_P13,
#endif
#if (MENU_MANUAL_EV_P17_EN)
    ITEMID_EV_P17,
#endif
#if (MENU_MANUAL_EV_P20_EN)
    ITEMID_EV_P20,
#endif

    ITEMID_ISO,
#if (MENU_MANUAL_ISO_AUTO_EN)
    ITEMID_ISO_AUTO,
#endif
#if (MENU_MANUAL_ISO_100_EN)
    ITEMID_ISO_100,
#endif
#if (MENU_MANUAL_ISO_200_EN)
    ITEMID_ISO_200,
#endif
#if (MENU_MANUAL_ISO_400_EN)
    ITEMID_ISO_400,
#endif
#if (MENU_MANUAL_ISO_800_EN)
    ITEMID_ISO_800,
#endif
#if (MENU_MANUAL_ISO_1600_EN)
    ITEMID_ISO_1600,
#endif
#if (MENU_MANUAL_ISO_3200_EN)
    ITEMID_ISO_3200,
#endif

    ITEMID_WB,
#if (MENU_MANUAL_WB_AUTO_EN)
    ITEMID_WB_AUTO,
#endif
#if (MENU_MANUAL_WB_DAYLIGHT_EN)
    ITEMID_WB_DAYLIGHT,
#endif
#if (MENU_MANUAL_WB_CLOUDY_EN)
    ITEMID_WB_CLOUDY,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT1_EN)
    ITEMID_WB_FLUORESCENT1,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT2_EN)
    ITEMID_WB_FLUORESCENT2,
#endif
#if (MENU_MANUAL_WB_FLUORESCENT3_EN)
    ITEMID_WB_FLUORESCENT3,
#endif
#if (MENU_MANUAL_WB_INCANDESCENT_EN)
    ITEMID_WB_INCANDESCENT,
#endif
#if (MENU_MANUAL_WB_FLASH_EN)
    ITEMID_WB_FLASH,
#endif
#if (MENU_MANUAL_WB_ONEPUSH_EN)
    ITEMID_WB_ONEPUSH,
#endif
#if (MENU_MANUAL_WB_ONE_PUSH_SET_EN)
    ITEMID_WB_ONE_PUSH_SET,
#endif

    ITEMID_COLOR,
#if (MENU_MANUAL_COLOR_NATURAL_EN)
    ITEMID_COLOR_NATURAL,
#endif
#if (MENU_MANUAL_COLOR_VIVID_EN)
    ITEMID_COLOR_VIVID,
#endif
#if (MENU_MANUAL_COLOR_PALE_EN)
    ITEMID_COLOR_PALE,
#endif

    ITEMID_EFFECT,
#if (MENU_MANUAL_EFFECT_NORMAL_EN)
    ITEMID_EFFECT_NORMAL,
#endif
#if (MENU_MANUAL_EFFECT_SEPIA_EN)
    ITEMID_EFFECT_SEPIA,
#endif
#if (MENU_MANUAL_EFFECT_BLACK_WHITE_EN)
    ITEMID_EFFECT_BLACK_WHITE,
#endif
#if (MENU_MANUAL_EFFECT_EMBOSS_EN)
    ITEMID_EFFECT_EMBOSS,
#endif
#if (MENU_MANUAL_EFFECT_NEGATIVE_EN)
    ITEMID_EFFECT_NEGATIVE,
#endif
#if (MENU_MANUAL_EFFECT_SKETCH_EN)
    ITEMID_EFFECT_SKETCH,
#endif
#if (MENU_MANUAL_EFFECT_OIL_EN)
    ITEMID_EFFECT_OIL,
#endif
#if (MENU_MANUAL_EFFECT_CRAYON_EN)
    ITEMID_EFFECT_CRAYON,
#endif
#if (MENU_MANUAL_EFFECT_BEAUTY_EN)
    ITEMID_EFFECT_BEAUTY,
#endif

    ITEMID_FACETOUCH,
#if (MENU_MANUAL_FACE_DETECT_ON_EN)
    ITEMID_FACETOUCH_FD,
#endif
#if (MENU_MANUAL_FACE_DETECT_OFF_EN)
    ITEMID_FACETOUCH_OFF,
#endif

    ITEMID_SMILE_DETECTION,
#if (MENU_MANUAL_SMILE_DETECT_OFF_EN)
    ITEMID_SMILED_OFF,
#endif
#if (MENU_MANUAL_SMILE_DETECT_1PEOPLE_EN)
    ITEMID_SMILED_1PEOPLE,
#endif
#if (MENU_MANUAL_SMILE_DETECT_2PEOPLE_EN)
    ITEMID_SMILED_2PEOPLE,
#endif

    ITEMID_SMILE_SENSITIVITY,
#if (MENU_MANUAL_SMILE_SEN_LOW_EN)
	ITEMID_SMILE_SENSITI_LOW,
#endif
#if (MENU_MANUAL_SMILE_SEN_HIGH_EN)
    ITEMID_SMILE_SENSITI_HIGH,
#endif

    ITEMID_CONTRAST,
    ITEMID_CONTRAST_INC,
    ITEMID_CONTRAST_DEC,

    ITEMID_SATURATION,
    ITEMID_SATURATION_INC,
    ITEMID_SATURATION_DEC,

    ITEMID_SHARPNESS,
    ITEMID_SHARPNESS_INC,
    ITEMID_SHARPNESS_DEC,

    ITEMID_GAMMA,
    ITEMID_GAMMA_INC,
    ITEMID_GAMMA_DEC,
    
    ITEMID_COLORTEMP,
#if (MENU_MANUAL_COLORTEMP_DEF_EN)
    ITEMID_COLORTEMP_DEF,
#endif
#if (MENU_MANUAL_COLORTEMP_3500K_EN)
    ITEMID_COLORTEMP_3500K,
#endif
#if (MENU_MANUAL_COLORTEMP_9300K_EN)
    ITEMID_COLORTEMP_9300K,
#endif
#if (MENU_MANUAL_COLORTEMP_3000K_EN)
    ITEMID_COLORTEMP_3000K,
#endif

    MAX_MANUALSETTINGITEMID
}MANUALSETTINGITEMID;

#if (MENU_MANUAL_CONTRAST_EN || MENU_STILL_CONTRAST_EN || MENU_MOVIE_CONTRAST_EN)
AHC_BOOL MenuItemContrastAdjust(PSMENUITEM pItem, AHC_BOOL bIsHover);
#endif

#if (MENU_MANUAL_SATURATION_EN || MENU_STILL_SATURATION_EN || MENU_MOVIE_SATURATION_EN)
AHC_BOOL MenuItemSaturationAdjust(PSMENUITEM pItem, AHC_BOOL bIsHover);
#endif

#if (MENU_MANUAL_SHARPNESS_EN || MENU_STILL_SHARPNESS_EN || MENU_MOVIE_SHARPNESS_EN)
AHC_BOOL MenuItemSharpnessAdjust(PSMENUITEM pItem, AHC_BOOL bIsHover);
#endif

#if (MENU_MANUAL_GAMMA_EN || MENU_STILL_GAMMA_EN || MENU_MOVIE_GAMMA_EN)
AHC_BOOL MenuItemGammaAdjust(PSMENUITEM pItem, AHC_BOOL bIsHover);
#endif


#endif //_MENU_STATE_MANUAL_SETTING_MENU_H_


