
#ifndef _MENU_STATE_EDIT_TOOL_MENU_H_
#define _MENU_STATE_EDIT_TOOL_MENU_H_

/*===========================================================================
 * Include file 
 *===========================================================================*/ 

#include "ahc_common.h"
#include "ahc_gui.h"

/*===========================================================================
 * Enum define 
 *===========================================================================*/ 

typedef enum {
    ITEMID_DELETE		 = 1,
    ITEMID_DELETE_ALL,
    ITEMID_DELETE_ALL_YES,
    ITEMID_DELETE_ALL_NO,
    ITEMID_DELETE_GLOCK,
    ITEMID_DELETE_GLOCK_YES,
    ITEMID_DELETE_GLOCK_NO,
    ITEMID_PROTECT,
    ITEMID_PROTECT_ALL,
    ITEMID_PROTECT_ALL_YES,
    ITEMID_PROTECT_ALL_NO,
    ITEMID_DELETE_ONE,
    ITEMID_DELETE_ONE_YES,
    ITEMID_DELETE_ONE_NO,
    ITEMID_PROTECT_ONE,
    ITEMID_PROTECT_ONE_YES,
    ITEMID_PROTECT_ONE_NO,
    ITEMID_UNPROTECT_ONE,
    ITEMID_UNPROTECT_ONE_YES,
    ITEMID_UNPROTECT_ONE_NO,
    ITEMID_UNPROTECT_ALL,
    ITEMID_UNPROTECT_ALL_YES,
    ITEMID_UNPROTECT_ALL_NO,
	ITEMID_DELETE_ALL_VIDEO,
	ITEMID_DELETE_ALL_VIDEO_YES,
	ITEMID_DELETE_ALL_VIDEO_NO,
	ITEMID_DELETE_ALL_IMAGE,
	ITEMID_DELETE_ALL_IMAGE_YES,
	ITEMID_DELETE_ALL_IMAGE_NO,
	ITEMID_DELETE_ALL_FILE,
	ITEMID_DELETE_ALL_FILE_YES,
	ITEMID_DELETE_ALL_FILE_NO,
	ITEMID_PROTECT_ALL_VIDEO,
	ITEMID_PROTECT_ALL_VIDEO_YES,
	ITEMID_PROTECT_ALL_VIDEO_NO,
	ITEMID_PROTECT_ALL_IMAGE,
	ITEMID_PROTECT_ALL_IMAGE_YES,
	ITEMID_PROTECT_ALL_IMAGE_NO,
	ITEMID_PROTECT_ALL_FILE,
	ITEMID_PROTECT_ALL_FILE_YES,
	ITEMID_PROTECT_ALL_FILE_NO,
	ITEMID_UNPROTECT_ALL_VIDEO,
	ITEMID_UNPROTECT_ALL_VIDEO_YES,
	ITEMID_UNPROTECT_ALL_VIDEO_NO,
	ITEMID_UNPROTECT_ALL_IMAGE,
	ITEMID_UNPROTECT_ALL_IMAGE_YES,
	ITEMID_UNPROTECT_ALL_IMAGE_NO,
	ITEMID_UNPROTECT_ALL_FILE,
	ITEMID_UNPROTECT_ALL_FILE_YES,
	ITEMID_UNPROTECT_ALL_FILE_NO,
	ITEMID_DELETE_FILE,
	ITEMID_DELETE_CANCEL,
	ITEMID_DELETE_FILE_LAST,
	ITEMID_DELETE_FILE_ALL,
	ITEMID_DELETE_VIDEO_ONE,
	ITEMID_DELETE_IMAGE_ONE,
	ITEMID_DELETE_FILE_ONE,
	ITEMID_PROTECT_VIDEO_ONE,
	ITEMID_PROTECT_IMAGE_ONE,
	ITEMID_PROTECT_FILE_ONE,
	ITEMID_UNPROTECT_VIDEO_ONE,
	ITEMID_UNPROTECT_IMAGE_ONE,
	ITEMID_UNPROTECT_FILE_ONE
		
} EDITTOOLITEMID;

#endif //_MENU_STATE_EDIT_TOOL_MENU_H_


