#ifndef __MMI_BTAPP_ID_H__
#define __MMI_BTAPP_ID_H__
#define BTSRV_PINCODE_LEN_RS 16
#define BTSRV_DEVICE_NAME_LEN_RS 40
typedef enum
{
    BTAPP_WND_MAIN = WND_ID_APP_BASE,
    BTAPP_WND_SETTING,
    BTAPP_WND_DEVICELIST_OPTIONMENU,
    BTAPP_WND_ADDDEVICETOMENU,
    BTAPP_WND_ADDDEVICETOMENU_BTFOUND,
    BTAPP_WND_ADDDEVICETOMENU_BTPAIRED,
    BTAPP_WND_ADDDEVICE_ENTERPINCODE,
    BTAPP_WND_INPUTSHORTNAME,
    BTAPP_WND_INPUTSHORTNAMEOPTIONMENU,
    BTAPP_WND_INPUTLOCALNAME,
    BTAPP_WND_INPUTLOCALNAMEOPTIONMENU,
    BTAPP_WND_SEARCHING,
    BTAPP_WND_DEVICE_INFORMATION
} BtAppWndId_e;

typedef enum
{
	MNU_BT_BT_MAIN_MENU = 0,
	MNU_BT_TURN_ON,
	MNU_BT_TURN_OFF,
	MNU_BT_PAIRED_DEVICES,
	MNU_BT_SEARCH_DEVICES,
	MNU_BT_SETTINGS,
	MNU_BT_BT_DEVICE_OPTION,
	MNU_BT_CONNECT,
	MNU_BT_DISCONNECT,
	MNU_BT_SEARCH,
	MNU_BT_ASSIGN_SHORT_NAME,
	MNU_BT_SET_AS_AUTHORIZED,
	MNU_BT_SET_AS_UNAUTHORIZED,
	MNU_BT_DELETE,
	MNU_BT_DELETE_ALL,
	MNU_BT_BT_SETTING_MENU,
	MNU_BT_VISIBILITY,
	MNU_BT_MY_PHONE_NAME,
	MNU_BT_RECEIVE_FOLDER,
	MNU_BT_DEVICE_INFORMATION,
	MNU_BT_AUDIO_DEVICE,
}BtMenuId_e;

#endif  //__MMI_BTAPP_ID_H__

