
#define	WdgAbsDefRC(...)
#define	WdgViewportDefRC(...)
#define	WdgButtonDefRC(...)
#define	WdgImageDefRC(...)
#define	WdgOverlayImageDefRC(...)
#define	WdgTextDefRC(...)
#define	WdgInputDefRC(...)
#define	WdgOsdDefRC(...)
#define	WdgTabDefRC(...)
#define	WdgSwitchIconDefRC(...)
#define	WdgSwitchIconItemDefRC(...)
#define	WdgProgressDefRC(...)
#define	WdgIpDefRC(...)
#define	WdgFadeoutDefRC(...)
#define	WdgPulldownDefRC(...)
#define	WdgIndicatorDefRC(...)
#define	WdgTextBubbleDefRC(...)
#define	WdgTimeDefRC(...)
#define	WdgFcDateDefRC(...)
#define	WdgDateDefRC(...)
#define	WdgFcTimeDefRC(...)
#define	WdgMenuDefRC(...)
#define	WdgPickDefRC(...)
#define	WdgL2InfoPickDefRC(...)
#define	WdgTxtPickImgTxtDefRC(...)
#define	WdgTxtPickTxtDefRC(...)
#define	WdgImgTxtPickImgTxtDefRC(...)
#define	WdgFormatInpDefRC(...)
#define	WdgGridBaseDefRC(...)
#define	WdgHandwriteDefRC(...)
#define	WdgImeAssistDefRC(...)
#define	WdgListDefRC(...)
#define	WdgScrollbarDefRC(...)
#define	WdgScrollIndDefRC(...)
#define	WdgTitleDefRC(...)
#define	WdgMflDefRC(...)
#define	WdgOpMenuDefRC(...)
#define	WdgPopUpSelDefRC(...)
#define	WdgShortcutBarDefRC(...)
#define	WdgSlideSwDefRC(...)
#define	WdgPropDefRC(...)
#define	WdgTimerFormatDefRC(...)
#define	WdgTransitionDefRC(...)
#define	WdgVolumeDefRC(...)
#define	WdgImgTextDefRC(...)
#define	WdgImgTextImgDefRC(...)
#define WdgTextImgDefRC(...)

#define WdgStatusBarDefRC(IconNum,...)
#define	WdgSoftkeyboardDefRC(...)
#define WdgSoftkeyDefRC(...)
#define WdgCanvasDefRC(...)


#define	WdgTxtL2InfoDefRC(...)
#define	WdgDbTxtInputDefRC(...)
#define	WdgDbTextDefRC(...)
#define	WdgITSTextDefRC(...)
#define	WdgITSInputDefRC(...)
#define	WdgDbTxtDateDefRC(...)
#define	WdgDbTxtTimeDefRC(...)
#define	WdgITSITDefRC(...)
#define	WdgITSTIDefRC(...)
#define	WdgTextIPDefRC(...)

#define WdgInputControllerMenuItemNumRC(...)
#define WdgInputControllerMenuItemRC(firstDimNum, ...)
#define WdgInputControllerCopyModeItemNumRC(...)
#define WdgInputControllerCopyModeRC(firstDimNum, ...)
#define WdgInputControllerSmartOnOffItemNumRC(...)
#define WdgInputControllerSmartOnOffRC(firstDimNum, ...)


#define	WdgSoftkeyboardCnStrokeItemNumRC(...)
#define	WdgSoftkeyboardCnStrokeRC(firstDimNum, ...)
#define	WdgSoftkeyboardEnCapitalItemNumRC(...)
#define	WdgSoftkeyboardEnCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardEnLcItemNumRC(...)
#define	WdgSoftkeyboardEnLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardSymbolItemNumRC(...)
#define	WdgSoftkeyboardSymbolRC(firstDimNum, ...)
#define	WdgSoftkeyboardCnPinyinItemNumRC(...)
#define	WdgSoftkeyboardCnPinyinRC(firstDimNum, ...)
#define	WdgSoftkeyboardCnBpmfItemNumRC(...)
#define	WdgSoftkeyboardCnBpmfRC(firstDimNum, ...)
#define	WdgSoftkeyboardNumericItemNumRC(...)
#define	WdgSoftkeyboardNumericRC(firstDimNum, ...)
#define	WdgSoftkeyboardFormatInputItemNumRC(...)
#define	WdgSoftkeyboardFormatInputRC(firstDimNum, ...)
#define	WdgSoftkeyboardRateItemNumRC(...)
#define	WdgSoftkeyboardRateRC(firstDimNum, ...)
#define	WdgSoftkeyboardPinItemNumRC(...)
#define	WdgSoftkeyboardPinRC(firstDimNum, ...)
#define	WdgSoftkeyboardDialingItemNumRC(...)
#define	WdgSoftkeyboardDialingRC(firstDimNum, ...)
#define	WdgSoftkeyboardEsCapitalItemNumRC(...)
#define	WdgSoftkeyboardEsCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardEsLcItemNumRC(...)
#define	WdgSoftkeyboardEsLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardFrCapitalItemNumRC(...)
#define	WdgSoftkeyboardFrCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardFrLcItemNumRC(...)
#define	WdgSoftkeyboardFrLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardVnCapitalItemNumRC(...)
#define	WdgSoftkeyboardVnCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardVnLcItemNumRC(...)
#define	WdgSoftkeyboardVnLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardPtCapitalItemNumRC(...)
#define	WdgSoftkeyboardPtCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardPtLcItemNumRC(...)
#define	WdgSoftkeyboardPtLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardRuCapitalItemNumRC(...)
#define	WdgSoftkeyboardRuCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardRuLcItemNumRC(...)
#define	WdgSoftkeyboardRuLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardTrCapitalItemNumRC(...)
#define	WdgSoftkeyboardTrCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardTrLcItemNumRC(...)
#define	WdgSoftkeyboardTrLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardPlCapitalItemNumRC(...)
#define	WdgSoftkeyboardPlCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardPlLcItemNumRC(...)
#define	WdgSoftkeyboardPlLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardNlCapitalItemNumRC(...)
#define	WdgSoftkeyboardNlCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardNlLcItemNumRC(...)
#define	WdgSoftkeyboardNlLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardThCapitalItemNumRC(...)
#define	WdgSoftkeyboardThCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardThLcItemNumRC(...)
#define	WdgSoftkeyboardThLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardArabicItemNumRC(...)
#define	WdgSoftkeyboardArabicRC(firstDimNum, ...)
#define	WdgSoftkeyboardPersianItemNumRC(...)
#define	WdgSoftkeyboardPersianRC(firstDimNum, ...)
#define	WdgSoftkeyboardGMCapitalItemNumRC(...)
#define	WdgSoftkeyboardGMCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardGMLcItemNumRC(...)
#define	WdgSoftkeyboardGMLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardITCapitalItemNumRC(...)
#define	WdgSoftkeyboardITCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardITLcItemNumRC(...)
#define	WdgSoftkeyboardITLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardHindiCapitalItemNumRC(...)
#define	WdgSoftkeyboardHindiCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardHindiLcItemNumRC(...)
#define	WdgSoftkeyboardHindiLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardTamil1ItemNumRC(...)
#define	WdgSoftkeyboardTamil1RC(firstDimNum, ...)
#define	WdgSoftkeyboardTamil2ItemNumRC(...)
#define	WdgSoftkeyboardTamil2RC(firstDimNum, ...)
#define	WdgSoftkeyboardTelugu1ItemNumRC(...)
#define	WdgSoftkeyboardTelugu1RC(firstDimNum, ...)
#define	WdgSoftkeyboardTelugu2ItemNumRC(...)
#define	WdgSoftkeyboardTelugu2RC(firstDimNum, ...)
#define	WdgSoftkeyboardBurmese1ItemNumRC(...)
#define	WdgSoftkeyboardBurmese1RC(firstDimNum, ...)
#define	WdgSoftkeyboardBurmese2ItemNumRC(...)
#define	WdgSoftkeyboardBurmese2RC(firstDimNum, ...)
#define	WdgSoftkeyboardPunjabi1ItemNumRC(...)
#define	WdgSoftkeyboardPunjabi1RC(firstDimNum, ...)
#define	WdgSoftkeyboardPunjabi2ItemNumRC(...)
#define	WdgSoftkeyboardPunjabi2RC(firstDimNum, ...)
#define	WdgSoftkeyboardUrdu1ItemNumRC(...)
#define	WdgSoftkeyboardUrdu1RC(firstDimNum, ...)
#define	WdgSoftkeyboardUrdu2ItemNumRC(...)
#define	WdgSoftkeyboardUrdu2RC(firstDimNum, ...)
#define	WdgSoftkeyboardBengali1ItemNumRC(...)
#define	WdgSoftkeyboardBengali1RC(firstDimNum, ...)
#define	WdgSoftkeyboardBengali2ItemNumRC(...)
#define	WdgSoftkeyboardBengali2RC(firstDimNum, ...)
#define	WdgSoftkeyboardCzechCapitalItemNumRC(...)
#define	WdgSoftkeyboardCzechCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardCzechLcItemNumRC(...)
#define	WdgSoftkeyboardCzechLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardGreekCapitalItemNumRC(...)
#define	WdgSoftkeyboardGreekCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardGreekLcItemNumRC(...)
#define	WdgSoftkeyboardGreekLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardPlCapitalItemNumRC(...)
#define	WdgSoftkeyboardPlCapitalRC(firstDimNum, ...)
#define	WdgSoftkeyboardPlLcItemNumRC(...)
#define	WdgSoftkeyboardPlLcRC(firstDimNum, ...)
#define	WdgSoftkeyboardSmartItemNumRC(...)
#define	WdgSoftkeyboardSmartRC(firstDimNum, ...)
#define	WdgSoftkeyboardChSymbolTblItemNumRC(...)
#define	WdgSoftkeyboardChSymbolTblRC(firstDimNum, ...)
#define	WdgSoftkeyboardSymbolTblPage2ItemNumRC(...)
#define	WdgSoftkeyboardSymbolTblPage2RC(firstDimNum, ...)

#define RSCustomize(type,name, ...)


