#undef ApBegin
#undef ApEnd
#undef WndBegin
#undef WndEnd
#undef WdgBegin
#undef WdgEnd
#undef ChildBegin
#undef ChildEnd
#undef DynamicStructBegin
#undef DynamicStructEnd
#undef VTMWdgBegin
#undef VTMWdgEnd

/* widget default */
#undef	WdgAbsDefRC
#undef	WdgViewportDefRC
#undef	WdgButtonDefRC
#undef	WdgImageDefRC
#undef	WdgOverlayImageDefRC
#undef	WdgTextDefRC
#undef	WdgInputDefRC
#undef	WdgOsdDefRC
#undef	WdgTabDefRC
#undef	WdgSwitchIconDefRC
#undef	WdgSwitchIconItemDefRC
#undef	WdgProgressDefRC
#undef	WdgIpDefRC
#undef	WdgFadeoutDefRC
#undef	WdgPulldownDefRC
#undef	WdgIndicatorDefRC
#undef	WdgTextBubbleDefRC
#undef	WdgTimeDefRC
#undef	WdgFcDateDefRC
#undef	WdgDateDefRC
#undef	WdgFcTimeDefRC
#undef	WdgMenuDefRC
#undef	WdgPickDefRC
#undef	WdgL2InfoPickDefRC
#undef	WdgTxtPickImgTxtDefRC
#undef	WdgTxtPickTxtDefRC
#undef	WdgImgTxtPickImgTxtDefRC
#undef	WdgFormatInpDefRC
#undef	WdgGridBaseDefRC
#undef	WdgHandwriteDefRC
#undef	WdgImeAssistDefRC
#undef	WdgListDefRC
#undef	WdgScrollbarDefRC
#undef	WdgScrollIndDefRC
#undef	WdgTitleDefRC
#undef	WdgMflDefRC
#undef	WdgOpMenuDefRC
#undef	WdgPopUpSelDefRC
#undef	WdgShortcutBarDefRC
#undef	WdgSlideSwDefRC
#undef	WdgPropDefRC
#undef	WdgTimerFormatDefRC
#undef	WdgTransitionDefRC
#undef	WdgVolumeDefRC
#undef	WdgImgTextDefRC
#undef	WdgImgTextImgDefRC
#undef  WdgTextImgDefRC
#undef	WdgTxtL2InfoDefRC
#undef	WdgDbTxtInputDefRC
#undef	WdgDbTextDefRC
#undef	WdgITSTextDefRC
#undef	WdgITSInputDefRC
#undef	WdgDbTxtDateDefRC
#undef	WdgDbTxtTimeDefRC
#undef	WdgITSITDefRC
#undef	WdgITSTIDefRC
#undef	WdgTextIPDefRC
#undef  WdgStatusBarDefRC
#undef  WdgSoftkeyboardDefRC
#undef  WdgSoftkeyDefRC
#undef  WdgCanvasDefRC

#undef  WdgInputControllerMenuItemNumRC
#undef  WdgInputControllerMenuItemRC
#undef  WdgInputControllerCopyModeItemNumRC
#undef  WdgInputControllerCopyModeRC
#undef  WdgInputControllerSmartOnOffItemNumRC
#undef  WdgInputControllerSmartOnOffRC

#undef	WdgSoftkeyboardCnStrokeItemNumRC
#undef	WdgSoftkeyboardCnStrokeRC
#undef	WdgSoftkeyboardEnCapitalItemNumRC
#undef	WdgSoftkeyboardEnCapitalRC
#undef	WdgSoftkeyboardEnLcItemNumRC
#undef	WdgSoftkeyboardEnLcRC
#undef	WdgSoftkeyboardSymbolItemNumRC
#undef	WdgSoftkeyboardSymbolRC
#undef	WdgSoftkeyboardCnPinyinItemNumRC
#undef	WdgSoftkeyboardCnPinyinRC
#undef	WdgSoftkeyboardCnBpmfItemNumRC
#undef	WdgSoftkeyboardCnBpmfRC
#undef	WdgSoftkeyboardNumericItemNumRC
#undef	WdgSoftkeyboardNumericRC
#undef	WdgSoftkeyboardFormatInputItemNumRC
#undef	WdgSoftkeyboardFormatInputRC
#undef	WdgSoftkeyboardRateItemNumRC
#undef	WdgSoftkeyboardRateRC
#undef	WdgSoftkeyboardPinItemNumRC
#undef	WdgSoftkeyboardPinRC
#undef	WdgSoftkeyboardDialingItemNumRC
#undef	WdgSoftkeyboardDialingRC
#undef	WdgSoftkeyboardEsCapitalItemNumRC
#undef	WdgSoftkeyboardEsCapitalRC
#undef	WdgSoftkeyboardEsLcItemNumRC
#undef	WdgSoftkeyboardEsLcRC
#undef	WdgSoftkeyboardFrCapitalItemNumRC
#undef	WdgSoftkeyboardFrCapitalRC
#undef	WdgSoftkeyboardFrLcItemNumRC
#undef	WdgSoftkeyboardFrLcRC
#undef	WdgSoftkeyboardVnCapitalItemNumRC
#undef	WdgSoftkeyboardVnCapitalRC
#undef	WdgSoftkeyboardVnLcItemNumRC
#undef	WdgSoftkeyboardVnLcRC
#undef	WdgSoftkeyboardPtCapitalItemNumRC
#undef	WdgSoftkeyboardPtCapitalRC
#undef	WdgSoftkeyboardPtLcItemNumRC
#undef	WdgSoftkeyboardPtLcRC
#undef	WdgSoftkeyboardRuCapitalItemNumRC
#undef	WdgSoftkeyboardRuCapitalRC
#undef	WdgSoftkeyboardRuLcItemNumRC
#undef	WdgSoftkeyboardRuLcRC
#undef	WdgSoftkeyboardTrCapitalItemNumRC
#undef	WdgSoftkeyboardTrCapitalRC
#undef	WdgSoftkeyboardTrLcItemNumRC
#undef	WdgSoftkeyboardTrLcRC
#undef	WdgSoftkeyboardThCapitalItemNumRC
#undef	WdgSoftkeyboardThCapitalRC
#undef	WdgSoftkeyboardThLcItemNumRC
#undef	WdgSoftkeyboardThLcRC
#undef	WdgSoftkeyboardArabicItemNumRC
#undef	WdgSoftkeyboardArabicRC
#undef	WdgSoftkeyboardPersianItemNumRC
#undef	WdgSoftkeyboardPersianRC
#undef	WdgSoftkeyboardGMCapitalItemNumRC
#undef	WdgSoftkeyboardGMCapitalRC
#undef	WdgSoftkeyboardGMLcItemNumRC
#undef	WdgSoftkeyboardGMLcRC
#undef	WdgSoftkeyboardITCapitalItemNumRC
#undef	WdgSoftkeyboardITCapitalRC
#undef	WdgSoftkeyboardITLcItemNumRC
#undef	WdgSoftkeyboardITLcRC
#undef	WdgSoftkeyboardHindiCapitalItemNumRC
#undef	WdgSoftkeyboardHindiCapitalRC
#undef	WdgSoftkeyboardHindiLcItemNumRC
#undef	WdgSoftkeyboardHindiLcRC
#undef	WdgSoftkeyboardTamil1ItemNumRC
#undef	WdgSoftkeyboardTamil1RC
#undef	WdgSoftkeyboardTamil2ItemNumRC
#undef	WdgSoftkeyboardTamil2RC
#undef	WdgSoftkeyboardTelugu1ItemNumRC
#undef	WdgSoftkeyboardTelugu1RC
#undef	WdgSoftkeyboardTelugu2ItemNumRC
#undef	WdgSoftkeyboardTelugu2RC
#undef	WdgSoftkeyboardBurmese1ItemNumRC
#undef	WdgSoftkeyboardBurmese1RC
#undef	WdgSoftkeyboardBurmese2ItemNumRC
#undef	WdgSoftkeyboardBurmese2RC
#undef	WdgSoftkeyboardPunjabi1ItemNumRC
#undef	WdgSoftkeyboardPunjabi1RC
#undef	WdgSoftkeyboardPunjabi2ItemNumRC
#undef	WdgSoftkeyboardPunjabi2RC
#undef	WdgSoftkeyboardUrdu1ItemNumRC
#undef	WdgSoftkeyboardUrdu1RC
#undef	WdgSoftkeyboardUrdu2ItemNumRC
#undef	WdgSoftkeyboardUrdu2RC
#undef	WdgSoftkeyboardBengali1ItemNumRC
#undef	WdgSoftkeyboardBengali1RC
#undef	WdgSoftkeyboardBengali2ItemNumRC
#undef	WdgSoftkeyboardBengali2RC
#undef	WdgSoftkeyboardCzechCapitalItemNumRC
#undef	WdgSoftkeyboardCzechCapitalRC
#undef	WdgSoftkeyboardCzechLcItemNumRC
#undef	WdgSoftkeyboardCzechLcRC
#undef	WdgSoftkeyboardGreekCapitalItemNumRC
#undef	WdgSoftkeyboardGreekCapitalRC
#undef	WdgSoftkeyboardGreekLcItemNumRC
#undef	WdgSoftkeyboardGreekLcRC
#undef	WdgSoftkeyboardPlCapitalItemNumRC
#undef	WdgSoftkeyboardPlCapitalRC
#undef	WdgSoftkeyboardPlLcItemNumRC
#undef	WdgSoftkeyboardPlLcRC
#undef	WdgSoftkeyboardNlCapitalItemNumRC
#undef	WdgSoftkeyboardNlCapitalRC
#undef	WdgSoftkeyboardNlLcItemNumRC
#undef	WdgSoftkeyboardNlLcRC
#undef	WdgSoftkeyboardSmartItemNumRC
#undef	WdgSoftkeyboardSmartRC
#undef	WdgSoftkeyboardChSymbolTblItemNumRC
#undef	WdgSoftkeyboardChSymbolTblRC
#undef	WdgSoftkeyboardSymbolTblPage2ItemNumRC
#undef	WdgSoftkeyboardSymbolTblPage2RC

#undef RSCustomize


