/**
 * @file    mmi_wdg_substatusbar_imgid.h
 * @brief   The document defines all image resource id used in statusbar widget
 * @author  steve.lee@mstarsemi.com
 *
 * @version $Id: mmi_wdg_substatusbar_imgid.h 34171 2009-06-23 12:05:19Z lih.wang $
 */

/*
	MAKE_IMGID(_a, _b)
		_a: image id defined by statusbar widget
		_b: resource id of the image corresponding to _a
*/
	MAKE_IMGID(SUB_SB_IMG_ID_BLANK,							SUB_STATUSBAR_IMG_BLANK),
	MAKE_IMGID(SUB_SB_IMG_ID_BG,							SUB_STATUSBAR_IMG_BG),

	//Battery level Indication Images
#if 0 //def __DUAL_BATT_MMI__  // Current spec doesn't support dual-battery on sub-panel
	MAKE_IMGID(SUB_SB_IMG_ID_BATT_LOW,		    			SUB_STATUSBAR_IMG_BATTERY1_LEVEL_LOW),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT0,							SUB_STATUSBAR_IMG_BATTERY1_LEVEL4_1),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT1,							SUB_STATUSBAR_IMG_BATTERY1_LEVEL4_2),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT2,							SUB_STATUSBAR_IMG_BATTERY1_LEVEL4_3),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT3,							SUB_STATUSBAR_IMG_BATTERY1_LEVEL4_4),
	MAKE_IMGID(SUB_SB_IMG_ID_CHARGING_ANIM,					SUB_STATUSBAR_IMG_BATTERY1_ANIM),

	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_BATT_LOW,        		SUB_STATUSBAR_IMG_BATTERY2_LEVEL_LOW),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_BATT0,	        		SUB_STATUSBAR_IMG_BATTERY2_LEVEL4_1),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_BATT1,	        		SUB_STATUSBAR_IMG_BATTERY2_LEVEL4_2),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_BATT2,					SUB_STATUSBAR_IMG_BATTERY2_LEVEL4_3),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_BATT3,	        		SUB_STATUSBAR_IMG_BATTERY2_LEVEL4_4),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_CHARGING_ANIM,    		SUB_STATUSBAR_IMG_BATTERY2_ANIM),
#else
	MAKE_IMGID(SUB_SB_IMG_ID_BATT_LOW,		    			SUB_STATUSBAR_IMG_BATTERY_LEVEL_LOW),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT0,							SUB_STATUSBAR_IMG_BATTERY_LEVEL4_1),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT1,							SUB_STATUSBAR_IMG_BATTERY_LEVEL4_2),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT2,							SUB_STATUSBAR_IMG_BATTERY_LEVEL4_3),
	MAKE_IMGID(SUB_SB_IMG_ID_BATT3,							SUB_STATUSBAR_IMG_BATTERY_LEVEL4_4),
	MAKE_IMGID(SUB_SB_IMG_ID_CHARGING_ANIM,     			SUB_STATUSBAR_IMG_BATTERY_ANIM),
#endif

	//RSSI Indication Images
#ifdef __DUAL_SIM_MMI__
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI0,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_0),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI1,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_1),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI2,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_2),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI3,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_3),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI4,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_4),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI5,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_5),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI_NO_SERVICE,				SUB_STATUSBAR_IMG_DUAL_RSSI_LEVEL_NO_SERVICE),

	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI0,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_0),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI1,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_1),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI2,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_2),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI3,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_3),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI4,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_4),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI5,					SUB_STATUSBAR_IMG_DUAL_RSSI_SIM2_LEVEL_5),
	MAKE_IMGID(SUB_SB_IMG_ID_SLAVE_RSSI_NO_SERVICE,			SUB_STATUSBAR_IMG_DUAL_RSSI_LEVEL_NO_SERVICE),
#else
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI0,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_0),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI1,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_1),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI2,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_2),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI3,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_3),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI4,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_4),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI5,							SUB_STATUSBAR_IMG_DUAL_RSSI_SIM1_LEVEL_5),
	MAKE_IMGID(SUB_SB_IMG_ID_RSSI_NO_SERVICE,				SUB_STATUSBAR_IMG_DUAL_RSSI_LEVEL_NO_SERVICE),
#endif /* __DUAL_SIM_MMI__ */
    MAKE_IMGID(SUB_SB_IMG_ID_AIRMODE,						SUB_STATUSBAR_IMG_DUAL_AIR_MODE),

    MAKE_IMGID(SUB_SB_IMG_ID_SILENT,            			SUB_STATUSBAR_IMG_SILENT),
#ifdef __MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__
    MAKE_IMGID(SUB_SB_IMG_ID_MEETING,                       SUB_STATUSBAR_IMG_MEETING),
    MAKE_IMGID(SUB_SB_IMG_ID_OUTDOOR,                       SUB_STATUSBAR_IMG_OUTDOOR),
#ifdef __POWER_SAVING_PROFILE_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_POWERSAVING,                   SUB_STATUSBAR_IMG_POWERSAVING),
#endif // __POWER_SAVING_PROFILE_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_CUSTOM,                        SUB_STATUSBAR_IMG_CUSTOM),
#endif // __MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__
    MAKE_IMGID(SUB_SB_IMG_ID_HEADSET,		    			SUB_STATUSBAR_IMG_HEADSET),
#ifdef __STATUSBAR_DISPLAY_MUTI_BT_DEVICE_STATUS_ICON__
    MAKE_IMGID(SUB_SB_IMG_ID_HFP_ONLY,          			SUB_STATUSBAR_IMG_HFP_ONLY),
	MAKE_IMGID(SUB_SB_IMG_ID_HFP_A2DP,          			SUB_STATUSBAR_IMG_HFP_A2DP),
    MAKE_IMGID(SUB_SB_IMG_ID_A2DP_ONLY,         			SUB_STATUSBAR_IMG_A2DP_ONLY),
#else // HFP, A2DP, A2DP+HFP using the same icon SUB_STATUSBAR_IMG_HFP_A2DP
    MAKE_IMGID(SUB_SB_IMG_ID_HFP_ONLY,                      SUB_STATUSBAR_IMG_HFP_A2DP),
	MAKE_IMGID(SUB_SB_IMG_ID_HFP_A2DP,                      SUB_STATUSBAR_IMG_HFP_A2DP),
    MAKE_IMGID(SUB_SB_IMG_ID_A2DP_ONLY,                     SUB_STATUSBAR_IMG_HFP_A2DP),
#endif // __STATUSBAR_DISPLAY_MUTI_BT_DEVICE_STATUS_ICON__
	MAKE_IMGID(SUB_SB_IMG_ID_SS_CFU_ENABLE,					SUB_STATUSBAR_IMG_DIVERT),
	MAKE_IMGID(SUB_SB_IMG_ID_SS_CFU_1_ENABLE,				SUB_STATUSBAR_IMG_DIVERT_1),
	MAKE_IMGID(SUB_SB_IMG_ID_SS_CFU_2_ENABLE,				SUB_STATUSBAR_IMG_DIVERT_2),
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_FULL,		    			SUB_STATUSBAR_IMG_MSG_FULL),
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_VOICE_MAIL,				SUB_STATUSBAR_IMG_MSG_VOICEMAIL),
#if (defined(__MMI_STATUSBAR_SUPPORT_UNREAD_MESSAGE__) || defined(__MMI_STATUSBAR_SUPPORT_UNREAD_MESSAGE_BY_IMSI__))
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_UNREAD,					SUB_STATUSBAR_IMG_MSG_UNREAD),
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_UNREAD_SIM1,				SUB_STATUSBAR_IMG_MSG_UNREAD_SIM1),
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_UNREAD_SIM2,				SUB_STATUSBAR_IMG_MSG_UNREAD_SIM2),
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_UNREAD_ALL,				SUB_STATUSBAR_IMG_MSG_UNREAD_ALL),
#endif
	MAKE_IMGID(SUB_SB_IMG_ID_MSG_TRANS,						SUB_STATUSBAR_IMG_MSG_TRANSMITTING),

	//Other Indication Images
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_MEMCARD,		    		SUB_STATUSBAR_IMG_OTHER_MEMCARD),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_MEMCARD_CONNECT,			SUB_STATUSBAR_IMG_OTHER_MEMCARD_CONNECT),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_MPLAYER,		    		SUB_STATUSBAR_IMG_OTHER_MPLAYER),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_MPLAYER_PAUSE,			SUB_STATUSBAR_IMG_OTHER_MPLAYER_PAUSE),
#ifdef __APP_MMI_FM_RADIO__
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_FMR,						SUB_STATUSBAR_IMG_OTHER_FMRADIO),
#endif
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_USB,						SUB_STATUSBAR_IMG_USB),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_BT,						SUB_STATUSBAR_IMG_OTHER_BLUETOOTH),
#ifdef __BLUETOOTH_OBEX_MMI__
	MAKE_IMGID(SUB_SB_IMG_ID_OTHR_BT_CONNECT,				SUB_STATUSBAR_IMG_OTHER_BLUETOOTH_CONNECT),
#endif

	MAKE_IMGID(SUB_SB_IMG_ID_ALARM,							SUB_STATUSBAR_IMG_ALARM),
#ifndef __MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__
	MAKE_IMGID(SUB_SB_IMG_ID_VIBRATE,						SUB_STATUSBAR_IMG_VIBRATE),
#endif // !__MMI_STATUSBAR_SUPPORT_PROFILE_STATUS__
#ifdef __MMI_STATUSBAR_SUPPORT_MISSED_CALL__
	#ifdef __DUAL_SIM_MMI__
		MAKE_IMGID(SUB_SB_IMG_ID_MISSCALL,					SUB_STATUSBAR_IMG_MISS_CALL_SIM1),
		MAKE_IMGID(SUB_SB_IMG_ID_MISSCALL_SLAVE,			SUB_STATUSBAR_IMG_MISS_CALL_SIM2),
		MAKE_IMGID(SUB_SB_IMG_ID_MISSCALL_BOTH,				SUB_STATUSBAR_IMG_MISS_CALL_ALL_SIM),
	#else
		MAKE_IMGID(SUB_SB_IMG_ID_MISSCALL,					SUB_STATUSBAR_IMG_MISS_CALL),
	#endif
#endif

/* Wifi icon defination */
#ifdef __WLAN_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_WIFI,          	            SUB_STATUSBAR_IMG_WIFI),
#ifdef __MMI_DISPLAY_GPRS_TRAFFIC__
	MAKE_IMGID(SUB_SB_IMG_ID_WIFI_TRAFFIC,	                SUB_STATUSBAR_IMG_WIFI_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_WIFI_TRAFFIC_HALF,	            SUB_STATUSBAR_IMG_WIFI_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif // End of __MMI_DISPLAY_GPRS_TRAFFIC__
	MAKE_IMGID(SUB_SB_IMG_ID_WIFI_CONNECT_LIMITED,	        SUB_STATUSBAR_IMG_WIFI_CONNECT_LIMITED),
	MAKE_IMGID(SUB_SB_IMG_ID_WIFI_CONNECTED,	            SUB_STATUSBAR_IMG_WIFI_CONNECTED),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_WIFI_HALF,          	        SUB_STATUSBAR_IMG_WIFI_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_WIFI_CONNECT_LIMITED_HALF,	    SUB_STATUSBAR_IMG_WIFI_CONNECT_LIMITED_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_WIFI_CONNECTED_HALF,	        SUB_STATUSBAR_IMG_WIFI_CONNECTED_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif

/* == Start of network icon defination == */
/* GPRS & EGPRS & UMTS(3G) & HSDPA part */
#ifdef __DUAL_SIM_MMI__ /* Start of __DUAL_SIM_MMI__ */
    /* For SIM 1 */
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS,                     SUB_STATUSBAR_IMG_NETWORK_SIM1_GPRS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS,                    SUB_STATUSBAR_IMG_NETWORK_SIM1_EGPRS),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_HALF,                SUB_STATUSBAR_IMG_NETWORK_SIM1_GPRS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_HALF,          	    SUB_STATUSBAR_IMG_NETWORK_SIM1_EGPRS_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS,                     SUB_STATUSBAR_IMG_NETWORK_SIM1_UMTS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA,                    SUB_STATUSBAR_IMG_NETWORK_SIM1_HSDPA),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_HALF,                SUB_STATUSBAR_IMG_NETWORK_SIM1_UMTS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_HALF,          	    SUB_STATUSBAR_IMG_NETWORK_SIM1_HSDPA_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif //__3G_RIL_MMI__
#ifdef __MMI_DISPLAY_GPRS_TRAFFIC__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_TRAFFIC,	            SUB_STATUSBAR_IMG_NETWORK_SIM1_GPRS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_TRAFFIC,	        SUB_STATUSBAR_IMG_NETWORK_SIM1_EGPRS_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM1_GPRS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM1_EGPRS_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_TRAFFIC,	            SUB_STATUSBAR_IMG_NETWORK_SIM1_UMTS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_TRAFFIC,	        SUB_STATUSBAR_IMG_NETWORK_SIM1_HSDPA_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM1_UMTS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM1_HSDPA_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif //__3G_RIL_MMI__
#endif // End of __MMI_DISPLAY_GPRS_TRAFFIC__

    /* For SIM 2 */
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_GPRS,              	    SUB_STATUSBAR_IMG_NETWORK_SIM2_GPRS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_EGPRS,          	        SUB_STATUSBAR_IMG_NETWORK_SIM2_EGPRS),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_GPRS_HALF,              	SUB_STATUSBAR_IMG_NETWORK_SIM2_GPRS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_EGPRS_HALF,          	    SUB_STATUSBAR_IMG_NETWORK_SIM2_EGPRS_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_UMTS,              	    SUB_STATUSBAR_IMG_NETWORK_SIM2_UMTS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_HSDPA,          	        SUB_STATUSBAR_IMG_NETWORK_SIM2_HSDPA),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_UMTS_HALF,              	SUB_STATUSBAR_IMG_NETWORK_SIM2_UMTS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_HSDPA_HALF,          	    SUB_STATUSBAR_IMG_NETWORK_SIM2_HSDPA_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif // __3G_RIL_MMI__
#ifdef __MMI_DISPLAY_GPRS_TRAFFIC__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_GPRS_TRAFFIC,	            SUB_STATUSBAR_IMG_NETWORK_SIM2_GPRS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_EGPRS_TRAFFIC,	        SUB_STATUSBAR_IMG_NETWORK_SIM2_EGPRS_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_GPRS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM2_GPRS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_EGPRS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM2_EGPRS_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_UMTS_TRAFFIC,	            SUB_STATUSBAR_IMG_NETWORK_SIM2_UMTS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_HSDPA_TRAFFIC,	        SUB_STATUSBAR_IMG_NETWORK_SIM2_HSDPA_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM2_UMTS_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM2_UMTS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_HSDPA_TRAFFIC_HALF,	    SUB_STATUSBAR_IMG_NETWORK_SIM2_HSDPA_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif // __3G_RIL_MMI__
#endif // End of __MMI_DISPLAY_GPRS_TRAFFIC__

    /* No SIM 1&2 case because target has only one socket */

#else /* __SINGLE_SIM_MMI__ */
    /* For SIM 1 without the number '1' */
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS,                     SUB_STATUSBAR_IMG_NETWORK_GPRS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS,                    SUB_STATUSBAR_IMG_NETWORK_EGPRS),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_HALF,                SUB_STATUSBAR_IMG_NETWORK_GPRS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_HALF,               SUB_STATUSBAR_IMG_NETWORK_EGPRS_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS,                     SUB_STATUSBAR_IMG_NETWORK_UMTS),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA,                    SUB_STATUSBAR_IMG_NETWORK_HSDPA),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_HALF,                SUB_STATUSBAR_IMG_NETWORK_UMTS_HALF),
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_HALF,               SUB_STATUSBAR_IMG_NETWORK_HSDPA_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif // __3G_RIL_MMI__
#ifdef __MMI_DISPLAY_GPRS_TRAFFIC__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_TRAFFIC,             SUB_STATUSBAR_IMG_NETWORK_GPRS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_TRAFFIC,            SUB_STATUSBAR_IMG_NETWORK_EGPRS_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_GPRS_TRAFFIC_HALF,        SUB_STATUSBAR_IMG_NETWORK_GPRS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_EGPRS_TRAFFIC_HALF,       SUB_STATUSBAR_IMG_NETWORK_EGPRS_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#ifdef __3G_RIL_MMI__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_TRAFFIC,             SUB_STATUSBAR_IMG_NETWORK_UMTS_TRAFFIC),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_TRAFFIC,            SUB_STATUSBAR_IMG_NETWORK_HSDPA_TRAFFIC),
#ifndef __MMI_STATUSBAR_AUTO_ARRANGE__
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_UMTS_TRAFFIC_HALF,        SUB_STATUSBAR_IMG_NETWORK_UMTS_TRAFFIC_HALF),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_HSDPA_TRAFFIC_HALF,       SUB_STATUSBAR_IMG_NETWORK_HSDPA_TRAFFIC_HALF),
#endif // !__MMI_STATUSBAR_AUTO_ARRANGE__
#endif // __3G_RIL_MMI__
#endif // End of __MMI_DISPLAY_GPRS_TRAFFIC__

#endif /* End of __DUAL_SIM_MMI__ */

/* Roaming part */
#ifdef __DUAL_SIM_MMI__ /* Start of __DUAL_SIM_MMI__ */
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_ROAM,	                    SUB_STATUSBAR_IMG_NETWORK_SIM1_ROAMING),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM2_ROAM,		                SUB_STATUSBAR_IMG_NETWORK_SIM2_ROAMING),
	MAKE_IMGID(SUB_SB_IMG_ID_SIM1_SIM2_ROAM,	            SUB_STATUSBAR_IMG_NETWORK_SIM1_SIM2_ROAMING),
#else /* __SINGLE_SIM_MMI__ */
    MAKE_IMGID(SUB_SB_IMG_ID_SIM1_ROAM,	                    SUB_STATUSBAR_IMG_NETWORK_ROAMING),

#endif /* End of __DUAL_SIM_MMI__ */

/*== End of network icon defination ==*/

// 3-party icon

#ifdef __NCCQQ_MMI__
    MAKE_IMGID(SUB_SB_IMG_ID_QQ_OFFLINE,            SUB_QQ_IMG_OFFLINE),
    MAKE_IMGID(SUB_SB_IMG_ID_QQ_ONLINE,             SUB_QQ_IMG_ONLINE),
    MAKE_IMGID(SUB_SB_IMG_ID_QQ_NEW_MSG,            SUB_QQ_IMG_NEW_MSG),
#endif

	MAKE_IMGID(SUB_SB_IMG_ID_OTHER_JAVA_BG,			SUB_STATUSBAR_IMG_BLANK),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHER_SKYENGINE_QQ_ONLINE,			SUB_STATUSBAR_IMG_BLANK),
	MAKE_IMGID(SUB_SB_IMG_ID_OTHER_TQQ_BLANK,			SUB_STATUSBAR_IMG_BLANK),
