#ifndef __MMI_FDNAPP_ID_H__
#define __MMI_FDNAPP_ID_H__

typedef enum FDNAPPWndId_e_
{
	FDNAPP_WND_ENTRY_MENU = WND_ID_APP_BASE,
	FDNAPP_WND_ENTRY_MENU_WAITING,
	FDNAPP_WND_CONTACT_LIST,
	FDNAPP_WND_CONTACT_LIST_OPTION,
	FDNAPP_WND_EDIT_CONTACT,
	FDNAPP_WND_FULLEDIT,
	FDNAPP_WND_FULLEDITOPTION,
}VID_FDNAPP_EDIT_CONTACT_VIEW_RC_e;

typedef enum //VID_FDNAPP_EDIT_CONTACT_VIEW_enum
{
	eWID_FDNAPP_EDIT_CONTACT_VIEW_MFLCONTAINER7=APP_WDG_START,
    eWID_FDNAPP_EDIT_CONTACT_VIEW_NAME_DOUBLETEXTWIDGET8,
    eWID_FDNAPP_EDIT_CONTACT_VIEW_NUMBER_TEXTINPUTWIDGET9,
}FDNAPP_EDIT_CONTACT_VIEW_enum;

typedef enum
{
	MNU_FDNAPP_ENTRY_MENU = 0x8000,
	MNU_FDNAPP_EM_FDN_LIST,
	MNU_FDNAPP_EM_FDN_STATUS,
	MNU_FDNAPP_MAKE_CALL,
	MNU_FDNAPP_NEW_CONTACT,
	MNU_FDNAPP_EDIT_CONTACT,
	MNU_FDNAPP_DELETE_CONTACT
}FdnMenuId_e;

#endif //__MMI_FDNAPP_ID_H__

