#ifndef __MMI_PACMAN_QVGAP_RS__
#define __MMI_PACMAN_QVGAP_RS__

typedef enum 
{
    VID_PACMAN_BITMAPWDG = WND_ID_APP_BASE,
    VID_PACMAN_IMAGE,
	VID_PACMAN_MAIN,
	PACMAN_WND_MAIN_OPTIONMENU,
	PACMAN_WND_SETTINGS,
	PACMAN_WND_VOLUME,
	PACMAN_WND_SOUND
}PacManWndId_e;

typedef enum
{
	WID_PACMAN_TEXTWDG= APP_WDG_START,
	WID_PACMAN_IMAGEWDG,
} PacManWdgId_e;


enum
{
	PACMAN_OPTION_MENU_ITEM_SETTINGS
};

typedef enum
{	
	PACMAN_SETTINGS_MENU = 0,
	PACMAN_SETTINGS_SOUND,
	PACMAN_SETTINGS_VOLUME
}SettingMenuId_e;

enum
{
    PACMAN_VOLUME_VIEW_BEGIN = APP_WDG_START,
    PACMAN_VOLUME_WIDGET,
};

typedef enum
{
	PACMAN_SOUND_MENU = 0,
	PACMAN_SOUND_ON,
	PACMAN_SOUND_OFF
}PacManSoundMenuId_e;

#endif //__MMI_CALIBRATIONAPP_ID_H__
