#ifndef __MMI_SHORTCUTSAPP_ID_H__
#define __MMI_SHORTCUTSAPP_ID_H__

typedef enum ShortcutsWndId_e_
{
    SHORTCUTS_WND_SHOWLIST = WND_ID_APP_BASE,
    SHORTCUTS_WND_CHANGEORDER_DISPLAYLIST,
    SHORTCUTS_WND_CHANGEORDER_MARK,
    SHORTCUTS_WND_ADDFUNC,
    SHORTCUTS_WND_MAINMENU_SETTING,
    SHORTCUTS_WND_KEYASSIGNMENT_MAINLIST,
    SHORTCUTS_WND_KEYASSIGNMENT_NAVIGATIONKEYS,
    SHORTCUTS_WND_KEYASSIGNMENT_NUMERICKEYS,
    SHORTCUTS_WND_KEYASSIGNMENT_FUNCTIONSMENU,
    SHORTCUTS_WND_ASSIGNDYNAMICLINK_AVAILABLESHORTCUTS,
    SHORTCUTS_WND_ASSIGNDYNAMICLINK_REPLACEDIALOG,
    SHORTCUTS_WND_ASSIGNDYNAMICLINK_REPLACELIST,
    SHORTCUTS_WND_ASSIGNDYNAMICLINK_ASSIGNASNUMERICKEYS,
    SHORTCUTS_WND_OPTION,
    SHORTCUTS_WND_ICONLIST,
} ShortcutsWndId_e;

typedef enum
{
	MNU_SHORTCUTS_LEFT_SOFT_KEY = 0,
	MNU_SHORTCUTS_RIGHT_SOFT_KEY,
	MNU_SHORTCUTS_NAVIGATION_KEYS,
	MNU_SHORTCUTS_NAVI_UP,
	MNU_SHORTCUTS_NAVI_DOWN,
	MNU_SHORTCUTS_NAVI_LEFT,
	MNU_SHORTCUTS_NAVI_RIGHT,
	MNU_SHORTCUTS_NUMERIC_KEYS,
	MNU_SHORTCUTS_NUM_KEY_1,
	MNU_SHORTCUTS_NUM_KEY_2,
	MNU_SHORTCUTS_NUM_KEY_3,
	MNU_SHORTCUTS_NUM_KEY_4,
	MNU_SHORTCUTS_NUM_KEY_5,
	MNU_SHORTCUTS_NUM_KEY_6,
	MNU_SHORTCUTS_NUM_KEY_7,
	MNU_SHORTCUTS_NUM_KEY_8,
	MNU_SHORTCUTS_NUM_KEY_9,
	MNU_SHORTCUTS_FUNC_MENU,
	MNU_SHORTCUTS_OPEN,
	MNU_SHORTCUTS_ADD_FUNCTION,
	MNU_SHORTCUTS_ADD_PHONE_NUMBER,
	MNU_SHORTCUTS_ADD_BOOKMARK,
	MNU_SHORTCUTS_CHANGE_ORDER,
	MNU_SHORTCUTS_DELETE,
	MNU_SHORTCUTS_DELETE_ALL,
	MNU_SHORTCUTS_REMOVE,
}ShortcutsMenuId_e;

#endif //__MMI_SHORTCUTSAPP_ID_H__

