#ifndef __MMI_SHORTCUTSAPP_VIEW_ID_H__
#define __MMI_SHORTCUTSAPP_VIEW_ID_H__

#include "mmi_view_id_range.h"
#include "mmi_shortcutsapp.h"
#include "mmi_shortcutssrv_cfg.h"
#include "mmi_common_transition.h"

enum
{
    /* View ID start */
    VID_SHORTCUTS_SHOW_LIST_VIEW = MMI_VIEW_ID_AP_BEGIN,
    VID_SHORTCUTS_KEY_ASSIGN_VIEW,
    VID_SHORTCUTS_FUNCTION_MENU_VIEW,
    VID_SHORTCUTS_SHORTCUTS_LIST_VIEW,
    VID_SHORTCUTS_APPLICATION_LIST_VIEW
    /* View ID end */
};

enum
{
    /* Widget ID start */
    WID_SHORTCUTS_TITLEWIDGET = 1,
    WID_SHORTCUTS_MENUWIDGET,
    WID_SHORTCUTS_CONTAINER,
    WID_SHORTCUTS_APPLICATION_LIST,
    WID_SHORTCUTS_OPTION_MENU_MODEL,
    WID_SHORTCUTS_KEY_ASSIGNMENT_MAIN_LIST_MODEL,
    WID_SHORTCUTS_KEY_ASSIGNMENT_NAVIKEY_MODEL,
    WID_SHORTCUTS_KEY_ASSIGNMENT_NUMKEY_MODEL,
    WID_SHORTCUTS_ASSIGNABLE_SHORTCUTS_MODEL,
    WID_SHORTCUTS_ASSIGNABLE_SHORTCUTS_NUMKEY_MODEL,
    WID_SHORTCUTS_NUMKEY_FUNC_MENU_MODEL,
    WID_SHORTCUTS_SHORTCUTS_LIST_MENU_MODEL
    /* Widget ID end */
};

#endif /* __MMI_SHORTCUTSAPP_VIEW_ID_H__ */
