/**
 * @file    mmi_mapapp_view_id.h
 *
 * @brief   This file defines the view IDs for CB setting AP.
 * @author	joe.hsu@mstarsemi.com
 *
 * @version $Id: mmi_mapapp_view_id.h 8322 2008-03-28 12:15:46Z joe.hsu $
 */
#ifndef __MMI_MAPAPP_VIEW_ID_H__
#define __MMI_MAPAPP_VIEW_ID_H__

#include "mmi_mapapp.h"
#include "mmi_view_id_range.h"

#define INPUTEDITOR_HEIGHT              (MAIN_DEFVIEW_HEIGHT - MAIN_TITLE_HEIGHT)

enum
{
    /* View ID start */
    ID_MAPAPP_MAIN_VIEW = MMI_VIEW_ID_AP_BEGIN,
    ID_MAPAPP_VIEW,
    ID_MAPAPP_DATALIST_VIEW,
    ID_MAPAPP_MULTI_FIELD_INPUT_VIEW,
    ID_MAPAPP_KEYWORD_INPUT_VIEW,	
    ID_MAPAPP_IMAGE_THUMB_VIEW,
    ID_MAPAPP_LOGO_VIEW,
    ID_MAPAPP_DUO_SELECTION_VIEW,    
    /* View ID end */
};

enum
{
/* Widget ID start */
	ID_ABSCONTAINER_MAPAPP_MAPVIEW = 0,
	ID_BITMAP_MAPAPP_BITMAP,
	ID_IMG_MAPAPP_TITLE_BAR,
	ID_TEXT_MAPAPP_TITLE_BAR,
	ID_IMG_MAPAPP_ZOOM,
	ID_IMG_MAPAPP_ZOOM_STATUS,
	ID_BUTTON_MAPAPP_ZOOM_IN_PRESS_UNRRESS,
	ID_BUTTON_MAPAPP_ZOOM_OUT_PRESS_UNRRESS,
	ID_MENU_MAPAPP_SETTINGS,
	ID_MENUMODEL_MAPAPP_SETTINGS,
	ID_IMG_MAPAPP_NOTICE_BG,									
	ID_BUTTON_MAPAPP_PREVIOUS_MODE_PRESS_UNRRESS,
	ID_TEXT_MAPAPP_FOCUS_MODE,
	ID_BUTTON_MAPAPP_NEXT_MODE_PRESS_UNRRESS,
	ID_TITLE_MAPAPP_DATALIST_CONTENT_TITLE,
	ID_MENU_MAPPAPP_DATALIST_CONTENT_LIST,
	ID_TITLE_MAPAPP_MULTI_FIELD_INPUT_CONTENT_TITLE,
	ID_MENU_MAPAPP_MULTI_FIELD_INPUT_CONTENT_LIST,	
	ID_TITLE_MAPAPP_KEYWORD_INPUT_CONTENT_TITLE,
       ID_SCROLLBAR_MAPAPP_KEYWORD_INPUT,	
	ID_INPUT_MAPAPP_KEYWORD_INPUT,	
       ID_TITLE_MAPAPP_IMAGE_THUMB_CONTENT_TITLE,	
       ID_IMGGRID_MENU_MAPAPP_IMAGE_THUMB_CONTENT_LIST,
       ID_MENUMODEL_MAPAPP_THUMBPOI,       
       ID_MENUMODEL_MAPAPP_MAPVIEW_OPTIONMENU,
       ID_MENUMODEL_MAPAPP_MENU_OPTIONMENU,
       ID_MENUMODEL_MAPAPP_KEYWORDINPUT_OPTIONMENU,
       ID_ABSCONTAINER_MAPAPP_LOGO,
       ID_BITMAP_MAPAPP_LOGO_BITMAP,
       ID_BUTTON_MAPAPP_SERVICE_LEFT_ARROW,
       ID_BUTTON_MAPAPP_SERVICE_RIGHT_ARROW,
       ID_TITLE_MAPAPP_DUO_SELECTION_CONTENT_TITLE,       
       ID_MENU_MAPAPP_DUO_SELECTION_CONTENT_LIST,       
       /* Widget ID end */
};

enum
{
    /* Binary ID start */
    MNU_MAPAPP_DUAL_MASTER,
    MNU_MAPAPP_DUAL_SLAVE
};

#endif /* __MMI_MAPAPP_VIEW_ID_H__ */
