/**
* @file mmi_btobexsrv_sm.h
*
* State Machine Service - BTOBEXSRV
* Generated by XFSM v1.0, CodeVer=v0.24
*
* Class Id: CLSID_BTOBEXSRV
*
*
* @version $Id$
*/
#ifndef __MMI_BTOBEXSRV_SM_H__
#define __MMI_BTOBEXSRV_SM_H__

#include "mmi_mae_sm.h"
#include "mmi_class.h"

/**
 * Mode Tree Properties
 */
#define cBTOBEXSRV_ModeNumbers              10
#define cBTOBEXSRV_DependencyNumbers                21

/**
 * Modes (index should begin from 0 and increase continuously)
 */
#define cBTOBEXSRV_MODE_BTOBEXSrv               0
#define cBTOBEXSRV_MODE_Init                1
#define cBTOBEXSRV_MODE_Active              2
#define cBTOBEXSRV_MODE_Active_Idle             3
#define cBTOBEXSRV_MODE_Active_Sending              4
#define cBTOBEXSRV_MODE_Active_Sending_ConnOBEXLink             5
#define cBTOBEXSRV_MODE_Active_Sending_SendingFile              6
#define cBTOBEXSRV_MODE_Active_Receiving                7
#define cBTOBEXSRV_MODE_Active_Receiving_ReceivingFile              8
#define cBTOBEXSRV_MODE_Active_Receiving_ImportFile             9


/**
 * Internal Events
 */
#define BTOBEXSRV_IEVT_FINISH               (CLSID_BTOBEXSRV << 16 | 7)
#define BTOBEXSRV_IEVT_TO_SENDING               (CLSID_BTOBEXSRV << 16 | 8)
#define BTOBEXSRV_IEVT_TO_RECEIVING             (CLSID_BTOBEXSRV << 16 | 9)
#define BTOBEXSRV_IEVT_ACCEPT               (CLSID_BTOBEXSRV << 16 | 10)
#define BTOBEXSRV_IEVT_DENY             (CLSID_BTOBEXSRV << 16 | 11)
#define BTOBEXSRV_IEVT_TO_IDLE              (CLSID_BTOBEXSRV << 16 | 12)
#define BTOBEXSRV_IEVT_TO_IMPORT                (CLSID_BTOBEXSRV << 16 | 13)
#define BTOBEXSRV_IEVT_TRANS_INTERACTIVE_CNF                (CLSID_BTOBEXSRV << 16 | 14)


/**
 * Macros for triggering internal events
 */
#define TRIGGER_EVT_BTOBEXSRV_IEVT_FINISH(pSM, p1, p2)  MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_FINISH, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_TO_SENDING(pSM, p1, p2)  MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_TO_SENDING, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_TO_RECEIVING(pSM, p1, p2)    MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_TO_RECEIVING, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_ACCEPT(pSM, p1, p2)  MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_ACCEPT, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_DENY(pSM, p1, p2)    MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_DENY, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_TO_IDLE(pSM, p1, p2) MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_TO_IDLE, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_TO_IMPORT(pSM, p1, p2)   MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_TO_IMPORT, p1, p2)
#define TRIGGER_EVT_BTOBEXSRV_IEVT_TRANS_INTERACTIVE_CNF(pSM, p1, p2)   MAE_TriggerEvent(pSM, BTOBEXSRV_IEVT_TRANS_INTERACTIVE_CNF, p1, p2)


/*-------------------------------------------------------------------------*/
extern const SM_Mode_t BTOBEXSRV_modeTree[];
extern const SM_Transition_t BTOBEXSRV_transition[];
extern const SM_TransitionForEvent_t BTOBEXSRV_transForEvent[];
extern const SM_EventDep_t BTOBEXSRV_eventDependency[];

#endif /* __MMI_BTOBEXSRV_SM_H__ */
