ApBegin(RS,CLSID_DIALERAPP)
    WndBegin(DIALER_WND_DIALING)
        WndSetTitleVisiableRC(FALSE)
        WndSetAllSoftkeyRC({SK_NONE, SK_NONE, SK_CANCEL})
        WndSetStatusBarVisibleRC((boolean)VIEWSB_VISIABLE)
        WndSetBgPosRC(WDG_BG_POS_WHOLE)
        WndSetBgColorRC((RGBColor_t)DEF_THM_DIALERAPP_BG)

        WdgBegin(CLSID_TEXTWIDGET,TouchShortcutWdg)
            WdgTextCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC((FontCategory_t)FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC((WdgAlignment_e)(ALIGN_H_LEFT|ALIGN_V_TOP))
            WdgCommonSetTextColorRC((RGBColor_t)DEF_THM_DIALERAPP_TEXT)
        WdgEnd(CLSID_TEXTWIDGET,TouchShortcutWdg)
        WdgBegin(CLSID_TEXTWIDGET,ShortcutWidget)
            WdgTextCreateForWndRC({{0,0},{0,MAIN_DEFVIEW_WIDTH},TEXT_STYLE_COMMON})
#ifdef __APP_MMI_SMALLROM__
            WdgCommonSetFontCategoryRC((FontCategory_t)FONT_CAT_NORMAL)
#else	// !__APP_MMI_SMALLROM__
	    			WdgCommonSetFontCategoryRC((FontCategory_t)FONT_CAT_SUPERSMALL)
#endif// !__APP_MMI_SMALLROM__

            WdgCommonSetAlignmentRC((WdgAlignment_e)(ALIGN_H_LEFT|ALIGN_V_TOP))
            WdgCommonSetTextColorRC((RGBColor_t)DEF_THM_DIALERAPP_TEXT)
        WdgEnd(CLSID_TEXTWIDGET,ShortcutWidget)
#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_ABSCONTAINER,DialButtonAbsContainer)
			WdgAbsContainerCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_HEIGHT},0})
		WdgEnd(CLSID_ABSCONTAINER,DialButtonAbsContainer)

        WdgBegin(CLSID_IMAGEWIDGET,DialButtonBgImageWdg)

			WdgImageCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_BG_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_BG_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_BG_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_INPUT_NUMBER}})
			WdgImageSetDataByIDRC(CALL_IMG_INPUT_NUMBER)

        WdgEnd(CLSID_IMAGEWIDGET,DialButtonBgImageWdg)
#endif	// !__APP_MMI_SMALLROM__
        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg1)
#ifdef __APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_HEIGHT},WDG_MENU_TYPE_GRID})
 			WdgStaticMenuItemRC(12,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 10}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 11}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}}) \
			WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_WIDTH) 
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_COLNUM)
			WdgMenuSetToGridStyleRC({4, 3, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#else	// !__APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(12,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_01}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_02}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_03}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_04}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_05}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_06}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_07}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_08}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_09}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_10}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 10}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_11}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 11}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_12}}}) \
			WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_WIDTH)

			WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_COLNUM)
            WdgMenuSetToGridStyleRC({3, 4, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#endif	// !__APP_MMI_SMALLROM__
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg1)
        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg2)
#ifdef __APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(4,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_COLNUM)
			WdgMenuSetToGridStyleRC({4, 1, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#else	// !__APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_HEIGHT},WDG_MENU_TYPE_GRID})

            WdgStaticMenuItemRC(4,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CLEAR}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_ADD  }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_MESSAGE      }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, TXT_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_RETURN }}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_WIDTH)

            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_COLNUM)
            WdgMenuSetToGridStyleRC({DIALERAPP_RS_GRID_WDG2_HORZ, DIALERAPP_RS_GRID_WDG2_VERT, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#endif	// !__APP_MMI_SMALLROM__
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg2)

		WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg3)
			WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
			WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(2,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CALL_SIM1}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, TXT_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CALL_SIM2 }}}) \
			WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_WIDTH)
			WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_HEIGHT)
			WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_ROW_GAP)
			WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_COL_GAP)
			WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_COLNUM)
		WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg3)

        WdgBegin(CLSID_INPUTWIDGET,TouchInputWdg)

            WdgInputCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_HEIGHT},{FALSE,SKBOARD_DISABLE}})

            WdgInputSetMultilineRC((boolean)TRUE)
            WdgInputSetTextColorRC((RGBColor_t)DEF_THM_DIALERAPP_TEXT)
            WdgInputSetCursorColorRC((RGBColor_t)DEF_THM_DIALERAPP_CURSOR)
            WdgInputSetFontSizeRC((FontCategory_t)FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC((u32)(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP))
            WdgInputSetCurrentInputModeRC((u32)MAE_INPUTMODE_DIALING)
            WdgInputSetMaxByteLengthRC(CCSRV_MAX_CALL_NUMBER_RS<<1)
            WdgInputSetHandWritingEnableRC(FALSE)
	    WdgMenuSetToGridStyleRC({DIALERAPP_RS_GRID_WDG2_HORZ, DIALERAPP_RS_GRID_WDG2_VERT, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
        WdgEnd(CLSID_INPUTWIDGET,TouchInputWdg)
        WdgBegin(CLSID_INPUTWIDGET,InputWidget)
            WdgInputCreateForWndRC({{0,0},{0,MAIN_DEFVIEW_WIDTH},{FALSE,SKBOARD_DISABLE}})
            WdgInputSetMultilineRC((boolean)TRUE)
            WdgInputSetTextColorRC((RGBColor_t)DEF_THM_DIALERAPP_TEXT)
            WdgInputSetCursorColorRC((RGBColor_t)DEF_THM_DIALERAPP_CURSOR)
#ifdef __LCM_QQVGA_MMI__
			WdgInputSetFontSizeRC((FontCategory_t)FONT_CAT_NUM_NORMAL)
#else
            WdgInputSetFontSizeRC((FontCategory_t)FONT_CAT_NUM_LARGE)
#endif
            WdgInputSetLineGapRC((u32)(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP))
            WdgInputSetCurrentInputModeRC((u32)MAE_INPUTMODE_DIALING)
            WdgInputSetMaxByteLengthRC(CCSRV_MAX_CALL_NUMBER_RS<<1)
        WdgEnd(CLSID_INPUTWIDGET,InputWidget)
#ifdef __SMART_DIALER__
        WdgBegin(CLSID_TEXTWIDGET,ContactNumberWdg)
            WdgTextCreateForWndRC( {{DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_NUMBER_POS_X,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_NUMBER_POS_Y},{DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_NUMBER_WIDTH,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_NUMBER_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,ContactNumberWdg)
        WdgBegin(CLSID_TEXTWIDGET,ContactInfoWdg)
            WdgTextCreateForWndRC( {{DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_INFO_POS_X,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_INFO_POS_Y},{DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_INFO_WIDTH,MAIN_LCD_ONELINE_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,ContactInfoWdg)
        WdgBegin(CLSID_IMAGEWIDGET,ContactImageWdg)
            WdgImageCreateForWndRC({ {DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_IMAGE_POS_X,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_IMAGE_POS_Y},{DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_IMAGE_WIDTH,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_CONTACT_ICO_SMALL}} )
            WdgImageSetDataByIDRC(CALL_IMG_CALL_CONTACT_ICO_SMALL)
        WdgEnd(CLSID_IMAGEWIDGET,ContactImageWdg)
        WdgBegin(CLSID_MENUWIDGET,ContactMenuWdg)
            WdgMenuCreateForWndRC({ {0,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_MENU_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_SMARTDIAL_CONTACT_MENU_HEIGHT},WDG_MENU_TYPE_NORMAL })
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE_TEXT)
        WdgEnd(CLSID_MENUWIDGET,ContactMenuWdg)
#endif	
    WndEnd(DIALER_WND_DIALING)

    WndBegin(DIALER_WND_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,DialerOpt)
#ifdef __SMART_DIALER__
	VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,7})
        VtmCreateOptionMenuDataRC(7,{
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_CALL},TXT_OIL1_N_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_VIDEOCALL},TXT_OIL1_N_VIDEO_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_IPCALL},TXT_OIL1_N_IP_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_SAVE},TXT_OIL1_N_SAVE},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_SMS},TXT_OIL1_N_SEND},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_VIEW_CONTACT},TXT_OIL1_N_VIEW_CONTACT},
        	{{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_SEARCH_SETTING},TXT_OIL1_N_SEARCH_SETTING}})
#else
	VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,5})
        VtmCreateOptionMenuDataRC(5,{
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_CALL},TXT_OIL1_N_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_VIDEOCALL},TXT_OIL1_N_VIDEO_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_IPCALL},TXT_OIL1_N_IP_CALL},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_SAVE},TXT_OIL1_N_SAVE},
        	{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_OPTION_SMS},TXT_OIL1_N_SEND}})
#endif
        WdgEnd(CLSID_VTMOPTIONMENU,DialerOpt)
    WndEnd(DIALER_WND_OPTION)

#ifdef __SMART_DIALER__
    WndBegin(DIALER_WND_SEARCH_SETTING_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,DialerSearchSettingOpt)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,4})
            VtmCreateOptionMenuDataRC(4,{
            	{{MENUMODEL_ITEM_VISABLE, {SK_SAVE, SK_OK, SK_CANCEL}, MNU_DIALERAPP_SEARCH_NUMBER}, TXT_OIL2_N_NUMBER_SEARCH},
		        {{MENUMODEL_ITEM_VISABLE, {SK_SAVE, SK_OK, SK_CANCEL}, MNU_DIALERAPP_SEARCH_LETTER}, TXT_OIL2_N_LETTER_SEARCH},
		        {{MENUMODEL_ITEM_VISABLE, {SK_SAVE, SK_OK, SK_CANCEL}, MNU_DIALERAPP_SEARCH_PINYIN_FIRST}, TXT_OIL2_N_PINYIN_FIRST_LETTER},
		        {{MENUMODEL_ITEM_VISABLE, {SK_SAVE, SK_OK, SK_CANCEL}, MNU_DIALERAPP_SEARCH_STROKES}, TXT_OIL2_N_STROKES_SEARCH}     })
        WdgEnd(CLSID_VTMOPTIONMENU,DialerSearchSettingOpt)
    WndEnd(DIALER_WND_SEARCH_SETTING_OPTION)
#endif    	

    WndBegin(DIALER_WND_SEND)
        WdgBegin(CLSID_VTMMENU,DialerMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_SEND_VIA,WDG_MENU_TYPE_NUMERIC,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,2,0,0})
            VtmCreateMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_SEND_VIA_SMS},{0,TXT_LTL_N_SMS}},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_DIALERAPP_SEND_VIA_MMS},{0,TXT_LTL_N_MMS}}})
        WdgEnd(CLSID_VTMMENU,DialerMenu)
    WndEnd(DIALER_WND_SEND)
ApEnd(RS,CLSID_DIALERAPP)

