#ifndef __MMI_IDLEAPP_ID_H__
#define __MMI_IDLEAPP_ID_H__

typedef enum IdleWndId_e_
{
    IDLE_WND_DESKTOP = WND_ID_APP_BASE,
    IDLE_WND_CONFIGMENU,
    IDLE_WND_CONFIGPREVIEW,

    /*<----- Sub LCD -----*/
    IDLE_WND_SUB_DESKTOP = WND_ID_APP_SUB_BASE,
    /*------ Sub LCD ---->*/
} IdleWndId_e;

typedef enum
{
    ///IdleConfigEntryId_e
    MNU_IDLE_CONFIGENTRY_FIRST = 0,
    MNU_IDLE_CONFIGENTRY_NEW_WIDGET = MNU_IDLE_CONFIGENTRY_FIRST,
    MNU_IDLE_CONFIGENTRY_NEW_SHORTCUT,
    MNU_IDLE_CONFIGENTRY_SET_LIVEWALLPAPER,
    MNU_IDLE_CONFIGENTRY_LAST = MNU_IDLE_CONFIGENTRY_SET_LIVEWALLPAPER,

    ///IdleConfigMenuForWidgetId_e
    MNU_IDLE_CONFIGMENU_WIDGET_FIRST,
    MNU_IDLE_CONFIGMENU_WIDGET_CLOCK = MNU_IDLE_CONFIGMENU_WIDGET_FIRST,
    MNU_IDLE_CONFIGMENU_WIDGET_PHOTO,
    MNU_IDLE_CONFIGMENU_WIDGET_CALENDAR,
    MNU_IDLE_CONFIGMENU_WIDGET_MESSAGE,
    MNU_IDLE_CONFIGMENU_WIDGET_PHONEBOOK,
    MNU_IDLE_CONFIGMENU_WIDGET_WORLDCLOCK,
    MNU_IDLE_CONFIGMENU_WIDGET_MPLAYER,
    MNU_IDLE_CONFIGMENU_WIDGET_FMRADIO,
    MNU_IDLE_CONFIGMENU_WIDGET_OPERATOR,
    MNU_IDLE_CONFIGMENU_WIDGET_NOTEPAD,
    MNU_IDLE_CONFIGMENU_WIDGET_SEARCH,
    MNU_IDLE_CONFIGMENU_WIDGET_LAST = MNU_IDLE_CONFIGMENU_WIDGET_SEARCH,

    ///IdleConfigMenuForWallpaperId_e
    MNU_IDLE_CONFIGMENU_WALLPAPER_FIRST,
    MNU_IDLE_CONFIGMENU_WALLPAPER_FLASH_LIGHTING = MNU_IDLE_CONFIGMENU_WALLPAPER_FIRST,
    MNU_IDLE_CONFIGMENU_WALLPAPER_SNAKELINE,
    MNU_IDLE_CONFIGMENU_WALLPAPER_EXPLOSION,
    MNU_IDLE_CONFIGMENU_WALLPAPER_COMET,
    MNU_IDLE_CONFIGMENU_WALLPAPER_LEAF,
    MNU_IDLE_CONFIGMENU_WALLPAPER_TUNNEL,
    MNU_IDLE_CONFIGMENU_WALLPAPER_FIREWORK,
    MNU_IDLE_CONFIGMENU_WALLPAPER_EARTHROT,
    MNU_IDLE_CONFIGMENU_WALLPAPER_STARFIELD,
    MNU_IDLE_CONFIGMENU_WALLPAPER_STARLIFE,
    MNU_IDLE_CONFIGMENU_WALLPAPER_FALLSNOW,
    MNU_IDLE_CONFIGMENU_WALLPAPER_FISH,
    MNU_IDLE_CONFIGMENU_WALLPAPER_IMAGE,
    MNU_IDLE_CONFIGMENU_WALLPAPER_LAST = MNU_IDLE_CONFIGMENU_WALLPAPER_IMAGE,

} IdleMenuId_e;

enum
{
    IDLE_DESKTOP_FULLSCREEN_ABSCONTAINER = APP_WDG_START,
    IDLE_DESKTOP_MAIN_ABSCONTAINER,
    IDLE_DESKTOP_SOFTKEYWIDGET,
    IDLE_DESKTOP_FADEOUTWIDGET,
    IDLE_DESKTOP_MEDIA_NAME_TEXTWIDGET,
    IDLE_DESKTOP_NETWORK_THMTEXTWIDGET,
    IDLE_DESKTOP_NETWORK_SLAVE_THMTEXTWIDGET,
    IDLE_DESKTOP_STK_THMTEXTWIDGET,
    IDLE_DESKTOP_STK_SLAVE_THMTEXTWIDGET,
    IDLE_DESKTOP_WARNING_IMAGEWIDGET,
    IDLE_DESKTOP_IMEASSISTWIDGET,
    IDLE_DESKTOP_COUNTDOWN_ALIVEWIDGET,
    IDLE_DESKTOP_CB_BG_IMAGEWIDGET,
    IDLE_DESKTOP_EVENT_TEXTWIDGET,
    IDLE_DESKTOP_LOCAL_TIME_THMTEXTWIDGET,
    IDLE_DESKTOP_LOCAL_12H_THMTEXTWIDGET,
    IDLE_DESKTOP_SEPERATOR_THMTEXTWIDGET,
    IDLE_DESKTOP_REMOTE_TIME_THMTEXTWIDGET,
    IDLE_DESKTOP_REMOTE_12H_THMTEXTWIDGET,
    IDLE_DESKTOP_WST_DATE_THMTEXTWIDGET,
    IDLE_DESKTOP_CHN_DATE_THMTEXTWIDGET,
    IDLE_DESKTOP_VIDEO_OSDWIDGET,

    IDLE_CONFIGMENU_MENUWIDGET,

    IDLE_CONFIGPREVIEW_FULLSCREEN_ABSCONTAINER,
    IDLE_CONFIGPREVIEW_TITLE_TEXTWIDGET,
    IDLE_CONFIGPREVIEW_LEFTINDICATOR_BUTTONWIDGET,
    IDLE_CONFIGPREVIEW_RIGHTINDICATOR_BUTTONWIDGET,
    IDLE_CONFIGPREVIEW_THUMBNAIL_IMAGEWIDGET,
    IDLE_CONFIGPREVIEW_SELECT_BUTTONWIDGET,
    IDLE_CONFIGPREVIEW_INFO_ABSCONTAINER,
    IDLE_CONFIGPREVIEW_STYLE1_TEXTWIDGET,
    IDLE_CONFIGPREVIEW_STYLE2_TEXTWIDGET,
    IDLE_CONFIGPREVIEW_EXIST_FADEOUTWIDGET,
    IDLE_CONFIGPREVIEW_EXIST_IMAGEWIDGET,
    IDLE_CONFIGPREVIEW_EXIST_TEXTWIDGET,
    IDLE_CONFIGPREVIEW_ANIMATION_SLIDEWIDGET,

    IDM_IDLEICON_THUMBNAIL_BUTTON_MODEL,
    IDM_IDLEICON_CONFIG_BUTTON_MODEL,
    IDM_IDLEICON_MAINMENU_BUTTON_MODEL,
    IDM_IDLEICON_DIALER_BUTTON_MODEL,
    IDM_IDLEICON_PHB_BUTTON_MODEL,

    IDM_IDLEICON_APPANEL_BUTTON_MODEL,
    IDM_IDLEICON_SHORTCUT_BUTTON_MODEL,

    IDM_IDLEICON_LEFT_ARROW_BUTTON_MODEL,
    IDM_IDLEICON_RIGHT_ARROW_BUTTON_MODEL,
    IDM_IDLEICON_SETTING_BUTTON_MODEL,

    /*<----- Sub LCD -----*/
    IDLE_SUB_DESKTOP_BG_IMAGEWIDGET,
    IDLE_SUB_DESKTOP_FADEOUTWIDGET,
    IDLE_SUB_DESKTOP_IDLE_INFO_ABSCONTAINER,
    IDLE_SUB_DESKTOP_TIME_IMGGRIDMENUWIDGET,
    IDLE_SUB_DESKTOP_12H_TEXTWIDGET,
    IDLE_SUB_DESKTOP_DATE_TEXTWIDGET,
    IDLE_SUB_DESKTOP_MEDIA_NAME_TEXTWIDGET,
    IDLE_SUB_DESKTOP_COUNT_DOWN_IMAGEWIDGT,
    IDLE_SUB_DESKTOP_NETWORK_TEXTWIDGET,
    IDLE_SUB_DESKTOP_NETWORK_SLAVE_TEXTWIDGET,
    IDLE_SUB_DESKTOP_DIALOG_INFO_BG_IMAGEWIDGET,
    IDLE_SUB_DESKTOP_DIALOG_INFO_TEXTWIDGET,
    IDLE_SUB_DESKTOP_NEW_MSG_IMAGEWIDGET,
    IDLE_SUB_DESKTOP_NEW_MSG_TEXTWIDGET,
    IDLE_SUB_DESKTOP_MISS_CALL_IMAGEWIDGET,
    IDLE_SUB_DESKTOP_MISS_CALL_TEXTWIDGET,
    IDLE_SUB_DESKTOP_MISS_CALL_SLAVE_IMAGEWIDGET,
    IDLE_SUB_DESKTOP_MISS_CALL_SLAVE_TEXTWIDGET,
    /*------ Sub LCD ---->*/
};

#endif //__MMI_IDLEAPP_ID_H__

