#ifndef __MMI_IDLEAPP_VIEW_ID_H__
#define __MMI_IDLEAPP_VIEW_ID_H__

#include "mae_menulabel.h"
#include "mmi_mae_menumodel.h"
#include "mmi_view_id_range.h"
#include "mmi_idleapp.h"
#include "mmi_mae_common_def.h"
#include "mmi_mae_widget_properties.h"
#include "mmi_mae_inputcontroller.h"
#include "mmi_layout.h"
#include "mmi_wdg_list.h"
#include "mmi_wdg_image.h"
#include "mmi_wdg_text.h"
#include "mmi_common_thmid.h"
#include "mmi_common_alivewidget.h"

enum
{
/* View ID start */
	IDLEAPP_ACTIVE_IDLEVIEW = MMI_VIEW_ID_AP_BEGIN,
	IDLEAPP_ACTIVE_DIALINGVIEW,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_ONAPP,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_OFFAPP,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_SECAPP,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_MCAAPP,
	IDLEAPP_BLANK_VIEW,
	IDLEAPP_ACTIVE_TOUCHDIALINGVIEW,
	IDLEAPP_ACTIVE_IDLEVIEW_PET_CLOCK
	
/* View ID end */
};

enum
{
/* Widget ID start */
    IDLEAPP_ACTIVE_IDLE_FULLSCREENCONTAINER = 0,
    IDLEAPP_ACTIVE_IDLE_WALLPAPERWIDGET,
	IDLEAPP_ACTIVE_IDLE_MAINCONTAINER,
	IDLEAPP_ACTIVE_IDLE_BGWIDGET,
	IDLEAPP_ACTIVE_IDLE_NETWORKWIDGET,
	IDLEAPP_ACTIVE_IDLE_NETWORKWIDGET_SLAVE,
	IDLEAPP_ACTIVE_IDLE_TIMEWIDGET_LOCAL,
	IDLEAPP_ACTIVE_IDLE_TIMEWIDGET_REMOTE,
	IDLEAPP_ACTIVE_IDLE_DATEWIDGET_WST,
	IDLEAPP_ACTIVE_IDLE_DATEWIDGET_CHN,
	IDLEAPP_ACTIVE_IDLE_EVENTWIDGET,
	IDLEAPP_ACTIVE_DIALING_MAINCONTAINER,
	IDLEAPP_ACTIVE_DIALING_BGWIDGET,
	IDLEAPP_ACTIVE_DIALING_PROPCONTAINER,
	IDLEAPP_ACTIVE_DIALING_SCROLLWIDGET,
	IDLEAPP_ACTIVE_DIALING_INPUTWIDGET,
	IDLEAPP_ACTIVE_DIALING_SHORTCUTWIDGET,
	IDLEAPP_OPTIONMENUTEST_MENUMODEL_L1,
	IDLEAPP_OPTIONMENUTEST_MENUMODEL_L2_SHORTCUT,
	IDLEAPP_OPTIONMENUTEST_MENUMODEL_L2_SAVE,
	IDLEAPP_DIALINGOPTIONVIEW_MENUMODEL,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_TITLEWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_MENUWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_ONAPP_TITLEWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_ONAPP_MENUWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_OFFAPP_TITLEWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_OFFAPP_MENUWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_SECAPP_TITLEWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_SECAPP_MENUWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_MCAAPP_TITLEWIDGET,
	IDLEAPP_ACTIVE_IDLE_TASKVIEW_MCAAPP_MENUWIDGET,
	IDLEAPP_BLANK_VIEW_MAINCONTAINER,
	IDLEAPP_ACTIVE_IDLE_12HWIDGET_LOCAL,
	IDLEAPP_ACTIVE_IDLE_12HWIDGET_REMOTE,
	IDLEAPP_ACTIVE_IDLE_SEPWIDGET,
	IDLEAPP_ACTIVE_IDLE_CBBGWIDGET,
	IDLEAPP_ACTIVE_IDLE_SKWIDGET,
	IDLEAPP_ACTIVE_TOUCHDIALING_MAINCONTAINER,
	IDLEAPP_ACTIVE_TOUCHDIALING_INPUTWIDGET,
	IDLEAPP_ACTIVE_TOUCHDIALING_SHORTCUTWIDGET,
	IDLEAPP_ACTIVE_TOUCHDIALING_GRIDWIDGET1,
	IDLEAPP_ACTIVE_TOUCHDIALING_BUTTONWIDGET1,
	IDLEAPP_ACTIVE_TOUCHDIALING_GRIDWIDGET2,
	IDLEAPP_ACTIVE_TOUCHDIALING_BUTTONWIDGET2,
	IDLEAPP_ACTIVE_IDLE_STKWIDGET,
	IDLEAPP_ACTIVE_IDLE_STKWIDGET_SLAVE,
	IDLEAPP_ACTIVE_IDLE_BGTRANSITIONWIDGET,
	IDLEAPP_ACTIVE_IDLE_ALARMWIDGET,
	IDLEAPP_ACTIVE_IDLE_SHORTCUTWIDGET,
	IDLEAPP_ACTIVE_IDLE_SHORTCUTBUTTON_OFF,
	IDLEAPP_ACTIVE_IDLE_SHORTCUTBUTTON_ON,
	IDLEAPP_ACTIVE_IDLE_IMEASSISTWIDGET,
	IDLEAPP_ACTIVE_IDLE_ALIVEWIDGET_CLOCK,
	IDLEAPP_ACTIVE_IDLE_ALIVEWIDGET_DOG,
	IDLEAPP_ACTIVE_IDLE_ALIVEWIDGET_COUNTDOWN,
	IDLEAPP_ACTIVE_IDLE_FADEOUTWIDGET,
	IDLEAPP_ACTIVE_IDLE_MEDIANAMEWIDGET,
	IDLEAPP_ACTIVE_IDLE_GAMEWIDGET,
	IDLEAPP_ACTIVE_IDLE_PROFILWIDGET,

	IDLEAPP_ACTIVE_IDLE_MP_DESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_FM_DESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_SEARCH_DESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_CALENDARDESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_OPDESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_NOTEDESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_DCLOCKDESKTOPWIDGET,
	IDLEAPP_ACTIVE_IDLE_PEDOMETERDESKTOPWIDGET
/* Widget ID end */
};

enum
{
/* Model ID start */
	IDM_MPDESKTOPWDG_VOL_BUTTON_MODEL = 0,
	IDM_MPDESKTOPWDG_VOL_DISABLE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_PRE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_PRE_DISABLE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_PLAY_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_PLAY_DISABLE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_NEXT_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_NEXT_DISABLE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_PAUSE_BUTTON_MODEL,
	IDM_MPDESKTOPWDG_STOP_BUTTON_MODEL,

    IDM_FMDESKTOPWDG_VOL_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_VOL_DISABLE_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_PRE_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_PRE_DISABLE_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_NEXT_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_NEXT_DISABLE_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_POWERON_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_POWEROFF_BUTTON_MODEL,
    IDM_FMDESKTOPWDG_POWER_DISABLE_BUTTON_MODEL,
	
	IDM_IDLESETTING_WALLPAPER_BUTTON_MODEL,
	IDM_IDLESETTING_AP_BUTTON_MODEL,
	IDM_IDLESETTING_DOCK_BUTTON_MODEL,
	IDM_IDLESETTING_CLOSE_BUTTON_MODEL,

	IDM_SEARCHDESKTOPWDG_SEARCH_BUTTON_MODEL
/* Model ID end */
};



#endif /* __MMI_IDLEAPP_VIEW_ID_H__ */
