

ApBegin(RS,CLSID_ANDROID_KEYGUARDAPP)

#ifdef __UI_STYLE_MMI_ANDROID_KEYGUARD__

    WndBegin(ANDROID_KEYGUARD_WND_MAIN)
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)
        WndSetAllSoftkeyRC({SK_UNLOCK, SK_NONE, SK_NONE})

#ifdef __UI_STYLE_MMI_ANDROID_4_0__
        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,WALLPAPER_IMG_06}})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_IMGGRID_MENUWIDGET,EMNumWdg)
            WdgMenuCreateForWndRC({{ANDROID_KEYGUARD_EMNUMWIDGET_POS_X,ANDROID_KEYGUARD_EMNUMWIDGET_POS_Y},{ANDROID_KEYGUARD_EMNUMWIDGET_WIDTH,ANDROID_KEYGUARD_EMNUMWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_TOP)
            WdgStaticMenuItemRC(3, {
                            {{MENUMODEL_ITEM_HIDE,{SK_SELECT,SK_OK,SK_BACK},0},{IMG_NULL_ID, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_HIDE,{SK_SELECT,SK_OK,SK_BACK},1},{IMG_NULL_ID, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_HIDE,{SK_SELECT,SK_OK,SK_BACK},2},{IMG_NULL_ID, TXT_NULL_ID}}
                            } )
            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(ANDROID_KEYGUARD_EMITEM_WIDTH)
            WdgMenuSetItemHeightRC(ANDROID_KEYGUARD_EMITEM_HEIGHT)
            WdgMenuSetFixedNumRC(3)
            WdgMenuSetToGridStyleRC({3, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})
        
		WdgEnd(CLSID_IMGGRID_MENUWIDGET,EMNumWdg)
		
#else // __UI_STYLE_MMI_ANDROID_4_0__
        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
            WdgImageCreateForWndRC({{MAIN_BG_X,MAIN_BG_Y},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,WALLPAPER_IMG_06}})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,UnlockWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_LOCKWIDGET_POS_X,ANDROID_KEYGUARD_LOCKWIDGET_POS_Y},{ANDROID_KEYGUARD_LOCKWIDGET_WIDTH,ANDROID_KEYGUARD_LOCKWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED)
        WdgEnd(CLSID_IMAGEWIDGET,UnlockWdg)

        WdgBegin(CLSID_FADEOUTWIDGET,DarkWdg)
            WdgFadeoutCreateForWndRC({{ANDROID_KEYGUARD_DARKNESSWIDGET_POS_X,ANDROID_KEYGUARD_DARKNESSWIDGET_POS_Y-ANDROID_KEYGUARD_DARKNESSWIDGET_POS_Y},{ANDROID_KEYGUARD_DARKNESSWIDGET_WIDTH,ANDROID_KEYGUARD_DARKNESSWIDGET_HEIGHT},FADEOUT_LEVEL_4})
        WdgEnd(CLSID_FADEOUTWIDGET,DarkWdg)

        WdgBegin(CLSID_TEXTWIDGET,EMNumWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_EMNUMWIDGET_POS_X,ANDROID_KEYGUARD_EMNUMWIDGET_POS_Y-ANDROID_KEYGUARD_DARKNESSWIDGET_POS_Y},{ANDROID_KEYGUARD_EMNUMWIDGET_WIDTH,ANDROID_KEYGUARD_EMNUMWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_SUPERLARGE)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_DIAL_NUMBER_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,EMNumWdg)
#endif // __UI_STYLE_MMI_ANDROID_4_0__


#ifdef __UI_STYLE_MMI_ANDROID_4_0__
        WdgBegin(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
            WdgMenuCreateForWndRC({{ANDROID_KEYGUARD_TIMEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_TIMEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_TIMEWIDGET_WIDTH,ANDROID_KEYGUARD_TIMEWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_TOP)
            WdgStaticMenuItemRC(5, {
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},0},{ANDROID_4_KEYGARD_IMG_CLOCK_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},1},{ANDROID_4_KEYGARD_IMG_CLOCK_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},2},{ANDROID_4_KEYGARD_IMG_CLOCK_COLON, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},3},{ANDROID_4_KEYGARD_IMG_CLOCK_9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},4},{ANDROID_4_KEYGARD_IMG_CLOCK_9, TXT_NULL_ID}},
                            } )

            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(32)
            WdgMenuSetItemHeightRC(50)
            WdgMenuSetFixedNumRC(5)
            WdgMenuSetToGridStyleRC({5, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})

        WdgEnd(CLSID_IMGGRID_MENUWIDGET,TimeWdg)

        WdgBegin(CLSID_TEXTWIDGET,I12HWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_12HWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_12HWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_12HWIDGET_WIDTH,ANDROID_KEYGUARD_12HWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PDL_N_AM)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TIME_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_TOP)
        WdgEnd(CLSID_TEXTWIDGET,I12HWdg)

        WdgBegin(CLSID_TEXTWIDGET,DateWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_DATEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_DATEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_DATEWIDGET_WIDTH,ANDROID_KEYGUARD_DATEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,DateWdg)

        WdgBegin(CLSID_TEXTWIDGET,MediaNameWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_MEDIANAMEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_MEDIANAMEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_MEDIANAMEWIDGET_WIDTH,ANDROID_KEYGUARD_MEDIANAMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MediaNameWdg)

        WdgBegin(CLSID_IMAGEWIDGET,CountdownWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_COUNTDOWN_POS_X_OFFSET,ANDROID_KEYGUARD_COUNTDOWN_POS_Y_OFFSET},{ANDROID_KEYGUARD_COUNTDOWN_WIDTH,ANDROID_KEYGUARD_COUNTDOWN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_COUNDOWN_TIMER}})
            WdgImageSetDataByIDRC(ANDROID_4_KEYGARD_IMG_COUNTDOWN_TIMER)
        WdgEnd(CLSID_IMAGEWIDGET,CountdownWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NETWORK_POS_X,ANDROID_KEYGUARD_NETWORK_POS_Y},{ANDROID_KEYGUARD_NETWORK_WIDTH,ANDROID_KEYGUARD_NETWORK_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkSlaveWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NETWORK_SLAVE_POS_X,ANDROID_KEYGUARD_NETWORK_SLAVE_POS_Y},{ANDROID_KEYGUARD_NETWORK_SLAVE_WIDTH,ANDROID_KEYGUARD_NETWORK_SLAVE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkSlaveWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MissCallWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_MISS_CALL_POS_X_OFFSET,ANDROID_KEYGUARD_MISS_CALL_POS_Y_OFFSET},{ANDROID_KEYGUARD_MISS_CALL_WIDTH,ANDROID_KEYGUARD_MISS_CALL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MISS_CALL}})
            WdgImageSetDataByIDRC(ANDROID_4_KEYGARD_IMG_MISS_CALL)
        WdgEnd(CLSID_IMAGEWIDGET,MissCallWdg)

        WdgBegin(CLSID_TEXTWIDGET,MissCallTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_MISS_CALL_TEXT_POS_X,ANDROID_KEYGUARD_MISS_CALL_TEXT_POS_Y},{ANDROID_KEYGUARD_MISS_CALL_TEXT_WIDTH,ANDROID_KEYGUARD_MISS_CALL_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MissCallTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,NewMsgWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_NEW_MSG_POS_X_OFFSET,ANDROID_KEYGUARD_NEW_MSG_POS_Y_OFFSET},{ANDROID_KEYGUARD_NEW_MSG_WIDTH,ANDROID_KEYGUARD_NEW_MSG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MESSAGE}})
            WdgImageSetDataByIDRC(ANDROID_4_KEYGARD_IMG_MESSAGE)
        WdgEnd(CLSID_IMAGEWIDGET,NewMsgWdg)

        WdgBegin(CLSID_TEXTWIDGET,NewMsgTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NEW_MSG_TEXT_POS_X,ANDROID_KEYGUARD_NEW_MSG_TEXT_POS_Y},{ANDROID_KEYGUARD_NEW_MSG_TEXT_WIDTH,ANDROID_KEYGUARD_NEW_MSG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NewMsgTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DialogInfoBGWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_DIALOG_INFO_BG_POS_X,ANDROID_KEYGUARD_DIALOG_INFO_BG_POS_Y},{ANDROID_KEYGUARD_DIALOG_INFO_BG_WIDTH,ANDROID_KEYGUARD_DIALOG_INFO_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_UNLOCK_NOTICE_BG}})
            WdgImageSetDataByIDRC(ANDROID_4_KEYGARD_NOTICE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,DialogInfoBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,DialogInfoTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_DIALOG_INFO_TEXT_POS_X,ANDROID_KEYGUARD_DIALOG_INFO_TEXT_POS_Y},{ANDROID_KEYGUARD_DIALOG_INFO_TEXT_WIDTH,ANDROID_KEYGUARD_DIALOG_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE|LAYOUT_ELLIPSIS)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
        WdgEnd(CLSID_TEXTWIDGET,DialogInfoTextWdg)

#else // __UI_STYLE_MMI_ANDROID_4_0__
        WdgBegin(CLSID_IMGGRID_MENUWIDGET,TimeWdg)
            WdgMenuCreateForWndRC({{ANDROID_KEYGUARD_TIMEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_TIMEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_TIMEWIDGET_WIDTH,ANDROID_KEYGUARD_TIMEWIDGET_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgCommonSetPaddingDataRC({0,0,0,0})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_BOTTOM)
            WdgStaticMenuItemRC(5, {
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},0},{ANDROID_COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},1},{ANDROID_COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},2},{ANDROID_COMMON_IMG_LOCKED_SYMBOL, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},3},{ANDROID_COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_BACK},4},{ANDROID_COMMON_IMG_LOCKED_NUM9, TXT_NULL_ID}},
                            } )

            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetFirstItemRC(0)
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGE)
            WdgMenuSetItemWidthRC(29)
            WdgMenuSetItemHeightRC(40)
            WdgMenuSetFixedNumRC(5)
            WdgMenuSetToGridStyleRC({5, 1, GRID_FIX_LAYOUT_IN_SINGLE_PAGE})

        WdgEnd(CLSID_IMGGRID_MENUWIDGET,TimeWdg)

        WdgBegin(CLSID_TEXTWIDGET,I12HWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_12HWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_12HWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_12HWIDGET_WIDTH,ANDROID_KEYGUARD_12HWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_PDL_N_AM)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TIME_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_BOTTOM)
        WdgEnd(CLSID_TEXTWIDGET,I12HWdg)

        WdgBegin(CLSID_TEXTWIDGET,DateWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_DATEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_DATEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_DATEWIDGET_WIDTH,ANDROID_KEYGUARD_DATEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_DATE_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,DateWdg)

        WdgBegin(CLSID_TEXTWIDGET,MediaNameWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_MEDIANAMEWIDGET_POS_X_OFFSET,ANDROID_KEYGUARD_MEDIANAMEWIDGET_POS_Y_OFFSET},{ANDROID_KEYGUARD_MEDIANAMEWIDGET_WIDTH,ANDROID_KEYGUARD_MEDIANAMEWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COMMON_COLOR_KEYPAD_LOCKED_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MediaNameWdg)

        WdgBegin(CLSID_IMAGEWIDGET,CountdownWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_COUNTDOWN_POS_X_OFFSET,ANDROID_KEYGUARD_COUNTDOWN_POS_Y_OFFSET},{ANDROID_KEYGUARD_COUNTDOWN_WIDTH,ANDROID_KEYGUARD_COUNTDOWN_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_COUNDOWN_TIMER}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_COUNDOWN_TIMER)
        WdgEnd(CLSID_IMAGEWIDGET,CountdownWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NETWORK_POS_X,ANDROID_KEYGUARD_NETWORK_POS_Y},{ANDROID_KEYGUARD_NETWORK_WIDTH,ANDROID_KEYGUARD_NETWORK_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkWdg)

        WdgBegin(CLSID_TEXTWIDGET,NetworkSlaveWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NETWORK_SLAVE_POS_X,ANDROID_KEYGUARD_NETWORK_SLAVE_POS_Y},{ANDROID_KEYGUARD_NETWORK_SLAVE_WIDTH,ANDROID_KEYGUARD_NETWORK_SLAVE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NIL_N_NETWORK_SEARCHING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NetworkSlaveWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MissCallWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_MISS_CALL_POS_X_OFFSET,ANDROID_KEYGUARD_MISS_CALL_POS_Y_OFFSET},{ANDROID_KEYGUARD_MISS_CALL_WIDTH,ANDROID_KEYGUARD_MISS_CALL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MISS_CALL}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MISS_CALL)
        WdgEnd(CLSID_IMAGEWIDGET,MissCallWdg)

        WdgBegin(CLSID_TEXTWIDGET,MissCallTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_MISS_CALL_TEXT_POS_X,ANDROID_KEYGUARD_MISS_CALL_TEXT_POS_Y},{ANDROID_KEYGUARD_MISS_CALL_TEXT_WIDTH,ANDROID_KEYGUARD_MISS_CALL_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,MissCallTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,NewMsgWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_NEW_MSG_POS_X_OFFSET,ANDROID_KEYGUARD_NEW_MSG_POS_Y_OFFSET},{ANDROID_KEYGUARD_NEW_MSG_WIDTH,ANDROID_KEYGUARD_NEW_MSG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LOCKED_MESSAGE}})
            WdgImageSetDataByIDRC(COMMON_IMG_LOCKED_MESSAGE)
        WdgEnd(CLSID_IMAGEWIDGET,NewMsgWdg)

        WdgBegin(CLSID_TEXTWIDGET,NewMsgTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_NEW_MSG_TEXT_POS_X,ANDROID_KEYGUARD_NEW_MSG_TEXT_POS_Y},{ANDROID_KEYGUARD_NEW_MSG_TEXT_WIDTH,ANDROID_KEYGUARD_NEW_MSG_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START|ALIGN_V_MIDDLE)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
        WdgEnd(CLSID_TEXTWIDGET,NewMsgTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DialogInfoBGWdg)
            WdgImageCreateForWndRC({{ANDROID_KEYGUARD_DIALOG_INFO_BG_POS_X,ANDROID_KEYGUARD_DIALOG_INFO_BG_POS_Y},{ANDROID_KEYGUARD_DIALOG_INFO_BG_WIDTH,ANDROID_KEYGUARD_DIALOG_INFO_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_UNLOCK_NOTICE_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_UNLOCK_NOTICE_BG)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,DialogInfoBGWdg)

        WdgBegin(CLSID_TEXTWIDGET,DialogInfoTextWdg)
            WdgTextCreateForWndRC({{ANDROID_KEYGUARD_DIALOG_INFO_TEXT_POS_X,ANDROID_KEYGUARD_DIALOG_INFO_TEXT_POS_Y},{ANDROID_KEYGUARD_DIALOG_INFO_TEXT_WIDTH,ANDROID_KEYGUARD_DIALOG_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE|LAYOUT_ELLIPSIS)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,DialogInfoTextWdg)

#endif // __UI_STYLE_MMI_ANDROID_4_0__

    WndEnd(ANDROID_KEYGUARD_WND_MAIN)

#endif

ApEnd(RS,CLSID_ANDROID_KEYGUARDAPP)



