ApBegin(RS,CLSID_VOICEMEMOAPP)
    WndBegin(VOICEMEMO_WND_RECORDER_INIT_VIEW)
        WndSetAllSoftkeyRC({SK_OPTION, SK_RECORD, SK_QUIT})
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_VOICE_MEMO})

        WdgBegin(CLSID_TEXTWIDGET,VoiceMemoRecorderStatusTextWdg)
            WdgTextCreateForWndRC({{VOICEMEMOAPP_RECORDER_STATUS_TEXTWIDGET_X_POSITION,VOICEMEMOAPP_RECORDER_STATUS_TEXTWIDGET_Y_POSITION},{VOICEMEMOAPP_RECORDER_STATUS_TEXTWIDGET_WIDTH,VOICEMEMOAPP_RECORDER_STATUS_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_FHL_N_START_RECORDING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE)
        WdgEnd(CLSID_TEXTWIDGET,VoiceMemoRecorderStatusTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,VoiceMemoRecorderTimeTextWdg)
            WdgTextCreateForWndRC({{VOICEMEMOAPP_RECORDER_TIME_TEXTWIDGET_X_POSITION,VOICEMEMOAPP_RECORDER_TIME_TEXTWIDGET_Y_POSITION},{VOICEMEMOAPP_RECORDER_TIME_TEXTWIDGET_WIDTH,VOICEMEMOAPP_RECORDER_TIME_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_SMALL)
        WdgEnd(CLSID_TEXTWIDGET,VoiceMemoRecorderTimeTextWdg)

        WdgBegin(CLSID_PROGRESSWIDGET,VoiceMemoRecorderProgressWdg)
            WdgProgressCreateForWndRC({{VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_X_POSITION,VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_Y_POSITION},{VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_WIDTH,VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_HEIGHT},{TRUE,TRUE,0,0,0,1}})
        WdgEnd(CLSID_PROGRESSWIDGET,VoiceMemoRecorderProgressWdg)
#ifdef __IFONE_STYLE_MMI_VOICEMEMO__ 	
        WdgBegin(CLSID_BUTTONWIDGET, VoiceMemoRecorderStartRecordWdg)
            WdgButtonCreateForWndRC({{VOICEMEMOAPP_RECORDER_STARTBUTTON_X,VOICEMEMOAPP_RECORDER_STARTBUTTON_Y},{VOICEMEMOAPP_RECORDER_STARTBUTTON_WIDTH,VOICEMEMOAPP_RECORDER_STARTBUTTON_HEIGHT}})
        WdgEnd(CLSID_BUTTONWIDGET,VoiceMemoRecorderStartRecordWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VoiceMemoRecorderSaveRecordWdg)
            WdgButtonCreateForWndRC({{VOICEMEMOAPP_RECORDER_SAVEBUTTON_X,VOICEMEMOAPP_RECORDER_SAVEBUTTON_Y},{VOICEMEMOAPP_RECORDER_SAVEBUTTON_WIDTH,VOICEMEMOAPP_RECORDER_SAVEBUTTON_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VOICEMEMO_IMG_FILE_BUTTON_UNPRESSED,VOICEMEMO_IMG_FILE_BUTTON_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VoiceMemoRecorderSaveRecordWdg)
        
        WdgBegin(CLSID_IMAGEWIDGET,VoiceMemoButtonContainerWdg)
            WdgImageCreateForWndRC({{VOICEMEMOAPP_RECORDER_BUTTONCONTAINER_X,VOICEMEMOAPP_RECORDER_BUTTONCONTAINER_Y},{VOICEMEMOAPP_RECORDER_BUTTONCONTAINER_WIDTH, VOICEMEMOAPP_RECORDER_BUTTONCONTAINER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VOICEMEMO_IMG_BUTTON_CONTAINER}})
            WdgImageSetDataByIDRC(VOICEMEMO_IMG_BUTTON_CONTAINER)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,VoiceMemoButtonContainerWdg)
        
        WdgBegin(CLSID_IMAGEWIDGET,VoiceMemoNeedleContainerWdg)
            WdgImageCreateForWndRC({{VOICEMEMOAPP_RECORDER_NEEDLECONTAINER_X,VOICEMEMOAPP_RECORDER_NEEDLECONTAINER_Y},{VOICEMEMOAPP_RECORDER_NEEDLECONTAINER_WIDTH, VOICEMEMOAPP_RECORDER_NEEDLECONTAINER_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VOICEMEMO_IMG_NEEDLE_CONTAINER}})
            WdgImageSetDataByIDRC(VOICEMEMO_IMG_NEEDLE_CONTAINER)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,VoiceMemoNeedleContainerWdg)

        WdgBegin(CLSID_BUTTONWIDGET, VoiceMemoSettingsButtonWdg)
            WdgButtonCreateForWndRC({{VOICEMEMOAPP_RECORDER_SETTINGS_BUTTON_X, VOICEMEMOAPP_RECORDER_SETTINGS_BUTTON_Y},{VOICEMEMOAPP_RECORDER_SETTINGS_BUTTON_WIDTH,VOICEMEMOAPP_RECORDER_SETTINGS_BUTTON_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, VOICEMEMO_IMG_SETTINGS_UNPRESSED, VOICEMEMO_IMG_SETTINGS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, VoiceMemoSettingsButtonWdg)
#endif		
    WndEnd(VOICEMEMO_WND_RECORDER_INIT_VIEW)

    WndBegin(VOICEMEMO_WND_RECORDER_INIT_OPTION_VIEW)
        WdgBegin(CLSID_VTMOPTIONMENU,VtmInitOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,4})
            VtmCreateOptionMenuDataRC(4, {
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_RECORD}, TXT_OIL1_N_RECORD},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_VIEW_FILES}, TXT_OIL1_N_VIEW_FILES},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_SETTINGS}, TXT_OIL1_N_STORAGE},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_TYPES}, TXT_LIL_N_VOICE_FORMAT},
                                          })
        WdgEnd(CLSID_VTMOPTIONMENU,VtmInitOptionMenu)

    WndEnd(VOICEMEMO_WND_RECORDER_INIT_OPTION_VIEW)

    WndBegin(VOICEMEMO_WND_RECORDER_PLAYER_VIEW)  /* need to check window id */
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_VOICE_MEMO})
        WndSetAllSoftkeyRC({SK_OPTION, SK_PLAY, SK_QUIT})

        WdgBegin(CLSID_TEXTWIDGET,VoiceMemoPlayerInfoTextWdg)
            WdgTextCreateForWndRC({{VOICEMEMOAPP_PLAYER_INFO_TEXTWIDGET_X_POSITION,VOICEMEMOAPP_PLAYER_INFO_TEXTWIDGET_Y_POSITION},{VOICEMEMOAPP_PLAYER_INFO_TEXTWIDGET_WIDTH,VOICEMEMOAPP_PLAYER_INFO_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_FHL_N_RECORDING)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,VoiceMemoPlayerInfoTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,VoiceMemoPlayerElapsedTimeTextWdg)
            WdgTextCreateForWndRC({{VOICEMEMOAPP_PLAYER_ELAPSEDTIME_TEXTWIDGET_X_POSITION,VOICEMEMOAPP_PLAYER_ELAPSEDTIME_TEXTWIDGET_Y_POSITION},{VOICEMEMOAPP_PLAYER_ELAPSEDTIME_TEXTWIDGET_WIDTH,VOICEMEMOAPP_PLAYER_ELAPSEDTIME_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(DEF_THM_VOICEMEMOAPP_TEXT)
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_SMALL)
        WdgEnd(CLSID_TEXTWIDGET,VoiceMemoPlayerElapsedTimeTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,VoiceMemoPlayerTotalTimeTextWdg)
            WdgTextCreateForWndRC({{VOICEMEMOAPP_PLAYER_TOTALTIME_TEXTWIDGET_X_POSITION,VOICEMEMOAPP_PLAYER_TOTALTIME_TEXTWIDGET_Y_POSITION},{VOICEMEMOAPP_PLAYER_TOTALTIME_TEXTWIDGET_WIDTH,VOICEMEMOAPP_PLAYER_TOTALTIME_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,VoiceMemoPlayerTotalTimeTextWdg)

        WdgBegin(CLSID_PROGRESSWIDGET,VoiceMemoPlayerProgressWdg)
            WdgProgressCreateForWndRC({{VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_X_POSITION,VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_Y_POSITION},{VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_WIDTH,VOICEMEMOAPP_RECORDER_PROGRESS_PROGRESSWIDGET_HEIGHT},{FALSE,FALSE,0,0,0,1}})
        WdgEnd(CLSID_PROGRESSWIDGET,VoiceMemoPlayerProgressWdg)

    WndEnd(VOICEMEMO_WND_RECORDER_PLAYER_VIEW)


    WndBegin(VOICEMEMO_WND_RECORDER_PLAYER_OPTION_VIEW)  /* need to check window id */

        WdgBegin(CLSID_VTMOPTIONMENU,VtmPlayerOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,4})
            VtmCreateOptionMenuDataRC(4, {
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_PLAY}, TXT_OIL1_N_PLAY},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_NEW}, TXT_OIL1_N_NEW},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_DELETE}, TXT_OIL1_N_DELETE},
                                            {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_VOICEMEMO_RECORDER_VIEW_FILES}, TXT_OIL1_N_VIEW_FILES}
                                          })
        WdgEnd(CLSID_VTMOPTIONMENU,VtmPlayerOptionMenu)

    WndEnd(VOICEMEMO_WND_RECORDER_PLAYER_OPTION_VIEW)

    WndBegin(VOICEMEMO_WND_RECORDER_SET_RECORD_TYPE_VIEW)
        WdgBegin(CLSID_VTMPOPUPSELECT,RecordTypeVtmSelect)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,4,0,0})
            VtmCreatePopUpSelectDataRC(4,{ {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},VOICEMEMO_RECORD_TYPE_AMR},TXT_LIL_N_VOICE_QUALITY_LOW_AMR},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},VOICEMEMO_RECORD_TYPE_AWB},TXT_LIL_N_VOICE_QUALITY_NORMAL_AWB},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},VOICEMEMO_RECORD_TYPE_MP3},TXT_LIL_N_VOICE_QUALITY_HIGH_MP3},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},VOICEMEMO_RECORD_TYPE_WAV},TXT_LIL_N_VOICE_QUALITY_HIGH_WAV}
                                            })
        WdgEnd(CLSID_VTMPOPUPSELECT,RecordTypeVtmSelect)
    WndEnd(VOICEMEMO_WND_RECORDER_SET_RECORD_TYPE_VIEW)

ApEnd(RS,CLSID_VOICEMEMOAPP)

