#ifndef __MMI_AUTOTESTAPP_ID_H__
#define __MMI_AUTOTESTAPP_ID_H__

#ifdef __FT_AUTO_TEST__

typedef enum
{
    AUTOTEST_WND_SPLASH = WND_ID_APP_BASE,
    AUTOTEST_WND_SELECT_BAND,
    AUTOTEST_WND_SETTING,
    AUTOTEST_WND_FINISH,
} AutotestWndId_e;


typedef enum
{
	MNU_AUTOTEST_Auto_Select=0,
	MNU_AUTOTEST_850,
	MNU_AUTOTEST_900,
	MNU_AUTOTEST_1800,
	MNU_AUTOTEST_1900,
	MNU_AUTOTEST_850_1900,
	MNU_AUTOTEST_900_1800,
	MNU_AUTOTEST_900_1900,
}SettingMenuId_e;

#endif // #ifdef __FT_AUTO_TEST__
#endif //__MMI_AUTOTESTAPP_ID_H__
