#ifndef __MMI_SMMSETTINGAPP_ID_H__
#define __MMI_SMMSETTINGAPP_ID_H__
enum
{
    MSA_WND_DUALSIMSELECT_MENU_VIEW,
    MSA_WND_MAIN_MENU_VIEW,
    MSA_WND_POPUP_RADIOLIST_VIEW,
    MSA_WND_POPUP_EDITOR_VIEW, // for every item setting selection
};
typedef enum
{
	MNU_MSG_SET_SAVE_SMS_TO = 0,
	MNU_MSG_SET_PHONE,
	MNU_MSG_SET_SIM,
	MNU_MSG_SET_SERVICE_CENTER_NO,
	MNU_MSG_SET_BEARER_MODE,
	MNU_MSG_SET_GPRS,
	MNU_MSG_SET_CSD,
	MNU_MSG_SET_VALIDITY_PERIOD,
	MNU_MSG_SET_12_HOURS,
	MNU_MSG_SET_1_DAY,
	MNU_MSG_SET_3_DAYS,
	MNU_MSG_SET_1_WEEK,
	MNU_MSG_SET_MAX,
	MNU_MSG_SET_MESSAGE_TYPE,
	MNU_MSG_SET_TEXT,
	MNU_MSG_SET_PAGING,
	MNU_MSG_SET_EMAIL,
	MNU_MSG_SET_FAX,
	MNU_MSG_SET_STATUS_REPORT,
	MNU_MSG_SET_SR_ON,
	MNU_MSG_SET_SR_OFF,
	MNU_MSG_SET_DIRECT_REPLY,
	MNU_MSG_SET_DR_ON,
	MNU_MSG_SET_DR_OFF,
	MNU_MSG_SET_INBOX_LOCATION,
	MNU_MSG_SET_IL_PHONE,
	MNU_MSG_SET_IL_SIM,
	MNU_MSG_SET_BACKUP_SENT_MSGS,
	MNU_MSG_SET_SMS_BS_ON,
	MNU_MSG_SET_SMS_BS_OFF,
}SmssettingMenuId_e;
#endif
