#ifndef __MMI_SMSSETTINGAPP_VIEW_ID_H__
#define __MMI_SMSSETTINGAPP_VIEW_ID_H__

#include "mmi_message_cfg.h"
#include "mmi_view_id_range.h"

#define MSG_SMS_SERVICE_CENTER_MAX_BYTE MSG_SMS_SERVICE_CENTER_MAX_CHAR*sizeof(MAE_WChar)  // for vdf  @@ will be remove


enum
{
/* View ID start */
	MSA_MAIN_VIEW = MMI_VIEW_ID_AP_BEGIN,
	MSA_BM_VIEW,
	MSA_VP_VIEW,
	MSA_MT_VIEW,
	MSA_SR_VIEW,
	MSA_DR_VIEW,
	MSA_IL_VIEW,
	MSA_EDITOR_VIEW,
	MSA_BS_VIEW,
	MSA_DUO_SELECTION_VIEW
/* View ID end */
};

enum
{
/* Widget ID start */
	MSA_MAIN_TITLEWIDGET = 1,
	MSA_MAIN_MENU,
	MSA_BM_TITLEWIDGET,
	MSA_BM_MENU,
	MSA_VP_TITLEWIDGET,
	MSA_VP_MENU,
	MSA_MT_TITLEWIDGET,
	MSA_MT_MENU,
	MSA_SR_TITLEWIDGET,
	MSA_SR_MENU,
	MSA_DR_TITLEWIDGET,
	MSA_DR_MENU,
	MSA_IL_TITLEWIDGET,
	MSA_IL_MENU,
	MSA_BS_TITLEWIDGET,
	MSA_BS_MENU,
    MSA_EDITOR_TITLEWIDGET,
    MSA_EDITOR_INPUTWIDGET,
    MSA_DUO_SELECTION_TITLEWIDGET,
    MSA_DUO_SELECTION_MENU,
    MSA_BEARER_MODEL,
    MSA_VP_MODEL,
    MSA_MT_MODEL,
/* Widget ID end */
};

enum e_DUO_SELECTION_MENU_ITEM
{
    /* Binary ID start */
    MNU_MSA_DUO_MASTER,
    MNU_MSA_DUO_SLAVE,
};
#endif /* __MMI_SMSSETTINGAPP_VIEW_ID_H__ */
