#ifndef __MMI_SETTINGAPP_ID_H__
#define __MMI_SETTINGAPP_ID_H__

#ifdef __APP_MMI_SMALLROM__
#define __SETTINGAPP_SMALLROM__
#endif

#include "mmi_common_setting_type.h"

typedef enum
{
    SETTINGAPP_WND_PREVIEW_MENULIST = WND_ID_APP_BASE,
    SETTINGAPP_WND_GENERAL,
    SETTINGAPP_WND_PHONE,
    SETTINGAPP_WND_CONNECT,
    SETTINGAPP_WND_PERSONALIZATION,
    SETTINGAPP_WND_DISPLAY,
    SETTINGAPP_WND_RINGTONE,
    SETTINGAPP_WND_POWERON_RINGTONE,
    SETTINGAPP_WND_POWEROFF_RINGTONE,
    SETTINGAPP_WND_VOICECALL,
    SETTINGAPP_WND_MESSAGE,
    SETTINGAPP_WND_CALENDAR,
    SETTINGAPP_WND_ALARM,
    SETTINGAPP_WND_FONTSTYLE,
    SETTINGAPP_WND_TRANSITION,
    SETTINGAPP_WND_BACKLIGHT,
    SETTINGAPP_WND_DATETIME,
    SETTINGAPP_WND_TIMEZONE,
	SETTINGAPP_WND_SECONDTIME,
    SETTINGAPP_WND_POWERONOFF,
    SETTINGAPP_WND_AUTOONOFF,
    SETTINGAPP_WND_INFORMATION,
    SETTINGAPP_WND_IDLESCREEN,
	SETTINGAPP_WND_LIVEEFFECTLIST,
	SETTINGAPP_WND_LIVEEFFECTPREVIEW,
    SETTINGAPP_WND_LANGUAGE,
    SETTINGAPP_WND_VIBRATETYPE,
    SETTINGAPP_WND_VOICECALLSRINGINGTYPE,
    SETTINGAPP_WND_MESSAGETONE,
    SETTINGAPP_WND_CALENDARTONE,
    SETTINGAPP_WND_ALARMTONE,
    SETTINGAPP_WND_BACKLIGHTDURATION,
    SETTINGAPP_WND_AUTOMATICUPDATE,
    SETTINGAPP_WND_DATEFORMAT,
    SETTINGAPP_WND_DEFAULTSIM,
    SETTINGAPP_WND_MENUANIMATEDSTYLE,
#ifdef __MULTI_THEMES_ENABLED__
	SETTINGAPP_WND_MENUCHANGETHEME,
#endif
	SETTINGAPP_WND_CAMERASELECT,
	SETTINGAPP_WND_VOLUME,
	SETTINGAPP_WND_BKLLEVEL,
	SETTINGAPP_WND_DISPLAYLANG,
	SETTINGAPP_WND_WRITINGLANG,
	SETTINGAPP_WND_DEFAULT_INPUT_METHOD,
	SETTINGAPP_WND_ENCODING,
	SETTINGAPP_WND_DATE,
	SETTINGAPP_WND_TIME,
#ifndef __APP_MMI_SMALLROM__
	SETTINGAPP_WND_LAYOUT,
#endif
    SETTINGAPP_WND_THEME,
	SETTINGAPP_WND_THEME_OPT,
    SETTINGAPP_WND_FILEMGR_MELODY,
    SETTINGAPP_WND_FILEMGR_IMAGE,
    SETTINGAPP_WND_FILEMGR_MAINMENU,
//#ifdef __G_SENSOR_MMI__
    SETTINGAPP_WND_GSENSOR,
//#endif
#ifdef __BREATHLIGHT_MMI__
    SETTINGAPP_WND_BREATHLIGHT,
#endif
    SETTINGAPP_WND_POWER_SWITCH,
#ifdef __LIVE_WALLPAPER__
    SETTINGAPP_WND_3D_WALLPAPER,
    SETTINGAPP_WND_IMGWALLPAPER_PREVIEW,
	SETTINGAPP_WND_LIVEWALLPAPER_PEREVIEW,
    SETTINGAPP_WND_LIVEWALLPAPER_OPTION,
#endif
#ifdef __APP_MMI_SCREENSAVER__
    SETTINGAPP_WND_SCREENSAVER,
#ifdef __3D_UI_SCREENSAVER_EFFECT__
	SETTINGAPP_WND_SCREENSAVERSTYLE,    
#endif
    SETTINGAPP_WND_SCREENSAVERDURATION,
#endif
#ifdef __SCREEN_EFFECTS_SUPPORT__
    SETTINGAPP_WND_SCREENEFFECT,
	SETTINGAPP_WND_SCREENEFFECTTYPE,
#ifdef __SCREEN_EFFECT_SNOW_SUPPORT__
	SETTINGAPP_WND_SCREENEFFECT_SNOW,
	SETTINGAPP_WND_SCREENEFFECT_BEZIER_NUM,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_SPEED,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_NUM,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_BIG_NUM,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_DIR,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_TIME,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_PILE_SPEED,
	SETTINGAPP_WND_SCREENEFFECT_SNOW_COLOR,
#endif // __SCREEN_EFFECT_SNOW_SUPPORT__
#endif // __SCREEN_EFFECTS_SUPPORT__
	SETTINGAPP_WND_IMEI,
	SETTINGAPP_WND_SOFTWARE_VERSION,
} SettingAppWndId_e;

enum
{
    SETTINGAPP_BACKLIGHTLEVEL_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_MAINCONTAINER,
    SETTINGAPP_BACKLIGHT_LEVEL_IMG,
    SETTINGAPP_BACKLIGHT_LEVEL_DECREASE_BUTTON_WIDGET,
    SETTINGAPP_BACKLIGHT_LEVEL_INCREASE_BUTTON_WIDGET,
#ifndef __SETTINGAPP_SMALLROM__
    SETTINGAPP_TITLE2TXT,
    SETTINGAPP_BACKGROUNDIMAGE,
#else
    SETTINGAPP_BACKLIGHT_MENU_WIDGET,
    SETTINGAPP_BACKLIGHT_TEXT_WIDGET,
#endif
};

enum
{
    SETTINGAPP_DATE_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_DATE_MFLCONTAINER,
    SETTINGAPP_DATE_TEXT_DATE_WIDGET,
};

enum
{
    SETTING_TIME_VIEW_BEGIN = APP_WDG_START,
    SETTING_TIME_MFLCONTAINER,
    SETTINGAPP_TIME_TEXT_TIME_WIDGET,
};

enum
{
    SETTINGAPP_VOLUME_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_VOLUME_WIDGET,
#ifdef __SETTINGAPP_SMALLROM__
	SETTINGAPP_VOLUME_BGIMAGE_WIDGET,
	SETTINGAPP_VOLUME_TOPIMAGE_WIDGET,
	SETTINGAPP_VOLUME_TOP2IMAGE_WIDGET,
#endif
};

#ifdef __LIVE_WALLPAPER__
enum
{
    SETTINGAPP_LIVEWALLPAPER_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_LIVEWALLPAPER_IMG_WIDGET,
    SETTINGAPP_LIVEWALLPAPER_EFFECT_WIDGET,
};
#endif

enum
{
    SETTINGAPP_INFOIMEI_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_INFOIMEI_TEXT_WIDGET,
};

enum
{
    SETTINGAPP_INFOSWVERSION_VIEW_BEGIN = APP_WDG_START,
    SETTINGAPP_INFOSWVERSION_TEXT_WIDGET,
};

#endif //__MMI_SETTINGAPP_ID_H__

