ApBegin(RS,CLSID_KINGMOVIEAPP)
    WndBegin(KMV_WND_CATEGORY_LIST)
        WdgBegin(CLSID_VTMMENU,vtmCategoryListMenuWdg)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_KING_MOVIE, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_TEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU,vtmCategoryListMenuWdg)
    WndEnd(KMV_WND_CATEGORY_LIST)

    WndBegin(KMV_WND_CATEGORY_LIST_OPTION)
        WdgBegin(CLSID_VTMMENU,vtmCategoryListOptionMenuWdg)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 3})
            VtmCreateOptionMenuDataRC(3, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_OPEN},             {TXT_OIL1_N_OPEN} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_UPDATELIST},       {TXT_OIL1_N_UPDATE_LIST} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_PASSWORD_MANAGER}, {TXT_LIL_N_PASSWORD_MANAGER} }})
        WdgEnd(CLSID_VTMMENU,vtmCategoryListOptionMenuWdg)
    WndEnd(KMV_WND_CATEGORY_LIST_OPTION)

    WndBegin(KMV_WND_MOVIE_LIST)
        WdgBegin(CLSID_VTMMENU,vtmMovieListMenuWdg)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_MOVIE_INFO, WDG_MENU_TYPE_NORMAL, WDG_MENU_ITEM_TYPE_IMAGE_TEXT_TEXT, WDG_MENU_CHECK_STYLE_NONE, 0, 0, 0})
        WdgEnd(CLSID_VTMMENU,vtmMovieListMenuWdg)
    WndEnd(KMV_WND_MOVIE_LIST)

    WndBegin(KMV_WND_MOVIE_LIST_OPTION)
        WdgBegin(CLSID_VTMMENU,vtmMovieListOptionMenuWdg)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 7})
            VtmCreateOptionMenuDataRC(7, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_CONT_PLAY},      {TXT_LIL_N_CONT_PLAYING} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_MOVIEINFO},      {TXT_LIL_N_MOVIE_INFO} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_VIEW_DETAILS},   {TXT_OIL1_N_VIEW_DETAILS} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_PLAY},           {TXT_OIL1_N_PLAY} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_DELETE},         {TXT_OIL1_N_DELETE} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_DELETE_ALL},     {TXT_OIL1_N_DELETE_ALL} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_ADDTOFAVORITES}, {TXT_PML_N_ADD_TO_MY_FAVORITES} }})
        WdgEnd(CLSID_VTMMENU,vtmMovieListOptionMenuWdg)
    WndEnd(KMV_WND_MOVIE_LIST_OPTION)

    WndBegin(KMV_WND_MOVIE_INFO)
        WndSetAllSoftkeyRC({SK_OPTION, SK_OK, SK_BACK})

        WdgBegin(CLSID_TEXTWIDGET,TitleTextWdg)
            WdgTextCreateForWndRC({{KMVAPP_MOVIE_INFO_TITLETEXT_X_POS, KMVAPP_MOVIE_INFO_TITLETEXT_Y_POS}, {KMVAPP_MOVIE_INFO_TITLETEXT_WIDTH, KMVAPP_MOVIE_INFO_TITLETEXT_HEIGHT}, TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_INFO)
            WdgTextSetTextOutlineColorRC(DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT_OUTLINE)
            WdgCommonSetTextColorRC(DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_H_START | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TitleTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MovieInfoImageWdg)
            WdgImageCreateForWndRC({{KMVAPP_MOVIE_INFO_IMAGE_X_POS, KMVAPP_MOVIE_INFO_IMAGE_Y_POS}, {KMVAPP_MOVIE_INFO_IMAGE_WIDTH, KMVAPP_MOVIE_INFO_IMAGE_HEIGHT}, IMAGE_STYLE_COMMON, {FALSE, KINGMOVIE_IMG_THUMBNAIL_DEFAULT_BG}})
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_IMAGEWIDGET,MovieInfoImageWdg)

        WdgBegin(CLSID_TEXTWIDGET,NameTextWdg)
            WdgTextCreateForWndRC({{KMVAPP_MOVIE_INFO_NAMETEXT_X_POS, KMVAPP_MOVIE_INFO_NAMETEXT_Y_POS}, {KMVAPP_MOVIE_INFO_NAMETEXT_WIDTH, KMVAPP_MOVIE_INFO_NAMETEXT_HEIGHT}, TEXT_STYLE_COMMON})
            WdgTextSetLayoutFlagRC(LAYOUT_MULTILINE | LAYOUT_BREAKONWORD)
            WdgCommonSetAlignmentRC(ALIGN_H_START | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,NameTextWdg)

        WdgBegin(CLSID_INPUTWIDGET,InfoTextWdg)
            WdgInputCreateForWndRC({{KMVAPP_MOVIE_INFO_INFOTEXT_X_POS, KMVAPP_MOVIE_INFO_INFOTEXT_Y_POS}, {KMVAPP_MOVIE_INFO_INFOTEXT_WIDTH, KMVAPP_MOVIE_INFO_INFOTEXT_HEIGHT}, {FALSE, FALSE}})
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_VIEWONLY)
            WdgInputSetMultilineRC(TRUE)
            WdgCommonEnableScrollBarRC(SCROLL_STYLE_V_RIGHT)
        WdgEnd(CLSID_INPUTWIDGET,InfoTextWdg)

        WdgBegin(CLSID_ABSCONTAINER,SwitchContainer)
            WdgAbsContainerCreateForWndRC({{KMVAPP_MOVIE_SWITCH_CONTAINER_X_POS, KMVAPP_MOVIE_SWITCH_CONTAINER_Y_POS}, {KMVAPP_MOVIE_SWITCH_CONTAINER_WIDTH, KMVAPP_MOVIE_SWITCH_CONTAINER_HEIGHT}, 0})
        WdgEnd(CLSID_ABSCONTAINER,SwitchContainer)

        WdgBegin(CLSID_TEXTWIDGET,MovieSwitchTextWdg)
            WdgTextCreateForWndRC({{KMVAPP_MOVIE_SWITCH_TEXT_X_POS, KMVAPP_MOVIE_SWITCH_TEXT_Y_POS}, {KMVAPP_MOVIE_SWITCH_TEXT_WIDTH, KMVAPP_MOVIE_SWITCH_TEXT_HEIGHT}, TEXT_STYLE_COMMON})
            WdgTextSetSlideOnOffRC(FALSE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(DEF_THM_COMMON_COLOR_LIST_TITLE_TEXT)
        WdgEnd(CLSID_TEXTWIDGET,MovieSwitchTextWdg)

#ifdef __TOUCH_SCREEN_MMI__
        WdgBegin(CLSID_BUTTONWIDGET,MovieInfoLeftArrowBtnWdg)
            WdgButtonCreateForWndRC({{KMVAPP_MOVIE_LEFT_ARROW_BTN_X_POS, KMVAPP_MOVIE_LEFT_ARROW_BTN_Y_POS}, {KMVAPP_MOVIE_ARROW_BTN_WIDTH, KMVAPP_MOVIE_ARROW_BTN_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, COMMON_IMG_VIEW_ARROW_LEFT_UNPRESSED, COMMON_IMG_VIEW_ARROW_LEFT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MovieInfoLeftArrowBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,MovieInfoRightArrowBtnWdg)
            WdgButtonCreateForWndRC({{KMVAPP_MOVIE_RIGHT_ARROW_BTN_X_POS, KMVAPP_MOVIE_RIGHT_ARROW_BTN_Y_POS}, {KMVAPP_MOVIE_ARROW_BTN_WIDTH, KMVAPP_MOVIE_ARROW_BTN_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, COMMON_IMG_VIEW_ARROW_RIGHT_UNPRESSED, COMMON_IMG_VIEW_ARROW_RIGHT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MovieInfoRightArrowBtnWdg)
#else
        WdgBegin(CLSID_BUTTONWIDGET,MovieInfoLeftArrowBtnWdg)
            WdgButtonCreateForWndRC({{KMVAPP_MOVIE_LEFT_ARROW_BTN_X_POS, KMVAPP_MOVIE_LEFT_ARROW_BTN_Y_POS}, {KMVAPP_MOVIE_ARROW_BTN_WIDTH, KMVAPP_MOVIE_ARROW_BTN_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, COMMON_IMG_VIEW_ARROW_LEFT_UNPRESSED, COMMON_IMG_VIEW_ARROW_LEFT_UNPRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MovieInfoLeftArrowBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,MovieInfoRightArrowBtnWdg)
            WdgButtonCreateForWndRC({{KMVAPP_MOVIE_RIGHT_ARROW_BTN_X_POS, KMVAPP_MOVIE_RIGHT_ARROW_BTN_Y_POS}, {KMVAPP_MOVIE_ARROW_BTN_WIDTH, KMVAPP_MOVIE_ARROW_BTN_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID, COMMON_IMG_VIEW_ARROW_RIGHT_UNPRESSED, COMMON_IMG_VIEW_ARROW_RIGHT_UNPRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MovieInfoRightArrowBtnWdg)
#endif
    WndEnd(KMV_WND_MOVIE_INFO)

    WndBegin(KMV_WND_MOVIE_INFO_OPTION)
        WdgBegin(CLSID_VTMMENU,vtmMovieInfoOptionMenuWdg)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 2})
            VtmCreateOptionMenuDataRC(2, {{{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_PLAY},   {TXT_OIL1_N_PLAY} },
                                          {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_KMV_OPTION_DELETE}, {TXT_OIL1_N_DELETE} }})
        WdgEnd(CLSID_VTMMENU,vtmMovieInfoOptionMenuWdg)
    WndEnd(KMV_WND_MOVIE_INFO_OPTION)
ApEnd(RS,CLSID_KINGMOVIEAPP)
