#ifndef __MMI_CONSETTINGAPP_ID_H__
#define __MMI_CONSETTINGAPP_ID_H__

#define DATA_ACCOUNT_E_GPRS_AUTH_TYPE_NORMAL_RS  0
#define DATA_ACCOUNT_E_GPRS_AUTH_TYPE_SECURE_RS  1
#define CONNECTION_TYPE_E_CONNECTION_ORIENTED_RS 0
#define CONNECTION_TYPE_E_HTTP_RS                1
#define DATA_ACCOUNT_E_CSD_SPEED_4_8_KPBS_RS     0
#define DATA_ACCOUNT_E_CSD_SPEED_9_6_KPBS_RS     1
#define DATA_ACCOUNT_E_CSD_SPEED_14_4_KPBS_RS    2
#define GPRS_E_ALWAYS_RS                         0
#define GPRS_E_WHEN_NEEDED_RS                    1
#define DATA_ACCOUNT_E_CSD_LINE_ANALOGUE_RS      0
#define DATA_ACCOUNT_E_CSD_LINE_ISDN_RS          1
#define CONNECT_SET_E_WIFI_ONLY                  0
#define CONNECT_SET_E_GPRS_ONLY                  1
#define CONNECT_SET_E_WIFI_PREFERRED             2
#define CONNECT_SET_E_GPRS_PREFERRED             3


typedef enum
{
    CONSETTING_WND_LIST_MENU = WND_ID_APP_BASE,
    CONSETTING_WND_LIST_DUAL_SIM_MENU,
    CONSETTING_WND_RADIO_MENU,
    CONSETTING_WND_RADIO_MENU_GPRS,
    CONSETTING_WND_RADIO_MENU_NAP_TYPE,
    CONSETTING_WND_RADIO_MENU_LINE_TYPE,
    CONSETTING_WND_RADIO_MENU_SPEED,
    CONSETTING_WND_RADIO_MENU_AUTH_TYPE,
    CONSETTING_WND_RADIO_MENU_CON_TYPE,
    CONSETTING_WND_RADIO_MENU_WAP_CONNECT_SET,
    CONSETTING_WND_RADIO_MENU_JAVA_CONNECT_SET,

#ifdef __EMAIL_MMI__
	CONSETTING_WND_RADIO_MENU_EMAIL_CONNECT_SET,
#endif // __EMAIL_MMI__

#ifdef __NCCQQ_MMI__
	CONSETTING_WND_RADIO_MENU_QQ_CONNECT_SET,
#endif // __NCCQQ_MMI__

#ifdef __STREAMING_MODULE__
    CONSETTING_WND_RADIO_MENU_STREAMING_CONNECT_SET,
#endif // __STREAMING_MODULE__

#ifdef __APP_MMI_NTP__
    CONSETTING_WND_RADIO_MENU_NTP_CONNECT_SET,
#endif // __APP_MMI_NTP__

    CONSETTING_WND_RADIO_MENU_OTHER_CONNECT_SET,    
    CONSETTING_WND_SORT_MENU,
    CONSETTING_WND_MFL,
    CONSETTING_WND_OPT,
    CONSETTING_WND_LIST_MENU_OPT,
    CONSETTING_WND_INPUT_TEXT,
    CONSETTING_WND_INPUT_DIAL_NUMBER,
    CONSETTING_WND_INPUT_PASSWORD,
    CONSETTING_WND_INPUT_NUMBER,
    CONSETTING_WND_IP_EDITOR,
} ConSettingWndId_e;

typedef enum
{
    CONSETTING_MFL_VIEW_BEGIN=APP_WDG_START,
    CONSETTING_MFL_SCROLLBAR,
    CONSETTING_MFL_CONTAINER,
    CONSETTING_MFL_ACCOUNT_NAME,
    CONSETTING_MFL_APN,
    CONSETTING_MFL_USER_NAME,
    CONSETTING_MFL_PASSWORD,
    CONSETTING_MFL_AUTH_TYPE,
    CONSETTING_MFL_DNS,

    CONSETTING_MFL_PROFILE_NAME,
    CONSETTING_MFL_CONNECT_TYPE,
    CONSETTING_MFL_PROXY,
    CONSETTING_MFL_PORT,
    CONSETTING_MFL_DATA_ACCOUNT,

    CONSETTING_MFL_HOME_PAGE,
    CONSETTING_MFL_MMSC,
#ifdef SUPPORT_CSD
    CONSETTING_MFL_NAP,
    CONSETTING_MFL_MMSC,
    CONSETTING_MFL_DIAL_NUMBER,
    CONSETTING_MFL_LINE_TYPE,
    CONSETTING_MFL_SPEED_TYPE,
#endif
    CONSETTING_MFL_VIEW_END
}ConSettingMFLView_e;

typedef enum
{
	MNU_CONSETTING_OPT_MENU = 0,
	MNU_CONSETTING_LIST_EDIT,
	MNU_CONSETTING_LIST_SELECT,
	MNU_CONSETTING_LIST_RESET,
	MNU_CONSETTING_LIST_RESET_ALL,
	MNU_CONSETTING_RADIO_EDIT,
	MNU_CONSETTING_RADIO_SELECT,
	MNU_CONSETTING_RADIO_RESET,
	MNU_CONSETTING_RADIO_RESET_ALL,
	MNU_CONSETTING_MFL_EDIT,
	MNU_CONSETTING_MFL_SELECT,
	MNU_CONSETTING_MFL_RESET,
	MNU_CONSETTING_MFL_RESET_ALL,
	MNU_CONSETTING_MFL_SAVE,
	MNU_CONSETTING_TEXT_EDITOR_SAVE,
	MNU_CONSETTING_TEXT_EDITOR_INPUT_MENU,
}ConsettingMenuId_e;

#endif //__MMI_CONSETTINGAPP_ID_H__

