ApBegin(RS,CLSID_VOICEMAILAPP)
    WndBegin(VOICEMAIL_WND_SELECTSIM)    
       WdgBegin(CLSID_VTMSIMSELECTION,DualSim)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_NULL_ID})
        WdgEnd(CLSID_VTMSIMSELECTION,DualSim)    
    WndEnd(VOICEMAIL_WND_SELECTSIM)

    WndBegin(VOICEMAIL_WND_SETNUMBER)
	WdgBegin(CLSID_VTMPOPUPINPUT,VoiceNumber)
		VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_NULL_ID,MAE_INPUTMODE_DIALING})
	WdgEnd(CLSID_VTMPOPUPINPUT,VoiceNumber)        
    WndEnd(VOICEMAIL_WND_SETNUMBER)

ApEnd(RS,CLSID_VOICEMAILAPP)

