/**
 * \file opic_api_fms.h
 * \brief Flash Management System (FMS) Opic/Opec public API Software Interrupts IDs
 */

#ifndef __OPIC_API_FMS_H__
#define __OPIC_API_FMS_H__

#include "opic_api.hi"

/* --- AUDIO API --- */

enum
{
	API_FMS_RAI_READ	= API_FMS_BASE,
	API_FMS_RAI_WRITE,
	API_FMS_RAI_DELETE,
	API_FMS_RAI_INFO,
	API_FMS_RAI_FIND_INIT,
	API_FMS_RAI_FIND_NEXT,
	API_FMS_RAI_FIND_CLOSE,
	API_FMS_RAI_STATS,
	API_FMS_RAI_GC_INIT,
	API_FMS_RAI_GC,
	API_FMS_AD_ALLOCATE,
	API_FMS_AD_WRITE,
	API_FMS_AD_RESUME,
	API_FMS_AD_FINALISE,
	API_FMS_AD_RETRIEVE,
	API_FMS_AD_FINDINIT,
	API_FMS_AD_FINDNEXT,
	API_FMS_AD_INFO,
	API_FMS_AD_STATS,
	API_FMS_AD_DELETE,
	API_FMS_AD_FORMAT,
	API_FMS_AD_RECOMPACTINIT,
	API_FMS_AD_RECOMPACT,
	API_FMS_AD_VOLUMESTATE,
	API_FMS_AD_VOLUMEIOCONTROL,
	API_FMS_AD_FORMAT2,
	API_FMS_BIN_GETORIGIN,
	API_FMS_BIN_GETSIZE,
	API_FMS_BIN_GETCHECKSUM,
	API_FMS_BIN_DESTROY
};

#endif /* __OPIC_API_FMS_H__ */

