ApBegin(RS,CLSID_USSDAPP)

    WndBegin(USSD_WND_DUAL_SIM)
        WdgBegin(CLSID_VTMSIMSELECTION,DualSim)
            VtmCreateSimSelectionRC({0,TXT_LIL_N_USSD})
        WdgEnd(CLSID_VTMSIMSELECTION,DualSim)
    WndEnd(USSD_WND_DUAL_SIM)

    WndBegin(USSD_WND_REPLY)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WdgBegin(CLSID_VTMINPUT,EditInput)
            VtmCreateInputRC({IMG_NULL_ID,TXT_LIL_N_USSD,USSDAPP_MAX_INPUT_BYTE,FALSE})
            WdgInputSetChineseInputOffRC(TRUE)
            WdgInputSetCurrentInputModeRC((u32)MAE_INPUTMODE_MT_ABC)
            WdgInputSetSoftKeyBoardEnableRC(TRUE)
            WdgInputSetMaxByteLengthRC(USSDAPP_MAX_INPUT_BYTE)
        WdgEnd(CLSID_VTMINPUT,EditInput)
    WndEnd(USSD_WND_REPLY)

    WndBegin(USSD_WND_DISPLAY_USSD)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_USSD})
        WndSetAllSoftkeyRC({SK_REPLY, SK_NONE, SK_CLOSE})

        WdgBegin(CLSID_INPUTWIDGET,pUssdDisplayInputWdg)
            WdgInputCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,USSDAPP_DISPLAY_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgCommonEnableScrollBarRC(SCROLL_V_RIGHT)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_VIEWONLY)
            WdgInputSetMultilineRC((boolean)TRUE)
        WdgEnd(CLSID_INPUTWIDGET,pUssdDisplayInputWdg)
    WndEnd(USSD_WND_DISPLAY_USSD)

    WndBegin(USSD_WND_NEW_RESULT)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_USSD})
        WndSetAllSoftkeyRC({SK_REPLY, SK_NONE, SK_CLOSE})

        WdgBegin(CLSID_INPUTWIDGET,pUssdNewResultInputWdg)
            WdgInputCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,USSDAPP_DISPLAY_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgCommonEnableScrollBarRC(SCROLL_V_RIGHT)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_VIEWONLY)
            WdgInputSetMultilineRC((boolean)TRUE)
        WdgEnd(CLSID_INPUTWIDGET,pUssdNewResultInputWdg)
    WndEnd(USSD_WND_NEW_RESULT)
ApEnd(RS,CLSID_USSDAPP)

