#ifndef __MMI_HAMSTERFIGHTAPP_ID_H__
#define __MMI_HAMSTERFIGHTAPP_ID_H__

typedef enum
{
    HF_WND_MENU = WND_ID_APP_BASE,
    HF_WND_GAME,
    HF_WND_OPTIONS,
    HF_WND_HELP,
    HF_WND_COMMON
} HFWndId_e;

typedef enum
{
    MENU_BG_IMAGE_WDG = APP_WDG_START,
    MENU_NEW_GAME_WDG,
    MENU_CONTINUE_GAME_WDG,
    MENU_OPTIONS_GAME_WDG,
    MENU_HELP_WDG,
    MENU_EXIT_WDG,
    MENU_ARROW_TO_LEFT_WDG,
    MENU_ARROW_TO_RIGHT_WDG
} HFMenuWdgList_e;

enum
{
    GAME_BG_IMAGE_WDG = APP_WDG_START,
    GAME_RETURN_WDG,
    ANIMAL_MOTION_IMAGE_WDG,
    GRASS_SHELTER_IMAGE_WDG,
    COUNT_DOWN_MOTION_IMAGE_WDG,
    LEVEL_NUMBER_IMAGE_WDG,
    HAMMER_MOTION_IMAGE_WDG,
    HIT_SIGN_IMAGE_WDG,
    Combo_NUMBER_IMAGE_WDG,
    GAME_Multi_SIGN_IMAGE_WDG,
    SPARK_IMAGE_WDG,
    HEALTH_POINT_IMAGE_WDG,
    SMALL_HAMSTER_SIGN_IMAGE_WDG,
    HAMSTER_NUMBER_IMAGE_WDG,
    WIN_GAME_IMAGE_WDG,
    LOSE_GAME_IMAGE_WDG
} HFGameWdgList_e;

enum
{
    OPTIONS_BG_IMAGE_WDG = APP_WDG_START,
    OPTIONS_FADE_OUT_WDG,
    OPTIONS_TXT_SOUND_WDG,
    OPTIONS_IMG_FRAME_WDG,
    OPTIONS_SOUND_SWITCH_WDG,
    OPTIONS_TXT_START_CAMERA_WDG,
    OPTIONS_CAMERA_WDG,
    OPTIONS_TXT_CHANGE_PIC_WDG,
    OPTIONS_CHANE_PIC_WDG,
 //   OPTIONS_TXT_NOTICE_WDG,
    OPTIONS_RETURN_WDG,
    OPTIONS_TXT_DEFAULT_PIC_WDG,
    OPTIONS_IMG_DEFAULT_PIC_WDG,
    OPTIONS_BTN_BACK_DEFAULT_WDG
} HFOptionsWdgList_e;

enum
{
    HELP_BG_IMAGE_WDG = APP_WDG_START,
    HELP_FADE_OUT_WDG,
    HELP_CONTENT_WDG,
    HELP_NOTICE_WDG,
    HELP_RULE_WDG,
    HELP_IMG_HIT_WDG,
    HELP_IMG_Multi_SIGN_WDG,
    HELP_IMG_GET_HP_WDG,
    HELP_RETURN_WDG
} HFHelpWdgList_e;

#endif
