ApBegin(RS,CLSID_CCMTA)
#ifdef __UI_STYLE_MMI_IFONE__
    WndBegin(CCMTA_WND_INCOMINGCALL)
        WdgBegin(CLSID_ABSCONTAINER,CallInfoCntr)
		WdgAbsContainerCreateForWndRC({{0,0},{CCMTA_IFONE_TOP_IMG_WIDTH,CCMTA_IFONE_TOP_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,CallInfoCntr)

        WdgBegin(CLSID_IMAGEWIDGET,InCallImgWdg)
            WdgImageCreateForWndRC({{CCMTA_IFONE_CALLER_IMAGE_POS_X,CCMTA_IFONE_CALLER_IMAGE_POS_Y},{CCMTA_IFONE_CALLER_IMAGE_WIDTH,CCMTA_IFONE_CALLER_IMAGE_HEIGTH},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,InCallImgWdg)

#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
        WdgBegin(CLSID_OSDWIDGET,IncomingCallVideoOsdWdg)
            WdgOsdCreateForWndRC({{CCMTA_IFONE_CALLER_IMAGE_POS_X, CCMTA_IFONE_CALLER_IMAGE_POS_Y}, {CCMTA_IFONE_CALLER_IMAGE_WIDTH, CCMTA_IFONE_CALLER_IMAGE_HEIGTH}}) 	 
        WdgEnd(CLSID_OSDWIDGET,IncomingCallVideoOsdWdg)
        WdgBegin(CLSID_IMAGEWIDGET,IncomingCallVideoFirstFrameImgWdg)
            WdgImageCreateForWndRC({{CCMTA_IFONE_CALLER_IMAGE_POS_X,CCMTA_IFONE_CALLER_IMAGE_POS_Y},{CCMTA_IFONE_CALLER_IMAGE_WIDTH,CCMTA_IFONE_CALLER_IMAGE_HEIGTH},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,IncomingCallVideoFirstFrameImgWdg)
#endif

        WdgBegin(CLSID_TEXTWIDGET,InCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCMTA_IFONE_CALLINFO_POS_X,CCMTA_IFONE_CALLINFO_POS_Y},{CCMTA_IFONE_CALLINFO_WIDTH,CCMTA_IFONE_CALLINFO_HEIGTH},TEXT_STYLE_COMMON})
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetTextColorRC(COLOR_WHITE)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,InCallInfoTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DuoStateImgWdg1)
            WdgImageCreateForWndRC({{CCAPP_IFONE_MO_DUAL_IMG_POS_X,CCAPP_IFONE_MO_DUAL_IMG_POS_Y},{CCAPP_IFONE_MO_DUAL_IMG_WIDTH,CCAPP_IFONE_MO_DUAL_IMG_WIDTH},IMAGE_STYLE_COMMON})
        WdgEnd(CLSID_IMAGEWIDGET,DuoStateImgWdg1)

        WdgBegin(CLSID_TEXTWIDGET,CallStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_IFONE_STATUS_POS_X,CCMTA_IFONE_STATUS_HEIGTH},{CCMTA_IFONE_STATUS_WIDTH,CCMTA_IFONE_STATUS_HEIGTH},TEXT_STYLE_COMMON})
/*            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)*/
            WdgTextSetDataByIDRC(TXT_CCL_N_INCOMING_CALLING)
/*            WdgCommonSetFontCategoryRC((FontCategory_t)*/
/*            WdgCommonSetTextColorRC((RGBColor_t)*/
/*            WdgCommonSetFontTypeRC((FontType_t)*/
/*            WdgTextSetTextOutlineColorRC((RGBColor_t)*/
        WdgEnd(CLSID_TEXTWIDGET,CallStateTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,DuoStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_IFONE_STATUS_POS_X,CCMTA_IFONE_STATUS_POS_Y},{CCMTA_IFONE_STATUS_WIDTH,CCMTA_IFONE_STATUS_HEIGTH},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_GREY_4)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,DuoStateTextWdg)

        WdgBegin(CLSID_ABSCONTAINER,BtnCntr)
            WdgAbsContainerCreateForWndRC({{CCMTA_IFONE_WAITING_CENTER_BTN_BG_POS_X,CCMTA_IFONE_WAITING_CENTER_BTN_BG_POS_Y},{CCMTA_IFONE_WAITING_CENTER_BTN_BG_WIDTH,CCMTA_IFONE_WAITING_CENTER_BTN_BG_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,BtnCntr)

        WdgBegin(CLSID_BUTTONWIDGET,RejectBtnWdg)
            WdgButtonCreateForWndRC({{CCMTA_IFONE_WAITING_IGNORE_BTN_POS_X,CCMTA_IFONE_WAITING_IGNORE_BTN_POS_Y},{CCMTA_IFONE_WAITING_CENTER_BTN_WIDTH,CCMTA_IFONE_WAITING_CENTER_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({0,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,RejectBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,HoldBtnWdg)
            WdgButtonCreateForWndRC({{CCMTA_IFONE_WAITING_END_HOLD_ANSWER_BTN_POS_X,CCMTA_IFONE_WAITING_END_HOLD_ANSWER_BTN_POS_Y},{CCMTA_IFONE_WAITING_CENTER_BTN_WIDTH,CCMTA_IFONE_WAITING_CENTER_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({0,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,HoldBtnWdg)

        WdgBegin(CLSID_ABSCONTAINER,OpCntr)
		WdgAbsContainerCreateForWndRC({{CCMTA_IFONE_BOTTOM_IMG_POS_X,CCMTA_IFONE_BOTTOM_IMG_POS_Y},{CCMTA_IFONE_BOTTOM_IMG_WIDTH,CCMTA_IFONE_BOTTOM_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,OpCntr)

	WdgBegin(CLSID_BUTTONWIDGET,AnswerCallBtnWdg)
            WdgButtonCreateForWndRC({{CCMTA_IFONE_ANSWER_BTN_POS_X,CCMTA_IFONE_ANSWER_BTN_POS_Y},{CCMTA_IFONE_ANSWER_BTN_WIDTH,CCMTA_IFONE_ANSWER_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({0,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,AnswerCallBtnWdg)

	WdgBegin(CLSID_BUTTONWIDGET,EndCallBtnWdg)
            WdgButtonCreateForWndRC({{CCMTA_IFONE_REJECT_BTN_POS_X,CCMTA_IFONE_REJECT_BTN_POS_Y},{CCMTA_IFONE_REJECT_BTN_WIDTH,CCMTA_IFONE_REJECT_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({0,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,EndCallBtnWdg)

    WndEnd(CCMTA_WND_INCOMINGCALL)
#else
    WndBegin(CCMTA_WND_INCOMINGCALL)
        WndSetAllSoftkeyRC( {SK_ANSWER, SK_NONE, SK_NONE} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
#ifdef __APP_MMI_SMALLROM__
		WndSetTitleVisiableRC(VIEWSB_INVISIABLE)
		WndSetBgColorRC(COLOR_BLUE_9) 
#else
        WdgBegin(CLSID_IMAGEWIDGET,CallScreenBGWdg)
            WdgImageCreateForWndRC({{0,0},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,CallScreenBGWdg)
#endif
#ifdef __MMI_PHB_VIDEOTONE_SUPPORT__
        WdgBegin(CLSID_OSDWIDGET,IncomingCallVideoOsdWdg)
            WdgOsdCreateForWndRC({{CCMTA_INCOMING_USER_VIDEO_POS_X, CCMTA_INCOMING_USER_VIDEO_POS_Y}, {CCMTA_INCOMING_USER_VIDEO_WIDTH, CCMTA_INCOMING_USER_VIDEO_HEIGHT}})		 
        WdgEnd(CLSID_OSDWIDGET,IncomingCallVideoOsdWdg)
        WdgBegin(CLSID_IMAGEWIDGET,IncomingCallVideoFirstFrameImgWdg)
            WdgImageCreateForWndRC({{CCMTA_INCOMING_USER_VIDEO_POS_X,CCMTA_INCOMING_USER_VIDEO_POS_Y},{CCMTA_INCOMING_USER_VIDEO_WIDTH,CCMTA_INCOMING_USER_VIDEO_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,IncomingCallVideoFirstFrameImgWdg)
#endif
        WdgBegin(CLSID_IMAGEWIDGET,IncomingCallImgWdg)
		WdgImageCreateForWndRC({{CCMTA_INCOMING_IMAGE_POS_X,CCMTA_INCOMING_IMAGE_POS_Y},{CCMTA_INCOMING_IMAGE_WIDTH,CCMTA_INCOMING_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_CONTACT_THUMBNAIL}})
		WdgImageSetDataByIDRC(PHONEBOOK_IMG_CONTACT_THUMBNAIL)
/*            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)*/
        WdgEnd(CLSID_IMAGEWIDGET,IncomingCallImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,IncomingCallTextAreaBgImgWdg)
#ifdef __APP_MMI_SMALLROM__
            WdgImageCreateForWndRC({{CCMTA_RS_TEXT_AREA_BG_L_POS_X,CCMTA_RS_TEXT_AREA_BG_L_POS_Y},{CCMTA_RS_TEXT_AREA_BG_L_POS_WIDTH,CCMTA_RS_TEXT_AREA_BG_L_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgCommonSetBGColorRC(COLOR_BLUE_10)
#else
            WdgImageCreateForWndRC({{CCMTA_RS_TEXT_AREA_BG_L_POS_X,CCMTA_RS_TEXT_AREA_BG_L_POS_Y},{CCMTA_RS_TEXT_AREA_BG_L_POS_WIDTH,CCMTA_RS_TEXT_AREA_BG_L_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_TEXTAREA_BG_L}})
            WdgImageSetDataByIDRC(CALL_IMG_TEXTAREA_BG_L)
#endif
        WdgEnd(CLSID_IMAGEWIDGET,IncomingCallTextAreaBgImgWdg)
        WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLINFO_POS_X,CCMTA_INCOMING_CALLINFO_POS_Y},{CCMTA_INCOMING_CALL_TEXTWDG_WIDTH,CCMTA_INCOMING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
			WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,CallStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLSTATE_POS_X,CCMTA_INCOMING_CALLSTATE_POS_Y},{CCMTA_INCOMING_CALL_TEXTWDG_WIDTH,CCMTA_INCOMING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetTextColorRC(COLOR_WHITE)
			WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallStateTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,DuoStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLDUO_POS_X,CCMTA_INCOMING_CALLDUO_POS_Y},{CCMTA_INCOMING_CALL_TEXTWDG_WIDTH,CCMTA_INCOMING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
			WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetTextColorRC(COLOR_WHITE)
			WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,DuoStateTextWdg)

#ifdef __CALLER_LOCATION__
        WdgBegin(CLSID_TEXTWIDGET,CallLocationTextWdg)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLLC_POS_X,CCMTA_INCOMING_CALLLC_POS_Y},{CCMTA_INCOMING_CALL_TEXTWDG_WIDTH,CCMTA_INCOMING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallLocationTextWdg)
#endif


/*MainContainer({{0,0},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_DEFAULT_VIEW_HEIGHT},LAYOUT_STYLE_VERTICAL})*/
/*ImgAreaContainer({{0,0},{0,0}})*/
/*TextAreaContainer({{0,0},{0,0}})*/
    WndEnd(CCMTA_WND_INCOMINGCALL)
/*<----- Sub LCD -----*/
#ifdef __DUAL_LCD__
    WndBegin(CCMTA_SUB_WND_INCOMINGCALL)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_NONE} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WdgBegin(CLSID_IMAGEWIDGET,SubCallScreenBGWdg)
            WdgImageCreateForWndRC({{0,0},{CCMTA_SUB_DEFAULT_VIEW_WIDTH,CCMTA_SUB_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,SUB_CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(SUB_CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,SubCallScreenBGWdg)
        WdgBegin(CLSID_IMAGEWIDGET,SubIncomingCallImgWdg)
            WdgImageCreateForWndRC({{0,0},{CCMTA_SUB_DEFAULT_VIEW_WIDTH,CCMTA_SUB_INCOMING_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,SUB_CALL_IMG_INCOMINGCALL_ANIM}})
            WdgImageSetDataByIDRC(SUB_CALL_IMG_INCOMINGCALL_ANIM)
        WdgEnd(CLSID_IMAGEWIDGET,SubIncomingCallImgWdg)
        WdgBegin(CLSID_TEXTWIDGET,SubCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCMTA_SUB_INCOMING_CALLINFO_POS_X,CCMTA_SUB_INCOMING_CALLINFO_POS_Y},{CCMTA_SUB_DEFAULT_VIEW_WIDTH,CCMTA_SUB_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,SubCallInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,SubCallStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_SUB_INCOMING_CALLSTATE_POS_X,CCMTA_SUB_INCOMING_CALLSTATE_POS_Y},{CCMTA_SUB_DEFAULT_VIEW_WIDTH,CCMTA_SUB_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_CCL_N_INCOMING_CALLING)
        WdgEnd(CLSID_TEXTWIDGET,SubCallStateTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,SubDuoStateTextWdg)
            WdgTextCreateForWndRC({{CCMTA_SUB_INCOMING_CALLDUO_POS_X,CCMTA_SUB_INCOMING_CALLDUO_POS_Y},{CCMTA_SUB_DEFAULT_VIEW_WIDTH,CCMTA_SUB_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,SubDuoStateTextWdg)
    WndEnd(CCMTA_SUB_WND_INCOMINGCALL)
	WndBegin(CCMTA_SUB_WND_CUS)
    	RSCustomize(WProp_t,SubIncomingCallImgAreCntnrPos,{TRUE,7})
		RSCustomize(WProp_t,SubIncomingCallTextAreaCntnrPos,{TRUE,9})
    WndEnd(CCMTA_SUB_WND_CUS)
#endif // __DUAL_LCD__    
/*------ Sub LCD ----->*/
#endif
    WndBegin(CCMTA_WND_WAITINGCALL)
        WndSetAllSoftkeyRC( {SK_ANSWER, SK_NONE, SK_NONE} )

        WdgBegin(CLSID_IMAGEWIDGET,WaitingBgImg)
            WdgImageCreateForWndRC({{0,0},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_PET_DIALOG_LAYOUT_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PET_IMG_EVENT_DIALOG_BG}})
            WdgImageSetDataByIDRC(PET_IMG_EVENT_DIALOG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,WaitingBgImg)
        WdgBegin(CLSID_IMAGEWIDGET,WaitingIncoming)
            WdgImageCreateForWndRC({{CCMTA_INCOMING_PET_PHOTO_IMAGE_POS_X,CCMTA_INCOMING_PET_PHOTO_IMAGE_POS_Y},{CCMTA_INCOMING_PET_PHOTO_IMAGE_WIDTH,CCMTA_INCOMING_PET_PHOTO_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,PET_IMG_INCOMING_CALL_PHOTO}})
            WdgImageSetDataByIDRC(PET_IMG_INCOMING_CALL_PHOTO)
/*            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)*/
        WdgEnd(CLSID_IMAGEWIDGET,WaitingIncoming)
        WdgBegin(CLSID_IMAGEWIDGET,DuoStateImgWdg)
            WdgImageCreateForWndRC({{CCMTA_INCOMING_PET_DUOSTATE_IMAGE_POS_X,CCMTA_INCOMING_PET_DUOSTATE_IMAGE_POS_Y},{CCMTA_INCOMING_PET_DUOSTATE_IMAGE_WIDTH,CCMTA_INCOMING_PET_DUOSTATE_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,DuoStateImgWdg)
        WdgBegin(CLSID_TEXTWIDGET,WaitingCallInfo)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_PET_CALLINFO_POS_X,CCMTA_INCOMING_PET_CALLINFO_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
/*            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)*/
/*            WdgCommonSetFontCategoryRC((FontCategory_t)*/
/*            WdgCommonSetTextColorRC((RGBColor_t)*/
/*            WdgCommonSetFontTypeRC((FontType_t)*/
/*            WdgTextSetTextOutlineColorRC((RGBColor_t)*/
        WdgEnd(CLSID_TEXTWIDGET,WaitingCallInfo)
#ifdef  __CALLER_LOCATION__
        WdgBegin(CLSID_TEXTWIDGET,PetCallLocationTextWdg)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_PET_CALLLC_POS_X,CCMTA_INCOMING_PET_CALLLC_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_GREY_5)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(COLOR_BLACK)
        WdgEnd(CLSID_TEXTWIDGET,PetCallLocationTextWdg)
#endif
        WdgBegin(CLSID_TEXTWIDGET,WaitingCallState)
            WdgTextCreateForWndRC({{CCMTA_INCOMING_PET_CALLSTATE_POS_X,CCMTA_INCOMING_PET_CALLSTATE_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
/*            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)*/
            WdgTextSetDataByIDRC(TXT_CCL_N_INCOMING_CALLING)
/*            WdgCommonSetFontCategoryRC((FontCategory_t)*/
/*            WdgCommonSetTextColorRC((RGBColor_t)*/
/*            WdgCommonSetFontTypeRC((FontType_t)*/
/*            WdgTextSetTextOutlineColorRC((RGBColor_t)*/
        WdgEnd(CLSID_TEXTWIDGET,WaitingCallState)
/*Container({{0,0},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_DEFAULT_VIEW_HEIGHT}})*/
/*NoSbContainer({{0,MAIN_STBAR_HEIGHT},{CCMTA_DEFAULT_VIEW_WIDTH,MAIN_DEFVIEW_HEIGHT_WITH_SB}})*/
/*BgContainer({{CCMTA_PET_DIALOG_LAYOUT_BG_POS_X,CCMTA_PET_DIALOG_LAYOUT_BG_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_PET_DIALOG_LAYOUT_BG_HEIGHT}})*/
/*IncomingAliveWdgDog({{0,0},{0,0},0})*/
    WndEnd(CCMTA_WND_WAITINGCALL)

    WndBegin(CCMTA_WND_CUS)
    	RSCustomize(WProp_t,IncomingCallImgAreCntnrPos,{TRUE,CCMTA_RS_IMCOMING_CALL_IMG_PROP})
	RSCustomize(WProp_t,IncomingCallTextAreaCntnrPos,{TRUE,CCMTA_RS_IMCOMING_CALL_TEXT_PROP})
    WndEnd(CCMTA_WND_CUS)
/*
    WndBegin(CCMTA_WND_WAITINGCALL_OPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,OptMenuWdg)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_REPLACE_ACTIVE},TXT_OIL1_N_REPLACE_ACTIVE_CALL},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_REPLACE_HOLD},TXT_OIL1_N_REPLACE_HOLD_CALL}})
        WdgEnd(CLSID_VTMOPTIONMENU,OptMenuWdg)
    WndEnd(CCMTA_WND_WAITINGCALL_OPTIONMENU)
*/

	WndBegin(CCMTA_WND_INCOMINGCALLOPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,IncomingCallOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,7})
            VtmCreateOptionMenuDataRC(7,
            	{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_REPLACE_ACTIVE},TXT_OIL1_N_REPLACE_ACTIVE_CALL},
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_REPLACE_HOLD},TXT_OIL1_N_REPLACE_HOLD_CALL},
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_ANSWER},TXT_LSK_N_ANSWER},
	            {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_QUIET},TXT_RSK_N_QUIET},
				{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_BUSY},TXT_RSK_N_BUSY},
    	        {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_DISTORTED_VOICE},TXT_LIL_N_DISTORTED_VOICE},
    	        {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CCMTA_OPT_CALL_BACKGROUND_SOUND},TXT_LIL_N_CALL_BACKGROUND_SOUND}})
        WdgEnd(CLSID_VTMOPTIONMENU,IncomingCallOptionMenu)
    WndEnd(CCMTA_WND_INCOMINGCALLOPTIONMENU)

#ifdef __VT_3G324M__
	WndBegin(VTCCMTA_WND_INCOMINGCALL)
		WndSetAllSoftkeyRC( {SK_OPTION, SK_INPUT_NUMBER, SK_QUIET} )
		WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

		WdgBegin(CLSID_IMAGEWIDGET,VtCallScreenBGWdg)
			WdgImageCreateForWndRC({{0,0},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
			WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
		WdgEnd(CLSID_IMAGEWIDGET,VtCallScreenBGWdg)

		WdgBegin(CLSID_IMAGEWIDGET,VtIncomingCallImgWdg)
			WdgImageCreateForWndRC({{0,0},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_INCOMING_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_CONTACT_THUMBNAIL}})
			WdgImageSetDataByIDRC(PHONEBOOK_IMG_CONTACT_THUMBNAIL)
		WdgEnd(CLSID_IMAGEWIDGET,VtIncomingCallImgWdg)

		WdgBegin(CLSID_TEXTWIDGET,VtCallInfoTextWdg)
			WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLINFO_POS_X,CCMTA_INCOMING_CALLINFO_POS_Y},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,VtCallInfoTextWdg)

		WdgBegin(CLSID_TEXTWIDGET,VtCallStateTextWdg)
			WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLSTATE_POS_X,CCMTA_INCOMING_CALLSTATE_POS_Y},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
			WdgTextSetDataByIDRC(TXT_CCL_N_VIDEO_INCOMING_CALLING)
		WdgEnd(CLSID_TEXTWIDGET,VtCallStateTextWdg)

		WdgBegin(CLSID_TEXTWIDGET,VtDuoStateTextWdg)
			WdgTextCreateForWndRC({{CCMTA_INCOMING_CALLDUO_POS_X,CCMTA_INCOMING_CALLDUO_POS_Y},{CCMTA_DEFAULT_VIEW_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,VtDuoStateTextWdg)
	WndEnd(VTCCMTA_WND_INCOMINGCALL)

	WndBegin(VTCCMTA_WND_WAITINGCALL)
		WndSetAllSoftkeyRC( {SK_ANSWER, SK_NONE, SK_NONE} )

		WdgBegin(CLSID_IMAGEWIDGET,VtWaitingBgImg)
			WdgImageCreateForWndRC({{0,0},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_PET_DIALOG_LAYOUT_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PET_IMG_EVENT_DIALOG_BG}})
			WdgImageSetDataByIDRC(PET_IMG_EVENT_DIALOG_BG)
		WdgEnd(CLSID_IMAGEWIDGET,VtWaitingBgImg)

		WdgBegin(CLSID_IMAGEWIDGET,VtWaitingIncoming)
			WdgImageCreateForWndRC({{CCMTA_INCOMING_PET_PHOTO_IMAGE_POS_X,CCMTA_INCOMING_PET_PHOTO_IMAGE_POS_Y},{CCMTA_INCOMING_PET_PHOTO_IMAGE_WIDTH,CCMTA_INCOMING_PET_PHOTO_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,PET_IMG_INCOMING_CALL_PHOTO}})
			WdgImageSetDataByIDRC(PET_IMG_INCOMING_CALL_PHOTO)
		WdgEnd(CLSID_IMAGEWIDGET,VtWaitingIncoming)

		WdgBegin(CLSID_IMAGEWIDGET,VtDuoStateImgWdg)
			WdgImageCreateForWndRC({{CCMTA_INCOMING_PET_DUOSTATE_IMAGE_POS_X,CCMTA_INCOMING_PET_DUOSTATE_IMAGE_POS_Y},{CCMTA_INCOMING_PET_DUOSTATE_IMAGE_WIDTH,CCMTA_INCOMING_PET_DUOSTATE_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
		WdgEnd(CLSID_IMAGEWIDGET,VtDuoStateImgWdg)

		WdgBegin(CLSID_TEXTWIDGET,VtWaitingCallInfo)
			WdgTextCreateForWndRC({{CCMTA_INCOMING_PET_CALLINFO_POS_X,CCMTA_INCOMING_PET_CALLINFO_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
		WdgEnd(CLSID_TEXTWIDGET,VtWaitingCallInfo)

		WdgBegin(CLSID_TEXTWIDGET,VtWaitingCallState)
			WdgTextCreateForWndRC({{CCMTA_INCOMING_PET_CALLSTATE_POS_X,CCMTA_INCOMING_PET_CALLSTATE_POS_Y},{CCMTA_PET_DIALOG_LAYOUT_BG_WIDTH,CCMTA_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
			WdgTextSetDataByIDRC(TXT_CCL_N_VIDEO_INCOMING_CALLING)
		WdgEnd(CLSID_TEXTWIDGET,VtWaitingCallState)
	WndEnd(VTCCMTA_WND_WAITINGCALL)

	WndBegin(VTCCMTA_WND_CUS)
		RSCustomize(WProp_t,IncomingCallImgAreCntnrPos,{TRUE,1})
		RSCustomize(WProp_t,IncomingCallTextAreaCntnrPos,{TRUE,1})
	WndEnd(VTCCMTA_WND_CUS)
#endif //__VT_3G324M__

ApEnd(RS,CLSID_CCMTA)

