#ifndef __MMI_OFFAPPVIEW_ID_H__
#define __MMI_OFFAPPVIEW_ID_H__

#include "mmi_wdg_image.h"
#include "mae_textlabel.h"
#include "mmi_mae_menumodel.h"
#include "mmi_view_id_range.h"

enum
{
/* View ID start */
	VID_OFFAPP_START = MMI_VIEW_ID_AP_BEGIN,	
	VID_OFFAPP_POWEROFFANIM,
	VID_OFFAPP_POWEROFF_OPTION_MENU,
	VID_OFFAPP_NETWORK,
	VID_OFFAPP_IFONE_MAINVIEW,
	VID_OFFAPP_SWITCHDUALMODE,
	VID_OFFAPP_END = 0x1FFF
/* View ID end */
};

enum
{
/* Widget ID start */
	WID_OFFAPP_START = 0x2000,	
	WID_OFFAPP_MAINCONTAINER,
	WID_OFFAPP_IMAGEAREA_CONTAINER,
	WID_OFFAPP_POWEROFFANIM,
	WID_OFFAPP_POWEROFFANIM_IMAGE,
	WID_OFFAPP_LOW_BATTERY_OFF,
	WID_OFFAPP_MENUWIDGET,
	MNU_OFFAPP_ITEM_SWITCH_OFF,
	MNU_OFFAPP_ITEM_OFF_WITHOUT_ALARM,
	MNU_OFFAPP_ITEM_MASTER_MODE,
	MNU_OFFAPP_ITEM_SLAVE_MODE,
	MNU_OFFAPP_ITEM_DUAL_MODE,
	MNU_OFFAPP_ITEM_DUAL_DISABLE,
	MNU_OFFAPP_ITEM_SINGLE_ENABLE,
	MNU_OFFAPP_ITEM_SINGLE_DISABLE,
	WID_OFFAPP_NETWORK,
	WID_OFFAPP_NETWORK_IMAGE,
	WID_OFFAPP_OPTION_MENU_MODEL,
	WID_OFFAPP_IFONE_MAINCONTAINER,
	WID_OFFAPP_IFONE_BGWIDGET,
	WID_OFFAPP_IFONE_DARKNESSWIDGET,
	//WID_OFFAPP_IFONE_TOPBGWIDGET,
	WID_OFFAPP_IFONE_BOTTOMBGWIDGET,
	WID_OFFAPP_IFONE_BUTTONWIDGET,
	WID_OFFAPP_IFONE_SLIDEWIDGET,
	WID_OFFAPP_TITLEWIDGET,
	WID_OFFAPP_END = 0x2FFF
/* Widget ID end */
};

#endif /* __MMI_OFFAPPVIEW_ID_H__ */
