ApBegin(RS,CLSID_CCAPP)
#ifdef __UI_STYLE_MMI_IFONE__
    WndBegin(CC_WND_OUTGOINGCALL)
        WdgBegin(CLSID_ABSCONTAINER,OutCallInfoCntr)
		WdgAbsContainerCreateForWndRC({{0,0},{CCAPP_IFONE_TOP_IMG_WIDTH,CCAPP_IFONE_TOP_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,OutCallInfoCntr)

        WdgBegin(CLSID_TEXTWIDGET,OutCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_IFONE_1A_NUMBER_INFO_L1_POS_X,CCAPP_IFONE_1A_NUMBER_INFO_L1_POS_Y},{CCAPP_IFONE_NUMBER_INFO_WIDTH,CCAPP_IFONE_NUMBER_INFO_HEIGHT},TEXT_STYLE_COMMON})
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetTextColorRC(COLOR_WHITE)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,OutCallInfoTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,DuoStateImgWdg)
            WdgImageCreateForWndRC({{CCAPP_IFONE_MO_DUAL_IMG_POS_X,CCAPP_IFONE_MO_DUAL_IMG_POS_Y},{CCAPP_IFONE_MO_DUAL_IMG_WIDTH,CCAPP_IFONE_MO_DUAL_IMG_WIDTH},IMAGE_STYLE_COMMON})
        WdgEnd(CLSID_IMAGEWIDGET,DuoStateImgWdg)

        WdgBegin(CLSID_TEXTWIDGET,CallStatesTextWdg)
            WdgTextCreateForWndRC({{CCMTA_IFONE_STATUS_POS_X,CCMTA_IFONE_STATUS_POS_Y},{CCMTA_IFONE_STATUS_WIDTH,CCMTA_IFONE_STATUS_HEIGTH},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_LEFT)
			WdgTextSetDataByIDRC(TXT_CCL_N_CALLING)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_GREEN_2)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(COLOR_WHITE)
        WdgEnd(CLSID_TEXTWIDGET,CallStatesTextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)
            WdgImageCreateForWndRC({{CCAPP_IFONE_MO_CALLER_IMAGE_POS_X,CCAPP_IFONE_MO_CALLER_IMAGE_POS_Y},{CCAPP_IFONE_MO_CALLER_IMAGE_WIDTH,CCAPP_IFONE_MO_CALLER_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)

        WdgBegin(CLSID_INPUTWIDGET,OutgoingInputWdg)
            WdgInputCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgInputSetMultilineRC(TRUE)
            WdgCommonSetTextColorRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_COLOR)
            WdgInputSetCursorColorRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_COLOR)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(CCAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
            WdgInputSetHandWritingEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,OutgoingInputWdg)

        WdgBegin(CLSID_GRID_MENUWIDGET,OutgoingGridWdg)
            WdgMenuCreateForWndRC({{CCAPP_IFONE_CENTER_IMG_POS_X,CCAPP_IFONE_CENTER_IMG_POS_Y},{CCAPP_IFONE_CENTER_IMG_WIDTH,CCAPP_IFONE_CENTER_IMG_HEIGHT},WDG_MENU_TYPE_GRID})
	      	WdgMenuSetItemWidthRC(CCAPP_IFONE_DIAL_GRID_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(CCAPP_IFONE_DIAL_GRID_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(CCAPP_IFONE_DIAL_GRID_ROW_GAP)
            WdgMenuSetColGapRC(CCAPP_IFONE_DIAL_GRID_COL_GAP)
            WdgMenuSetFixedNumRC(CCAPP_IFONE_DIAL_GRID_FIX_NUM)
            WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_DIAL_GRID_PADDING_LEFT,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_RIGHT,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_TOP,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_BOTTOM})
        WdgEnd(CLSID_GRID_MENUWIDGET,OutgoingGridWdg)

		WdgBegin(CLSID_BUTTONWIDGET,OutgoingHideKeypadBtnWdg)
			WdgButtonCreateForWndRC({{CCAPP_IFONE_HIDEKEYPAD_BTN_POS_X,CCAPP_IFONE_HIDEKEYPAD_BTN_POS_Y},{CCAPP_IFONE_HIDEKEYPAD_BTN_WIDTH,CCAPP_IFONE_HIDEKEYPAD_BTN_HEIGHT},0})
			WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
			WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
			WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
			WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
			WdgCommonSetPaddingDataRC({0,0,0,0})
		WdgEnd(CLSID_BUTTONWIDGET,OutgoingHideKeypadBtnWdg)

        WdgBegin(CLSID_ABSCONTAINER,OutBtnCntr)
    		WdgAbsContainerCreateForWndRC({{CCAPP_IFONE_CENTER_IMG_POS_X,CCAPP_IFONE_CENTER_IMG_POS_Y},{CCAPP_IFONE_CENTER_IMG_WIDTH,CCAPP_IFONE_CENTER_IMG_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,OutBtnCntr)

        WdgBegin(CLSID_BUTTONWIDGET,OutVolumeBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_VOLUME_BTN_POS_X,CCAPP_IFONE_VOLUME_BTN_POS_Y},{CCAPP_IFONE_VOLUME_BTN_WIDTH,CCAPP_IFONE_VOLUME_BTN_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IFONE_CALL_IMG_CALL_VOLUME_UNPRESSED,IFONE_CALL_IMG_CALL_VOLUME_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,OutVolumeBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,OutMuteBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_MUTE_BTN_POS_X,CCAPP_IFONE_MUTE_BTN_POS_Y},{CCAPP_IFONE_MUTE_BTN_WIDTH,CCAPP_IFONE_MUTE_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutMuteBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,OutKeypadBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_DIAL_BTN_POS_X,CCAPP_IFONE_DIAL_BTN_POS_Y},{CCAPP_IFONE_DIAL_BTN_WIDTH,CCAPP_IFONE_DIAL_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutKeypadBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,OutSpeakerBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_SPEAKER_BTN_POS_X,CCAPP_IFONE_SPEAKER_BTN_POS_Y},{CCAPP_IFONE_SPEAKER_BTN_WIDTH,CCAPP_IFONE_SPEAKER_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutSpeakerBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,OutOp1BtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_OP1_BTN_POS_X,CCAPP_IFONE_OP1_BTN_POS_Y},{CCAPP_IFONE_OP1_BTN_WIDTH,CCAPP_IFONE_OP1_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_GREY_4)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutOp1BtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,OutOp2BtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_OP2_BTN_POS_X,CCAPP_IFONE_OP2_BTN_POS_Y},{CCAPP_IFONE_OP2_BTN_WIDTH,CCAPP_IFONE_OP2_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_GREY_4)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutOp2BtnWdg)

	WdgBegin(CLSID_BUTTONWIDGET,OutContactBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_CONTACT_BTN_POS_X,CCAPP_IFONE_CONTACT_BTN_POS_Y},{CCAPP_IFONE_CONTACT_BTN_WIDTH,CCAPP_IFONE_CONTACT_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_GREY_4)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,OutContactBtnWdg)

        WdgBegin(CLSID_ABSCONTAINER,OutOpCntr)
		WdgAbsContainerCreateForWndRC({{CCAPP_IFONE_BOTTOM_IMG_POS_X,CCAPP_IFONE_BOTTOM_IMG_POS_Y},{CCAPP_IFONE_BOTTOM_IMG_WIDTH,CCAPP_IFONE_BOTTOM_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,OutOpCntr)

	WdgBegin(CLSID_BUTTONWIDGET,OutEndCallBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_HANGUP_BTN_POS_X,CCAPP_IFONE_HANGUP_BTN_POS_Y},{CCAPP_IFONE_HANGUP_BTN_WIDTH,CCAPP_IFONE_HANGUP_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_LEFT)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_ENDCALLBTN_PADDING_LEFT,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,OutEndCallBtnWdg)

    WndEnd(CC_WND_OUTGOINGCALL)
#else
    WndBegin(CC_WND_OUTGOINGCALL)
        WndSetAllSoftkeyRC( {SK_NONE, SK_DIAL_CALL, SK_CANCEL} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,CallScreenBGWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,CallScreenBGWdg)
#else
		WndSetTitleVisiableRC(VIEWSB_INVISIABLE)
		WndSetBgColorRC(COLOR_BLUE_9)
#endif
        WdgBegin(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)
            WdgImageCreateForWndRC({{CCAPP_OUTGOING_IMAGE_POS_X,CCAPP_OUTGOING_IMAGE_POS_Y},{CCAPP_OUTGOING_IMAGE_WIDTH,CCAPP_OUTGOING_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,PHONEBOOK_IMG_CONTACT_THUMBNAIL}})            
            WdgImageSetDataByIDRC(PHONEBOOK_IMG_CONTACT_THUMBNAIL)
        WdgEnd(CLSID_IMAGEWIDGET,OutgoingCallImgWdg)
        
        WdgBegin(CLSID_IMAGEWIDGET,OutgoingCallTextAreaBgImgWdg)
#ifdef __APP_MMI_SMALLROM__
            WdgImageCreateForWndRC({{CCAPP_RS_TEXT_AREA_BG_L_POS_X,CCAPP_RS_TEXT_AREA_BG_L_POS_Y},{CCAPP_RS_TEXT_AREA_BG_L_POS_WIDTH,CCAPP_RS_TEXT_AREA_BG_L_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgCommonSetBGColorRC(COLOR_BLUE_10)
#else
            WdgImageCreateForWndRC({{CCAPP_RS_TEXT_AREA_BG_L_POS_X,CCAPP_RS_TEXT_AREA_BG_L_POS_Y},{CCAPP_RS_TEXT_AREA_BG_L_POS_WIDTH,CCAPP_RS_TEXT_AREA_BG_L_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_TEXTAREA_BG_L}})
            WdgImageSetDataByIDRC(CALL_IMG_TEXTAREA_BG_L)
#endif
        WdgEnd(CLSID_IMAGEWIDGET,OutgoingCallTextAreaBgImgWdg)

        WdgBegin(CLSID_TEXTWIDGET,CallStatesTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLSTATE_POS_X,CCAPP_OUTGOING_CALLSTATE_POS_Y},{CCAPP_OUTGOING_CALL_TEXTWDG_WIDTH,CCAPP_OUTGOING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
			WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallStatesTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLINFO_POS_X,CCAPP_OUTGOING_CALLINFO_POS_Y},{CCAPP_OUTGOING_CALL_TEXTWDG_WIDTH,CCAPP_OUTGOING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,DuoStateTextWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLDUO_POS_X,CCAPP_OUTGOING_CALLDUO_POS_Y},{CCAPP_OUTGOING_CALL_TEXTWDG_WIDTH,CCAPP_OUTGOING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
			WdgCommonSetTextColorRC(COLOR_WHITE)
			WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,DuoStateTextWdg)
	
#ifdef __CALLER_LOCATION__
        WdgBegin(CLSID_TEXTWIDGET,CallLocationWdg)
            WdgTextCreateForWndRC({{CCAPP_OUTGOING_CALLLC_POS_X,CCAPP_OUTGOING_CALLLC_POS_Y},{CCAPP_OUTGOING_CALL_TEXTWDG_WIDTH,CCAPP_OUTGOING_CALL_TEXTWDG_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallLocationWdg)
#endif	
	
    WndEnd(CC_WND_OUTGOINGCALL)
#endif
#ifdef __UI_STYLE_MMI_IFONE__
    WndBegin(CC_WND_INCALLSCREEN)

        WdgBegin(CLSID_ABSCONTAINER,CallInfoCntr)
            WdgAbsContainerCreateForWndRC({{0,0},{CCAPP_IFONE_TOP_IMG_WIDTH,CCAPP_IFONE_TOP_IMG_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,CallInfoCntr)

        WdgBegin(CLSID_TEXTWIDGET,InCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_IFONE_1A_NUMBER_INFO_L1_POS_X,CCAPP_IFONE_1A_NUMBER_INFO_L1_POS_Y},{CCAPP_IFONE_NUMBER_INFO_WIDTH,CCAPP_IFONE_NUMBER_INFO_HEIGHT},TEXT_STYLE_COMMON})
    		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
    		WdgCommonSetTextColorRC(COLOR_WHITE)
    		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,InCallInfoTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,HoldCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_IFONE_1A1H_NUMBER_INFO_L2_POS_X,CCAPP_IFONE_1A1H_NUMBER_INFO_L2_POS_Y},{CCAPP_IFONE_NUMBER_INFO_WIDTH,CCAPP_IFONE_NUMBER_INFO_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_GREY_4)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_LEFT)
        WdgEnd(CLSID_TEXTWIDGET,HoldCallInfoTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,HoldTextWdg)
            WdgTextCreateForWndRC({{CCAPP_IFONE_1A_STATUS_INFO_L2_POS_X,CCAPP_IFONE_1A_STATUS_INFO_L2_POS_Y},{CCAPP_IFONE_HOLD_INFO_WIDTH,CCAPP_IFONE_HOLD_INFO_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_GREY_4)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_RIGHT)
        WdgEnd(CLSID_TEXTWIDGET,HoldTextWdg)

        WdgBegin(CLSID_BUTTONWIDGET,MptyBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_1A_MPTY_VIEW_LIST_POS_X,CCAPP_IFONE_1A_MPTY_VIEW_LIST_POS_Y},{CCAPP_IFONE_MPTY_VIEW_LIST_WIDTH,CCAPP_IFONE_MPTY_VIEW_LIST_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IFONE_CALL_IMG_CALL_VIEW_UNPRESSED,IFONE_CALL_IMG_CALL_VIEW_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,MptyBtnWdg)

        WdgBegin(CLSID_INPUTWIDGET,InputWdg)
            WdgInputCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgInputSetMultilineRC(TRUE)
            WdgCommonSetTextColorRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_COLOR)
            WdgInputSetCursorColorRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_COLOR)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(CCAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
            WdgInputSetHandWritingEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,InputWdg)

        WdgBegin(CLSID_ABSCONTAINER,BtnCntr)
		WdgAbsContainerCreateForWndRC({{CCAPP_IFONE_CENTER_IMG_POS_X,CCAPP_IFONE_CENTER_IMG_POS_Y},{CCAPP_IFONE_CENTER_IMG_WIDTH,CCAPP_IFONE_CENTER_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,BtnCntr)

        WdgBegin(CLSID_BUTTONWIDGET,VolumeBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_VOLUME_BTN_POS_X,CCAPP_IFONE_VOLUME_BTN_POS_Y},{CCAPP_IFONE_VOLUME_BTN_WIDTH,CCAPP_IFONE_VOLUME_BTN_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IFONE_CALL_IMG_CALL_VOLUME_UNPRESSED,IFONE_CALL_IMG_CALL_VOLUME_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,MuteBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_MUTE_BTN_POS_X,CCAPP_IFONE_MUTE_BTN_POS_Y},{CCAPP_IFONE_MUTE_BTN_WIDTH,CCAPP_IFONE_MUTE_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,MuteBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,KeypadBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_DIAL_BTN_POS_X,CCAPP_IFONE_DIAL_BTN_POS_Y},{CCAPP_IFONE_DIAL_BTN_WIDTH,CCAPP_IFONE_DIAL_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,KeypadBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,SpeakerBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_SPEAKER_BTN_POS_X,CCAPP_IFONE_SPEAKER_BTN_POS_Y},{CCAPP_IFONE_SPEAKER_BTN_WIDTH,CCAPP_IFONE_SPEAKER_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L1_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L1_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L1_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L1_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,SpeakerBtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,Op1BtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_OP1_BTN_POS_X,CCAPP_IFONE_OP1_BTN_POS_Y},{CCAPP_IFONE_OP1_BTN_WIDTH,CCAPP_IFONE_OP1_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,Op1BtnWdg)

        WdgBegin(CLSID_BUTTONWIDGET,Op2BtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_OP2_BTN_POS_X,CCAPP_IFONE_OP2_BTN_POS_Y},{CCAPP_IFONE_OP2_BTN_WIDTH,CCAPP_IFONE_OP2_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,Op2BtnWdg)

	WdgBegin(CLSID_BUTTONWIDGET,ContactBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_CONTACT_BTN_POS_X,CCAPP_IFONE_CONTACT_BTN_POS_Y},{CCAPP_IFONE_CONTACT_BTN_WIDTH,CCAPP_IFONE_CONTACT_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_WHITE)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
		WdgCommonSetAlignmentRC(ALIGN_V_BOTTOM | ALIGN_H_CENTER)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_TXT_L2_PADDING_LEFT,CCAPP_IFONE_BTN_TXT_L2_PADDING_RIGHT,CCAPP_IFONE_BTN_TXT_L2_PADDING_TOP,CCAPP_IFONE_BTN_TXT_L2_PADDING_BOTTOM})
        WdgEnd(CLSID_BUTTONWIDGET,ContactBtnWdg)

        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg)
            WdgMenuCreateForWndRC({{CCAPP_IFONE_CENTER_IMG_POS_X,CCAPP_IFONE_CENTER_IMG_POS_Y},{CCAPP_IFONE_CENTER_IMG_WIDTH,CCAPP_IFONE_CENTER_IMG_HEIGHT},WDG_MENU_TYPE_GRID})
	      WdgMenuSetItemWidthRC(CCAPP_IFONE_DIAL_GRID_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(CCAPP_IFONE_DIAL_GRID_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(CCAPP_IFONE_DIAL_GRID_ROW_GAP)
            WdgMenuSetColGapRC(CCAPP_IFONE_DIAL_GRID_COL_GAP)
            WdgMenuSetFixedNumRC(CCAPP_IFONE_DIAL_GRID_FIX_NUM)
            WdgCommonSetPaddingDataRC({CCAPP_IFONE_BTN_DIAL_GRID_PADDING_LEFT,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_RIGHT,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_TOP,CCAPP_IFONE_BTN_DIAL_GRID_PADDING_BOTTOM})
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg)

        WdgBegin(CLSID_ABSCONTAINER,OpCntr)
		WdgAbsContainerCreateForWndRC({{CCAPP_IFONE_BOTTOM_IMG_POS_X,CCAPP_IFONE_BOTTOM_IMG_POS_Y},{CCAPP_IFONE_BOTTOM_IMG_WIDTH,CCAPP_IFONE_BOTTOM_IMG_HEIGHT},0})
	  WdgEnd(CLSID_ABSCONTAINER,OpCntr)

	WdgBegin(CLSID_BUTTONWIDGET,HideKeypadBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_HIDEKEYPAD_BTN_POS_X,CCAPP_IFONE_HIDEKEYPAD_BTN_POS_Y},{CCAPP_IFONE_HIDEKEYPAD_BTN_WIDTH,CCAPP_IFONE_HIDEKEYPAD_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_H_CENTER|ALIGN_V_MIDDLE)
		WdgCommonSetPaddingDataRC({0,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,HideKeypadBtnWdg)

	WdgBegin(CLSID_BUTTONWIDGET,EndCallBtnWdg)
            WdgButtonCreateForWndRC({{CCAPP_IFONE_HANGUP_BTN_POS_X,CCAPP_IFONE_HANGUP_BTN_POS_Y},{CCAPP_IFONE_HANGUP_BTN_WIDTH,CCAPP_IFONE_HANGUP_BTN_HEIGHT},0})
		WdgButtonSetUnpressedTextColorRC(COLOR_WHITE)
		WdgButtonSetPressedTextColorRC(COLOR_GREY_4)
		WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
		WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
		WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_LEFT)
		WdgCommonSetPaddingDataRC({CCAPP_IFONE_ENDCALLBTN_PADDING_LEFT,0,0,0})
        WdgEnd(CLSID_BUTTONWIDGET,EndCallBtnWdg)

    WndEnd(CC_WND_INCALLSCREEN)
#else
    WndBegin(CC_WND_INCALLSCREEN)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_NONE, SK_NONE} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,CallScreenBgImgWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,CallScreenBgImgWdg)
#else
        WndSetTitleVisiableRC(VIEWSB_INVISIABLE)
        WndSetBgColorRC(COLOR_BLUE_9)
#endif
        WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg1)
            WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg1)
        WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg2)
            WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg2)
        WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg3)
            WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg3)
        WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg4)
            WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg4)
        WdgBegin(CLSID_IMAGEWIDGET,MptyImgWdg5)
            WdgImageCreateForWndRC({{0,0},{CCAPP_IMGAREA_MPTY_IMAGE_WIDTH,CCAPP_IMGAREA_MPTY_IMAGE_HIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
        WdgEnd(CLSID_IMAGEWIDGET,MptyImgWdg5)
        WdgBegin(CLSID_IMAGEWIDGET,DuoImgWdg)
            WdgImageCreateForWndRC({{CCAPP_DUO_IMAGE_POS_X,CCAPP_DUO_IMAGE_POS_Y},{CCAPP_DUO_IMAGE_WIDTH,CCAPP_DUO_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgImageSetDataByIDRC(IMG_NULL_ID)
        WdgEnd(CLSID_IMAGEWIDGET,DuoImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,RecordImgWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORD_IMAGE_POS_X,CCAPP_RECORD_IMAGE_POS_Y},{CCAPP_RECORD_IMAGE_WIDTH,CCAPP_RECORD_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_RECORD_STATE}})
            WdgImageSetDataByIDRC(CALL_IMG_CALL_RECORD_STATE)
        WdgEnd(CLSID_IMAGEWIDGET,RecordImgWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MuteImgWdg)
            WdgImageCreateForWndRC({{CCAPP_MUTE_IMAGE_POS_X,CCAPP_MUTE_IMAGE_POS_Y},{CCAPP_MUTE_IMAGE_WIDTH,CCAPP_MUTE_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_MUTE_STATE}})
            WdgImageSetDataByIDRC(CALL_IMG_MUTE_STATE)
        WdgEnd(CLSID_IMAGEWIDGET,MuteImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,TextAreaBgImgWdg)
#ifdef __APP_MMI_SMALLROM__
            WdgImageCreateForWndRC({{CCAPP_RS_TEXT_AREA_BG_S_POS_X,CCAPP_RS_TEXT_AREA_BG_S_POS_Y},{CCAPP_RS_TEXT_AREA_BG_S_POS_WIDTH,CCAPP_RS_TEXT_AREA_BG_S_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,IMG_NULL_ID}})
            WdgCommonSetBGColorRC(COLOR_BLUE_10)
#else
            WdgImageCreateForWndRC({{CCAPP_RS_TEXT_AREA_BG_S_POS_X,CCAPP_RS_TEXT_AREA_BG_S_POS_Y},{CCAPP_RS_TEXT_AREA_BG_S_POS_WIDTH,CCAPP_RS_TEXT_AREA_BG_S_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_TEXTAREA_BG_S}})
            WdgImageSetDataByIDRC(CALL_IMG_TEXTAREA_BG_S)
#endif
        WdgEnd(CLSID_IMAGEWIDGET,TextAreaBgImgWdg)
        WdgBegin(CLSID_IMAGEWIDGET,CallInfoImgWdg1)
            WdgImageCreateForWndRC({{CCAPP_TEXTAREA_LINE1_IMG_POS_X,CCAPP_TEXTAREA_LINE1_IMG_POS_Y},{CCAPP_TEXTAREA_CALLINFO_IMG_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_ACTIVE}})
            WdgImageSetDataByIDRC(CALL_IMG_CALL_ACTIVE)
        WdgEnd(CLSID_IMAGEWIDGET,CallInfoImgWdg1)
        WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg1)
            WdgTextCreateForWndRC({{CCAPP_TEXTAREA_LINE1_TEXT_POS_X,CCAPP_TEXTAREA_LINE1_TEXT_POS_Y},{CCAPP_TEXTAREA_CALLINFO_TEXT_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_LEFT)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg1)

        WdgBegin(CLSID_IMAGEWIDGET,CallInfoImgWdg2)
            WdgImageCreateForWndRC({{CCAPP_TEXTAREA_LINE2_IMG_POS_X,CCAPP_TEXTAREA_LINE2_IMG_POS_Y},{CCAPP_TEXTAREA_CALLINFO_IMG_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_HOLD}})
            WdgImageSetDataByIDRC(CALL_IMG_CALL_HOLD)
        WdgEnd(CLSID_IMAGEWIDGET,CallInfoImgWdg2)
        WdgBegin(CLSID_TEXTWIDGET,CallInfoTextWdg2)
            WdgTextCreateForWndRC({{CCAPP_TEXTAREA_LINE2_TEXT_POS_X,CCAPP_TEXTAREA_LINE2_TEXT_POS_Y},{CCAPP_TEXTAREA_CALLINFO_TEXT_WIDTH,CCAPP_CALLINFO_ITEM_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_LEFT)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,CallInfoTextWdg2)
    WndEnd(CC_WND_INCALLSCREEN)

#endif

    WndBegin(CC_WND_INCALLEDITOR)
        WndSetAllSoftkeyRC( {SK_NONE, SK_NONE, SK_CANCEL} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
#ifdef __APP_MMI_SMALLROM__
        WndSetBgColorRC((RGBColor_t)RGBCOLOR_BLACK)
#endif	// !__APP_MMI_SMALLROM__

        WdgBegin(CLSID_INPUTWIDGET,InputWidget)
            WdgInputCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_HEIGHT},{FALSE,SKBOARD_DISABLE}})
            WdgInputSetMultilineRC(TRUE)
            WdgInputSetTextColorRC(DEF_THM_CCAPP_TOUCHDIALING_INPUT)
            WdgInputSetCursorColorRC(DEF_THM_CCAPP_TOUCHDIALING_INPUT)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(CCAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
            WdgInputSetHandWritingEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,InputWidget)
        WdgBegin(CLSID_TEXTWIDGET,ShortcutWidget)
            WdgTextCreateForWndRC({{0,0},{DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_SHORTCUT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_START | ALIGN_V_MIDDLE)
            WdgCommonSetTextColorRC(DEF_THM_CCAPP_TOUCHDIALING_INPUT)
        WdgEnd(CLSID_TEXTWIDGET,ShortcutWidget)

#ifdef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_ABSCONTAINER,ButtonAbsContainer)
            WdgAbsContainerCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_CONTAINTER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,ButtonAbsContainer)

        WdgBegin(CLSID_IMAGEWIDGET,ButtonBgImageWdg)
            WdgImageCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_BG_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_BG_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_BG_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_INPUT_NUMBER}})
            WdgImageSetDataByIDRC(CALL_IMG_INPUT_NUMBER)
        WdgEnd(CLSID_IMAGEWIDGET,ButtonBgImageWdg)
#endif	// !__APP_MMI_SMALLROM__

        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg1)
#ifdef __APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(12,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 10}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 11}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_PRESS}}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_COLNUM)
			WdgMenuSetToGridStyleRC({4, 3, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#else	// !__APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_HEIGHT},WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(12,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_01}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_02}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_03}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_04}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 4},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_05}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 5},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_06}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 6},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_07}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 7},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_08}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 8},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_09}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 9},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_10}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 10}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_11}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 11}, {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_12}}}) \
	      WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID1_ITEM_COLNUM)            
            WdgMenuSetToGridStyleRC({3, 4, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#endif	// !__APP_MMI_SMALLROM__
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg1)
        
        WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg2)
#ifdef __APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_HEIGHT}, WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(4,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_NUMBER_CALL_PRESS}}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_COLNUM)
			WdgMenuSetToGridStyleRC({4, 1, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#else	// !__APP_MMI_SMALLROM__
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
            WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_HEIGHT}, WDG_MENU_TYPE_GRID})
            WdgStaticMenuItemRC(4,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CLEAR}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_ADD  }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 2},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_MESSAGE      }}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 3},  {TXT_NULL_ID, TXT_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_RETURN }}}) \
            WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_WIDTH)
            WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_HEIGHT)
            WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_ROW_GAP)
            WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_POS_COL_GAP)
            WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID2_ITEM_COLNUM)
            WdgMenuSetToGridStyleRC({DIALERAPP_RS_GRID_WDG2_HORZ, DIALERAPP_RS_GRID_WDG2_VERT, WDG_MENU_GRID_STYLE_FIX_SINGLE_PAGE})
#endif	// !__APP_MMI_SMALLROM__
        WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg2)
        
#ifndef __APP_MMI_SMALLROM__         
		WdgBegin(CLSID_GRID_MENUWIDGET,GridWdg3)
			WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_BUTTON)
			WdgMenuCreateForWndRC({{DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_X,DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_Y},{DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_WIDTH,DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgStaticMenuItemRC(2,
				{{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 0},  {TXT_NULL_ID, IMG_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CALL_SIM1}}, \
				{{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, 1},  {TXT_NULL_ID, TXT_NULL_ID, CALL_IMG_INPUT_BLUE_NUMBER_CALL_SIM2 }}}) \
			WdgMenuSetItemWidthRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_WIDTH)
			WdgMenuSetItemHeightRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_HEIGHT)
			WdgMenuSetRowGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_ROW_GAP)
			WdgMenuSetColGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_POS_COL_GAP)
			WdgMenuSetFixedNumRC(DIALERAPP_LAYOUT_TOUCHDIALING_GRID3_ITEM_COLNUM)
		WdgEnd(CLSID_GRID_MENUWIDGET,GridWdg3)
#endif        
        
        WdgBegin(CLSID_INPUTWIDGET,ActInputWidget)
            WdgInputCreateForWndRC({{0,0},{CCAPP_RS_ACT_INPUT_WEIGHT,CCAPP_RS_ACT_INPUT_HEIGHT},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetTextColorRC(DEF_THM_CCAPP_DIALING_INPUT)
            WdgInputSetCursorColorRC(DEF_THM_CCAPP_DIALING_INPUT)
            WdgInputSetFontSizeRC(FONT_CAT_NUM_LARGE)
            WdgInputSetLineGapRC(DIALERAPP_LAYOUT_TOUCHDIALING_INPUT_LINEGAP)
            WdgInputSetMaxByteLengthRC(CCAPP_DIALER_MAX_INPUT_BYTE)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetSoftKeyBoardEnableRC(FALSE)
        WdgEnd(CLSID_INPUTWIDGET,ActInputWidget)
        WdgBegin(CLSID_TEXTWIDGET,ActShortcutWidget)
            WdgTextCreateForWndRC({{0,0},{CCAPP_RS_ACT_INPUT_WEIGHT,CCAPP_RS_ACT_INPUT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC(ALIGN_H_LEFT)
            WdgCommonSetTextColorRC(DEF_THM_CCAPP_DIALING_INPUT)
        WdgEnd(CLSID_TEXTWIDGET,ActShortcutWidget)
    WndEnd(CC_WND_INCALLEDITOR)
#ifdef __IP_CALL_MMI__
    WndBegin(CC_WND_IPNUMBEREDITOR)
        WndSetTitleRC({IMG_NULL_ID,TXT_LTL_N_IP_NUMBER})
        WndSetAllSoftkeyRC( {SK_SAVE, SK_OK, SK_CANCEL} )
        WdgBegin(CLSID_INPUTWIDGET,IpNumInput)
            WdgInputCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT_WITH_SB},{TRUE,SKBOARD_ENABLE}})
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_DIALING)
            WdgInputSetMultilineRC(TRUE)
            WdgInputSetMaxByteLengthRC(CCAPP_IPCALL_MAX_NUM_LEN)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP)
        WdgEnd(CLSID_INPUTWIDGET,IpNumInput)
    WndEnd(CC_WND_IPNUMBEREDITOR)
#endif
    WndBegin(CC_WND_MULTIPARTYLIST)
        WdgBegin(CLSID_VTMMENU,MutiList)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_MULTIPARTY,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,MutiList)
    WndEnd(CC_WND_MULTIPARTYLIST)
#ifdef __IP_CALL_MMI__
    WndBegin(CC_WND_IPNUMBERLIST)
        WdgBegin(CLSID_VTMMENU,IpNumber)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_IP_NUMBER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_VTMMENU,IpNumber)
    WndEnd(CC_WND_IPNUMBERLIST)
#endif
    WndBegin(CC_WND_INCALLEDITOROPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,InCallMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,4})
            VtmCreateOptionMenuDataRC(4,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_CALL},TXT_OIL1_N_CALL},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_IPCALL},TXT_OIL1_N_IP_CALL},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_ADD},TXT_OIL1_N_SAVE},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_SEND},TXT_OIL1_N_SEND}})
        WdgEnd(CLSID_VTMOPTIONMENU,InCallMenu)
    WndEnd(CC_WND_INCALLEDITOROPTIONMENU)

    WndBegin(CC_WND_MULTIPARTYOPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,MultiMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_SPLIT},TXT_OIL1_N_SPLIT},{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_END_SELECTED_},TXT_OIL1_N_END_SELECTED_CALL}})
        WdgEnd(CLSID_VTMOPTIONMENU,MultiMenu)
    WndEnd(CC_WND_MULTIPARTYOPTIONMENU)

    WndBegin(CC_WND_INCALLSCREENOPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU,InCallScreen)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,21})
            VtmCreateOptionMenuDataRC(21,{
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_SPEAKER},TXT_OIL1_N_SPEAKER},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_HANDSET},TXT_OIL1_N_HANDSET},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_BT_HEADSET},TXT_OIL1_N_BTHEADSET},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_MUTE},TXT_RSK_N_MUTE},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_UNMUTE},TXT_RSK_N_UNMUTE},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_HOLD},TXT_OIL1_N_HOLD},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_RETRIEVE},TXT_OIL1_N_RETRIEVE},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_SWAP},TXT_OIL1_N_SWAP},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_VIEW},TXT_OIL1_N_VIEW},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_END_ACTIVE},TXT_OIL1_N_END_ACTIVE_CALL},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_END_HOLD},TXT_OIL1_N_END_HOLD_CALL},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_MULTIPARTY},TXT_OIL1_N_MULTIPARTY},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_TRANSFER},TXT_OIL1_N_TRANSFER},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_VOLUME},TXT_OIL1_N_VOLUME},
                {{MENUMODEL_ITEM_VISABLE|MENUMODEL_ITEM_HAS_CHILD,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_DTMF},TXT_OIL1_N_DTMF},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_RECORD},TXT_OIL1_N_RECORD},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_STOP_RECORD},TXT_OIL1_N_STOP_RECORD},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_PHONEBOOK},TXT_OIL1_N_PHONEBOOK},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_MESSAGE},TXT_OIL1_N_MESSAGES},
                {{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_DISTORTED_VOICE},TXT_LIL_N_DISTORTED_VOICE},
		{{MENUMODEL_ITEM_VISABLE,{SK_SELECT,SK_OK,SK_CANCEL},MNU_CC_OPT_CALL_BACKGROUND_SOUND},TXT_LIL_N_CALL_BACKGROUND_SOUND}})
        WdgEnd(CLSID_VTMOPTIONMENU,InCallScreen)
    WndEnd(CC_WND_INCALLSCREENOPTIONMENU)

    WndBegin(CC_WND_DTMFNUMBERINPUT)
        WndSetAllSoftkeyRC( {SK_SELECT, SK_OK, SK_BACK} )
        WdgBegin(CLSID_VTMPOPUPINPUT,DtmfInput)
            VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_PML_N_DTMF_NUMBER,MAE_INPUTMODE_DIALING})
        WdgEnd(CLSID_VTMPOPUPINPUT,DtmfInput)
    WndEnd(CC_WND_DTMFNUMBERINPUT)

    WndBegin(CC_WND_DUALMENU)
        WdgBegin(CLSID_VTMSIMSELECTION,DualMenu)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_LTL_N_CALL})
        WdgEnd(CLSID_VTMSIMSELECTION,DualMenu)
    WndEnd(CC_WND_DUALMENU)
    
    WndBegin(CC_WND_CBS_OPTION_LIST)
        WdgBegin(CLSID_VTMMENU,CBSOptionMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CALL_BACKGROUND_SOUND,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,CHECK_RADIO_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,CBSOptionMenu)
    WndEnd(CC_WND_CBS_OPTION_LIST)

    WndBegin(CC_WND_CBS_SETTING_MAIN)
        WdgBegin(CLSID_VTMMENU,CBSSettingMain)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_CALL_BACKGROUND_SOUND,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,4,0,0})
            VtmCreateMenuDataRC(4,{{{MENUMODEL_ITEM_VISABLE,{SK_CHANGE,SK_OK,SK_BACK},MNU_CC_CBS_STATUS},{TXT_LIL_N_STATUS,TXT_NULL_ID}},
            					{{MENUMODEL_ITEM_VISABLE,{SK_CHANGE,SK_OK,SK_BACK},MNU_CC_CBS_PLAY_TYPE},{TXT_LIL_N_PLAY_TYPE,TXT_NULL_ID}},
            					{{MENUMODEL_ITEM_VISABLE,{SK_CHANGE,SK_OK,SK_BACK},MNU_CC_CBS_EFFECT_SOUND},{TXT_LIL_N_EFFECT_SOUND,TXT_NULL_ID}},
								{{MENUMODEL_ITEM_VISABLE,{SK_CHANGE,SK_OK,SK_BACK},MNU_CC_CBS_VOLUME},{TXT_LIL_N_VOLUME,TXT_NULL_ID}}})
        WdgEnd(CLSID_VTMMENU,CBSSettingMain)
    WndEnd(CC_WND_CBS_SETTING_MAIN)

    WndBegin(CC_WND_CBS_SETTING_PLAY_TYPE)
        WdgBegin(CLSID_VTMMENU,CBSPlayType)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,3,0,0})
            WdgStaticMenuItemRC(3,{{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_CC_CBS_PLAY_ONCE, TXT_LIL_N_ONCE},
                              	{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_CC_CBS_PLAY_REPEAT, TXT_LIL_N_REPEAT},
							  	{MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_CC_CBS_PLAY_INTERVAL, TXT_NULL_ID}})
        WdgEnd(CLSID_VTMMENU,CBSPlayType)
	WndEnd(CC_WND_CBS_SETTING_PLAY_TYPE)
	
	WndBegin(CC_WND_CBS_SETTING_INTERVAL_INPUT_POPUP)
		WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
		WdgBegin(CLSID_VTMPOPUPINPUT,IntervalPopupInput)
			VtmCreatePopUpInputRC({IMG_NULL_ID,IMG_NULL_ID,TXT_LIL_N_INTERVAL,MAE_INPUTMODE_NUMERIC})
			VTMWdgBegin (CLSID_INPUTWIDGET, POP_UP_INPUT_INPUT_WDG, IntervalInputWidget)
				WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_NUMERIC)
				WdgInputSetMaxByteLengthRC(4)
				WdgInputSetDisableSymbolTableRC(TRUE)
			VTMWdgEnd (CLSID_INPUTWIDGET, POP_UP_INPUT_INPUT_WDG, IntervalInputWidget)
		WdgEnd(CLSID_VTMPOPUPINPUT,IntervalPopupInput)
	WndEnd(CC_WND_CBS_SETTING_INTERVAL_INPUT_POPUP)

    WndBegin(CC_WND_CBS_SETTING_EFFECT_SOUND)
        WdgBegin(CLSID_VTMMENU,EffectSoundMenu)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_EFFECT_SOUND,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,CHECK_RADIO_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,EffectSoundMenu)
    WndEnd(CC_WND_CBS_SETTING_EFFECT_SOUND)

    WndBegin(CC_WND_CBS_SETTING_VOLUME)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_VOLUME})
    WndEnd(CC_WND_CBS_SETTING_VOLUME)

	WndBegin(CC_WND_CUS)
		RSCustomize(WProp_t,tTalkViewImgAreaCntnrPos,{TRUE,CCAPP_RS_TALK_VIEW_IMG_PROP})
		RSCustomize(WProp_t,tTalkViewTimeAreaCntnrPos,{TRUE,CCAPP_RS_TALK_VIEW_TIME_PROP})
		RSCustomize(WProp_t,tTalkViewTextAreaCntnrPos,{TRUE,CCAPP_RS_TALK_VIEW_TEXT_PROP})
		RSCustomize(WProp_t,tOutgoingImgAreaCntnrPos,{TRUE,CCAPP_RS_OUTGOING_IMG_PROP})
		RSCustomize(WProp_t,tOutgoingTextAreaCntnrPos,{TRUE,CCAPP_RS_OUTGOING_TEXT_PROP})
	WndEnd(CC_WND_CUS)
		
	WndBegin(CC_WND_DISTORTEDEFFECTLIST)
        WdgBegin(CLSID_VTMMENU,DistortedEffectList)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_DISTORTED_VOICE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,CHECK_RADIO_STYLE_RADIO,7,0,0})
            VtmCreateMenuDataRC(7,
            	{{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_OFF},TXT_LIL_N_OFF},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_KID},TXT_LIL_N_DISTORTED_EFFECT_KID},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_GIRL},TXT_LIL_N_DISTORTED_EFFECT_GIRL},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_WOMAN},TXT_LIL_N_DISTORTED_EFFECT_WOMAN},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_YOUNGMAN},TXT_LIL_N_DISTORTED_EFFECT_YOUNGMAN},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_MAN},TXT_LIL_N_DISTORTED_EFFECT_MAN},
				{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT,SK_OK,SK_CANCEL},MNU_CC_DISTORTED_EFFECT_BASS},TXT_LIL_N_DISTORTED_EFFECT_BASS}})
        WdgEnd(CLSID_VTMMENU,DistortedEffectList)
    WndEnd(CC_WND_DISTORTEDEFFECTLIST)

    WndBegin(CC_WND_RECORDINGSCREEN)
        WndSetAllSoftkeyRC( {SK_OPTION, SK_NONE, SK_NONE} )
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)

#ifndef __APP_MMI_SMALLROM__
#ifdef __UI_STYLE_MMI_IFONE__
		WdgBegin(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
			WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_IFONE_BG}})
			WdgImageSetDataByIDRC(CALL_IMG_DIALING_IFONE_BG)
		WdgEnd(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
#else
        WdgBegin(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
#endif
        WdgBegin(CLSID_IMAGEWIDGET,RecordingWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORDING_POS_X,CCAPP_RECORDING_POS_Y},{CCAPP_RECORDING_POS_WIDTH,CCAPP_RECORDING_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_ANSWER_MACHINE}})
            WdgImageSetDataByIDRC(CALL_IMG_CALL_ANSWER_MACHINE)
        WdgEnd(CLSID_IMAGEWIDGET,RecordingWdg)
#else
        WndSetTitleVisiableRC(VIEWSB_INVISIABLE)
        WndSetBgColorRC(COLOR_BLUE_9)
        WdgBegin(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORD_BG_POS_X,CCAPP_RECORD_BG_POS_Y},{CCAPP_RECORD_BG_POS_WIDTH,CCAPP_RECORD_BG_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_RECORDING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_RECORDING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,RecordingScreenBgImgWdg)
#endif

        WdgBegin(CLSID_TEXTWIDGET,RecordCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_RECORDING_CALLINFO_TEXT_POS_X,CCAPP_FULL_RECORDING_CALLINFO_TEXT_POS_Y},{CCAPP_FULL_RECORDING_CALLINFO_TEXT_WIDTH,CCAPP_FULL_RECORDING_CALLINFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,RecordCallInfoTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,InfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_RECORDING_INFO_TEXT_POS_X,CCAPP_FULL_RECORDING_INFO_TEXT_POS_Y},{CCAPP_FULL_RECORDING_INFO_TEXT_WIDTH,CCAPP_FULL_RECORDING_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,InfoTextWdg)
       
        WdgBegin(CLSID_TEXTWIDGET,DurationTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_RECORDING_DURATION_POS_X,CCAPP_FULL_RECORDING_DURATION_POS_Y},{CCAPP_FULL_RECORDING_DURATION_WIDTH,CCAPP_FULL_RECORDING_DURATION_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)                    
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,DurationTextWdg)
    WndEnd(CC_WND_RECORDINGSCREEN)

#ifdef __APP_MMI_ANSWERING_MACHINE__
    WndBegin(CC_WND_ANSWERINGMACHINESCREEN)
        WndSetAllSoftkeyRC({SK_NONE, SK_NONE, SK_CANCEL})
        WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
#ifndef __APP_MMI_SMALLROM__
#ifdef __UI_STYLE_MMI_IFONE__
		WdgBegin(CLSID_IMAGEWIDGET,AMScreenBgImgWdg)
			WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_IFONE_BG}})
			WdgImageSetDataByIDRC(CALL_IMG_DIALING_IFONE_BG)
		WdgEnd(CLSID_IMAGEWIDGET,AMScreenBgImgWdg)
#else
        WdgBegin(CLSID_IMAGEWIDGET,AMScreenBgImgWdg)
            WdgImageCreateForWndRC({{0,0},{CCAPP_DEFAULT_VIEW_WIDTH,CCAPP_DEFAULT_VIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_DIALING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_DIALING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,AMScreenBgImgWdg)        
#endif
        WdgBegin(CLSID_IMAGEWIDGET,AMScreenRecordingWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORDING_POS_X,CCAPP_RECORDING_POS_Y},{CCAPP_RECORDING_POS_WIDTH,CCAPP_RECORDING_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_CALL_ANSWER_MACHINE}})
            WdgImageSetDataByIDRC(CALL_IMG_CALL_ANSWER_MACHINE)
        WdgEnd(CLSID_IMAGEWIDGET,AMScreenRecordingWdg)        
#else
        WndSetTitleVisiableRC(VIEWSB_INVISIABLE)
        WndSetBgColorRC(COLOR_BLUE_9)
        WdgBegin(CLSID_IMAGEWIDGET,AMScreenRecordingImgWdg)
            WdgImageCreateForWndRC({{CCAPP_RECORD_BG_POS_X,CCAPP_RECORD_BG_POS_Y},{CCAPP_RECORD_BG_POS_WIDTH,CCAPP_RECORD_BG_POS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,CALL_IMG_RECORDING_BG}})
            WdgImageSetDataByIDRC(CALL_IMG_RECORDING_BG)
        WdgEnd(CLSID_IMAGEWIDGET,AMScreenRecordingImgWdg)
#endif
        WdgBegin(CLSID_TEXTWIDGET,AMCallInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_AM_CALLINFO_TEXT_POS_X,CCAPP_FULL_AM_CALLINFO_TEXT_POS_Y},{CCAPP_FULL_AM_CALLINFO_TEXT_WIDTH,CCAPP_FULL_AM_CALLINFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,AMCallInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,AMInfoTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_AM_INFO_TEXT_POS_X,CCAPP_FULL_AM_INFO_TEXT_POS_Y},{CCAPP_FULL_AM_INFO_TEXT_WIDTH,CCAPP_FULL_AM_INFO_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,AMInfoTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,AMWaitingTextWdg)
            WdgTextCreateForWndRC({{CCAPP_FULL_AM_WAITING_TEXT_POS_X,CCAPP_FULL_AM_WAITING_TEXT_POS_Y},{CCAPP_FULL_AM_WAITING_TEXT_WIDTH,CCAPP_FULL_AM_WAITING_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE | ALIGN_H_CENTER)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)                    
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetFontTypeRC(FONT_TYPE_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,AMWaitingTextWdg)
    WndEnd(CC_WND_ANSWERINGMACHINESCREEN)
#endif
    
ApEnd(RS,CLSID_CCAPP)

