ApBegin(RS,CLSID_MAPAPP)
    WndBegin(MAP_WND_SELECT_CARD)
        WdgBegin(CLSID_VTMSIMSELECTION,vtmSimSelect)
            VtmCreateSimSelectionRC({IMG_NULL_ID,TXT_TTL_N_SIM})
        WdgEnd(CLSID_VTMSIMSELECTION,vtmSimSelect)
    WndEnd(MAP_WND_SELECT_CARD)

    WndBegin(MAP_WND_LOGO)
        WdgBegin(CLSID_VTMIMG,vtmImgLogo)
            VtmCreateImgRC(MAPVIEW_IMG_POWER_ON)
        WdgEnd(CLSID_VTMIMG,vtmImgLogo)
    WndEnd(MAP_WND_LOGO)

    WndBegin(MAP_WND_OPTION_MY_FAVORITE)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMyFavorite)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,9})
            VtmCreateOptionMenuDataRC(9, {
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_VIEWONMAP},TXT_LIL_N_MAP_VIEWONMAP},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_EDIT},TXT_LIL_N_MAP_EDIT},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_MARK},TXT_LIL_N_MAP_MARK},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_MARKALL},TXT_LIL_N_MAP_MARKALL},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_UNMARK},TXT_LIL_N_MAP_UNMARK},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_UNMARKALL},TXT_LIL_N_MAP_UNMARKALL},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_DELETE},TXT_LIL_N_MAP_DELETE},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_POI},TXT_LIL_N_MAP_POI},
                {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_OPT_MYLOCATION},TXT_LIL_N_MAP_MYLOCATION} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmMyFavorite)
    WndEnd(MAP_WND_OPTION_MY_FAVORITE)

    WndBegin(MAP_WND_OPTION_MAPVIEW)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmMapView)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,12})
            VtmCreateOptionMenuDataRC(12, {
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_CALL},TXT_LIL_N_MAP_CALL},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_IP_CALL},TXT_LIL_N_MAP_IP_CALL},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_VIEW},TXT_LIL_N_MAP_VIEW},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_LBS},TXT_LIL_N_MAP_LBS},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_POI_NEARBY},TXT_LIL_N_MAP_POINEARBY},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_SEARCH_POI},TXT_LIL_N_MAP_SEARCHPOI},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_HISTORY},TXT_LIL_N_MAP_HISTORY},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_MY_FAVORITE},TXT_LIL_N_MAP_MYFAVORITE},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_ADDTOFAVORITE},TXT_LIL_N_MAP_ADDTOFAVORITE},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_SEND},TXT_LIL_N_MAP_SEND},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_WHERE_AM_I},TXT_LIL_N_MAP_WHEREAMI},
                                        {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_CANCEL}, MNU_MAPAPP_SETTINGS},TXT_LIL_N_MAP_SETTING} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmMapView)
    WndEnd(MAP_WND_OPTION_MAPVIEW)

    WndBegin(MAP_WND_KEYWORD_INPUT)
        WdgBegin(CLSID_VTMOPTIONMENU, vtmKeyword)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2, {
                           {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_SAVE}, TXT_LSK_N_OK},
                           {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_COMMON_TEXT_INPUT_MENU}, TXT_OIL1_N_INPUT_MENU} })
        WdgEnd(CLSID_VTMOPTIONMENU,vtmKeyword)
    WndEnd(MAP_WND_KEYWORD_INPUT)

    WndBegin(MAP_WND_MAPVIEW)
        WndSetAllSoftkeyRC({SK_SELECT, SK_OK, SK_BACK})
        WdgBegin(CLSID_IMAGEWIDGET,ImgTitleBar)
            WdgImageCreateForWndRC({{MAPVIEW_POS_TITLE_BAR_X,MAPVIEW_POS_TITLE_BAR_Y},{MAPVIEW_TITLE_BAR_WIDTH,MAPVIEW_TITLE_BAR_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_LIST_TITLE_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_LIST_TITLE_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ImgTitleBar)

        WdgBegin(CLSID_TEXTWIDGET,TextTitleBar)
            WdgTextCreateForWndRC({{MAPVIEW_POS_TITLE_BAR_X,MAPVIEW_POS_TITLE_BAR_Y},{MAPVIEW_TITLE_BAR_WIDTH,MAPVIEW_TITLE_BAR_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetAlignmentRC(ALIGN_H_START | ALIGN_V_MIDDLE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetFontTypeRC(FONT_TYPE_OUTLINE)
            WdgTextSetTextOutlineColorRC(DEF_THM_MAPAPP_CALENDAR_HIGHLIGHT_BORDER)
        WdgEnd(CLSID_TEXTWIDGET,TextTitleBar)

        WdgBegin(CLSID_IMAGEWIDGET,ImgCenterFocus)
            WdgImageCreateForWndRC({{MAPVIEW_POS_CENTER_FOCUS_X,MAPVIEW_POS_CENTER_FOCUS_Y},{MAPVIEW_ICON_CENTER_FOCUS_WIDTH,MAPVIEW_ICON_CENTER_FOCUS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MAPVIEW_IMG_MAP_CENTER}})
            WdgImageSetDataByIDRC(MAPVIEW_IMG_MAP_CENTER)
        WdgEnd(CLSID_IMAGEWIDGET,ImgCenterFocus)

        WdgBegin(CLSID_IMAGEWIDGET,ImgZoom)
            WdgImageCreateForWndRC({{MAPVIEW_POS_ZOOM_X,MAPVIEW_POS_ZOOM_Y},{MAPVIEW_ICON_ZOOM_WIDTH,MAPVIEW_ICON_ZOOM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MAPVIEW_IMG_ZOOM_BG}})
            WdgImageSetDataByIDRC(MAPVIEW_IMG_ZOOM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ImgZoom)

        WdgBegin(CLSID_IMAGEWIDGET,ImgZoomStatus)
            WdgImageCreateForWndRC({{MAPVIEW_POS_ZOOM_STATUS_X,MAPVIEW_POS_ZOOM_STATUS_Y},{MAPVIEW_ICON_ZOOM_STATUS_WIDTH,MAPVIEW_ICON_ZOOM_STATUS_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MAPVIEW_IMG_ZOOM_STATUS}})
            WdgImageSetDataByIDRC(MAPVIEW_IMG_ZOOM_STATUS)
        WdgEnd(CLSID_IMAGEWIDGET,ImgZoomStatus)

        WdgBegin(CLSID_BUTTONWIDGET,ZoomIn)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_ZOOM_IN_PRESS_UNPRESS_X,MAPVIEW_POS_ZOOM_IN_PRESS_UNPRESS_Y},{MAPVIEW_ICON_ZOOM_PRESS_UNPRESS_WIDTH,MAPVIEW_ICON_ZOOM_PRESS_UNPRESS_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_ZOOM_IN_UNPRESSED,MAPVIEW_IMG_ZOOM_IN_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZoomIn)

        WdgBegin(CLSID_BUTTONWIDGET,ZoomOut)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_ZOOM_OUT_PRESS_UNPRESS_X,MAPVIEW_POS_ZOOM_OUT_PRESS_UNPRESS_Y},{MAPVIEW_ICON_ZOOM_PRESS_UNPRESS_WIDTH,MAPVIEW_ICON_ZOOM_PRESS_UNPRESS_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_ZOOM_OUT_UNPRESSED,MAPVIEW_IMG_ZOOM_OUT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ZoomOut)

        WdgBegin(CLSID_MENUWIDGET,Settings)
            WdgMenuCreateForWndRC({{MAPVIEW_SETTING_MENU_X_POS,MAPVIEW_SETTING_MENU_Y_POS},{MAPVIEW_SETTING_MENU_WIDTH,MAPVIEW_SETTING_MENU_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgMenuSetMenuBGImageRC(MAPVIEW_IMG_OPTIONS_BG)
        WdgEnd(CLSID_MENUWIDGET,Settings)

        WdgBegin(CLSID_IMAGEWIDGET,ImgNotice)
            WdgImageCreateForWndRC({{MAPVIEW_POS_FOCUS_MODE_TEXT_BG_X,MAPVIEW_POS_FOCUS_MODE_TEXT_BG_Y},{MAPVIEW_FOCUS_MODE_TEXT_WIDTH,MAPVIEW_FOCUS_MODE_TEXT_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,MAPVIEW_IMG_NOTICE_BG}})
            WdgImageSetDataByIDRC(MAPVIEW_IMG_NOTICE_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ImgNotice)

        WdgBegin(CLSID_TEXTWIDGET,FocusMode)
            WdgTextCreateForWndRC({{MAPVIEW_POS_FOCUS_MODE_TEXT_X,MAPVIEW_POS_FOCUS_MODE_TEXT_Y},{MAPVIEW_FOCUS_MODE_TEXT_WIDTH,MAPVIEW_FOCUS_MODE_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetTextColorRC(DEF_THM_MAPAPP_CALENDAR_DAY_TEXT)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetAlignmentRC((ALIGN_V_MIDDLE|ALIGN_H_CENTER))
        WdgEnd(CLSID_TEXTWIDGET,FocusMode)

        WdgBegin(CLSID_BUTTONWIDGET,PrevMode)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_SWITCH_PREVIOUS_BUTTON_X,MAPVIEW_POS_SWITCH_PREVIOUS_BUTTON_Y},{MAPVIEW_SWITCH_BUTTON_WIDTH,MAPVIEW_SWITCH_BUTTON_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_NOTICE_PREVIOUS_UNPRESSED,MAPVIEW_IMG_NOTICE_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,PrevMode)

        WdgBegin(CLSID_BUTTONWIDGET,NextMode)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_SWITCH_NEXT_BUTTON_X,MAPVIEW_POS_SWITCH_NEXT_BUTTON_Y},{MAPVIEW_SWITCH_BUTTON_WIDTH,MAPVIEW_SWITCH_BUTTON_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_NOTICE_NEXT_UNPRESSED,MAPVIEW_IMG_NOTICE_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,NextMode)

        WdgBegin(CLSID_BUTTONWIDGET,LeftArrow)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_SERVICE_LEFT_ARROW_X,MAPVIEW_POS_SERVICE_LEFT_ARROW_Y},{MAPVIEW_ICON_SERVICE_LEFT_ARROW_WIDTH,MAPVIEW_ICON_SERVICE_LEFT_ARROW_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_SERVICE_LEFT_ARROW,MAPVIEW_IMG_SERVICE_LEFT_ARROW})
        WdgEnd(CLSID_BUTTONWIDGET,LeftArrow)

        WdgBegin(CLSID_BUTTONWIDGET,RightArrow)
            WdgButtonCreateForWndRC({{MAPVIEW_POS_SERVICE_RIGHT_ARROW_X,MAPVIEW_POS_SERVICE_RIGHT_ARROW_Y},{MAPVIEW_ICON_SERVICE_RIGHT_ARROW_WIDTH,MAPVIEW_ICON_SERVICE_RIGHT_ARROW_HEIGHT}})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,MAPVIEW_IMG_SERVICE_RIGHT_ARROW,MAPVIEW_IMG_SERVICE_RIGHT_ARROW})
        WdgEnd(CLSID_BUTTONWIDGET,RightArrow)

        WdgBegin(CLSID_VTMOPTIONMENU, vtmOptionSetting)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,14})
            VtmCreateOptionMenuDataRC(14, {
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_CALL}, MAPVIEW_IMG_OPTIONS_CALL},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_IP_CALL}, MAPVIEW_IMG_OPTIONS_IP_CALL},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_VIEW}, MAPVIEW_IMG_OPTIONS_VIEW_DETAIL},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_LBS},MAPVIEW_IMG_OPTIONS_SERVICE},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_POI_NEARBY},MAPVIEW_IMG_OPTIONS_POI_NEARBY},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SEARCH_POI},MAPVIEW_IMG_OPTIONS_SEARCH_POI},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SEARCH_LIST},MAPVIEW_IMG_OPTIONS_SEARCH_LIST},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HISTORY},MAPVIEW_IMG_OPTIONS_HISTORY},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_MY_FAVORITE},MAPVIEW_IMG_OPTIONS_MY_FAVORITE},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_ADDTOFAVORITE},MAPVIEW_IMG_OPTIONS_ADD_FAVORITE},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SEND},MAPVIEW_IMG_OPTIONS_SEND},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_WHERE_AM_I},MAPVIEW_IMG_OPTIONS_MY_LOCATION},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SETTINGS},MAPVIEW_IMG_OPTIONS_SETTINGS},
                                    {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_ABOUT},MAPVIEW_IMG_OPTIONS_ABOUT} })

        WdgEnd(CLSID_VTMOPTIONMENU,vtmOptionSetting)

/*Container({{0,0},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT}})*/
/*Bitmap({{MAPVIEW_BITMAP_X_POS,MAPVIEW_BITMAP_Y_POS},{MAPVIEW_BITMAP_WIDTH,MAPVIEW_BITMAP_HEIGHT},IMG_NULL_ID})*/
/* Bitmap -> Image */
    WndEnd(MAP_WND_MAPVIEW)

    WndBegin(MAP_WND_DATALIST)
        WndSetTitleRC(IMG_NULL_ID,TXT_LIL_N_LOCATION)

        WdgBegin(CLSID_MENUWIDGET,DataListMenu)
            WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT-MAIN_TITLE_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
        WdgEnd(CLSID_MENUWIDGET,DataListMenu)
    WndEnd(MAP_WND_DATALIST)

    WndBegin(MAP_WND_MULTI_FIELD_INPUT)
        WndSetTitleRC(IMG_NULL_ID,TXT_LIL_N_LOCATION)

        WdgBegin(CLSID_MENUWIDGET,FieldMenu)
            WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT-MAIN_TITLE_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgStaticMenuInitRC(WDG_MENU_ITEM_TYPE_IMAGETEXT_SPACETEXT)
        WdgEnd(CLSID_MENUWIDGET,FieldMenu)
    WndEnd(MAP_WND_MULTI_FIELD_INPUT)

    WndBegin(MAP_WND_THUMB_POI)
        WndSetTitleRC(IMG_NULL_ID,TXT_NULL_ID)

        WdgBegin(CLSID_IMGGRID_MENUWIDGET,ThumbImgGrid)
            WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_DEFVIEW_WIDTH,MAIN_DEFVIEW_HEIGHT-MAIN_TITLE_HEIGHT},WDG_MENU_TYPE_IMG_GRID})
            WdgCommonSetBGColorRC(DEF_THM_MAPAPP_BG)
            WdgMenuSetRowGapRC(MAIN_THUMBNAIL_ITEM_ROW_GAP)
            WdgMenuSetColGapRC(MAIN_THUMBNAIL_ITEM_COL_GAP)
            WdgCommonSetPaddingDataRC({MAIN_THUMBNAIL_LEFT_PADDING, MAIN_THUMBNAIL_RIGHT_PADDING, MAIN_THUMBNAIL_TOP_PADDING, MAIN_THUMBNAIL_BOTTOM_PADDING})
            WdgStaticMenuItemRC(33, {
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_BEIJING},{MAPVIEW_IMG_AREA_BEIJING,TXT_LIL_N_DISTRICT_BEIJING}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_TIANJIN},{MAPVIEW_IMG_AREA_TIANJIN,TXT_LIL_N_DISTRICT_TIANJIN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HEBEI},{MAPVIEW_IMG_AREA_HEBEI,TXT_LIL_N_DISTRICT_HEBEI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SHANXI},{MAPVIEW_IMG_AREA_SHANXI,TXT_LIL_N_DISTRICT_SHANXI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_NEIMONGOL},{MAPVIEW_IMG_AREA_INNER_MONGOLIA,TXT_LIL_N_DISTRICT_NEIMONGOL}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_LIAONING},{MAPVIEW_IMG_AREA_LIAONING,TXT_LIL_N_DISTRICT_LIAONING}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_JILIN},{MAPVIEW_IMG_AREA_JILIN,TXT_LIL_N_DISTRICT_JILIN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HEILONGJIANG},{MAPVIEW_IMG_AREA_HEILONGJIANG,TXT_LIL_N_DISTRICT_HEILONGJIANG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SHANGHAI},{MAPVIEW_IMG_AREA_SHANGHAI,TXT_LIL_N_DISTRICT_SHANGHAI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_JIANGSU},{MAPVIEW_IMG_AREA_JIANGSU,TXT_LIL_N_DISTRICT_JIANGSU}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_ZHEJIANG},{MAPVIEW_IMG_AREA_ZHEJIANG,TXT_LIL_N_DISTRICT_ZHEJIANG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_ANHUI},{MAPVIEW_IMG_AREA_ANHUI,TXT_LIL_N_DISTRICT_ANHUI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_FUJIAN},{MAPVIEW_IMG_AREA_FUJIAN,TXT_LIL_N_DISTRICT_FUJIAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_JIANGXI},{MAPVIEW_IMG_AREA_JIANGXI,TXT_LIL_N_DISTRICT_JIANGXI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SHANDONG},{MAPVIEW_IMG_AREA_SHANDONG,TXT_LIL_N_DISTRICT_SHANDONG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HENAN},{MAPVIEW_IMG_AREA_HENAN,TXT_LIL_N_DISTRICT_HENAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HUBEI},{MAPVIEW_IMG_AREA_HUBEI,TXT_LIL_N_DISTRICT_HUBEI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HUNAN},{MAPVIEW_IMG_AREA_HUNAN_BRANCH,TXT_LIL_N_DISTRICT_HUNAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_GUANGDONG},{MAPVIEW_IMG_AREA_GUANGDONG,TXT_LIL_N_DISTRICT_GUANGDONG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_GUANGXI},{MAPVIEW_IMG_AREA_GUANGXI,TXT_LIL_N_DISTRICT_GUANGXI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HAINAN},{MAPVIEW_IMG_AREA_HAINAN,TXT_LIL_N_DISTRICT_HAINAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_CHONGQING},{MAPVIEW_IMG_AREA_CHONGQING,TXT_LIL_N_DISTRICT_CHONGQING}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SICHUAN},{MAPVIEW_IMG_AREA_SICHUAN,TXT_LIL_N_DISTRICT_SICHUAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_GUIZHOU},{MAPVIEW_IMG_AREA_GUIZHOU,TXT_LIL_N_DISTRICT_GUIZHOU}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_YUNNAN},{MAPVIEW_IMG_AREA_YUNNAN,TXT_LIL_N_DISTRICT_YUNNAN}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_TIBET},{MAPVIEW_IMG_AREA_TIBET,TXT_LIL_N_DISTRICT_TIBET}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_SHAANXI},{MAPVIEW_IMG_AREA_SHAANXI,TXT_LIL_N_DISTRICT_SHAANXI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_GANSU},{MAPVIEW_IMG_AREA_GANS,TXT_LIL_N_DISTRICT_GANSU}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_QINGHAI},{MAPVIEW_IMG_AREA_QINGHAI,TXT_LIL_N_DISTRICT_QINGHAI}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_NINGXIA},{MAPVIEW_IMG_AREA_NINGXIA,TXT_LIL_N_DISTRICT_NINGXIA}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_XINJIANG},{MAPVIEW_IMG_AREA_XINJIANG,TXT_LIL_N_DISTRICT_XINJIANG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_HONGKONG},{MAPVIEW_IMG_AREA_HONG_KONG,TXT_LIL_N_DISTRICT_HONGKONG}},
                {{MENUMODEL_ITEM_VISABLE, {DEFAULT_SK, DEFAULT_SK, DEFAULT_SK}, MNU_MAPAPP_MACAU},{MAPVIEW_IMG_AREA_MACAO,TXT_LIL_N_DISTRICT_MACAU}} })
        WdgEnd(CLSID_IMGGRID_MENUWIDGET,ThumbImgGrid)
    WndEnd(MAP_WND_THUMB_POI)

ApEnd(RS,CLSID_MAPAPP)


