ApBegin(RS,CLSID_SHORTCUTPHB)

#if defined(__3D_UI_IDLE_MULTIPAGE__)

	WndBegin(SHORTCUTPHB_WND_MAINWND)

        WndSetTitleVisiableRC(FALSE)
	    WndSetStatusBarVisibleRC(VIEWSB_VISIABLE)
        WndSetSoftkeyVisibleRC(VIEWSK_INVISIABLE)

        WdgBegin(CLSID_IMAGEWIDGET,SHORTCUTPHB_WDG_MAINWND_IMG_STATUSBAR)
            WdgImageCreateForWndRC({ {COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_CONTAINER_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_CONTAINER_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_CONTAINER_W ,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_CONTAINER_H}, IMAGE_STYLE_COMMON, {FALSE,IMG_NULL_ID} })
        WdgEnd(CLSID_IMAGEWIDGET,SHORTCUTPHB_WDG_MAINWND_IMG_STATUSBAR)

        WdgBegin(CLSID_BUTTONWIDGET, SHORTCUTPHB_WDG_MAINWND_BTN_CALL)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FIRST_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FIRST_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W ,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IDLE_IMG_CALL_ICON_UNPRESSED,IDLE_IMG_CALL_ICON_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_CALL)

        WdgBegin(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_SEND)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_SECOND_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_SECOND_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W ,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IDLE_IMG_MESSAGE_ICON_UNPRESSED,IDLE_IMG_MESSAGE_ICON_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_SEND)

        WdgBegin(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_DELETE)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_THIRD_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_THIRD_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W ,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IDLE_IMG_DEL_ICON_UNPRESSED,IDLE_IMG_DEL_ICON_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_DELETE)

        WdgBegin(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_BACK)
            WdgButtonCreateForWndRC({{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FOURTH_X,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_FOURTH_Y},{COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_W ,COMMON_LAYOUT_SOFTKEY_FOUR_BUTTON_H},0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,IDLE_IMG_BACK_ICON_UNPRESSED,IDLE_IMG_BACK_ICON_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,SHORTCUTPHB_WDG_MAINWND_BTN_BACK)

    WndEnd(SHORTCUTPHB_WND_MAINWND)

#endif

ApEnd(RS,CLSID_SHORTCUTPHB)

