#ifndef __GTSBOX_DEFS_H__
#define __GTSBOX_DEFS_H__

typedef enum
{
	SCR_ID_GTSBOX_START = GTSBOX_BASE + 1,
	SCR_GTSBOX_GAMELIST,
	SCR_GTSBOX_OU_SCREEN, 
	SCR_GTSBOX_DOWNLOAD, 
	SCR_GTSBOX_APP_FULLSCREEN, 
	SCR_GTSBOX_EXPLAIN,
	SCR_GTSBOX_MENU,
	SCR_ID_GTSBOX_MAX
} SCREENID_LIST_GTSBOX;

typedef enum
{
	//弹弹兔
	STR_ID_GTSBOX_TANTANTU= GTSBOX_BASE + 1,
	//末世战机
	STR_ID_GTSBOX_MOSHIZHANJI,
	//美女麻将
	STR_ID_GTSBOX_MEINVMAJIANG,
	//水晶物语
	STR_ID_GTSBOX_SHUIJINGWUYU,
	//海钓王
	STR_ID_GTSBOX_HAIDIAOWANG,
	 //幻想魔法城堡
	STR_ID_GTSBOX_HUANXIANGMOFA,
 	//回到雅典
	STR_ID_GTSBOX_HUIDAOYADIAN,
	 //魔法大作战
	STR_ID_GTSBOX_MOFABATTLE,
	 //魔箭天使
	STR_ID_GTSBOX_MOJIANTIANSHI,
	//坦克大作战
	STR_ID_GTSBOX_TANKBATTLE,
	//王子传说
	STR_ID_GTSBOX_WANGZICHUANSHUO,
	 //钢铁兄弟连
	STR_ID_GTSBOX_GANGTIE,
	//水晶球
	STR_ID_GTSBOX_SHUIJINGQIU,
	//打地鼠
	STR_ID_GTSBOX_DADISHU,
	//是男人撑过20秒
	STR_ID_GTSBOX_SHINANREN,
	// 贪吃鱼
	STR_ID_GTSBOX_TANCHIYU,
	// 热气球
	STR_ID_GTSBOX_REQIQIU,
	// 贪吃蛇
	STR_ID_GTSBOX_TANCHISHE,
	// 拳皇争霸
	STR_ID_GTSBOX_KOF,
	// 抽签
	STR_ID_GTSBOX_CHOUQIAN,
	// 掷骰子
	STR_ID_GTSBOX_ZHITOUZI,
	// WAP游戏
	STR_ID_GTSBOX_WAPGAME,
	//皇帝的宝藏
	STR_ID_GTSBOX_HUANGDI,
	// 跑酷
	STR_ID_GTSBOX_PAOKU,
	// 疯狂的兔子
	STR_ID_GTSBOX_CRAZYRABIT,
	// 金山词霸
	STR_ID_GTSBOX_CIBA,
	// 新浪微博
	STR_ID_GTSBOX_MBLOG,
	// 淘宝
	STR_ID_GTSBOX_NTB,
	// 小猪快跑
	STR_ID_GTSBOX_PIGRUN,
	// 电线狂奔
	STR_ID_GTSBOX_WIRE,
	// 妄撮
	STR_ID_GTSBOX_WANGCUO,
	//捕鱼达人
	STR_ID_GTSBOX_BUYUDAREN,
	//美女找茬
	STR_ID_GTSBOX_MEINVCHAOCHA,
	//超人
	STR_ID_GTSBOX_CHAOREN,
	//裙舞飞扬
	STR_ID_GTSBOX_CHUIQUNZI,
	//更多精彩内容
	STR_ID_GTSBOX_MORE_CONTENTS,

	STR_ID_GTSBOX_MAX
} STRINGID_LIST_GTSBOX;

typedef enum
{
	//弹弹兔
	IMG_ID_GTSBOX_TANTANTU= GTSBOX_BASE + 1,
	//末世战机
	IMG_ID_GTSBOX_MOSHIZHANJI,
	//美女麻将
	IMG_ID_GTSBOX_MEINVMAJIANG,
	//水晶物语
	IMG_ID_GTSBOX_SHUIJINGWUYU,
	//海钓王
	IMG_ID_GTSBOX_HAIDIAOWANG,
	 //幻想魔法城堡
	IMG_ID_GTSBOX_HUANXIANGMOFA,
 	//回到雅典
	IMG_ID_GTSBOX_HUIDAOYADIAN,
	 //魔法大作战
	IMG_ID_GTSBOX_MOFABATTLE,
	 //魔箭天使
	IMG_ID_GTSBOX_MOJIANTIANSHI,
	//坦克大作战
	IMG_ID_GTSBOX_TANKBATTLE,
	//王子传说
	IMG_ID_GTSBOX_WANGZICHUANSHUO,
	 //钢铁兄弟连
	IMG_ID_GTSBOX_GANGTIE,
	//水晶球
	IMG_ID_GTSBOX_SHUIJINGQIU,
	//打地鼠
	IMG_ID_GTSBOX_DADISHU,
	//是男人撑过20秒
	IMG_ID_GTSBOX_SHINANREN,
	// 贪吃鱼
	IMG_ID_GTSBOX_TANCHIYU,
	// 热气球
	IMG_ID_GTSBOX_REQIQIU,
	// 贪吃蛇
	IMG_ID_GTSBOX_TANCHISHE,
	// 拳皇争霸
	IMG_ID_GTSBOX_KOF,
	// 抽签
	IMG_ID_GTSBOX_CHOUQIAN,
	// 掷骰子
	IMG_ID_GTSBOX_ZHITOUZI,
	// WAP游戏
	IMG_ID_GTSBOX_WAPGAME,
	//皇帝的宝藏
	IMG_ID_GTSBOX_HUANGDI,
	// 跑酷
	IMG_ID_GTSBOX_PAOKU,
	// 疯狂的兔子
	IMG_ID_GTSBOX_CRAZYRABIT,
	// 金山词霸
	IMG_ID_GTSBOX_CIBA,
	// 新浪微博
	IMG_ID_GTSBOX_MBLOG,
	// 淘宝
	IMG_ID_GTSBOX_NTB,
	// 小猪快跑
	IMG_ID_GTSBOX_PIGRUN,
	// 电线狂奔
	IMG_ID_GTSBOX_WIRE,
	// 妄撮
	IMG_ID_GTSBOX_WANGCUO,
	//捕鱼达人
	IMG_ID_GTSBOX_BUYUDAREN,
	//美女找茬
	IMG_ID_GTSBOX_MEINVCHAOCHA,
	//超人
	IMG_ID_GTSBOX_CHAOREN,
	//裙舞飞扬
	IMG_ID_GTSBOX_CHUIQUNZI,
	//更多精彩内容
	IMG_ID_GTSBOX_MORE_CONTENTS,

	IMG_ID_GTSBOX_MAX
} IMAGEID_LIST_GTSBOX;

#define IMG_ICON_GTSBOX_TANTANTU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MOSHIZHANJI CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MEINVMAJIANG CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_SHUIJINGWUYU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_HAIDIAOWANG CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_HUANXIANGMOFA CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_HUIDAOYADIAN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MOFABATTLE CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MOJIANTIANSHI CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_TANKBATTLE CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_WANGZICHUANSHUO CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_GANGTIE CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_SHUIJINGQIU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_DADISHU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_SHINANREN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MORE_CONTENTS CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_TANCHIYU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_REQIQIU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_TANCHISHE CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_KOF CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_CHOUQIAN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_ZHITOUZI CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_WAPGAME CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_HUANGDI CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_PIGRUN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_CRAZYRABIT CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_CIBA CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MBLOG CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_NTB CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_PAOKU CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_WIRE CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_WANGCUO CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_BUYUDAREN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_MEINVCHAOCHA CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_CHAOREN CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"
#define IMG_ICON_GTSBOX_CHUIQUNZI CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM"

#endif
