#ifndef __MMI_TUDOUAPP_ID_H__
#define __MMI_TUDOUAPP_ID_H__

#define TUDOU_PLAYTYPE_CLEAR_INVISIBLE  1

typedef enum
{
    TUDOU_WND_START = WND_ID_APP_BASE,
    TUDOU_WND_HOTSPOT,
    TUDOU_WND_CHANNEL,
    TUDOU_WND_SEARCH,
    TUDOU_WND_DOWNLOAD,
    TUDOU_WND_DOWNLOAD_OPTION,
    TUDOU_WND_VIDEO_DETAIL,
    TUDOU_WND_SETTINGS,
    TUDOU_WND_DUALSIM_SELECT,
    TUDOU_WND_PLAY_TYPE,
} TuDouWndId_e;


typedef enum
{
    TUDOU_WND_START_START_IMGWDG = APP_WDG_START,
    TUDOU_WND_START_ANIM_IMGWDG,
    TUDOU_WND_HOTSPOT_MENUWDG,
    TUDOU_WND_CHANNEL_LIST_MENUWDG,
    TUDOU_WND_VIDEO_LIST_MENUWDG,
    TUDOU_WND_SEARCH_INPUTWDG,
    TUDOU_WND_SEARCH_INPUT_BG_IMGWDG,
    TUDOU_WND_SEARCH_BUTTONWDG,
    TUDOU_WND_SEARCH_POPULAR_TEXTWDG,
    TUDOU_WND_SEARCH_POPULAR_MENUWDG,
    TUDOU_WND_SEARCH_HISTORY_TEXTWDG,
    TUDOU_WND_SEARCH_HISTORY_MENUWDG,
    TUDOU_WND_VIDEO_DETAIL_VIDEO_IMGWDG,
    TUDOU_WND_VIDEO_DETAIL_TITLE_TEXTWDG,
    TUDOU_WND_VIDEO_DETAIL_PLAY_NUM_WDG,
    TUDOU_WND_VIDEO_DETAIL_PLAY_TOTAL_NUM_WDG,
    TUDOU_WND_VIDEO_DETAIL_PLAY_BUTTON_WDG,
    TUDOU_WND_VIDEO_DETAIL_DOWNLOAD_BUTTON_WDG,
    TUDOU_WND_VIDEO_DETAIL_LEVEL_MENU_WDG,
    TUDOU_WND_VIDEO_DETAIL_INTRO_TITLE_TEXTWDG,
    TUDOU_WND_VIDEO_DETAIL_INTRO_TEXTWDG,
    TUDOU_WND_VIDEO_DETAIL_RETURN_BUTTON_BG_IMGWDG,
    TUDOU_WND_VIDEO_DETAIL_RETURN_BUTTON_WDG,
    TUDOU_WND_VIDEO_DETAIL_ONLINE_TEXT_WDG,
    TUDOU_WND_SETTINGS_MFLCONTAINER_WDG,
    TUDOU_WND_SETTINGS_NETWORK_WDG,
    TUDOU_WND_SETTINGS_STORAGE_WDG,
    //TUDOU_WND_SETTINGS_MENU_WDG,
    TUDOU_WND_DOWNLOAD_VIDEO_LIST_MENUWDG,
    TUDOU_WND_EXIT_BUTTON_WDG,
    // #ifdef TUDOU_APP_FEATURE_WAP
    TUDOU_WND_WAP_AREA_TITLE_WDG,
    TUDOU_WND_WAP_VIDEO_TITLE_WDG,
    TUDOU_WND_WAP_VIDEO_2_TITLE_WDG
}TuDouViewWdgId_e;

typedef enum
{
    MNU_TUDOU_HOTSPOT = 0,
    MNU_TUDOU_CHANNEL,
    MNU_TUDOU_SEARCH,
    MNU_TUDOU_DOWNLOAD,
    MNU_TUDOU_SETTINGS,
    MNU_TUDOU_DOWNLOAD_PLAY,
    MNU_TUDOU_DOWNLOAD_STOP,
    MNU_TUDOU_DOWNLOAD_DELETE,
    MNU_TUDOU_DOWNLOAD_START,
    MNU_TUDOU_SETTINGS_NETWORK,
    MNU_TUDOU_SETTINGS_STORAGE,
    MNU_TUDOU_PLAYTYPE_FLUENCY,
    MNU_TUDOU_PLAYTYPE_CLEAR,
}TuDouMenuId_e;

enum
{
    TUDOU_SIM_MASTER = 0,
    TUDOU_SIM_SLAVE = 1,
    TUDOU_SIM_NO_ACTIVE = 2,
    TUDOU_SIM_NO_SIM = 3,
    TUDOU_SIM_UNKNOW = 4
};
typedef u8 TuDouSimID_e;

enum
{
    TUDOU_SEARCH_HOTKEY = 0,
    TUDOU_SEARCH_VIDEO_LIST = 1,
};
typedef u8 TuDouSearchParseType_e;

enum
{
    TUDOU_SEARCH_FOCUS_TYPE_BEGIN = 0,
    TUDOU_SEARCH_FOCUS_TYPE_HOTKEY,
    TUDOU_SEARCH_FOCUS_TYPE_HISTORY,
};
typedef u8 TuDouSearchFocusType_e;

enum
{
    TUDOU_CHANNEL_TYPE = 0,
    TUDOU_CHANNEL_LIST = 1,
};
typedef u8 TuDouChannelParseType_e;

enum
{
    TUDOU_CONNECT_IN_WLAN = 0,
    TUDOU_CONNECT_IN_GPRS = 1,
};
typedef u8 TuDouConnectType_e;

enum
{
    TUDOU_TRANSCODE_ONE = 1,
    TUDOU_TRANSCODE_TWO = 2,
};
typedef u8 TuDouTranscode_e;

typedef enum
{
    TUDOU_ID_NONE = 0,
    TUDOU_ID_STOP_BT,
} TuDouItemID_e;

typedef enum
{
    TUDOU_VT_INITIAL = 0,
    TUDOU_VT_BT,
    TUDOU_VT_CONFIRM_STOP_BT_OPP,
}TuDouAppViewType_e;

typedef enum
{
    TUDOU_VT_INIT_ID = 0,
    TUDOU_VT_LAUNCH_WAP,
    TUDOU_VT_LAUNCH_VIDEO,
}TuDouAppSuspendFreeId_e;

typedef enum
{
    TUDOU_DATALINK_INIT = 0,
    TUDOU_DATALINK_CREATING,
    TUDOU_DATALINK_COMPLETE,
}TuDouAppDataLinkStatus_e;

#endif //__MMI_TUDOUAPP_ID_H__

