ApBegin(RS,CLSID_COUNTDOWNTIMER)
    WndBegin(COUNTDOWNTIMER_WND_SETTIME)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_COUNTDOWN_TIMER})
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_FCTIME_WIDGET,SetTimeWdg)
            WdgFcTimeCreateForWndRC({{COUNTDOWN_TIMER_SETTIMER_XPOS,COUNTDOWN_TIMER_SETTIMER_YPOS},{FC_TIME_WDG_WIDTH,FC_TIME_WDG_HEIGHT},FCTIME_STYLE_COUNTDOWNTIME,{0,1,1,1,0,0,0,0}})
        WdgEnd(CLSID_FCTIME_WIDGET,SetTimeWdg)
#ifdef __IFONE_STYLE_MMI_COUNTDOWN_TIMER__
        WdgBegin(CLSID_TEXTWIDGET,HourTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_HOUR_TEXT_XPOS,COUNTDOWN_TIMER_HOUR_TEXT_YPOS},{COUNTDOWN_TIMER_HOUR_TEXT_WIDTH,COUNTDOWN_TIMER_HOUR_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_COUNTDOWN_HOUR)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,HourTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,MinTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_MIN_TEXT_XPOS,COUNTDOWN_TIMER_MIN_TEXT_YPOS},{COUNTDOWN_TIMER_MIN_TEXT_WIDTH,COUNTDOWN_TIMER_MIN_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_COUNTDOWN_MINUTE)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,MinTextWdg)
#else
        WdgBegin(CLSID_TEXTWIDGET,HourTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_HOUR_TEXT_XPOS,COUNTDOWN_TIMER_HOUR_TEXT_YPOS},{COUNTDOWN_TIMER_HOUR_TEXT_WIDTH,COUNTDOWN_TIMER_HOUR_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_COMMON_HOUR)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
        WdgEnd(CLSID_TEXTWIDGET,HourTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,MinTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_MIN_TEXT_XPOS,COUNTDOWN_TIMER_MIN_TEXT_YPOS},{COUNTDOWN_TIMER_MIN_TEXT_WIDTH,COUNTDOWN_TIMER_MIN_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_COMMON_MIN)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
        WdgEnd(CLSID_TEXTWIDGET,MinTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,SecTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_SEC_TEXT_XPOS,COUNTDOWN_TIMER_SEC_TEXT_YPOS},{COUNTDOWN_TIMER_SEC_TEXT_WIDTH,COUNTDOWN_TIMER_SEC_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_COMMON_SEC)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_CENTER)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
        WdgEnd(CLSID_TEXTWIDGET,SecTextWdg)
#endif
#ifdef __IFONE_STYLE_MMI_COUNTDOWN_TIMER__
        WdgBegin(CLSID_TEXTWIDGET,StartRingTextWdg)
        	WdgTextCreateForWndRC({{COUNTDOWN_TIMER_STARTRING_TEXT_XPOS,COUNTDOWN_TIMER_STARTRING_TEXT_YPOS},{COUNTDOWN_TIMER_STARTRING_TEXT_WIDTH,COUNTDOWN_TIMER_STARTRING_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        	WdgTextSetDataByIDRC(TXT_LIL_N_TIME_EXPIRE_TO_RING)
        	WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        	WdgCommonSetTextColorRC(COLOR_BLACK)
        	WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,StartRingTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,RingNameTextWdg)
        	WdgTextCreateForWndRC({{COUNTDOWN_TIMER_RINGNAME_TEXT_XPOS,COUNTDOWN_TIMER_RINGNAME_TEXT_YPOS},{COUNTDOWN_TIMER_RINGNAME_TEXT_WIDTH,COUNTDOWN_TIMER_RINGNAME_TEXT_HEIGHT},TEXT_STYLE_COMMON})
        	WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|COUNTDOWN_TIMER_RINGNAME_TEXT_H_ALIGN)
        	WdgCommonSetTextColorRC(COLOR_BLACK)
        	WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,RingNameTextWdg)

        WdgBegin(CLSID_BUTTONWIDGET,StartButtonWdg)
        	WdgButtonCreateForWndRC({{COUNTDOWN_POS_STARTBUTTON_XPOS,COUNTDOWN_POS_STARTBUTTON_YPOS},{COUNTDOWN_TIMER_BUTTON_WIDTH,COUNTDOWN_TIMER_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_LIL_N_START,COUNTDOWN_IMG_START_UNPRESSED,COUNTDOWN_IMG_START_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, StartButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,StopButtonWdg)
        	WdgButtonCreateForWndRC({{COUNTDOWN_POS_STARTBUTTON_XPOS,COUNTDOWN_POS_STARTBUTTON_YPOS},{COUNTDOWN_TIMER_BUTTON_WIDTH,COUNTDOWN_TIMER_BUTTON_HEIGHT},0})
            WdgButtonSetDataByIDRC({TXT_LIL_N_STOP,COUNTDOWN_IMG_STOP_UNPRESSED,COUNTDOWN_IMG_STOP_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET, StopButtonWdg)
        WdgBegin(CLSID_BUTTONWIDGET,StartRingWdg)
        	WdgButtonCreateForWndRC({{COUNTDOWN_POS_STARTRING_XPOS,COUNTDOWN_POS_STARTRING_YPOS},{COUNTDOWN_TIMER_BUTTON_WIDTH,COUNTDOWN_TIMER_BUTTON_HEIGHT},0})
        	WdgButtonSetDataByIDRC({TXT_NULL_ID,COUNTDOWN_BUTTON_START_RING_UNPRESSED,COUNTDOWN_BUTTON_START_RING_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,StartRingWdg)
#endif
#else
        WdgBegin(CLSID_TEXTWIDGET,TimeTextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_TEXT_XPOS,COUNTDOWN_TIMER_TEXT_YPOS},{COUNTDOWN_TIMER_TEXT_WIDTH,COUNTDOWN_TIMER_TEXT_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_TIMETEXT)
            WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_LEFT)
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,TimeTextWdg)
        WdgBegin(CLSID_TEXTWIDGET,InputWdg)
            WdgInputCreateForWndRC({{COUNTDOWN_TIMER_INPUT_XPOS,COUNTDOWN_TIMER_INPUT_YPOS},{COUNTDOWN_TIMER_INPUT_WIDTH,COUNTDOWN_TIMER_INPUT_HEIGHT},TEXT_STYLE_COMMON})
	     #ifdef __LCM_QQVGA_MMI__
	     WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_CENTER)
	     #else
			WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_LEFT)
	     #endif
            WdgCommonSetTextColorRC(COLOR_BLACK)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
        WdgEnd(CLSID_TEXTWIDGET,InputWdg)
#endif
    WndEnd(COUNTDOWNTIMER_WND_SETTIME)

#ifdef __IFONE_STYLE_MMI_COUNTDOWN_TIMER__
    WndBegin(COUNTDOWNTIMER_WND_SETRINGTONE)
        WdgBegin(CLSID_VTMMENU,CountDownSelect)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            WdgStaticMenuItemRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_USE_SYSTEM_FILE, TXT_LIL_N_USE_SYSTEM_FILE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SELECT_FILE, TXT_LIL_N_SELECT_FILE} })
        WdgEnd(CLSID_VTMMENU,CountDownSelect)
    WndEnd(COUNTDOWNTIMER_WND_SETRINGTONE)
#endif

    WndBegin(COUNTDOWNTIMER_WND_COUNTDOWN)
        WndSetTitleRC({IMG_NULL_ID,TXT_LIL_N_COUNTDOWN_TIMER})
        WdgBegin(CLSID_TEXTWIDGET,TextWdg)
            WdgTextCreateForWndRC({{COUNTDOWN_TIMER_RUNNING_TIME_XPOS,COUNTDOWN_TIMER_RUNNING_TIME_YPOS},{MAIN_DEFVIEW_WIDTH,MAIN_LCD_ONELINE_HEIGHT},TEXT_STYLE_COMMON})
            #ifdef __LCM_QQVGA_MMI__
            WdgCommonSetAlignmentRC(ALIGN_V_TOP|ALIGN_H_CENTER)
            #else
						WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
            #endif

            WdgCommonSetTextColorRC(COLOR_WHITE)
#ifdef __LCM_QQVGA_MMI__
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_NORMAL)
#else
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_LARGE)
#endif
        WdgEnd(CLSID_TEXTWIDGET,TextWdg)
    WndEnd(COUNTDOWNTIMER_WND_COUNTDOWN)
ApEnd(RS,CLSID_COUNTDOWNTIMER)

