#ifndef __MMI_EVTCENTERAPP_ID_H__
#define __MMI_EVTCENTERAPP_ID_H__

typedef enum
{
    EVTCENTER_WND_ALL_EVT_SUMMARY = WND_ID_APP_BASE,
    EVTCENTER_WND_SYS_EVT_SUMMARY,
    EVTCENTER_WND_SYS_EVT_OPTION_MENU,
    EVTCENTER_WND_DETAIL
} EvtCenterAppWndId_e;

typedef enum
{
    EVTCENTER_WND_ALL_EVT_SUMMARY_MENU = APP_WDG_START,
	EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE01,
	EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE02,
	EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE03,
	EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE04,
    EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE05,
    EVTCENTER_WND_ALL_EVT_SUMMARY_IMAGE06,
	EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT01,
	EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT02,
	EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT03,
	EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT04,
    EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT05,
    EVTCENTER_WND_ALL_EVT_SUMMARY_TEXT06,
}AllEvtSummaryWndView_e;

typedef enum
{
    EVTCENTER_WND_DETAIL_TITLE = APP_WDG_START,
    EVTCENTER_WND_DETAIL_PROP_CNTR,
    EVTCENTER_WND_DETAIL_DATETIME_TEXT,
    EVTCENTER_WND_DETAIL_INFO_TEXT,
}DetailWndWdgView_e;

typedef enum
{
	MNU_EVTCENTER_MAIN_MENU = 0,
	MNU_EVTCENTER_MODEL_SMS,
	MNU_EVTCENTER_MODEL_CB,
	MNU_EVTCENTER_MODEL_VOICEMAIL,
	MNU_EVTCENTER_MODEL_ALARMCALENDAR,
	MNU_EVTCENTER_MODEL_BATTERY,
	MNU_EVTCENTER_MODEL_OTHER,
	MNU_EVTCENTER_OPT_MENU,
	MNU_EVTCENTER_ITEM_VIEW_DETAIL,
	MNU_EVTCENTER_ITEM_DELETE,
	MNU_EVTCENTER_ITEM_DELETE_ALL,
}EvtcenterMenuId_e;

#endif //__MMI_EVTCENTERAPP_ID_H__

