#include "mmi_settingapp_view_id.h"

ApBegin(RS,CLSID_SETTINGAPP)
    WndBegin(SETTINGAPP_WND_GENERAL)
        WdgBegin(CLSID_VTMMENU,GeneralVtm)
            WdgMenuItemTextRC(9, { TXT_LIL_N_PERSONALIZATION, TXT_LIL_N_DATE_TIME, TXT_LIL_N_PROFILES, TXT_LIL_N_GSENSOR, TXT_LIL_N_POWER_ONOFF, TXT_LIL_N_POWER_SWITCH, TXT_LIL_N_INFORMATION, TXT_LIL_N_SECURITY, TXT_LIL_N_RESTORE_SETTINGS })
            WdgDynamicMenuItemInfRC(9, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_DATE_TIME, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_MAIN_PROFILES, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_OFF, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_POWER_SWITCH_SETTINGS, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_INFORMATION, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SEC_SECURITY, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_RESTORE_SETTINGS, SET_Info} })
        WdgEnd(CLSID_VTMMENU,GeneralVtm)
	WndEnd(SETTINGAPP_WND_GENERAL)

	WndBegin(SETTINGAPP_WND_PHONE)
        WdgBegin(CLSID_VTMMENU,PhoneVtm)
            WdgMenuItemTextRC(7, { TXT_LIL_N_CALL_SETTINGS, TXT_LIL_N_CALL_DIVERT, TXT_LIL_N_CALL_BARRING, TXT_LIL_N_NETWORK_SETTINGS, TXT_LIL_N_SWITCH_MODE, TXT_LTL_N_DEFAULT_SIM, TXT_LIL_N_SPEED_DIAL })
            WdgDynamicMenuItemInfRC(7, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CS_CALL_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CS_CALL_DIVERT, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_CS_CALL_BARRING, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_NETWORK_NETWORK_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SWITCH_MODE, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_DEFAULT_SIM, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SPEED_DIAL, SET_LaunchAP} })
        WdgEnd(CLSID_VTMMENU,PhoneVtm)
	WndEnd(SETTINGAPP_WND_PHONE)

	WndBegin(SETTINGAPP_WND_CONNECT)
        WdgBegin(CLSID_VTMMENU,ConnectVtm)
            WdgMenuItemTextRC(13, { TXT_LIL_N_CONNECT_SETTING, TXT_LIL_N_DATA_ACCOUNTS, TXT_LIL_N_WAP_SETTING, TXT_LIL_N_MMS_SETTING,  TXT_LIL_N_JAVA_SETTING, TXT_LIL_N_LBS_SETTING, TXT_LIL_N_WLAN_SETTING, TXT_LIL_N_EMAIL_SETTING, TXT_LIL_N_NTP_SETTING, TXT_LIL_N_QQ_SETTING, TXT_LIL_N_STREAMING_SETTING, TXT_LIL_N_NETWORK_COUNTER, TXT_LIL_N_OTHER_SETTING })
            WdgDynamicMenuItemInfRC(13, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_CONNECT_SETTING, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_DATA_ACCOUNTS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_WAP_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_MMS_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_JAVA_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_LBS_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_WLAN_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_EMAIL_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_NTP_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_QQ_SETTINGS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_STREAMING_SETTINGS, SET_LaunchAP},     
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_NETWORK_COUNTER, SET_LaunchAP},                                                            
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_OTHER_SETTINGS, SET_LaunchAP} })
        WdgEnd(CLSID_VTMMENU,ConnectVtm)
	WndEnd(SETTINGAPP_WND_CONNECT)

#ifdef __APP_MMI_SOHU_UPDATER__
	WndBegin(SETTINGAPP_WND_PERSONALIZATION)
        WdgBegin(CLSID_VTMMENU,PersonalizationVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(7, { TXT_LIL_N_DISPLAY, TXT_LIL_N_RINGTONE_SETTINGS, TXT_LIL_N_LANGUAGE, TXT_LIL_N_NAVIGATION_KEYS, TXT_LIL_N_BREATHLIGHT, TXT_LIL_N_SOGO_UPDATER, TXT_LIL_N_SETTINGAPP_CHANGE_THEME })
            WdgDynamicMenuItemInfRC(7, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_DISPLAY, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_RINGTONE_SETTINGS, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_LANGUAGE, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SHORTCUTS_KEY_ASSIGNMENT, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_BREATHLIGHT, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SOHU_UPDATER, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_CHANGE_THEME_STYLE, SET_OptionList}})
        WdgEnd(CLSID_VTMMENU,PersonalizationVtm)
	WndEnd(SETTINGAPP_WND_PERSONALIZATION)
#else
	WndBegin(SETTINGAPP_WND_PERSONALIZATION)
        WdgBegin(CLSID_VTMMENU,PersonalizationVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_DISPLAY, TXT_LIL_N_RINGTONE_SETTINGS, TXT_LIL_N_LANGUAGE, TXT_LIL_N_NAVIGATION_KEYS, TXT_LIL_N_BREATHLIGHT, TXT_LIL_N_SETTINGAPP_CHANGE_THEME })
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_DISPLAY, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_RINGTONE_SETTINGS, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_LANGUAGE, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SHORTCUTS_KEY_ASSIGNMENT, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_PERSONALIZATION_BREATHLIGHT, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_CHANGE_THEME_STYLE, SET_OptionList}})
        WdgEnd(CLSID_VTMMENU,PersonalizationVtm)
	WndEnd(SETTINGAPP_WND_PERSONALIZATION)
#endif

    WndBegin(SETTINGAPP_WND_DISPLAY)            
        WdgBegin(CLSID_VTMMENU,DisplayVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(12, { TXT_LIL_N_MAIN_MENU_STYLE, TXT_LIL_N_FONT_STYLE, TXT_LTL_N_CALIBRATION, TXT_LIL_N_TRANSITION, TXT_LIL_N_SCREENSAVER, TXT_LIL_N_BACKLIGHT, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE, TXT_LIL_N_WALLPAPER,TXT_LIL_N_MAINMENU_DISPLAY ,TXT_LIL_N_SCREENEFFECT,TXT_LIL_N_KEYGUARD_WALLPAPER, TXT_LIL_N_OPERATOR_NAME})
            WdgDynamicMenuItemInfRC(12, {         
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MAIN_MENU_LAYOUT, SET_Info},
							  {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_FONT_STYLE, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_CALIBRATION, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_TRANSITION, SET_MenuList},                     
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_SAVER, SET_MenuList},                           
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_BACKLIGHT, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE, SET_OptionList},
#ifdef __LIVE_WALLPAPER__
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_IDLE_SCREEN_WALLPAPER, SET_OptionList},
#else
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_IDLE_SCREEN_WALLPAPER, SET_LaunchFileMgrAP},
#endif
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MAINMENU_IMG_SETTING, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_LOCK_WALLPAPER, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_OPERATOR_NAME, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,DisplayVtm)
    WndEnd(SETTINGAPP_WND_DISPLAY)

	WndBegin(SETTINGAPP_WND_RINGTONE)
        WdgBegin(CLSID_VTMMENU,RingToneVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(13, { TXT_LIL_N_VIBRATE, TXT_LIL_N_VOLUME, TXT_LIL_N_VOICE_CALLS, TXT_LIL_N_POWER_ON_TONE, TXT_LIL_N_POWER_ON_TONE ,TXT_LIL_N_POWER_OFF_TONE, TXT_LIL_N_POWER_OFF_TONE, TXT_LIL_N_MESSAGE, TXT_LIL_N_CALENDAR, TXT_LIL_N_ALARM, TXT_LIL_N_MISS_EVENT_REMINDER, TXT_LIL_N_KEYPAD_TONE, TXT_LIL_N_SLIDE_TONE })
            WdgDynamicMenuItemInfRC(13, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VIBRATE_TYPE, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOLUME, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOICE_CALLS, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_TONE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_SETTING, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_OFF_TONE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_OFF_SETTING, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MESSAGING, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_CALENDAR, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_ALARM, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MISS_EVENT_REMINDER, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_KEYPAD_TONE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SLIDE_TONE, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,RingToneVtm)
	WndEnd(SETTINGAPP_WND_RINGTONE)


	WndBegin(SETTINGAPP_WND_POWERON_RINGTONE)
        WdgBegin(CLSID_VTMMENU,PowerOnRingToneVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE,TXT_LIL_N_POWER_ON_TONE})
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_RINGTONE, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_TONE, SET_SOption}
							  })
        WdgEnd(CLSID_VTMMENU,PowerOnRingToneVtm)
	WndEnd(SETTINGAPP_WND_POWERON_RINGTONE)

	WndBegin(SETTINGAPP_WND_POWEROFF_RINGTONE)
        WdgBegin(CLSID_VTMMENU,PowerOffRingToneVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE,TXT_LIL_N_POWER_OFF_TONE})
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_OFF_RINGTONE, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_POWER_OFF_TONE, SET_SOption}
							  })
        WdgEnd(CLSID_VTMMENU,PowerOffRingToneVtm)
	WndEnd(SETTINGAPP_WND_POWEROFF_RINGTONE)



#ifdef __DUAL_PROFILE_MMI__
	WndBegin(SETTINGAPP_WND_VOICECALL)
        WdgBegin(CLSID_VTMMENU,VoiceCallVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_SIM1_DEFAULT_RINGTONE,TXT_LIL_N_SIM2_DEFAULT_RINGTONE, TXT_LIL_N_RING_TYPE })
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOICE_CALLS_MELODY, SET_LaunchFileMgrAP},
			      			  {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SIM2_VOICE_CALLS_MELODY, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOICE_CALLS_RINGING_TYPE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,VoiceCallVtm)
	WndEnd(SETTINGAPP_WND_VOICECALL)

	WndBegin(SETTINGAPP_WND_MESSAGE)
        WdgBegin(CLSID_VTMMENU,MessageVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_SIM1_DEFAULT_RINGTONE,TXT_LIL_N_SIM2_DEFAULT_RINGTONE, TXT_LIL_N_MSG_TONE })
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MESSAGE_MELODY, SET_LaunchFileMgrAP},
			      			  {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SIM2_MESSAGE_MELODY, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MESSAGE_TONE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,MessageVtm)
	WndEnd(SETTINGAPP_WND_MESSAGE)
#else
	WndBegin(SETTINGAPP_WND_VOICECALL)
        WdgBegin(CLSID_VTMMENU,VoiceCallVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE, TXT_LIL_N_RING_TYPE })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOICE_CALLS_MELODY, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_VOICE_CALLS_RINGING_TYPE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,VoiceCallVtm)
	WndEnd(SETTINGAPP_WND_VOICECALL)

	WndBegin(SETTINGAPP_WND_MESSAGE)
        WdgBegin(CLSID_VTMMENU,MessageVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE, TXT_LIL_N_MSG_TONE })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MESSAGE_MELODY, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MESSAGE_TONE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,MessageVtm)
	WndEnd(SETTINGAPP_WND_MESSAGE)
#endif
	WndBegin(SETTINGAPP_WND_CALENDAR)
        WdgBegin(CLSID_VTMMENU,CalendarVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE, TXT_LIL_N_CAL_TONE })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_CALENDAR_MELODY, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_CALENDAR_TONE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,CalendarVtm)
	WndEnd(SETTINGAPP_WND_CALENDAR)

	WndBegin(SETTINGAPP_WND_ALARM)
        WdgBegin(CLSID_VTMMENU,AlarmVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_DEFAULT_RINGTONE, TXT_LIL_N_ALARM_TONE })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_ALARM_MELODY, SET_LaunchFileMgrAP}, \
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_ALARM_TONE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,AlarmVtm)
	WndEnd(SETTINGAPP_WND_ALARM)

	WndBegin(SETTINGAPP_WND_TRANSITION)
        WdgBegin(CLSID_VTMMENU,TransitionVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(1,  TXT_LIL_N_MENU_TRANSITION )
            WdgDynamicMenuItemInfRC(1, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_MENU_TRANSITION, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,TransitionVtm)
	WndEnd(SETTINGAPP_WND_TRANSITION)

	WndBegin(SETTINGAPP_WND_BACKLIGHT)
        WdgBegin(CLSID_VTMMENU,BackLightVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_BACKLIGHT_LEVEL, TXT_LIL_N_BACKLIGHT_DURATION })
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_BACKLIGHT_LEVEL, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_BACKLIGHT_DURATION, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,BackLightVtm)
	WndEnd(SETTINGAPP_WND_BACKLIGHT)

	WndBegin(SETTINGAPP_WND_DATETIME)
        WdgBegin(CLSID_VTMMENU,DateTimeVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(8, { TXT_LIL_N_TIME, TXT_LIL_N_TIME_ZONE, TXT_LIL_N_SECOND_TIME, TXT_LIL_N_TIME_FORMAT, TXT_LIL_N_DATE, TXT_LIL_N_DATE_FORMAT, TXT_LIL_N_DAYLIGHT_SAVING_TIME, TXT_LIL_N_LUNAR_CALENDAR })
            WdgDynamicMenuItemInfRC(8, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_TIME_, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_TIME_ZONE, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SECOND_TIME_ZONE, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_TIME_FORMAT, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_DATE, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_DATE_FORMAT, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_DAYLIGHT_SAVING_TIME, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_LUNAR_CALENDAR, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,DateTimeVtm)
	WndEnd(SETTINGAPP_WND_DATETIME)

	WndBegin(SETTINGAPP_WND_TIMEZONE)
        WdgBegin(CLSID_VTMMENU,TimeZoneVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_FIRST, TXT_LIL_N_SECOND, TXT_LIL_N_AUTOMATIC_UPDATE })
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_FIRST, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SECOND, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_AUTOMATIC_UPDATE, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,TimeZoneVtm)
	WndEnd(SETTINGAPP_WND_TIMEZONE)

	WndBegin(SETTINGAPP_WND_SECONDTIME)
        WdgBegin(CLSID_VTMMENU,SecondTimeVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, {TXT_LIL_N_SECOND, TXT_LIL_N_CITY})
            WdgDynamicMenuItemInfRC(2, {
    						  {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SECOND_TIME, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SECOND, SET_LaunchAP}})
        WdgEnd(CLSID_VTMMENU,SecondTimeVtm)
	WndEnd(SETTINGAPP_WND_SECONDTIME)

	WndBegin(SETTINGAPP_WND_POWERONOFF)
        WdgBegin(CLSID_VTMMENU,PowerOnOffVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(4, { TXT_LIL_N_POWER_ON,TXT_LIL_N_POWER_OFF,TXT_LIL_N_AUTO_ONOFF, TXT_LIL_N_SLIDE_TO_POWER_OFF })
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_POWER_ON_ANIMATION, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_POWER_OFF_ANIMATION, SET_LaunchFileMgrAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_AUTO_ON_OFF, SET_MenuList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SLIDE_TO_POWER_OFF, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,PowerOnOffVtm)
	WndEnd(SETTINGAPP_WND_POWERONOFF)

	WndBegin(SETTINGAPP_WND_AUTOONOFF)
        WdgBegin(CLSID_VTMMENU,AutoOnOffVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(4, { TXT_LIL_N_AUTO_POWER_ON, TXT_LIL_N_STATUS, TXT_LIL_N_AUTO_POWER_OFF, TXT_LIL_N_STATUS })
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_AUTO_POWER_ON_TIME, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_AUTO_POWER_ON_STATUS, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_AUTO_POWER_OFF_TIME, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_AUTO_POWER_OFF_STATUS, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,AutoOnOffVtm)
	WndEnd(SETTINGAPP_WND_AUTOONOFF)

	WndBegin(SETTINGAPP_WND_INFORMATION)
        WdgBegin(CLSID_VTMMENU,InformationVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_IMEI, TXT_LIL_N_MEMORY_DETAILS, TXT_LIL_N_SOFTWARE_VERSION })
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_IMEI, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_MEMORY_DETAILS, SET_LaunchAP},
                              {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, MNU_SETTING_SOFTWARE_VERSION, SET_Info} })
        WdgEnd(CLSID_VTMMENU,InformationVtm)
	WndEnd(SETTINGAPP_WND_INFORMATION)

	WndBegin(SETTINGAPP_WND_LANGUAGE)
        WdgBegin(CLSID_VTMMENU,LanguageVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_LANGUAGE, TXT_LIL_N_WRITING_LANGUAGE, TXT_LIL_N_DEFAULT_INPUT_METHOD, TXT_LIL_N_ENCODING_METHOD, TXT_OIL2_N_SMARTINPUT_ON_OFF, TXT_OIL2_N_SOFT_KEYBOARD })
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_LANGUAGE, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_WRITING_LANGUAGE, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_DEFAULT_INPUT_METHOD, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_ENCODING_METHOD, SET_Info},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SMARTINPUT_ON_OFF, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SOFT_KEYBOARD_ON_OFF, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,LanguageVtm)
    WndEnd(SETTINGAPP_WND_LANGUAGE)

    WndBegin(SETTINGAPP_WND_BKLLEVEL)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_TEXTWIDGET,Title2Txt)
            WdgTextCreateForWndRC({{0,SETTINGAPP_LAYOUT_BACKLIGHT_LAYOUT_POS_Y},{MAIN_LCD_WIDTH,MAIN_LCD_ONELINE_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_BACKLIGHT_LEVEL)
        WdgEnd(CLSID_TEXTWIDGET,Title2Txt)

        WdgBegin(CLSID_IMAGEWIDGET,BackgroundImgWidget)
            WdgImageCreateForWndRC({{0,SETTINGAPP_LAYOUT_BACKLIGHT_LAYOUT_POS_Y},{MAIN_LCD_WIDTH,SETTINGAPP_RS_BGIMG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,COMMON_IMG_SYSTEM_BG}})
            WdgImageSetDataByIDRC(COMMON_IMG_SYSTEM_BG)
        WdgEnd(CLSID_IMAGEWIDGET,BackgroundImgWidget)

        WdgBegin(CLSID_IMAGEWIDGET,ImgWidget)
            WdgImageCreateForWndRC({{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_POS_X,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_POS_Y+SETTINGAPP_LAYOUT_BACKLIGHT_LAYOUT_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,SETTINGS_IMG_BACKLIGHT_LEV_0}})
            WdgImageSetDataByIDRC(SETTINGS_IMG_BACKLIGHT_LEV_0)
        WdgEnd(CLSID_IMAGEWIDGET,ImgWidget)
#else
        WdgBegin(CLSID_IMAGEWIDGET,SettingImgWidget)
            WdgImageCreateForWndRC({{SETTINGAPP_LAYOUT_SETTINGIMGWIDGET_POS_X,SETTINGAPP_LAYOUT_SETTINGIMGWIDGET_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,SETTINGS_IMG_BACKLIGHT_LEV_0}})
            WdgImageSetDataByIDRC(SETTINGS_IMG_BACKLIGHT_LEV_0)
        WdgEnd(CLSID_IMAGEWIDGET,SettingImgWidget)
        WdgBegin(CLSID_HORZ_MENUWIDGET,SettingMenuWdg)
            WdgMenuCreateForWndRC({{SETTINGAPP_LAYOUT_SETTINGMENUWIDGET_POS_X,SETTINGAPP_LAYOUT_SETTINGMENUWIDGET_POS_Y},{SETTINGAPP_LAYOUT_SETTINGMENUWIDGET_WIDTH,SETTINGAPP_LAYOUT_SETTINGMENUWIDGET_HEIGHT},WDG_MENU_TYPE_HORZ})
            WdgMenuSetColGapRC(0)
        WdgEnd(CLSID_HORZ_MENUWIDGET,SettingMenuWdg)
        WdgBegin(CLSID_TEXTWIDGET,SettingBKLTextWdg)
            WdgMenuCreateForWndRC({{SETTINGAPP_LAYOUT_SETTINGBKLTEXTWIDGET_POX_X,SETTINGAPP_LAYOUT_SETTINGBKLTEXTWIDGET_POX_Y},{SETTINGAPP_LAYOUT_SETTINGBKLTEXTWIDGET_WIDTH,SETTINGAPP_LAYOUT_SETTINGBKLTEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
        WdgEnd(CLSID_TEXTWIDGET,SettingBKLTextWdg)
#endif
        WdgBegin(CLSID_BUTTONWIDGET,DecreaseButtonWidget)
#ifndef __APP_MMI_SMALLROM__
            WdgButtonCreateForWndRC({{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_POS_X,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_POS_Y+SETTINGAPP_LAYOUT_BACKLIGHT_LAYOUT_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_HEIGHT},0})
#else
            WdgButtonCreateForWndRC({{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_POS_X,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_DECREASE_HEIGHT},0})
#endif
            WdgButtonSetDataByIDRC({TXT_NULL_ID,SETTINGS_IMG_BACKLIGHT_DECREASE,SETTINGS_IMG_BACKLIGHT_DECREASE})
        WdgEnd(CLSID_BUTTONWIDGET,DecreaseButtonWidget)

        WdgBegin(CLSID_BUTTONWIDGET,IncreaseButtonWidget)
#ifndef __APP_MMI_SMALLROM__
            WdgButtonCreateForWndRC({{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_POS_X,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_POS_Y+SETTINGAPP_LAYOUT_BACKLIGHT_LAYOUT_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_HEIGHT},0})
#else
            WdgButtonCreateForWndRC({{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_POS_X,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_POS_Y},{SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_WIDTH,SETTINGAPP_LAYOUT_BACKLIGHT_LEVEL_INCREASE_HEIGHT},0})
#endif
            WdgButtonSetDataByIDRC({TXT_NULL_ID,SETTINGS_IMG_BACKLIGHT_INCREASE,SETTINGS_IMG_BACKLIGHT_INCREASE})
        WdgEnd(CLSID_BUTTONWIDGET,IncreaseButtonWidget)
    WndEnd(SETTINGAPP_WND_BKLLEVEL)

    WndBegin(SETTINGAPP_WND_DATE)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_DATE})
        WdgBegin(CLSID_VTMMENU,DateVtm)
            VtmCreateDateInputRC({IMG_NULL_ID,TXT_LIL_N_DATE,0,0,0})
        WdgEnd(CLSID_VTMMENU,DateVtm)

        WdgBegin(CLSID_TEXT_DATE_WIDGET,TextDateWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_DATE})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_DATE, {0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_DATE_WIDGET,TextDateWidget)
    WndEnd(SETTINGAPP_WND_DATE)

    WndBegin(SETTINGAPP_WND_TIME)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_TIME})
        WdgBegin(CLSID_VTMMENU,TimeVtm)
            VtmCreateTimeInputRC({IMG_NULL_ID,TXT_LIL_N_TIME,0,0,0})
        WdgEnd(CLSID_VTMMENU,TimeVtm)

        WdgBegin(CLSID_TEXT_TIME_WIDGET,TextTimeWidget)
            WdgDoubleItemCreateForWndRC({{0,0},{0,0},DOUBLEITEM_STYLE_TEXT_TIME})
            WdgDoubleItemTextDateSetDataByIDRC({TXT_LIL_N_TIME, {0,0,0,0,0,0,0,0}})
        WdgEnd(CLSID_TEXT_TIME_WIDGET,TextTimeWidget)
    WndEnd(SETTINGAPP_WND_TIME)

    WndBegin(SETTINGAPP_WND_VOLUME)
        WndSetAllSoftkeyRC({SK_OK_TEXT, SK_OK, SK_CANCEL})
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_VOLUME})
#ifdef 	__APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,VolumeBGImageWidget)
            WdgImageCreateForWndRC({{SETTINGAPP_LAYOUT_VOLUME_BGIMAGEWIDGET_POS_X,SETTINGAPP_LAYOUT_VOLUME_BGIMAGEWIDGET_POS_Y},{SETTINGAPP_LAYOUT_VOLUME_BGIMAGEWIDGET_WIDTH,SETTINGAPP_LAYOUT_VOLUME_BGIMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,NOTICE_IMG_BG}})
            WdgImageSetDataByIDRC(NOTICE_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeBGImageWidget)
#endif
    WndEnd(SETTINGAPP_WND_VOLUME)

    WndBegin(SETTINGAPP_WND_FONTSTYLE)
        WdgBegin(CLSID_VTMMENU,FontStyleVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,FontStyleVtm)
    WndEnd(SETTINGAPP_WND_FONTSTYLE)
    
    WndBegin(SETTINGAPP_WND_DISPLAYLANG)
        WdgBegin(CLSID_VTMMENU,DisplayLangVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,DisplayLangVtm)
    WndEnd(SETTINGAPP_WND_DISPLAYLANG)

    WndBegin(SETTINGAPP_WND_VIBRATETYPE)
        WdgBegin(CLSID_VTMMENU,VibrateVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_VIBRATE_ON, TXT_LIL_N_VIBRATE_OFF, TXT_LIL_N_VIBRATE_THEN_RING})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_VIBRATE_ON, VIBRATE_TYPE_VIBRATE_ON},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_VIBRATE_OFF, VIBRATE_TYPE_VIBRATE_OFF},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_VIBRATE_THEN_RING, VIBRATE_TYPE_VIBRATE_THEN_RING} })
        WdgEnd(CLSID_VTMMENU,VibrateVtm)
	WndEnd(SETTINGAPP_WND_VIBRATETYPE)

	WndBegin(SETTINGAPP_WND_VOICECALLSRINGINGTYPE)
        WdgBegin(CLSID_VTMMENU,VoiceCallsRingVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(4, { TXT_LIL_N_RINGING, TXT_LIL_N_RING_ONCE, TXT_LIL_N_BEEP, TXT_LIL_N_SILENT})
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_RINGING_TYPE_RINGING, RING_TYPE_RINGING},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_RINGING_TYPE_RING_ONCE, RING_TYPE_RING_ONCE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_RINGING_TYPE_BEEP_ONCE, RING_TYPE_BEEP},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_RINGING_TYPE_SILENT, RING_TYPE_SILENT} })
        WdgEnd(CLSID_VTMMENU,VoiceCallsRingVtm)
	WndEnd(SETTINGAPP_WND_VOICECALLSRINGINGTYPE)

	WndBegin(SETTINGAPP_WND_MESSAGETONE)
        WdgBegin(CLSID_VTMMENU,MessageToneVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_ON, TXT_LIL_N_OFF, TXT_LIL_N_BEEP})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_ON, MESSAGE_TONE_ON},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_OFF, MESSAGE_TONE_OFF},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_BEEP, MESSAGE_TONE_BEEP} })
        WdgEnd(CLSID_VTMMENU,MessageToneVtm)
	WndEnd(SETTINGAPP_WND_MESSAGETONE)

	WndBegin(SETTINGAPP_WND_CALENDARTONE)
        WdgBegin(CLSID_VTMMENU,CalendarToneVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_ON, TXT_LIL_N_OFF, TXT_LIL_N_BEEP})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_ON, MESSAGE_TONE_ON},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_OFF, MESSAGE_TONE_OFF},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_BEEP, MESSAGE_TONE_BEEP} })
        WdgEnd(CLSID_VTMMENU,CalendarToneVtm)
	WndEnd(SETTINGAPP_WND_CALENDARTONE)

	WndBegin(SETTINGAPP_WND_ALARMTONE)
        WdgBegin(CLSID_VTMMENU,AlarmToneVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_ON, TXT_LIL_N_OFF, TXT_LIL_N_BEEP})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_ON, MESSAGE_TONE_ON},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_OFF, MESSAGE_TONE_OFF},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_COM_ONOFFBEEP_BEEP, MESSAGE_TONE_BEEP} })
        WdgEnd(CLSID_VTMMENU,AlarmToneVtm)
	WndEnd(SETTINGAPP_WND_ALARMTONE)

	WndBegin(SETTINGAPP_WND_BACKLIGHTDURATION)
        WdgBegin(CLSID_VTMMENU,BackLightDurationVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_5_SECONDS, TXT_LIL_N_10_SECONDS, TXT_LIL_N_15_SECONDS, TXT_LIL_N_20_SECONDS, TXT_LIL_N_30_SECONDS, TXT_LIL_N_60_SECONDS})
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_5_SECONDS, BACKLIGHT_DURATION_5SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_10_SECONDS, BACKLIGHT_DURATION_10SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_15_SECONDS, BACKLIGHT_DURATION_15SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_20_SECONDS, BACKLIGHT_DURATION_20SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_30_SECONDS, BACKLIGHT_DURATION_30SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_BACKLIGHT_DURATION_60_SECONDS, BACKLIGHT_DURATION_60SECS} })
        WdgEnd(CLSID_VTMMENU,BackLightDurationVtm)
	WndEnd(SETTINGAPP_WND_BACKLIGHTDURATION)

	WndBegin(SETTINGAPP_WND_AUTOMATICUPDATE)
        WdgBegin(CLSID_VTMMENU,AutomaticUpdateVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_ON, TXT_LIL_N_OFF, TXT_LIL_N_CONFIRM_FIRST})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_AUTOMATIC_UPDATE_ON, TIMEZONE_AUTOMATICUPDATE_ON},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_AUTOMATIC_UPDATE_OFF, TIMEZONE_AUTOMATICUPDATE_OFF},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_AUTOMATIC_UPDATE_CONFIRM_FIRST, TIMEZONE_AUTOMATICUPDATE_CONFIRM_FIRST} })
        WdgEnd(CLSID_VTMMENU,AutomaticUpdateVtm)
	WndEnd(SETTINGAPP_WND_AUTOMATICUPDATE)

	WndBegin(SETTINGAPP_WND_DATEFORMAT)
        WdgBegin(CLSID_VTMMENU,DateFormatVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(3, { TXT_LIL_N_YYYYMMDD, TXT_LIL_N_DDMMYYYY, TXT_LIL_N_MMDDYYYY})
            WdgDynamicMenuItemInfRC(3, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_DATE_FORMAT_YYYYMMDD, DATEFORMAT_YYYYMMDD},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_DATE_FORMAT_DDMMYYYY, DATEFORMAT_DDMMYYYY},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_DATE_FORMAT_MMDDYYYY, DATEFORMAT_MMDDYYYY} })
        WdgEnd(CLSID_VTMMENU,DateFormatVtm)
	WndEnd(SETTINGAPP_WND_DATEFORMAT)

	WndBegin(SETTINGAPP_WND_DEFAULTSIM)
        WdgBegin(CLSID_VTMMENU,DefaultSimVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LTL_N_DEFAULT_SIM,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_MASTER_SIM, TXT_LIL_N_SLAVE_SIM})
            WdgDynamicMenuItemInfRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MASTER_SIM, DEFAULT_SIM_MASTER},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SLAVE_SIM, DEFAULT_SIM_SLAVE} })
        WdgEnd(CLSID_VTMMENU,DefaultSimVtm)
	WndEnd(SETTINGAPP_WND_DEFAULTSIM)

	WndBegin(SETTINGAPP_WND_MENUANIMATEDSTYLE)
        WdgBegin(CLSID_VTMMENU,MenuAnimatedStyleVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(10, { TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_RANDOM, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_NONE, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_3DFLIP, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_ROTATE, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_SLIDE, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_LIQUID, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_ZOOM, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_2DFLIP, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_DESTRUCT, TXT_LIL_N_MAIN_MENU_ANIMATION_STYLE_SPLIT})
            WdgDynamicMenuItemInfRC(10, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_RANDOM, SET_MENU_ANIMATION_STYLE_RANDOM},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_NONE, SET_MENU_ANIMATION_STYLE_NONE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_3DFLIP, SET_MENU_ANIMATION_STYLE_3DFLIP},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_ROTATE, SET_MENU_ANIMATION_STYLE_ROTATE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_SLIDE, SET_MENU_ANIMATION_STYLE_SLIDE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_LIQUID, SET_MENU_ANIMATION_STYLE_LIQUID},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_ZOOM, SET_MENU_ANIMATION_STYLE_ZOOM},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_2DFLIP, SET_MENU_ANIMATION_STYLE_2DFLIP},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_DESTRUCT, SET_MENU_ANIMATION_STYLE_DESTRUCT},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_MAIN_MENU_ANIMATION_STYLE_SPLIT, SET_MENU_ANIMATION_STYLE_SPLIT} })
        WdgEnd(CLSID_VTMMENU,MenuAnimatedStyleVtm)
    WndEnd(SETTINGAPP_WND_MENUANIMATEDSTYLE)

#ifdef __MULTI_THEMES_ENABLED__
    WndBegin(SETTINGAPP_WND_MENUCHANGETHEME)
        WdgBegin(CLSID_VTMMENU,MenuChangeThemeStyleVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,MenuChangeThemeStyleVtm)
    WndEnd(SETTINGAPP_WND_MENUCHANGETHEME)
#endif
#if defined(__LIVE_WALLPAPER__)
    WndBegin(SETTINGAPP_WND_3D_WALLPAPER)
        WdgBegin(CLSID_VTMMENU,WallpaperVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_WALLPAPER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(17, { TXT_LIL_N_3D_EFFECT_DEFAULT, TXT_LIL_N_3D_EFFECT_SNAKELINE, TXT_LIL_N_3D_EFFECT_COMET, TXT_LIL_N_3D_EFFECT_EARTHROT, TXT_LIL_N_3D_EFFECT_FALLSNOW, TXT_LIL_N_3D_EFFECT_FISH, TXT_LIL_N_3D_EFFECT_SEASHORE, TXT_LIL_N_3D_EFFECT_SOLARSYSTEM, TXT_LIL_N_3D_EFFECT_JUMPGATE, TXT_LIL_N_3D_EFFECT_WEATHER, TXT_LIL_N_3D_EFFECT_GRASSTRACE, TXT_LIL_N_3D_EFFECT_FARM,TXT_LIL_N_3D_EFFECT_BIRD,TXT_LIL_N_3D_EFFECT_DROPLET,TXT_LIL_N_3D_EFFECT_INWATER,TXT_LIL_N_3D_EFFECT_INWATERSHOOT,TXT_LIL_N_3D_EFFECT_IMAGE})
            WdgDynamicMenuItemInfRC(17, {
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FLUTTERSNOW, WALLPAPER_3DEFFECT_FLUTTERSNOW},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SNAKELINE, WALLPAPER_3DEFFECT_SNAKELINE},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_COMET, WALLPAPER_3DEFFECT_COMET},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_EARTHROT, WALLPAPER_3DEFFECT_EARTHROT},							
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FALLSNOW, WALLPAPER_3DEFFECT_FALLSNOW},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FISH, WALLPAPER_3DEFFECT_FISH},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SEASHORE, WALLPAPER_3DEFFECT_SEASHORE},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SOLARSYSTEM, WALLPAPER_3DEFFECT_SOLARSYSTEM},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_JUMPGATE, WALLPAPER_3DEFFECT_JUMPGATE},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_WEATHER, WALLPAPER_3DEFFECT_WEATHER},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_GRASSTRACE, WALLPAPER_3DEFFECT_GRASSTRACE},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FARM, WALLPAPER_3DEFFECT_FARM},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_BIRD, WALLPAPER_3DEFFECT_BIRD},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_DROPLET, WALLPAPER_3DEFFECT_DROPLET},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_INWATER, WALLPAPER_3DEFFECT_INWATER},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_INWATERSHOOT, WALLPAPER_3DEFFECT_INWATERSHOOT},
                    {MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_IMAGE, WALLPAPER_3DEFFECT_IMAGE}
                    })
        WdgEnd(CLSID_VTMMENU,WallpaperVtm)
        WdgBegin(CLSID_VTMMENU,IdleWallpaperVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_LIVEWALLPAPER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGE_TEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgDynamicMenuItemRC(17, {
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FLUTTERSNOW, WALLPAPER_3DEFFECT_FLUTTERSNOW}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_DEFAULT, TXT_LIL_N_3D_EFFECT_DEFAULT}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SNAKELINE, WALLPAPER_3DEFFECT_SNAKELINE}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_SNAKELINE, TXT_LIL_N_3D_EFFECT_SNAKELINE}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_COMET, WALLPAPER_3DEFFECT_COMET}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_COMET, TXT_LIL_N_3D_EFFECT_COMET}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_EARTHROT, WALLPAPER_3DEFFECT_EARTHROT}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_EARTHROT, TXT_LIL_N_3D_EFFECT_EARTHROT}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FALLSNOW, WALLPAPER_3DEFFECT_FALLSNOW}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_FALLSNOW, TXT_LIL_N_3D_EFFECT_FALLSNOW}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FISH, WALLPAPER_3DEFFECT_FISH}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_FISH, TXT_LIL_N_3D_EFFECT_FISH}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SEASHORE, WALLPAPER_3DEFFECT_SEASHORE}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_SEASHORE, TXT_LIL_N_3D_EFFECT_SEASHORE}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_SOLARSYSTEM, WALLPAPER_3DEFFECT_SOLARSYSTEM}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_SOLARSYSTEM, TXT_LIL_N_3D_EFFECT_SOLARSYSTEM}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_JUMPGATE, WALLPAPER_3DEFFECT_JUMPGATE}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_JUMPGATE, TXT_LIL_N_3D_EFFECT_JUMPGATE}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_WEATHER, WALLPAPER_3DEFFECT_WEATHER}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_WEATHER, TXT_LIL_N_3D_EFFECT_WEATHER}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_GRASSTRACE, WALLPAPER_3DEFFECT_GRASSTRACE}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_GRASSTRACE, TXT_LIL_N_3D_EFFECT_GRASSTRACE}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_FARM, WALLPAPER_3DEFFECT_FARM}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_FARM, TXT_LIL_N_3D_EFFECT_FARM}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_BIRD, WALLPAPER_3DEFFECT_BIRD}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_BIRD, TXT_LIL_N_3D_EFFECT_BIRD}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_DROPLET, WALLPAPER_3DEFFECT_DROPLET}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_DROPLET, TXT_LIL_N_3D_EFFECT_DROPLET}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_INWATER, WALLPAPER_3DEFFECT_INWATER}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_INWATER, TXT_LIL_N_3D_EFFECT_INWATER}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_INWATERSHOOT, WALLPAPER_3DEFFECT_INWATERSHOOT}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_INWATERSHOOT, TXT_LIL_N_3D_EFFECT_INWATERSHOOT}},
                    {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_PLAY, SK_BACK}, MNU_SETTING_WALLPAPER_3D_EFFECT_IMAGE, WALLPAPER_3DEFFECT_IMAGE}, {SETTINGS_IMG_SINGLE_LIST_LIVE_WALLPAPER_IMAGE, TXT_LIL_N_3D_EFFECT_IMAGE}}
                    })
        WdgEnd(CLSID_VTMMENU,IdleWallpaperVtm)
    WndEnd(SETTINGAPP_WND_3D_WALLPAPER) 

    WndBegin(SETTINGAPP_WND_LIVEWALLPAPER_PEREVIEW)
        WndSetStatusBarVisibleRC(FALSE)
        WndSetTitleVisiableRC(FALSE)
        WndSetSoftkeyVisibleRC(VIEWSK_VISIABLE)
    WndEnd(SETTINGAPP_WND_LIVEWALLPAPER_PEREVIEW)

    WndBegin(SETTINGAPP_WND_LIVEWALLPAPER_OPTION)
        WdgBegin(CLSID_VTMOPTIONMENU,WallpaperOption)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT,2})
            VtmCreateOptionMenuDataRC(2, {
                              {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_SELECT, SK_BACK}, MNU_SETTING_WALLPAPER_OPTION_SELECT}, TXT_LSK_N_SELECT},
                              {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_SELECT, SK_BACK}, MNU_SETTING_WALLPAPER_OPTION_EDIT}, TXT_OIL1_N_EDIT} })
        WdgEnd(CLSID_VTMOPTIONMENU,WallpaperOption)
    WndEnd(SETTINGAPP_WND_LIVEWALLPAPER_OPTION)

    WndBegin(SETTINGAPP_WND_IMGWALLPAPER_PREVIEW)
        WndSetTitleRC({IMG_NULL_ID, TXT_LIL_N_3D_EFFECT_IMAGE})
        WdgBegin(CLSID_IMAGEWIDGET,WallpaperImgWidget)
            WdgImageCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_LCD_HEIGHT-MAIN_TITLE_HEIGHT-MAIN_SK_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,IMG_NULL_ID}})
            WdgImageSetDataByIDRC(IMG_NULL_ID)
        WdgEnd(CLSID_IMAGEWIDGET,WallpaperImgWidget)
    WndEnd(SETTINGAPP_WND_IMGWALLPAPER_PREVIEW)
#endif

#ifndef __APP_MMI_SMALLROM__
    WndBegin(SETTINGAPP_WND_LAYOUT)
        WdgBegin(CLSID_VTMMENU,LayoutVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,LayoutVtm)
    WndEnd(SETTINGAPP_WND_LAYOUT)
#endif
    WndBegin(SETTINGAPP_WND_WRITINGLANG)
        WdgBegin(CLSID_VTMMENU,WritingLangVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,WritingLangVtm)
    WndEnd(SETTINGAPP_WND_WRITINGLANG)

    WndBegin(SETTINGAPP_WND_DEFAULT_INPUT_METHOD)
        WdgBegin(CLSID_VTMMENU,DefaultInputMethodVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,DefaultInputMethodVtm)
    WndEnd(SETTINGAPP_WND_DEFAULT_INPUT_METHOD)

    WndBegin(SETTINGAPP_WND_ENCODING)
        WdgBegin(CLSID_VTMMENU,EncodingVtm)
            VtmCreateMenuRC({IMG_NULL_ID, TXT_LIL_N_ENCODING_METHOD, WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
        WdgEnd(CLSID_VTMMENU,EncodingVtm)
    WndEnd(SETTINGAPP_WND_ENCODING)

    WndBegin(SETTINGAPP_WND_FILEMGR_IMAGE)
        WdgBegin(CLSID_VTMMENU,FileMgrImageVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            WdgStaticMenuItemRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_USE_SYSTEM_FILE, TXT_LIL_N_USE_SYSTEM_FILE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SELECT_FILE, TXT_LIL_N_SELECT_FILE} })
        WdgEnd(CLSID_VTMMENU,FileMgrImageVtm)
    WndEnd(SETTINGAPP_WND_FILEMGR_IMAGE)

    WndBegin(SETTINGAPP_WND_FILEMGR_MELODY)
        WdgBegin(CLSID_VTMMENU,FileMgrMelodyVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            WdgStaticMenuItemRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_USE_SYSTEM_FILE, TXT_LIL_N_USE_SYSTEM_FILE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SELECT_FILE, TXT_LIL_N_SELECT_FILE} })
        WdgEnd(CLSID_VTMMENU,FileMgrMelodyVtm)
    WndEnd(SETTINGAPP_WND_FILEMGR_MELODY)

    WndBegin(SETTINGAPP_WND_FILEMGR_MAINMENU)
        WdgBegin(CLSID_VTMMENU,FileMgrMainmenuVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            WdgStaticMenuItemRC(2, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_DEFAULT_FILE, TXT_OIL1_N_USE_DEFAULT},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SELECT_FILE, TXT_LIL_N_SELECT_FILE} })
        WdgEnd(CLSID_VTMMENU,FileMgrMainmenuVtm)
    WndEnd(SETTINGAPP_WND_FILEMGR_MAINMENU)

    WndBegin(SETTINGAPP_WND_POWER_SWITCH)
        WdgBegin(CLSID_VTMMENU,PowerSwitchVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_POWER_SWITCH,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,2,0,0})
            VtmCreateMenuDataRC(2,{{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT, SK_OK, SK_CANCEL},MNU_SETTING_POWER_SWITCH_BATTERY_MASTER},TXT_LIL_N_BATTERY1},{{MENUMODEL_ITEM_VISABLE,{SK_OK_TEXT, SK_OK, SK_CANCEL},MNU_SETTING_POWER_SWITCH_BATTERY_SLAVE},TXT_LIL_N_BATTERY2}})
        WdgEnd(CLSID_VTMMENU,PowerSwitchVtm)
		WndEnd(SETTINGAPP_WND_POWER_SWITCH)

#ifdef __G_SENSOR_MMI__
       WndBegin(SETTINGAPP_WND_GSENSOR)
        WdgBegin(CLSID_VTMMENU,GSensorVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_GSENSOR_WND_AUTOROTATE,TXT_LIL_N_GSENSOR_SHAKE_WALLPAPER, TXT_LIL_N_GSENSOR_SHAKE_SONG, TXT_LIL_N_GSENSOR_CHANGE_PICTURE, TXT_LIL_N_GSENSOR_ROTATE_PICTURE, TXT_LIL_N_GSENSOR_FLIP_SILENT})
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_WND_AUTOROTATE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_SHAKE_WALLPAPER, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_SHAKE_SONG, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_CHANGE_PICTURE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_ROTATE_PICTURE, SET_SOption},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_GSENSOR_FLIP_SILENT, SET_SOption} })
        WdgEnd(CLSID_VTMMENU,GSensorVtm)
        WndEnd(SETTINGAPP_WND_GSENSOR)
#endif
#ifdef __APP_MMI_SCREENSAVER__
    WndBegin(SETTINGAPP_WND_SCREENSAVER)
        WdgBegin(CLSID_VTMMENU,ScreensaverVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_SCREENSAVER,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})         
            WdgMenuItemTextRC(4, { TXT_LIL_N_STATUS, TXT_LIL_N_SCREEN_SAVER_3D_EFFECT, TXT_LIL_N_SCREEN_SAVER_DURATION, TXT_LIL_N_SCREEN_DISPLAY })
            WdgDynamicMenuItemInfRC(4, {           
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_SAVER_STATUS, SET_SOption},                          
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_SAVER_3D_EFFECT, SET_SOption},                                                            
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_SAVER_DURATION, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREEN_SAVER_DISPLAY, SET_LaunchFileMgrAP} })
        WdgEnd(CLSID_VTMMENU,ScreensaverVtm)
    WndEnd(SETTINGAPP_WND_SCREENSAVER)

    WndBegin(SETTINGAPP_WND_SCREENSAVERDURATION)
        WdgBegin(CLSID_VTMMENU,ScreensaverDurationVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(4, { TXT_LIL_N_5_SECONDS, TXT_LIL_N_15_SECONDS, TXT_LIL_N_30_SECONDS, TXT_LIL_N_60_SECONDS})
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREEN_SAVER_DURATION_5_SECONDS, SCREEN_SAVER_DURATION_5SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREEN_SAVER_DURATION_15_SECONDS, SCREEN_SAVER_DURATION_15SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREEN_SAVER_DURATION_30_SECONDS, SCREEN_SAVER_DURATION_30SECS},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREEN_SAVER_DURATION_60_SECONDS, SCREEN_SAVER_DURATION_60SECS} })
        WdgEnd(CLSID_VTMMENU,ScreensaverDurationVtm)
    WndEnd(SETTINGAPP_WND_SCREENSAVERDURATION)

#endif

#ifdef __SCREEN_EFFECTS_SUPPORT__
    WndBegin(SETTINGAPP_WND_SCREENEFFECT)
        WdgBegin(CLSID_VTMMENU,ScreenEffectVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(2, { TXT_LIL_N_SCREEN_EFFECT_TYPE, TXT_LIL_N_SCREEN_EFFECT_SNOW_CONFIG })
            WdgDynamicMenuItemInfRC(2, {
                            {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_TYPE, SET_OptionList},
                            {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW, SET_MenuList} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT)
    WndBegin(SETTINGAPP_WND_SCREENEFFECTTYPE)
        WdgBegin(CLSID_VTMMENU,ScreenEffectTypeVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(9, { TXT_LIL_N_SCREEN_EFFECT_SNOW, TXT_LIL_N_SCREEN_EFFECT_RIPPLE, TXT_LIL_N_SCREEN_EFFECT_FIRE_FLY, TXT_LIL_N_SCREEN_EFFECT_WATER, TXT_LIL_N_SCREEN_EFFECT_METEOR, TXT_LIL_N_SCREEN_EFFECT_BEZIER, TXT_LIL_N_SCREEN_EFFECT_FIRE, TXT_LIL_N_SCREEN_EFFECT_SPACE, TXT_LIL_N_OFF})
            WdgDynamicMenuItemInfRC(9, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_SNOW, SCREENEFFECT_SNOW},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_RIPPLE, SCREENEFFECT_RIPPLE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_FIRE_FLY, SCREENEFFECT_FIRE_FLY},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_WATER, SCREENEFFECT_WATER},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_METEOR, SCREENEFFECT_METEOR},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_BEZIER, SCREENEFFECT_BEZIER},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_FIRE, SCREENEFFECT_FIRE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_SPACE, SCREENEFFECT_SPACE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_SCREENEFFECT_TYPE_OFF, SCREENEFFECT_OFF} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectTypeVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECTTYPE)
#ifdef __SCREEN_EFFECT_SNOW_SUPPORT__
    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowVtm)
            VtmCreateMenuRC({IMG_NULL_ID,TXT_LIL_N_NO_TITLE,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_TEXT_THEMETEXT,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
            WdgMenuItemTextRC(7, { TXT_LIL_N_SNOW_DROP_SPEED, TXT_LIL_N_SNOW_NUM, TXT_LIL_N_SNOW_BIG_NUM, TXT_LIL_N_SNOW_BLOW_DIR, TXT_LIL_N_SNOW_BLOW_CHANGE_PERIOD, TXT_LIL_N_SNOW_PILE_SPEED, TXT_LIL_N_SNOW_COLOR })
            WdgDynamicMenuItemInfRC(7, {
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_SPEED, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_NUM, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_BIG_NUM, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_BLOW_DIR, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_BLOW_TIME, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_PILE_SPEED, SET_OptionList},
                              {MENUMODEL_ITEM_VISABLE, {SK_CHANGE, SK_OK, SK_BACK}, MNU_SETTING_SCREENEFFECT_SNOW_COLOR, SET_OptionList} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_SPEED)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowSpeedVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(5, { TXT_LIL_N_VERY_SLOW, TXT_LIL_N_SLOW, TXT_LIL_N_SPEED_NORMAL, TXT_LIL_N_FAST, TXT_LIL_N_VERY_FAST})
            WdgDynamicMenuItemInfRC(5, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_SPEED_1},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_SPEED_2},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_SPEED_3},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_SPEED_4},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_SPEED_5} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowSpeedVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_SPEED)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_NUM)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowNumVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(5, { TXT_NIL_N_50, TXT_NIL_N_100, TXT_NIL_N_200, TXT_NIL_N_500, TXT_NIL_N_1000})
            WdgDynamicMenuItemInfRC(5, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_NUM_50},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_NUM_100},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_NUM_200},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_NUM_500},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_NUM_1000} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowNumVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_NUM)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_BIG_NUM)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowBigNumVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(7, { TXT_NIL_N_0, TXT_NIL_N_5, TXT_NIL_N_15, TXT_NIL_N_30, TXT_NIL_N_60, TXT_NIL_N_120, TXT_NIL_N_240})
            WdgDynamicMenuItemInfRC(7, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_0},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_5},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_15},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_30},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_60},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_120},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BIG_NUM_240} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowBigNumVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_BIG_NUM)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_DIR)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowBlowDirVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(4, { TXT_LIL_N_BLOW_RANDOM, TXT_LIL_N_BLOW_LEFT, TXT_LIL_N_BLOW_RIGHT, TXT_LIL_N_BLOW_DOWN})
            WdgDynamicMenuItemInfRC(4, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_DIR_RANDOM},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_DIR_LEFT},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_DIR_RIGHT},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_DIR_DOWN} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowBlowDirVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_DIR)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_TIME)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowBlowTimeVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(7, { TXT_NIL_N_20, TXT_NIL_N_100, TXT_NIL_N_500, TXT_NIL_N_2000, TXT_NIL_N_5000, TXT_NIL_N_10000, TXT_LIL_N_TIME_INFINITE})
            WdgDynamicMenuItemInfRC(7, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_20},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_100},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_500},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_2000},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_5000},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_10000},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_BLOW_TIME_INFINITE} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowBlowTimeVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_BLOW_TIME)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_PILE_SPEED)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowPileSpeedVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_NO_SNOW_PILE, TXT_LIL_N_VERY_SLOW, TXT_LIL_N_SLOW, TXT_LIL_N_SPEED_NORMAL, TXT_LIL_N_FAST, TXT_LIL_N_VERY_FAST})
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_0},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_10},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_20},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_40},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_80},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_PILE_SPEED_100} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowPileSpeedVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_PILE_SPEED)

    WndBegin(SETTINGAPP_WND_SCREENEFFECT_SNOW_COLOR)
        WdgBegin(CLSID_VTMMENU,ScreenEffectSnowColorVtm)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,0,0,0})
            WdgMenuItemTextRC(6, { TXT_LIL_N_WHITE, TXT_LIL_N_YELLOW, TXT_LIL_N_RED, TXT_LIL_N_GREEN, TXT_LIL_N_BLUE, TXT_LIL_N_BLACK})
            WdgDynamicMenuItemInfRC(6, {
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_WHITE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_YELLOW},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_RED},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_GREEN},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_BLUE},
                              {MENUMODEL_ITEM_VISABLE, {SK_OK_TEXT, SK_OK, SK_CANCEL}, MNU_SETTING_NONE, SCREENEFFECT_SNOW_COLOR_BLACK} })
        WdgEnd(CLSID_VTMMENU,ScreenEffectSnowColorVtm)
    WndEnd(SETTINGAPP_WND_SCREENEFFECT_SNOW_COLOR)
#endif // __SCREEN_EFFECT_SNOW_SUPPORT__
#endif // __SCREEN_EFFECTS_SUPPORT__

ApEnd(RS,CLSID_SETTINGAPP)

