/**
* @file ResMgr_CtrlItf.h
*
* This header file defines the interface of resource manager
* control request
*/

#ifndef __RESMGR_CTRLITF_H__
#define __RESMGR_CTRLITF_H__

/*=============================================================*/
// Include Files
/*=============================================================*/
#include "ResMgr_Common.h"

/*=============================================================*/
// Type Declarations
/*=============================================================*/
typedef enum ResMgr_CtrlType_e_
{
    RES_MGR_CTRL_TYPE__REG_LISTENER,
    RES_MGR_CTRL_TYPE__DEREG_LISTENER,
    RES_MGR_CTRL_TYPE__CONFIG_LISTENER,
    RES_MGR_CTRL_TYPE__SET_DEVICE_STATUS,
    RES_MGR_CTRL_TYPE__SET_SPEAKER_TYPE,
    RES_MGR_CTRL_TYPE__GET_SPEAKER_TYPE,
    RES_MGR_CTRL_TYPE__GET_DEVICE_STATUS,
    RES_MGR_CTRL_TYPE__INIT_DEFAULT_VOL,
    RES_MGR_CTRL_TYPE__REG_VOL_CTRL,
    RES_MGR_CTRL_TYPE__DEREG_VOL_CTRL,
    RES_MGR_CTRL_TYPE__SET_PREF_PATH,
    RES_MGR_CTRL_TYPE__SET_VOL,
    RES_MGR_CTRL_TYPE__SET_PROFILE_VOL,
    RES_MGR_CTRL_TYPE__GET_VOL,
    RES_MGR_CTRL_TYPE__GET_PATH,
    RES_MGR_CTRL_TYPE__SET_BALANCE,
    RES_MGR_CTRL_TYPE__ENABLE_DTMF,
    RES_MGR_CTRL_TYPE__DISABLE_DTMF,
    RES_MGR_CTRL_TYPE__IS_DTMF_DISABLED,
    RES_MGR_CTRL_TYPE__ENABLE_LOCAL_TONE,    
    RES_MGR_CTRL_TYPE__INIT_DEFAULT_PROFILE_VOL,
    RES_MGR_CTRL_TYPE__SET_ACTIVE_PROFILE,
    RES_MGR_CTRL_TYPE__GET_ACTIVE_PROFILE,
    RES_MGR_CTRL_TYPE__REG_DEVICE_CHANGED_CB,
    RES_MGR_CTRL_TYPE__REG_BT_STATUS_CHANGED_CNF_CB,
    RES_MGR_CTRL_TYPE__FINALIZE_CMD,
    RES_MGR_CTRL_TYPE__RESUME_CMD,
    RES_MGR_CTRL_TYPE__SET_TMP_VOL,
    RES_MGR_CTRL_TYPE__SET_MEDIA_CONFIG,
    RES_MGR_CTRL_TYPE__UPDATE_MEDIA_CONFIG,
    RES_MGR_CTRL_TYPE__CONFIRM_REL_RESOURCE,
    RES_MGR_CTRL_TYPE__UPDATE_BEARER_STATUS,
    RES_MGR_CTRL_TYPE__GET_MMP_CAPABILITY,
    RES_MGR_CTRL_TYPE__GET_MML_CONCURRENT_SECTION,
    RES_MGR_CTRL_TYPE__GET_PLATFORM_CAPABILITY,
    RES_MGR_CTRL_TYPE__GET_PLATFORM_CHIPTYPE,
    RES_MGR_CTRL_TYPE__IS_HWSCALAR_OCCUPIED,
    RES_MGR_CTRL_TYPE__CHECK_FORMAT,
    RES_MGR_CTRL_TYPE__CHECK_PLAYBACK_FORMAT,
    RES_MGR_CTRL_TYPE__EMU_MAX_ROM_SIZE,
    RES_MGR_CTRL_TYPE__CHECK_VDO_CODEC,
    RES_MGR_CTRL_TYPE__CHECK_AUD_CODEC,
    RES_MGR_CTRL_TYPE__CHECK_VDO_ENC_FPS,
    RES_MGR_CTRL_TYPE__CHECK_VDO_ENC_RES,
    RES_MGR_CTRL_TYPE__RINGBUFF_INIT,
    RES_MGR_CTRL_TYPE__RINGBUFF_UNINIT,
    RES_MGR_CTRL_TYPE__RINGBUFF_PUSH,
    RES_MGR_CTRL_TYPE__RINGBUFF_POP,
    RES_MGR_CTRL_TYPE__RINGBUFF_GET_INFO,    
    RES_MGR_CTRL_TYPE__RINGBUFF_SET_DATAEND,
    RES_MGR_CTRL_TYPE__RETRIEVE_BUFF_INFO,
    RES_MGR_CTRL_TYPE__GET_AP_PATH_SETTING,
    RES_MGR_CTRL_TYPE__IS_TASK_IDLE,
    RES_MGR_CTRL_TYPE__GET_RESUME_RESTART,
    RES_MGR_CTRL_TYPE__EXEC_RESUME_RESTART,
    RES_MGR_CTRL_TYPE__NUM
} ResMgr_CtrlType_e;

typedef void* ResMgr_CtrlReqHandle_t;

/*=============================================================*/
// Function Declaration
/*=============================================================*/

#endif //__RESMGR_CTRLITF_H__

