ApBegin(RS,CLSID_SEARCHAPP)
#if defined(__MMI_SEARCH_APP__)
	WndBegin(SEARCHAPP_WND_MAIN)
        WdgBegin(CLSID_ABSCONTAINER,tSearchAbsContainer)
            WdgAbsContainerCreateForWndRC({{SEARCHAPP_SEARCH_ABSCONTAINER_X,SEARCHAPP_SEARCH_ABSCONTAINER_Y},{SEARCHAPP_SEARCH_ABSCONTAINER_WIDTH,SEARCHAPP_SEARCH_ABSCONTAINER_HEIGHT},0})
        WdgEnd(CLSID_ABSCONTAINER,tSearchAbsContainer)
        
        WdgBegin(CLSID_IMAGEWIDGET,pSearchBGImageWidget)
            WdgImageCreateForWndRC({ {SEARCHAPP_SEARCH_BG_X,SEARCHAPP_SEARCH_BG_Y},{SEARCHAPP_SEARCH_BG_WIDTH,SEARCHAPP_SEARCH_BG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,SEARCH_IMG_BG} })
            WdgImageSetDataByIDRC(SEARCH_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,pSearchBGImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pSearchIconImageWidget)
            WdgImageCreateForWndRC({ {SEARCHAPP_SEARCH_IMGICON_X,SEARCHAPP_SEARCH_IMGICON_Y},{SEARCHAPP_SEARCH_IMGICON_WIDTH,SEARCHAPP_SEARCH_IMGICON_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,SEARCH_IMG_SEARCH} })
            WdgImageSetDataByIDRC(SEARCH_IMG_SEARCH)
        WdgEnd(CLSID_IMAGEWIDGET,pSearchIconImageWidget)

        WdgBegin(CLSID_IMAGEWIDGET,pSearchLoadingImageWidget)
            WdgImageCreateForWndRC({ {SEARCHAPP_SEARCH_IMGLOADING_X,SEARCHAPP_SEARCH_IMGLOADING_Y},{SEARCHAPP_SEARCH_IMGLOADING_WIDTH,SEARCHAPP_SEARCH_IMGLOADING_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,SEARCH_IMG_LOADING} })
            WdgImageSetDataByIDRC(SEARCH_IMG_LOADING)
        WdgEnd(CLSID_IMAGEWIDGET,pSearchLoadingImageWidget)

        WdgBegin(CLSID_GRID_MENUWIDGET,pMainMenuWidget)
            WdgMenuCreateForWndRC({{SEARCHAPP_SEARCH_MAINMENU_X,SEARCHAPP_SEARCH_MAINMENU_Y}, {SEARCHAPP_SEARCH_MAINMENU_WIDTH,SEARCHAPP_SEARCH_MAINMENU_HEIGHT},WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_GRID_MENUWIDGET,pMainMenuWidget)
        
        WdgBegin(CLSID_GRID_MENUWIDGET,pItemMenuWidget)
            WdgMenuCreateForWndRC({{SEARCHAPP_SEARCH_MAINMENU_X,SEARCHAPP_SEARCH_MAINMENU_Y}, {SEARCHAPP_SEARCH_MAINMENU_WIDTH,SEARCHAPP_SEARCH_MAINMENU_HEIGHT},WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_GRID_MENUWIDGET,pItemMenuWidget)

        WdgBegin(CLSID_INPUTWIDGET,pSearchInputWidget)
            WdgInputCreateForWndRC({ {SEARCHAPP_SEARCH_INPUT_WDG_X,SEARCHAPP_SEARCH_INPUT_WDG_Y},{SEARCHAPP_SEARCH_INPUT_WDG_WIDTH,SEARCHAPP_SEARCH_INPUT_WDG_HEIGHT},{TRUE,SKBOARD_ENABLE} })
            WdgInputSetModeMaskRC(MAE_MODEMASK_PHB_SEARCH)
            WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_MT_abc_EN)
        WdgEnd(CLSID_INPUTWIDGET,pSearchInputWidget)
    WndEnd(SEARCHAPP_WND_MAIN)
#endif
ApEnd(RS,CLSID_SEARCHAPP)

