ApBegin(RS,CLSID_FMRADIOAPP)
#ifndef __APP_MMI_SMALLROM__
    WndBegin(FMRAPP_WND_RECORD)
        WdgBegin(CLSID_TEXTWIDGET,TextWdgDate)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_DATE_X,FMR_RECORD_TEXTWDG_DATE_Y},{FMR_RECORD_TEXTWDG_DATE_WIDTH,FMR_RECORD_TEXTWDG_DATE_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgDate)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgTime)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_TIME_X,FMR_RECORD_TEXTWDG_TIME_Y},{FMR_RECORD_TEXTWDG_TIME_WIDTH,FMR_RECORD_TEXTWDG_TIME_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgTime)

        WdgBegin(CLSID_IMAGEWIDGET,ImageWdgBg)
            WdgImageCreateForWndRC({{FMR_RECORD_IMAGEWDG_BG_X,FMR_RECORD_IMAGEWDG_BG_Y},{FMR_RECORD_IMAGEWDG_BG_WIDTH,FMR_RECORD_IMAGEWDG_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_RECORDING_BG} } )
        WdgEnd(CLSID_IMAGEWIDGET,ImageWdgBg)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgChannel)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_CHANNEL_X,FMR_RECORD_TEXTWDG_CHANNEL_Y},{FMR_RECORD_TEXTWDG_CHANNEL_WIDTH,FMR_RECORD_TEXTWDG_CHANNEL_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgChannel)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgCount)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_COUNT_X,FMR_RECORD_TEXTWDG_COUNT_Y},{FMR_RECORD_TEXTWDG_COUNT_WIDTH,FMR_RECORD_TEXTWDG_COUNT_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_LARGE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgCount)

        WdgBegin(CLSID_IMAGEWIDGET,ImageWdgRec)
            WdgImageCreateForWndRC({{FMR_RECORD_IMAGEWDG_REC_X,FMR_RECORD_IMAGEWDG_REC_Y},{FMR_RECORD_IMAGEWDG_REC_WIDTH,FMR_RECORD_IMAGEWDG_REC_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_RECORDING_ICON} } )
        WdgEnd(CLSID_IMAGEWIDGET,ImageWdgRec)

         WdgBegin(CLSID_TEXTWIDGET,TextWdgStatus)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_STATUS_X,FMR_RECORD_TEXTWDG_STATUS_Y},{FMR_RECORD_TEXTWDG_STATUS_WIDTH,FMR_RECORD_TEXTWDG_STATUS_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgStatus)

    WndEnd(FMRAPP_WND_RECORD)

#else  // small rom

    WndBegin(FMRAPP_WND_RECORD)
        WdgBegin(CLSID_IMAGEWIDGET,ImageWdgTitleBg)
            WdgImageCreateForWndRC({{FMR_RECORD_IMAGEWDG_TITLEBG_X,FMR_RECORD_IMAGEWDG_TITLEBG_Y},{FMR_RECORD_IMAGEWDG_TITLEBG_WIDTH,FMR_RECORD_IMAGEWDG_TITLEBG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_TITLEBAR_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_TITLEBAR_BG)
        WdgEnd(CLSID_IMAGEWIDGET,ImageWdgTitleBg)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgChannel)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_CHANNEL_X,FMR_RECORD_TEXTWDG_CHANNEL_Y},{FMR_RECORD_TEXTWDG_CHANNEL_WIDTH,FMR_RECORD_TEXTWDG_CHANNEL_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgChannel)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgDate)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_DATE_X,FMR_RECORD_TEXTWDG_DATE_Y},{FMR_RECORD_TEXTWDG_DATE_WIDTH,FMR_RECORD_TEXTWDG_DATE_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgDate)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgTime)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_TIME_X,FMR_RECORD_TEXTWDG_TIME_Y},{FMR_RECORD_TEXTWDG_TIME_WIDTH,FMR_RECORD_TEXTWDG_TIME_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_SUPERSMALL)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgTime)

         WdgBegin(CLSID_TEXTWIDGET,TextWdgStatus)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_STATUS_X,FMR_RECORD_TEXTWDG_STATUS_Y},{FMR_RECORD_TEXTWDG_STATUS_WIDTH,FMR_RECORD_TEXTWDG_STATUS_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(COLOR_RED_3)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgStatus)

        WdgBegin(CLSID_TEXTWIDGET,TextWdgCount)
            WdgTextCreateForWndRC({{FMR_RECORD_TEXTWDG_COUNT_X,FMR_RECORD_TEXTWDG_COUNT_Y},{FMR_RECORD_TEXTWDG_COUNT_WIDTH,FMR_RECORD_TEXTWDG_COUNT_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_LARGE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,TextWdgCount)

    WndEnd(FMRAPP_WND_RECORD)
#endif  // small rom

#if defined(__3D_UI_FMRADIO__)
    WndBegin(FMRAPP_WND_MAIN)
        WndSetStatusBarVisibleRC(FALSE)
        WndSetSoftkeyVisibleRC(TRUE)
        WndSetAllSoftkeyRC({SK_OPTION, SK_NONE, SK_QUIT})
        WdgBegin(CLSID_IMAGEWIDGET,BgImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_BG_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_BG_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BG_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,COMMON_IMG_M303_BG} } )
            WdgImageSetDataByIDRC(COMMON_IMG_M303_BG)
        WdgEnd(CLSID_IMAGEWIDGET,BgImageWdg)

        WdgBegin(CLSID_TEXTWIDGET,NameTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_TITLE_TEXTWIDGET_X_POSITION,FMR_MAIN_PANEL_TITLE_TEXTWIDGET_Y_POSITION},{FMR_MAIN_PANEL_TITLE_TEXTWIDGET_WIDTH,FMR_MAIN_PANEL_TITLE_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FMR_MAIN_PANEL_TITLE_TEXTWIDGET_FONT_SIZE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
        WdgEnd(CLSID_TEXTWIDGET,NameTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,FrequencyTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_X_POSITION,FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_WIDTH,FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FONT_CAT_LARGE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_ALIGN)
        WdgEnd(CLSID_TEXTWIDGET,FrequencyTextWdg)

		WdgBegin(CLSID_IMAGEWIDGET,FrequencyUnitImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_FREQUENCY_UNIT_IMAGE_X_POSITION,FMR_MAIN_PANEL_FREQUENCY_UNIT_IMAGE_Y_POSITION},{FMR_MAIN_PANEL_FREQUENCY_UNIT_IMAGE_WIDTH,FMR_MAIN_PANEL_FREQUENCY_UNIT_IMAGE_HEIGHT},IMAGE_STYLE_COMMON,{FMRADIO_IMG_M303_FREQUENCY_NUMBER_UNITS}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_FREQUENCY_NUMBER_UNITS)
		WdgEnd(CLSID_IMAGEWIDGET,FrequencyUnitImageWdg)

        WdgBegin(CLSID_SWITCHICONWIDGET,BgPlaySwitchIconWdg)
            WdgSwitchIconCreateForWndRC({{FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,BgPlaySwitchIconWdg)

        WdgBegin(CLSID_BUTTONWIDGET,ChannelAddButtonWdg)
            WdgButtonCreateForWndRC({ {FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_ADD_CHANNEL_UNPRESSED,FMRADIO_IMG_M303_ADD_CHANNEL_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ChannelAddButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,ForwardButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_NEXT_UNPRESSED,FMRADIO_IMG_M303_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ForwardButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,BackwardButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_HEIGHT},0 })
			WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_BACK_UNPRESSED,FMRADIO_IMG_M303_BACK_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,BackwardButtonWdg)

        WdgBegin(CLSID_SWITCHICONWIDGET,PowerOnOffSwitchIconWdg)
            WdgSwitchIconCreateForWndRC({{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,PowerOnOffSwitchIconWdg)

        WdgBegin(CLSID_IMAGEWIDGET,PowerOnOffImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FMRADIO_IMG_M303_POWER_DISABLE}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_M303_POWER_DISABLE)
        WdgEnd(CLSID_IMAGEWIDGET,PowerOnOffImageWdg)

        WdgBegin(CLSID_BUTTONWIDGET,RecButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_HEIGHT},0 })
			WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_REC_CHANNEL_UNPRESSED,FMRADIO_IMG_M303_REC_CHANNEL_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,RecButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_SOUND_INCREASE_UNPRESSED,FMRADIO_IMG_M303_SOUND_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_SOUND_DECREASE_UNPRESSED,FMRADIO_IMG_M303_SOUND_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev8ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev8ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev7ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev7ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev6ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev6ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev5ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev5ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev4ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev4ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev3ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev3ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev2ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev2ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev1ImageWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_VOLUME_LEVEL}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev1ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SoundOnOffImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_ON}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_ON)
        WdgEnd(CLSID_IMAGEWIDGET,SoundOnOffImageWdg)

#if defined(__MMI_BATTERY_ICON_DISPLAY__)
        WdgBegin(CLSID_IMAGEWIDGET,BatteryImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,STATUSBAR_IMG_BATTERY_LEVEL4_1}})
            WdgImageSetDataByIDRC(STATUSBAR_IMG_BATTERY_LEVEL4_1)
        WdgEnd(CLSID_IMAGEWIDGET,BatteryImageWdg)
#endif

        WdgBegin(CLSID_INDICATORWIDGET,FreqIndicatorWdg)
            WdgIndicatorCreateForWndRC({{FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_X_POSITION,FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_WIDTH,FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_HEIGHT},LAYOUT_STYLE_HORIZONTAL})
            WdgIndicatorSetDataRC({FMR_FREQ_IND__START_RS,FMR_FREQ_IND__END_RS,FMR_FREQ_IND__POS_RS})
            WdgIndicatorSetBGImageIDRC(FMRADIO_IMG_M303_SLIDE_BG)
            WdgIndicatorSetINDImageIDRC(FMRADIO_IMG_M303_SLIDE)
            WdgIndicatorSetFGLeftOffsetRC(FMR_FREQ_IND_PADDING_LEFT)
            WdgIndicatorSetFGRightOffsetRC(FMR_FREQ_IND_PADDING_RIGHT)
            WdgIndicatorSetFGTopOffsetRC(FMR_FREQ_IND_PADDING_TOP)
            WdgIndicatorSetFGBottomOffsetRC(FMR_FREQ_IND_PADDING_BOTTOM)
            WdgIndicatorSetINDOffsetRC(FMR_FREQ_IND_IND_OFFSET)
        WdgEnd(CLSID_INDICATORWIDGET,FreqIndicatorWdg)

		WdgBegin(CLSID_INDICATORWIDGET,ChannelMenuWdg)
			WdgMenuCreateForWndRC({{FMR_MAIN_PANEL_CHANNEL_MENU_X_POSITION,FMR_MAIN_PANEL_CHANNEL_MENU_Y_POSITION},{FMR_MAIN_PANEL_CHANNEL_MENU_WIDTH,FMR_MAIN_PANEL_CHANNEL_MENU_HEIGHT},WDG_MENU_TYPE_GRID})
			WdgMenuSetToGridStyleRC({FMR_MAIN_PANEL_CHANNEL_MENU_LAYOUT_HORZNUM,FMR_MAIN_PANEL_CHANNEL_MENU_LAYOUT_VERTNUM,GRID_FIX_LAYOUT_IN_SINGLE_PAGE})
			WdgMenuSetMenuBGImageRC(FMRADIO_IMG_RECORDING_BG)
			WdgMenuSetColGapRC(FMR_CHANNELMENU_COLGAP)			
			WdgCommonSetPaddingDataRC({FMR_CHANNELMENU_PADDING_LEFT,FMR_CHANNELMENU_PADDING_RIGHT,FMR_CHANNELMENU_PADDING_TOP,FMR_CHANNELMENU_PADDING_BOTTOM})
		WdgEnd(CLSID_INDICATORWIDGET,ChannelMenuWdg)

		WdgBegin(CLSID_BUTTONWIDGET,ChannelMenuNextWdg)
			WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_CHANNEL_MENU_NEXT_X_POSITION,FMR_MAIN_PANEL_CHANNEL_MENU_NEXT_Y_POSITION},{FMR_MAIN_PANEL_CHANNEL_MENU_NEXT_WIDTH,FMR_MAIN_PANEL_CHANNEL_MENU_NEXT_HEIGHT}, 0})
			WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_CHANNEL_NUMBER_NEXT_PAGE,FMRADIO_IMG_M303_CHANNEL_NUMBER_NEXT_PAGE_PRESSED})
		WdgEnd(CLSID_BUTTONWIDGET,ChannelMenuNextWdg)

		WdgBegin(CLSID_BUTTONWIDGET,ChannelMenuBackWdg)
			WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_CHANNEL_MENU_BACK_X_POSITION,FMR_MAIN_PANEL_CHANNEL_MENU_BACK_Y_POSITION},{FMR_MAIN_PANEL_CHANNEL_MENU_BACK_WIDTH,FMR_MAIN_PANEL_CHANNEL_MENU_BACK_HEIGHT}, 0})
			WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_M303_CHANNEL_NUMBER_BACK_PAGE,FMRADIO_IMG_M303_CHANNEL_NUMBER_BACK_PAGE_PRESSED})
		WdgEnd(CLSID_BUTTONWIDGET,ChannelMenuBackWdg)

        WdgBegin(CLSID_TEXTWIDGET,PosTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_TEXTWDG_COUNT_X,FMR_MAIN_PANEL_TEXTWDG_COUNT_Y},{FMR_MAIN_PANEL_TEXTWDG_COUNT_WIDTH,FMR_MAIN_PANEL_TEXTWDG_COUNT_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_FONT)
            WdgCommonSetTextColorRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_COLOR)
            WdgCommonSetAlignmentRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_ALIGN)
        WdgEnd(CLSID_TEXTWIDGET,PosTextWdg)

		WdgBegin(CLSID_IMAGEWIDGET,PosImgWdg)
			WdgImageCreateForWndRC({{FMR_MAIN_PANEL_IMGWDG_COUNT_X,FMR_MAIN_PANEL_IMGWDG_COUNT_Y},{FMR_MAIN_PANEL_IMGWDG_COUNT_WIDTH,FMR_MAIN_PANEL_IMGWDG_COUNT_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_M303_ADD_REC_ICON}})
			WdgImageSetDataByIDRC(FMRADIO_IMG_M303_ADD_REC_ICON)
		WdgEnd(CLSID_IMAGEWIDGET,PosImgWdg)

    WndEnd(FMRAPP_WND_MAIN)

#else  // non 3DUI

    WndBegin(FMRAPP_WND_MAIN)
        WndSetStatusBarVisibleRC(FALSE)
        WndSetSoftkeyVisibleRC(TRUE)
        WndSetAllSoftkeyRC({SK_OPTION, SK_NONE, SK_QUIT})
#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_IMAGEWIDGET,BgImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_BG_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_BG_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BG_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_BG} } )
            WdgImageSetDataByIDRC(FMRADIO_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,BgImageWdg)
#else
        WndSetBgColorRC(COLOR_BLACK)
        WdgBegin(CLSID_IMAGEWIDGET,TitleBarImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_TITLEBAR_BG_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_TITLEBAR_BG_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_TITLEBAR_BG_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_TITLEBAR_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_TITLEBAR_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_TITLEBAR_BG)
        WdgEnd(CLSID_IMAGEWIDGET,TitleBarImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,BgImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_BG_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_BG_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BG_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,BgImageWdg)

		WdgBegin(CLSID_TEXTWIDGET,FmTextWdg)
			WdgTextCreateForWndRC({{FMR_MAIN_PANEL_FM_TEXTWIDGET_X_POSITION,FMR_MAIN_PANEL_FM_TEXTWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FM_TEXTWIDGET_WIDTH,FMR_MAIN_PANEL_FM_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON })
			WdgCommonSetTextColorRC(COLOR_WHITE)
			WdgCommonSetAlignmentRC((ALIGN_H_RIGHT | ALIGN_V_MIDDLE))
		WdgEnd(CLSID_TEXTWIDGET, FmTextWdg)
#endif
        WdgBegin(CLSID_TEXTWIDGET,NameTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_TITLE_TEXTWIDGET_X_POSITION,FMR_MAIN_PANEL_TITLE_TEXTWIDGET_Y_POSITION},{FMR_MAIN_PANEL_TITLE_TEXTWIDGET_WIDTH,FMR_MAIN_PANEL_TITLE_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON })
            WdgCommonSetFontCategoryRC(FMR_MAIN_PANEL_TITLE_TEXTWIDGET_FONT_SIZE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
        WdgEnd(CLSID_TEXTWIDGET,NameTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,FrequencyTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_X_POSITION,FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_WIDTH,FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_HEIGHT},TEXT_STYLE_COMMON})
            WdgCommonSetFontCategoryRC(FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_FONT_SIZE)
            WdgCommonSetTextColorRC(COLOR_WHITE)
            WdgCommonSetAlignmentRC(FMR_MAIN_PANEL_FREQUENCY_TEXTWIDGET_ALIGN)
        WdgEnd(CLSID_TEXTWIDGET,FrequencyTextWdg)

        WdgBegin(CLSID_SWITCHICONWIDGET,BgPlaySwitchIconWdg)
            WdgSwitchIconCreateForWndRC({{FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_BGPLAY_BUTTONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,BgPlaySwitchIconWdg)

        WdgBegin(CLSID_BUTTONWIDGET,ChannelAddButtonWdg)
            WdgButtonCreateForWndRC({ {FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_CHANNEL_ADD_BUTTONWIDGET_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_ADD_CHANNEL_UNPRESSED,FMRADIO_IMG_ADD_CHANNEL_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ChannelAddButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,ForwardButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_FORWARD_BUTTONWIDGET_HEIGHT}, 0})
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_NEXT_UNPRESSED,FMRADIO_IMG_NEXT_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,ForwardButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,BackwardButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_BACKWARD_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_PREVIOUS_UNPRESSED,FMRADIO_IMG_PREVIOUS_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,BackwardButtonWdg)

        WdgBegin(CLSID_SWITCHICONWIDGET,PowerOnOffSwitchIconWdg)
            WdgSwitchIconCreateForWndRC({{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_HEIGHT},{SWITCH_ICON_STYLE_CHECK,IMG_NULL_ID,IMG_NULL_ID}})
        WdgEnd(CLSID_SWITCHICONWIDGET,PowerOnOffSwitchIconWdg)

        WdgBegin(CLSID_IMAGEWIDGET,PowerOnOffImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_POWERONOFF_BUTTONWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_POWER_DISABLE}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_POWER_DISABLE)
        WdgEnd(CLSID_IMAGEWIDGET,PowerOnOffImageWdg)

        WdgBegin(CLSID_BUTTONWIDGET,RecButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_RECORD_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_NO_TOUCH_REC_DISABLE,FMRADIO_IMG_NO_TOUCH_REC_DISABLE})
        WdgEnd(CLSID_BUTTONWIDGET,RecButtonWdg)

#ifndef __APP_MMI_SMALLROM__
        WdgBegin(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_SOUND_INCREASE_UNPRESSED,FMRADIO_IMG_SOUND_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,FMRADIO_IMG_SOUND_DECREASE_UNPRESSED,FMRADIO_IMG_SOUND_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev8ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV8_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_08}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_08)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev8ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev7ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV7_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_07}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_07)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev7ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev6ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV6_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_06}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_06)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev6ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev5ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV5_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_05}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_05)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev5ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev4ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV4_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_04}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_04)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev4ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev3ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV3_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_03}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_03)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev3ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev2ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV2_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_02}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_02)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev2ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeLev1ImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_LEV1_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_LEVEL_01}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_LEVEL_01)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeLev1ImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,SoundOnOffImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_SOUND_ONOFF_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,FMRADIO_IMG_SOUND_ON}})
            WdgImageSetDataByIDRC(FMRADIO_IMG_SOUND_ON)
        WdgEnd(CLSID_IMAGEWIDGET,SoundOnOffImageWdg)
#else
        WdgBegin(CLSID_IMAGEWIDGET,VolumeBgImageWdg)
            WdgImageCreateForWndRC({{VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_BG_IMAGEWIDGET_X_POSITION,VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_BG_IMAGEWIDGET_Y_POSITION},{VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_BG_IMAGEWIDGET_WIDTH,VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_BG_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_VOLUME_PROGRESS_BG}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_VOLUME_PROGRESS_BG)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeBgImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,VolumeImageWdg)
            WdgImageCreateForWndRC({{VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_IMAGEWIDGET_X_POSITION,VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_IMAGEWIDGET_Y_POSITION},{VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_IMAGEWIDGET_WIDTH,VIDEOPLAYERAPP_PANEL_VOLUME_LEVEL_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,VIDEOPLAYER_IMG_VOLUME_LEVEL}})
            WdgImageSetDataByIDRC(VIDEOPLAYER_IMG_VOLUME_LEVEL)
        WdgEnd(CLSID_IMAGEWIDGET,VolumeImageWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_MINUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_VOLUME_DECREASE_UNPRESSED,VIDEOPLAYER_IMG_VOLUME_DECREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumeMinusButtonWdg)

        WdgBegin(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)
            WdgButtonCreateForWndRC({{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_X_POSITION,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_Y_POSITION},{FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_WIDTH,FMR_MAIN_PANEL_VOLUME_PLUS_BUTTONWIDGET_HEIGHT},0 })
            WdgButtonSetDataByIDRC({TXT_NULL_ID,VIDEOPLAYER_IMG_VOLUME_INCREASE_UNPRESSED,VIDEOPLAYER_IMG_VOLUME_INCREASE_PRESSED})
        WdgEnd(CLSID_BUTTONWIDGET,VolumePlusButtonWdg)
#endif
#if defined(__MMI_BATTERY_ICON_DISPLAY__)
        WdgBegin(CLSID_IMAGEWIDGET,BatteryImageWdg)
            WdgImageCreateForWndRC({{FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_X_POSITION,FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_Y_POSITION},{FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_WIDTH,FMR_MAIN_PANEL_BATTERY_IMAGEWIDGET_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,STATUSBAR_IMG_BATTERY_LEVEL4_1}})
            WdgImageSetDataByIDRC(STATUSBAR_IMG_BATTERY_LEVEL4_1)
        WdgEnd(CLSID_IMAGEWIDGET,BatteryImageWdg)
#endif

        WdgBegin(CLSID_INDICATORWIDGET,FreqIndicatorWdg)
            WdgIndicatorCreateForWndRC({{FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_X_POSITION,FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_Y_POSITION},{FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_WIDTH,FMR_MAIN_PANEL_FREQ_INDICATORWIDGET_HEIGHT},LAYOUT_STYLE_HORIZONTAL})
            WdgIndicatorSetDataRC({FMR_FREQ_IND__START_RS,FMR_FREQ_IND__END_RS,FMR_FREQ_IND__POS_RS})
            WdgIndicatorSetBGImageIDRC(FMRADIO_IMG_SLIDE_BG)
            WdgIndicatorSetINDImageIDRC(FMRADIO_IMG_SLIDE)
            WdgIndicatorSetFGLeftOffsetRC(FMR_FREQ_IND_PADDING_LEFT)
            WdgIndicatorSetFGRightOffsetRC(FMR_FREQ_IND_PADDING_RIGHT)
            WdgIndicatorSetFGTopOffsetRC(FMR_FREQ_IND_PADDING_TOP)
            WdgIndicatorSetFGBottomOffsetRC(FMR_FREQ_IND_PADDING_BOTTOM)
            WdgIndicatorSetINDOffsetRC(FMR_FREQ_IND_IND_OFFSET)
        WdgEnd(CLSID_INDICATORWIDGET,FreqIndicatorWdg)

        WdgBegin(CLSID_TEXTWIDGET,PosTextWdg)
            WdgTextCreateForWndRC({{FMR_MAIN_PANEL_TEXTWDG_COUNT_X,FMR_MAIN_PANEL_TEXTWDG_COUNT_Y},{FMR_MAIN_PANEL_TEXTWDG_COUNT_WIDTH,FMR_MAIN_PANEL_TEXTWDG_COUNT_HEIGHT},TEXT_STYLE_COMMON })
#ifndef __APP_MMI_SMALLROM__
            WdgCommonSetFontCategoryRC(FONT_CAT_NUM_NORMAL)
#else
            WdgCommonSetFontCategoryRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_FONT)
#endif
            WdgCommonSetTextColorRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_COLOR)
            WdgCommonSetAlignmentRC(FMR_MAIN_PANEL_TEXTWDG_COUNT_ALIGN)
        WdgEnd(CLSID_TEXTWIDGET,PosTextWdg)
    WndEnd(FMRAPP_WND_MAIN)
#endif // __3D_UI_FMRADIO__

    WndBegin(FMRAPP_WND_AUTOSEARCHLIST)
        WdgBegin(CLSID_NUMERIC_MENUWIDGET,AutoSearchMenuWdg)
            VtmCreateMenuRC({TOOLS_BLUETOOTH_IMG_SEARCH_ANIM,TXT_CCL_N_FMR_AUTO_SEARCHING,WDG_MENU_TYPE_NORMAL,WDG_MENU_ITEM_TYPE_IMAGETEXT_IMAGE,WDG_MENU_CHECK_STYLE_NONE,0,0,0})
        WdgEnd(CLSID_NUMERIC_MENUWIDGET,AutoSearchMenuWdg)
    WndEnd(FMRAPP_WND_AUTOSEARCHLIST)

    WndBegin(FMRAPP_WND_MAIN_OPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU, VtmOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 13})
            VtmCreateOptionMenuDataRC(13, {
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_RADIO_ON_OFF}, TXT_OIL1_N_FMR_RADIO_ON},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_PAUSE_RECORD}, TXT_OIL1_N_FMR_PAUSE_RECORD},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_RESUME_RECORD}, TXT_OIL1_N_FMR_RESUME_RECORD},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_STOP_RECORD}, TXT_OIL1_N_FMR_STOP_RECORD},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_MY_CHANNEL}, TXT_OIL1_N_FMR_MY_CHANNEL},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_ADD_CHANNEL}, TXT_OIL1_N_FMR_ADD_MY_CHANNEL},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_ADD_ALL_CHANNEL}, TXT_CCL_N_FMR_ADD_ALL_TO_MY_CHANNEL},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_MANUAL_INPUT}, TXT_OIL1_N_FMR_MANUAL_INPUT},
            {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_SEARCH_CHANNEL}, TXT_CCL_N_FMR_SEARCH_CHANNEL},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_RECORD}, TXT_OIL1_N_RECORD},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_APPEND_RECORD}, TXT_OIL1_N_APPEND_RECORD},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_VIEW_RECORD_FILES}, TXT_OIL1_N_VIEW_RECORD_FILES},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_SETTINGS}, TXT_OIL1_N_SETTINGS}
            })
        WdgEnd(CLSID_VTMOPTIONMENU,VtmOptionMenu)
    WndEnd(FMRAPP_WND_MAIN_OPTIONMENU)

    WndBegin(FMRAPP_WND_MYCHANNELLIST)
        WndSetTitleRC(IMG_NULL_ID,TXT_OIL1_N_FMR_MY_CHANNEL)

        WdgBegin(CLSID_NUMERIC_MENUWIDGET,MyChannelMenuWdg)
            WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_SINGLE_LINE_MENU_ICON_HEIGHT*FMR_RS_HEIGHT_MUL},WDG_MENU_TYPE_NUMERIC})
        WdgEnd(CLSID_NUMERIC_MENUWIDGET,MyChannelMenuWdg)

        WdgBegin(CLSID_TEXTWIDGET,FreqThmTextWdg)
            WdgTextCreateForWndRC({{0,MAIN_TITLE_HEIGHT+MAIN_SINGLE_LINE_MENU_ICON_HEIGHT*FMR_RS_HEIGHT_MUL},{MAIN_LCD_WIDTH,MAIN_SINGLE_LINE_MENU_ICON_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_LIL_N_FREQUENCY)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER | ALIGN_V_MIDDLE)
        WdgEnd(CLSID_TEXTWIDGET,FreqThmTextWdg)
    WndEnd(FMRAPP_WND_MYCHANNELLIST)

    WndBegin(FMRAPP_WND_MYCHANNELLIST_OPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU, VtmMyChListOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 4})
            VtmCreateOptionMenuDataRC(4, {
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_PLAY}, TXT_OIL1_N_PLAY},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_EDIT}, TXT_LIL_N_EDIT},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_REMOVE}, TXT_OIL1_N_REMOVE},
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_OK, SK_BACK}, FMR_OPTION_MENU_ITEM_REMOVE_ALL}, TXT_OIL1_N_REMOVE_ALL}
            })
        WdgEnd(CLSID_VTMOPTIONMENU,VtmMyChListOptionMenu)
    WndEnd(FMRAPP_WND_MYCHANNELLIST_OPTIONMENU)

    WndBegin(FMRAPP_WND_EDITCHANNEL_MAIN)
        WndSetTitleRC(IMG_NULL_ID,TXT_TTL_N_FMR_EDIT_CHANNEL)
        WdgBegin(CLSID_MENUWIDGET,EditMenuWdg)
            WdgMenuCreateForWndRC({{0,MAIN_TITLE_HEIGHT},{MAIN_LCD_WIDTH,MAIN_LCD_TWOLINE_HEIGHT*2},WDG_MENU_TYPE_NORMAL})
        WdgEnd(CLSID_MENUWIDGET,EditMenuWdg)
    WndEnd(FMRAPP_WND_EDITCHANNEL_MAIN)

    WndBegin(FMRAPP_WND_EDITCHANNEL_EDITNAME)
        WdgBegin(CLSID_VTMINPUT, VtmEditChEditName)
            VtmCreateInputRC({IMG_NULL_ID, TXT_LIL_N_FMR_CHANNEL_NAME, FMR_NAME_MAX_BYTE_SIZE_RS, FALSE})
        WdgEnd(CLSID_VTMINPUT, VtmEditChEditName)
    WndEnd(FMRAPP_WND_EDITCHANNEL_EDITNAME)

    WndBegin(FMRAPP_WND_EDITCHANNEL_EDITNAME_OPTIONMENU)
        WdgBegin(CLSID_VTMOPTIONMENU, VtmEditNameOptionMenu)
            VtmCreateOptionMenuRC({WDG_MENU_ITEM_TYPE_TEXT, 2})
            VtmCreateOptionMenuDataRC(2, {
            {{MENUMODEL_ITEM_VISABLE, {SK_SELECT, SK_SELECT, SK_BACK}, FMR_OPTION_MENU_ITEM_OK}, TXT_LSK_N_OK},
            {{MENUMODEL_ITEM_VISABLE | MENUMODEL_ITEM_HAS_CHILD, {SK_SELECT, SK_SELECT, SK_BACK}, FMR_OPTION_MENU_ITEM_INPUT_MENU}, TXT_OIL1_N_INPUT_MENU}
            })
        WdgEnd(CLSID_VTMOPTIONMENU, VtmEditNameOptionMenu)
    WndEnd(FMRAPP_WND_EDITCHANNEL_EDITNAME_OPTIONMENU)

    WndBegin(FMRAPP_WND_EDITCHANNEL_EDITFREQ)
        WdgBegin(CLSID_VTMPOPUPPROMPT, VtmEditChEditFreq)
            VtmCreatePopUpPromptRC({IMG_NULL_ID, IMG_NULL_ID, TXT_LIL_N_FMR_CHANNEL_FREQUENCY, TXT_PML_N_FM_FREQUENCY_RANGE})
				VTMWdgBegin (CLSID_INPUTWIDGET, POP_UP_PROMPT_INPUT_WDG, VtmInputWdg)
					WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
					WdgInputSetDecimalPointEnableRC(TRUE)
					WdgInputSetMaxlenAfterExponentRC(FMR_FREQ_MAXLEN_AFTER_EXPONENT)
					WdgInputSetMaxByteLengthRC(FMR_FREQ_MAX_BYTE_SIZE_RS)
					WdgInputSetDisableSwitchInputModeRC(TRUE)
					WdgCommonSetFontCategoryRC(FMR_EDIT_INPUT_CHANNEL_FONT_SIZE)
				VTMWdgEnd (CLSID_INPUTWIDGET, POP_UP_PROMPT_INPUT_WDG, VtmInputWdg)
        WdgEnd(CLSID_VTMPOPUPPROMPT, VtmEditChEditFreq)
    WndEnd(FMRAPP_WND_EDITCHANNEL_EDITFREQ)

    WndBegin(FMRAPP_WND_MANUALINPUT)
        WndSetAllSoftkeyRC({SK_NONE, SK_NONE, SK_CANCEL})
        WdgBegin(CLSID_VTMPOPUPPROMPT, VtmManualInput)
            VtmCreatePopUpPromptRC({IMG_NULL_ID, IMG_NULL_ID, TXT_LIL_N_FMR_CHANNEL_FREQUENCY, TXT_PML_N_FM_FREQUENCY_RANGE})
				VTMWdgBegin (CLSID_INPUTWIDGET, POP_UP_PROMPT_INPUT_WDG, VtmInputWdgManual)
					WdgInputSetCurrentInputModeRC(MAE_INPUTMODE_RATE)
					WdgInputSetDecimalPointEnableRC(TRUE)
					WdgInputSetMaxlenAfterExponentRC(FMR_FREQ_MAXLEN_AFTER_EXPONENT)
					WdgInputSetMaxByteLengthRC(FMR_FREQ_MAX_BYTE_SIZE_RS)
					WdgInputSetDisableSwitchInputModeRC(TRUE)
					WdgCommonSetFontCategoryRC(FMR_EDIT_INPUT_CHANNEL_FONT_SIZE)
				VTMWdgEnd (CLSID_INPUTWIDGET, POP_UP_PROMPT_INPUT_WDG, VtmInputWdgManual)
        WdgEnd(CLSID_VTMPOPUPPROMPT, VtmManualInput)
    WndEnd(FMRAPP_WND_MANUALINPUT)

    WndBegin(FMRAPP_WND_SETTINGS)
        WndSetTitleRC(IMG_NULL_ID,TXT_LIL_N_SETTINGS)
        WndSetAllSoftkeyRC({SK_CHANGE, SK_OK, SK_BACK})
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,BgPlayTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(2, {0,{IMG_NULL_ID,TXT_OIL1_N_BACKGOUND_PLAY}},{ {IMG_NULL_ID,TXT_LIL_N_OFF},{IMG_NULL_ID,TXT_LIL_N_ON} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,BgPlayTextPickWidget)
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,SpeakerTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(2, {0,{IMG_NULL_ID,TXT_OIL1_N_SPEAKER}},{ {IMG_NULL_ID,TXT_LIL_N_OFF},{IMG_NULL_ID,TXT_LIL_N_ON} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,SpeakerTextPickWidget)
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordTypeTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(4, {0,{IMG_NULL_ID,TXT_LIL_N_VOICE_FORMAT}},{ {IMG_NULL_ID,TXT_LIL_N_VOICE_QUALITY_LOW_AMR}, {IMG_NULL_ID,TXT_LIL_N_VOICE_QUALITY_NORMAL_AWB}, {IMG_NULL_ID,TXT_LIL_N_VOICE_QUALITY_HIGH_MP3}, {IMG_NULL_ID,TXT_LIL_N_VOICE_QUALITY_HIGH_WAV} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordTypeTextPickWidget)
        WdgBegin(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordStorageTextPickWidget)
            WdgCommonPickCreateForWndRC({{0,0},{0,0},COMMONPICK_STYLE_LINE2INFOPICK_TEXTWIDGET})
            WdgCommonPickSetDataByIDRC(3, {0,{IMG_NULL_ID,TXT_OIL1_N_STORAGE}},{ {IMG_NULL_ID,TXT_LIL_N_CARD}, {IMG_NULL_ID,TXT_LIL_N_CARD2},{IMG_NULL_ID,TXT_LIL_N_PHONE} })
        WdgEnd(CLSID_LINE2INFOPICK_TEXTWIDGET,RecordStorageTextPickWidget)
    WndEnd(FMRAPP_WND_SETTINGS)

    WndBegin(FMRAPP_WND_SETRECORDTYPE)
        WdgBegin(CLSID_VTMPOPUPSELECT,RecordTypeVtmSelect)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,4,0,0})
            VtmCreatePopUpSelectDataRC(4,{ {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_LOW_QUALITY},TXT_LIL_N_VOICE_QUALITY_LOW_AMR},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_NORMAL_QUALITY},TXT_LIL_N_VOICE_QUALITY_NORMAL_AWB},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_HIGH_QUALITY},TXT_LIL_N_VOICE_QUALITY_HIGH_MP3},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_HIGH_QUALITY_2},TXT_LIL_N_VOICE_QUALITY_HIGH_WAV}
                                            })
        WdgEnd(CLSID_VTMPOPUPSELECT,RecordTypeVtmSelect)
    WndEnd(FMRAPP_WND_SETRECORDTYPE)

/*
    WndBegin(FMRAPP_WND_SETRECORDSTORAGE)
        WdgBegin(CLSID_VTMPOPUPSELECT,RecordStorageVtmSelect)
            VtmCreatePopUpSelectRC({NULL,WDG_MENU_ITEM_TYPE_TEXT,WDG_MENU_CHECK_STYLE_RADIO,3,0,0})
            VtmCreatePopUpSelectDataRC(3,{  {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_STORAGE_PHONE},TXT_LIL_N_PHONE},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_STORAGE_CARD},TXT_LIL_N_CARD},
                                            {{MENUMODEL_ITEM_VISABLE,{DEFAULT_SK,DEFAULT_SK,DEFAULT_SK},FMR_RECORD_STORAGE_CARD2},TXT_LIL_N_CARD2} })
        WdgEnd(CLSID_VTMPOPUPSELECT,RecordStorageVtmSelect)
    WndEnd(FMRAPP_WND_SETRECORDSTORAGE)
*/
ApEnd(RS,CLSID_FMRADIOAPP)
