ApBegin(RS,CLSID_MAINMENUAPP)
    WndBegin(WND_GRID)
        WndSetTitleRC(MAINMENU_IMG_GRID_TITLE, TXT_NULL_ID)
        WdgBegin(CLSID_MENUWIDGET,GridMenuWdg)
	WdgMenuCreateForWndRC({{0, MAIN_TITLE_HEIGHT},{MAINMENUAPP_MAINVIEW_WIDTH,MAINMENUAPP_MAINVIEW_HEIGHT},WDG_MENU_TYPE_IMG_GRID})
#ifdef  __MMI_KING_MOVIE__
	WdgCommonSetBGImageIdRC(MAINMENU_IMG_KM_BG)
#else
	WdgCommonSetBGImageIdRC(THM_MAINMENU_IMG_BG)
#endif
	WdgMenuSetItemFocusImageRC(IMG_NULL_ID)
	WdgCommonSetPaddingDataRC({MAINMENUAPP_GRID_LEFT_PADDING, MAINMENUAPP_GRID_RIGHT_PADDING, MAINMENUAPP_GRID_TOP_PADDING, MAINMENUAPP_GRID_BOTTOM_PADDING})
        WdgEnd(CLSID_MENUWIDGET, GridMenuWdg)
    WndEnd(WND_GRID)
#ifndef __APP_MMI_SMALLROM__
    WndBegin(WND_LIST)
        WdgBegin(CLSID_MENUWIDGET, ListMenuWdg)
            WdgMenuCreateForWndRC({{0, MAIN_TITLE_HEIGHT},{MAINMENUAPP_MAINVIEW_WIDTH,MAINMENUAPP_MAINVIEW_HEIGHT},WDG_MENU_TYPE_NORMAL})
            WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
            WdgMenuSetItemHeightRC(MAINMENUAPP_LIST_MENU_ITEM_HEIGHT)
            WdgITISetPreImageWidthRC(MAINMENUAPP_LIST_ITI_IMG_PREIMAGE_WIDTH)
            WdgITISetPreImagePrePaddingRC(MAINMENUAPP_LIST_ITI_IMG_PRE_PENDDING)
            WdgITISetTextPrePaddingRC(MAINMENUAPP_LIST_ITI_TXT_PRE_PENDDING)
        WdgEnd(CLSID_MENUWIDGET,ListMenuWdg)
    WndEnd(WND_LIST)
#endif
    WndBegin(WND_SUB)
        WdgBegin(CLSID_MENUWIDGET,SubMenuWdg)
			WdgMenuCreateForWndRC({{0, MAIN_TITLE_HEIGHT},{MAINMENUAPP_MAINVIEW_WIDTH,MAINMENUAPP_MAINVIEW_HEIGHT},WDG_MENU_TYPE_NUMERIC})	
			WdgMenuSetCheckStyleRC(WDG_MENU_CHECK_STYLE_NONE)
        WdgEnd(CLSID_MENUWIDGET,SubMenuWdg)
    WndEnd(WND_SUB)

    WndBegin(WND_SPIN)
        WdgBegin(CLSID_IMAGEWIDGET,BGWdg)
            WdgImageCreateForWndRC({{MAINMENUAPP_SPIN_BG_X,MAINMENUAPP_SPIN_BG_Y},{MAINMENUAPP_SPIN_BG_WIDTH,MAINMENUAPP_SPIN_BG_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,MAIN_MENU_BG}})	
        WdgEnd(CLSID_IMAGEWIDGET,BGWdg)

        WdgBegin(CLSID_TEXTWIDGET,TextWdg)
			WdgTextCreateForWndRC({{MAINMENUAPP_TRANSFER_LEFT_X,MAINMENUAPP_TRANSFER_LEFT_Y},{MAINMENUAPP_TRANSFER_WIDTH,MAINMENUAPP_TRANSFER_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetTextColorRC(DEF_THM_MAINMENUAPP_TEXT)
            WdgTextSetTextOutlineColorRC(DEF_THM_MAINMENUAPP_TEXT_OUTLINE)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetAlignmentRC(ALIGN_V_MIDDLE|ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,TextWdg)

        WdgBegin(CLSID_IMAGEWIDGET,MImgWdg)
			WdgImageCreateForWndRC({{MAINMENUAPP_STATIC_MIDDLE_X,MAINMENUAPP_STATIC_MIDDLE_Y},{MAINMENUAPP_STATIC_MIDDLE_WIDTH,MAINMENUAPP_STATIC_MIDDLE_HEIGHT},IMAGE_STYLE_COMMON,{TRUE,IMG_NULL_ID}})	
        WdgEnd(CLSID_IMAGEWIDGET,MImgWdg)
		
        WdgBegin(CLSID_MENUWIDGET,SpinMenuWdg)
            WdgMenuCreateForWndRC({{MAINMENUAPP_THUMBNAIL_MENU_X, MAINMENUAPP_THUMBNAIL_MENU_Y},{MAINMENUAPP_THUMBNAIL_MENU_WIDTH,MAINMENUAPP_THUMBNAIL_MENU_HEIGHT},WDG_MENU_TYPE_IMG_GRID})
            WdgCommonSetBGImageIdRC(MAIN_MENU_THUMBNAIL_BG)
        WdgEnd(CLSID_MENUWIDGET,SpinMenuWdg)
    WndEnd(WND_SPIN)

    WndBegin(WND_SPIN3D)
        WndSetSoftkeyVisibleRC(FALSE)
        WndSetStatusBarVisibleRC(FALSE)
    WndEnd(WND_SPIN3D) 
  
#ifdef __MAINMENUIFONE_PRELOAD_ANIMBMP__
    WndBegin(WND_IFONE_INITIAL)
        WndSetSoftkeyVisibleRC(FALSE)
        WndSetStatusBarVisibleRC(FALSE)

        WdgBegin(CLSID_IMAGEWIDGET,BGImageWdg)
            WdgImageCreateForWndRC({{MAIN_BG_X, MAIN_BG_Y},{MAINMENUAPP_IFONE_MAINVIEW_WIDTH, MAINMENUAPP_IFONE_MAINVIEW_HEIGHT},IMAGE_STYLE_COMMON,{FALSE, 0}})
        WdgEnd(CLSID_IMAGEWIDGET,BGImageWdg)

        WdgBegin(CLSID_FADEOUTWIDGET,DarkBGWdg)
            WdgFadeoutCreateForWndRC({{MAINMENUAPP_IFONE_INITIAL_DRAK_X, MAINMENUAPP_IFONE_INITIAL_DRAK_Y},{MAINMENUAPP_IFONE_INITIAL_DRAK_WIDTH, MAINMENUAPP_IFONE_INITIAL_DRAK_HEIGHT},FADEOUT_LEVEL_4})
        WdgEnd(CLSID_FADEOUTWIDGET,DarkBGWdg)

        WdgBegin(CLSID_IMAGEWIDGET,AnimImageWdg)
            WdgImageCreateForWndRC({{MAINMENUAPP_IFONE_INITIAL_ANIM_X, MAINMENUAPP_IFONE_INITIAL_ANIM_Y},{MAINMENUAPP_IFONE_INITIAL_ANIM_WIDTH, MAINMENUAPP_IFONE_INITIAL_ANIM_HEIGHT},IMAGE_STYLE_COMMON,{FALSE, TOOLS_BLUETOOTH_IMG_SEARCH_ANIM}})
        WdgEnd(CLSID_IMAGEWIDGET,AnimImageWdg)

        WdgBegin(CLSID_TEXTWIDGET,StatusTextWdg)
            WdgTextCreateForWndRC({{MAINMENUAPP_IFONE_INITIAL_TEXT_X,MAINMENUAPP_IFONE_INITIAL_TEXT_Y},{MAINMENUAPP_IFONE_INITIAL_TEXT_WIDTH,MAINMENUAPP_IFONE_INITIAL_TEXT_HEIGHT},0})
        WdgEnd(CLSID_TEXTWIDGET,StatusTextWdg)

    WndEnd(WND_IFONE_INITIAL)
#endif
    WndBegin(WND_IFONE_EDITFOLDERNAME)
        VtmCreateInputRC({0, 0, 0, FALSE})
    WndEnd(WND_IFONE_EDITFOLDERNAME)
ApEnd(RS,CLSID_MAINMENUAPP)

