#ifndef __MMI_ALARMAPP_ID_H__
#define __MMI_ALARMAPP_ID_H__

#define ALARM_RECORDS_MAX_NUM_RS 6

typedef enum
{
    ALARM_WND_ALARMLIST = WND_ID_APP_BASE,
    ALARM_WND_SETALARM,
    ALARM_WND_SETTITLE,
    ALARM_WND_SETTITLE_LOADOPTIONMENU,
    ALARM_WND_SETFREQUENCY,
    ALARM_WND_VIEWALARM,
    ALARM_WND_FILEMGR
} AlarmWndId_e;

typedef enum
{
    ALARMAPP_ALARMLIST_VIEW_BEGIN = APP_WDG_START,
}AlarmListViewId_e;

typedef enum
{
    ALARMAPP_SETALARM_VIEW_BEGIN = APP_WDG_START,
    ALARMAPP_SETALARM_SCROLLBARWIDGET,
    ALARMAPP_SETALARM_MFLCONTAINER,
    ALARMAPP_SETALARM_TITLE_DOUBLETEXTWIDGET,
    ALARMAPP_SETALARM_TIME_TEXTTIMEWIDGET,
    ALARMAPP_SETALARM_STATUS_TEXTPICKWIDGET,
    ALARMAPP_SETALARM_FREQUENCY_DOUBLETEXTWIDGET,
    ALARMAPP_SETALARM_RINGTONE_DOUBLETEXTWIDGET,
}AlarmSetViewId_e;

typedef enum
{
    ALARMAPP_SETTITLE_VIEW_BEGIN = APP_WDG_START,
}AlarmTitleViewId_e;

typedef enum
{
    ALARMAPP_SETTITLELOADOPTIONMENU_VIEW_BEGIN = APP_WDG_START,
}AlarmOptionMenuViewId_e;

typedef enum
{
    ALARMAPP_SETFREQUENCY_VIEW_BEGIN = APP_WDG_START,
}AlarmFrequencyViewId_e;

typedef enum
{
    ALARMAPP_VIEWALARM_VIEW_BEGIN = APP_WDG_START,
}AlarmViewAlarmId_e;

typedef enum
{
    ALARMAPP_FILEMGR_VIEW_BEGIN = APP_WDG_START,
}AlarmFilemgrViewId_e;

#endif //__MMI_ALARMAPP_ID_H__

