////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

/**
* @file    mmi_android_mainitem.h
* @version
* @brief
*
*/
#ifdef __UI_STYLE_MMI_ANDROID_MAIN_MENU__
#ifndef 	__MMI_ANDROID_MENUITEM_H_
#define 	__MMI_ANDROID_MENUITEM_H_

#include "mmi_mae_common_def.h"
#include "mmi_clstbl.h"
#include "mmi_cfgsrv.h"
#include "mmi_sssrv_def.h"
#include "mmi_stksrv_def.h"
#include "mmi_ccsrv.h"
#include "mmi_evtcentersrv.h"

#include "mmi_camapp.h"
#include "mmi_calllogapp.h"
#include "mmi_messagecenterapp.h"
#include "mmi_settingapp.h"
#include "mmi_evtcenterapp.h"
#include "mmi_shortcutsapp.h"
#include "mmi_ccapp.h"
#include "mmi_emapp.h"
#include "mmi_keyguardapp.h"
#include "mmi_phbapp.h"
#include "mmi_secapp.h"
#include "mmi_mplayerapp.h"
#include "mmi_offapp.h"
#include "mmi_filemgrapp.h"

#if defined(__YOUTUBE_MMI_CDWAP__) || defined(__YOUKU_MMI_CDWAP__) || defined(__VUCLIP_MMI_CDWAP__) || defined(__BAIDU_MMI_CDWAP__)
#include "mmi_cdwapapp.h"
#endif

#include "mmi_common_content.h"
#include "mae_textlabel.h"
#include "img_data.h"
#include "mmi_android_mainmenuapp_id.h"
#include "Rs_layout_id.h"

#ifdef __APP_MMI_FM_SCHEDULE__
#include "mmi_fmschapp.h"
#endif
#include "mmi_common_menu.h"

//Start Menu Item UserData Num
#define ANDROIDUSERDATA_NUM	 	1	//now must 	>=1
#define ANDROIDITEM_VISABLE_MASK				0x0001
#define ANDROIDITEM_MOVABLE_MASK				0x0002
//flag bit function
// 	15	14	13	12	11	10	09	08	07	06	05	04	03	02	01	00
//	 														 | 	 |
//	 													     	 |	 +------------visable
//	 														+----------------movable
typedef struct
{
	u16 nId;		//menu item id
	u16 nParentId;	//Parent menu item id
	u32 nTextId;	//text 	id
	u32	nImgId;		//image id
	u16	nClsId;		//class id
	u32 nParam;		//start param
	u16 nFlag;		//flag (visable, movable, ...)
	u32 nUserData[ANDROIDUSERDATA_NUM]; //
}AndroidMenuItemData_t;

//android  style
static const AndroidMenuItemData_t g_CellMenuData[]={
// nId 					nParentId	nTextId						nImgId							nClsId				nParam			nFlag
{MNU_MAIN_ANDROID_DIALING,		      MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_DIAL,		IDLE_ANDROID_INPUT_NUMBER,		CLSID_DIALERAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},//from g3d
{MNU_MAIN_ANDROID_MESSAGES,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_MESSAGES,		IDLE_ANDROID_MESSAGE_MAIN,		CLSID_MCA,				0/*(u32)&_g_MCA*/, 					ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_CALL_HISTORY,	MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_CALL_HISTORY,	IDLE_ANDROID_CALLLOG_MAIN,		CLSID_CALLLOGAPP,		MMI_CALLLOG_AP_SHOW_ALL_LIST,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_PHONE_BOOK,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_PHONEBOOK,		IDLE_ANDROID_PHB_MAIN,		CLSID_PHBAP,			0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_FILE_MANAGER,	MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_FILE_MANAGER,	IDLE_ANDROID_FILEMGR_MAIN,		CLSID_FILEMGRAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},
#ifdef __MMI_KING_MOVIE__
#ifdef __MMI_KING_MOVIE_3D_APP_INDIE__
{MNU_MAIN_ANDROID_KINGMOVIE,        MNU_MAIN_ANDROID_MAIN,    TXT_LIL_N_KING_MOVIE,     IDLE_ANDROID_KINGMOVIE_MAIN,   CLSID_MAINMENUAPP,      MAINMENU_SUBMENU_KMV,    ANDROIDITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_ANDROID_KINGMOVIE,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_KING_MOVIE,		IDLE_ANDROID_KINGMOVIE_MAIN,		CLSID_KINGMOVIEAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ANDROID_MULTIMEDIA,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_MULTIMEDIA,		IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_ANDROID_MULTIMEDIA,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_MULTIMEDIA,		IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_PROFILES,			MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_PROFILES,			IDLE_ANDROID_PROFILE_MAIN,		CLSID_PROFILEAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ANDROID_ORGANIZER,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_ORGANIZER,		IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_GAMES,			MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_GAMES,			IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_TOOLS,			MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_TOOLS,			IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_APPLICATIONS,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_APPLICATIONS,		IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_SETTINGS,			MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_SETTINGS,			IDLE_ANDROID_SETTING_MAIN,		CLSID_SETTINGAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_SERVICES,		MNU_MAIN_ANDROID_MAIN,	  TXT_LIL_N_SERVICES,		IDLE_ANDROID_MESSAGE_MAIN,		0,						0,								ANDROIDITEM_VISABLE_MASK, {0}},
//Message
{MNU_MSG_MCA_ANDROID_MESSAGE_CENTER,	MNU_MAIN_ANDROID_MESSAGES,		IDLE_ANDROID_MESSAGE_MAIN,	IMG_NULL_ID,			CLSID_MCA,			  	 MCA_E_START_MENU,				 ANDROIDITEM_VISABLE_MASK, {0}},
//Services
#ifdef __RFID_MMI__
{MNU_MAIN_ANDROID_RFID_FUNC,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_RFID_DEMO,		IMG_NULL_ID,	CLSID_RFIDDEMOAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __WAP_MMI__
{MNU_MAIN_ANDROID_WAP_EXPLORER,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_CDW_WAP_EXPLORER,	IDLE_ANDROID_CDWAP_MAIN,	CLSID_CDWAPAPP,			0,		ANDROIDITEM_VISABLE_MASK, {0}},

#ifdef __YOUTUBE_MMI_CDWAP__
{MNU_MAIN_ANDROID_YOUTUBE,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_CDW_YOUTUBE,	IDLE_ANDROID_YOUTUBE_MAIN,	CLSID_CDWAPAPP,			CDWAP_OPEN_YOUTUBE,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __YOUKU_MMI_CDWAP__
{MNU_MAIN_ANDROID_YOUKU,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_CDW_YOUKU,	IDLE_ANDROID_YOUKU_MAIN,	CLSID_CDWAPAPP,			CDWAP_OPEN_YOUKU,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __VUCLIP_MMI_CDWAP__
{MNU_MAIN_ANDROID_VUCLIP,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_CDW_VUCLIP,	IDLE_ANDROID_VUCLIP_MAIN,	CLSID_CDWAPAPP,			CDWAP_OPEN_VUCLIP,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __BAIDU_MMI_CDWAP__
{MNU_MAIN_ANDROID_BAIDU,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_CDW_BAIDU,	IDLE_ANDROID_BAIDU_MAIN,	CLSID_CDWAPAPP,			CDWAP_OPEN_BAIDU,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#endif
#ifdef __EMAIL_MMI__
{MNU_MAIN_ANDROID_EMAIL, MNU_MAIN_ANDROID_SERVICES, TXT_LIL_N_EMAIL, IDLE_ANDROID_EMAIL, CLSID_EMAILAPP, 0, ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __BLUETOOTH_MMI__
{MNU_MAIN_ANDROID_BLUETOOTH,		MNU_MAIN_ANDROID_SERVICES,		TXT_LTL_N_BLUETOOTH,		IDLE_ANDROID_BLUETOOTH_MAIN,	CLSID_BTAPP,			0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ANDROID_SIM_SERVICE_1,MNU_MAIN_ANDROID_SERVICES,		TXT_NULL_ID,					IDLE_ANDROID_STK_MAIN,	CLSID_STKAPP,			STKSRV_CMD_SETUPMENU,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_SIM_SERVICE_2,MNU_MAIN_ANDROID_SERVICES,		TXT_NULL_ID,					IDLE_ANDROID_STK_MAIN,	CLSID_STKAPP2,			STKSRV_CMD_SETUPMENU,	ANDROIDITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_EVENTCENTER__
{MNU_MAIN_ANDROID_EVENT_CENTER,	MNU_MAIN_ANDROID_SERVICES,		TXT_LIL_N_EVENT_CENTER,	IDLE_ANDROID_EVTCENT_MAIN,	CLSID_EVTCENTERAPP,		EvtCenterApp_Start_AllEvtSummary,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE__
{MNU_MAIN_ANDROID_SXM_VIDEO_CHAT,  MNU_MAIN_ANDROID_SERVICES,     	TXT_OIL2_N_VIDEO_CHAT,                           IDLE_ANDROID_VIDEOCHAT_MAIN,    CLSID_SXM_VCHAT,    0x0300009a, ANDROIDITEM_VISABLE_MASK, {0}},
#ifdef __SXMENGINE_BOOKSTORE__
//{MNU_MAIN_ANDROID_SXM_LIBRARY,     MNU_MAIN_ANDROID_SERVICES,     	TXT_LIL_N_POI_EDUCATION_BOOK_STORE,         IDLE_ANDROID_LIBRARY_MAIN,    CLSID_SXM_BOOK,     0x0300000B, ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE_GAME__
//{MNU_MAIN_ANDROID_SXM_GAMES,       MNU_MAIN_ANDROID_SERVICES,      	TXT_DSL_N_GAME,                             IDLE_ANDROID_GAME_MAIN,    CLSID_SXM_GAME,     0x03000000, ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#endif
//Tool
#ifdef __APP_MMI_CALCULATOR__
{MNU_MAIN_ANDROID_CALCULATOR,			MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_CALCULATOR,		IDLE_ANDROID_CALCULATOR_MAIN,	CLSID_CALCULATORAPP,	0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_CALCULATOR_PLUS__
{MNU_MAIN_ANDROID_CALCULATOR,			MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_CALCULATOR,		IDLE_ANDROID_CALCULATOR_MAIN,	CLSID_CALCULATORPLUSAPP,	0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_UNITCONVERTER__
{MNU_MAIN_ANDROID_UNIT_CONVERTER,		MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_CONVERTER,		IDLE_ANDROID_CONVERTER_MAIN,	CLSID_UNITCONVERTER, 	0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_STOPWATCH__
{MNU_MAIN_ANDROID_STOPWATCH,			MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_STOPWATCH,		IDLE_ANDROID_STOPWATCH_MAIN,	CLSID_STOPWATCHAPP,		0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_COUNTDOWN_TIMER__
{MNU_MAIN_ANDROID_COUNTDOWN_TIMER,	MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_COUNTDOWN_TIMER,	IDLE_ANDROID_COUNTDOWN_MAIN,	CLSID_COUNTDOWNTIMER, 	0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_WORLDCLOCK__
{MNU_MAIN_ANDROID_WORLD_CLOCK,		MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_WORLD_CLOCK,		IDLE_ANDROID_WORLDCLOCK_MAIN,	CLSID_WORLDCLOCKAPP,	0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_SHORTCUTLIST__
{MNU_MAIN_ANDROID_SHORTCUTS,			MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_SHORTCUTS,		IDLE_ANDROID_SHORTCUT_MAIN,	CLSID_SHORTCUTSAPP,		SHORTCUTS_ENTRY_SHORTCUTS,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_BMI__
{MNU_MAIN_ANDROID_BMI,					MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_BMI,				IDLE_ANDROID_BMI_MAIN,	CLSID_BMI,				0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_LICENSEMGR__
{MNU_MAIN_ANDROID_LICENSEMGR,			MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_LICENSEMGR,		IDLE_ANDROID_LICENSE_MANAGER,	CLSID_LICENSEMGRAPP,		0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_AZAN__
{MNU_MAIN_ANDROID_AZAN,					MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_AZAN_ALARM,				IDLE_ANDROID_AZAN,	CLSID_AZANAPP,				0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __CALLER_LOCATION__
{MNU_MAIN_ANDROID_CALLERLOCATION,		MNU_MAIN_ANDROID_TOOLS,			TXT_LIL_N_CALLER_LOCATION,				IDLE_ANDROID_CALLERLOCATION,	CLSID_CALLERLOCATIONAPP,				0,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#if defined(__ENABLE_CAMERA__)
{MNU_MAIN_ANDROID_CAMERA,				MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_CAMERA,			IDLE_ANDROID_DC_MAIN,	CLSID_CAMAPP,			CAM_PICTURE_MODE,		ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#if defined(__ENABLE_CAMCORDER__)
{MNU_MAIN_ANDROID_VIDEO_RECORDER,		MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_CAMCORDER,		IDLE_ANDROID_DV_MAIN,	CLSID_CAMAPP,			CAM_VIDEO_MODE,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ANDROID_MUSIC_PLAYER,		MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_MUSIC,			IDLE_ANDROID_MPLAYER_MAIN,	CLSID_MPLAYERAPP,		MPLAYER_MODE_MUSIC, 	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_VIDEO_PLAYER,		MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_VIDEO_PLAYER,		IDLE_ANDROID_VPLAYER_MAIN,	CLSID_FILEMGRAPP,	FILEMGRAPP_VIDEO_FILE,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_PHOTO_VIEWER,		MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_PHOTOS,			IDLE_ANDROID_PHOTO_MAIN,	CLSID_FILEMGRAPP,	FILEMGRAPP_PICTURE_FILE,ANDROIDITEM_VISABLE_MASK, {0}},

#ifdef __APP_MMI_FM_RADIO__
#ifdef __APP_MMI_FM_SCHEDULE__
//{MNU_MAIN_ANDROID_FM_RADIO,			MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IMG_NULL_ID,	0,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_FM_RADIO,			MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IDLE_ANDROID_FM_MAIN,	CLSID_MAINMENUAPP,		MAINMENU_SUBMENU_FM,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_FM_RADIO,         MNU_MAIN_ANDROID_FM_RADIO,    TXT_LIL_N_FM_RADIO_PLAYER,         IMG_NULL_ID,    CLSID_FMRADIOAPP,       0,  ANDROIDITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_FM_RADIO_REC__
{MNU_MAIN_ANDROID_SCHEDULE_RECORD,   MNU_MAIN_ANDROID_FM_RADIO,  TXT_LIL_N_FM_RECORD_SCHEDULE,   IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE_RECORD,     ANDROIDITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_RADIO_REC__
{MNU_MAIN_ANDROID_FM_SCHEDULE_PLAY,     MNU_MAIN_ANDROID_FM_RADIO,  TXT_LIL_N_FM_SCHEDULE,      IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE,        ANDROIDITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_ANDROID_FM_RADIO,			MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IDLE_ANDROID_FM_MAIN,	CLSID_FMRADIOAPP,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_SCHEDULE__
#endif //__APP_MMI_FM_RADIO__

#ifdef __APP_MMI_VOICE_MEMO__
{MNU_MAIN_ANDROID_VOICE_MEMO,			MNU_MAIN_ANDROID_MULTIMEDIA,	TXT_LIL_N_VOICE_MEMO,		IDLE_ANDROID_RECODER_MAIN,	CLSID_VOICEMEMOAPP,	0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __ATV_MMI__
#ifdef __ATV_CMMB__
{MNU_MAIN_ANDROID_ATV,                          MNU_MAIN_ANDROID_MULTIMEDIA,    TXT_LIL_N_CMMB,                 IDLE_ANDROID_ATV_MAIN,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_CMMB,        ANDROIDITEM_VISABLE_MASK, {0}},
#else // !__ATV_CMMB__
{MNU_MAIN_ANDROID_ATV,                          MNU_MAIN_ANDROID_MULTIMEDIA,    TXT_LIL_N_ATV,                  IDLE_ANDROID_ATV_MAIN,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ANALOG,      ANDROIDITEM_VISABLE_MASK, {0}},
#ifdef __ATV_ISDBT__
{MNU_MAIN_ANDROID_ATV_ISDBT,                    MNU_MAIN_ANDROID_MULTIMEDIA,    TXT_LIL_N_ISDBT,                IDLE_ANDROID_ATV_ISDBT_MAIN,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ISDBT,       ANDROIDITEM_VISABLE_MASK, {0}},
#endif // __ATV_ISDBT__
#endif // __ATV_CMMB__
#endif // __ATV_MMI__
#ifdef __APP_MMI_TUDOU__
{MNU_MAIN_ANDROID_TUDOU,                          MNU_MAIN_ANDROID_MULTIMEDIA,    TXT_CCL_N_COMMON_TUDOU,                  IDLE_ANDROID_TUDOU,    CLSID_TUDOUAPP,           0,      ANDROIDITEM_VISABLE_MASK, {0}},
#endif
//organizer
#ifdef __APP_MMI_CALENDAR__
{MNU_MAIN_ANDROID_CALENDAR,			MNU_MAIN_ANDROID_ORGANIZER,		TXT_LIL_N_CALENDAR,			IDLE_ANDROID_CALENDAR_MAIN,	CLSID_CALENDARAPP,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ANDROID_ALARM,				MNU_MAIN_ANDROID_ORGANIZER,		TXT_LIL_N_ALARM,			IDLE_ANDROID_ALARM_MAIN,	CLSID_ALARMAPP,			0,	ANDROIDITEM_VISABLE_MASK, {0}},
//Game
#ifdef __APP_MMI_NOTEPAD__
{MNU_MAIN_ANDROID_NOTEPAD,        			MNU_MAIN_ANDROID_ORGANIZER,   TXT_LTL_N_NOTEPAD,          IDLE_ANDROID_NOTEPAD_MAIN,    CLSID_NOTEPADAPP,       0,  ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_TODOLIST__
{MNU_MAIN_ANDROID_TODO,                 MNU_MAIN_ANDROID_ORGANIZER,     TXT_LTL_N_TODO_LIST,        IDLE_ANDROID_TO_DO_LIST,  CLSID_TODOLISTAPP,     0,    ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_SKETCHNOTE__
{MNU_MAIN_ANDROID_SNOTE,				MNU_MAIN_ANDROID_ORGANIZER, 	TXT_LIL_N_SKETCH_NOTE,		IDLE_ANDROID_SNOTE_MAIN,	CLSID_SNOTEAPP, 		0,	ANDROIDITEM_VISABLE_MASK},
#endif
//Game
#if defined(__GAME_ENGINE_EMU_MMI__)
{MNU_MAIN_ANDROID_EMU,						MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_EMU_GAMES,		IDLE_ANDROID_GAME_MAIN,	CLSID_EMUAPP,			0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __SKYENGINE__
{MNU_MAIN_ANDROID_VENDOR_GAMES, 	MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_GAMES,			IDLE_ANDROID_SKY,	CLSID_SKY_ENGINE_GAME_APP,		1,						ANDROIDITEM_VISABLE_MASK},
#endif
#if (defined(__GOGOBOX_GAME__))
{MNU_MAIN_ANDROID_GOGOBOX,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_GOGOBOXGAME,	IDLE_ANDROID_GOGOBOX,	CLSID_GOGOBOXGAME,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef  __NATIVE_GAME_MMI_PACMAN__
{MNU_MAIN_ANDROID_PACMAN,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_PACMAN,	IDLE_ANDROID_PAC_MAN,	CLSID_PACMAN,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_BIG2__
{MNU_MAIN_ANDROID_BIG2,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_BIGTWO,	IDLE_ANDROID_BIG_TWO,	CLSID_BIG2,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef	 __NATIVE_GAME_MMI_FRUIT__
{MNU_MAIN_ANDROID_FRUIT,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_FRUIT,	IDLE_ANDROID_FRUIT,	CLSID_FRUITGAMBLEGAME,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_PUZZLE__
{MNU_MAIN_ANDROID_PUZZLE,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_PUZZLE,	IDLE_ANDROID_PUZZLE,	CLSID_PUZZLEAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_HAMSTERFIGHT__
{MNU_MAIN_ANDROID_HAMSTERFIGHT,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_HAMSTERFIGHT,	IDLE_ANDROID_HAMSTERFIGHT,	CLSID_HAMSTERFIGHTAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_LINKUP__
{MNU_MAIN_ANDROID_LINKUP,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_LINKUP,	IDLE_ANDROID_LINKUP,	CLSID_LINKUPAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_GOBANG__
{MNU_MAIN_ANDROID_GOBANG,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_GOBANG,	IDLE_ANDROID_GOBANG,	CLSID_GOBANGAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_SOKOBAN__
{MNU_MAIN_ANDROID_SOKOBAN,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_SOKOBAN,	IDLE_ANDROID_SOKOBAN,	CLSID_SOKOBANAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_SUDOKU__
{MNU_MAIN_ANDROID_SUDOKU,			  MNU_MAIN_ANDROID_GAMES,			TXT_LIL_N_SUDOKU,	IDLE_ANDROID_SUDOKU,	CLSID_SUDOKUAPP,		0,			ANDROIDITEM_VISABLE_MASK, {0}},
#endif

//Application
#ifdef __MAP_MMI__
{MNU_MAIN_ANDROID_MAP,					MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_MAP,				IDLE_ANDROID_MAP_MAIN,	CLSID_MAPAPP,			0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __E_BOOK_MMI__
{MNU_MAIN_ANDROID_E_BOOK,				MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_E_BOOK,			IDLE_ANDROID_EBOOK_MAIN,	CLSID_E_BOOK,			0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#ifdef __DICTAPP_MMI__
{MNU_MAIN_ANDROID_DICT,					MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_DICT,				IDLE_ANDROID_DICT_MAIN,	CLSID_DICTAPP,			0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __TENCENT_MCARE__
#ifdef __TENCENT_MCARE_QXIN__
{MNU_MAIN_ANDROID_MCARE,				MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_QQ,			IDLE_ANDROID_QQ_MAIN,	CLSID_TENCENT_MCARE_QXIN,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_ANDROID_MCARE,				MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_QQ,			IDLE_ANDROID_QQ_MAIN,	CLSID_TENCENT_MCARE,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif
#endif

#ifdef __ZYUE_ENGINE__//TXT_LIL_N_ZHANGYUE_APP
{MNU_MAIN_ANDROID_ZHANGYUE_EBOOK,     MNU_MAIN_ANDROID_APPLICATIONS, TXT_LIL_N_ZHANGYUE_EBOOK,            IDLE_ANDROID_ZHANGYUE_EBOOK,    CLSID_3RD_ZHANGYUE_EBOOK,        1,                        ANDROIDITEM_VISABLE_MASK},
#endif

#ifdef __JAVA_MMI__
{MNU_MAIN_ANDROID_JAVAAMS,			MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_JAVA,				IDLE_ANDROID_JAVA_MAIN,	CLSID_JAVAAMSAPP,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __NCCQQ_MMI__
{MNU_MAIN_ANDROID_QQAPPNEW,		MNU_MAIN_ANDROID_APPLICATIONS,	  TXT_LIL_N_QQ,		           IDLE_ANDROID_QQ_MAIN,		            CLSID_QQAPP,				0,			        ANDROIDITEM_VISABLE_MASK, {0}},
#else //__NCCQQ_MMI__
#ifdef __SKYENGINE__
{MNU_MAIN_ANDROID_QQ,						MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_QQ,				IDLE_ANDROID_QQ_MAIN,	CLSID_SKY_ENGINE_QQ_APP,		0,						ANDROIDITEM_VISABLE_MASK},
{MNU_MAIN_ANDROID_VENDOR_GAMES, MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_GAMES,			IDLE_ANDROID_SKY,	CLSID_SKY_ENGINE_GAME_APP,		1,						ANDROIDITEM_VISABLE_MASK},
#endif
#endif //#ifndef __NCCQQ_MMI__

#ifdef __ZMOL__
{MNU_MAIN_ANDROID_ZMOL_APP,	MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_ZMOLAPP,	IDLE_ANDROID_ZMOLAPP,	CLSID_ZMOL_APP,	0,	ANDROIDITEM_VISABLE_MASK},
#endif

#ifdef __APP_MMI_VENDOR_LIST__
//{MNU_MAIN_ANDROID_MORE,					MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LIL_N_MORE,				IMG_NULL_ID,	CLSID_VENDORLISTAPP,0,						ANDROIDITEM_VISABLE_MASK},
#endif
#ifdef __MMI_SEARCH_APP__
{MNU_MAIN_ANDROID_SEARCH,				MNU_MAIN_ANDROID_APPLICATIONS,	TXT_LTL_N_SEARCH,			IDLE_ANDROID_SEARCH,	CLSID_SEARCHAPP,		0,	ANDROIDITEM_VISABLE_MASK, {0}},
#endif

#ifdef __APP_MMI_NTP__
{MNU_MAIN_ANDROID_NTPAPP,               MNU_MAIN_ANDROID_APPLICATIONS,  TXT_LIL_N_NTP,           IDLE_ANDROID_NTPAPP_MAIN,    CLSID_NTPAPP,        0,  ANDROIDITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_NTP__

//Setting
{MNU_SETTING_ANDROID_PHONE_SETTINGS,	MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_PHONE_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_PhoneSettings,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_DISPLAY_SETTINGS,	MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_DISPLAY_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_DisplaySettings,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_MAIN_ANDROID_PROFILES,					MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_PROFILES,			IMG_NULL_ID,	CLSID_PROFILEAPP,		0,								ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_RINGTONE_SETTINGS,	MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_RINGTONE_SETTINGS,IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_RingtoneSettings,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_CS_CALL_SETTINGS,			MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_CALL_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_CallSettings,		ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_CONNECT_SETTING,	MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_CONNECT_SETTING,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_ConnectSettings,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_NETWORK_NETWORK_SETTINGS,	MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_NETWORK_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_NetworkSettings,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_SWITCH_MODE,		MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_SWITCH_MODE,		IMG_NULL_ID,	CLSID_SWITCHMODE,		PowerOffType_SwitchDualMode,	ANDROIDITEM_VISABLE_MASK, {0}},
{MNU_SETTING_ANDROID_SEC_SECURITY,				MNU_MAIN_ANDROID_SETTINGS,		TXT_LIL_N_SECURITY,			IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_Security,			ANDROIDITEM_VISABLE_MASK, {0}},
};

#endif//__MMI_ANDROID_MENUITEM_H_
#endif//__UI_STYLE_MMI_ANDROID_MAIN_MENU__
