#!/bin/sh
#################################################################################
#
# The confidential and proprietary information contained in this file may
# only be used by a person authorised under and to the extent permitted
# by a subsisting licensing agreement from ARM Limited.
#
#                 (C) COPYRIGHT 2000 ARM Limited.
#                       ALL RIGHTS RESERVED
#
# This entire notice must be reproduced on all copies of this file
# and copies of this file may only be made by a person if such person is
# permitted to do so under the terms of a subsisting license agreement
# from ARM Limited.
#
#
#	       Bin2Hex
#	       =======
#
#     $Author: jrijk $
#   $Revision: $
#       $Date: $
#
################################################################################

# call perl from PATH
eval 'exec perl -x -S $0 ${1+"$@"}'
exit

################################################################################
#!perl -w

# --------------------------------------------------------------------------------
# This routine converts a binary file to hex text file
# --------------------------------------------------------------------------------

my $word;

open(INFILE, "$ARGV[0]") or die "could not open $ARGV[0]\n";

# read in the binary file in word chunks
while(read INFILE, $word, 4) {
  # unpack each word 'string' into a 'long' little-endian and print it as hex
  printf "0x%.8x,\n", unpack("V*", $word);
}

close(INFILE);


