/**
* @file mmi_mae_event.h
*
* This file defines the global events used in MAE platform.
*
* Events used in MAE platform are 32-bit values. The higher 16-bit field denotes the class or the
* category that event belongs to. Most global (system) events are classified to special categories
* which are only dummy classes. Generally these global events are translated from system messages
* in the interface functions to drive the components of MAE platform.
*
* @version $Id: mmi_mae_event.h 1854 2009-09-28 15:50:15Z mark.yang $
*/

#ifndef __MMI_MAE_EVENT_H__
#define __MMI_MAE_EVENT_H__
#include "mmi_mae_clstbl.h"

// macro to retrieve the event category
#define MAE_EVENT_CATEGORY(_event_) (_event_ >> 16)
// base event id of the specified category
#define MAE_EVENT_CAT_BASE(_cat_) (_cat_ << 16)


//
// special events used in shell; the value CLSID_SHELL shall be zero.
//
// DO NOT MODIFY THESE EVENTS OR CHANGE THEIR ORDER IN THIS CATEGORY.
//
#define MEVT_SH_BASE			MAE_EVENT_CAT_BASE(CLSID_SHELL)

#define MAE_EVT_NONE			(MEVT_SH_BASE + 0x0000) ///< it means the event slot is empty (32-bit 0)
#define MAE_EVT_NOP				(MEVT_SH_BASE + 0x0001) ///< a canceled event; its destination object has been released

#define MAE_EVT_RESUMED_CB		(MEVT_SH_BASE + 0x0002) ///< a queued Resume callback function
#define MAE_EVT_RESUMED_CBEX	(MEVT_SH_BASE + 0x0003) ///< a queued ResumeEx callback function (with additional parameters)
#define MAE_EVT_CANCELED_CB		(MEVT_SH_BASE + 0x0004) ///< a canceled Resume callback function
#define MAE_EVT_CANCELED_CBEX	(MEVT_SH_BASE + 0x0005) ///< a canceled ResumeEx callback function

/// APM generated events for applets
#define MAE_EVT_APP_START		(MEVT_SH_BASE + 0x0006)
#define MAE_EVT_APP_STOP		(MEVT_SH_BASE + 0x0007)
#define MAE_EVT_APP_SUSPEND		(MEVT_SH_BASE + 0x0008)
#define MAE_EVT_APP_RESUME		(MEVT_SH_BASE + 0x0009)
/// system termination event; an out-of-band termination event for static objects
/// to resolve circular references when the system is shutting down
#define MAE_EVT_TERMINATE		(MEVT_SH_BASE + 0x000A)
#define MAE_EVT_CONSTRUCT		        (MEVT_SH_BASE + 0x000B)
#define MAE_EVT_DESTRUCT		        (MEVT_SH_BASE + 0x000C)
#define MAE_EVT_HOOK_DRAW               (MEVT_SH_BASE + 0x000D)
#define MAE_EVT_HOOK_ISFUllOPAQUE       (MEVT_SH_BASE + 0x000E)
#define MAE_EVT_HOOK_GETINVALIDATERECT  (MEVT_SH_BASE + 0x000F)
#define MAE_EVT_WINDOW_HANDLER			(MEVT_SH_BASE + 0x0010)
#define MAE_EVT_PRE_HOOK                (MEVT_SH_BASE + 0x0011)
#define MAE_EVT_APP_LAUNCHED            (MEVT_SH_BASE + 0x0012)
#define MAE_EVT_APP_CLOSED              (MEVT_SH_BASE + 0x0013)

#define MAE_EVT_EMBEDDED_AP_CLOSE		(MEVT_SH_BASE + 0x0014) ///< for parent applet to close its embedded applet
#define MAE_EVT_EMBEDDED_AP_SEND        (MEVT_SH_BASE + 0x0015) ///< for parent applet to send data to its embedded applet

//events to inform the applet's location stack is changed between the Fore/Back Stack
#define MAE_EVT_APP_SWAP   (MEVT_SH_BASE + 0x0020)
//events to inform the applet is invisible or visible
#define MAE_EVT_APP_INVISIBLE   (MEVT_SH_BASE + 0x0021)

///
/// MAE specified events
///
#define MEVT_MAE_BASE			MAE_EVENT_CAT_BASE(CLSID_MAE)

#define MAE_EVT_KEY_PRESS		(MEVT_MAE_BASE + 0x0000) ///< key pressed; check lParam for key code
#define MAE_EVT_KEY_RELEASE		(MEVT_MAE_BASE + 0x0001) ///< key released; check lParam for key code
#define MAE_EVT_KEY_LONGPRESS	(MEVT_MAE_BASE + 0x0002) ///< key long-press indication
#define MAE_EVT_KEY_REPEAT		(MEVT_MAE_BASE + 0x0003) ///< key repeat indication
#define MAE_EVT_FLIP			(MEVT_MAE_BASE + 0x0004) ///< flip indication

#define MAE_EVT_GET_PROPERTY	(MEVT_MAE_BASE + 0x0005) ///< get property event for specific handler objects
///< lParam: the property id
///< dParam: pointer to store returned value
#define MAE_EVT_SET_PROPERTY	(MEVT_MAE_BASE + 0x0006) ///< set property event for specefic handler objects
///< lParam: the property id
///< dParam: the value to set

#define MAE_EVT_SM_ACTIVATE		(MEVT_MAE_BASE + 0x0007) ///< state machine mode tree activation
#define MAE_EVT_SM_INACTIVATE	(MEVT_MAE_BASE + 0x0008) ///< state machine mode tree inactivation

#define MAE_EVT_DB_SDDB_READY			(MEVT_MAE_BASE + 0x0020)
#define MAE_EVT_DB_SDDB_INSTALLING		(MEVT_MAE_BASE + 0x0021)
#define MAE_EVT_DB_SDDB_DISABLED		(MEVT_MAE_BASE + 0x0022)
#define MAE_EVT_DB_UPDATED				(MEVT_MAE_BASE + 0x0023) // to be removed
#define MAE_EVT_DB_INSERTED				(MEVT_MAE_BASE + 0x0024) // to be removed
#define MAE_EVT_DB_REMOVED				(MEVT_MAE_BASE + 0x0025) // to be removed
#define MAE_EVT_DB_CONTENT_INSERTED		(MEVT_MAE_BASE + 0x0026)
#define	MAE_EVT_DB_CONTENT_UPDATED		(MEVT_MAE_BASE + 0x0027)
#define	MAE_EVT_DB_CONTENT_REMOVED		(MEVT_MAE_BASE + 0x0028)
#define MAE_EVT_DB_CATEGORY_INSERTED	(MEVT_MAE_BASE + 0x0029)
#define	MAE_EVT_DB_CATEGORY_UPDATED		(MEVT_MAE_BASE + 0x002A)
#define	MAE_EVT_DB_CATEGORY_REMOVED		(MEVT_MAE_BASE + 0x002B)
#define	MAE_EVT_DB_INCOMPLETE_INSTALL	(MEVT_MAE_BASE + 0x002C)
#define	MAE_EVT_TaskDB_INSERTED			(MEVT_MAE_BASE + 0x0040)
#define	MAE_EVT_TaskDB_REMOVED			(MEVT_MAE_BASE + 0x0041)
#define	MAE_EVT_TaskDB_UPDATED			(MEVT_MAE_BASE + 0x0042)
#define	MAE_EVT_EventDB_INSERTED		(MEVT_MAE_BASE + 0x0043)
#define	MAE_EVT_EventDB_REMOVED			(MEVT_MAE_BASE + 0x0044)
#define	MAE_EVT_EventDB_UPDATED			(MEVT_MAE_BASE + 0x0045)

/// events for socket ///
#define	MAE_EVT_SOCKET_CREATE_CNF			(MEVT_MAE_BASE + 0x0060)
#define	MAE_EVT_SOCKET_CONNECT_CNF			(MEVT_MAE_BASE + 0x0061)
#define	MAE_EVT_SOCKET_CLOSE_CNF			(MEVT_MAE_BASE + 0x0062)
#define	MAE_EVT_SOCKET_SEND_CNF				(MEVT_MAE_BASE + 0x0063)
#define	MAE_EVT_SOCKET_SEND_TO_CNF			(MEVT_MAE_BASE + 0x0064)
#define	MAE_EVT_SOCKET_RECV_CNF				(MEVT_MAE_BASE + 0x0065)
#define	MAE_EVT_SOCKET_RECV_FROM_CNF		(MEVT_MAE_BASE + 0x0066)
#define	MAE_EVT_SOCKET_RECV_CB_CNF			(MEVT_MAE_BASE + 0x0067)
#define	MAE_EVT_SOCKET_RECV_FROM_CB_CNF		(MEVT_MAE_BASE + 0x0068)
#define	MAE_EVT_SOCKET_GET_HOST_BY_NAME_CNF	(MEVT_MAE_BASE + 0x0069)


//events for dialog
#define MAE_EVT_DIALOG_CONSTRUCT           (MEVT_MAE_BASE + 0x0080)
#define MAE_EVT_DIALOG_DESTRUCT           (MEVT_MAE_BASE + 0x0081)
#define MAE_EVT_DIALOG_TIMEOUT            (MEVT_MAE_BASE + 0x0082)

#define MAE_EVT_HOPPER_LOCK                (MEVT_MAE_BASE + 0x0090)

///
/// device related events
///
#define MEVT_MAEDEV_BASE		MAE_EVENT_CAT_BASE(CLSID_MAEDEV)

#define MAE_EVT_VM_BAT			(MEVT_MAEDEV_BASE + 0x0000) ///< For VM_BAT_BASE events. This is strictly used in IBattery.
#define MAE_EVT_CARD_ACCESS		(MEVT_MAEDEV_BASE + 0x0001) ///< Notify that SD card is under accessing.
#define MAE_EVT_LOW_STORAGE		(MEVT_MAEDEV_BASE + 0x0002) ///< Warn that the remaing storage of the volume is low
#define MAE_EVT_ACC_PLUG_IND	(MEVT_MAEDEV_BASE + 0x0003) ///< event from acc driver. 20070816, Eric
#define MAE_EVT_CARD_ERROR		(MEVT_MAEDEV_BASE + 0x0004) ///< Notify that SD card is error.

#define MAE_EVT_CARD_CRASH		(MEVT_MAEDEV_BASE + 0x0005) ///< Notify that SD card is crash; need to format.
#define MAE_EVT_CARD_FIX		(MEVT_MAEDEV_BASE + 0x0006) ///< Notify that SD card is fix.
#define MAE_EVT_NAND_CRASH		(MEVT_MAEDEV_BASE + 0x0007) ///< Notify that phone nand user disk is crash; need to format.
#define MAE_EVT_NAND_FIX		(MEVT_MAEDEV_BASE + 0x0008) ///< Notify that phone nand user disk is fix.

#define MAE_EVT_FACTORY_RESET	(MEVT_MAEDEV_BASE + 0x0009) ///< Tool Send notify tell mmi to execute factory reset
#define MAE_EVT_CLEAR_PASSWORD	(MEVT_MAEDEV_BASE + 0x000A) ///< Tool Send notify tell mmi to clear password

/// event from camera, added by Allan Hsu on 2007/8/27
#define	MAE_EVT_CAMERA_OPEN_CNF						(MEVT_MAEDEV_BASE + 0x0020)
#define	MAE_EVT_CAMERA_CLOSE_CNF					(MEVT_MAEDEV_BASE + 0x0021)
#define	MAE_EVT_CAMERA_SET_CONFIG_CNF				(MEVT_MAEDEV_BASE + 0x0022)
#define	MAE_EVT_CAMERA_GET_CONFIG_CNF				(MEVT_MAEDEV_BASE + 0x0023)
#define	MAE_EVT_CAMERA_SET_ATTRIBUTE_CNF			(MEVT_MAEDEV_BASE + 0x0024)
#define	MAE_EVT_CAMERA_GET_ATTRIBUTE_CNF			(MEVT_MAEDEV_BASE + 0x0025)
#define	MAE_EVT_CAMERA_SET_ATTR_AWB_CNF				(MEVT_MAEDEV_BASE + 0x0026)
#define	MAE_EVT_CAMERA_SET_ATTR_AE_CNF				(MEVT_MAEDEV_BASE + 0x0027)
#define	MAE_EVT_CAMERA_SET_ATTR_AF_CNF				(MEVT_MAEDEV_BASE + 0x0028)
#define	MAE_EVT_CAMERA_SET_ATTR_ZOOM_CNF			(MEVT_MAEDEV_BASE + 0x0029)
#define	MAE_EVT_CAMERA_SET_ATTR_EV_CNF				(MEVT_MAEDEV_BASE + 0x002A)
#define	MAE_EVT_CAMERA_SET_ATTR_ANTIFLICKER_CNF		(MEVT_MAEDEV_BASE + 0x002B)
#define	MAE_EVT_CAMERA_SET_ATTR_EFFECT_CNF			(MEVT_MAEDEV_BASE + 0x002C)
#define	MAE_EVT_CAMERA_SET_ATTR_ENV_CNF				(MEVT_MAEDEV_BASE + 0x002D)
#define	MAE_EVT_CAMERA_GET_FILENAME_CNF				(MEVT_MAEDEV_BASE + 0x002E)
#define	MAE_EVT_CAMERA_START_PREVIEW_CNF			(MEVT_MAEDEV_BASE + 0x002F)

#define	MAE_EVT_CAMERA_STOP_PREVIEW_CNF				(MEVT_MAEDEV_BASE + 0x0030)
#define	MAE_EVT_CAMERA_START_CAPTURE_CNF			(MEVT_MAEDEV_BASE + 0x0031)
#define	MAE_EVT_CAMERA_STOP_CAPTURE_CNF				(MEVT_MAEDEV_BASE + 0x0032)
#define	MAE_EVT_CAMERA_START_RECORD_CNF				(MEVT_MAEDEV_BASE + 0x0033)
#define	MAE_EVT_CAMERA_STOP_RECORD_CNF				(MEVT_MAEDEV_BASE + 0x0034)
#define	MAE_EVT_CAMERA_INIT_EV_CNF					(MEVT_MAEDEV_BASE + 0x0035)
#define	MAE_EVT_CAMERA_ENABLE_OSD_CNF				(MEVT_MAEDEV_BASE + 0x0036)
#define	MAE_EVT_CAMERA_DISABLE_OSD_CNF				(MEVT_MAEDEV_BASE + 0x0037)
#define	MAE_EVT_CAMERA_LOAD_OSD_CNF					(MEVT_MAEDEV_BASE + 0x0038)
#define	MAE_EVT_CAMERA_LOAD_FRAME_CNF				(MEVT_MAEDEV_BASE + 0x0039)
#define	MAE_EVT_CAMERA_ERACE_LAYER_CNF				(MEVT_MAEDEV_BASE + 0x003A)
#define	MAE_EVT_CAMERA_SET_WIN_GEOMETRY_CNF			(MEVT_MAEDEV_BASE + 0x003B)
#define	MAE_EVT_CAMERA_PLAY_SHUTTER_SOUND_IND		(MEVT_MAEDEV_BASE + 0x003C)
#define	MAE_EVT_CAMERA_ERROR_CNF					(MEVT_MAEDEV_BASE + 0x003D)
#define	MAE_EVT_CAMERA_STOP_NORMAL_CNF				(MEVT_MAEDEV_BASE + 0x003E)
#define	MAE_EVT_CAMERA_STOP_REACH_TIME_LIMIT_IND	(MEVT_MAEDEV_BASE + 0x003F)

#define MAE_EVT_CAMERA_STOP_REACH_SIZE_LIMIT_IND	(MEVT_MAEDEV_BASE + 0x0040)
#define MAE_EVT_CAMERA_STOP_SPACE_FULL_IND			(MEVT_MAEDEV_BASE + 0x0041)
#define MAE_EVT_CAMERA_UPDATE_POSITION_IND			(MEVT_MAEDEV_BASE + 0x0042)
// EMA notifies MMI that capture stops.
#define MAE_EVT_CAMERA_CAPTURE_STOP_IND				(MEVT_MAEDEV_BASE + 0x0043)
// EMA notifies MMI that recording stops due to size/time limit, or user selects stop.
#define MAE_EVT_CAMERA_RECORD_STOP_IND				(MEVT_MAEDEV_BASE + 0x0044)
#define MAE_EVT_CAMERA_REG_NOTIFY_CNF				(MEVT_MAEDEV_BASE + 0x0045)
#define MAE_EVT_CAMERA_SET_SHUTTER_SOUND_CNF		(MEVT_MAEDEV_BASE + 0x0046)
// ICamera resource control
#define MAE_EVT_CAMERA_RES_SUSPEND_IND				(MEVT_MAEDEV_BASE + 0x0047)
#define MAE_EVT_CAMERA_ENABLE_STICKER_CNF              (MEVT_MAEDEV_BASE + 0x0048)
#define MAE_EVT_CAMERA_DISABLE_STICKER_CNF              (MEVT_MAEDEV_BASE + 0x0049)
#define	MAE_EVT_CAMERA_GET_IMAGE_CNF				(MEVT_MAEDEV_BASE + 0x004A)


/// events for touch screen device ///
#define	MAE_EVT_TS_PRESS			(MEVT_MAEDEV_BASE +	0x0060)
#define	MAE_EVT_TS_RELEASE			(MEVT_MAEDEV_BASE +	0x0061)
#define	MAE_EVT_TS_MOVE				(MEVT_MAEDEV_BASE +	0x0062)
#define	MAE_EVT_TS_UP				(MEVT_MAEDEV_BASE +	0x0063)
#define	MAE_EVT_TS_DOWN				(MEVT_MAEDEV_BASE +	0x0064)
#define	MAE_EVT_TS_LEFT				(MEVT_MAEDEV_BASE +	0x0065)
#define	MAE_EVT_TS_RIGHT			(MEVT_MAEDEV_BASE +	0x0066)
#define	MAE_EVT_TS_CLICK			(MEVT_MAEDEV_BASE +	0x0067)
#define	MAE_EVT_TS_DBL_CLICK		(MEVT_MAEDEV_BASE +	0x0068)
#define	MAE_EVT_TS_LONG_PRESS		(MEVT_MAEDEV_BASE +	0x0069)
#define	MAE_EVT_TS_CALIBRATION		(MEVT_MAEDEV_BASE +	0x006A)
#define	MAE_EVT_TS_FORCE_UNHOOK		(MEVT_MAEDEV_BASE +	0x006B)
#define MAE_EVT_TS_PINCH_IN         (MEVT_MAEDEV_BASE +	0x006C)
#define MAE_EVT_TS_PINCH_OUT        (MEVT_MAEDEV_BASE +	0x006D)
#define MAE_EVT_TS_ROTATE_CKW       (MEVT_MAEDEV_BASE +	0x006E)
#define MAE_EVT_TS_ROTATE_ACKW      (MEVT_MAEDEV_BASE +	0x006F)
#define	MAE_EVT_TS_MULTI_PRESS      (MEVT_MAEDEV_BASE +	0x0070)
#define	MAE_EVT_TS_MULTI_RELEASE    (MEVT_MAEDEV_BASE +	0x0071)
#define	MAE_EVT_TS_MULTI_MOVE       (MEVT_MAEDEV_BASE +	0x0072)
#define MAE_EVT_TS_DBL_UP            (MEVT_MAEDEV_BASE +	0x0073)
#define MAE_EVT_TS_DBL_DOWN       (MEVT_MAEDEV_BASE +	0x0074)
#define MAE_EVT_TS_DBL_LEFT         (MEVT_MAEDEV_BASE +	0x0075)
#define MAE_EVT_TS_DBL_RIGHT       (MEVT_MAEDEV_BASE +	0x0076)

/// events for media ///
#define	MAE_EVT_AUD_PLAY_START_CNF				(MEVT_MAEDEV_BASE + 0x0100)
#define	MAE_EVT_AUD_PLAY_START_FAILED			(MEVT_MAEDEV_BASE + 0x0101)
#define	MAE_EVT_AUD_PLAY_STOP_CNF				(MEVT_MAEDEV_BASE + 0x0102)
#define	MAE_EVT_AUD_PLAY_STOP_FAILED			(MEVT_MAEDEV_BASE + 0x0103)
#define	MAE_EVT_AUD_PLAYTONE_START_CNF			(MEVT_MAEDEV_BASE + 0x0104)
#define	MAE_EVT_AUD_PLAYTONE_START_FAILED		(MEVT_MAEDEV_BASE + 0x0105)
#define	MAE_EVT_AUD_SET_POSITION_CNF			(MEVT_MAEDEV_BASE + 0x0106)
#define	MAE_EVT_AUD_SET_POSITION_FAILED			(MEVT_MAEDEV_BASE + 0x0107)
#define	MAE_EVT_AUD_SET_SPEED_CNF				(MEVT_MAEDEV_BASE + 0x0108)
#define	MAE_EVT_AUD_SET_SPEED_FAILED			(MEVT_MAEDEV_BASE + 0x0109)
#define	MAE_EVT_AUD_PLAY_PAUSE_CNF				(MEVT_MAEDEV_BASE + 0x010A)
#define	MAE_EVT_AUD_PLAY_PAUSE_FAILED			(MEVT_MAEDEV_BASE + 0x010B)
#define	MAE_EVT_AUD_PLAY_RESUME_CNF				(MEVT_MAEDEV_BASE + 0x010C)
#define	MAE_EVT_AUD_PLAY_RESUME_FAILED			(MEVT_MAEDEV_BASE + 0x010D)
#define	MAE_EVT_AUD_PLAY_STREAM_CNF				(MEVT_MAEDEV_BASE + 0x010E)
#define	MAE_EVT_AUD_PLAY_STREAM_FAILED			(MEVT_MAEDEV_BASE + 0x010F)

#define	MAE_EVT_AUD_PLAY_ADD_BUFFER_CNF			(MEVT_MAEDEV_BASE + 0x0110)
#define	MAE_EVT_AUD_GET_FILE_INFO_CNF			(MEVT_MAEDEV_BASE + 0x0111)
#define	MAE_EVT_AUD_GET_FILE_INFO_FAILED		(MEVT_MAEDEV_BASE + 0x0112)
#define	MAE_EVT_AUD_GET_ID3_INFO_CNF			(MEVT_MAEDEV_BASE + 0x0113)
#define	MAE_EVT_AUD_GET_ID3_INFO_FAILED			(MEVT_MAEDEV_BASE + 0x0114)
#define	MAE_EVT_AUD_GET_LYRICS_INFO_CNF			(MEVT_MAEDEV_BASE + 0x0115)
#define	MAE_EVT_AUD_GET_LYRICS_INFO_FAILED		(MEVT_MAEDEV_BASE + 0x0116)
#define	MAE_EVT_AUD_SET_3D_EFFECT_CNF			(MEVT_MAEDEV_BASE + 0x0117)
#define	MAE_EVT_AUD_SET_3D_EFFECT_FAILED		(MEVT_MAEDEV_BASE + 0x0118)
#define	MAE_EVT_AUD_SET_EQ_TYPE_CNF				(MEVT_MAEDEV_BASE + 0x0119)
#define	MAE_EVT_AUD_SET_EQ_TYPE_FAILED			(MEVT_MAEDEV_BASE + 0x011A)
#define	MAE_EVT_AUD_SET_POWER_ON_CNF			(MEVT_MAEDEV_BASE + 0x011B)
#define	MAE_EVT_AUD_REC_START_CNF				(MEVT_MAEDEV_BASE + 0x011C)
#define	MAE_EVT_AUD_REC_START_FAILED			(MEVT_MAEDEV_BASE + 0x011D)
#define	MAE_EVT_AUD_REC_STOP_CNF				(MEVT_MAEDEV_BASE + 0x011E)

#define	MAE_EVT_AUD_REC_STOP_FAILED				(MEVT_MAEDEV_BASE + 0x0120)
#define	MAE_EVT_AUD_REC_NOTIFY_CNF				(MEVT_MAEDEV_BASE + 0x0121)
#define	MAE_EVT_AUD_REC_NOTIFY_FAILED			(MEVT_MAEDEV_BASE + 0x0122)
#define	MAE_EVT_AUD_REC_GET_LATEST_RECORDED_FILENAME_CNF		(MEVT_MAEDEV_BASE + 0x0123)
#define	MAE_EVT_AUD_REC_GET_LATEST_RECORDED_FILENAME_FAILED		(MEVT_MAEDEV_BASE + 0x0124)
#define	MAE_EVT_AUD_NOTIFY_PLAY_END				(MEVT_MAEDEV_BASE + 0x0125)
#define	MAE_EVT_AUD_NOTIFY_PLAY_ERROR			(MEVT_MAEDEV_BASE + 0x0126)
#define	MAE_EVT_AUD_NOTIFY_PLAY_POSITION_UPDATE	(MEVT_MAEDEV_BASE + 0x0127)
#define	MAE_EVT_AUD_NOTIFY_PLAY_BITRATE_CHANGE	(MEVT_MAEDEV_BASE + 0x0128)
#define	MAE_EVT_AUD_NOTIFY_PLAY_LYRICS_UPDATE	(MEVT_MAEDEV_BASE + 0x0129)
#define	MAE_EVT_AUD_NOTIFY_REC_END				(MEVT_MAEDEV_BASE + 0x012A)

#define	MAE_EVT_AUD_NOTIFY_REC_SPACE_FULL		(MEVT_MAEDEV_BASE + 0x0130)
#define	MAE_EVT_AUD_NOTIFY_REC_ERROR			(MEVT_MAEDEV_BASE + 0x0131)
#define	MAE_EVT_AUD_NOTIFY_REC_POSITION_UPDATE	(MEVT_MAEDEV_BASE + 0x0132)

#define	MAE_EVT_VDO_NOTIFY_PLAY_END				(MEVT_MAEDEV_BASE + 0x0140)
#define	MAE_EVT_VDO_NOTIFY_PLAY_ERROR			(MEVT_MAEDEV_BASE + 0x0141)
#define	MAE_EVT_VDO_NOTIFY_POSITION_UPDATE		(MEVT_MAEDEV_BASE + 0x0142)
#define	MAE_EVT_VDO_NOTIFY_BITRATE_CHANGE		(MEVT_MAEDEV_BASE + 0x0143)
#define	MAE_EVT_VDO_PLAY_FILE_CNF				(MEVT_MAEDEV_BASE + 0x0144)
#define	MAE_EVT_VDO_PLAY_FILE_FAILED			(MEVT_MAEDEV_BASE + 0x0145)
#define	MAE_EVT_VDO_PLAY_PAUSE_CNF				(MEVT_MAEDEV_BASE + 0x0146)
#define	MAE_EVT_VDO_PLAY_PAUSE_FAILED			(MEVT_MAEDEV_BASE + 0x0147)
#define	MAE_EVT_VDO_PLAY_RESUME_CNF				(MEVT_MAEDEV_BASE + 0x0148)
#define	MAE_EVT_VDO_PLAY_RESUME_FAILED			(MEVT_MAEDEV_BASE + 0x0149)
#define	MAE_EVT_VDO_PLAY_STREAM_CNF				(MEVT_MAEDEV_BASE + 0x014A)
#define	MAE_EVT_VDO_PLAY_STREAM_FAILED			(MEVT_MAEDEV_BASE + 0x014B)
#define	MAE_EVT_VDO_PLAY_STOP_CNF				(MEVT_MAEDEV_BASE + 0x014C)
#define	MAE_EVT_VDO_PLAY_STOP_FAILED			(MEVT_MAEDEV_BASE + 0x014D)
#define	MAE_EVT_VDO_PLAY_SET_POSITION_CNF		(MEVT_MAEDEV_BASE + 0x014E)
#define	MAE_EVT_VDO_PLAY_SET_POSITION_FAILED	(MEVT_MAEDEV_BASE + 0x014F)

#define	MAE_EVT_VDO_PLAY_SET_SPEED_CNF			(MEVT_MAEDEV_BASE + 0x0150)
#define	MAE_EVT_VDO_PLAY_SET_SPEED_FAILED		(MEVT_MAEDEV_BASE + 0x0151)
#define	MAE_EVT_VDO_PLAY_FIRST_FRAME_CNF		(MEVT_MAEDEV_BASE + 0x0152)
#define	MAE_EVT_VDO_DECODE_FIRST_FRAME_CNF		(MEVT_MAEDEV_BASE + 0x0153)
#define	MAE_EVT_VDO_DECODE_FIRST_FRAME_FAILED	(MEVT_MAEDEV_BASE + 0x0154)
#define	MAE_EVT_VDO_RESET_WINDOW_CNF			(MEVT_MAEDEV_BASE + 0x0155)
#define	MAE_EVT_VDO_RESET_WINDOW_FAILED			(MEVT_MAEDEV_BASE + 0x0156)
#define	MAE_EVT_VDO_GET_FILE_INFO_CNF			(MEVT_MAEDEV_BASE + 0x0157)
#define	MAE_EVT_VDO_GET_FILE_INFO_FAILED		(MEVT_MAEDEV_BASE + 0x0158)
#define	MAE_EVT_VDO_REG_NOTIFY_CNF				(MEVT_MAEDEV_BASE + 0x0159)
#define	MAE_EVT_VDO_REG_NOTIFY_FAILED			(MEVT_MAEDEV_BASE + 0x015A)
#define	MAE_EVT_VDO_STATUS_NOTIFY				(MEVT_MAEDEV_BASE + 0x015B)
#define	MAE_EVT_VDO_INIT_CNF					(MEVT_MAEDEV_BASE + 0x015C)
#define	MAE_EVT_VDO_INIT_FAILED					(MEVT_MAEDEV_BASE + 0x015D)

#define	MAE_EVT_AUD_INIT_STREAMING_CNF			(MEVT_MAEDEV_BASE + 0x0160)
#define	MAE_EVT_AUD_SKIP_CNF					(MEVT_MAEDEV_BASE + 0x0161)
#define	MAE_EVT_AUD_NOTIFY_ADD_BUFFER_DONE_CNF	(MEVT_MAEDEV_BASE + 0x0162)
#define	MAE_EVT_AUD_FILE_FORMAT_NOT_SUPPORTED	(MEVT_MAEDEV_BASE + 0x0163)
#define	MAE_EVT_VDO_FILE_FORMAT_NOT_SUPPORTED	(MEVT_MAEDEV_BASE + 0x0164)
#define MAE_EVT_AUD_SET_A2DP_STOP_CNF           (MEVT_MAEDEV_BASE + 0x0165)

#define   MAE_EVT_AUD_PCMREC_REGCB_CNF                  (MEVT_MAEDEV_BASE + 0x0166)
#define   MAE_EVT_AUD_PCMREC_REGCB_FAILED             (MEVT_MAEDEV_BASE + 0x0167)
#define   MAE_EVT_AUD_PCMREC_START_CNF                  (MEVT_MAEDEV_BASE + 0x0168)
#define   MAE_EVT_AUD_PCMREC_START_FAILED            (MEVT_MAEDEV_BASE + 0x0169)
#define   MAE_EVT_AUD_PCMREC_STOP_CNF                    (MEVT_MAEDEV_BASE + 0x016A)
#define   MAE_EVT_AUD_PCMREC_STOP_FAILED              (MEVT_MAEDEV_BASE + 0x016B)

//ResMgr notifications
#define   MAE_EVT_RESMGR_PREEMPT_NOTIFY           (MEVT_MAEDEV_BASE+ 0x016C)
#define   MAE_EVT_RESMGR_RESUME_NOTIFY            (MEVT_MAEDEV_BASE+ 0x016D)
#define   MAE_EVT_RESMGR_SUSPEND_CMD_NOTIFY       (MEVT_MAEDEV_BASE+ 0x016E)

#ifdef __RFID__
#define	MAE_EVT_RFIDREADER_RESPONSE_CNF		(MEVT_MAEDEV_BASE + 0x01D0)
#ifdef __SUPPORT_JSR257__
#define	MAE_EVT_RFIDREADER_LISTENER_IND		(MEVT_MAEDEV_BASE + 0x01D1)
#endif	//__SUPPORT_JSR257__
#endif	//__RFID__

/// events for G-sensor ///
#define MAE_EVT_GSENSOR_POWER_ON_CNF			(MEVT_MAEDEV_BASE + 0x0200)
#define MAE_EVT_GSENSOR_POWER_OFF_CNF			(MEVT_MAEDEV_BASE + 0x0201)
#define MAE_EVT_GSENSOR_REG_NOTIFY_CNF			(MEVT_MAEDEV_BASE + 0x0202)
#define MAE_EVT_GSENSOR_NOTIFY					(MEVT_MAEDEV_BASE + 0x0203)

/// events for GPS ///
#define    MAE_EVT_GPS_OPEN_CNF   (MEVT_MAEDEV_BASE + 0x0204)
#define    MAE_EVT_GPS_CLOSE_CNF  (MEVT_MAEDEV_BASE + 0x0205)
#define    MAE_EVT_GPS_GETDATA_CNF (MEVT_MAEDEV_BASE + 0x0206)

/// events for Content DB ///
#define    MAE_EVT_CONTENTDB_SYNC_CNF   (MEVT_MAEDEV_BASE + 0x0207)
#define    MAE_EVT_CONTENTDB_SYNC_IND  (MEVT_MAEDEV_BASE + 0x0208)

/// events for Proximity sensor ///
#define MAE_EVT_INFRARED_IND       (MEVT_MAEDEV_BASE + 0x0209)//__PAI_SENSOR__

///	Bluetooth deivce
#define	MAE_EVT_BT_POWER_ONOFF_CNF				(MEVT_MAEDEV_BASE +	0x300)
#define	MAE_EVT_BT_INQUIRY_IND					(MEVT_MAEDEV_BASE +	0x301)
#define	MAE_EVT_BT_INQUIRY_CNF					(MEVT_MAEDEV_BASE +	0x302)
#define	MAE_EVT_BT_NAME_QUERY_CNF				(MEVT_MAEDEV_BASE +	0x303)
#define	MAE_EVT_BT_DELETE_DEVICE_CNF			(MEVT_MAEDEV_BASE +	0x304)
#define	MAE_EVT_BT_SET_LOCAL_NAME_CNF			(MEVT_MAEDEV_BASE +	0x305)
#define	MAE_EVT_BT_SET_DISCOVERY_CNF			(MEVT_MAEDEV_BASE +	0x306)
#define	MAE_EVT_BT_PIN_CODE_IND					(MEVT_MAEDEV_BASE +	0x307)
#define	MAE_EVT_BT_PAIR_DONE_IND				(MEVT_MAEDEV_BASE +	0x308)
#define	MAE_EVT_BT_ACL_LINK_CNF					(MEVT_MAEDEV_BASE +	0x309)
#define	MAE_EVT_BT_ACL_LINK_IND					(MEVT_MAEDEV_BASE +	0x30A)
#define	MAE_EVT_BT_AUDIO_LINK_CNF				(MEVT_MAEDEV_BASE +	0x30B)
#define	MAE_EVT_BT_AUDIO_LINK_IND				(MEVT_MAEDEV_BASE +	0x30C)
#define	MAE_EVT_BT_AUDIO_LINK_CONN_IND			(MEVT_MAEDEV_BASE +	0x30D)
#define	MAE_EVT_BT_AUDIO_CALL_IND				(MEVT_MAEDEV_BASE +	0x30E)
#define	MAE_EVT_BT_AUDIO_CALL_CNF				(MEVT_MAEDEV_BASE +	0x30F)
#define	MAE_EVT_BT_AUDIO_VOL_IND				(MEVT_MAEDEV_BASE +	0x310)
#define	MAE_EVT_BT_AUDIO_PKTTYPE_IND			(MEVT_MAEDEV_BASE +	0x311)
#define	MAE_EVT_BT_AUDIO_ATCMD_IND				(MEVT_MAEDEV_BASE +	0x312)
#define	MAE_EVT_BT_AUDIO_ATCMD_REQ				(MEVT_MAEDEV_BASE +	0x313)

#define	MAE_EVT_BT_OBEX_LINK_CNF				(MEVT_MAEDEV_BASE +	0x314)
#define	MAE_EVT_BT_OBEX_SEND_CNF				(MEVT_MAEDEV_BASE +	0x315)
#define	MAE_EVT_BT_OBEX_RECEIVE_IND				(MEVT_MAEDEV_BASE +	0x316)
#define	MAE_EVT_BT_OBEX_RECEIVE_CNF				(MEVT_MAEDEV_BASE +	0x317)
#define	MAE_EVT_BT_OBEX_TRANS_STATUS_IND		(MEVT_MAEDEV_BASE +	0x318)
#define	MAE_EVT_BT_OBEX_FILE_WRITE_IND			(MEVT_MAEDEV_BASE +	0x319)

#define	MAE_EVT_BT_CHIP_RESET_IND				(MEVT_MAEDEV_BASE +	0x31A)
#define	MAE_EVT_BT_TEST_MODE_RF_POWER_LEVEL		(MEVT_MAEDEV_BASE +	0x31B)
#define	MAE_EVT_BT_TEST_MODE_RF_RSSI			(MEVT_MAEDEV_BASE +	0x31C)
#define	MAE_EVT_BT_TEST_MODE_RF_CONT_TX			(MEVT_MAEDEV_BASE +	0x31D)
#define	MAE_EVT_BT_TEST_MODE_RF_CONT_RX			(MEVT_MAEDEV_BASE +	0x31E)
#define	MAE_EVT_BT_TEST_MODE_RF_AUTO_TEST		(MEVT_MAEDEV_BASE +	0x31F)
#define	MAE_EVT_BT_A2DP_LINK_CNF				(MEVT_MAEDEV_BASE +	0x320)
#define	MAE_EVT_BT_A2DP_LINK_IND				(MEVT_MAEDEV_BASE +	0x321)
#define	MAE_EVT_BT_A2DP_ACTION_CNF				(MEVT_MAEDEV_BASE +	0x322)
#define	MAE_EVT_BT_A2DP_STATUS_CHANGED_IND		(MEVT_MAEDEV_BASE +	0x323)
#define	MAE_EVT_BT_A2DP_UNBLOCK_BT_IND		    (MEVT_MAEDEV_BASE +	0x324)

#define	MAE_EVT_BT_AVRCP_ACTION_IND 			(MEVT_MAEDEV_BASE +	0x325)
#define	MAE_EVT_BT_AVRCP_ACTION_CNF 			(MEVT_MAEDEV_BASE +	0x326)
#define	MAE_EVT_BT_SDP_SERVICE_CNF 				(MEVT_MAEDEV_BASE +	0x327)

#define	MAE_EVT_BT_LOOPBACK_TEST_CNF			(MEVT_MAEDEV_BASE +	0x328)
#define	MAE_EVT_BT_ACL_MODE_CHANGE_IND			(MEVT_MAEDEV_BASE +	0x329)

/// events for Config ///
#define	MAE_EVT_CFG_SETTING_CHANGE              (MEVT_MAEDEV_BASE + 0x330)
#define MAE_EVT_WLAN_POWER_ONOFF_CNF            (MEVT_MAEDEV_BASE + 0x400)
#define MAE_EVT_WLAN_RESET_CNF                  (MEVT_MAEDEV_BASE + 0x401)
#define MAE_EVT_WLAN_POWER_SAVING_CNF           (MEVT_MAEDEV_BASE + 0x402)
#define MAE_EVT_WLAN_START_SCAN_CNF             (MEVT_MAEDEV_BASE + 0x403)
#define MAE_EVT_WLAN_STOP_SCAN_CNF              (MEVT_MAEDEV_BASE + 0x404)
#define MAE_EVT_WLAN_SCAN_DONE_IND              (MEVT_MAEDEV_BASE + 0x405)
#define MAE_EVT_WLAN_CONNECT_CNF                (MEVT_MAEDEV_BASE + 0x406)
#define MAE_EVT_WLAN_DISCONNECT_CNF             (MEVT_MAEDEV_BASE + 0x407)
#define MAE_EVT_WLAN_STATUS_UPDATE_IND          (MEVT_MAEDEV_BASE + 0x408)
#define MAE_EVT_WLAN_INIT_FIFO_CNF              (MEVT_MAEDEV_BASE + 0x409)
#define MAE_EVT_WLAN_DELETE_FIFO_CNF            (MEVT_MAEDEV_BASE + 0x40A)
#define MAE_EVT_WLAN_SET_CONFIG_CNF             (MEVT_MAEDEV_BASE + 0x40B)
#define MAE_EVT_WLAN_SET_BTSTATUS_CNF           (MEVT_MAEDEV_BASE + 0x40C)
#define MAE_EVT_WLAN_SET_GSMSTATUS_CNF          (MEVT_MAEDEV_BASE + 0x40D)

//events for emapp
#define MAE_EVT_WLAN_SET_WIFION                 (MEVT_MAEDEV_BASE + 0x40E)
#define MAE_EVT_WLAN_SEND_PRODUCTION            (MEVT_MAEDEV_BASE + 0x40F)
#define MAE_EVT_WLAN_STATUS_UPDATE              (MEVT_MAEDEV_BASE + 0x410)
#define MAE_EVT_WLAN_GET_FW_TEST_RESULT         (MEVT_MAEDEV_BASE + 0x411)
#define MAE_EVT_WLAN_GET_AQUARIUD_SW_VERSION    (MEVT_MAEDEV_BASE + 0x412)
#define MAE_EVT_WLAN_GET_RX                     (MEVT_MAEDEV_BASE + 0x413)
#define MAE_EVT_WLAN_SET_RX                     (MEVT_MAEDEV_BASE + 0x414)
#define MAE_EVT_WLAN_READ_REG                   (MEVT_MAEDEV_BASE + 0x415)
#define MAE_EVT_WLAN_WRITE_REG                  (MEVT_MAEDEV_BASE + 0x416)
#define MAE_EVT_WLAN_SEND_TX                    (MEVT_MAEDEV_BASE + 0x417)
#define MAE_EVT_FIND_HIGH_SPEED_TASK            (MEVT_MAEDEV_BASE + 0x418)
#define MAE_EVT_WLAN_STOP_TX                    (MEVT_MAEDEV_BASE + 0x419)
#define MAE_EVT_WLAN_SET_SIN_TONE               (MEVT_MAEDEV_BASE + 0x41A)
#define MAE_EVT_WLAN_WRITE_RF_REG               (MEVT_MAEDEV_BASE + 0x41B)
#define MAE_EVT_WLAN_READ_RF_REG                (MEVT_MAEDEV_BASE + 0x41C)
#define MAE_EVT_WLAN_WRITE_AQU_MEM              (MEVT_MAEDEV_BASE + 0x41D)
#define MAE_EVT_WLAN_READ_AQU_MEM               (MEVT_MAEDEV_BASE + 0x41E)

/**
* MAE key codes used in keypad events.
*
* @see mdl_keypad.h
*/
#define	MAE_KEY_OK			0x00
#define	MAE_KEY_MEN			0x01
#define	MAE_KEY_LEFT		0x02
#define	MAE_KEY_PHB			0x03
#define	MAE_KEY_RIGHT		0x04
#define	MAE_KEY_ONOFF		0x05
#define	MAE_KEY_CLR			0x06
#define	MAE_KEY_PLUS		0x07
#define	MAE_KEY_SEND		0x08
#define	MAE_KEY_SEND1		0x09
#define	MAE_KEY_SEND2		0x0A
#define	MAE_KEY_END			0x0B
#define	MAE_KEY_MINUS		0x0C
#define	MAE_KEY_1			0x0D
#define	MAE_KEY_2			0x0E
#define	MAE_KEY_3			0x0F

#define	MAE_KEY_4			0x10
#define	MAE_KEY_5			0x11
#define	MAE_KEY_6			0x12
#define	MAE_KEY_7			0x13
#define	MAE_KEY_8			0x14
#define	MAE_KEY_9			0x15
#define	MAE_KEY_STAR		0x16
#define	MAE_KEY_0			0x17
#define	MAE_KEY_HASH		0x18
#define	MAE_KEY_MSG			0x19
#define	MAE_KEY_MAIL		0x1A
#define	MAE_KEY_FSTDL1		0x1B
#define	MAE_KEY_FSTDL2		0x1C
#define	MAE_KEY_FSTDL3		0x1D
#define	MAE_KEY_FSTDL4		0x1E
#define	MAE_KEY_REDIAL		0x1F

#define	MAE_KEY_HOOK		0x20
#define	MAE_KEY_UP			0x21
#define	MAE_KEY_DOWN		0x22
#define	MAE_KEY_FLAPON		0x23
#define	MAE_KEY_FLAPOFF		0x24
#define	MAE_KEY_SIDE_UP		0x25
#define	MAE_KEY_SIDE_DN		0x26
#define	MAE_KEY_SKLEFT		0x27
#define	MAE_KEY_SKRIGHT		0x28
#define	MAE_KEY_HEADSET		0x29
#define	MAE_KEY_CLEAR		0x2A
#define	MAE_KEY_ACTION		0x2B
#define	MAE_KEY_CAMERA		0x2C
#define	MAE_KEY_MP3			0x2D
#define	MAE_KEY_POWERMODE	0x2E
#define	MAE_KEY_ATV			0x2F
#define	MAE_KEY_FM			0x30
#define	MAE_KEY_FAST_FORWARD	0x31
#define	MAE_KEY_REWIND			0x32

#ifdef __QWERTY_KEYPAD_MMI__
#ifdef __QWERTY_KEYPAD_TYPE_N__
#define MAE_KEY_A			0x33
#define MAE_KEY_D			0x36
#define MAE_KEY_E			0x37
#define MAE_KEY_I			0x3B
#define MAE_KEY_K			0x3D
#define MAE_KEY_L			0x3E
#define MAE_KEY_M			0x3F
#define MAE_KEY_N			0x40//MAE_KEY_HASH
#define MAE_KEY_O			0x41
#define MAE_KEY_P			0x42
#define MAE_KEY_Q			0x43
#define MAE_KEY_S			0x45
#define MAE_KEY_U			0x47//MAE_KEY_STAR
#define MAE_KEY_W			0x49
#define MAE_KEY_X			0x4A
#define MAE_KEY_Z			0x4C

#define MAE_KEY_R			MAE_KEY_1
#define MAE_KEY_T			MAE_KEY_2
#define MAE_KEY_Y			MAE_KEY_3
#define MAE_KEY_F			MAE_KEY_4
#define MAE_KEY_G			MAE_KEY_5
#define MAE_KEY_H			MAE_KEY_6
#define MAE_KEY_C			MAE_KEY_7
#define MAE_KEY_V			MAE_KEY_8
#define MAE_KEY_B			MAE_KEY_9
#define MAE_KEY_J			MAE_KEY_0

#define MAE_KEY_Alt			0x4D
#define MAE_KEY_SHIFTLEFT	0x4E
#define MAE_KEY_SHIFTRIGHT	0x4F
#define MAE_KEY_ENTER		0x50
#define MAE_KEY_SPACE		0x51
#define MAE_KEY_SYM			0x52
#define MAE_KEY_DOLLAR		0x53
#define MAE_KEY_DEL			0x54
#define MAE_KEY_NEXT		0x55
#define MAE_KEY_DOT			0x56
#define MAE_KEY_SHIFT		0x57
#define MAE_KEY_LOCK		0x58
#define MAE_KEY_Ctrl		0x59
#define MAE_KEY_MENU		0x5A
#define MAE_KEY_QUESTION	0x5B
#define MAE_KEY_VKEY_NUM	0x5C
#define MAE_KEY_HOME            0x5D
#elif __QWERTY_KEYPAD_TYPE_H__
#define MAE_KEY_A			0x33//MAE_KEY_STAR
#define MAE_KEY_B			0x34
#define MAE_KEY_G			0x39
#define MAE_KEY_H			0x3A
#define MAE_KEY_I			0x3B
#define MAE_KEY_J			0x3C
#define MAE_KEY_K			0x3D
#define MAE_KEY_L			0x3E
#define MAE_KEY_M			0x3F
#define MAE_KEY_N			0x40
#define MAE_KEY_O			0x41
#define MAE_KEY_P			0x42
#define MAE_KEY_Q			0x43//MAE_KEY_HASH
#define MAE_KEY_T			0x44
#define MAE_KEY_U			0x47
#define MAE_KEY_V			0x48
#define MAE_KEY_Y			0x4B

#define MAE_KEY_W			MAE_KEY_1
#define MAE_KEY_E			MAE_KEY_2
#define MAE_KEY_R			MAE_KEY_3
#define MAE_KEY_S			MAE_KEY_4
#define MAE_KEY_D			MAE_KEY_5
#define MAE_KEY_F			MAE_KEY_6
#define MAE_KEY_Z			MAE_KEY_7
#define MAE_KEY_X			MAE_KEY_8
#define MAE_KEY_C			MAE_KEY_9

#define MAE_KEY_Alt			0x4D
#define MAE_KEY_SHIFTLEFT	0x4E
#define MAE_KEY_SHIFTRIGHT	0x4F
#define MAE_KEY_ENTER		0x50
#define MAE_KEY_SPACE		0x51
#define MAE_KEY_SYM			0x52
#define MAE_KEY_DOLLAR		0x53
#define MAE_KEY_DEL			0x54
#define MAE_KEY_NEXT		0x55
#define MAE_KEY_DOT			0x56
#define MAE_KEY_SHIFT		0x57
#define MAE_KEY_LOCK		0x58
#define MAE_KEY_Ctrl		0x59
#define MAE_KEY_MENU		0x5A
#define MAE_KEY_QUESTION	0x5B
#define MAE_KEY_VKEY_NUM	0x5C
#define MAE_KEY_HOME            0x5D

#endif
#else  //no__QWERTY_KEYPAD_MMI__
#define MAE_KEY_VKEY_NUM	0x33
#define MAE_KEY_HOME            0x34
#endif  //__QWERTY_KEYPAD_MMI__
#define MAE_KEY_DUMMY		0xFF

// modify by chenyan for 7165 dial UI
#ifdef __POP_DIAL_PANEL__
#define MAE_KEY_TOUCH_MIDDLESK 0xFE
#endif // __POP_DIAL_PANEL__

#endif // __MAE_EVENT_H__
