#ifndef _SECAPPVIEW_ID_H_
#define _SECAPPVIEW_ID_H_

#include "mae_menulabel.h"
#include "mmi_wdg_image.h"
#include "mae_textlabel.h"
#include "mmi_mae_menumodel.h"
#include "mmi_view_id_range.h"
#include "mmi_mae_widget_properties.h"
#include "mmi_mae_inputcontroller.h"
#include "mmi_common_thmid.h"
#include "mmi_wdg_menu.h"
#include "mmi_common_cfg.h"
#include "mmi_secapp_cfg.h"

typedef enum
{
  SEC_MenuList  ,
  SEC_OptionList  ,
  SEC_SOption   ,
  SEC_LaunchAP  ,
  SEC_Info    ,
  SEC_LaunchFileMgrAP ,

}SEC_NEXT_FORM_TYPE_e;

enum
{
/* View ID start */
  VID_SECAPP_START = MMI_VIEW_ID_AP_BEGIN,
  VID_SECAPP_EMERGENCYCALL_LIST,
  VID_SECAPP_SECURITY_MENU,
  VID_SECAPP_PIN_CODE_MENU,
  VID_SECAPP_PHONE_LOCK_MENU,
  VID_SECAPP_SIM_LOCK_MENU,
  VID_SECAPP_PIN_STATUS_MENU,
  VID_SECAPP_PHONE_LOCK_STATUS_MENU,
  VID_SECAPP_SIM_LOCK_STATUS_MENU,
  VID_SECAPP_AUTO_KEYPAD_LOCK_MENU,
  VID_SECAPP_VERIFY_LOCK, //verify lock begin
  VID_SECAPP_VERIFY_PIN,
  VID_SECAPP_VERIFY_PIN2,
  VID_SECAPP_VERIFY_SIM,
  VID_SECAPP_VERIFY_PHONE,
  VID_SECAPP_POWERON_VERIFY_PIN,
  VID_SECAPP_POWERON_VERIFY_SIM,
  VID_SECAPP_POWERON_VERIFY_PHONE,
  VID_SECAPP_POWERON_VERIFY_MASTER_CODE,
  VID_SECAPP_POWERON_VERIFY_NETWORK,
  VID_SECAPP_POWERON_VERIFY_NETWORK_SUBSET,
  VID_SECAPP_POWERON_VERIFY_SP,
  VID_SECAPP_POWERON_VERIFY_CORPORATE,
  VID_SECAPP_POWERON_VERIFY_SIMUSIM,
  VID_SECAPP_CHANGE_PASSWROD,   //change password begin
  VID_SECAPP_CHANGE_PIN,
  VID_SECAPP_CHANGE_PIN2,
  VID_SECAPP_CHANGE_SIM,
  VID_SECAPP_CHANGE_PHONE,
  VID_SECAPP_CONFIRM_PIN,
  VID_SECAPP_CONFIRM_PIN2,
  VID_SECAPP_CONFIRM_SIM,
  VID_SECAPP_CONFIRM_PHONE,
  VID_SECAPP_UNBLOCK_LOCK,  //unblock lock begin
  VID_SECAPP_UNBLOCK_PIN,
  VID_SECAPP_UNBLOCK_PIN2,
  VID_SECAPP_UNBLOCK_CHANGE_PIN,
  VID_SECAPP_UNBLOCK_CHANGE_PIN2,
  VID_SECAPP_UNBLOCK_CONFIRM_PIN,
  VID_SECAPP_UNBLOCK_CONFIRM_PIN2,
  VID_SECAPP_ON_OFF_VIEW,
  VID_SECAPP_END = 0x1FFF
/* View ID end */
};

enum
{
/* Widget ID start */
  WID_SECAPP_START = 0x2000,
  WID_SECAPP_TITLEWIDGET,
  WID_SECAPP_MENUWIDGET,
  WID_SECAPP_MFLCONTAINER,
  WID_SECAPP_PROPCONTAINER,
  WID_SECAPP_ABSCONTAINER,
  WID_SECAPP_TEXT_INPUT_WIDGET_VERIFY,
  WID_SECAPP_TEXT_INPUT_WIDGET_MASTERKEY_VERIFY,
  WID_SECAPP_TEXT_INPUT_WIDGET_CHANGE_NEW,
  WID_SECAPP_TEXT_INPUT_WIDGET_CHANGE_CONFIRM,
  WID_SECAPP_TEXT_INPUT_WIDGET_UNBLOCK,
  WID_SECAPP_TEXT_INPUT_WIDGET_UNBLOCK_NEW,
  WID_SECAPP_TEXT_INPUT_WIDGET_UNBLOCK_CONFIRM,
  WID_SECAPP_TEXT_INPUT_TEXTWIDGET,
  WID_SECAPP_TEXT_INPUT_INPUTWIDGET,
  WID_SECAPP_END = 0x2FFF
/* Widget ID end */
};

#endif /* _SECAPPVIEW_ID_H_ */
