#ifndef __MMI_FMSCHAPP_ID_H__
#define __MMI_FMSCHAPP_ID_H__

#define FMRECSCH_RECORDS_MAX_NUM_RS (6)
#define FMSCH_RECORDS_MAX_NUM_RS (6)
#define FMR_FREQ_MAXLEN_AFTER_EXPONENT      1
#define FMR_FREQ_MAX_BYTE_SIZE_RS           10  //5 characters, ex: 100.7

typedef enum
{
    FMSCH_WND_SCH_PLAY_LIST = WND_ID_APP_BASE,
    FMSCH_WND_SET_PLAY_SCHEDULE,
    FMSCH_WND_SELECT_MENU,
    FMSCH_WND_SELECT_MY_CHANNEL,
    FMSCH_WND_MANUAL_INPUT,
    FMSCH_WND_SET_FREQUENCY,
    FMSCH_WND_SET_RECFILE,
    FMSCH_WND_SET_RECFILETYPE,
    FMSCH_WND_SET_STORAGETYPE,
    FMSCH_WND_SCH_REC_LIST,
    FMSCH_WND_SET_REC_SCHEDULE,
} FmSchWndId_e;

typedef enum
{
    FMSCHAPP_SETSCHEDULE_VIEW_BEGIN = APP_WDG_START,
    FMSCHAPP_SETSCHEDULE_SCROLLBARWIDGET,
    FMSCHAPP_SETSCHEDULE_MFLCONTAINER,
    FMSCHAPP_SETSCHEDULE_CHANNEL_FREQUENCY_DOUBLETEXTWIDGET,
    FMSCHAPP_SETSCHEDULE_TIME_TEXTTIMEWIDGET,
    FMSCHAPP_SETSCHEDULE_STATUS_TEXTPICKWIDGET,
    FMSCHAPP_SETSCHEDULE_FREQUENCY_DOUBLETEXTWIDGET,
} FmSchSetScheduleId_e;

typedef enum
{
    FMSCHAPP_SETRECSCHEDULE_VIEW_BEGIN = APP_WDG_START,
    FMSCHAPP_SETRECSCHEDULE_SCROLLBARWIDGET,
    FMSCHAPP_SETRECSCHEDULE_MFLCONTAINER,
    FMSCHAPP_SETRECSCHEDULE_CHANNEL_FREQUENCY_DOUBLETEXTWIDGET,
    FMSCHAPP_SETRECSCHEDULE_STATUS_TEXTPICKWIDGET,
    FMSCHAPP_SETRECSCHEDULE_START_DATE_TEXTDATEWIDGET,
    FMSCHAPP_SETRECSCHEDULE_START_TIME_TEXTTIMEWIDGET,
    FMSCHAPP_SETRECSCHEDULE_END_TIME_TEXTTIMEWIDGET,
    FMSCHAPP_SETRECSCHEDULE_FREQUENCY_DOUBLETEXTWIDGET,
    FMSCHAPP_SETRECSCHEDULE_RECFILE_DOUBLETEXTWIDGET,
    FMSCHAPP_SETRECSCHEDULE_RECFILETYPE_PICKTEXTWIDGET,
    FMSCHAPP_SETRECSCHEDULE_STORAGETYPE_PICKTEXTWIDGET
} FmSchSetRecScheduleId_e;

typedef enum
{
    FMSCHAPP_SELECT_MY_CHANNEL_PROPCONTAINER = APP_WDG_START,
    FMSCHAPP_SELECT_MY_CHANNEL_MENUWDG,
    FMSCHAPP_SELECT_MY_CHANNEL_THM_TEXTWDG
} FmSchSelectMyChannelViewId_e;

typedef enum
{
    FMSCHAPP_SETFREQUENCY_VIEW_BEGIN = APP_WDG_START,
} FmSchFrequencyViewId_e;

typedef enum
{

    FMSCHAPP_SELECT_MY_CHANNEL,
    FMSCHAPP_MANUAL_INPUT
} FmSchSelectFrequencyMenu_e;

#endif //__MMI_FMSCHAPP_ID_H__
