////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (¡§MStar Confidential Information¡¨) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

/**
* @file    mmi_mainitem.h
* @version
* @brief
*
*/
#ifndef 	__MMI_MENUITEM_H_
#define 	__MMI_MENUITEM_H_

#include "mmi_mae_common_def.h"
#include "mmi_clstbl.h"
#include "mmi_cfgsrv.h"
#include "mmi_sssrv_def.h"
#include "mmi_stksrv_def.h"
#include "mmi_ccsrv.h"
#include "mmi_evtcentersrv.h"

#include "mmi_camapp.h"
#include "mmi_calllogapp.h"
#include "mmi_messagecenterapp.h"
#include "mmi_settingapp.h"
#include "mmi_evtcenterapp.h"
#include "mmi_shortcutsapp.h"
#include "mmi_ccapp.h"
#include "mmi_emapp.h"
#include "mmi_keyguardapp.h"
#include "mmi_phbapp.h"
#include "mmi_secapp.h"
#include "mmi_mplayerapp.h"
#include "mmi_offapp.h"
#include "mmi_filemgrapp.h"

#include "mmi_common_content.h"
#include "mae_textlabel.h"
#include "img_data.h"
#include "mmi_mainmenuapp_id.h"
#include "Rs_layout_id.h"

#ifdef __APP_MMI_FM_SCHEDULE__
#include "mmi_fmschapp.h"
#endif

#ifdef __NCCQQ_MMI__
#include "QQApp_resource.h"
#endif // #ifdef __NCCQQ_MMI__

#if defined(__YOUTUBE_MMI_CDWAP__) || defined(__YOUKU_MMI_CDWAP__) || defined(__VUCLIP_MMI_CDWAP__) || defined(__BAIDU_MMI_CDWAP__)
#include "mmi_cdwapapp.h"
#endif

#include "mmi_tvsrv_def.h"
//Start Menu Item UserData Num
#define USERDATA_NUM	 	1	//now must 	>=1
								//grid list >=0
								//spin 	 	>=1
#define ITEM_VISABLE_MASK				0x0001
#define ITEM_MOVABLE_MASK				0x0002
//flag bit function
// 	15	14	13	12	11	10	09	08	07	06	05	04	03	02	01	00
//	 														 | 	 |
//	 													     	 |	 +------------visable
//	 														+----------------movable
typedef struct
{
	u16 nId;		//menu item id
	u16 nParentId;	//Parent menu item id
	u32 nTextId;	//text 	id
	u32	nImgId;		//image id
	u16	nClsId;		//class id
	u32 nParam;		//start param
	u16 nFlag;		//flag (visable, movable, ...)
	u32 nUserData[USERDATA_NUM]; //
}MenuItemData_t;

//#if defined(__UI_STYLE_MMI_MAIN_MENU_GRID_AND_LIST__) || defined(__UI_STYLE_MMI_MAIN_MENU_SPIN__)
//static const MCA_Start_t _g_MCA = {MCA_E_START_MENU, NULL, MCA_E_MAIN_MENU};
//#endif


#ifdef __UI_STYLE_MMI_MAIN_MENU_GRID_AND_LIST__
//grid list style
static const MenuItemData_t g_GridListMenuData[]={
// nId 					nParentId	nTextId						nImgId							nClsId				nParam			nFlag
{MNU_MAIN_MESSAGES,		MNU_MAIN_MAIN,	  TXT_LIL_N_MESSAGES,		THM_MAINMENU_IMG_GRID_FOCUS_01,		CLSID_MCA,				0/*(u32)&_g_MCA*/, 					ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_CALL_HISTORY,	MNU_MAIN_MAIN,	  TXT_LIL_N_CALL_HISTORY,	THM_MAINMENU_IMG_GRID_FOCUS_02,		CLSID_CALLLOGAPP,		MMI_CALLLOG_AP_SHOW_ALL_LIST,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_PHONE_BOOK,		MNU_MAIN_MAIN,	  TXT_LIL_N_PHONEBOOK,		THM_MAINMENU_IMG_GRID_FOCUS_03,		CLSID_PHBAP,			0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_FILE_MANAGER,	MNU_MAIN_MAIN,	  TXT_LIL_N_FILE_MANAGER,	THM_MAINMENU_IMG_GRID_FOCUS_04,		CLSID_FILEMGRAPP,		0,								ITEM_VISABLE_MASK, {0}},
#ifdef __MMI_KING_MOVIE__
#if defined (__MMI_KING_MOVIE_3D__) && (__MMI_KING_MOVIE_3D_APP_INDIE__)
{MNU_MAIN_KINGMOVIE,		MNU_MAIN_MAIN,	  TXT_LIL_N_KING_MOVIE,		THM_MAINMENU_IMG_GRID_FOCUS_05,		0,		0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_2DKINGMOVIE,        MNU_MAIN_KINGMOVIE,    TXT_LIL_N_KING_MOVIE,     IMG_NULL_ID,     CLSID_KINGMOVIEAPP,      0,                              ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_3DKINGMOVIE,        MNU_MAIN_KINGMOVIE,    TXT_LIL_N_3DKMV,     IMG_NULL_ID,     CLSID_3DKINGMOVIEAPP,      0,                              ITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_KINGMOVIE,		MNU_MAIN_MAIN,	  TXT_LIL_N_KING_MOVIE,		THM_MAINMENU_IMG_GRID_FOCUS_05,		CLSID_KINGMOVIEAPP,		0,								ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_MULTIMEDIA,		MNU_MAIN_MAIN,	  TXT_LIL_N_MULTIMEDIA,		THM_MAINMENU_IMG_GRID_FOCUS_06,		0,						0,								ITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_MULTIMEDIA,		MNU_MAIN_MAIN,	  TXT_LIL_N_MULTIMEDIA,		THM_MAINMENU_IMG_GRID_FOCUS_05,		0,						0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_PROFILES,			MNU_MAIN_MAIN,	  TXT_LIL_N_PROFILES,			THM_MAINMENU_IMG_GRID_FOCUS_06,		CLSID_PROFILEAPP,		0,								ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ORGANIZER,		MNU_MAIN_MAIN,	  TXT_LIL_N_ORGANIZER,		THM_MAINMENU_IMG_GRID_FOCUS_07,		0,						0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_GAMES,			MNU_MAIN_MAIN,	  TXT_LIL_N_GAMES,			THM_MAINMENU_IMG_GRID_FOCUS_08,		0,						0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_TOOLS,			MNU_MAIN_MAIN,	  TXT_LIL_N_TOOLS,			THM_MAINMENU_IMG_GRID_FOCUS_09,		0,						0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_APPLICATIONS,		MNU_MAIN_MAIN,	  TXT_LIL_N_APPLICATIONS,		THM_MAINMENU_IMG_GRID_FOCUS_10,		0,						0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_SETTINGS,			MNU_MAIN_MAIN,	  TXT_LIL_N_SETTINGS,			THM_MAINMENU_IMG_GRID_FOCUS_11,		CLSID_SETTINGAPP,		0,								ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_SERVICES,		MNU_MAIN_MAIN,	  TXT_LIL_N_SERVICES,		THM_MAINMENU_IMG_GRID_FOCUS_12,		0,						0,								ITEM_VISABLE_MASK, {0}},
//Message
{MNU_MSG_MCA_MESSAGE_CENTER,	MNU_MAIN_MESSAGES,		TXT_LIL_N_MESSAGE_CENTER,	IMG_NULL_ID,			CLSID_MCA,			  	 MCA_E_START_MENU,				 ITEM_VISABLE_MASK, {0}},
//Services
#ifdef __RFID_MMI__
{MNU_MAIN_RFID_FUNC,	MNU_MAIN_SERVICES,		TXT_LIL_N_RFID_DEMO,		IMG_NULL_ID,	CLSID_RFIDDEMOAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __WAP_MMI__
{MNU_MAIN_WAP_EXPLORER,	MNU_MAIN_SERVICES,		TXT_LIL_N_CDW_WAP_EXPLORER,	IMG_NULL_ID,	CLSID_CDWAPAPP,			0,		ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __EMAIL_MMI__
{MNU_MAIN_EMAIL, MNU_MAIN_SERVICES, TXT_LIL_N_EMAIL, IMG_NULL_ID, CLSID_EMAILAPP, 0, ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __BLUETOOTH_MMI__
{MNU_MAIN_BLUETOOTH,		MNU_MAIN_SERVICES,		TXT_LTL_N_BLUETOOTH,		IMG_NULL_ID,	CLSID_BTAPP,			0,		ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_SIM_SERVICE_1,MNU_MAIN_SERVICES,		TXT_NULL_ID,					IMG_NULL_ID,	CLSID_STKAPP,			STKSRV_CMD_SETUPMENU,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_SIM_SERVICE_2,MNU_MAIN_SERVICES,		TXT_NULL_ID,					IMG_NULL_ID,	CLSID_STKAPP2,			STKSRV_CMD_SETUPMENU,	ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_EVENTCENTER__
{MNU_MAIN_EVENT_CENTER,	MNU_MAIN_SERVICES,		TXT_LIL_N_EVENT_CENTER,	IMG_NULL_ID,	CLSID_EVTCENTERAPP,		EvtCenterApp_Start_AllEvtSummary,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE__
{MNU_MAIN_SXM_VIDEO_CHAT,  MNU_MAIN_SERVICES,     	TXT_OIL2_N_VIDEO_CHAT,                           IMG_NULL_ID,    CLSID_SXM_VCHAT,    0x0300009a, ITEM_VISABLE_MASK, {0}},
#ifdef __SXMENGINE_BOOKSTORE__
{MNU_MAIN_SXM_LIBRARY,     MNU_MAIN_SERVICES,     	TXT_LIL_N_POI_EDUCATION_BOOK_STORE,         IMG_NULL_ID,    CLSID_SXM_BOOK,     0x0300000B, ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE_GAME__
{MNU_MAIN_SXM_GAMES,       MNU_MAIN_SERVICES,      	TXT_DSL_N_GAME,                             IMG_NULL_ID,    CLSID_SXM_GAME,     0x03000000, ITEM_VISABLE_MASK, {0}},
#endif
#endif
//Tool
#ifdef __APP_MMI_CALCULATOR__
{MNU_MAIN_CALCULATOR,			MNU_MAIN_TOOLS,			TXT_LIL_N_CALCULATOR,		IMG_NULL_ID,	CLSID_CALCULATORAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_CALCULATOR_PLUS__
{MNU_MAIN_CALCULATOR,			MNU_MAIN_TOOLS,			TXT_LIL_N_CALCULATOR,		IMG_NULL_ID,	CLSID_CALCULATORPLUSAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_UNITCONVERTER__
{MNU_MAIN_UNIT_CONVERTER,		MNU_MAIN_TOOLS,			TXT_LIL_N_CONVERTER,		IMG_NULL_ID,	CLSID_UNITCONVERTER, 	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_STOPWATCH__
{MNU_MAIN_STOPWATCH,			MNU_MAIN_TOOLS,			TXT_LIL_N_STOPWATCH,		IMG_NULL_ID,	CLSID_STOPWATCHAPP,		0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_COUNTDOWN_TIMER__
{MNU_MAIN_COUNTDOWN_TIMER,	MNU_MAIN_TOOLS,			TXT_LIL_N_COUNTDOWN_TIMER,	IMG_NULL_ID,	CLSID_COUNTDOWNTIMER, 	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_WORLDCLOCK__
{MNU_MAIN_WORLD_CLOCK,		MNU_MAIN_TOOLS,			TXT_LIL_N_WORLD_CLOCK,		IMG_NULL_ID,	CLSID_WORLDCLOCKAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_SHORTCUTLIST__
{MNU_MAIN_SHORTCUTS,			MNU_MAIN_TOOLS,			TXT_LIL_N_SHORTCUTS,		IMG_NULL_ID,	CLSID_SHORTCUTSAPP,		SHORTCUTS_ENTRY_SHORTCUTS,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_BMI__
{MNU_MAIN_BMI,					MNU_MAIN_TOOLS,			TXT_LIL_N_BMI,				IMG_NULL_ID,	CLSID_BMI,				0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_LICENSEMGR__
{MNU_MAIN_LICENSEMGR,			MNU_MAIN_TOOLS,			TXT_LIL_N_LICENSEMGR,		IMG_NULL_ID,	CLSID_LICENSEMGRAPP,		0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_AZAN__
{MNU_MAIN_AZAN,					MNU_MAIN_TOOLS,			TXT_LIL_N_AZAN_ALARM,				IMG_NULL_ID,	CLSID_AZANAPP,				0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __CALLER_LOCATION__
{MNU_MAIN_CALLERLOCATION,		MNU_MAIN_TOOLS,			TXT_LIL_N_CALLER_LOCATION,				IMG_NULL_ID,	CLSID_CALLERLOCATIONAPP,				0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_NTP__
{MNU_MAIN_NTP,                  MNU_MAIN_TOOLS,         TXT_LIL_N_NTP,			    IMG_NULL_ID,    CLSID_NTPAPP,		0,      ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SRE__
{MNU_MAIN_SRE,		            MNU_MAIN_TOOLS,			TXT_LIL_N_SRE,				        IMG_NULL_ID,	CLSID_SRE,		            0,      ITEM_VISABLE_MASK, {0}},
#endif /// __SRE__
//{MNU_MAIN_PCSYNCTOOL,			MNU_MAIN_TOOLS,			TXT_LIL_N_PC_SYNC_TOOL,		IMG_NULL_ID,	CLSID_USBAPP,			0,		ITEM_VISABLE_MASK},
#ifdef __PC_SIMULATOR__
//{MNU_MAIN_UNITTESTAPP,          MNU_MAIN_TOOLS,         TXT_LIL_N_UNITTESTAPP,      IMG_NULL_ID,    CLSID_UNITTEST,         0,      ITEM_VISABLE_MASK, {0}},
#endif
//multimedia
/* move the camera selection setting to camer/camcorder AP
#ifdef __DUAL_CAMERA_MMI__
{MNU_MAIN_CAMERA_SELECT,  MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CAMERA_SELECT,    	IMG_NULL_ID,	CLSID_SETTINGAPP, SETTINGAPType_CameraType, ITEM_VISABLE_MASK, {0}},
#endif*/
#if defined(__ENABLE_CAMERA__)
{MNU_MAIN_CAMERA,				MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_CAMERA,			IMG_NULL_ID,	CLSID_CAMAPP,			CAM_PICTURE_MODE,		ITEM_VISABLE_MASK, {0}},
#endif
#if defined(__ENABLE_CAMCORDER__)
{MNU_MAIN_VIDEO_RECORDER,		MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_CAMCORDER,		IMG_NULL_ID,	CLSID_CAMAPP,			CAM_VIDEO_MODE,			ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_MUSIC_PLAYER,		MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_MUSIC,			IMG_NULL_ID,	CLSID_MPLAYERAPP,		MPLAYER_MODE_MUSIC, 	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_VIDEO_PLAYER,		MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_VIDEO_PLAYER,		IMG_NULL_ID,	CLSID_FILEMGRAPP,	FILEMGRAPP_VIDEO_FILE,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_PHOTO_VIEWER,		MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_PHOTOS,			IMG_NULL_ID,	CLSID_FILEMGRAPP,	FILEMGRAPP_PICTURE_FILE,ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_FM_RADIO__
#ifdef __APP_MMI_FM_SCHEDULE__
{MNU_MAIN_FM_RADIO,			MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IMG_NULL_ID,	0,		0,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_FM_RADIO,         MNU_MAIN_FM_RADIO,    TXT_LIL_N_FM_RADIO_PLAYER,         IMG_NULL_ID,    CLSID_FMRADIOAPP,       0,  ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_FM_RADIO_REC__
{MNU_MAIN_FM_SCHEDULE_RECORD,   MNU_MAIN_FM_RADIO,  TXT_LIL_N_FM_RECORD_SCHEDULE,   IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE_RECORD,     ITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_RADIO_REC__
{MNU_MAIN_FM_SCHEDULE_PLAY,     MNU_MAIN_FM_RADIO,  TXT_LIL_N_FM_SCHEDULE,      IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE,        ITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_FM_RADIO,			MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IMG_NULL_ID,	CLSID_FMRADIOAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_SCHEDULE__
#endif //__APP_MMI_FM_RADIO__

#ifdef __APP_MMI_VOICE_MEMO__
{MNU_MAIN_VOICE_MEMO,			MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_VOICE_MEMO,		IMG_NULL_ID,	CLSID_VOICEMEMOAPP,	0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __ATV_MMI__
#ifdef __ATV_CMMB__
{MNU_MAIN_ATV,                          MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CMMB,                 IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_CMMB,        ITEM_VISABLE_MASK, {0}},
#else // !__ATV_CMMB__
{MNU_MAIN_ATV,                          MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_ATV,                  IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ANALOG,      ITEM_VISABLE_MASK, {0}},
#ifdef __ATV_ISDBT__
{MNU_MAIN_ISDBT,                        MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_ISDBT,                IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ISDBT,       ITEM_VISABLE_MASK, {0}},
#endif // __ATV_ISDBT__
#endif // __ATV_CMMB__
#endif // __ATV_MMI__
#ifdef __APP_MMI_TUDOU__
{MNU_MAIN_TUDOU,                          MNU_MAIN_MULTIMEDIA,    TXT_CCL_N_COMMON_TUDOU,                  IMG_NULL_ID,    CLSID_TUDOUAPP,           0,      ITEM_VISABLE_MASK, {0}},
#endif
//organizer
#ifdef __APP_MMI_CALENDAR__
{MNU_MAIN_CALENDAR,			MNU_MAIN_ORGANIZER,		TXT_LIL_N_CALENDAR,			IMG_NULL_ID,	CLSID_CALENDARAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ALARM,				MNU_MAIN_ORGANIZER,		TXT_LIL_N_ALARM,			IMG_NULL_ID,	CLSID_ALARMAPP,			0,	ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_NOTEPAD__
{MNU_MAIN_NOTEPAD,        			MNU_MAIN_ORGANIZER,   TXT_LTL_N_NOTEPAD,          IMG_NULL_ID,    CLSID_NOTEPADAPP,       0,  ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_TODOLIST__
{MNU_MAIN_TODO,                 MNU_MAIN_ORGANIZER,     TXT_LTL_N_TODO_LIST,        IMG_NULL_ID,  CLSID_TODOLISTAPP,     0,    ITEM_VISABLE_MASK, {0}},
#endif
//Game
#ifdef __APP_MMI_SKETCHNOTE__
{MNU_MAIN_SNOTE,				MNU_MAIN_ORGANIZER, 	TXT_LIL_N_SKETCH_NOTE,		IMG_NULL_ID,	CLSID_SNOTEAPP, 		0,	ITEM_VISABLE_MASK},
#endif
//Game
#if defined(__GAME_ENGINE_EMU_MMI__)
{MNU_MAIN_EMU,						MNU_MAIN_GAMES,			TXT_LIL_N_EMU_GAMES,		IMG_NULL_ID,	CLSID_EMUAPP,			0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SKYENGINE__
{MNU_MAIN_VENDOR_GAMES, 	MNU_MAIN_GAMES,			TXT_LIL_N_GAMES,			IMG_NULL_ID,	CLSID_SKY_ENGINE_GAME_APP,		1,						ITEM_VISABLE_MASK},
#endif
#if (defined(__GOGOBOX_GAME__))
{MNU_MAIN_GOGOBOX,			  MNU_MAIN_GAMES,			TXT_LIL_N_GOGOBOXGAME,	IMG_NULL_ID,	CLSID_GOGOBOXGAME,		0,			ITEM_VISABLE_MASK, {0}},
#endif

#ifdef  __NATIVE_GAME_MMI_PACMAN__
{MNU_MAIN_PACMAN,			  MNU_MAIN_GAMES,			TXT_LIL_N_PACMAN,	IMG_NULL_ID,	CLSID_PACMAN,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_BIG2__
{MNU_MAIN_BIG2,			  MNU_MAIN_GAMES,			TXT_LIL_N_BIGTWO,	IMG_NULL_ID,	CLSID_BIG2,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef	 __NATIVE_GAME_MMI_FRUIT__
{MNU_MAIN_FRUIT,			  MNU_MAIN_GAMES,			TXT_LIL_N_FRUIT,	IMG_NULL_ID,	CLSID_FRUITGAMBLEGAME,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_PUZZLE__
{MNU_MAIN_PUZZLE,			  MNU_MAIN_GAMES,			TXT_LIL_N_PUZZLE,	IMG_NULL_ID,	CLSID_PUZZLEAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_HAMSTERFIGHT__
{MNU_MAIN_HAMSTERFIGHT,			  MNU_MAIN_GAMES,			TXT_LIL_N_HAMSTERFIGHT,	IMG_NULL_ID,	CLSID_HAMSTERFIGHTAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_LINKUP__
{MNU_MAIN_LINKUP,			  MNU_MAIN_GAMES,			TXT_LIL_N_LINKUP,	IMG_NULL_ID,	CLSID_LINKUPAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_GOBANG__
{MNU_MAIN_GOBANG,			  MNU_MAIN_GAMES,			TXT_LIL_N_GOBANG,	IMG_NULL_ID,	CLSID_GOBANGAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_SOKOBAN__
{MNU_MAIN_SOKOBAN,			  MNU_MAIN_GAMES,			TXT_LIL_N_SOKOBAN,	IMG_NULL_ID,	CLSID_SOKOBANAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif
#ifdef  __NATIVE_GAME_MMI_SUDOKU__
{MNU_MAIN_SUDOKU,			  MNU_MAIN_GAMES,			TXT_LIL_N_SUDOKU,	IMG_NULL_ID,	CLSID_SUDOKUAPP,		0,			ITEM_VISABLE_MASK, {0}},
#endif

//Application
#ifdef __MAP_MMI__
{MNU_MAIN_MAP,					MNU_MAIN_APPLICATIONS,	TXT_LIL_N_MAP,				IMG_NULL_ID,	CLSID_MAPAPP,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __E_BOOK_MMI__
{MNU_MAIN_E_BOOK,				MNU_MAIN_APPLICATIONS,	TXT_LIL_N_E_BOOK,			IMG_NULL_ID,	CLSID_E_BOOK,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __DICTAPP_MMI__
{MNU_MAIN_DICT,					MNU_MAIN_APPLICATIONS,	TXT_LIL_N_DICT,				IMG_NULL_ID,	CLSID_DICTAPP,			0,	ITEM_VISABLE_MASK, {0}},
#endif


#ifdef __TENCENT_MCARE__
#ifdef __TENCENT_MCARE_QXIN__
{MNU_MAIN_MCARE,				MNU_MAIN_APPLICATIONS,	TXT_LIL_N_QQ,			IMG_NULL_ID,	CLSID_TENCENT_MCARE_QXIN,		0,	ITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_MCARE,				MNU_MAIN_APPLICATIONS,	TXT_LIL_N_QQ,			IMG_NULL_ID,	CLSID_TENCENT_MCARE,		0,	ITEM_VISABLE_MASK, {0}},
#endif
#endif

#ifdef __ZYUE_ENGINE__//TXT_LIL_N_ZHANGYUE_APP
{MNU_MAIN_ZHANGYUE_EBOOK,     MNU_MAIN_APPLICATIONS, TXT_LIL_N_ZHANGYUE_EBOOK,            IMG_NULL_ID,    CLSID_3RD_ZHANGYUE_EBOOK,        1,                        ITEM_VISABLE_MASK},
#endif

#ifdef __JAVA_MMI__
{MNU_MAIN_JAVAAMS,			MNU_MAIN_APPLICATIONS,	TXT_LIL_N_JAVA,				IMG_NULL_ID,	CLSID_JAVAAMSAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __NCCQQ_MMI__
{MNU_MAIN_QQAPPNEW,		MNU_MAIN_APPLICATIONS,	  TXT_LIL_N_QQ,		           IMG_NULL_ID,		            CLSID_QQAPP,				0,			        ITEM_VISABLE_MASK, {0}},
#else //__NCCQQ_MMI__
#ifdef __SKYENGINE__
{MNU_MAIN_QQ,						MNU_MAIN_APPLICATIONS,	TXT_LIL_N_QQ,				IMG_NULL_ID,	CLSID_SKY_ENGINE_QQ_APP,		0,						ITEM_VISABLE_MASK},
{MNU_MAIN_VENDOR_GAMES, MNU_MAIN_APPLICATIONS,	TXT_LIL_N_GAMES,			IMG_NULL_ID,	CLSID_SKY_ENGINE_GAME_APP,		1,						ITEM_VISABLE_MASK},
#endif
#endif //#ifndef __NCCQQ_MMI__

#ifdef __ZMOL__
{MNU_MAIN_ZMOL_APP,	MNU_MAIN_APPLICATIONS,	TXT_LIL_N_ZMOLAPP,	IMG_NULL_ID,	CLSID_ZMOL_APP,	0,	ITEM_VISABLE_MASK},
#endif

#if (defined(__MMI_GTSBOX_MBLOG_DYNAMIC__) || defined(__MMI_GTSBOX_MBLOG_STATIC__))
{MNU_MAIN_GTSBOX,	MNU_MAIN_APPLICATIONS,	TXT_LIL_N_SINA_WEIBO,	IMG_NULL_ID,	CLSID_GTSBOX_APP,	114,	ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __APP_MMI_VENDOR_LIST__
{MNU_MAIN_MORE,					MNU_MAIN_APPLICATIONS,	TXT_LIL_N_MORE,				IMG_NULL_ID,	CLSID_VENDORLISTAPP,0,						ITEM_VISABLE_MASK},
#endif
#ifdef __MMI_SEARCH_APP__
{MNU_MAIN_SEARCH,				MNU_MAIN_APPLICATIONS,	TXT_LTL_N_SEARCH,			IMG_NULL_ID,	CLSID_SEARCHAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __MMI_KMX_TT__
{MNU_MAIN_KMX_TT_APP,   MNU_MAIN_APPLICATIONS,  TXT_LIL_N_KMXTT,      IMG_NULL_ID,  CLSID_KMX_TT_APP, 0x0300009a,   ITEM_VISABLE_MASK, {0}},
#endif
//Setting
{MNU_SETTING_PHONE_SETTINGS,	MNU_MAIN_SETTINGS,		TXT_LIL_N_PHONE_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_PhoneSettings,	ITEM_VISABLE_MASK, {0}},
{MNU_SETTING_DISPLAY_SETTINGS,	MNU_MAIN_SETTINGS,		TXT_LIL_N_DISPLAY_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_DisplaySettings,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_PROFILES,					MNU_MAIN_SETTINGS,		TXT_LIL_N_PROFILES,			IMG_NULL_ID,	CLSID_PROFILEAPP,		0,								ITEM_VISABLE_MASK, {0}},
{MNU_SETTING_RINGTONE_SETTINGS,	MNU_MAIN_SETTINGS,		TXT_LIL_N_RINGTONE_SETTINGS,IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_RingtoneSettings,	ITEM_VISABLE_MASK, {0}},
{MNU_CS_CALL_SETTINGS,			MNU_MAIN_SETTINGS,		TXT_LIL_N_CALL_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_CallSettings,		ITEM_VISABLE_MASK, {0}},
{MNU_SETTING_CONNECT_SETTING,	MNU_MAIN_SETTINGS,		TXT_LIL_N_CONNECT_SETTING,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_ConnectSettings,	ITEM_VISABLE_MASK, {0}},
{MNU_NETWORK_NETWORK_SETTINGS,	MNU_MAIN_SETTINGS,		TXT_LIL_N_NETWORK_SETTINGS,	IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_NetworkSettings,	ITEM_VISABLE_MASK, {0}},
{MNU_SETTING_SWITCH_MODE,		MNU_MAIN_SETTINGS,		TXT_LIL_N_SWITCH_MODE,		IMG_NULL_ID,	CLSID_SWITCHMODE,		PowerOffType_SwitchDualMode,	ITEM_VISABLE_MASK, {0}},
{MNU_SEC_SECURITY,				MNU_MAIN_SETTINGS,		TXT_LIL_N_SECURITY,			IMG_NULL_ID,	CLSID_SETTINGAPP,		SETTINGAPType_Security,			ITEM_VISABLE_MASK, {0}},

#ifdef __YOUTUBE_MMI_CDWAP__
{MNU_MAIN_YOUTUBE,     MNU_MAIN_SERVICES,    TXT_LIL_N_CDW_YOUTUBE, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_YOUTUBE,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __YOUKU_MMI_CDWAP__
{MNU_MAIN_YOUKU,     MNU_MAIN_SERVICES,    TXT_LIL_N_CDW_YOUKU, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_YOUKU,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __VUCLIP_MMI_CDWAP__
{MNU_MAIN_VUCLIP,     MNU_MAIN_SERVICES,    TXT_LIL_N_CDW_VUCLIP, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_VUCLIP,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __BAIDU_MMI_CDWAP__
{MNU_MAIN_BAIDU,     MNU_MAIN_SERVICES,    TXT_LIL_N_CDW_BAIDU, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_BAIDU,  ITEM_VISABLE_MASK, {0}},
#endif

};
#endif //__UI_STYLE_MMI_MAIN_MENU_GRID_AND_LIST__


#ifdef __UI_STYLE_MMI_MAIN_MENU_SPIN__
//spin style
static const MenuItemData_t g_SpinMenuData[]={
// nId 						nParentId			nTextId						nImgId							nClsId				nParam			nFlag
{MNU_MAIN_MESSAGES,MNU_MAIN_MAIN,    TXT_LIL_N_MESSAGES,       MAINMENU_IMG_SPIN_MESSAGES,        CLSID_MCA,          0/*(u32)&_g_MCA*/, ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_MESSAGES}},
{MNU_MAIN_CALL_HISTORY,     MNU_MAIN_MAIN,    TXT_LIL_N_CALL_HISTORY,   MAINMENU_IMG_SPIN_CALLHISTORY,     CLSID_CALLLOGAPP,       MMI_CALLLOG_AP_SHOW_ALL_LIST,   ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_CALLHISTORY}},
{MNU_MAIN_PHONE_BOOK,       MNU_MAIN_MAIN,    TXT_LIL_N_PHONEBOOK,      MAINMENU_IMG_SPIN_PHONEBOOK,     	CLSID_PHBAP,            0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_PHONEBOOK}},
{MNU_MAIN_FILE_MANAGER,     MNU_MAIN_MAIN,    TXT_LIL_N_FILE_MANAGER,   MAINMENU_IMG_SPIN_FILEMANAGER,     CLSID_FILEMGRAPP,  0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_FILEMANAGER}},
{MNU_MAIN_MULTIMEDIA,       	MNU_MAIN_MAIN,    TXT_LIL_N_MULTIMEDIA,     MAINMENU_IMG_SPIN_MEDIATOOLS,      0,                  	0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_MEDIATOOLS}},
{MNU_MAIN_APPLICATIONS,     MNU_MAIN_MAIN,    TXT_LIL_N_APPLICATIONS,   MAINMENU_IMG_SPIN_ORGANIZER,       0,                  	0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_ORGANIZER}},
{MNU_MAIN_GAMES,            MNU_MAIN_MAIN,    TXT_LIL_N_GAMES,          MAINMENU_IMG_SPIN_ENTERTAINMENT,   0,                  	0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_ENTERTAINMENT}},
{MNU_MAIN_TOOLS,	    	 		MNU_MAIN_MAIN,    TXT_LIL_N_TOOLS,     	 		MAINMENU_IMG_SPIN_TOOLS,     			0,                  	0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_TOOLS}},
{MNU_MAIN_SETTINGS, 	     	MNU_MAIN_MAIN,    TXT_LIL_N_SETTINGS,     	MAINMENU_IMG_SPIN_SETTINGS,     	CLSID_SETTINGAPP,      	0,      ITEM_VISABLE_MASK, {MAIN_MENU_THUMBNAIL_SETTINGS}},
//multimedia
/* move the camera selection setting to camer/camcorder AP
#ifdef __DUAL_CAMERA_MMI__
{MNU_MAIN_CAMERA_SELECT,    MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CAMERA_SELECT,    	IMG_NULL_ID,	CLSID_SETTINGAPP, SETTINGAPType_CameraType, ITEM_VISABLE_MASK, {0}},
#endif*/
#if defined(__ENABLE_CAMERA__)
{MNU_MAIN_CAMERA,   			  MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CAMERA,    		IMG_NULL_ID,	CLSID_CAMAPP,			CAM_PICTURE_MODE,		ITEM_VISABLE_MASK, {0}},
#endif
#if defined(__ENABLE_CAMCORDER__)
{MNU_MAIN_VIDEO_RECORDER,   MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CAMCORDER,   	IMG_NULL_ID,	CLSID_CAMAPP,			CAM_VIDEO_MODE,			ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_MUSIC_PLAYER,  		MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_MUSIC,   			IMG_NULL_ID,	CLSID_MPLAYERAPP,		MPLAYER_MODE_MUSIC, 	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_VIDEO_PLAYER,    	MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_VIDEO_PLAYER,	IMG_NULL_ID,	CLSID_FILEMGRAPP,	FILEMGRAPP_VIDEO_FILE,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_PHOTO_VIEWER,    	MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_PHOTOS,				IMG_NULL_ID,	CLSID_FILEMGRAPP,	FILEMGRAPP_PICTURE_FILE,ITEM_VISABLE_MASK, {0}},
#ifdef __MMI_KING_MOVIE__
#if defined (__MMI_KING_MOVIE_3D__) && (__MMI_KING_MOVIE_3D_APP_INDIE__)
 {MNU_MAIN_KINGMOVIE,        MNU_MAIN_MAIN,    TXT_LIL_N_KING_MOVIE,     THM_MAINMENU_IMG_GRID_FOCUS_05,     0,      0,                              ITEM_VISABLE_MASK, {0}},
 {MNU_MAIN_2DKINGMOVIE,        MNU_MAIN_KINGMOVIE,    TXT_LIL_N_KING_MOVIE,     IMG_NULL_ID,     CLSID_KINGMOVIEAPP,      0,                              ITEM_VISABLE_MASK, {0}},
 {MNU_MAIN_3DKINGMOVIE,        MNU_MAIN_KINGMOVIE,    TXT_LIL_N_3DKMV,     IMG_NULL_ID,     CLSID_3DKINGMOVIEAPP,      0,                              ITEM_VISABLE_MASK, {0}},
#else
 {MNU_MAIN_KINGMOVIE,     	MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_KING_MOVIE,   IMG_NULL_ID,      CLSID_KINGMOVIEAPP,     0,                              ITEM_VISABLE_MASK, {0}},
#endif
#endif
#ifdef __APP_MMI_FM_RADIO__
{MNU_MAIN_FM_RADIO,	    		MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_FM_RADIO,    	IMG_NULL_ID,	CLSID_FMRADIOAPP,		0,						ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_FM_RADIO__
#ifdef __APP_MMI_FM_SCHEDULE__
{MNU_MAIN_FM_RADIO,			MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IMG_NULL_ID,	0,		0,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_FM_RADIO,         MNU_MAIN_FM_RADIO,    TXT_LIL_N_FM_RADIO_PLAYER,         IMG_NULL_ID,    CLSID_FMRADIOAPP,       0,  ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_FM_RADIO_REC__
{MNU_MAIN_FM_SCHEDULE_RECORD,   MNU_MAIN_FM_RADIO,  TXT_LIL_N_FM_RECORD_SCHEDULE,   IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE_RECORD,     ITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_RADIO_REC__
{MNU_MAIN_FM_SCHEDULE_PLAY,     MNU_MAIN_FM_RADIO,  TXT_LIL_N_FM_SCHEDULE,      IMG_NULL_ID,    CLSID_FMSCHAPP,         FMSCHAPP_START_TYPE_FM_SCHEDULE,        ITEM_VISABLE_MASK, {0}},
#else
{MNU_MAIN_FM_RADIO,			MNU_MAIN_MULTIMEDIA,	TXT_LIL_N_FM_RADIO,			IMG_NULL_ID,	CLSID_FMRADIOAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif //__APP_MMI_FM_SCHEDULE__
#endif //__APP_MMI_FM_RADIO__


#ifdef __APP_MMI_VOICE_MEMO__
{MNU_MAIN_VOICE_MEMO,      	MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_VOICE_MEMO,   IMG_NULL_ID,    CLSID_VOICEMEMOAPP,       0,                      ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __ATV_MMI__
#ifdef __ATV_CMMB__
{MNU_MAIN_ATV,                  MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_CMMB,                 IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_CMMB,        ITEM_VISABLE_MASK, {0}},
#else // !__ATV_CMMB__
{MNU_MAIN_ATV,                  MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_ATV,                  IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ANALOG,      ITEM_VISABLE_MASK, {0}},
#ifdef __ATV_ISDBT__
{MNU_MAIN_ISDBT,                MNU_MAIN_MULTIMEDIA,    TXT_LIL_N_ISDBT,                IMG_NULL_ID,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ISDBT,       ITEM_VISABLE_MASK, {0}},
#endif // __ATV_ISDBT__
#endif // __ATV_CMMB__
#endif // __ATV_MMI__

//Application
#ifdef __APP_MMI_CALENDAR__
{MNU_MAIN_CALENDAR,      		MNU_MAIN_APPLICATIONS,    TXT_LIL_N_CALENDAR,  	IMG_NULL_ID,	CLSID_CALENDARAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_ALARM,        		MNU_MAIN_APPLICATIONS,    TXT_LIL_N_ALARM,  		IMG_NULL_ID,	CLSID_ALARMAPP,			0,	ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_NOTEPAD__
{MNU_MAIN_NOTEPAD,          MNU_MAIN_APPLICATIONS,     TXT_LTL_N_NOTEPAD,   IMG_NULL_ID,    CLSID_NOTEPADAPP,       0,  ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_TODOLIST__
{MNU_MAIN_TODO,                 MNU_MAIN_ORGANIZER,  TXT_LIL_N_TO_DO_LIST,   IMG_NULL_ID,  CLSID_TODOLISTAPP,     0,    ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_SKETCHNOTE__
{MNU_MAIN_SNOTE,            MNU_MAIN_APPLICATIONS,     TXT_LIL_N_SKETCH_NOTE,IMG_NULL_ID,    CLSID_SNOTEAPP,         0,  ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __MAP_MMI__
{MNU_MAIN_MAP, 	        		MNU_MAIN_APPLICATIONS,    TXT_LIL_N_MAP,     		IMG_NULL_ID,	CLSID_MAPAPP,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __E_BOOK_MMI__
{MNU_MAIN_E_BOOK,          	MNU_MAIN_APPLICATIONS,    TXT_LIL_N_E_BOOK,    	IMG_NULL_ID,	CLSID_E_BOOK,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __DICTAPP_MMI__
{MNU_MAIN_DICT,          		MNU_MAIN_APPLICATIONS,    TXT_LIL_N_DICT,  			IMG_NULL_ID,	CLSID_DICTAPP,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __JAVA_MMI__
{MNU_MAIN_JAVAAMS,         	MNU_MAIN_APPLICATIONS,    TXT_LIL_N_JAVA,      	IMG_NULL_ID,	CLSID_JAVAAMSAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __WAP_MMI__
{MNU_MAIN_WAP_EXPLORER,    	MNU_MAIN_APPLICATIONS,    TXT_LIL_N_CDW_WAP_EXPLORER, IMG_NULL_ID,	CLSID_CDWAPAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __NCCQQ_MMI__
{MNU_MAIN_QQAPPNEW,    	MNU_MAIN_APPLICATIONS,    TXT_LIL_N_QQ, IMG_NULL_ID,	CLSID_QQAPP,		0,	ITEM_VISABLE_MASK, {0}},
#endif //__NCCQQ_MMI__

//game
#if defined(__GAME_ENGINE_EMU_MMI__)
{MNU_MAIN_EMU,    					MNU_MAIN_GAMES,    		TXT_LIL_N_EMU_GAMES, IMG_NULL_ID,	CLSID_EMUAPP,			0,	ITEM_VISABLE_MASK, {0}},
#endif
#if (defined(__GOGOBOX_GAME__))
{MNU_MAIN_GOGOBOX,			  MNU_MAIN_GAMES,			TXT_LIL_N_GOGOBOXGAME,	IMG_NULL_ID,	CLSID_GOGOBOXGAME,		0,			ITEM_VISABLE_MASK, {0}},
#endif
//Tools
#ifdef __APP_MMI_CALCULATOR__
{MNU_MAIN_CALCULATOR, 			MNU_MAIN_TOOLS, 		TXT_LIL_N_CALCULATOR, 		IMG_NULL_ID,	CLSID_CALCULATORAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_CALCULATOR_PLUS__
{MNU_MAIN_CALCULATOR, 			MNU_MAIN_TOOLS, 		TXT_LIL_N_CALCULATOR, 		IMG_NULL_ID,	CLSID_CALCULATORPLUSAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_UNITCONVERTER__
{MNU_MAIN_UNIT_CONVERTER,  	MNU_MAIN_TOOLS,    	TXT_LIL_N_CONVERTER, 			IMG_NULL_ID,	CLSID_UNITCONVERTER, 	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_STOPWATCH__
{MNU_MAIN_STOPWATCH,  			MNU_MAIN_TOOLS,    	TXT_LIL_N_STOPWATCH, 			IMG_NULL_ID,	CLSID_STOPWATCHAPP,		0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_COUNTDOWN_TIMER__
{MNU_MAIN_COUNTDOWN_TIMER, 	MNU_MAIN_TOOLS,    	TXT_LIL_N_COUNTDOWN_TIMER,IMG_NULL_ID,	CLSID_COUNTDOWNTIMER, 	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_WORLDCLOCK__
{MNU_MAIN_WORLD_CLOCK,  		MNU_MAIN_TOOLS,    	TXT_LIL_N_WORLD_CLOCK, 		IMG_NULL_ID,	CLSID_WORLDCLOCKAPP,	0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_SHORTCUTLIST__
{MNU_MAIN_SHORTCUTS,  			MNU_MAIN_TOOLS,    	TXT_LIL_N_SHORTCUTS, 			IMG_NULL_ID,	CLSID_SHORTCUTSAPP,		SHORTCUTS_ENTRY_SHORTCUTS,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __BLUETOOTH_MMI__
{MNU_MAIN_BLUETOOTH,  			MNU_MAIN_TOOLS,    	TXT_LTL_N_BLUETOOTH, 			IMG_NULL_ID,	CLSID_BTAPP,			0,		ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __APP_MMI_BMI__
{MNU_MAIN_BMI,  						MNU_MAIN_TOOLS,    	TXT_LIL_N_BMI, 						IMG_NULL_ID,	CLSID_BMI,				0,		ITEM_VISABLE_MASK, {0}},
#endif
{MNU_MAIN_SIM_SERVICE_1,  	MNU_MAIN_TOOLS,   	TXT_NULL_ID,							IMG_NULL_ID,	CLSID_STKAPP,			STKSRV_CMD_SETUPMENU,	ITEM_VISABLE_MASK, {0}},
{MNU_MAIN_SIM_SERVICE_2,  	MNU_MAIN_TOOLS,   	TXT_NULL_ID,							IMG_NULL_ID,	CLSID_STKAPP2,			STKSRV_CMD_SETUPMENU,	ITEM_VISABLE_MASK, {0}},
#ifdef __APP_MMI_EVENTCENTER__
{MNU_MAIN_EVENT_CENTER,  		MNU_MAIN_TOOLS,    	TXT_LIL_N_EVENT_CENTER, 	IMG_NULL_ID,	CLSID_EVTCENTERAPP,		EvtCenterApp_Start_AllEvtSummary,	ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE__
{MNU_MAIN_SXM_VIDEO_CHAT,  	MNU_MAIN_TOOLS,     TXT_OIL2_N_VIDEO_CHAT,                           IMG_NULL_ID,    CLSID_SXM_VCHAT,    0x0300009a, ITEM_VISABLE_MASK, {0}},
#ifdef __SXMENGINE_BOOKSTORE__
{MNU_MAIN_SXM_LIBRARY,     	MNU_MAIN_TOOLS,     TXT_LIL_N_POI_EDUCATION_BOOK_STORE,         IMG_NULL_ID,    CLSID_SXM_BOOK,     0x0300000B, ITEM_VISABLE_MASK, {0}},
#endif
#ifdef __SXMENGINE_GAME__
{MNU_MAIN_SXM_GAMES,       	MNU_MAIN_TOOLS,     TXT_DSL_N_GAME,                             IMG_NULL_ID,    CLSID_SXM_GAME,     0x03000000, ITEM_VISABLE_MASK, {0}},
#endif
#endif

#ifdef __YOUTUBE_MMI_CDWAP__
{MNU_MAIN_YOUTUBE,     MNU_MAIN_APPLICATIONS,    TXT_LIL_N_CDW_YOUTUBE, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_YOUTUBE,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __YOUKU_MMI_CDWAP__
{MNU_MAIN_YOUKU,     MNU_MAIN_APPLICATIONS,    TXT_LIL_N_CDW_YOUKU, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_YOUKU,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __VUCLIP_MMI_CDWAP__
{MNU_MAIN_VUCLIP,     MNU_MAIN_APPLICATIONS,    TXT_LIL_N_CDW_VUCLIP, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_VUCLIP,  ITEM_VISABLE_MASK, {0}},
#endif

#ifdef __BAIDU_MMI_CDWAP__
{MNU_MAIN_BAIDU,     MNU_MAIN_APPLICATIONS,    TXT_LIL_N_BAIDU, IMG_NULL_ID,  CLSID_CDWAPAPP,     CDWAP_OPEN_BAIDU,  ITEM_VISABLE_MASK, {0}},
#endif

};
#endif //__UI_STYLE_MMI_MAIN_MENU_SPIN__

#if defined (__UI_STYLE_MMI_IFONE__) || defined (__UI_STYLE_MMI_STYLE_SWITCH__)
#ifdef __MMI_MAINMENUAPP_IFONESTYLE_C__
const MenuItemModelInfo2_t g_IfoneMenuData[]={   // some applications are disable, should sync with IfoneMenuId_e and MainMenuIfoneTextImgTable
    {TXT_LIL_N_DIAL,					DIALER_MAIN,			MENUTYPE_DIALER,		CLSID_DIALERAPP,            0,          MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_PHONEBOOK,			PHB_MAIN,				MENUTYPE_APPLET,		CLSID_PHBAP,                    0,          MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_MESSAGES,				MESSAGE_MAIN,			MENUTYPE_MESSAGE,		CLSID_MCA,                  0, MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_SETTINGS,				SETTING_MAIN,			MENUTYPE_APPLET,		CLSID_SETTINGAPP,       0,              MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_CALENDAR,				CALENDAR_MAIN,			MENUTYPE_CALENDAR,		CLSID_CALENDARAPP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#ifdef __WAP_MMI_CDWAP__
    {TXT_LIL_N_CDW_WAP_EXPLORER,	CDWAP_MAIN,			MENUTYPE_APPLET,		CLSID_CDWAPAPP,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
    {TXT_LIL_N_PROFILES,				PROFILE_MAIN,			MENUTYPE_APPLET,		CLSID_PROFILEAPP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#if defined(__ENABLE_CAMCORDER__)
    {TXT_LIL_N_CAMCORDER,			DV_MAIN,				MENUTYPE_APPLET,			CLSID_CAMAPP,			CAM_VIDEO_MODE, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#if defined(__ENABLE_CAMERA__)
    {TXT_LIL_N_CAMERA,				DC_MAIN,				MENUTYPE_APPLET,		CLSID_CAMAPP,			CAM_PICTURE_MODE, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
    {TXT_LIL_N_MUSIC,			    		MPLAYER_MAIN,			MENUTYPE_APPLET,		CLSID_MPLAYERAPP,		MPLAYER_MODE_MUSIC, MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_VIDEO_PLAYER,			VPLAYER_MAIN,			MENUTYPE_APPLET,	CLSID_FILEMGRAPP,	FILEMGRAPP_VIDEO_FILE   , MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_PHOTOS,				PHOTO_MAIN,				MENUTYPE_APPLET,			CLSID_FILEMGRAPP,	FILEMGRAPP_PICTURE_FILE, MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_FILE_MANAGER,			FILEMGR_MAIN,			MENUTYPE_APPLET,		CLSID_FILEMGRAPP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_TIME,					TIME_MAIN,				MENUTYPE_APPLET,		CLSID_SETTINGAPP, SETTINGAPType_Time, MAINMENUIFONE_FOLDER_SYSTEM},
    {TXT_LIL_N_CALL_HISTORY,			CALLLOG_MAIN,			MENUTYPE_APPLET,		CLSID_CALLLOGAPP,		MMI_CALLLOG_AP_SHOW_ALL_LIST, MAINMENUIFONE_FOLDER_SYSTEM},
#ifdef __RFID_MMI__
	{TXT_LIL_N_RFID_DEMO,			RFID_MAIN,					MAINMENU_APPLET,		CLSID_RFIDMAINAPP, 0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __JAVA_MMI__
    {TXT_LIL_N_JAVA,					JAVA_MAIN,				MENUTYPE_APPLET,		CLSID_JAVAAMSAPP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_VOICE_MEMO__
    {TXT_LIL_N_VOICE_MEMO,			RECODER_MAIN,			MENUTYPE_APPLET,		CLSID_VOICEMEMOAPP,	0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_FM_RADIO__
        {TXT_LIL_N_FM_RADIO,             FM_MAIN,    MENUTYPE_APPLET,    CLSID_FMRADIOAPP,   0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif //__APP_MMI_FM_RADIO__

#ifdef __MAP_MMI__
    {TXT_LIL_N_MAP,					MAP_MAIN,				MENUTYPE_APPLET,		CLSID_MAPAPP,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __SRE__
	  {MNU_MAIN_SRE,		    TXT_LIL_N_SRE,			    APPICON_SRE,				MENUTYPE_APPLET,	CLSID_SRE,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif /// __SRE__
#ifdef __E_BOOK_MMI__
    {TXT_LIL_N_E_BOOK,				EBOOK_MAIN,				MENUTYPE_APPLET,			CLSID_E_BOOK,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
    {TXT_LIL_N_CONNECT_SETTING,		CONNECTSETTING_MAIN,	MENUTYPE_APPLET,		CLSID_SETTINGAPP,		SETTINGAPType_ConnectSettings, MAINMENUIFONE_FOLDER_SYSTEM},

#ifdef __NCCQQ_MMI__
    {TXT_LIL_N_QQ,                  QQ_MAIN,                MENUTYPE_APPLET,        CLSID_QQAPP,        0, MAINMENUIFONE_FOLDER_SYSTEM},
#else
#ifdef __SKYENGINE__
    {TXT_LIL_N_QQ,					QQ_MAIN,				MENUTYPE_APPLET,		CLSID_SKY_ENGINE_QQ_APP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#endif //__NCCQQ_MMI__

#ifdef __DICTAPP_MMI__
    {TXT_LIL_N_DICT,					DICT_MAIN,				MENUTYPE_APPLET,		CLSID_DICTAPP,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_BMI__
    {TXT_LIL_N_BMI,					BMI_MAIN,				MENUTYPE_APPLET,		CLSID_BMI,				0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __NATIVE_GAME_MMI_BIG2__
	{TXT_LIL_N_BIGTWO,				BIG2_MAIN,				MENUTYPE_APPLET,		CLSID_BIG2,      0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __NATIVE_GAME_MMI_FRUIT__
	{TXT_LIL_N_FRUIT,				FRUIT_MAIN,				    MENUTYPE_APPLET,		CLSID_FRUITGAMBLEGAME,      0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __APP_MMI_SKETCHNOTE__
    {TXT_LIL_N_SKETCH_NOTE,			SNOTE_MAIN,				MENUTYPE_APPLET,		CLSID_SNOTEAPP, 		0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_UNITCONVERTER__
    {TXT_LIL_N_CONVERTER,			CONVERTER_MAIN,			MENUTYPE_APPLET,		CLSID_UNITCONVERTER, 	0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
    {TXT_LIL_N_ALARM,				ALARM_MAIN,				MENUTYPE_APPLET,		CLSID_ALARMAPP,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#ifdef __BLUETOOTH_MMI__
    {TXT_LTL_N_BLUETOOTH,			BLUETOOTH_MAIN,			MENUTYPE_APPLET,		CLSID_BTAPP,			0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_CALCULATOR__
    {TXT_LIL_N_CALCULATOR,			CALCULATOR_MAIN,		MENUTYPE_APPLET,		CLSID_CALCULATORAPP,	0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_CALCULATOR_PLUS__
    {TXT_LIL_N_CALCULATOR,			CALCULATOR_MAIN,		MENUTYPE_APPLET,		CLSID_CALCULATORPLUSAPP,	0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_COUNTDOWN_TIMER__
    {TXT_LIL_N_COUNTDOWN_TIMER,		COUNTDOWN_MAIN,		MENUTYPE_APPLET,		CLSID_COUNTDOWNTIMER, 	0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
    {TXT_LIL_N_WORLD_CLOCK,			WORLDCLOCK_MAIN,	MENUTYPE_APPLET,        CLSID_WORLDCLOCKAPP,	0, MAINMENUIFONE_FOLDER_SYSTEM},
#ifdef __APP_MMI_NOTEPAD__
    {TXT_LIL_N_NOTEPAD,				NOTEPAD_MAIN,		MENUTYPE_APPLET,        CLSID_NOTEPADAPP,       0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_STOPWATCH__
    {TXT_LIL_N_STOPWATCH,			STOPWATCH_MAIN,		MENUTYPE_APPLET,        CLSID_STOPWATCHAPP,		0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __YOUTUBE_MMI_CDWAP__
        {TXT_LIL_N_CDW_YOUTUBE,             YOUTUBE_MAIN,         MENUTYPE_APPLET,        CLSID_CDWAPAPP,         CDWAP_OPEN_YOUTUBE, MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __YOUKU_MMI_CDWAP__
        {TXT_LIL_N_CDW_YOUKU,             YOUKU_MAIN,         MENUTYPE_APPLET,        CLSID_CDWAPAPP,         CDWAP_OPEN_YOUKU, MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __VUCLIP_MMI_CDWAP__
        {TXT_LIL_N_CDW_VUCLIP,             VUCLIP_MAIN,         MENUTYPE_APPLET,        CLSID_CDWAPAPP,         CDWAP_OPEN_VUCLIP, MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __MMI_KING_MOVIE__
#ifdef __MMI_KING_MOVIE_3D_APP_INDIE__
    {TXT_LIL_N_KING_MOVIE,        KINGMOVIE_MAIN,    MENUTYPE_APPLET,     CLSID_FMRADIOAPP,      MAINMENU_SUBMENU_KMV,    MAINMENUIFONE_FOLDER_SYSTEM},
#else
    {TXT_LIL_N_KING_MOVIE,        KINGMOVIE_MAIN,    MENUTYPE_APPLET,     CLSID_KINGMOVIEAPP,     0,        MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#endif

#ifdef __EMAIL_MMI__
    {TXT_LIL_N_EMAIL, EMAIL_MAIN, MENUTYPE_MESSAGE, CLSID_EMAILAPP, 0, MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __APP_MMI_EVENTCENTER__
    {TXT_LIL_N_EVENT_CENTER, EVENT_CENTER_MAIN, MENUTYPE_MESSAGE,  CLSID_EVTCENTERAPP,     EvtCenterApp_Start_AllEvtSummary,   MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __APP_MMI_SHORTCUTLIST__
    {TXT_LIL_N_SHORTCUTS,            SHORT_CUTS_MAIN,        MENUTYPE_APPLET, CLSID_SHORTCUTSAPP,     SHORTCUTS_ENTRY_SHORTCUTS,      MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __APP_MMI_LICENSEMGR__
    {TXT_LIL_N_LICENSEMGR,           LICENSE_MANAGER_MAIN,       MENUTYPE_APPLET,   CLSID_LICENSEMGRAPP,        0,      MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __APP_MMI_AZAN__
    {TXT_LIL_N_AZAN_ALARM,                 AZAN_MAIN,               MENUTYPE_APPLET,  CLSID_AZANAPP,              0,      MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __CALLER_LOCATION__
    {TXT_LIL_N_CALLER_LOCATION,      CALLERLOCATION_MAIN,              MENUTYPE_APPLET,    CLSID_CALLERLOCATIONAPP,                0,      MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __ATV_MMI__
#ifdef __ATV_CMMB__
    {TXT_LIL_N_CMMB,                          ATV_MAIN,                 MENUTYPE_APPLET,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_CMMB,        MAINMENUIFONE_FOLDER_SYSTEM},
#else // !__ATV_CMMB__
    {TXT_LIL_N_ATV,                          ATV_MAIN,                  MENUTYPE_APPLET,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ANALOG,      MAINMENUIFONE_FOLDER_SYSTEM},
#ifdef __ATV_ISDBT__
    {TXT_LIL_N_ISDBT,                    ISDBTV_MAIN,                MENUTYPE_APPLET,    CLSID_ATVAPP,           TVSRV_TV_HYBRID_ISDBT,       MAINMENUIFONE_FOLDER_SYSTEM},
#endif // __ATV_ISDBT__
#endif // __ATV_CMMB__
#endif // __ATV_MMI__

#ifdef __APP_MMI_TUDOU__
    {TXT_CCL_N_COMMON_TUDOU,                          TUDOU_MAIN,                  MENUTYPE_APPLET,    CLSID_TUDOUAPP,           0,      MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __APP_MMI_TODOLIST__
    {TXT_LTL_N_TODO_LIST,                 TODOLIST_MAIN,        MENUTYPE_APPLET,  CLSID_TODOLISTAPP,     0,    MAINMENUIFONE_FOLDER_SYSTEM},
#endif

    //Game
#if defined(__GAME_ENGINE_EMU_MMI__)
    {TXT_LIL_N_EMU_GAMES,                      GAME_MAIN,        MENUTYPE_APPLET, CLSID_EMUAPP,           0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __SKYENGINE__
    {TXT_LIL_N_GAMES,     SKY_MAIN,            MENUTYPE_APPLET,   CLSID_SKY_ENGINE_GAME_APP,      1,                      MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#if (defined(__GOGOBOX_GAME__))
    {TXT_LIL_N_GOGOBOXGAME,            GOGOBOX_MAIN,  MENUTYPE_APPLET,   CLSID_GOGOBOXGAME,      0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef  __NATIVE_GAME_MMI_PACMAN__
    {TXT_LIL_N_PACMAN,             PACMAN_MAIN,   MENUTYPE_APPLET,   CLSID_PACMAN,       0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef  __NATIVE_GAME_MMI_PUZZLE__
    {TXT_LIL_N_PUZZLE,             PUZZLE_MAIN,   MENUTYPE_APPLET,    CLSID_PUZZLEAPP,        0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef  __NATIVE_GAME_MMI_HAMSTERFIGHT__
    {TXT_LIL_N_HAMSTERFIGHT,           HAMSTERFIGHT_MAIN, MENUTYPE_APPLET,  CLSID_HAMSTERFIGHTAPP,      0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef  __NATIVE_GAME_MMI_LINKUP__
    {TXT_LIL_N_LINKUP,             LINKUP_MAIN,   MENUTYPE_APPLET,    CLSID_LINKUPAPP,        0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef  __NATIVE_GAME_MMI_GOBANG__
    {TXT_LIL_N_GOBANG,             GOBANG_MAIN,   MENUTYPE_APPLET,    CLSID_GOBANGAPP,        0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef  __NATIVE_GAME_MMI_SOKOBAN__
    {TXT_LIL_N_SOKOBAN,            SOKOBAN_MAIN,  MENUTYPE_APPLET,   CLSID_SOKOBANAPP,       0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef  __NATIVE_GAME_MMI_SUDOKU__
    {TXT_LIL_N_SUDOKU,             SUDOKU_MAIN,   MENUTYPE_APPLET,    CLSID_SUDOKUAPP,        0,          MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __TENCENT_MCARE__
    {TXT_LIL_N_QQ,                QQ_MAIN,           MENUTYPE_APPLET,   CLSID_TENCENT_MCARE,        0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif
#ifdef __ZYUE_ENGINE__//TXT_LIL_N_ZHANGYUE_APP
    {TXT_LIL_N_ZHANGYUE_EBOOK,     ZHANGYUE_EBOOK_MAIN,            MENUTYPE_APPLET,    CLSID_3RD_ZHANGYUE_EBOOK,        1,                        MAINMENUIFONE_FOLDER_SYSTEM},
#endif

#ifdef __ZMOL__
    {TXT_LIL_N_ZMOLAPP, ZMOLAPP_MAIN,  MENUTYPE_APPLET,   CLSID_ZMOL_APP, 0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif


#ifdef __MMI_SEARCH_APP__
    {TXT_LTL_N_SEARCH,               SEARCH_MAIN,           MENUTYPE_APPLET,    CLSID_SEARCHAPP,        0,  MAINMENUIFONE_FOLDER_SYSTEM},
#endif

{TXT_NULL_ID,   STK_MAIN,		MENUTYPE_APPLET,	CLSID_STKAPP,			STKSRV_CMD_SETUPMENU,	MAINMENUIFONE_FOLDER_SYSTEM},
{TXT_NULL_ID,   STK_MAIN,		MENUTYPE_APPLET,	CLSID_STKAPP2,			STKSRV_CMD_SETUPMENU,	MAINMENUIFONE_FOLDER_SYSTEM},


};
#else
extern const MenuItemModelInfo2_t g_IfoneMenuData[];
#endif
#define MAINMENUIFONE_SYSTEMMENUITEM_NUM (sizeof(g_IfoneMenuData)/sizeof(MenuItemModelInfo2_t))
#endif
#endif
