#-------------------------------------------------------------------------------
#	${Variable} is generated by script and $(variable) is manually maintained.
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
#	Description of some variables owned by the library
#-------------------------------------------------------------------------------
# Library module (lib) or Binary module (bin)
PROCESS = lib

PATH_C +=\
    $(PATH_core_application_mmpd_vid_play)/src\

PATH_H += \
    $(PATH_core_application_mmpd_audio)/inc\
    $(PATH_core_application_mmpd_system)/inc\
    $(PATH_core_application_mmpd_vid_play)/inc\
    $(PATH_core_application_mmpd_display)/inc\
    $(PATH_core_application_mmph)/inc\
    $(PATH_core_application_mmps_audio)/inc\
    $(PATH_core_application_mmps_vid_play)/inc\
    $(PATH_core_application_mmps_display)/inc\
    $(PATH_core_driver_bsp)/inc\
    $(PATH_core_driver_common)/inc\
    $(PATH_core_include_application)\
    $(PATH_core_include_display)\
    $(PATH_core_include_img_pipe)\
    $(PATH_core_include_misc)\
    $(PATH_core_system_host_if)/inc\
    $(PATH_core_system_os)/inc\
    $(PATH_core_system_vid_play)/inc\
    $(PATH_core_system_vid_play_inc_parser)\
    $(PATH_project_Dvr_CarDV_SDK_cfg_core)/inc\
#-------------------------------------------------------------------------------
#	List of source files of the library or executable to generate
#-------------------------------------------------------------------------------
SRC_C_LIST =\
    mmpd_3gpparser.c \
    mmpd_aviparser.c \
    mmpd_h264dec.c \
    mmpd_mkvparser.c \
    mmpd_mp4vdec.c \
    mmpd_rmparser.c \
    mmpd_tsparser.c \
    mmpd_vidplayer.c \
