#ifndef __MMI_CALLERLOCATIONAPP_ID_H__
#define __MMI_CALLERLOCATIONAPP_ID_H__


typedef enum
{
    CALLERLOCATIONAPP_WND_MAIN = WND_ID_APP_BASE,
    CALLERLOCATIONAPP_WND_QUERY,
    CALLERLOCATIONAPP_WND_UPDATE,
    CALLERLOCATIONAPP_WND_SETTING,    
    CALLERLOCATIONAPP_WND_HELP,
} CallerLocationWndId_e;

typedef enum
{
    MNU_CALLERLOCATION_MAIN_MENU = 0,
    MNU_CALLERLOCATION_QUERY,
    MNU_CALLERLOCATION_UPDATE,
    MNU_CALLERLOCATION_DISPLAY_STATUS,
    MNU_CALLERLOCATION_HELP,
}CallerLocationMenuId_e;

enum
{
    CALLERLOCATIONAPP_VIEW_BEGIN = APP_WDG_START,
    CALLERLOCATIONAPP_QUERY_INPUTLABLEWIDGET,
    CALLERLOCATIONAPP_QUERY_INPUTWIDGET,
    CALLERLOCATIONAPP_QUERY_RESULTLABLEWIDGET,
    CALLERLOCATIONAPP_QUERY_RESULTWIDGET,    
    CALLERLOCATIONAPP_HELP_STRINGWIDGET,    
};



#endif //__MMI_TRACKERSMSAPP_ID_H__

