#ifndef MCR_ERRORDEF_H
#define MCR_ERRORDEF_H

#ifdef __cplusplus   
extern "C"{   
#endif // __cplusplus


/* Í¨ÓÃ´íÎóºÅ */
#define MCRBASEERR								(10000)
#define MCRBASEERR_SUCCESS						(MCRBASEERR)
#define MCRBASEERR_FAILED						(MCRBASEERR + 1)
#define MCRBASEERR_NO_MEMORY					(MCRBASEERR + 2)
#define MCRBASEERR_BAD_PARAM					(MCRBASEERR + 3)
#define MCRBASEERR_BAD_STATE					(MCRBASEERR + 4)
#define MCRBASEERR_BAD_TIME						(MCRBASEERR + 5)
#define MCRBASEERR_BAD_DATE						(MCRBASEERR + 6)
#define MCRBASEERR_BAD_HANDLE					(MCRBASEERR + 7)
#define MCRBASEERR_BAD_DATA						(MCRBASEERR + 8)
#define MCRBASEERR_NOT_FOUND					(MCRBASEERR + 9)
#define MCRBASEERR_NOT_READY					(MCRBASEERR + 10)
#define MCRBASEERR_NOT_SUPPORT					(MCRBASEERR + 11)
#define MCRBASEERR_OVERFLOW						(MCRBASEERR + 12)
#define MCRBASEERR_ALREADY_EXIST				(MCRBASEERR + 13)
#define MCRBASEERR_IN_USE						(MCRBASEERR + 14)
#define MCRBASEERR_BUSY							(MCRBASEERR + 15)
#define MCRBASEERR_TIME_OUT						(MCRBASEERR + 16)
#define MCRBASEERR_ABORT						(MCRBASEERR + 17)
#define MCRBASEERR_TOO_BIG						(MCRBASEERR + 18)
#define MCRBASEERR_TOO_SMALL					(MCRBASEERR + 19)
#define MCRBASEERR_PARITY						(MCRBASEERR + 20)
#define MCRBASEERR_CORRUPTED					(MCRBASEERR + 21)
#define MCRBASEERR_GENERAL						(MCRBASEERR + 22)
#define MCRBASEERR_UNKNOWN						(MCRBASEERR + 23)
#define MCRBASEERR_RETRY_TOO_MANY				(MCRBASEERR + 24)
#define MCRBASEERR_BUFFER_EMPTY					(MCRBASEERR + 25)
#define MCRBASEERR_BUFFER_FULL					(MCRBASEERR + 26)


/* FS´íÎóºÅ */
#define MCRFSERR								(10100)
#define MCRFSERR_FS_NOT_FOUND					(MCRFSERR)
#define MCRFSERR_FS_ALREADY_EXIST				(MCRFSERR + 1)
#define MCRFSERR_FS_LOCKED						(MCRFSERR + 2)
#define MCRFSERR_FS_ALREADY_OPENED				(MCRFSERR + 3)
#define MCRFSERR_BAD_ATTR						(MCRFSERR + 4)
#define MCRFSERR_BAD_PATH						(MCRFSERR + 5)
#define MCRFSERR_BAD_FSNAME						(MCRFSERR + 6)
#define MCRFSERR_BAD_FS_EXT						(MCRFSERR + 7)
#define MCRFSERR_BAD_POSITION					(MCRFSERR + 8)
#define MCRFSERR_BAD_DRIVE						(MCRFSERR + 9)
#define MCRFSERR_DISK_FULL						(MCRFSERR + 10)
#define MCRFSERR_END_OF_FILE					(MCRFSERR + 11)
#define MCRFSERR_OPEN							(MCRFSERR + 12)
#define MCRFSERR_CLOSE							(MCRFSERR + 13)
#define MCRFSERR_READ							(MCRFSERR + 14)
#define MCRFSERR_WRITE							(MCRFSERR + 15)
#define MCRFSERR_RENAME							(MCRFSERR + 16)
#define MCRFSERR_COPY							(MCRFSERR + 17)
#define MCRFSERR_MOVE							(MCRFSERR + 18)
#define MCRFSERR_DELETE							(MCRFSERR + 19)
#define MCRFSERR_CREATE							(MCRFSERR + 20)


/* ÍøÂç´íÎóºÅ */
#define MCRNETERR								(10200)
#define MCRNETERR_END_OF_FILE					(MCRNETERR)
#define MCRNETERR_WOULD_BLOCK					(MCRNETERR + 1)
#define MCRNETERR_CANNOT_CONNECT				(MCRNETERR + 2)
#define MCRNETERR_CANNOT_DISCONNECT				(MCRNETERR + 3)
#define MCRNETERR_BAD_DOMAIN					(MCRNETERR + 4)
#define MCRNETERR_BAD_IP						(MCRNETERR + 5)
#define MCRNETERR_BAD_URL						(MCRNETERR + 6)
#define MCRNETERR_BAD_PORT						(MCRNETERR + 7)
#define MCRNETERR_BAD_MAC						(MCRNETERR + 8)
#define MCRNETERR_BAD_PACKET					(MCRNETERR + 9)
#define MCRNETERR_BAD_DATA						(MCRNETERR + 10)
#define MCRNETERR_BAD_RESPONSE					(MCRNETERR + 11)
#define MCRNETERR_BAD_REQUEST					(MCRNETERR + 12)
#define MCRNETERR_CONNECTION_DOWN				(MCRNETERR + 13)
#define MCRNETERR_CONNECTION_EXIST				(MCRNETERR + 14)
#define MCRNETERR_CONNECTION_REFUSED			(MCRNETERR + 15)
#define MCRNETERR_CANNOT_RESOLVED				(MCRNETERR + 16)
#define MCRNETERR_SHUTDOWN						(MCRNETERR + 17)
#define MCRNETERR_OPENING						(MCRNETERR + 18)
#define MCRNETERR_CONNECTING					(MCRNETERR + 19)
#define MCRNETERR_DISCONNECTING					(MCRNETERR + 20)
#define MCRNETERR_CLOSING						(MCRNETERR + 21)
#define MCRNETERR_READING						(MCRNETERR + 22)
#define MCRNETERR_WRITING						(MCRNETERR + 23)


/* SOCKET´íÎóºÅ*/
#define MCRSOCKERR								(10300)
#define MCRSOCKERR_CREATE						(MCRSOCKERR + 1)
#define MCRSOCKERR_CLOSE						(MCRSOCKERR + 2)
#define MCRSOCKERR_OPEN							(MCRSOCKERR + 3)
#define MCRSOCKERR_EXIST						(MCRSOCKERR + 4)
#define MCRSOCKERR_READING						(MCRSOCKERR + 5)
#define MCRSOCKERR_WRITING						(MCRSOCKERR + 6)


/* GDI´íÎóºÅ */
#define MCRGDIERR								(10400)
#define MCRGDIERR_BAD_POINT						(MCRGDIERR + 1)
#define MCRGDIERR_BAD_LINE						(MCRGDIERR + 2)
#define MCRGDIERR_BAD_CIRCLE					(MCRGDIERR + 3)
#define MCRGDIERR_BAD_RECT						(MCRGDIERR + 4)
#define MCRGDIERR_BAD_AREA						(MCRGDIERR + 5)
#define MCRGDIERR_BAD_SIZE						(MCRGDIERR + 6)
#define MCRGDIERR_BAD_TEXT						(MCRGDIERR + 7)
#define MCRGDIERR_BAD_FONT						(MCRGDIERR + 8)
#define MCRGDIERR_BAD_COLOR						(MCRGDIERR + 9)
#define MCRGDIERR_BAD_STYLE						(MCRGDIERR + 10)
#define MCRGDIERR_OVERLAPPED					(MCRGDIERR + 11)


/* AUDIO´íÎóºÅ*/
#define MCRAUDIOERR								(10500)


/* VIDEO´íÎóºÅ*/
#define MCRVIDEOERR								(10600)


/* SOUND´íÎóºÅ*/
#define MCRSOUNDERR								(10700)


/* IMAGE´íÎóºÅ*/
#define MCRIMAGEERR								(10800)


/* CAMERA´íÎóºÅ*/
#define MCRCAMERAERR							(10900)


/* PROTOCOL´íÎóºÅ*/
#define MCRPROTOCOLERR							(11000)
#define MCRPROTOCOLERR_BAD_VERSION				(MCRPROTOCOLERR)
#define MCRPROTOCOLERR_BAD_LENGTH				(MCRPROTOCOLERR + 1)
#define MCRPROTOCOLERR_BAD_TYPE					(MCRPROTOCOLERR + 2)
#define MCRPROTOCOLERR_BAD_ID					(MCRPROTOCOLERR + 3)
#define MCRPROTOCOLERR_BAD_SESSION				(MCRPROTOCOLERR + 4)
#define MCRPROTOCOLERR_BAD_TOKEN				(MCRPROTOCOLERR + 5)
#define MCRPROTOCOLERR_BAD_FORMAT				(MCRPROTOCOLERR + 6)
#define MCRPROTOCOLERR_BAD_VALUE				(MCRPROTOCOLERR + 7)
#define MCRPROTOCOLERR_CANNOT_DECODE			(MCRPROTOCOLERR + 8)
#define MCRPROTOCOLERR_CANNOT_ENCODE			(MCRPROTOCOLERR + 9)

//last mcare state
#define MCR_STATE_BEFORE_EXEC       (10) //before mcare exit
#define MCR_STATE_READY_EXEC        (19) //mcare is ready
#define MCR_APP_STATE_BEFORE_EXEC   (20) //before app exit
#define MCR_APP_STATE_NORMAL_EXIT   (30) //app normal exit
#define MCR_STATE_NORMAL_EXIT       (40) //normal exit


#ifdef __cplusplus   
}   
#endif // __cplusplus
#endif // MCR_ERRORDEF_H
