#ifndef __MMI_WORLDCLOCKAPP_ID_H__
#define __MMI_WORLDCLOCKAPP_ID_H__

typedef enum
{
    WORLDCLOCKAPP_WND_MAIN = WND_ID_APP_BASE,
#if defined(__3D_UI_IDLE_MULTIPAGE__)
    WORLDCLOCKAPP_WND_LIST,
#endif
} WorldClockAppWndId_e;

enum
{
    WORLDCLOCKAPP_VIEW_BEGIN = APP_WDG_START,
    WORLDCLOCKAPP_MAP_BG_IMAGEWIDGET,
    WORLDCLOCKAPP_LINE_IMAGEWIDGET,
    WORLDCLOCKAPP_CITY_IMAGEWIDGET,
    WORLDCLOCKAPP_TZ_TEXTWIDGET,
    WORLDCLOCKAPP_TIME_TEXTWIDGET,
};

#endif //__MMI_WORLDCLOCKAPP_ID_H__

