ApBegin(RS,CLSID_WORLDCLOCKAPP)
    WndBegin(WORLDCLOCKAPP_WND_MAIN)

        WndSetTitleRC({ IMG_NULL_ID,TXT_LTL_N_WORLD_CLOCK} )

        WdgBegin(CLSID_IMAGEWIDGET,MapBgImageWdg)
            WdgImageCreateForWndRC({{WORLDCLOCKAPP_MAP_BG_XPOS,WORLDCLOCKAPP_MAP_BG_YPOS},{WORLDCLOCKAPP_MAINVIEW_WIDTH,WORLDCLOCKAPP_MAP_BG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,TOOLS_WORLDCLOCK_IMG_BG}})
            WdgImageSetDataByIDRC(TOOLS_WORLDCLOCK_IMG_BG)
        WdgEnd(CLSID_IMAGEWIDGET,MapBgImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,LineImageWdg)
            WdgImageCreateForWndRC({{0,0},{WORLDCLOCKAPP_LINE_IMG_WIDTH,WORLDCLOCKAPP_LINE_IMG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,TOOLS_WORLDCLOCK_IMG_LINE}})
            WdgImageSetDataByIDRC(TOOLS_WORLDCLOCK_IMG_LINE)
        WdgEnd(CLSID_IMAGEWIDGET,LineImageWdg)

        WdgBegin(CLSID_IMAGEWIDGET,CityImageWdg)
            WdgImageCreateForWndRC({{0,0},{WORLDCLOCKAPP_CITY_IMG_WIDTH,WORLDCLOCKAPP_CITY_IMG_HEIGHT},IMAGE_STYLE_COMMON,{FALSE,TOOLS_WORLDCLOCK_IMG_CITY}})
            WdgImageSetDataByIDRC(TOOLS_WORLDCLOCK_IMG_CITY)
        WdgEnd(CLSID_IMAGEWIDGET,CityImageWdg)

        WdgBegin(CLSID_TEXTWIDGET,TzTextWdg)
            WdgTextCreateForWndRC({{WORLDCLOCKAPP_TZ_XPOS,WORLDCLOCKAPP_TZ_YPOS},{WORLDCLOCKAPP_MAINVIEW_WIDTH,WORLDCLOCKAPP_TZ_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_COMMON_COLOR_LIST_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,TzTextWdg)

        WdgBegin(CLSID_TEXTWIDGET,TimeTextWdg)
            WdgTextCreateForWndRC({{WORLDCLOCKAPP_TIME_XPOS,WORLDCLOCKAPP_TIME_YPOS},{WORLDCLOCKAPP_MAINVIEW_WIDTH,WORLDCLOCKAPP_TIME_HEIGHT},TEXT_STYLE_COMMON})
            WdgTextSetDataByIDRC(TXT_NULL_ID)
            WdgCommonSetFontCategoryRC(FONT_CAT_NORMAL)
            WdgCommonSetTextColorRC(DEF_THM_COMMON_COLOR_LIST_TEXT)
            WdgCommonSetAlignmentRC(ALIGN_H_CENTER)
        WdgEnd(CLSID_TEXTWIDGET,TimeTextWdg)
    WndEnd(WORLDCLOCKAPP_WND_MAIN)
ApEnd(RS,CLSID_WORLDCLOCKAPP)

